commands
commandc93610dc3aebb645bec6eb824792657c
	<command>

	^ (Dictionary newFrom: {
(#className -> #ViQueryCommand).
(#definition -> #'afd86e99-aa29-7e41-ad95-b40388cb2cde').
(#iconCode -> 'nil').
(#id -> #'c93610dc-3aeb-b645-bec6-eb824792657c').
(#label -> 'Run failures').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 February 2014 2:20:02 pm')
}))
})