commands
commandc6d3ac2885f2324a872510d7a20cab86
	<command>

	^ ((Dictionary new) add: (#definition->#'8739979f-8b09-c347-b65a-39e7e63faa3a'); add: (#class->ViQueryCommand); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'7 February 2014 2:31:54 pm'); yourself)); add: (#id->#'c6d3ac28-85f2-324a-8725-10d7a20cab86'); add: (#iconCode->'UiFugueIcons arrow315Icon'); add: (#label->'Through'); yourself)