commands
command7c36df21eb06d842b04108f05ab93e93
	<command>

	^ (Dictionary newFrom: {
(#className -> #ViQueryCommand).
(#definition -> #'0d03c64f-bdac-5644-9771-2e467ce0a48e').
(#iconCode -> 'nil').
(#id -> #'7c36df21-eb06-d842-b041-08f05ab93e93').
(#label -> 'Run profiled').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 February 2014 2:12:06 pm')
}))
})