commands
command3d357a8bbafe604a94badc2941e88623
	<command>

	^ (Dictionary newFrom: {
(#class -> ViQueryCommand).
(#definition -> #'c0ce300c-864b-7b4f-9870-4bfbf0efa5ff').
(#iconCode -> 'UiFugueIcons controlIcon').
(#id -> #'3d357a8b-bafe-604a-94ba-dc2941e88623').
(#label -> 'Resume').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '10 February 2014 3:37:34 pm')}))})