commands
commandbc70b4363a1c15468c932a855c00522d
	<command>

	^ ((Dictionary new) add: (#definition->#'78f345f7-529f-5547-b19f-f5235365bce2'); add: (#class->ViQueryCommand); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 May 2014 7:13:25 pm'); yourself)); add: (#id->#'bc70b436-3a1c-1546-8c93-2a855c00522d'); add: (#iconCode->'nil'); add: (#label->'Clean up'); yourself)