commands
commandc49de43560650547ac1d1d78cb3cb0fb
	<command>

	^ (Dictionary newFrom: {
(#class -> ViQueryCommand).
(#definition -> #'370f1a4a-5473-454e-96c9-b6249cdcd8d9').
(#iconCode -> 'UiFugueIcons arrowStepIcon').
(#id -> #'c49de435-6065-0547-ac1d-1d78cb3cb0fb').
(#label -> 'Into').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '7 February 2014 2:30:21 pm')}))})