commands
command7c36df21eb06d842b04108f05ab93e93
	<command>

	^ ((Dictionary new) add: (#definition->#'0d03c64f-bdac-5644-9771-2e467ce0a48e'); add: (#class->ViQueryCommand); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 February 2014 2:12:06 pm'); yourself)); add: (#id->#'7c36df21-eb06-d842-b041-08f05ab93e93'); add: (#iconCode->'nil'); add: (#label->'Run profiled'); yourself)