commands
commandfc22f15fedd2654bb9cf4162ea360191
	<command>

	^ ((Dictionary new) add: (#definition->#'8aa25254-91af-8d40-b807-ff135c771e98'); add: (#class->ViQueryCommand); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 February 2014 2:22:36 pm'); yourself)); add: (#id->#'fc22f15f-edd2-654b-b9cf-4162ea360191'); add: (#iconCode->'nil'); add: (#label->'Run errors'); yourself)