commands
commandd811a72faf5db5469bb9b0df038ec7f7
	<command>

	^ (Dictionary newFrom: {
(#class -> ViQueryCommand).
(#definition -> #'60c838c8-d1a1-7d4c-a00f-3210018bcdaa').
(#iconCode -> 'UiSilkIcons databaseRefreshIcon').
(#id -> #'d811a72f-af5d-b546-9bb9-b0df038ec7f7').
(#label -> 'Update Archive').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '10 February 2014 4:42:04 pm')}))})