commands
command6f2a858ad1ec5f40a08438c8528d3b2f
	<command>

	^ ((Dictionary new) add: (#definition->#'f580aabf-2330-cf4a-a12c-a6207b1c8a93'); add: (#class->ViQueryCommand); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 February 2014 1:59:57 pm'); yourself)); add: (#id->#'6f2a858a-d1ec-5f40-a084-38c8528d3b2f'); add: (#iconCode->'nil'); add: (#label->'Debug'); yourself)