commands
commandc49de43560650547ac1d1d78cb3cb0fb
	<command>

	^ ((Dictionary new) add: (#definition->#'370f1a4a-5473-454e-96c9-b6249cdcd8d9'); add: (#class->ViQueryCommand); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'7 February 2014 2:30:21 pm'); yourself)); add: (#id->#'c49de435-6065-0547-ac1d-1d78cb3cb0fb'); add: (#iconCode->'UiFugueIcons arrowStepIcon'); add: (#label->'Into'); yourself)