commands
command81bfe1b01618de48a67d8913eb4b4564
	<command>

	^ (Dictionary newFrom: {
(#class -> ViQueryCommand).
(#definition -> #'690e8c35-7eef-244c-85c1-020bccc1243e').
(#iconCode -> 'UiFugueIcons controlStopSquareIcon').
(#id -> #'81bfe1b0-1618-de48-a67d-8913eb4b4564').
(#label -> 'Terminate').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '10 February 2014 3:50:17 pm')}))})