commands
command93bc2c1d521151468b304317d085c09d
	<command>

	^ (Dictionary newFrom: {
(#className -> #ViQueryCommand).
(#definition -> #'4dcfff32-64f3-a54d-955e-faab62251b7d').
(#iconCode -> 'UiFugueIcons arrowStepOverIcon').
(#id -> #'93bc2c1d-5211-5146-8b30-4317d085c09d').
(#label -> 'Over').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '7 February 2014 2:29:31 pm')
}))
})