commands
command94f658350c5e014ea42c2408e26ff3b2
	<command>

	^ (Dictionary newFrom: {
(#className -> #ViQueryCommand).
(#definition -> #'e75b2027-7d4f-e24d-8ad3-4f7a91ea05e6').
(#iconCode -> 'UiSilkIcons cogIcon').
(#id -> #'94f65835-0c5e-014e-a42c-2408e26ff3b2').
(#label -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '6 June 2014 11:30:26 am')
}))
})