commands
command4fea03ad94df94469c816ac378d2d0e5
	<command>

	^ (Dictionary newFrom: {
(#className -> #ViQueryCommand).
(#definition -> #'c1709374-1f27-5d45-9131-8defe81a40da').
(#iconCode -> 'nil').
(#id -> #'4fea03ad-94df-9446-9c81-6ac378d2d0e5').
(#label -> 'Run Selected').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 February 2014 1:06:19 pm')
}))
})