commands
commandc6d3ac2885f2324a872510d7a20cab86
	<command>

	^ (Dictionary newFrom: {
(#className -> #ViQueryCommand).
(#definition -> #'8739979f-8b09-c347-b65a-39e7e63faa3a').
(#iconCode -> 'UiFugueIcons arrow315Icon').
(#id -> #'c6d3ac28-85f2-324a-8725-10d7a20cab86').
(#label -> 'Through').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '7 February 2014 2:31:54 pm')
}))
})