definitions
def0fee1e3fc9f89042b64688feee2a13c8
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | obj value identityHash]).
(#class -> ViQueryMapDefinition).
(#id -> #'0fee1e3f-c9f8-9042-b646-88feee2a13c8').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '8 November 2013 4:10:44 pm')})).
(#sourceCode -> '[:obj | obj value identityHash]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})