definitions
def007df436f9d47e4e9bed200cbef6b4d0
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:def | #text -> (  ViLabelService doObject: def outputKind ) ]).
(#class -> ViQueryMapDefinition).
(#id -> #'007df436-f9d4-7e4e-9bed-200cbef6b4d0').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '3 September 2013 1:58:21 pm')})).
(#sourceCode -> '[:def | #text -> (  ViLabelService doObject: def outputKind ) ].').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})