definitions
def07db93e49707644c8344528719c82bd1
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 February 2014 4:24:55 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'07db93e4-9707-644c-8344-528719c82bd1'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:sysO | sysO categories collect: [:cat | cat -> sysO]]'); add: (#mapType->#each); add: (#block->[:sysO | sysO categories collect: [:cat | cat -> sysO]]); yourself)