definitions
def0c8f9b64ae239e4ab4c87fbd8f29d864
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | in ifNotEmpty: [out add: [#outline] value]]).
(#class -> ViScriptDefinition).
(#id -> #'0c8f9b64-ae23-9e4a-b4c8-7fbd8f29d864').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '9 December 2015 10:14:14 am')})).
(#sourceCode -> '[:in :out | in ifNotEmpty: [out add: [#outline] value]]')})