definitions
def0731793ad6b75d488e1b92baf48768d7
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | out add: [#groups] value]).
(#class -> ViQueryStepDefinition).
(#id -> #'0731793a-d6b7-5d48-8e1b-92baf48768d7').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '29 May 2018 9:10:14 am')})).
(#sourceCode -> '[:in :out | out add: [#groups] value]')})