definitions
def0f8f45f9a0ccc34a9b8f6d1a4f00e403
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:spec | SystemNavigation default allAccessesTo: spec key from: spec value]).
(#class -> ViQueryMapDefinition).
(#id -> #'0f8f45f9-a0cc-c34a-9b8f-6d1a4f00e403').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '15 November 2014 4:10:06 pm')})).
(#sourceCode -> '[:spec | SystemNavigation default allAccessesTo: spec key from: spec value]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})