definitions
def03349ae00dabb9448a12e55a675ab325
	<definition>

	^ (Dictionary newFrom: {
(#block -> [PackageOrganizer default]).
(#class -> ViQueryMapDefinition).
(#id -> #'03349ae0-0dab-b944-8a12-e55a675ab325').
(#inputKind -> Object).
(#mapType -> #all).
(#outputKind -> PackageOrganizer).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 1:09:51 pm')})).
(#sourceCode -> '[PackageOrganizer default]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})