definitions
def0ffa7f9adf28b24e9fe90a8bcfefe2d9
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:step | #text -> step references size]).
(#class -> ViQueryMapDefinition).
(#id -> #'0ffa7f9a-df28-b24e-9fe9-0a8bcfefe2d9').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '23 July 2014 2:46:54 pm')})).
(#sourceCode -> '[:step | #text -> step references size]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})