definitions
def0534dd08f5ca4d49999fbef1399e3364
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | out addAll: ([:selectors | selectors] value: in)]).
(#class -> ViScriptDefinition).
(#id -> #'0534dd08-f5ca-4d49-999f-bef1399e3364').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 September 2013 7:22:26 pm')})).
(#sourceCode -> '[:in :out | out addAll: ([:selectors | selectors] value: in)]')})