definitions
def055d25a7a9771a44990bd742711caaf1
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | out add: [#'494bc6a5-c09d-fc4f-b22f-37955f890e49'] value]).
(#class -> ViQueryStepDefinition).
(#id -> #'055d25a7-a977-1a44-990b-d742711caaf1').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:12.824834 pm')})).
(#sourceCode -> '[:in :out | out add: [#''494bc6a5-c09d-fc4f-b22f-37955f890e49''] value]')})