definitions
def042fe8279b71854d84137f5befe2d4a5
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | in ifNotEmpty: [out add: [#outline] value]]).
(#class -> ViQueryStepDefinition).
(#id -> #'042fe827-9b71-854d-8413-7f5befe2d4a5').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '9 December 2015 10:48:47 am')})).
(#sourceCode -> '[:in :out | in ifNotEmpty: [out add: [#outline] value]]')})