definitions
def0359b0f142e5ef4cb9933022fe9fa515
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:dirs | dirs gather: [:dir | dir entries]]).
(#class -> ViQueryMapDefinition).
(#id -> #'0359b0f1-42e5-ef4c-b993-3022fe9fa515').
(#inputKind -> FileDirectory).
(#mapType -> #all).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:dirs | dirs gather: [:dir | dir entries]]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})