definitions
def0bc0ce7e2194504ab60b9cd9c19cef01
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj1 :obj2 | obj1 timeStamp >= obj2 timeStamp]).
(#class -> ViQueryMapDefinition).
(#id -> #'0bc0ce7e-2194-504a-b60b-9cd9c19cef01').
(#inputKind -> Object).
(#mapType -> #twoArgs).
(#outputKind -> Boolean).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:obj1 :obj2 | obj1 timeStamp >= obj2 timeStamp]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})