definitions
def0d9c1713c12c064eb583ff4df2c3f4de
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | [#groupsUnsorted] value in: [:result |
	out addAll: result asList]]).
(#class -> ViQueryStepDefinition).
(#id -> #'0d9c1713-c12c-064e-b583-ff4df2c3f4de').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '15 June 2015 10:01:59 am')})).
(#sourceCode -> '[:in :out | [#groupsUnsorted] value in: [:result |
	out addAll: result asList]]')})