definitions
def058d3529d310e847b148dadf47ff31b9
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 February 2014 4:06:47 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'058d3529-d310-e847-b148-dadf47ff31b9'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:class | class name]'); add: (#mapType->#each); add: (#block->[:class | class name]); yourself)