definitions
def0c53b73c4e161542b40ccd76a3b1dda5
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | {
	#text -> (ViLabelServiceForEclipse doObject: obj).
	#icon -> (ViIconServiceForEclipse doObject: obj)}]).
(#class -> ViQueryMapDefinition).
(#id -> #'0c53b73c-4e16-1542-b40c-cd76a3b1dda5').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 September 2013 3:34:54 pm')})).
(#sourceCode -> '[:obj | {
	#text -> (ViLabelServiceForEclipse doObject: obj).
	#icon -> (ViIconServiceForEclipse doObject: obj)}]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})