definitions
def07db93e49707644c8344528719c82bd1
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:sysO | sysO categories collect: [:cat | cat -> sysO]]).
(#class -> ViQueryMapDefinition).
(#id -> #'07db93e4-9707-644c-8344-528719c82bd1').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 February 2014 4:24:55 pm')})).
(#sourceCode -> '[:sysO | sysO categories collect: [:cat | cat -> sysO]]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})