definitions
def0c8f9b64ae239e4ab4c87fbd8f29d864
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'9 December 2015 10:14:14 am'); yourself)); add: (#id->#'0c8f9b64-ae23-9e4a-b4c8-7fbd8f29d864'); add: (#block->[:in :out | in ifNotEmpty: [out add: [#outline] value]]); add: (#sourceCode->'[:in :out | in ifNotEmpty: [out add: [#outline] value]]'); yourself)