definitions
def0bdb10b6b5eb65498cedc377d39afdfa
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:symbol | #text -> (  symbol asString ) ]).
(#class -> ViQueryMapDefinition).
(#id -> #'0bdb10b6-b5eb-6549-8ced-c377d39afdfa').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 September 2013 12:50:01 pm')})).
(#sourceCode -> '[:symbol | #text -> (  symbol asString ) ]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})