definitions
def05e20c0019c2b546be31ae5d98b374f1
	<definition>

	^ ((Dictionary new) add: (#inputKind->CompiledMethod); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'3 June 2014 11:14 am'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'05e20c00-19c2-b546-be31-ae5d98b374f1'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:method | #text -> (method getSource, String cr)]'); add: (#mapType->#each); add: (#block->[:method | #text -> (method getSource, String cr)]); yourself)