definitions
def058d3529d310e847b148dadf47ff31b9
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:class | class name]).
(#class -> ViQueryMapDefinition).
(#id -> #'058d3529-d310-e847-b148-dadf47ff31b9').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 February 2014 4:06:47 pm')})).
(#sourceCode -> '[:class | class name]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})