definitions
def072ec793712bb14f9b7c473999b7002d
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | ViObjectOriginService doObject: obj]).
(#class -> ViQueryStepDefinition).
(#id -> #'072ec793-712b-b14f-9b7c-473999b7002d').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:obj | ViObjectOriginService doObject: obj]')})