definitions
def052a74fa7606c9419a371dead31a8a3e
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:objs | objs gather: [:obj | obj categories]]).
(#class -> ViQueryMapDefinition).
(#id -> #'052a74fa-7606-c941-9a37-1dead31a8a3e').
(#inputKind -> Categorizer).
(#mapType -> #all).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:objs | objs gather: [:obj | obj categories]]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})