definitions
def0e8d96d2e16146428ab89c4f1e307194
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:method | #text -> (  method symbolic ) ]).
(#class -> ViQueryMapDefinition).
(#id -> #'0e8d96d2-e161-4642-8ab8-9c4f1e307194').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '24 February 2014 10:42:49 am')})).
(#sourceCode -> '[:method | #text -> (  method symbolic ) ]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})