definitions
def07161242230e104993b72f75e3deef7b
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'07161242-230e-1049-93b7-2f75e3deef7b'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:method | method methodClass theNonMetaClass]'); add: (#mapType->#each); add: (#block->[:method | method methodClass theNonMetaClass]); yourself)