definitions
def07203f12f1b6974698840b9e8f1a4f6b
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'07203f12-f1b6-9746-9884-0b9e8f1a4f6b'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:method | method methodClass organization categoryOfElement: method selector]'); add: (#mapType->#each); add: (#block->[:method | method methodClass organization categoryOfElement: method selector]); yourself)