definitions
def03349ae00dabb9448a12e55a675ab325
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'11 February 2014 1:09:51 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->PackageOrganizer); add: (#id->#'03349ae0-0dab-b944-8a12-e55a675ab325'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[PackageOrganizer default]'); add: (#mapType->#all); add: (#block->[PackageOrganizer default]); yourself)