definitions
def042fe8279b71854d84137f5befe2d4a5
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'9 December 2015 10:48:47 am'); yourself)); add: (#id->#'042fe827-9b71-854d-8413-7f5befe2d4a5'); add: (#block->[:in :out | in ifNotEmpty: [out add: [#outline] value]]); add: (#sourceCode->'[:in :out | in ifNotEmpty: [out add: [#outline] value]]'); yourself)