definitions
def045ec7be6ef32448b846acab2248a757
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | in ifNotEmpty: [out add: [#groupsMinimal] value]]).
(#class -> ViQueryStepDefinition).
(#id -> #'045ec7be-6ef3-2448-b846-acab2248a757').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 3:12:48.400594 pm')})).
(#sourceCode -> '[:in :out | in ifNotEmpty: [out add: [#groupsMinimal] value]]')})