definitions
def0f8f45f9a0ccc34a9b8f6d1a4f00e403
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'15 November 2014 4:10:06 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'0f8f45f9-a0cc-c34a-9b8f-6d1a4f00e403'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:spec | SystemNavigation default allAccessesTo: spec key from: spec value]'); add: (#mapType->#each); add: (#block->[:spec | SystemNavigation default allAccessesTo: spec key from: spec value]); yourself)