definitions
def02eb996a482ea94ab60747360c8f1033
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | out add: [#'580b86a1-54c0-3a4f-a37c-d12c765b21d4'] value]).
(#class -> ViQueryStepDefinition).
(#id -> #'02eb996a-482e-a94a-b607-47360c8f1033').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:11.508834 pm')})).
(#sourceCode -> '[:in :out | out add: [#''580b86a1-54c0-3a4f-a37c-d12c765b21d4''] value]')})