definitions
def05876be4b12e20468fe7256847cabd85
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'5 October 2013 2:45:38 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'05876be4-b12e-2046-8fe7-256847cabd85'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | #text -> obj key]'); add: (#mapType->#each); add: (#block->[:obj | #text -> obj key]); yourself)