definitions
def0c32b445e778024f83757de9bdce9985
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | out add: [#groups] value]).
(#class -> ViQueryStepDefinition).
(#id -> #'0c32b445-e778-024f-8375-7de9bdce9985').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '20 May 2015 2:48:29 pm')})).
(#sourceCode -> '[:in :out | out add: [#groups] value]')})