definitions
def0bbe027a47646349bc957252096d2002
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | #text -> (  obj key ) ]).
(#class -> ViQueryMapDefinition).
(#id -> #'0bbe027a-4764-6349-bc95-7252096d2002').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 10:25:09 am')})).
(#sourceCode -> '[:obj | #text -> (  obj key ) ]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})