definitions
def06752cb1e5f3b847894650a90ce30938
	<definition>

	^ (Dictionary newFrom: {
(#block -> [SystemOrganization]).
(#class -> ViQueryMapDefinition).
(#id -> #'06752cb1-e5f3-b847-8946-50a90ce30938').
(#inputKind -> Object).
(#mapType -> #all).
(#outputKind -> SystemOrganizer).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 February 2014 3:56:01 pm')})).
(#sourceCode -> '[SystemOrganization]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})