definitions
def13c4a593c111794c9601d7df0930581d
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'13c4a593-c111-794c-9601-d7df0930581d'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:objects :context | objects select: [:def | def first >= 0]].'); add: (#mapType->#all); add: (#block->[:objects :context | objects select: [:def | def first >= 0]]); yourself)