definitions
def1a63b3b5dd5bc242b72324e2fb3768d7
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:def | #text -> (ViTextStyler new styledTextFor: def sourceCode asText)]).
(#class -> ViQueryMapDefinition).
(#id -> #'1a63b3b5-dd5b-c242-b723-24e2fb3768d7').
(#inputKind -> ViQueryStepDefinition).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '3 September 2013 1:56:12 pm')})).
(#sourceCode -> '[:def | #text -> (ViTextStyler new styledTextFor: def sourceCode asText)]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})