definitions
def10f8246fb65e0c46a92eac2a1af3605a
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:def | ViLabelService doObject: def inputKind]).
(#class -> ViQueryStepDefinition).
(#id -> #'10f8246f-b65e-0c46-a92e-ac2a1af3605a').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '3 September 2013 1:57:12 pm')})).
(#sourceCode -> '[:def | ViLabelService doObject: def inputKind]')})