definitions
def1b368e84fb3a6e42b68e7076124c7ab6
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 October 2015 11:12:34 am'); yourself)); add: (#id->#'1b368e84-fb3a-6e42-b68e-7076124c7ab6'); add: (#block->[:in :out | [#groupsUnsorted] value in: [:result |
	out addAll: result asList]]); add: (#sourceCode->'[:in :out | [#groupsUnsorted] value in: [:result |
	out addAll: result asList]]'); yourself)