definitions
def1198e55ba78e68428a273a6403912dca
	<definition>

	^ ((Dictionary new) add: (#inputKind->CompiledMethod); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'20 February 2014 3:41:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Association); add: (#id->#'1198e55b-a78e-6842-8a27-3a6403912dca'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:method | 
	((Smalltalk at: #MethodTags ifAbsentPut: [Dictionary new])
		at: method methodReference ifAbsentPut: [Set new]) -> method]'); add: (#mapType->#each); add: (#block->[:method | 
	((Smalltalk at: #MethodTags ifAbsentPut: [Dictionary new])
		at: method methodReference ifAbsentPut: [Set new]) -> method]); yourself)