definitions
def145841e8e96d2243acbf2de9c5697829
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | 'a ', obj value class name]).
(#class -> ViQueryMapDefinition).
(#id -> #'145841e8-e96d-2243-acbf-2de9c5697829').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 November 2013 4:59:12 pm')})).
(#sourceCode -> '[:obj | ''a '', obj value class name]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})