definitions
def16b05fc9d8ef7845a1ef2347666faaab
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:o1 :o2 | o2 third withAllSuperclasses includes: o1 third]).
(#class -> ViQueryMapDefinition).
(#id -> #'16b05fc9-d8ef-7845-a1ef-2347666faaab').
(#inputKind -> Object).
(#mapType -> #twoArgs).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 January 2014 4:37:27 pm')})).
(#sourceCode -> '[:o1 :o2 | o2 third withAllSuperclasses includes: o1 third]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})