definitions
def1b368e84fb3a6e42b68e7076124c7ab6
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | [#groupsUnsorted] value in: [:result |
	out addAll: result asList]]).
(#class -> ViScriptDefinition).
(#id -> #'1b368e84-fb3a-6e42-b68e-7076124c7ab6').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 October 2015 11:12:34 am')})).
(#sourceCode -> '[:in :out | [#groupsUnsorted] value in: [:result |
	out addAll: result asList]]')})