definitions
def12f308145104df418cadfee1eb31343d
	<definition>

	^ ((Dictionary new) add: (#inputKind->ViFlagComment); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 September 2013 7:00:36 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Boolean); add: (#id->#'12f30814-5104-df41-8cad-fee1eb31343d'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:f1 :f2 | f1 symbol <= f2 symbol]'); add: (#mapType->#twoArgs); add: (#block->[:f1 :f2 | f1 symbol <= f2 symbol]); yourself)