definitions
def163e805162616b4f8d176d1d49dce384
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:class | #text -> (  class name ) ]).
(#class -> ViQueryMapDefinition).
(#id -> #'163e8051-6261-6b4f-8d17-6d1d49dce384').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 February 2014 4:06:47 pm')})).
(#sourceCode -> '[:class | #text -> (  class name ) ]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})