definitions
def110ae7b7c0035f4f8bceb8ec5d33741f
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#copyOf->#'de8216a7-6374-7b49-9452-fe1b108395fb'); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 October 2015 2:07 pm'); yourself)); add: (#id->#'110ae7b7-c003-5f4f-8bce-b8ec5d33741f'); add: (#block->[:in :out | out add: {#objects -> in}, [{
	#bounds -> (0@0 corner: 641@365).
	#current -> #unsavedScripts.
	#scripts -> #(#unsavedScripts ).
	#id -> #'40a98164-6ab3-db44-8db2-caa27b0c9f0c'.
	#out -> #(#(#interactive #'4cc8c555-00fc-e049-b56d-1ca0013dea25' ) #(#interactive #outer ) ).
	#in -> #(#(#automatic #outer ) ).
}] value]); add: (#sourceCode->'[:in :out | out add: {#objects -> in}, [{
	#bounds -> (0@0 corner: 641@365).
	#current -> #unsavedScripts.
	#scripts -> #(#unsavedScripts ).
	#id -> #''40a98164-6ab3-db44-8db2-caa27b0c9f0c''.
	#out -> #(#(#interactive #''4cc8c555-00fc-e049-b56d-1ca0013dea25'' ) #(#interactive #outer ) ).
	#in -> #(#(#automatic #outer ) ).
}] value]'); yourself)