definitions
def110cd1a97a947345a3d8482f7c4670f9
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | #text -> obj printString]).
(#class -> ViQueryMapDefinition).
(#id -> #'110cd1a9-7a94-7345-a3d8-482f7c4670f9').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '25 July 2014 6:20:43 pm')})).
(#sourceCode -> '[:obj | #text -> obj printString]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})