definitions
def1d92a8e5d139ef4b8c89e9b7f36c881a
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'1d92a8e5-d139-ef4b-8c89-e9b7f36c881a'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:tally | tally process
	ifNil: [''Other Processes'']
	ifNotNil: [:p | p browserPrintString escapeHtmlText]]'); add: (#mapType->#each); add: (#block->[:tally | tally process
	ifNil: ['Other Processes']
	ifNotNil: [:p | p browserPrintString escapeHtmlText]]); yourself)