definitions
def17e5fd356230f348a789da694c0d0f55
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'12 May 2015 6:23:49 pm'); yourself)); add: (#id->#'17e5fd35-6230-f348-a789-da694c0d0f55'); add: (#block->[:in :out | out addAll: ([:tuples | tuples asGroups ] value: in)]); add: (#sourceCode->'[:in :out | out addAll: ([:tuples | tuples asGroups ] value: in)]'); yourself)