definitions
def1ceed05f3e46bb44863a75e15728b9af
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | [ViScriptOrganizer active] value in: [:result |
	out addAll: result asList]]).
(#className -> #ViScriptDefinition).
(#id -> #'1ceed05f-3e46-bb44-863a-75e15728b9af').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '23 July 2014 3:01:21 pm')
})).
(#sourceCode -> '[:in :out | [ViScriptOrganizer active] value in: [:result |
	out addAll: result asList]]')
})