definitions
def18acd9e0dfe45e4fbf30f837199c504f
	<definition>

	^ ((Dictionary new) add: (#inputKind->ViStampedHistory); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'18acd9e0-dfe4-5e4f-bf30-f837199c504f'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:objs | objs gather: [:o | o objects reversed gather: [:assoc |
		assoc value collect: [:ea | assoc key -> ea]]]]'); add: (#mapType->#all); add: (#block->[:objs | objs gather: [:o | o objects reversed gather: [:assoc |
		assoc value collect: [:ea | assoc key -> ea]]]]); yourself)