definitions
def1b0474886502e74e83f205ae0fbf0400
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:entry | entry asFileDirectory]).
(#class -> ViQueryMapDefinition).
(#id -> #'1b047488-6502-e74e-83f2-05ae0fbf0400').
(#inputKind -> DirectoryEntryDirectory).
(#mapType -> #each).
(#outputKind -> FileDirectory).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '3 January 2014 3:14:09 pm')})).
(#sourceCode -> '[:entry | entry asFileDirectory]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})