definitions
def1bf3602c26fb4b40a55af0133f1f17d4
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | obj symbol]).
(#class -> ViQueryMapDefinition).
(#id -> #'1bf3602c-26fb-4b40-a55a-f0133f1f17d4').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:obj | obj symbol]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})