definitions
def12c2f0e423f0334a830920f4e2e8a293
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | out add: [#groupsMinimal] value]).
(#class -> ViQueryStepDefinition).
(#id -> #'12c2f0e4-23f0-334a-8309-20f4e2e8a293').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:13.614834 pm')})).
(#sourceCode -> '[:in :out | out add: [#groupsMinimal] value]')})