definitions
def1c82c7d637c74a4dae5c617902522935
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | [ActiveWorld submorphs] value in: [:result |
	out addAll: result asList]]).
(#className -> #ViScriptDefinition).
(#id -> #'1c82c7d6-37c7-4a4d-ae5c-617902522935').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 July 2014 2:12:59 pm')
})).
(#sourceCode -> '[:in :out | [ActiveWorld submorphs] value in: [:result |
	out addAll: result asList]]')
})