definitions
def22e2e96d767f7242ac1879b9438046bc
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:objects | objects select: [:obj | obj isBehavior]]).
(#class -> ViQueryMapDefinition).
(#id -> #'22e2e96d-767f-7242-ac18-79b9438046bc').
(#inputKind -> Object).
(#mapType -> #all).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 February 2014 9:43 am')})).
(#sourceCode -> '[:objects | objects select: [:obj | obj isBehavior]]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})