definitions
def2d4505f2f7236c42ba5bf3cc0d3c03c7
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'14 December 2015 11:30:58 am'); yourself)); add: (#id->#'2d4505f2-f723-6c42-ba5b-f3cc0d3c03c7'); add: (#block->[:in :out | in ifNotEmpty: [out add: [#defaultPropertiesExtended] value]]); add: (#sourceCode->'[:in :out | in ifNotEmpty: [out add: [#defaultPropertiesExtended] value]]'); yourself)