definitions
def281f78d8daabac47abb87f18398684ee
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | #text -> (  ViObjectOriginService doObject: obj ) ]).
(#class -> ViQueryMapDefinition).
(#id -> #'281f78d8-daab-ac47-abb8-7f18398684ee').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:obj | #text -> (  ViObjectOriginService doObject: obj ) ]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})