definitions
def2f31c9953a2b9a418c9a281f6d2a3ffa
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:ref | #text -> ref classSymbol ]).
(#class -> ViQueryMapDefinition).
(#id -> #'2f31c995-3a2b-9a41-8c9a-281f6d2a3ffa').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '24 July 2014 11:37:10 am')})).
(#sourceCode -> '[:ref | #text -> ref classSymbol ]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})