definitions
def2ef099b5ca0a3a4e934e823156b061a9
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:group1 :group2 | group1 asString >= group2 asString]).
(#class -> ViQueryMapDefinition).
(#id -> #'2ef099b5-ca0a-3a4e-934e-823156b061a9').
(#inputKind -> Object).
(#mapType -> #twoArgs).
(#outputKind -> Boolean).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:group1 :group2 | group1 asString >= group2 asString]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})