definitions
def292e64dcce4c7a42964d85da2486116c
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | [SystemOrganization] value in: [:result |
	out addAll: result asList]]).
(#class -> ViScriptDefinition).
(#id -> #'292e64dc-ce4c-7a42-964d-85da2486116c').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 February 2014 3:56:01 pm')})).
(#sourceCode -> '[:in :out | [SystemOrganization] value in: [:result |
	out addAll: result asList]]')})