definitions
def245c4ce0a93e69438f4e042ef3efa6a8
	<definition>

	^ (Dictionary newFrom: {
(#block -> [ChangeSet allChangeSets]).
(#class -> ViQueryMapDefinition).
(#id -> #'245c4ce0-a93e-6943-8f4e-042ef3efa6a8').
(#inputKind -> Object).
(#mapType -> #all).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '5 June 2014 4:48:11 pm')})).
(#sourceCode -> '[ChangeSet allChangeSets]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})