definitions
def239f5618cfad964689cbd2162d14e9c0
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:ref | ref classSymbol]).
(#class -> ViQueryMapDefinition).
(#id -> #'239f5618-cfad-9646-89cb-d2162d14e9c0').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:ref | ref classSymbol]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})