definitions
def250805b91be7c7449a122ccaa6d3670c
	<definition>

	^ ((Dictionary new) add: (#class->ViQuerySnippetDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'10 February 2014 3:57:12 pm'); yourself)); add: (#id->#'250805b9-1be7-c744-9a12-2ccaa6d3670c'); add: (#inputKind->Process); add: (#block->nil); add: (#sourceCode->'Project spawnNewProcessIfThisIsUI: self.
self suspend.'); add: (#receiverIsCollection->false); yourself)