definitions
def274930888837484dba3455061b4f955d
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj1 :obj2 | obj1 theClass name <= obj2 theClass name]).
(#class -> ViQueryMapDefinition).
(#id -> #'27493088-8837-484d-ba34-55061b4f955d').
(#inputKind -> ViClassComment).
(#mapType -> #twoArgs).
(#outputKind -> Boolean).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:obj1 :obj2 | obj1 theClass name <= obj2 theClass name]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})