definitions
def2c677287606b6e4489fb01fb56357b98
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'2c677287-606b-6e44-89fb-01fb56357b98'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | {
	#text -> (ViLabelService doObject: obj reference).
	#icon -> (ViIconService doObject: obj reference)}]'); add: (#mapType->#each); add: (#block->[:obj | {
	#text -> (ViLabelService doObject: obj reference).
	#icon -> (ViIconService doObject: obj reference)}]); yourself)