definitions
def2909f9fe4d358542b0da49fa6a8b6a35
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | out addAll: ([:objects | objects] value: in)]).
(#class -> ViQueryStepDefinition).
(#id -> #'2909f9fe-4d35-8542-b0da-49fa6a8b6a35').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:in :out | out addAll: ([:objects | objects] value: in)]')})