definitions
def2d64642b996d4549b799afb46cd159ae
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'21 May 2014 2:37:53 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'2d64642b-996d-4549-b799-afb46cd159ae'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:hit | #text -> ((((hit at: #info) at: #title) at: #text) convertFromEncoding: ''utf-8'') unescapeEntities asHtmlText]'); add: (#mapType->#each); add: (#block->[:hit | #text -> ((((hit at: #info) at: #title) at: #text) convertFromEncoding: 'utf-8') unescapeEntities asHtmlText]); yourself)