definitions
def2240fd955e9af74597eb38ddbce8c00e
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'23 July 2014 3:01:21 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->ViQueryOrganizer); add: (#id->#'2240fd95-5e9a-f745-97eb-38ddbce8c00e'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[ViQueryOrganizer default]'); add: (#mapType->#all); add: (#block->[ViQueryOrganizer default]); yourself)