definitions
def2c677287606b6e4489fb01fb56357b98
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | {
	#text -> (ViLabelService doObject: obj reference).
	#icon -> (ViIconService doObject: obj reference)}]).
(#class -> ViQueryMapDefinition).
(#id -> #'2c677287-606b-6e44-89fb-01fb56357b98').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:obj | {
	#text -> (ViLabelService doObject: obj reference).
	#icon -> (ViIconService doObject: obj reference)}]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})