definitions
def25c58bc0e985aa41b91c42a88a9a8019
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | out addAll: ([:objects | objects] value: in)]).
(#className -> #ViScriptDefinition).
(#id -> #'25c58bc0-e985-aa41-b91c-42a88a9a8019').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')
})).
(#sourceCode -> '[:in :out | out addAll: ([:objects | objects] value: in)]')
})