definitions
def2d4505f2f7236c42ba5bf3cc0d3c03c7
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | in ifNotEmpty: [out add: [#defaultPropertiesExtended] value]]).
(#class -> ViScriptDefinition).
(#id -> #'2d4505f2-f723-6c42-ba5b-f3cc0d3c03c7').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '14 December 2015 11:30:58 am')})).
(#sourceCode -> '[:in :out | in ifNotEmpty: [out add: [#defaultPropertiesExtended] value]]')})