definitions
def2b65e88571886c41b37402263bb60444
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:cls | cls methodDict values size + cls class methodDict values size]).
(#class -> ViQueryStepDefinition).
(#id -> #'2b65e885-7188-6c41-b374-02263bb60444').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '17 January 2014 3:22:32 pm')})).
(#sourceCode -> '[:cls | cls methodDict values size + cls class methodDict values size]')})