definitions
def2f2ca70660a53745978233256331f57f
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:def | ViLabelService doObject: def outputKind]).
(#class -> ViQueryMapDefinition).
(#id -> #'2f2ca706-60a5-3745-9782-33256331f57f').
(#inputKind -> ViQueryMapDefinition).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '3 September 2013 1:58:21 pm')})).
(#sourceCode -> '[:def | ViLabelService doObject: def outputKind].').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})