definitions
def22e2e96d767f7242ac1879b9438046bc
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 February 2014 9:43 am'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'22e2e96d-767f-7242-ac18-79b9438046bc'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:objects | objects select: [:obj | obj isBehavior]]'); add: (#mapType->#all); add: (#block->[:objects | objects select: [:obj | obj isBehavior]]); yourself)