definitions
def250805b91be7c7449a122ccaa6d3670c
	<definition>

	^ (Dictionary newFrom: {
(#block -> nil).
(#class -> ViQuerySnippetDefinition).
(#id -> #'250805b9-1be7-c744-9a12-2ccaa6d3670c').
(#inputKind -> Process).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '10 February 2014 3:57:12 pm')})).
(#receiverIsCollection -> false).
(#sourceCode -> 'Project spawnNewProcessIfThisIsUI: self.
self suspend.')})