definitions
def35a0b9b2b526b5448986611c3a032ccd
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | in ifNotEmpty: [out add: [#groupsMinimal] value]]).
(#class -> ViQueryStepDefinition).
(#id -> #'35a0b9b2-b526-b544-8986-611c3a032ccd').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '29 March 2019 2:52:43.089235 pm')})).
(#sourceCode -> '[:in :out | in ifNotEmpty: [out add: [#groupsMinimal] value]]')})