definitions
def3c4ea291ae2b63449d0694315e411bf1
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'3c4ea291-ae2b-6344-9d06-94315e411bf1'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:objects :context | objects select: [:method | method selector endsWith: #Icon]].'); add: (#mapType->#all); add: (#block->[:objects :context | objects select: [:method | method selector endsWith: #Icon]]); yourself)