definitions
def38b1fcdaea44fc4bacfc118dc0d54db5
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Boolean); add: (#id->#'38b1fcda-ea44-fc4b-acfc-118dc0d54db5'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj1 :obj2 | obj1 name asLowercase <= obj2 name asLowercase]'); add: (#mapType->#twoArgs); add: (#block->[:obj1 :obj2 | obj1 name asLowercase <= obj2 name asLowercase]); yourself)