definitions
def370f1a4a5473454e96c9b6249cdcd8d9
	<definition>

	^ (Dictionary newFrom: {
(#block -> nil).
(#className -> #ViQuerySnippetDefinition).
(#id -> #'370f1a4a-5473-454e-96c9-b6249cdcd8d9').
(#inputKind -> Process).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '7 February 2014 2:30:18 pm')
})).
(#receiverIsCollection -> false).
(#sourceCode -> 'self step: self suspendedContext.
self stepToSendOrReturn.')
})