definitions
def37b396f7407c3b4da914f5d2034918ca
	<definition>

	^ ((Dictionary new) add: (#inputKind->ClassDescription); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 September 2013 12:58:17 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'37b396f7-407c-3b4d-a914-f5d2034918ca'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:cls | (cls theNonMetaClass organization categories collect: [:p | cls theNonMetaClass -> p]),
	(cls theMetaClass organization categories collect: [:p | cls theMetaClass -> p])]'); add: (#mapType->#each); add: (#block->[:cls | (cls theNonMetaClass organization categories collect: [:p | cls theNonMetaClass -> p]),
	(cls theMetaClass organization categories collect: [:p | cls theMetaClass -> p])]); yourself)