definitions
def3f2640f2b1319d4682fde7424438668c
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:hit | (hit at: #info) at: #year]).
(#class -> ViQueryMapDefinition).
(#id -> #'3f2640f2-b131-9d46-82fd-e7424438668c').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '21 May 2014 6:11:06 pm')})).
(#sourceCode -> '[:hit | (hit at: #info) at: #year]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})