definitions
def3b29544582334343b8f528fbcc5e1319
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:flag | {
	#icon -> (ViIconService doObject: flag reference). 
	#text -> (ViLabelService doObject: flag reference)}]).
(#class -> ViQueryMapDefinition).
(#id -> #'3b295445-8233-4343-b8f5-28fbcc5e1319').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 September 2013 7:01:48 pm')})).
(#sourceCode -> '[:flag | {
	#icon -> (ViIconService doObject: flag reference). 
	#text -> (ViLabelService doObject: flag reference)}]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})