definitions
def353e01ce518b5d49b09504ef0d632d71
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:p | p at: #license]).
(#class -> ViQueryMapDefinition).
(#id -> #'353e01ce-518b-5d49-b095-04ef0d632d71').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '23 September 2013 5:12:29 pm')})).
(#sourceCode -> '[:p | p at: #license]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})