definitions
def353e01ce518b5d49b09504ef0d632d71
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'23 September 2013 5:12:29 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'353e01ce-518b-5d49-b095-04ef0d632d71'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:p | p at: #license]'); add: (#mapType->#each); add: (#block->[:p | p at: #license]); yourself)