definitions
def39a8096b1174d848af3286daa4776f7c
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 4:21:57 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'39a8096b-1174-d848-af32-86daa4776f7c'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | #text -> obj third sourceCode]'); add: (#mapType->#each); add: (#block->[:obj | #text -> obj third sourceCode]); yourself)