definitions
def3994d384d109e44e8b929a64780ce685
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'3 February 2014 5:06:28 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'3994d384-d109-e44e-8b92-9a64780ce685'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | obj vResizing]'); add: (#mapType->#each); add: (#block->[:obj | obj vResizing]); yourself)