definitions
def3d4c128d3a2b994a83e4728679818c54
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | obj category]).
(#class -> ViQueryMapDefinition).
(#id -> #'3d4c128d-3a2b-994a-83e4-728679818c54').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:obj | obj category]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})