definitions
def3d0c7269aed89e4a9b3dfa7ec52d2dc1
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'3d0c7269-aed8-9e4a-9b3d-fa7ec52d2dc1'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | #text -> obj key]'); add: (#mapType->#each); add: (#block->[:obj | #text -> obj key]); yourself)