definitions
def3bdecc0789339f418381c3e613996d08
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:flag | #text -> (ViObjectOriginService doObject: flag reference)]).
(#class -> ViQueryMapDefinition).
(#id -> #'3bdecc07-8933-9f41-8381-c3e613996d08').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 September 2013 7:03:26 pm')})).
(#sourceCode -> '[:flag | #text -> (ViObjectOriginService doObject: flag reference)]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})