definitions
def3b29544582334343b8f528fbcc5e1319
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 September 2013 7:01:48 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'3b295445-8233-4343-b8f5-28fbcc5e1319'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:flag | {
	#icon -> (ViIconService doObject: flag reference). 
	#text -> (ViLabelService doObject: flag reference)}]'); add: (#mapType->#each); add: (#block->[:flag | {
	#icon -> (ViIconService doObject: flag reference). 
	#text -> (ViLabelService doObject: flag reference)}]); yourself)