definitions
def3d0c7269aed89e4a9b3dfa7ec52d2dc1
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | #text -> obj key]).
(#class -> ViQueryMapDefinition).
(#id -> #'3d0c7269-aed8-9e4a-9b3d-fa7ec52d2dc1').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:obj | #text -> obj key]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})