definitions
def3947d99b51290a4d86e55b34e5b2c414
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | out add: [#'045e9d2c-b29a-4641-b942-d4b769535d4a'] value]).
(#class -> ViScriptDefinition).
(#id -> #'3947d99b-5129-0a4d-86e5-5b34e5b2c414').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:13.323834 pm')})).
(#sourceCode -> '[:in :out | out add: [#''045e9d2c-b29a-4641-b942-d4b769535d4a''] value]')})