definitions
def39a8096b1174d848af3286daa4776f7c
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | #text -> obj third sourceCode]).
(#class -> ViQueryMapDefinition).
(#id -> #'39a8096b-1174-d848-af32-86daa4776f7c').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 4:21:57 pm')})).
(#sourceCode -> '[:obj | #text -> obj third sourceCode]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})