definitions
def38b1fcdaea44fc4bacfc118dc0d54db5
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj1 :obj2 | obj1 name asLowercase <= obj2 name asLowercase]).
(#class -> ViQueryMapDefinition).
(#id -> #'38b1fcda-ea44-fc4b-acfc-118dc0d54db5').
(#inputKind -> Object).
(#mapType -> #twoArgs).
(#outputKind -> Boolean).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:obj1 :obj2 | obj1 name asLowercase <= obj2 name asLowercase]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})