definitions
def42b080f1f789de468d53de288f085a5a
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:history | history objects reversed]).
(#class -> ViQueryMapDefinition).
(#id -> #'42b080f1-f789-de46-8d53-de288f085a5a').
(#inputKind -> ViExceptionHistory).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '16 November 2013 4:51:28 pm')})).
(#sourceCode -> '[:history | history objects reversed]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})