definitions
def452e935982a23f4394fec108dfa3fef0
	<definition>

	^ ((Dictionary new) add: (#inputKind->PackageInfo); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->MethodReference); add: (#id->#'452e9359-82a2-3f43-94fe-c108dfa3fef0'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:package | package methods]'); add: (#mapType->#each); add: (#block->[:package | package methods]); yourself)