definitions
def452e935982a23f4394fec108dfa3fef0
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:package | package methods]).
(#class -> ViQueryMapDefinition).
(#id -> #'452e9359-82a2-3f43-94fe-c108dfa3fef0').
(#inputKind -> PackageInfo).
(#mapType -> #each).
(#outputKind -> MethodReference).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:package | package methods]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})