definitions
def4455276a46f3b44c84b87d1a0ab966e7
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:step | #text -> step viewDefinition id]).
(#class -> ViQueryMapDefinition).
(#id -> #'4455276a-46f3-b44c-84b8-7d1a0ab966e7').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '23 July 2014 2:54:01 pm')})).
(#sourceCode -> '[:step | #text -> step viewDefinition id]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})