definitions
def49bc89f4204068469c084b80785c6642
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | out addAll: ([:objects | objects] value: in)]).
(#class -> ViScriptDefinition).
(#id -> #'49bc89f4-2040-6846-9c08-4b80785c6642').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:in :out | out addAll: ([:objects | objects] value: in)]')})