definitions
def48f0bb0fb73d4d4a89a4d68e5f89f019
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:ass1 :ass2 | ass1 key <= ass2 key]).
(#class -> ViQueryMapDefinition).
(#id -> #'48f0bb0f-b73d-4d4a-89a4-d68e5f89f019').
(#inputKind -> Object).
(#mapType -> #twoArgs).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 10:25:52 am')})).
(#sourceCode -> '[:ass1 :ass2 | ass1 key <= ass2 key]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})