definitions
def412dc831637b4b419ed1e8eb3db97062
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:organizer | organizer orderedSteps]).
(#class -> ViQueryMapDefinition).
(#id -> #'412dc831-637b-4b41-9ed1-e8eb3db97062').
(#inputKind -> ViQueryOrganizer).
(#mapType -> #each).
(#outputKind -> ViQueryStep).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '3 September 2013 3:26:55 pm')})).
(#sourceCode -> '[:organizer | organizer orderedSteps]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})