definitions
def4a4ff927816f594998d5e55b44483adc
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'23 September 2013 5:09:20 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'4a4ff927-816f-5949-98d5-e55b44483adc'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:p1 :p2 | (p1 at: #name) asLowercase <= (p2 at: #name) asLowercase]'); add: (#mapType->#twoArgs); add: (#block->[:p1 :p2 | (p1 at: #name) asLowercase <= (p2 at: #name) asLowercase]); yourself)