definitions
def489f815583b35d428ac016fea5427b26
	<definition>

	^ ((Dictionary new) add: (#inputKind->CompiledMethod); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'17 January 2014 3:28:31 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'489f8155-83b3-5d42-8ac0-16fea5427b26'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:methods | methods inject: 0 into: [:sum :each | sum + each linesOfCode]]'); add: (#mapType->#all); add: (#block->[:methods | methods inject: 0 into: [:sum :each | sum + each linesOfCode]]); yourself)