definitions
def489f815583b35d428ac016fea5427b26
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:methods | methods inject: 0 into: [:sum :each | sum + each linesOfCode]]).
(#class -> ViQueryMapDefinition).
(#id -> #'489f8155-83b3-5d42-8ac0-16fea5427b26').
(#inputKind -> CompiledMethod).
(#mapType -> #all).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '17 January 2014 3:28:31 pm')})).
(#sourceCode -> '[:methods | methods inject: 0 into: [:sum :each | sum + each linesOfCode]]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})