definitions
def4c648ac48ed24e47b5bf224c33a1f999
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | ViObjectOriginService doObject: obj]).
(#class -> ViQueryMapDefinition).
(#id -> #'4c648ac4-8ed2-4e47-b5bf-224c33a1f999').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:obj | ViObjectOriginService doObject: obj]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})