definitions
def49caf340056bec4ca1fe877183ba0bc7
	<definition>

	^ ((Dictionary new) add: (#inputKind->ViSmalltalkHub); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'23 September 2013 4:54:28 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'49caf340-056b-ec4c-a1fe-877183ba0bc7'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:hub | hub projects collect: [:nm | hub project: nm] thenSelect: [:p | p ~~ #notFound]]'); add: (#mapType->#each); add: (#block->[:hub | hub projects collect: [:nm | hub project: nm] thenSelect: [:p | p ~~ #notFound]]); yourself)