definitions
def4ed0c30426affe4882590553dbe3f8e0
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:o1 :o2 | o1 value selector <= o2 value selector]).
(#class -> ViQueryMapDefinition).
(#id -> #'4ed0c304-26af-fe48-8259-0553dbe3f8e0').
(#inputKind -> Object).
(#mapType -> #twoArgs).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '20 February 2014 6:27:55 pm')})).
(#sourceCode -> '[:o1 :o2 | o1 value selector <= o2 value selector]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})