definitions
def4fae4afe0c3e74419597e7f50787e6e4
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'31 January 2014 5:10:11 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'4fae4afe-0c3e-7441-9597-e7f50787e6e4'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:def | {
	#icon -> (def receiverIsCollection
		ifTrue: [ViIconService collection]
		ifFalse: [ViIconService blank]).
	#text -> def inputKind asString}]'); add: (#mapType->#each); add: (#block->[:def | {
	#icon -> (def receiverIsCollection
		ifTrue: [ViIconService collection]
		ifFalse: [ViIconService blank]).
	#text -> def inputKind asString}]); yourself)