definitions
def4a0dff95e55dc442b258e5fd54236a7b
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | ViObjectOriginService doObject: obj]).
(#class -> ViQueryMapDefinition).
(#id -> #'4a0dff95-e55d-c442-b258-e5fd54236a7b').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:obj | ViObjectOriginService doObject: obj]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})