definitions
def4455276a46f3b44c84b87d1a0ab966e7
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'23 July 2014 2:54:01 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'4455276a-46f3-b44c-84b8-7d1a0ab966e7'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:step | #text -> step viewDefinition id]'); add: (#mapType->#each); add: (#block->[:step | #text -> step viewDefinition id]); yourself)