definitions
def46f92ae140b018419cabc98a804b3b72
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | #text -> (  obj symbol ) ]).
(#class -> ViQueryMapDefinition).
(#id -> #'46f92ae1-40b0-1841-9cab-c98a804b3b72').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:obj | #text -> (  obj symbol ) ]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})