definitions
def4d86db4d38b87d42b937130dce32f786
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:flag | #text -> (ViObjectOriginServiceForEclipse doObject: flag reference)]).
(#class -> ViQueryMapDefinition).
(#id -> #'4d86db4d-38b8-7d42-b937-130dce32f786').
(#inputKind -> ViFlagComment).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 September 2013 9:29:04 pm')})).
(#sourceCode -> '[:flag | #text -> (ViObjectOriginServiceForEclipse doObject: flag reference)]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})