definitions
def58e3ab98ca82564286d705c3b94c72d8
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | {
	#text -> ((ViMethodVersion versionsOfMethod: obj methodReference) size)}]).
(#class -> ViQueryMapDefinition).
(#id -> #'58e3ab98-ca82-5642-86d7-05c3b94c72d8').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:obj | {
	#text -> ((ViMethodVersion versionsOfMethod: obj methodReference) size)}]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})