definitions
def532b388ce4eeb544be597d3619e04e42
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#copyOf->#'e289bd6c-b383-c943-b655-c502679e2cfc'); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 October 2015 2:07 pm'); yourself)); add: (#id->#'532b388c-e4ee-b544-be59-7d3619e04e42'); add: (#block->[:in :out | out add: {#objects -> in}, [{
	#bounds -> (427@370 corner: 641@391).
	#current -> #'1af15768-bcf7-b14b-83c1-b420955ce1e4'.
	#scripts -> #(#'1af15768-bcf7-b14b-83c1-b420955ce1e4' ).
	#id -> #'4cc8c555-00fc-e049-b56d-1ca0013dea25'.
	#out -> #().
	#in -> #(#(#interactive #'40a98164-6ab3-db44-8db2-caa27b0c9f0c' ) ).
}] value]); add: (#sourceCode->'[:in :out | out add: {#objects -> in}, [{
	#bounds -> (427@370 corner: 641@391).
	#current -> #''1af15768-bcf7-b14b-83c1-b420955ce1e4''.
	#scripts -> #(#''1af15768-bcf7-b14b-83c1-b420955ce1e4'' ).
	#id -> #''4cc8c555-00fc-e049-b56d-1ca0013dea25''.
	#out -> #().
	#in -> #(#(#interactive #''40a98164-6ab3-db44-8db2-caa27b0c9f0c'' ) ).
}] value]'); yourself)