definitions
def563021ef44a7e24ebeb76201088a6f24
	<definition>

	^ ((Dictionary new) add: (#inputKind->String); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Boolean); add: (#id->#'563021ef-44a7-e24e-beb7-6201088a6f24'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:cat1 :cat2 | cat1 <= cat2]'); add: (#mapType->#twoArgs); add: (#block->[:cat1 :cat2 | cat1 <= cat2]); yourself)