definitions
def5dae62e91976c94dbf24d48085622337
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'14 December 2015 11:52:58 am'); yourself)); add: (#id->#'5dae62e9-1976-c94d-bf24-d48085622337'); add: (#block->[:in :out | out addAll: ([:classes | classes
		reject: [:c | classes includes: c superclass]] value: in)]); add: (#sourceCode->'[:in :out | out addAll: ([:classes | classes
		reject: [:c | classes includes: c superclass]] value: in)]'); yourself)