definitions
def5ca6f96bb7e5ae47b4422abfa2f51046
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:cls | cls methodDict values size + cls class methodDict values size]).
(#class -> ViQueryMapDefinition).
(#id -> #'5ca6f96b-b7e5-ae47-b442-2abfa2f51046').
(#inputKind -> ClassDescription).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '17 January 2014 3:22:32 pm')})).
(#sourceCode -> '[:cls | cls methodDict values size + cls class methodDict values size]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})