definitions
def55c88de46025784abe92e1e5dc17e0e4
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:classes | classes gather: [:cls | cls withAllSuperclasses]]).
(#class -> ViQueryMapDefinition).
(#id -> #'55c88de4-6025-784a-be92-e1e5dc17e0e4').
(#inputKind -> ClassDescription).
(#mapType -> #all).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:classes | classes gather: [:cls | cls withAllSuperclasses]]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})