definitions
def5fbe5c7f6f1fad4081abfaf3f9ee4b4d
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'14 December 2015 11:53:32 am'); yourself)); add: (#id->#'5fbe5c7f-6f1f-ad40-81ab-faf3f9ee4b4d'); add: (#block->[:in :out | in ifNotEmpty: [out add: [#'9b96cd37-e54b-5649-b04d-d585c24b8303'] value]]); add: (#sourceCode->'[:in :out | in ifNotEmpty: [out add: [#''9b96cd37-e54b-5649-b04d-d585c24b8303''] value]]'); yourself)