definitions
def5082a340361f9c498de33c1f6aee7276
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:flag | #text -> (  'line ', flag line asString ) ]).
(#class -> ViQueryMapDefinition).
(#id -> #'5082a340-361f-9c49-8de3-3c1f6aee7276').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 September 2013 9:12:52 pm')})).
(#sourceCode -> '[:flag | #text -> (  ''line '', flag line asString ) ]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})