definitions
def52e3e1311ce2694186f6ba307bf8e791
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'20 February 2014 6:28:37 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'52e3e131-1ce2-6941-86f6-ba307bf8e791'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:tag | tag value methodClass organization categoryOfElement: tag value selector]'); add: (#mapType->#each); add: (#block->[:tag | tag value methodClass organization categoryOfElement: tag value selector]); yourself)