definitions
def563021ef44a7e24ebeb76201088a6f24
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:cat1 :cat2 | cat1 <= cat2]).
(#class -> ViQueryMapDefinition).
(#id -> #'563021ef-44a7-e24e-beb7-6201088a6f24').
(#inputKind -> String).
(#mapType -> #twoArgs).
(#outputKind -> Boolean).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:cat1 :cat2 | cat1 <= cat2]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})