definitions
def58e3ab98ca82564286d705c3b94c72d8
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'58e3ab98-ca82-5642-86d7-05c3b94c72d8'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | {
	#text -> ((ViMethodVersion versionsOfMethod: obj methodReference) size)}]'); add: (#mapType->#each); add: (#block->[:obj | {
	#text -> ((ViMethodVersion versionsOfMethod: obj methodReference) size)}]); yourself)