definitions
def59f27a2423d19d49a3835d12c3815d83
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | out add: [#'f4803742-eb44-0846-9085-92c09d525159'] value]).
(#class -> ViQueryStepDefinition).
(#id -> #'59f27a24-23d1-9d49-a383-5d12c3815d83').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:11.882834 pm')})).
(#sourceCode -> '[:in :out | out add: [#''f4803742-eb44-0846-9085-92c09d525159''] value]')})