definitions
def5bcb73c59ad5054d90c6997215e79578
	<definition>

	^ ((Dictionary new) add: (#inputKind->ViTranscriptHistory); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 November 2013 9:09:07 am'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'5bcb73c5-9ad5-054d-90c6-997215e79578'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:history | history objects]'); add: (#mapType->#each); add: (#block->[:history | history objects]); yourself)