definitions
def5bcb73c59ad5054d90c6997215e79578
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:history | history objects]).
(#class -> ViQueryMapDefinition).
(#id -> #'5bcb73c5-9ad5-054d-90c6-997215e79578').
(#inputKind -> ViTranscriptHistory).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 November 2013 9:09:07 am')})).
(#sourceCode -> '[:history | history objects]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})