definitions
def524c947977b0664a87a3626871241adc
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'1 June 2015 1:44:09 pm'); yourself)); add: (#id->#'524c9479-77b0-664a-87a3-626871241adc'); add: (#block->[:in :out | in ifNotEmpty: [out add: [#paneHierarchy] value]]); add: (#sourceCode->'[:in :out | in ifNotEmpty: [out add: [#paneHierarchy] value]]'); yourself)