definitions
def51e565d5fc7cb94eb558b7c0bb51532a
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | out add: [#'d70d563f-bdd7-1842-9175-cf758450e227'] value]).
(#class -> ViQueryStepDefinition).
(#id -> #'51e565d5-fc7c-b94e-b558-b7c0bb51532a').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:13.732834 pm')})).
(#sourceCode -> '[:in :out | out add: [#''d70d563f-bdd7-1842-9175-cf758450e227''] value]')})