definitions
def59640e42b31e9b4a9c48776e3acd55bc
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | {#text -> obj description. #icon -> UiSilkIcons databaseIcon}]).
(#class -> ViQueryMapDefinition).
(#id -> #'59640e42-b31e-9b4a-9c48-776e3acd55bc').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:obj | {#text -> obj description. #icon -> UiSilkIcons databaseIcon}]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})