definitions
def59426283fddab34692ea5fb39aebb54b
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'22 July 2015 9:47:58 am'); yourself)); add: (#id->#'59426283-fdda-b346-92ea-5fb39aebb54b'); add: (#block->[:in :out | [ViProfile active] value in: [:result |
	out addAll: result asList]]); add: (#sourceCode->'[:in :out | [ViProfile active] value in: [:result |
	out addAll: result asList]]'); yourself)