definitions
def595f22af5b39df4782fcbfe9343c2c57
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'595f22af-5b39-df47-82fc-bfe9343c2c57'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:ref | {
	#text -> (ViLabelService doObject: ref).
	#icon -> (ViIconService doObject: ref).
	#color -> (ref isSymbol ifTrue: [Color gray: 0.85] ifFalse: [])}]'); add: (#mapType->#each); add: (#block->[:ref | {
	#text -> (ViLabelService doObject: ref).
	#icon -> (ViIconService doObject: ref).
	#color -> (ref isSymbol ifTrue: [Color gray: 0.85] ifFalse: [])}]); yourself)