definitions
def52e3e1311ce2694186f6ba307bf8e791
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:tag | tag value methodClass organization categoryOfElement: tag value selector]).
(#class -> ViQueryMapDefinition).
(#id -> #'52e3e131-1ce2-6941-86f6-ba307bf8e791').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '20 February 2014 6:28:37 pm')})).
(#sourceCode -> '[:tag | tag value methodClass organization categoryOfElement: tag value selector]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})