definitions
def524c947977b0664a87a3626871241adc
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | in ifNotEmpty: [out add: [#paneHierarchy] value]]).
(#class -> ViScriptDefinition).
(#id -> #'524c9479-77b0-664a-87a3-626871241adc').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '1 June 2015 1:44:09 pm')})).
(#sourceCode -> '[:in :out | in ifNotEmpty: [out add: [#paneHierarchy] value]]')})