definitions
def514e33c149efdb4aab271b67d793b46b
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:ctxt | ctxt method]).
(#class -> ViQueryMapDefinition).
(#id -> #'514e33c1-49ef-db4a-ab27-1b67d793b46b').
(#inputKind -> Context).
(#mapType -> #each).
(#outputKind -> CompiledMethod).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '31 January 2014 6:41:42 pm')})).
(#sourceCode -> '[:ctxt | ctxt method]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})