definitions
def58ea78968763644ca23f47ea23baadcd
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | #text -> (obj comment ifNil: ['-'])]).
(#class -> ViQueryMapDefinition).
(#id -> #'58ea7896-8763-644c-a23f-47ea23baadcd').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:obj | #text -> (obj comment ifNil: [''-''])]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})