definitions
def58ea78968763644ca23f47ea23baadcd
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'58ea7896-8763-644c-a23f-47ea23baadcd'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | #text -> (obj comment ifNil: [''-''])]'); add: (#mapType->#each); add: (#block->[:obj | #text -> (obj comment ifNil: ['-'])]); yourself)