definitions
def5ca204944fecd94a8cc4ad0ae673270b
	<definition>

	^ ((Dictionary new) add: (#inputKind->ViQueryStepDefinition); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'31 January 2014 5:08:06 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->ViQuerySnippetDefinition); add: (#id->#'5ca20494-4fec-d94a-8cc4-ad0ae673270b'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:definitions | definitions select: [:def | def isSnippetDefinition]]'); add: (#mapType->#all); add: (#block->[:definitions | definitions select: [:def | def isSnippetDefinition]]); yourself)