definitions
def55c88de46025784abe92e1e5dc17e0e4
	<definition>

	^ ((Dictionary new) add: (#inputKind->ClassDescription); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'55c88de4-6025-784a-be92-e1e5dc17e0e4'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:classes | classes gather: [:cls | cls withAllSuperclasses]]'); add: (#mapType->#all); add: (#block->[:classes | classes gather: [:cls | cls withAllSuperclasses]]); yourself)