definitions
def6d65793d81a24342bdd935a1e8b2f927
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:pkg | pkg mcPackage]).
(#class -> ViQueryMapDefinition).
(#id -> #'6d65793d-81a2-4342-bdd9-35a1e8b2f927').
(#inputKind -> PackageInfo).
(#mapType -> #each).
(#outputKind -> MCPackage).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 September 2013 4:34:58 pm')})).
(#sourceCode -> '[:pkg | pkg mcPackage]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})