definitions
def6026e2fe064b694e87129dee79b258ec
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | out add: [#groupsMinimal] value]).
(#class -> ViScriptDefinition).
(#id -> #'6026e2fe-064b-694e-8712-9dee79b258ec').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:11.999834 pm')})).
(#sourceCode -> '[:in :out | out add: [#groupsMinimal] value]')})