definitions
def664dac2dff006c42a83d3a52f5a83749
	<definition>

	^ ((Dictionary new) add: (#inputKind->PackageInfo); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'664dac2d-ff00-6c42-a83d-3a52f5a83749'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:packages | packages gather: [:pkg |
	pkg classes]]'); add: (#mapType->#all); add: (#block->[:packages | packages gather: [:pkg |
	pkg classes]]); yourself)