definitions
def6157902679beff43b0def9ca7b8e6c4c
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'61579026-79be-ff43-b0de-f9ca7b8e6c4c'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[SystemNavigation allMethodsSelect: [:m | m linesOfCode > 100]]'); add: (#mapType->#all); add: (#block->[SystemNavigation allMethodsSelect: [:m | m linesOfCode > 100]]); yourself)