definitions
def6f13ef5fb9020443a00920bc9eb86762
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'6f13ef5f-b902-0443-a009-20bc9eb86762'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | #text -> obj info date]'); add: (#mapType->#each); add: (#block->[:obj | #text -> obj info date]); yourself)