definitions
def63eaf355b75ddb42a29bdf015c798b3b
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | [#defaultPropertiesExtended] value in: [:result |
	out addAll: result asList]]).
(#class -> ViScriptDefinition).
(#id -> #'63eaf355-b75d-db42-a29b-df015c798b3b').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '1 February 2016 2:01:31 pm')})).
(#sourceCode -> '[:in :out | [#defaultPropertiesExtended] value in: [:result |
	out addAll: result asList]]')})