definitions
def60127c92d0d0f5448437975ef4eeb195
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:ref | ref actualClass organization categoryOfElement: ref selector]).
(#class -> ViQueryStepDefinition).
(#id -> #'60127c92-d0d0-f544-8437-975ef4eeb195').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:ref | ref actualClass organization categoryOfElement: ref selector]')})