definitions
def6bd7549b9d9b094280f69d2fadde9dfd
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | ViObjectOriginService doObject: obj]).
(#class -> ViQueryStepDefinition).
(#id -> #'6bd7549b-9d9b-0942-80f6-9d2fadde9dfd').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:obj | ViObjectOriginService doObject: obj]')})