definitions
def64d8a552c5676b4eaa78382859927a24
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 September 2013 6:06:33 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->ViObjectHistory); add: (#id->#'64d8a552-c567-6b4e-aa78-382859927a24'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[ViObjectHistory transcriptHistory]'); add: (#mapType->#all); add: (#block->[ViObjectHistory transcriptHistory]); yourself)