definitions
def6034a8ada5b2e14b9a6a6ad8fcd2565e
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | in ifNotEmpty: [out add: [#'4f14fbe5-65d1-c74f-ab1f-7751495fcf7c'] value]]).
(#class -> ViQueryStepDefinition).
(#id -> #'6034a8ad-a5b2-e14b-9a6a-6ad8fcd2565e').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '9 December 2015 1:13:34 pm')})).
(#sourceCode -> '[:in :out | in ifNotEmpty: [out add: [#''4f14fbe5-65d1-c74f-ab1f-7751495fcf7c''] value]]')})