definitions
def6615e26b6ca72a4eb214c4e0bc0ca8f3
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'6615e26b-6ca7-2a4e-b214-c4e0bc0ca8f3'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:ref | ref actualClass category]'); add: (#mapType->#each); add: (#block->[:ref | ref actualClass category]); yourself)