definitions
def6791d9d62faf34488e220aa4c948acdc
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | obj key]).
(#class -> ViQueryMapDefinition).
(#id -> #'6791d9d6-2faf-3448-8e22-0aa4c948acdc').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 10:25:09 am')})).
(#sourceCode -> '[:obj | obj key]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})