definitions
def690e8c357eef244c85c1020bccc1243e
	<definition>

	^ (Dictionary newFrom: {
(#block -> nil).
(#className -> #ViQuerySnippetDefinition).
(#id -> #'690e8c35-7eef-244c-85c1-020bccc1243e').
(#inputKind -> Process).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '10 February 2014 3:50 pm')
})).
(#receiverIsCollection -> false).
(#sourceCode -> 'Project spawnNewProcessIfThisIsUI: self.
self terminate.')
})