definitions
def6a9cd53f7fbbd1408d4dd28b243e5465
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | out addAll: ([:objects | objects] value: in)]).
(#class -> ViQueryStepDefinition).
(#id -> #'6a9cd53f-7fbb-d140-8d4d-d28b243e5465').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:in :out | out addAll: ([:objects | objects] value: in)]')})