definitions
def6731f25c570568438e6f0c4263ca2073
	<definition>

	^ ((Dictionary new) add: (#inputKind->Morph); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'3 February 2014 4:57:24 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Morph); add: (#id->#'6731f25c-5705-6843-8e6f-0c4263ca2073'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:morph | morph submorphs]'); add: (#mapType->#each); add: (#block->[:morph | morph submorphs]); yourself)