definitions
def68e5d13aced82246bed5463df2170ccb
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'15 December 2015 10:40:06 am'); yourself)); add: (#id->#'68e5d13a-ced8-2246-bed5-463df2170ccb'); add: (#block->[:in :out | in ifNotEmpty: [out add: [#'494f08ea-fbe5-8341-b949-c5ac1b22c09b'] value]]); add: (#sourceCode->'[:in :out | in ifNotEmpty: [out add: [#''494f08ea-fbe5-8341-b949-c5ac1b22c09b''] value]]'); yourself)