definitions
def6a55f686f73fd94cb810e6a946eb771a
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | obj at: #website]).
(#class -> ViQueryMapDefinition).
(#id -> #'6a55f686-f73f-d94c-b810-e6a946eb771a').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '23 September 2013 5:12:03 pm')})).
(#sourceCode -> '[:obj | obj at: #website]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})