definitions
def66cd48ee25f8f845b64877d9a1ca2dfe
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:binding | ViToolSet printRelativeTimeStamp: binding key]).
(#class -> ViQueryMapDefinition).
(#id -> #'66cd48ee-25f8-f845-b648-77d9a1ca2dfe').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:binding | ViToolSet printRelativeTimeStamp: binding key]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})