definitions
def664dac2dff006c42a83d3a52f5a83749
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:packages | packages gather: [:pkg |
	pkg classes]]).
(#class -> ViQueryMapDefinition).
(#id -> #'664dac2d-ff00-6c42-a83d-3a52f5a83749').
(#inputKind -> PackageInfo).
(#mapType -> #all).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:packages | packages gather: [:pkg |
	pkg classes]]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})