definitions
def690e8c357eef244c85c1020bccc1243e
	<definition>

	^ ((Dictionary new) add: (#class->ViQuerySnippetDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'10 February 2014 3:50 pm'); yourself)); add: (#id->#'690e8c35-7eef-244c-85c1-020bccc1243e'); add: (#inputKind->Process); add: (#block->nil); add: (#sourceCode->'Project spawnNewProcessIfThisIsUI: self.
self terminate.'); add: (#receiverIsCollection->false); yourself)