definitions
def637834ffc53d7046a8b0edf73f34ff52
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:hub | hub users collect: [:username | hub user: username]]).
(#class -> ViQueryMapDefinition).
(#id -> #'637834ff-c53d-7046-a8b0-edf73f34ff52').
(#inputKind -> ViSmalltalkHub).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 September 2013 5:31:55 pm')})).
(#sourceCode -> '[:hub | hub users collect: [:username | hub user: username]]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})