definitions
def69d885825b2fab488b6499d72b1432a0
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:ctxts | ctxts gather: [:ctxt | ctxt stack]]).
(#class -> ViQueryMapDefinition).
(#id -> #'69d88582-5b2f-ab48-8b64-99d72b1432a0').
(#inputKind -> Context).
(#mapType -> #all).
(#outputKind -> Context).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:ctxts | ctxts gather: [:ctxt | ctxt stack]]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})