definitions
def656c81667060fa4bb228496749942bb7
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | [TestCase] value in: [:result |
	out addAll: result asList]]).
(#class -> ViQueryStepDefinition).
(#id -> #'656c8166-7060-fa4b-b228-496749942bb7').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 February 2014 11:25:12 am')})).
(#sourceCode -> '[:in :out | [TestCase] value in: [:result |
	out addAll: result asList]]')})