definitions
def6157902679beff43b0def9ca7b8e6c4c
	<definition>

	^ (Dictionary newFrom: {
(#block -> [SystemNavigation allMethodsSelect: [:m | m linesOfCode > 100]]).
(#class -> ViQueryMapDefinition).
(#id -> #'61579026-79be-ff43-b0de-f9ca7b8e6c4c').
(#inputKind -> Object).
(#mapType -> #all).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[SystemNavigation allMethodsSelect: [:m | m linesOfCode > 100]]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})