definitions
def6a9db3f020aed541bded40c32e0a065a
	<definition>

	^ ((Dictionary new) add: (#inputKind->RBProgramNode); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'6a9db3f0-20ae-d541-bded-40c32e0a065a'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:node | #text -> node formattedCode]'); add: (#mapType->#each); add: (#block->[:node | #text -> node formattedCode]); yourself)