definitions
def629e8c2420769b46a2657ac9602e8aa5
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:context | #text -> ( 
	"See Debugger >> newStack:"
	context printString ) ]).
(#class -> ViQueryMapDefinition).
(#id -> #'629e8c24-2076-9b46-a265-7ac9602e8aa5').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 February 2014 5:43:01 pm')})).
(#sourceCode -> '[:context | #text -> ( 
	"See Debugger >> newStack:"
	context printString ) ]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})