definitions
def6f38796b7a6d494e926ea2dc03b50f2e
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:entry | #text -> entry name]).
(#class -> ViQueryMapDefinition).
(#id -> #'6f38796b-7a6d-494e-926e-a2dc03b50f2e').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:entry | #text -> entry name]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})