definitions
def6975eef04e5f5542b7b0e35b1872410b
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:def | def organization referencesToDefinition: def]).
(#class -> ViQueryMapDefinition).
(#id -> #'6975eef0-4e5f-5542-b7b0-e35b1872410b').
(#inputKind -> ViQueryStepDefinition).
(#mapType -> #each).
(#outputKind -> ViAbstractQueryPart).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '9 September 2013 12:03:08 pm')})).
(#sourceCode -> '[:def | def organization referencesToDefinition: def]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})