definitions
def63fac7525bc2a14c93db1ae5f37af050
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:symbol | symbol asString]).
(#class -> ViQueryMapDefinition).
(#id -> #'63fac752-5bc2-a14c-93db-1ae5f37af050').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 September 2013 12:50:01 pm')})).
(#sourceCode -> '[:symbol | symbol asString]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})