definitions
def6615e26b6ca72a4eb214c4e0bc0ca8f3
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:ref | ref actualClass category]).
(#class -> ViQueryMapDefinition).
(#id -> #'6615e26b-6ca7-2a4e-b214-c4e0bc0ca8f3').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:ref | ref actualClass category]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})