definitions
def6731f25c570568438e6f0c4263ca2073
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:morph | morph submorphs]).
(#class -> ViQueryMapDefinition).
(#id -> #'6731f25c-5705-6843-8e6f-0c4263ca2073').
(#inputKind -> Morph).
(#mapType -> #each).
(#outputKind -> Morph).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '3 February 2014 4:57:24 pm')})).
(#sourceCode -> '[:morph | morph submorphs]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})