definitions
def64d8a552c5676b4eaa78382859927a24
	<definition>

	^ (Dictionary newFrom: {
(#block -> [ViObjectHistory transcriptHistory]).
(#class -> ViQueryMapDefinition).
(#id -> #'64d8a552-c567-6b4e-aa78-382859927a24').
(#inputKind -> Object).
(#mapType -> #all).
(#outputKind -> AnObsoleteViObjectHistory2).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 September 2013 6:06:33 pm')})).
(#sourceCode -> '[ViObjectHistory transcriptHistory]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})