definitions
def68c20e13b6738e4884c09a67faf9de02
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:assoc | #text -> assoc value asString]).
(#class -> ViQueryMapDefinition).
(#id -> #'68c20e13-b673-8e48-84c0-9a67faf9de02').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 September 2013 6:09:21 pm')})).
(#sourceCode -> '[:assoc | #text -> assoc value asString]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})