definitions
def6ffb588325e94643a9437dd170e4169a
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'6ffb5883-25e9-4643-a943-7dd170e4169a'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:objects :context | objects select: [:entry | entry isDirectory not and: [#(jpg png gif) includes: entry extension]]].'); add: (#mapType->#all); add: (#block->[:objects :context | objects select: [:entry | entry isDirectory not and: [#(jpg png gif) includes: entry extension]]]); yourself)