definitions
def642bd6ceae5f44479fe4ba08475a3dbd
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 September 2013 7:05:18 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'642bd6ce-ae5f-4447-9fe4-ba08475a3dbd'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | obj isBehavior ifTrue: [obj subclasses] ifFalse: [#()]]'); add: (#mapType->#each); add: (#block->[:obj | obj isBehavior ifTrue: [obj subclasses] ifFalse: [#()]]); yourself)