definitions
def6791d9d62faf34488e220aa4c948acdc
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'11 February 2014 10:25:09 am'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'6791d9d6-2faf-3448-8e22-0aa4c948acdc'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | obj key]'); add: (#mapType->#each); add: (#block->[:obj | obj key]); yourself)