definitions
def7bdeb06fbb88d0428057b1f6dccae67b
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | #text -> (obj at: #name)]).
(#class -> ViQueryMapDefinition).
(#id -> #'7bdeb06f-bb88-d042-8057-b1f6dccae67b').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '23 September 2013 4:51:14 pm')})).
(#sourceCode -> '[:obj | #text -> (obj at: #name)]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})