definitions
def729f566ccae2d342b313485aece0c9f6
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:method | method symbolic]).
(#class -> ViQueryMapDefinition).
(#id -> #'729f566c-cae2-d342-b313-485aece0c9f6').
(#inputKind -> CompiledMethod).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '24 February 2014 10:42:49 am')})).
(#sourceCode -> '[:method | method symbolic]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})