definitions
def767367b40c7dcf419d85fc2b543d0747
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'9 December 2015 11:26:37 am'); yourself)); add: (#id->#'767367b4-0c7d-cf41-9d85-fc2b543d0747'); add: (#block->[:in :out | in ifNotEmpty: [out add: [#'297515f3-11ce-2e45-94a2-b23a6cad1586'] value]]); add: (#sourceCode->'[:in :out | in ifNotEmpty: [out add: [#''297515f3-11ce-2e45-94a2-b23a6cad1586''] value]]'); yourself)