definitions
def7bdeb06fbb88d0428057b1f6dccae67b
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'23 September 2013 4:51:14 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'7bdeb06f-bb88-d042-8057-b1f6dccae67b'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | #text -> (obj at: #name)]'); add: (#mapType->#each); add: (#block->[:obj | #text -> (obj at: #name)]); yourself)