definitions
def7edc593b3bddfe4c8177cfab9dec78f2
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'21 January 2015 11:47:33 am'); yourself)); add: (#id->#'7edc593b-3bdd-fe4c-8177-cfab9dec78f2'); add: (#block->[:in :out | out addAll: in]); add: (#sourceCode->'[:in :out | out addAll: in]'); yourself)