definitions
def73823f91a046b84f9fe52fa1da7584a8
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | obj key]).
(#class -> ViQueryMapDefinition).
(#id -> #'73823f91-a046-b84f-9fe5-2fa1da7584a8').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 10:25:09 am')})).
(#sourceCode -> '[:obj | obj key]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})