definitions
def7dd11be7db096d43bc91fbc818f50e1e
	<definition>

	^ ((Dictionary new) add: (#inputKind->Behavior); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 September 2013 6:45:44 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->MethodReference); add: (#id->#'7dd11be7-db09-6d43-bc91-fbc818f50e1e'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:behaviors | SystemNavigation allCallsOn: #flag: fromBehaviors: behaviors sorted: true]'); add: (#mapType->#all); add: (#block->[:behaviors | SystemNavigation allCallsOn: #flag: fromBehaviors: behaviors sorted: true]); yourself)