definitions
def77a2ad581e74ba40b2b6d596c594480b
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'77a2ad58-1e74-ba40-b2b6-d596c594480b'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:ref | SystemNavigation default allCallsOn: ref selector]'); add: (#mapType->#each); add: (#block->[:ref | SystemNavigation default allCallsOn: ref selector]); yourself)