definitions
def7dd11be7db096d43bc91fbc818f50e1e
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:behaviors | SystemNavigation allCallsOn: #flag: fromBehaviors: behaviors sorted: true]).
(#class -> ViQueryMapDefinition).
(#id -> #'7dd11be7-db09-6d43-bc91-fbc818f50e1e').
(#inputKind -> Behavior).
(#mapType -> #all).
(#outputKind -> MethodReference).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 September 2013 6:45:44 pm')})).
(#sourceCode -> '[:behaviors | SystemNavigation allCallsOn: #flag: fromBehaviors: behaviors sorted: true]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})