definitions
def766d7729fc4c6d43a99b6b3c832c0d0d
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 September 2013 7:15:27 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'766d7729-fc4c-6d43-a99b-6b3c832c0d0d'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:refs | refs reject: [:ref | ref selector beginsWith: #test]]'); add: (#mapType->#all); add: (#block->[:refs | refs reject: [:ref | ref selector beginsWith: #test]]); yourself)