definitions
def7fd3badef48ec24d8962354e9676a6d2
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'7fd3bade-f48e-c24d-8962-354e9676a6d2'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | #text -> obj info name]'); add: (#mapType->#each); add: (#block->[:obj | #text -> obj info name]); yourself)