definitions
def720a8d90f7c1334ea4ea5094ba285a8d
	<definition>

	^ ((Dictionary new) add: (#inputKind->MethodReference); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->ByteSymbol); add: (#id->#'720a8d90-f7c1-334e-a4ea-5094ba285a8d'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:ref | ref selector]'); add: (#mapType->#each); add: (#block->[:ref | ref selector]); yourself)