definitions
def720a8d90f7c1334ea4ea5094ba285a8d
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:ref | ref selector]).
(#class -> ViQueryMapDefinition).
(#id -> #'720a8d90-f7c1-334e-a4ea-5094ba285a8d').
(#inputKind -> MethodReference).
(#mapType -> #each).
(#outputKind -> ByteSymbol).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:ref | ref selector]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})