definitions
def7c3c31a6c625d7419241e745aec8f9e9
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | ViObjectOriginService doObject: obj key]).
(#class -> ViQueryMapDefinition).
(#id -> #'7c3c31a6-c625-d741-9241-e745aec8f9e9').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 November 2013 5:07:13 pm')})).
(#sourceCode -> '[:obj | ViObjectOriginService doObject: obj key]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})