definitions
def7eda921dfd52a64689df986706665049
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | #text -> (  obj value identityHash ) ]).
(#class -> ViQueryMapDefinition).
(#id -> #'7eda921d-fd52-a646-89df-986706665049').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '8 November 2013 4:10:44 pm')})).
(#sourceCode -> '[:obj | #text -> (  obj value identityHash ) ]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})