definitions
def76130d1c37343d46a44e7310846af40e
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:cls | ViToolSet linesOfCodeForClassWithoutExtensions: cls]).
(#class -> ViQueryMapDefinition).
(#id -> #'76130d1c-3734-3d46-a44e-7310846af40e').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '17 January 2014 3:23:10 pm')})).
(#sourceCode -> '[:cls | ViToolSet linesOfCodeForClassWithoutExtensions: cls]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})