definitions
def7500e5a099664645a6e451a9ac020852
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:refactoring | refactoring changes changes]).
(#class -> ViQueryMapDefinition).
(#id -> #'7500e5a0-9966-4645-a6e4-51a9ac020852').
(#inputKind -> RBRefactoring).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '6 June 2014 4:16:39 pm')})).
(#sourceCode -> '[:refactoring | refactoring changes changes]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})