definitions
def75c00022426bf341b69fa760df0ca037
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | out add: [#groupsMinimal] value]).
(#class -> ViQueryStepDefinition).
(#id -> #'75c00022-426b-f341-b69f-a760df0ca037').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:12.206834 pm')})).
(#sourceCode -> '[:in :out | out add: [#groupsMinimal] value]')})