definitions
def757d1b4715a6c340a4aa7a62a3a4d909
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | [SystemNavigation default] value in: [:result |
	out addAll: result asList]]).
(#className -> #ViScriptDefinition).
(#id -> #'757d1b47-15a6-c340-a4aa-7a62a3a4d909').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '10 February 2014 4:49:24 pm')
})).
(#sourceCode -> '[:in :out | [SystemNavigation default] value in: [:result |
	out addAll: result asList]]')
})