definitions
def75d098534032ac47a682ee8bf116e232
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | out add: [#'b510b1f4-2f4c-514a-bd82-a354adbf042f'] value]).
(#class -> ViScriptDefinition).
(#id -> #'75d09853-4032-ac47-a682-ee8bf116e232').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:11.705834 pm')})).
(#sourceCode -> '[:in :out | out add: [#''b510b1f4-2f4c-514a-bd82-a354adbf042f''] value]')})