definitions
def7e9d16d47549f441bf3d74fbe6115750
	<definition>

	^ ((Dictionary new) add: (#inputKind->ViQueryStep); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'10 December 2014 10:17:26 am'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'7e9d16d4-7549-f441-bf3d-74fbe6115750'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:q1 :q2 | (q1 valueOfProperty: #priority ifAbsent: [9999]) <= (q2 valueOfProperty: #priority ifAbsent: [9999])]'); add: (#mapType->#twoArgs); add: (#block->[:q1 :q2 | (q1 valueOfProperty: #priority ifAbsent: [9999]) <= (q2 valueOfProperty: #priority ifAbsent: [9999])]); yourself)