definitions
def7bf109e4f6d27c4da0840e72ff4d8753
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:e1 :e2 | e1 isDirectory or: [e2 isDirectory not]]).
(#class -> ViQueryMapDefinition).
(#id -> #'7bf109e4-f6d2-7c4d-a084-0e72ff4d8753').
(#inputKind -> Object).
(#mapType -> #twoArgs).
(#outputKind -> Boolean).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '3 January 2014 3:39:51 pm')})).
(#sourceCode -> '[:e1 :e2 | e1 isDirectory or: [e2 isDirectory not]]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})