definitions
def77a2ad581e74ba40b2b6d596c594480b
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:ref | SystemNavigation default allCallsOn: ref selector]).
(#class -> ViQueryMapDefinition).
(#id -> #'77a2ad58-1e74-ba40-b2b6-d596c594480b').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:ref | SystemNavigation default allCallsOn: ref selector]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})