definitions
def727d53ad887c6c418d2d12fa488d95af
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | #text -> (  obj key ) ]).
(#class -> ViQueryMapDefinition).
(#id -> #'727d53ad-887c-6c41-8d2d-12fa488d95af').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 10:25:09 am')})).
(#sourceCode -> '[:obj | #text -> (  obj key ) ]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})