definitions
def73717316edf30d4db96f250a2ed95c7d
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'9 December 2015 9:44:59 am'); yourself)); add: (#id->#'73717316-edf3-0d4d-b96f-250a2ed95c7d'); add: (#block->[:in :out | in ifNotEmpty: [out add: [#senders] value]]); add: (#sourceCode->'[:in :out | in ifNotEmpty: [out add: [#senders] value]]'); yourself)