definitions
def7c3c31a6c625d7419241e745aec8f9e9
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 November 2013 5:07:13 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'7c3c31a6-c625-d741-9241-e745aec8f9e9'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | ViObjectOriginService doObject: obj key]'); add: (#mapType->#each); add: (#block->[:obj | ViObjectOriginService doObject: obj key]); yourself)