definitions
def7fd3badef48ec24d8962354e9676a6d2
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | #text -> obj info name]).
(#class -> ViQueryMapDefinition).
(#id -> #'7fd3bade-f48e-c24d-8962-354e9676a6d2').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:obj | #text -> obj info name]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})