definitions
def8cd44e71e224234c84af614a4b0ac44f
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:tally | {#text -> tally tally}]).
(#class -> ViQueryMapDefinition).
(#id -> #'8cd44e71-e224-234c-84af-614a4b0ac44f').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:tally | {#text -> tally tally}]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})