definitions
def8e8afd87a8ecb048bf33e99e5d6f9484
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | out add: [#'ef81aed0-ae2d-6548-904f-030b28e12e97'] value]).
(#class -> ViScriptDefinition).
(#id -> #'8e8afd87-a8ec-b048-bf33-e99e5d6f9484').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:12.890834 pm')})).
(#sourceCode -> '[:in :out | out add: [#''ef81aed0-ae2d-6548-904f-030b28e12e97''] value]')})