definitions
def8a8d6ac70a642e4d942f654924a02c68
	<definition>

	^ ((Dictionary new) add: (#inputKind->MethodReference); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 September 2013 6:34:06 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->ViFlagComment); add: (#id->#'8a8d6ac7-0a64-2e4d-942f-654924a02c68'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:ref | ViFlagComment newListFromReference: ref]'); add: (#mapType->#each); add: (#block->[:ref | ViFlagComment newListFromReference: ref]); yourself)