definitions
def8287f41b826f0247b83e45b6688f9d76
	<definition>

	^ ((Dictionary new) add: (#inputKind->FileDirectory); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'6 December 2013 4:49:40 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->DirectoryEntry); add: (#id->#'8287f41b-826f-0247-b83e-45b6688f9d76'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:fd | [fd entries] on: InvalidDirectoryError do: [#()]]'); add: (#mapType->#each); add: (#block->[:fd | [fd entries] on: InvalidDirectoryError do: [#()]]); yourself)