definitions
def880555d52cba5741b7fcd3790f26420e
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | out add: [#'e0d4454d-0188-6242-916d-1c1f2b47e445'] value]).
(#class -> ViScriptDefinition).
(#id -> #'880555d5-2cba-5741-b7fc-d3790f26420e').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:11.707834 pm')})).
(#sourceCode -> '[:in :out | out add: [#''e0d4454d-0188-6242-916d-1c1f2b47e445''] value]')})