definitions
def8d04e4fb3e37ca47967868392bce2475
	<definition>

	^ ((Dictionary new) add: (#inputKind->ViFlagComment); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 September 2013 9:12:52 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'8d04e4fb-3e37-ca47-9678-68392bce2475'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:flag | ''line '', flag line asString]'); add: (#mapType->#each); add: (#block->[:flag | 'line ', flag line asString]); yourself)