definitions
def8287f41b826f0247b83e45b6688f9d76
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:fd | [fd entries] on: InvalidDirectoryError do: [#()]]).
(#class -> ViQueryMapDefinition).
(#id -> #'8287f41b-826f-0247-b83e-45b6688f9d76').
(#inputKind -> FileDirectory).
(#mapType -> #each).
(#outputKind -> DirectoryEntry).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '6 December 2013 4:49:40 pm')})).
(#sourceCode -> '[:fd | [fd entries] on: InvalidDirectoryError do: [#()]]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})