definitions
def85bc20f14a8e54408c069b7261827cb1
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:cls1 :cls2 | cls2 inheritsFrom: cls1]).
(#class -> ViQueryMapDefinition).
(#id -> #'85bc20f1-4a8e-5440-8c06-9b7261827cb1').
(#inputKind -> Object).
(#mapType -> #twoArgs).
(#outputKind -> Boolean).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:cls1 :cls2 | cls2 inheritsFrom: cls1]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})