definitions
def86ecc589bfac754a92b469704fa9b84b
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:selectors | SystemNavigation allUnSentMessagesIn: selectors]).
(#class -> ViQueryMapDefinition).
(#id -> #'86ecc589-bfac-754a-92b4-69704fa9b84b').
(#inputKind -> ByteSymbol).
(#mapType -> #all).
(#outputKind -> ByteSymbol).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 September 2013 7:12:18 pm')})).
(#sourceCode -> '[:selectors | SystemNavigation allUnSentMessagesIn: selectors]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})