definitions
def8171a213b8ca1248b5d5e386fc8a12e5
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:m | #text -> m compiledMethod linesOfCode]).
(#class -> ViQueryMapDefinition).
(#id -> #'8171a213-b8ca-1248-b5d5-e386fc8a12e5').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:m | #text -> m compiledMethod linesOfCode]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})