definitions
def81479141e781ec45a43362852714eeb2
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | #text -> (  obj key ) ]).
(#class -> ViQueryMapDefinition).
(#id -> #'81479141-e781-ec45-a433-62852714eeb2').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 10:25:09 am')})).
(#sourceCode -> '[:obj | #text -> (  obj key ) ]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})