definitions
def89b09f364977604689421b42f21b88f0
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 September 2013 7:19:15 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'89b09f36-4977-6046-8942-1b42f21b88f0'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:refs | refs reject: [:ref | ref classSymbol == #ViQueryArchive]]'); add: (#mapType->#all); add: (#block->[:refs | refs reject: [:ref | ref classSymbol == #ViQueryArchive]]); yourself)