definitions
def86393cf7e7c5e54da0eda9bad31b33d1
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | obj value identityHash]).
(#class -> ViQueryMapDefinition).
(#id -> #'86393cf7-e7c5-e54d-a0ed-a9bad31b33d1').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '8 November 2013 4:10:44 pm')})).
(#sourceCode -> '[:obj | obj value identityHash]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})