definitions
def889c4b1ac134b24781b3f1f186198c7e
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'6 June 2014 5:22:34 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'889c4b1a-c134-b247-81b3-f1f186198c7e'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:change | change changes "composition"
	copyWithout: change]'); add: (#mapType->#each); add: (#block->[:change | change changes "composition"
	copyWithout: change]); yourself)