definitions
def81d4bba3fa925a449759d980ccef208a
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'81d4bba3-fa92-5a44-9759-d980ccef208a'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | #text -> (obj methodClass organization categoryOfElement: obj selector)]'); add: (#mapType->#each); add: (#block->[:obj | #text -> (obj methodClass organization categoryOfElement: obj selector)]); yourself)