definitions
def80a0c58a55587b4bb9331bd54f7214c0
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | out add: [#groupsMinimal] value]).
(#class -> ViQueryStepDefinition).
(#id -> #'80a0c58a-5558-7b4b-b933-1bd54f7214c0').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:11.654834 pm')})).
(#sourceCode -> '[:in :out | out add: [#groupsMinimal] value]')})