definitions
def89be979727105844ab5eb2bdd7f82581
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:project | #text -> (project label allButFirst: 15)]).
(#class -> ViQueryMapDefinition).
(#id -> #'89be9797-2710-5844-ab5e-b2bdd7f82581').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:project | #text -> (project label allButFirst: 15)]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})