definitions
def8171a213b8ca1248b5d5e386fc8a12e5
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'8171a213-b8ca-1248-b5d5-e386fc8a12e5'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:m | #text -> m compiledMethod linesOfCode]'); add: (#mapType->#each); add: (#block->[:m | #text -> m compiledMethod linesOfCode]); yourself)