definitions
def8a8d6ac70a642e4d942f654924a02c68
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:ref | ViFlagComment newListFromReference: ref]).
(#class -> ViQueryMapDefinition).
(#id -> #'8a8d6ac7-0a64-2e4d-942f-654924a02c68').
(#inputKind -> MethodReference).
(#mapType -> #each).
(#outputKind -> ViFlagComment).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 September 2013 6:34:06 pm')})).
(#sourceCode -> '[:ref | ViFlagComment newListFromReference: ref]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})