definitions
def84ee52f9c014804bb364628e00c875d7
	<definition>

	^ ((Dictionary new) add: (#inputKind->ClassDescription); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'84ee52f9-c014-804b-b364-628e00c875d7'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:classes | classes gather: [:cls | cls theMetaClass methodDict values]]'); add: (#mapType->#all); add: (#block->[:classes | classes gather: [:cls | cls theMetaClass methodDict values]]); yourself)