definitions
def8068b6a45651ed4ebf4b38809290491d
	<definition>

	^ ((Dictionary new) add: (#inputKind->MCPackage); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 September 2013 5:13:59 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'8068b6a4-5651-ed4e-bf4b-38809290491d'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:mcp | {
	#text -> (ViLabelServiceForEclipse new doMCPackage: mcp).
	#icon -> (ViIconServiceForEclipse new doMCPackage: mcp)}]'); add: (#mapType->#each); add: (#block->[:mcp | {
	#text -> (ViLabelServiceForEclipse new doMCPackage: mcp).
	#icon -> (ViIconServiceForEclipse new doMCPackage: mcp)}]); yourself)