definitions
def8d8c0677fb622547b0ca9397bf9ffce5
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'8d8c0677-fb62-2547-b0ca-9397bf9ffce5'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | {
	#text -> (ViLabelService doObject: obj).
	#icon -> (ViIconService doObject: obj).
	#color -> (ViColorService doObject: obj)}]'); add: (#mapType->#each); add: (#block->[:obj | {
	#text -> (ViLabelService doObject: obj).
	#icon -> (ViIconService doObject: obj).
	#color -> (ViColorService doObject: obj)}]); yourself)