definitions
def9a123eedf732304a80615921223ef529
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 February 2014 8:38:45 am'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'9a123eed-f732-304a-8061-5921223ef529'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:binding | binding value]'); add: (#mapType->#each); add: (#block->[:binding | binding value]); yourself)