definitions
def946d491e650f484795e269b1d7757dae
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | #text -> obj timeStamp]).
(#class -> ViQueryMapDefinition).
(#id -> #'946d491e-650f-4847-95e2-69b1d7757dae').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:obj | #text -> obj timeStamp]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})