definitions
def9242cbac47978d4c9f3f8d8dc15a9b9e
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:process | #text -> process priority]).
(#class -> ViQueryMapDefinition).
(#id -> #'9242cbac-4797-8d4c-9f3f-8d8dc15a9b9e').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '12 November 2013 4:58:54 pm')})).
(#sourceCode -> '[:process | #text -> process priority]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})