definitions
def947580aed1f52f4c9c336314c8d48f67
	<definition>

	^ ((Dictionary new) add: (#inputKind->ByteSymbol); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'4 December 2013 8:34:54 am'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->MethodReference); add: (#id->#'947580ae-d1f5-2f4c-9c33-6314c8d48f67'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:symbol | ViQueryOrganizer default allCallsOn: symbol]'); add: (#mapType->#each); add: (#block->[:symbol | ViQueryOrganizer default allCallsOn: symbol]); yourself)