definitions
def9bcd7a3d1618064f856d386ada70cdca
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:step | step organization referencesToStep: step]).
(#class -> ViQueryMapDefinition).
(#id -> #'9bcd7a3d-1618-064f-856d-386ada70cdca').
(#inputKind -> ViQueryStep).
(#mapType -> #each).
(#outputKind -> ViQueryStep).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '15 September 2013 5:33:06 pm')})).
(#sourceCode -> '[:step | step organization referencesToStep: step]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})