definitions
def98b3f72931d1cd46b0922db0dbc473e2
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | #text -> obj third id]).
(#class -> ViQueryMapDefinition).
(#id -> #'98b3f729-31d1-cd46-b092-2db0dbc473e2').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 4:21:57 pm')})).
(#sourceCode -> '[:obj | #text -> obj third id]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})