definitions
def95c882eedf97bb48bfb5fadeedf09205
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:protocols | protocols gather: [:protocol | protocol methods]]).
(#class -> ViQueryMapDefinition).
(#id -> #'95c882ee-df97-bb48-bfb5-fadeedf09205').
(#inputKind -> ViProtocol).
(#mapType -> #all).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:protocols | protocols gather: [:protocol | protocol methods]]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})