definitions
def94349485e72e6d47b370a6a240d8da9f
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'6 December 2013 5:27:49 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'94349485-e72e-6d47-b370-a6a240d8da9f'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:objs | objs reject: [:obj | obj isKindOf: Error]]'); add: (#mapType->#all); add: (#block->[:objs | objs reject: [:obj | obj isKindOf: Error]]); yourself)