definitions
def95c882eedf97bb48bfb5fadeedf09205
	<definition>

	^ ((Dictionary new) add: (#inputKind->ViProtocol); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'95c882ee-df97-bb48-bfb5-fadeedf09205'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:protocols | protocols gather: [:protocol | protocol methods]]'); add: (#mapType->#all); add: (#block->[:protocols | protocols gather: [:protocol | protocol methods]]); yourself)