definitions
def946d491e650f484795e269b1d7757dae
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'946d491e-650f-4847-95e2-69b1d7757dae'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | #text -> obj timeStamp]'); add: (#mapType->#each); add: (#block->[:obj | #text -> obj timeStamp]); yourself)