definitions
def901d941e93ccca479bb096ce8b7d62f8
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | #text -> (  obj symbol ) ]).
(#class -> ViQueryMapDefinition).
(#id -> #'901d941e-93cc-ca47-9bb0-96ce8b7d62f8').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:obj | #text -> (  obj symbol ) ]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})