definitions
def9a123eedf732304a80615921223ef529
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:binding | binding value]).
(#class -> ViQueryMapDefinition).
(#id -> #'9a123eed-f732-304a-8061-5921223ef529').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 February 2014 8:38:45 am')})).
(#sourceCode -> '[:binding | binding value]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})