definitions
def954dc6a5194da1439928d69d3079d47a
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:context |
	"See Debugger >> newStack:"
	context printString]).
(#class -> ViQueryMapDefinition).
(#id -> #'954dc6a5-194d-a143-9928-d69d3079d47a').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 February 2014 5:43:01 pm')})).
(#sourceCode -> '[:context |
	"See Debugger >> newStack:"
	context printString]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})