definitions
def9b0b0af62af29d44a8d0acb6157978ac
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:method | #text -> (method decompileWithTemps decompileString asText makeSelectorBoldIn: method methodClass)]).
(#class -> ViQueryMapDefinition).
(#id -> #'9b0b0af6-2af2-9d44-a8d0-acb6157978ac').
(#inputKind -> CompiledMethod).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '24 February 2014 10:52:06 am')})).
(#sourceCode -> '[:method | #text -> (method decompileWithTemps decompileString asText makeSelectorBoldIn: method methodClass)]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})