definitions
def9286450be6b8d94f9454366751f2fce5
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | [PackageOrganizer default] value in: [:result |
	out addAll: result asList]]).
(#className -> #ViScriptDefinition).
(#id -> #'9286450b-e6b8-d94f-9454-366751f2fce5').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 1:09:51 pm')
})).
(#sourceCode -> '[:in :out | [PackageOrganizer default] value in: [:result |
	out addAll: result asList]]')
})