definitions
def934e4a5501f2e344963c6e32fe1b86a6
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | out add: [#groups] value]).
(#class -> ViQueryStepDefinition).
(#id -> #'934e4a55-01f2-e344-963c-6e32fe1b86a6').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '20 May 2015 2:36:10 pm')})).
(#sourceCode -> '[:in :out | out add: [#groups] value]')})