definitions
def982afa1e5280254cb404f3f9ba5ff8c6
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'10 February 2014 4:49:24 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->SystemNavigation); add: (#id->#'982afa1e-5280-254c-b404-f3f9ba5ff8c6'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[SystemNavigation default]'); add: (#mapType->#all); add: (#block->[SystemNavigation default]); yourself)