definitions
def9b5abd1676eb5248b99e5ae7c8cce33b
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'16 November 2013 4:58:02 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'9b5abd16-76eb-5248-b99e-5ae7c8cce33b'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:stamp | #text -> (''<font color="#AAAAAA">{1}</font><br>{2}'' format: {
	ViToolSet printRelativeTimeStamp: stamp key.
	(stamp value description withNoLineLongerThan: 35) escapeHtmlText}) asHtmlText]'); add: (#mapType->#each); add: (#block->[:stamp | #text -> ('<font color="#AAAAAA">{1}</font><br>{2}' format: {
	ViToolSet printRelativeTimeStamp: stamp key.
	(stamp value description withNoLineLongerThan: 35) escapeHtmlText}) asHtmlText]); yourself)