definitions
def98b3f72931d1cd46b0922db0dbc473e2
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 4:21:57 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'98b3f729-31d1-cd46-b092-2db0dbc473e2'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | #text -> obj third id]'); add: (#mapType->#each); add: (#block->[:obj | #text -> obj third id]); yourself)