definitions
def954dc6a5194da1439928d69d3079d47a
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 February 2014 5:43:01 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'954dc6a5-194d-a143-9928-d69d3079d47a'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:context |
	"See Debugger >> newStack:"
	context printString]'); add: (#mapType->#each); add: (#block->[:context |
	"See Debugger >> newStack:"
	context printString]); yourself)