definitions
def99bb691f84691a408b633bf4fb21355c
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:flag | flag comment]).
(#class -> ViQueryStepDefinition).
(#id -> #'99bb691f-8469-1a40-8b63-3bf4fb21355c').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 September 2013 9:36:30 pm').
(#labelColor -> '007F00')})).
(#sourceCode -> '[:flag | flag comment]')})