definitions
def9f165395722b6b41979e695440a8254b
	<definition>

	^ ((Dictionary new) add: (#inputKind->RBProgramNode); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'9f165395-722b-6b41-979e-695440a8254b'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:node | #text -> node class]'); add: (#mapType->#each); add: (#block->[:node | #text -> node class]); yourself)