definitions
defae87be093c235743bab5e2d9aae7bdfb
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'5 June 2014 4:52:37 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'ae87be09-3c23-5743-bab5-e2d9aae7bdfb'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:cs | #icon -> ((cs instVarNamed: #revertable) == true ifTrue: [UiFugueIcons arrowCurve180LeftIcon] ifFalse: [ ])]'); add: (#mapType->#each); add: (#block->[:cs | #icon -> ((cs instVarNamed: #revertable) == true ifTrue: [UiFugueIcons arrowCurve180LeftIcon] ifFalse: [ ])]); yourself)