definitions
defa49c3cf694f73441a8cc666a06f23d42
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:rep1 :rep2 | rep1 description <= rep2 description]).
(#class -> ViQueryMapDefinition).
(#id -> #'a49c3cf6-94f7-3441-a8cc-666a06f23d42').
(#inputKind -> Object).
(#mapType -> #twoArgs).
(#outputKind -> Boolean).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:rep1 :rep2 | rep1 description <= rep2 description]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})