definitions
defad4d80acc0c03e47a673d51547ce89b8
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | {#text -> (ViObjectOriginService doObject: obj value)}]).
(#class -> ViQueryMapDefinition).
(#id -> #'ad4d80ac-c0c0-3e47-a673-d51547ce89b8').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:obj | {#text -> (ViObjectOriginService doObject: obj value)}]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})