definitions
defa47ba51942026e41b76ec19d8e8ab81a
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | out addAll: ([:objects | objects] value: in)]).
(#class -> ViScriptDefinition).
(#id -> #'a47ba519-4202-6e41-b76e-c19d8e8ab81a').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:in :out | out addAll: ([:objects | objects] value: in)]')})