definitions
defac61d54e889d08409451e8c31df3dc34
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:package | package classesAndMetaClasses asArray]).
(#class -> ViQueryMapDefinition).
(#id -> #'ac61d54e-889d-0840-9451-e8c31df3dc34').
(#inputKind -> PackageInfo).
(#mapType -> #each).
(#outputKind -> Behavior).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 September 2013 6:45:25 pm')})).
(#sourceCode -> '[:package | package classesAndMetaClasses asArray]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})