definitions
defa51d601cc1f2d54088780769cf929b4d
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 February 2014 11:23:26 am'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'a51d601c-c1f2-d540-8878-0769cf929b4d'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:category | category]'); add: (#mapType->#each); add: (#block->[:category | category]); yourself)