definitions
defafcc34561c105d4caa94a1fd5b3f1d66
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | in ifNotEmpty: [out add: [#implementors] value]]).
(#class -> ViScriptDefinition).
(#id -> #'afcc3456-1c10-5d4c-aa94-a1fd5b3f1d66').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '9 December 2015 10:25:03 am')})).
(#sourceCode -> '[:in :out | in ifNotEmpty: [out add: [#implementors] value]]')})