definitions
defa048b1ae20425848a30a57a958be6864
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'6 September 2013 9:10:21 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'a048b1ae-2042-5848-a30a-57a958be6864'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:def | #icon -> (def updateClearDefinition
	ifNil: [UiFugueIcons crossSmallIcon]
	ifNotNil: [UiFugueIcons tickSmallIcon])]'); add: (#mapType->#each); add: (#block->[:def | #icon -> (def updateClearDefinition
	ifNil: [UiFugueIcons crossSmallIcon]
	ifNotNil: [UiFugueIcons tickSmallIcon])]); yourself)