definitions
defa9a2b6a9705b9347bad33abd6d56975c
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'12 November 2013 5:16:28 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'a9a2b6a9-705b-9347-bad3-3abd6d56975c'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:objs | objs reject: [:obj | obj isNil]]'); add: (#mapType->#all); add: (#block->[:objs | objs reject: [:obj | obj isNil]]); yourself)