definitions
defa58b2a6f0eb32648b37a6e73442844b7
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'9 December 2015 11:55:27 am'); yourself)); add: (#id->#'a58b2a6f-0eb3-2648-b37a-6e73442844b7'); add: (#block->[:in :out | in ifNotEmpty: [out add: [#groupsUnsorted] value]]); add: (#sourceCode->'[:in :out | in ifNotEmpty: [out add: [#groupsUnsorted] value]]'); yourself)