definitions
defa4426d275a0b244297d01a272d0f6e58
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:cs | #text -> cs preamble]).
(#class -> ViQueryMapDefinition).
(#id -> #'a4426d27-5a0b-2442-97d0-1a272d0f6e58').
(#inputKind -> ChangeSet).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '5 June 2014 5:33:44 pm')})).
(#sourceCode -> '[:cs | #text -> cs preamble]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})