definitions
defa340d182121da8419378c6dd65102090
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Boolean); add: (#id->#'a340d182-121d-a841-9378-c6dd65102090'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:ref1 :ref2 | ref1 selector < ref2 selector
	or: [ref1 selector = ref2 selector
		and: [ref1 classSymbol <= ref2 classSymbol]]]'); add: (#mapType->#twoArgs); add: (#block->[:ref1 :ref2 | ref1 selector < ref2 selector
	or: [ref1 selector = ref2 selector
		and: [ref1 classSymbol <= ref2 classSymbol]]]); yourself)