definitions
defafcc34561c105d4caa94a1fd5b3f1d66
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'9 December 2015 10:25:03 am'); yourself)); add: (#id->#'afcc3456-1c10-5d4c-aa94-a1fd5b3f1d66'); add: (#block->[:in :out | in ifNotEmpty: [out add: [#implementors] value]]); add: (#sourceCode->'[:in :out | in ifNotEmpty: [out add: [#implementors] value]]'); yourself)