definitions
defae87be093c235743bab5e2d9aae7bdfb
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:cs | #icon -> ((cs instVarNamed: #revertable) == true ifTrue: [UiFugueIcons arrowCurve180LeftIcon] ifFalse: [ ])]).
(#class -> ViQueryMapDefinition).
(#id -> #'ae87be09-3c23-5743-bab5-e2d9aae7bdfb').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '5 June 2014 4:52:37 pm')})).
(#sourceCode -> '[:cs | #icon -> ((cs instVarNamed: #revertable) == true ifTrue: [UiFugueIcons arrowCurve180LeftIcon] ifFalse: [ ])]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})