definitions
defa9a2b6a9705b9347bad33abd6d56975c
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:objs | objs reject: [:obj | obj isNil]]).
(#class -> ViQueryMapDefinition).
(#id -> #'a9a2b6a9-705b-9347-bad3-3abd6d56975c').
(#inputKind -> Object).
(#mapType -> #all).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '12 November 2013 5:16:28 pm')})).
(#sourceCode -> '[:objs | objs reject: [:obj | obj isNil]]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})