definitions
defac630cc7c5d7d8409593845690f6bb00
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | [] value in: [:result |
	out addAll: result asList]]).
(#class -> ViQueryStepDefinition).
(#id -> #'ac630cc7-c5d7-d840-9593-845690f6bb00').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '9 December 2015 10:56:04 am')})).
(#sourceCode -> '[:in :out | [] value in: [:result |
	out addAll: result asList]]')})