definitions
defa4426d275a0b244297d01a272d0f6e58
	<definition>

	^ ((Dictionary new) add: (#inputKind->ChangeSet); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'5 June 2014 5:33:44 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'a4426d27-5a0b-2442-97d0-1a272d0f6e58'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:cs | #text -> cs preamble]'); add: (#mapType->#each); add: (#block->[:cs | #text -> cs preamble]); yourself)