definitions
defac630cc7c5d7d8409593845690f6bb00
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'9 December 2015 10:56:04 am'); yourself)); add: (#id->#'ac630cc7-c5d7-d840-9593-845690f6bb00'); add: (#block->[:in :out | [] value in: [:result |
	out addAll: result asList]]); add: (#sourceCode->'[:in :out | [] value in: [:result |
	out addAll: result asList]]'); yourself)