definitions
defafe544ddac959747aa66a354d9e820a0
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | #text -> (  ViObjectOriginService doObject: obj ) ]).
(#class -> ViQueryMapDefinition).
(#id -> #'afe544dd-ac95-9747-aa66-a354d9e820a0').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:obj | #text -> (  ViObjectOriginService doObject: obj ) ]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})