definitions
defa49c3cf694f73441a8cc666a06f23d42
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Boolean); add: (#id->#'a49c3cf6-94f7-3441-a8cc-666a06f23d42'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:rep1 :rep2 | rep1 description <= rep2 description]'); add: (#mapType->#twoArgs); add: (#block->[:rep1 :rep2 | rep1 description <= rep2 description]); yourself)