definitions
defaddce1449b97fb46b280b5500d0f6a06
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | out add: [#groupsMinimal] value]).
(#class -> ViScriptDefinition).
(#id -> #'addce144-9b97-fb46-b280-b5500d0f6a06').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:11.295834 pm')})).
(#sourceCode -> '[:in :out | out add: [#groupsMinimal] value]')})