definitions
defa51d601cc1f2d54088780769cf929b4d
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:category | category]).
(#class -> ViQueryMapDefinition).
(#id -> #'a51d601c-c1f2-d540-8878-0769cf929b4d').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 February 2014 11:23:26 am')})).
(#sourceCode -> '[:category | category]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})