definitions
defac61d54e889d08409451e8c31df3dc34
	<definition>

	^ ((Dictionary new) add: (#inputKind->PackageInfo); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 September 2013 6:45:25 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Behavior); add: (#id->#'ac61d54e-889d-0840-9451-e8c31df3dc34'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:package | package classesAndMetaClasses asArray]'); add: (#mapType->#each); add: (#block->[:package | package classesAndMetaClasses asArray]); yourself)