definitions
defbaae03672eb92745b6afc747b95925ac
	<definition>

	^ ((Dictionary new) add: (#inputKind->CompiledMethod); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'10 January 2014 12:49:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->MethodReference); add: (#id->#'baae0367-2eb9-2745-b6af-c747b95925ac'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:method | method methodReference]'); add: (#mapType->#each); add: (#block->[:method | method methodReference]); yourself)