definitions
defbfa601d39c109a4c854cfc07691dbc37
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | out add: [#groups] value]).
(#class -> ViQueryStepDefinition).
(#id -> #'bfa601d3-9c10-9a4c-854c-fc07691dbc37').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '29 May 2018 9:24:33 am')})).
(#sourceCode -> '[:in :out | out add: [#groups] value]')})