definitions
defbd42b84be2e03f449361626b76d2721f
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'3 February 2014 5:07:16 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'bd42b84b-e2e0-3f44-9361-626b76d2721f'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | obj layoutPolicy class name]'); add: (#mapType->#each); add: (#block->[:obj | obj layoutPolicy class name]); yourself)