definitions
defb6d3bfa595fc2d4eafdbb0ff8f7ac905
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'15 September 2013 5:43:59 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'b6d3bfa5-95fc-2d4e-afdb-b0ff8f7ac905'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:step | step id]'); add: (#mapType->#each); add: (#block->[:step | step id]); yourself)