definitions
defbd23428f5e248b4ea1daf1a684f38d81
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'24 September 2013 8:01 am'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'bd23428f-5e24-8b4e-a1da-f1a684f38d81'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | #icon -> ((obj at: #public) ifTrue: [] ifFalse: [UiFugueIcons eyeIcon])]'); add: (#mapType->#each); add: (#block->[:obj | #icon -> ((obj at: #public) ifTrue: [] ifFalse: [UiFugueIcons eyeIcon])]); yourself)