definitions
defb0fe6ff5386f3c49b42dd2f2c7c96a1a
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:organizer | organizer useFrequencyForDefinitions]).
(#class -> ViQueryMapDefinition).
(#id -> #'b0fe6ff5-386f-3c49-b42d-d2f2c7c96a1a').
(#inputKind -> ViQueryOrganizer).
(#mapType -> #each).
(#outputKind -> Bag).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '5 October 2013 5:06:48 pm')})).
(#sourceCode -> '[:organizer | organizer useFrequencyForDefinitions]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})