definitions
defb08835ac24fe3b4387cbceb4b81fc6fb
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj1 :obj2 | obj1 reference selector <= obj2 reference selector asString]).
(#class -> ViQueryMapDefinition).
(#id -> #'b08835ac-24fe-3b43-87cb-ceb4b81fc6fb').
(#inputKind -> Object).
(#mapType -> #twoArgs).
(#outputKind -> Boolean).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:obj1 :obj2 | obj1 reference selector <= obj2 reference selector asString]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})