definitions
defb47ce5fd48cabe4ea9ec085c8c0d5546
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:step | step steps]).
(#class -> ViQueryMapDefinition).
(#id -> #'b47ce5fd-48ca-be4e-a9ec-085c8c0d5546').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '23 July 2014 1:16:12 pm')})).
(#sourceCode -> '[:step | step steps]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})