definitions
defbfee3c65a0048f47bd94d9d92eaee86b
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 4:21:57 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'bfee3c65-a004-8f47-bd94-d9d92eaee86b'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | #text -> obj third mapType]'); add: (#mapType->#each); add: (#block->[:obj | #text -> obj third mapType]); yourself)