definitions
defb5109e4ef1903846b6375583d25abcce
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | obj key]).
(#class -> ViQueryMapDefinition).
(#id -> #'b5109e4e-f190-3846-b637-5583d25abcce').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 10:25:09 am')})).
(#sourceCode -> '[:obj | obj key]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})