definitions
defbe02a17dcc981640ae53b8838236dad5
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:package | package classes]).
(#class -> ViQueryMapDefinition).
(#id -> #'be02a17d-cc98-1640-ae53-b8838236dad5').
(#inputKind -> PackageInfo).
(#mapType -> #each).
(#outputKind -> ClassDescription).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 June 2014 3:49:58 pm')})).
(#sourceCode -> '[:package | package classes]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})