definitions
defb6d3bfa595fc2d4eafdbb0ff8f7ac905
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:step | step id]).
(#class -> ViQueryMapDefinition).
(#id -> #'b6d3bfa5-95fc-2d4e-afdb-b0ff8f7ac905').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '15 September 2013 5:43:59 pm')})).
(#sourceCode -> '[:step | step id]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})