definitions
defbfe36700f08a1845b1d3c30eccf37a29
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:pkg | pkg systemCategories]).
(#class -> ViQueryMapDefinition).
(#id -> #'bfe36700-f08a-1845-b1d3-c30eccf37a29').
(#inputKind -> PackageInfo).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '20 September 2013 4:54:16 pm')})).
(#sourceCode -> '[:pkg | pkg systemCategories]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})