definitions
defbdf7d30c95466b4e8111e1ca31bd5be9
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'bdf7d30c-9546-6b4e-8111-e1ca31bd5be9'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:version | version relativeDateString]'); add: (#mapType->#each); add: (#block->[:version | version relativeDateString]); yourself)