definitions
defb47ce5fd48cabe4ea9ec085c8c0d5546
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'23 July 2014 1:16:12 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'b47ce5fd-48ca-be4e-a9ec-085c8c0d5546'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:step | step steps]'); add: (#mapType->#each); add: (#block->[:step | step steps]); yourself)