definitions
defbdf7d30c95466b4e8111e1ca31bd5be9
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:version | version relativeDateString]).
(#class -> ViQueryMapDefinition).
(#id -> #'bdf7d30c-9546-6b4e-8111-e1ca31bd5be9').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:version | version relativeDateString]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})