definitions
defbfee3c65a0048f47bd94d9d92eaee86b
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | #text -> obj third mapType]).
(#class -> ViQueryMapDefinition).
(#id -> #'bfee3c65-a004-8f47-bd94-d9d92eaee86b').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 4:21:57 pm')})).
(#sourceCode -> '[:obj | #text -> obj third mapType]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})