definitions
defca489b64d3e0c343b5e1c28e5999d55a
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Boolean); add: (#id->#'ca489b64-d3e0-c343-b5e1-c28e5999d55a'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:o1 :o2 | (o1 isBehavior ifTrue: [o1 name] ifFalse: [o1 selector]) <= (o2 isBehavior ifTrue: [o2 name] ifFalse: [o2 selector])]'); add: (#mapType->#twoArgs); add: (#block->[:o1 :o2 | (o1 isBehavior ifTrue: [o1 name] ifFalse: [o1 selector]) <= (o2 isBehavior ifTrue: [o2 name] ifFalse: [o2 selector])]); yourself)