definitions
defc5e79a5514299047b9169f616017f84a
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:cls | cls methodDict values, cls class methodDict values]).
(#class -> ViQueryMapDefinition).
(#id -> #'c5e79a55-1429-9047-b916-9f616017f84a').
(#inputKind -> ClassDescription).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '17 January 2014 2:55:42 pm')})).
(#sourceCode -> '[:cls | cls methodDict values, cls class methodDict values]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})