definitions
defc3ea1545f452484c8c978118ee648839
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj1 :obj2 | obj1 compiledMethod linesOfCode
	>= obj2 compiledMethod linesOfCode]).
(#class -> ViQueryMapDefinition).
(#id -> #'c3ea1545-f452-484c-8c97-8118ee648839').
(#inputKind -> Object).
(#mapType -> #twoArgs).
(#outputKind -> Boolean).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:obj1 :obj2 | obj1 compiledMethod linesOfCode
	>= obj2 compiledMethod linesOfCode]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})