definitions
defce710d02e55be74885cf67baa093cd49
	<definition>

	^ (Dictionary newFrom: {
(#block -> [TestCase]).
(#class -> ViQueryMapDefinition).
(#id -> #'ce710d02-e55b-e748-85cf-67baa093cd49').
(#inputKind -> Object).
(#mapType -> #all).
(#outputKind -> Behavior).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 February 2014 11:25:12 am')})).
(#sourceCode -> '[TestCase]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})