definitions
defc25e78681c1a4647ab325182e547450a
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:cs | cs methodChanges associations]).
(#class -> ViQueryMapDefinition).
(#id -> #'c25e7868-1c1a-4647-ab32-5182e547450a').
(#inputKind -> ChangeSet).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '5 June 2014 4:56:12 pm')})).
(#sourceCode -> '[:cs | cs methodChanges associations]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})