definitions
defc832c4253742784c81f6541b0f9ae50a
	<definition>

	^ ((Dictionary new) add: (#inputKind->ObjectExplorerWrapper); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'8 November 2013 3:19:19 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'c832c425-3742-784c-81f6-541b0f9ae50a'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:wrapper | wrapper withoutListWrapper]'); add: (#mapType->#each); add: (#block->[:wrapper | wrapper withoutListWrapper]); yourself)