definitions
defc634d79589e7024988d2e94f6ad48bba
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | in ifNotEmpty: [out add: [#inheritance] value]]).
(#class -> ViQueryStepDefinition).
(#id -> #'c634d795-89e7-0249-88d2-e94f6ad48bba').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '1 February 2016 2:17:14 pm')})).
(#sourceCode -> '[:in :out | in ifNotEmpty: [out add: [#inheritance] value]]')})