definitions
defc70a89eb72fb1846be69841c75c0a435
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:morph | {#text -> morph class name. #icon -> (morph imageForm scaledToSize: 16@16)  }]).
(#class -> ViQueryMapDefinition).
(#id -> #'c70a89eb-72fb-1846-be69-841c75c0a435').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 March 2014 10:06:15 am')})).
(#sourceCode -> '[:morph | {#text -> morph class name. #icon -> (morph imageForm scaledToSize: 16@16)  }]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})