definitions
defce6afbe5bac68d438242117271d13401
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | obj at: #email]).
(#class -> ViQueryMapDefinition).
(#id -> #'ce6afbe5-bac6-8d43-8242-117271d13401').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 September 2013 5:36:31 pm')})).
(#sourceCode -> '[:obj | obj at: #email]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})