definitions
defc3d14c3079e47e49976d60b6548c297e
	<definition>

	^ (Dictionary newFrom: {
(#block -> [VivideLight editorStates]).
(#class -> ViQueryMapDefinition).
(#id -> #'c3d14c30-79e4-7e49-976d-60b6548c297e').
(#inputKind -> Object).
(#mapType -> #all).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '20 May 2014 11:59:48 am')})).
(#sourceCode -> '[VivideLight editorStates]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})