definitions
defc89a35bed81ae94298a604cd534ba537
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:packages | packages gather: [:pkg |
	pkg extensionMethods]]).
(#class -> ViQueryMapDefinition).
(#id -> #'c89a35be-d81a-e942-98a6-04cd534ba537').
(#inputKind -> PackageInfo).
(#mapType -> #all).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:packages | packages gather: [:pkg |
	pkg extensionMethods]]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})