definitions
defcb0697a0955cf84e821f1a0301557b51
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | out add: [#'8ed52473-9493-2142-94be-054478bc571b'] value]).
(#class -> ViQueryStepDefinition).
(#id -> #'cb0697a0-955c-f84e-821f-1a0301557b51').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:12.931834 pm')})).
(#sourceCode -> '[:in :out | out add: [#''8ed52473-9493-2142-94be-054478bc571b''] value]')})