definitions
defc6a08f059e2f4542bdfc23dbd53617cc
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'c6a08f05-9e2f-4542-bdfc-23dbd53617cc'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | {
	#text -> (ViObjectOriginService doObject: obj reference)}]'); add: (#mapType->#each); add: (#block->[:obj | {
	#text -> (ViObjectOriginService doObject: obj reference)}]); yourself)