definitions
defc6a08f059e2f4542bdfc23dbd53617cc
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | {
	#text -> (ViObjectOriginService doObject: obj reference)}]).
(#class -> ViQueryMapDefinition).
(#id -> #'c6a08f05-9e2f-4542-bdfc-23dbd53617cc').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:obj | {
	#text -> (ViObjectOriginService doObject: obj reference)}]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})