definitions
defc5c5e6af5c6873468f742b8ce9d21204
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:entry | entry creationDateAndTime asDate asString]).
(#class -> ViQueryMapDefinition).
(#id -> #'c5c5e6af-5c68-7346-8f74-2b8ce9d21204').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:entry | entry creationDateAndTime asDate asString]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})