definitions
defc8e4d891577b37459417d647f783c713
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | 'a ', obj value class name]).
(#class -> ViQueryStepDefinition).
(#id -> #'c8e4d891-577b-3745-9417-d647f783c713').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 November 2013 4:59:12 pm')})).
(#sourceCode -> '[:obj | ''a '', obj value class name]')})