definitions
defca63f41a42ba4a4c8fc339f3fd8428b2
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:op | {#text -> op definition description first}]).
(#class -> ViQueryMapDefinition).
(#id -> #'ca63f41a-42ba-4a4c-8fc3-39f3fd8428b2').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:op | {#text -> op definition description first}]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})