definitions
defc3876e0215ba414aae61c41de8ba4e72
	<definition>

	^ ((Dictionary new) add: (#inputKind->ByteSymbol); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->MethodReference); add: (#id->#'c3876e02-15ba-414a-ae61-c41de8ba4e72'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:symbol | SystemNavigation default allImplementorsOf: symbol]'); add: (#mapType->#each); add: (#block->[:symbol | SystemNavigation default allImplementorsOf: symbol]); yourself)