definitions
defc05078c360b7974f963811f50024055a
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'9 December 2015 1:06:03 pm'); yourself)); add: (#id->#'c05078c3-60b7-974f-9638-11f50024055a'); add: (#block->[:in :out | out addAll: in]); add: (#sourceCode->'[:in :out | out addAll: in]'); yourself)