definitions
defc7130d649f4e7247bd609214f1d0f522
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | #text -> obj first]).
(#class -> ViQueryMapDefinition).
(#id -> #'c7130d64-9f4e-7247-bd60-9214f1d0f522').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:obj | #text -> obj first]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})