definitions
defc832c4253742784c81f6541b0f9ae50a
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:wrapper | wrapper withoutListWrapper]).
(#class -> ViQueryMapDefinition).
(#id -> #'c832c425-3742-784c-81f6-541b0f9ae50a').
(#inputKind -> ObjectExplorerWrapper).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '8 November 2013 3:19:19 pm')})).
(#sourceCode -> '[:wrapper | wrapper withoutListWrapper]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})