definitions
defc7130d649f4e7247bd609214f1d0f522
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'c7130d64-9f4e-7247-bd60-9214f1d0f522'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | #text -> obj first]'); add: (#mapType->#each); add: (#block->[:obj | #text -> obj first]); yourself)