definitions
defd94d89ddc32ff144b8b5f265d775a7f5
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:pkg1 :pkg2 | pkg1 packageName <= pkg2 packageName]).
(#class -> ViQueryMapDefinition).
(#id -> #'d94d89dd-c32f-f144-b8b5-f265d775a7f5').
(#inputKind -> PackageInfo).
(#mapType -> #twoArgs).
(#outputKind -> Boolean).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:pkg1 :pkg2 | pkg1 packageName <= pkg2 packageName]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})