definitions
defd579b1f644668842b908ef4dcc51f0ad
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:step | #text -> step id]).
(#class -> ViQueryMapDefinition).
(#id -> #'d579b1f6-4466-8842-b908-ef4dcc51f0ad').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '23 July 2014 2:44:48 pm')})).
(#sourceCode -> '[:step | #text -> step id]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})