definitions
defde8216a763747b499452fe1b108395fb
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 October 2015 11:47:09 am'); yourself)); add: (#id->#'de8216a7-6374-7b49-9452-fe1b108395fb'); add: (#block->[:in :out | out add: {#objects -> in}, [{
	#bounds -> (243@313 corner: 368@347).
	#current -> #'e9577839-3b92-8e4f-a413-365561ade680'.
	#scripts -> #(#'e9577839-3b92-8e4f-a413-365561ade680' ).
	#id -> #'4cc8c555-00fc-e049-b56d-1ca0013dea25'.
	#out -> #().
	#in -> #(#(#interactive #'40a98164-6ab3-db44-8db2-caa27b0c9f0c' ) ).
}] value]); add: (#sourceCode->'[:in :out | out add: {#objects -> in}, [{
	#bounds -> (243@313 corner: 368@347).
	#current -> #''e9577839-3b92-8e4f-a413-365561ade680''.
	#scripts -> #(#''e9577839-3b92-8e4f-a413-365561ade680'' ).
	#id -> #''4cc8c555-00fc-e049-b56d-1ca0013dea25''.
	#out -> #().
	#in -> #(#(#interactive #''40a98164-6ab3-db44-8db2-caa27b0c9f0c'' ) ).
}] value]'); yourself)