definitions
defdd5ac1768ae85d49b08038900d03870b
	<definition>

	^ ((Dictionary new) add: (#inputKind->MethodContext); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 February 2014 5:58:29 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'dd5ac176-8ae8-5d49-b080-38900d03870b'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:ctxt | ctxt receiver]'); add: (#mapType->#each); add: (#block->[:ctxt | ctxt receiver]); yourself)