definitions
defdd5ac1768ae85d49b08038900d03870b
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:ctxt | ctxt receiver]).
(#class -> ViQueryMapDefinition).
(#id -> #'dd5ac176-8ae8-5d49-b080-38900d03870b').
(#inputKind -> Context).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 February 2014 5:58:29 pm')})).
(#sourceCode -> '[:ctxt | ctxt receiver]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})