definitions
defd94d89ddc32ff144b8b5f265d775a7f5
	<definition>

	^ ((Dictionary new) add: (#inputKind->PackageInfo); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Boolean); add: (#id->#'d94d89dd-c32f-f144-b8b5-f265d775a7f5'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:pkg1 :pkg2 | pkg1 packageName <= pkg2 packageName]'); add: (#mapType->#twoArgs); add: (#block->[:pkg1 :pkg2 | pkg1 packageName <= pkg2 packageName]); yourself)