definitions
defd387d29cec6cd7449b76f0019c974b66
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | ViObjectOriginService doObject: obj key]).
(#class -> ViQueryMapDefinition).
(#id -> #'d387d29c-ec6c-d744-9b76-f0019c974b66').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 November 2013 5:07:13 pm')})).
(#sourceCode -> '[:obj | ViObjectOriginService doObject: obj key]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})