definitions
defd756d757ff89864c9ae1dcc219b18358
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:ref | #text -> (  ref selector ) ]).
(#class -> ViQueryMapDefinition).
(#id -> #'d756d757-ff89-864c-9ae1-dcc219b18358').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:ref | #text -> (  ref selector ) ]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})