definitions
defd8985e4a16e98643914306e11ad06235
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:symbol | symbol asString]).
(#class -> ViQueryMapDefinition).
(#id -> #'d8985e4a-16e9-8643-9143-06e11ad06235').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 September 2013 12:50:01 pm')})).
(#sourceCode -> '[:symbol | symbol asString]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})