definitions
defd90a894f095c5c43ac7b5c0f959c349c
	<definition>

	^ (Dictionary newFrom: {
(#block -> [ActiveWorld submorphs]).
(#class -> ViQueryMapDefinition).
(#id -> #'d90a894f-095c-5c43-ac7b-5c0f959c349c').
(#inputKind -> Object).
(#mapType -> #all).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 July 2014 2:12:59 pm')})).
(#sourceCode -> '[ActiveWorld submorphs]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})