definitions
defd1c87767867eaf499a091e5f2934e9dd
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | out add: [#groupsMinimal] value]).
(#class -> ViQueryStepDefinition).
(#id -> #'d1c87767-867e-af49-9a09-1e5f2934e9dd').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:13.434834 pm')})).
(#sourceCode -> '[:in :out | out add: [#groupsMinimal] value]')})