definitions
defd0916bc97082ad48b568cf6594d4730e
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'d0916bc9-7082-ad48-b568-cf6594d4730e'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | {#text -> (ViLabelService doObject: obj value description)}]'); add: (#mapType->#each); add: (#block->[:obj | {#text -> (ViLabelService doObject: obj value description)}]); yourself)