definitions
defdfc526350f67ec4495da0015581b3976
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | #text -> (  obj value identityHash ) ]).
(#class -> ViQueryMapDefinition).
(#id -> #'dfc52635-0f67-ec44-95da-0015581b3976').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '8 November 2013 4:10:44 pm')})).
(#sourceCode -> '[:obj | #text -> (  obj value identityHash ) ]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})