definitions
defd0916bc97082ad48b568cf6594d4730e
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | {#text -> (ViLabelService doObject: obj value description)}]).
(#class -> ViQueryMapDefinition).
(#id -> #'d0916bc9-7082-ad48-b568-cf6594d4730e').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:obj | {#text -> (ViLabelService doObject: obj value description)}]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})