definitions
defdead5eeb1ecf8040aa1c9f2476397298
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:ref | ref actualClass organization categoryOfElement: ref selector]).
(#class -> ViQueryMapDefinition).
(#id -> #'dead5eeb-1ecf-8040-aa1c-9f2476397298').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:ref | ref actualClass organization categoryOfElement: ref selector]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})