definitions
defde45825b35e8204ebbdd4b6a784be13c
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | out add: [#groupsMinimal] value]).
(#class -> ViQueryStepDefinition).
(#id -> #'de45825b-35e8-204e-bbdd-4b6a784be13c').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:11.896834 pm')})).
(#sourceCode -> '[:in :out | out add: [#groupsMinimal] value]')})