definitions
defd8985e4a16e98643914306e11ad06235
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 September 2013 12:50:01 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'d8985e4a-16e9-8643-9143-06e11ad06235'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:symbol | symbol asString]'); add: (#mapType->#each); add: (#block->[:symbol | symbol asString]); yourself)