definitions
defdead5eeb1ecf8040aa1c9f2476397298
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'dead5eeb-1ecf-8040-aa1c-9f2476397298'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:ref | ref actualClass organization categoryOfElement: ref selector]'); add: (#mapType->#each); add: (#block->[:ref | ref actualClass organization categoryOfElement: ref selector]); yourself)