definitions
defd11fd676c93090419741c3b05ed28509
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | out add: [#'37989d23-0602-ed44-ad37-440cccc8d6d9'] value]).
(#class -> ViQueryStepDefinition).
(#id -> #'d11fd676-c930-9041-9741-c3b05ed28509').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:12.222834 pm')})).
(#sourceCode -> '[:in :out | out add: [#''37989d23-0602-ed44-ad37-440cccc8d6d9''] value]')})