definitions
defda49621777f2ba44a2d70d804e4e9dee
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | out add: [#'67636419-4db6-8c43-aa22-b3948e02e796'] value]).
(#class -> ViScriptDefinition).
(#id -> #'da496217-77f2-ba44-a2d7-0d804e4e9dee').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:13.389834 pm')})).
(#sourceCode -> '[:in :out | out add: [#''67636419-4db6-8c43-aa22-b3948e02e796''] value]')})