definitions
defda22d385455e8b43aa55c0c3094b1ca7
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:line | #text -> line value]).
(#class -> ViQueryMapDefinition).
(#id -> #'da22d385-455e-8b43-aa55-c0c3094b1ca7').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '14 February 2014 9:31:36 am')})).
(#sourceCode -> '[:line | #text -> line value]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})