definitions
defd0d48ca25848de409dec499bcb0ef520
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:pkg | #morph -> (Morph new color: Color green muchDarker; extent: (pkg linesOfCode // 100) @ 10)]).
(#class -> ViQueryMapDefinition).
(#id -> #'d0d48ca2-5848-de40-9dec-499bcb0ef520').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 1:47:30 pm')})).
(#sourceCode -> '[:pkg | #morph -> (Morph new color: Color green muchDarker; extent: (pkg linesOfCode // 100) @ 10)]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})