definitions
defeed543869a8f024e90ba9efea47b5d59
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | [SystemOrganization] value in: [:result |
	out addAll: result asList]]).
(#class -> ViScriptDefinition).
(#id -> #'eed54386-9a8f-024e-90ba-9efea47b5d59').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 February 2014 3:56:01 pm')})).
(#sourceCode -> '[:in :out | [SystemOrganization] value in: [:result |
	out addAll: result asList]]')})