definitions
defe7757bdb25c1524995ae95baac8a366d
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | in ifNotEmpty: [out add: [#'8451e0da-6c99-7f41-9483-316176f07642'] value]]).
(#class -> ViScriptDefinition).
(#id -> #'e7757bdb-25c1-5249-95ae-95baac8a366d').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '20 May 2015 2:55:26 pm')})).
(#sourceCode -> '[:in :out | in ifNotEmpty: [out add: [#''8451e0da-6c99-7f41-9483-316176f07642''] value]]')})