definitions
defecc82096e22c14469001ba0f0f6d0be2
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:def | #text -> ('<font color="#AAAAAA">', def id, '</font>') asHtmlText]).
(#class -> ViQueryMapDefinition).
(#id -> #'ecc82096-e22c-1446-9001-ba0f0f6d0be2').
(#inputKind -> ViAbstractQueryPart).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '3 September 2013 1:56:59 pm')})).
(#sourceCode -> '[:def | #text -> (''<font color="#AAAAAA">'', def id, ''</font>'') asHtmlText]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})