definitions
defe34d1bb92423d34ea16bf84b0ab7ae75
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'e34d1bb9-2423-d34e-a16b-f84b0ab7ae75'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | {
	#text -> (ViLabelService doObject: obj).
	#icon -> ((ViIconService doObject: obj) ifNil: [ViIcons blankIcon])}]'); add: (#mapType->#each); add: (#block->[:obj | {
	#text -> (ViLabelService doObject: obj).
	#icon -> ((ViIconService doObject: obj) ifNil: [ViIcons blankIcon])}]); yourself)