definitions
defe43c93d0ee96e5428395df731e1f9503
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'e43c93d0-ee96-e542-8395-df731e1f9503'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:entry | {
	#text -> entry name.
	#icon -> (ViThumbnailCache default thumbnailForEntry: entry size: 100@100)}]'); add: (#mapType->#each); add: (#block->[:entry | {
	#text -> entry name.
	#icon -> (ViThumbnailCache default thumbnailForEntry: entry size: 100@100)}]); yourself)