definitions
defef07cc37d75caa4cbac087ad92606d23
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:assoc | assoc value]).
(#class -> ViQueryMapDefinition).
(#id -> #'ef07cc37-d75c-aa4c-bac0-87ad92606d23').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:assoc | assoc value]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})