definitions
defe215b2d247eb3e4db409f7a3b60f2aea
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | out add: [#groupsMinimal] value]).
(#class -> ViQueryStepDefinition).
(#id -> #'e215b2d2-47eb-3e4d-b409-f7a3b60f2aea').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:13.628834 pm')})).
(#sourceCode -> '[:in :out | out add: [#groupsMinimal] value]')})