definitions
defe64a13383b924a46a650cd9b6c5ca8dc
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'22 July 2015 9:48:05 am'); yourself)); add: (#id->#'e64a1338-3b92-4a46-a650-cd9b6c5ca8dc'); add: (#block->[:in :out | [#recentlyOpened] value in: [:result |
	out addAll: result asList]]); add: (#sourceCode->'[:in :out | [#recentlyOpened] value in: [:result |
	out addAll: result asList]]'); yourself)