definitions
defe2b4597cc351224e86deee5cb0cff6b5
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | ViObjectOriginService doObject: obj]).
(#class -> ViQueryMapDefinition).
(#id -> #'e2b4597c-c351-224e-86de-ee5cb0cff6b5').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:obj | ViObjectOriginService doObject: obj]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})