definitions
defe64a13383b924a46a650cd9b6c5ca8dc
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | [#recentlyOpened] value in: [:result |
	out addAll: result asList]]).
(#class -> ViScriptDefinition).
(#id -> #'e64a1338-3b92-4a46-a650-cd9b6c5ca8dc').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '22 July 2015 9:48:05 am')})).
(#sourceCode -> '[:in :out | [#recentlyOpened] value in: [:result |
	out addAll: result asList]]')})