definitions
defe75b20277d4fe24d8ad34f7a91ea05e6
	<definition>

	^ (Dictionary newFrom: {
(#block -> nil).
(#class -> ViQuerySnippetDefinition).
(#id -> #'e75b2027-7d4f-e24d-8ad3-4f7a91ea05e6').
(#inputKind -> RBRefactoring).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '6 June 2014 11:30:19 am')})).
(#receiverIsCollection -> false).
(#sourceCode -> 'RBRefactoringManager instance addRefactoring: self')})