definitions
defe8978022c0370a4b9e33a81e1e562382
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'e8978022-c037-0a4b-9e33-a81e1e562382'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:ref | {#text -> (ref actualClass organization categoryOfElement: ref selector)}]'); add: (#mapType->#each); add: (#block->[:ref | {#text -> (ref actualClass organization categoryOfElement: ref selector)}]); yourself)