definitions
defecc82096e22c14469001ba0f0f6d0be2
	<definition>

	^ ((Dictionary new) add: (#inputKind->ViAbstractQueryPart); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'3 September 2013 1:56:59 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'ecc82096-e22c-1446-9001-ba0f0f6d0be2'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:def | #text -> (''<font color="#AAAAAA">'', def id, ''</font>'') asHtmlText]'); add: (#mapType->#each); add: (#block->[:def | #text -> ('<font color="#AAAAAA">', def id, '</font>') asHtmlText]); yourself)