definitions
defe51b58172aa30e4abd1068436cd94de6
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 February 2014 9:44:14 am'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'e51b5817-2aa3-0e4a-bd10-68436cd94de6'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | obj isVariableBinding
	ifTrue: [''** scripts **'']
	ifFalse: [obj category]]'); add: (#mapType->#each); add: (#block->[:obj | obj isVariableBinding
	ifTrue: ['** scripts **']
	ifFalse: [obj category]]); yourself)