definitions
defe122c0286e2c234889185640418abb8e
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | out add: [#'688b9e53-cc30-9341-a368-54f6c47e402c'] value]).
(#class -> ViQueryStepDefinition).
(#id -> #'e122c028-6e2c-2348-8918-5640418abb8e').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:11.743834 pm')})).
(#sourceCode -> '[:in :out | out add: [#''688b9e53-cc30-9341-a368-54f6c47e402c''] value]')})