definitions
defe289bd6cb383c943b655c502679e2cfc
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 October 2015 11:47:11 am'); yourself)); add: (#id->#'e289bd6c-b383-c943-b655-c502679e2cfc'); add: (#block->[:in :out | out add: {#objects -> in}, [{
	#bounds -> (0@0 corner: 368@308).
	#current -> #unsavedChanges.
	#scripts -> #(#unsavedChanges ).
	#id -> #'40a98164-6ab3-db44-8db2-caa27b0c9f0c'.
	#out -> #(#(#interactive #'4cc8c555-00fc-e049-b56d-1ca0013dea25' ) #(#interactive #outer ) ).
	#in -> #(#(#automatic #outer ) ).
}] value]); add: (#sourceCode->'[:in :out | out add: {#objects -> in}, [{
	#bounds -> (0@0 corner: 368@308).
	#current -> #unsavedChanges.
	#scripts -> #(#unsavedChanges ).
	#id -> #''40a98164-6ab3-db44-8db2-caa27b0c9f0c''.
	#out -> #(#(#interactive #''4cc8c555-00fc-e049-b56d-1ca0013dea25'' ) #(#interactive #outer ) ).
	#in -> #(#(#automatic #outer ) ).
}] value]'); yourself)