definitions
defeaacc8b24e11bb4cab2b7aa0583b7467
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:organizer | organizer orderedDefinitions]).
(#class -> ViQueryMapDefinition).
(#id -> #'eaacc8b2-4e11-bb4c-ab2b-7aa0583b7467').
(#inputKind -> ViQueryOrganizer).
(#mapType -> #each).
(#outputKind -> ViQueryStepDefinition).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '6 September 2013 8:27:11 pm')})).
(#sourceCode -> '[:organizer | organizer orderedDefinitions]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})