definitions
defed9f3ef77d17c541b7cf2821cca31d6b
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:flag | flag comment]).
(#class -> ViQueryMapDefinition).
(#id -> #'ed9f3ef7-7d17-c541-b7cf-2821cca31d6b').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 September 2013 9:36:30 pm').
(#labelColor -> '007F00')})).
(#sourceCode -> '[:flag | flag comment]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})