definitions
defe289bd6cb383c943b655c502679e2cfc
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | out add: {#objects -> in}, [{
	#bounds -> (0@0 corner: 442@331).
	#current -> #unsavedChanges.
	#scripts -> #(#unsavedChanges ).
	#id -> #'40a98164-6ab3-db44-8db2-caa27b0c9f0c'.
	#out -> #(#(#interactive #'4cc8c555-00fc-e049-b56d-1ca0013dea25' ) #(#interactive #outer ) ).
	#in -> #(#(#automatic #outer ) ).
}] value]).
(#className -> #ViScriptDefinition).
(#id -> #'e289bd6c-b383-c943-b655-c502679e2cfc').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 October 2015 11:47:11 am')
})).
(#sourceCode -> '[:in :out | out add: {#objects -> in}, [{
	#bounds -> (0@0 corner: 442@331).
	#current -> #unsavedChanges.
	#scripts -> #(#unsavedChanges ).
	#id -> #''40a98164-6ab3-db44-8db2-caa27b0c9f0c''.
	#out -> #(#(#interactive #''4cc8c555-00fc-e049-b56d-1ca0013dea25'' ) #(#interactive #outer ) ).
	#in -> #(#(#automatic #outer ) ).
}] value]')
})