definitions
deffea3ce8f77511047846920e2e7346e54
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:mcp | mcp packageInfo systemCategories]).
(#class -> ViQueryMapDefinition).
(#id -> #'fea3ce8f-7751-1047-8469-20e2e7346e54').
(#inputKind -> MCPackage).
(#mapType -> #each).
(#outputKind -> String).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 September 2013 3:14:17 pm')})).
(#sourceCode -> '[:mcp | mcp packageInfo systemCategories]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})