definitions
deffaed7704ad2d7943947867ede63ba768
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | out add: [#'89c40fb8-551c-9e46-9651-f11978e9ff30'] value]).
(#class -> ViScriptDefinition).
(#id -> #'faed7704-ad2d-7943-9478-67ede63ba768').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:11.279834 pm')})).
(#sourceCode -> '[:in :out | out add: [#''89c40fb8-551c-9e46-9651-f11978e9ff30''] value]')})