definitions
deff49420f90ade234186347849db05d952
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'14 December 2015 11:52:58 am'); yourself)); add: (#id->#'f49420f9-0ade-2341-8634-7849db05d952'); add: (#block->[:in :out | in ifNotEmpty: [out add: [#defaultPropertiesExtended] value]]); add: (#sourceCode->'[:in :out | in ifNotEmpty: [out add: [#defaultPropertiesExtended] value]]'); yourself)