definitions
deff580aabf2330cf4aa12ca6207b1c8a93
	<definition>

	^ (Dictionary newFrom: {
(#block -> nil).
(#className -> #ViQuerySnippetDefinition).
(#id -> #'f580aabf-2330-cf4a-a12c-a6207b1c8a93').
(#inputKind -> TestCase).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 February 2014 1:59:53 pm')
})).
(#receiverIsCollection -> false).
(#sourceCode -> 'self debug.')
})