definitions
deff6032f7abaab74469764e0f1e97f6d34
	<definition>

	^ ((Dictionary new) add: (#inputKind->ViFlagComment); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 September 2013 7:46:49 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'f6032f7a-baab-7446-9764-e0f1e97f6d34'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:flag | #icon -> (flag priority = #high ifTrue: [ViEclipseIcons hprioTskIcon] ifFalse: [])]'); add: (#mapType->#each); add: (#block->[:flag | #icon -> (flag priority = #high ifTrue: [ViEclipseIcons hprioTskIcon] ifFalse: [])]); yourself)