definitions
defff90c055cbd6794d8d174f11adb2bd9a
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | out add: [#groupsMinimal] value]).
(#class -> ViQueryStepDefinition).
(#id -> #'ff90c055-cbd6-794d-8d17-4f11adb2bd9a').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:12.484834 pm')})).
(#sourceCode -> '[:in :out | out add: [#groupsMinimal] value]')})