definitions
deff5fcb65ace619f41be89945ee8be0d1b
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:o1 :o2 | o1 key <= o2 key]).
(#class -> ViQueryMapDefinition).
(#id -> #'f5fcb65a-ce61-9f41-be89-945ee8be0d1b').
(#inputKind -> Object).
(#mapType -> #twoArgs).
(#outputKind -> Boolean).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:o1 :o2 | o1 key <= o2 key]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})