definitions
deff88512ad81ddac4c8e82ff004696fed6
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | obj symbol]).
(#class -> ViQueryMapDefinition).
(#id -> #'f88512ad-81dd-ac4c-8e82-ff004696fed6').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:obj | obj symbol]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})