definitions
deff7a4445758fa9242a06b06f5a7784f40
	<definition>

	^ ((Dictionary new) add: (#inputKind->DirectoryEntry); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'6 December 2013 4:50:48 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->DirectoryEntryFile); add: (#id->#'f7a44457-58fa-9242-a06b-06f5a7784f40'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:entries | entries reject: [:e | e isDirectory]]'); add: (#mapType->#all); add: (#block->[:entries | entries reject: [:e | e isDirectory]]); yourself)