definitions
deff5ed8b900396e14ab7c7a384000dcbea
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | (PointerExplorerWrapper with: obj) contents]).
(#class -> ViQueryMapDefinition).
(#id -> #'f5ed8b90-0396-e14a-b7c7-a384000dcbea').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> ObjectExplorerWrapper).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '8 November 2013 3:52:47 pm')})).
(#sourceCode -> '[:obj | (PointerExplorerWrapper with: obj) contents]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})