definitions
deffabe7fbdc4f0094f94084b69675b5a93
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | ViObjectOriginService doObject: obj]).
(#class -> ViQueryStepDefinition).
(#id -> #'fabe7fbd-c4f0-094f-9408-4b69675b5a93').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:obj | ViObjectOriginService doObject: obj]')})