definitions
deff580aabf2330cf4aa12ca6207b1c8a93
	<definition>

	^ ((Dictionary new) add: (#class->ViQuerySnippetDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 February 2014 1:59:53 pm'); yourself)); add: (#id->#'f580aabf-2330-cf4a-a12c-a6207b1c8a93'); add: (#inputKind->TestCase); add: (#block->nil); add: (#sourceCode->'self debug.'); add: (#receiverIsCollection->false); yourself)