definitions
deff49420f90ade234186347849db05d952
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | in ifNotEmpty: [out add: [#defaultPropertiesExtended] value]]).
(#class -> ViScriptDefinition).
(#id -> #'f49420f9-0ade-2341-8634-7849db05d952').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '14 December 2015 11:52:58 am')})).
(#sourceCode -> '[:in :out | in ifNotEmpty: [out add: [#defaultPropertiesExtended] value]]')})