definitions
deff09a7901d8686c4da809bd45bde16a09
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | #text -> obj info time]).
(#class -> ViQueryMapDefinition).
(#id -> #'f09a7901-d868-6c4d-a809-bd45bde16a09').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:obj | #text -> obj info time]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})