definitions
deff79fab05e1b12b488d3e70b1b9af9e0f
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:flag | 'line ', flag line asString]).
(#class -> ViQueryStepDefinition).
(#id -> #'f79fab05-e1b1-2b48-8d3e-70b1b9af9e0f').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 September 2013 9:12:52 pm')})).
(#sourceCode -> '[:flag | ''line '', flag line asString]')})