definitions
defff1b9ab3bfd3544c820a325431fce6ee
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | out add: [#groupsMinimal] value]).
(#class -> ViQueryStepDefinition).
(#id -> #'ff1b9ab3-bfd3-544c-820a-325431fce6ee').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:11.714834 pm')})).
(#sourceCode -> '[:in :out | out add: [#groupsMinimal] value]')})