definitions
deff054ff68004cac4a8a95e8b6414caa98
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:def1 :def2 | def1 sourceCode <= def2 sourceCode]).
(#class -> ViQueryMapDefinition).
(#id -> #'f054ff68-004c-ac4a-8a95-e8b6414caa98').
(#inputKind -> Object).
(#mapType -> #twoArgs).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '4 December 2013 8:37:28 am')})).
(#sourceCode -> '[:def1 :def2 | def1 sourceCode <= def2 sourceCode]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})