definitions
deffea3ce8f77511047846920e2e7346e54
	<definition>

	^ ((Dictionary new) add: (#inputKind->MCPackage); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 September 2013 3:14:17 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->String); add: (#id->#'fea3ce8f-7751-1047-8469-20e2e7346e54'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:mcp | mcp packageInfo systemCategories]'); add: (#mapType->#each); add: (#block->[:mcp | mcp packageInfo systemCategories]); yourself)