definitions
deff6032f7abaab74469764e0f1e97f6d34
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:flag | #icon -> (flag priority = #high ifTrue: [ViEclipseIcons hprioTskIcon] ifFalse: [])]).
(#class -> ViQueryMapDefinition).
(#id -> #'f6032f7a-baab-7446-9764-e0f1e97f6d34').
(#inputKind -> ViFlagComment).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 September 2013 7:46:49 pm')})).
(#sourceCode -> '[:flag | #icon -> (flag priority = #high ifTrue: [ViEclipseIcons hprioTskIcon] ifFalse: [])]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})