definitions
deff2f9dad48d504c45b26783c97a117df9
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | ViObjectOriginService doObject: obj]).
(#class -> ViQueryStepDefinition).
(#id -> #'f2f9dad4-8d50-4c45-b267-83c97a117df9').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:obj | ViObjectOriginService doObject: obj]')})