definitions
defidentity
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:objects | objects]).
(#class -> ViQueryMapDefinition).
(#id -> #identity).
(#inputKind -> Object).
(#mapType -> #all).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:objects | objects]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})