definitions
defsubclasses
	<definition>

	^ ((Dictionary new) add: (#inputKind->Behavior); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Behavior); add: (#id->#subclasses); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:behavior | behavior subclasses]'); add: (#mapType->#each); add: (#block->[:behavior | behavior subclasses]); yourself)