definitions
defsubclasses
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:behavior | behavior subclasses]).
(#class -> ViQueryMapDefinition).
(#id -> #subclasses).
(#inputKind -> Behavior).
(#mapType -> #each).
(#outputKind -> Behavior).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:behavior | behavior subclasses]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})