steps
step7d7f7d20939a7c4e9a801915e705d82e
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'8171a213-b8ca-1248-b5d5-e386fc8a12e5').
(#iconCode -> 'nil').
(#id -> #'7d7f7d20-939a-7c4e-9a80-1915e705d82e').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'LOC').
(#labelColor -> '#AAAAAA').
(#priority -> 3090)}))})