steps
step19cadf89e6012b45be3bc5bcf0de5b35
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'c9754a97-bb74-8e41-b369-f6bc4bb81c0d').
(#iconCode -> 'UiSilkIcons chartBarIcon').
(#id -> #'19cadf89-e601-2b45-be3b-c5bcf0de5b35').
(#isProperty -> false).
(#isReference -> false).
(#label -> 'Frequency of Step Definitions').
(#next -> #'d0704ef9-0a64-0d44-9681-7487f8ee4e7b').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 4:21:57 pm').
(#inputKind -> ViQueryOrganizer).
(#outputKind -> Bag).
(#priority -> 950).
(#view -> ViTreeViewExtended)}))})