steps
step6d69dbf61d70234f9579df039b658aa0
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryReferenceStep).
(#definition -> nil).
(#iconCode -> 'nil').
(#id -> #'6d69dbf6-1d70-234f-9579-df039b658aa0').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '29 March 2019 5:05:19.02235 pm')})).
(#reference -> #'4b707439-66b1-c64b-805a-80c63759305e')})