steps
step432a6001f00e514ea68e4605686f7755
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #iconAndLabel).
(#iconCode -> 'nil').
(#id -> #'432a6001-f00e-514e-a68e-4605686f7755').
(#label -> nil).
(#next -> #'17c595bf-6cf3-1143-a13a-a297052fd4cc').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Object').
(#priority -> 2670)}))})