steps
stepaa3ec915c019e9418b9bf9baa09fd69a
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'4a160412-af62-9242-8483-cd08cd5b241f').
(#iconCode -> 'nil').
(#id -> #'aa3ec915-c019-e941-8b9b-f9baa09fd69a').
(#isProperty -> true).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 February 2014 10:22:16 am').
(#priority -> 5540).
(#view -> #text)
}))
})