steps
stepe3c616ba4453c04bb99791416620222a
	<step>

	^ ((Dictionary new) add: (#definition->#'e289bd6c-b383-c943-b655-c502679e2cfc'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#view->ViMultiPaneTiled); add: (#creationTimeStamp->'19 October 2015 11:47:11 am'); yourself)); add: (#isProperty->true); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'e3c616ba-4453-c04b-b997-91416620222a'); add: (#isReference->false); yourself)