steps
step5a501a24fd9a87418e5444a08209481a
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'0c3cb364-b408-444e-be67-6c71c2bdee55').
(#iconCode -> 'nil').
(#id -> #'5a501a24-fd9a-8741-8e54-44a08209481a').
(#isProperty -> false).
(#isReference -> false).
(#label -> 'Processes').
(#next -> #'93b6233e-a34e-f54d-9c6a-b7eeef30e075').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#isGlobal -> true).
(#priority -> 870).
(#view -> ViTreeViewExtended)}))})