steps
step18533aea2a404a4fb098e14e7fdcb291
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'245c4ce0-a93e-6943-8f4e-042ef3efa6a8').
(#iconCode -> 'nil').
(#id -> #'18533aea-2a40-4a4f-b098-e14e7fdcb291').
(#label -> 'Change Sets').
(#next -> #'fdc9d784-2f4f-8a42-8553-dfc7982b9585').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '5 June 2014 4:48:11 pm').
(#priority -> 6180)}))})