steps
step83cf71976cf5554eb5352b2ebf2fb60e
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'02fdc016-c7d4-774c-b567-7c9d4ed539b9').
(#iconCode -> 'nil').
(#id -> #'83cf7197-6cf5-554e-b535-2b2ebf2fb60e').
(#isProperty -> true).
(#label -> 'Byte codes').
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '24 February 2014 10:42:49 am').
(#priority -> 5820).
(#view -> ViTreeViewExtended)}))})