steps
step24a9922a802c1543acf7ff6d8dc30bbf
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #iconAndLabel).
(#iconCode -> 'nil').
(#id -> #'24a9922a-802c-1543-acf7-ff6d8dc30bbf').
(#label -> nil).
(#next -> #'eae7856b-17a8-2746-aa42-f06591c95280').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 September 2013 7:33:25 pm').
(#priority -> 3470)}))})