steps
step12f3cc3b319f8842a3d943b6034d0539
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'720a8d90-f7c1-334e-a4ea-5094ba285a8d').
(#iconCode -> 'nil').
(#id -> #'12f3cc3b-319f-8842-a3d9-43b6034d0539').
(#label -> nil).
(#next -> #'e62a3f59-4f57-1c4a-b8f1-2ea49415d52e').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 September 2013 7:11:16 pm').
(#priority -> 3390)}))})