steps
step07d98c15a20c0b459dc3ba44905e9a7a
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryReferenceStep).
(#definition -> nil).
(#iconCode -> 'nil').
(#id -> #'07d98c15-a20c-0b45-9dc3-ba44905e9a7a').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '29 March 2019 5:00:11.34035 pm').
(#view -> ViTreeViewExtended)})).
(#reference -> #'37989d23-0602-ed44-ad37-440cccc8d6d9')})