steps
stepa6b7eb35f794e7419102f303b6594f32
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'e22c6d26-271f-0145-b39a-d2f7d44aa913').
(#iconCode -> 'UiSilkIcons userSuitIcon').
(#id -> #'a6b7eb35-f794-e741-9102-f303b6594f32').
(#label -> 'Count Authors').
(#next -> #'d82ec0a6-a967-514a-953c-27fcb67ec3d3').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #defaultProperties).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 810)}))})