steps
step736c249139ee9f4c9abc4d4c87ef1a03
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'635033e3-7ada-9642-9335-413c12550d95').
(#iconCode -> 'nil').
(#id -> #'736c2491-39ee-9f4c-9abc-4d4c87ef1a03').
(#isProperty -> true).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 4940)}))})