steps
step17c595bf6cf31143a13aa297052fd4cc
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'c9ea5248-93e4-da4c-ad7b-4a56ef4e7187').
(#iconCode -> 'nil').
(#id -> #'17c595bf-6cf3-1143-a13a-a297052fd4cc').
(#isProperty -> true).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Origin').
(#labelColor -> '#AAAAAA').
(#priority -> 2680)}))})