steps
stepcf440614e202124f830d3b4a1d9eef00
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'df63e2e9-8e20-3c4f-971f-f54e51c9033e').
(#iconCode -> 'nil').
(#id -> #'cf440614-e202-124f-830d-3b4a1d9eef00').
(#isProperty -> false).
(#label -> nil).
(#next -> #'494bc6a5-c09d-fc4f-b22f-37955f890e49').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#oldCode -> '[:obj1 :obj2 | obj1 asString <= obj2 asString]').
(#outputKind -> Boolean).
(#priority -> 1630)
}))
})