steps
step8f80622f53f5844f807572405edfae0d
	<step>

	^ (Dictionary newFrom: {
(#'_def' -> (Dictionary newFrom: {
(#block -> [:in :out | out addAll: in]).
(#className -> #ViScriptDefinition).
(#id -> #'b37a1385-2a25-0848-befb-77dfe8044d98').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:11.393834 pm')
})).
(#sourceCode -> '[:in :out | out addAll: in]')
})).
(#className -> #ViScriptStep).
(#definition -> #'b37a1385-2a25-0848-befb-77dfe8044d98').
(#iconCode -> 'nil').
(#id -> #'8f80622f-53f5-844f-8075-72405edfae0d').
(#isProperty -> false).
(#label -> nil).
(#next -> #'a1816fcb-1266-bb43-8500-bf8b71248ede').
(#properties -> (Dictionary newFrom: {
(#after -> #(#groupsMinimal)).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:11.393834 pm')
}))
})