steps
step11b9014af6fa1a408446f63ddf69232f
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'b9ea6a9f-63d1-7d4e-a7e2-74493c799d30').
(#iconCode -> 'nil').
(#id -> #'11b9014a-f6fa-1a40-8446-f63ddf69232f').
(#isProperty -> false).
(#isReference -> false).
(#label -> 'Processes').
(#next -> #'71efc7d9-c3cb-7246-9652-6b74bc022b8e').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'5a501a24-fd9a-8741-8e54-44a08209481a').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#isGlobal -> true).
(#priority -> 6160).
(#view -> ViTreeViewExtended)}))})