steps
step9a8f7fe5e3fe5e4e8f65c463b0cac3e9
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'f5499ecb-55d4-5643-a59c-ff7b84874734').
(#iconCode -> 'nil').
(#id -> #'9a8f7fe5-e3fe-5e4e-8f65-c463b0cac3e9').
(#isProperty -> true).
(#label -> nil).
(#next -> #'e33fe689-cff8-ff4f-b574-d2a3b3986f94').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 February 2014 1:08:14 pm').
(#headerText -> #DMr).
(#priority -> 5320)
}))
})