steps
step5672f69dd1351d409f5ba8d58b762aa5
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'72afa9e5-7d79-104b-97b0-accfde7204b7').
(#iconCode -> 'nil').
(#id -> #'5672f69d-d135-1d40-9f5b-a8d58b762aa5').
(#label -> 'Pictures (nicer)').
(#next -> #'476a828e-2f7b-4b4a-9c8a-b515f83ac457').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 510).
(#view -> ViTreeViewExtended)}))})