steps
step761098d48a292a47be447677570b352e
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'490cdda4-45bc-414d-b6a5-e84c85f44b30').
(#iconCode -> 'nil').
(#id -> #'761098d4-8a29-2a47-be44-7677570b352e').
(#label -> 'Global variables').
(#next -> #'b193f637-d3a4-cb4b-9b3e-94c7b7ba29e9').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 10:06:57 am').
(#priority -> 860).
(#view -> ViTreeViewExtended)}))})