steps
stepc17a5204307f044bb7845a13673d0684
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'06fc91e1-5571-f846-b94c-6d710c844be5').
(#iconCode -> 'nil').
(#id -> #'c17a5204-307f-044b-b784-5a13673d0684').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '15 September 2013 5:43:59 pm').
(#priority -> 3580)}))})