steps
step71efc7d9c3cb724696526b74bc022b8e
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'bef82bf3-b23c-f44d-9d6b-c86d59afa5c8').
(#iconCode -> 'nil').
(#id -> #'71efc7d9-c3cb-7246-9652-6b74bc022b8e').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'5636df93-3a8f-ea44-9406-e602b99e3101').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 6380)}))})