steps
step2e77fdef881e274f91b744b1bb8e7e9c
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'49e02558-6e3e-0748-b0c1-b744754b910f').
(#iconCode -> 'nil').
(#id -> #'2e77fdef-881e-274f-91b7-44b1bb8e7e9c').
(#isProperty -> false).
(#isReference -> true).
(#label -> nil).
(#next -> #'37aa1dbd-bbd2-b242-9c7d-2efb85ce5e27').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:12.789834 pm')}))})