steps
stepd61e908712152d4eb336316c41064b72
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'81948c0e-8882-e34f-9ceb-0ec2ebedc648').
(#iconCode -> 'nil').
(#id -> #'d61e9087-1215-2d4e-b336-316c41064b72').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '23 July 2014 1:18:56 pm').
(#priority -> 6650)}))})