steps
stepc56e2e0c6b9a7b43a503dfea27e23d82
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'7fd3bade-f48e-c24d-8962-354e9676a6d2').
(#iconCode -> 'nil').
(#id -> #'c56e2e0c-6b9a-7b43-a503-dfea27e23d82').
(#label -> nil).
(#next -> #'e6e2433a-dfdd-7d4c-942a-ae804d9b9e29').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Name').
(#priority -> 2940)}))})