steps
step494f08eafbe58341b949c5ac1b22c09b
	<step>

	^ ((Dictionary new) add: (#definition->#'768fe1d5-783e-a546-b83a-016c4db6d552'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'15 December 2015 10:39:29 am'); yourself)); add: (#isProperty->true); add: (#next->#'46326a42-9071-7248-8541-10159c34c0a8'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'494f08ea-fbe5-8341-b949-c5ac1b22c09b'); add: (#isReference->false); yourself)