steps
step47ebfeaff6ff624a8fc6078f452527db
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupStep).
(#definition -> #'fd572dfd-7602-ae44-b123-a3d198f338b0').
(#iconCode -> 'nil').
(#id -> #'47ebfeaf-f6ff-624a-8fc6-078f452527db').
(#label -> nil).
(#next -> #'17740675-7772-7641-81dc-431205cff3b8').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '9 September 2013 3:27:49 pm').
(#priority -> 3270)}))})