steps
step6cd4db5cd2de844892b74f3c52589cf8
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'1c1144c6-2cce-c947-aec9-7b48023da265').
(#iconCode -> 'nil').
(#id -> #'6cd4db5c-d2de-8448-92b7-4f3c52589cf8').
(#isProperty -> false).
(#isReference -> false).
(#label -> 'Count Instance Variables').
(#next -> #'61afd65e-d943-5642-bd31-15492112b6ad').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#inputKind -> SystemNavigation).
(#priority -> 4670).
(#view -> ViTreeViewExtended)}))})