steps
stepf4803742eb440846908592c09d525159
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'1a63b3b5-dd5b-c242-b723-24e2fb3768d7').
(#iconCode -> 'nil').
(#id -> #'f4803742-eb44-0846-9085-92c09d525159').
(#label -> nil).
(#next -> #'69e497c2-4f93-4d49-84b1-94178c53e847').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '6 September 2013 8:28:17 pm').
(#priority -> 1010)}))})