steps
stepd003dd9abd31c14fbc56ea9cd47b3bb1
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'8d2906a9-399e-5747-8b83-d1b9309cb1db').
(#iconCode -> 'nil').
(#id -> #'d003dd9a-bd31-c14f-bc56-ea9cd47b3bb1').
(#isProperty -> false).
(#isReference -> false).
(#label -> 'Experiment').
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '20 May 2015 10:56:21 pm').
(#inputKind -> ViExperiment).
(#priority -> 10).
(#view -> ViExperimentView)}))})