steps
step2d49b98d3f27e14faaa8aee4706a6a0a
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'39285e02-e3ba-704f-9dfc-bf05f576b9d7').
(#iconCode -> 'nil').
(#id -> #'2d49b98d-3f27-e14f-aaa8-aee4706a6a0a').
(#isProperty -> true).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#labelColor -> '#AAAAAA').
(#priority -> 2480)}))})