steps
step5e40bd1a93876f42948e0dc9439c31c8
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'d5487647-ffe9-154b-9d5c-3cc2c971450e').
(#iconCode -> 'UiFugueIcons scriptArrowIcon').
(#id -> #'5e40bd1a-9387-6f42-948e-0dc9439c31c8').
(#label -> 'Implementors (recursive, symbols only)').
(#next -> #'a0abb65a-7c24-ff4a-a661-579881ae45e7').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 220).
(#view -> ViTreeViewExtended)}))})