steps
step5f25d26e227f9b45abc1644d5e129639
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'0c53b73c-4e16-1542-b40c-cd76a3b1dda5').
(#iconCode -> 'nil').
(#id -> #'5f25d26e-227f-9b45-abc1-644d5e129639').
(#label -> nil).
(#next -> #'5810152a-258e-1044-82c6-a1d1c4ad946a').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 September 2013 3:34:54 pm').
(#priority -> 3700)}))})