steps
step7951779362590c4d852f1225f668aba2
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'bfe36700-f08a-1845-b1d3-c30eccf37a29').
(#iconCode -> 'nil').
(#id -> #'79517793-6259-0c4d-852f-1225f668aba2').
(#label -> nil).
(#next -> #'00d6ab88-02b8-d343-98bf-44d2fb8c6ab5').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'edcd89de-8046-a844-bfde-c7aca99dba50').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 4070).
(#view -> ViTreeViewExtended)}))})