steps
stepc9208feb9579b54e83a343ffb87e69fa
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'91921a92-85c1-4046-bacf-5b8d2c22f236').
(#iconCode -> 'nil').
(#id -> #'c9208feb-9579-b54e-83a3-43ffb87e69fa').
(#label -> 'Diff').
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #identity).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 1:01:49 pm').
(#priority -> 6260)}))})