steps
stepbb553ae0c81d4641964f7f27055d9c15
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'caba53d0-beeb-e349-9e02-eddcd6930b08').
(#iconCode -> 'nil').
(#id -> #'bb553ae0-c81d-4641-964f-7f27055d9c15').
(#isProperty -> true).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#hAlignment -> #right).
(#headerText -> 'Size').
(#labelColor -> '#AAAAAA').
(#priority -> 4550)}))})