steps
stepe6902a58ee3c7a4993758c1501d23175
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #iconAndLabel).
(#iconCode -> 'nil').
(#id -> #'e6902a58-ee3c-7a49-9375-8c1501d23175').
(#label -> nil).
(#next -> #'458cbad9-3001-ab46-8458-4bb4c3232229').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '15 September 2013 5:35:42 pm').
(#priority -> 3570)}))})