steps
stepf128659b7f02364dafc1143f418bf135
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'6cf2af52-49e3-484c-a268-8783121ba43a').
(#iconCode -> 'nil').
(#id -> #'f128659b-7f02-364d-afc1-143f418bf135').
(#isProperty -> false).
(#label -> nil).
(#next -> #'266651fd-1b71-0244-ac45-79f564404cc5').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '7 November 2013 10:51:34 am').
(#priority -> 5460)}))})