steps
stepe2c47fce01c22d40aef44fae92dba501
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'3947d99b-5129-0a4d-86e5-5b34e5b2c414').
(#iconCode -> 'nil').
(#id -> #'e2c47fce-01c2-2d40-aef4-4fae92dba501').
(#isProperty -> false).
(#isReference -> true).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '29 March 2019 5:00:11.34035 pm')}))})