steps
step8c87a9e9a74c3749b4bab8960612b464
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'524c9479-77b0-664a-87a3-626871241adc').
(#iconCode -> 'nil').
(#id -> #'8c87a9e9-a74c-3749-b4ba-b8960612b464').
(#isProperty -> false).
(#isReference -> true).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '1 June 2015 1:44:09 pm')}))})