steps
step8aa2299483215647823f8e9203115b01
	<step>

	^ (Dictionary newFrom: {
(#'_def' -> (Dictionary newFrom: {
(#block -> [:in :out | out addAll: in]).
(#className -> #ViScriptDefinition).
(#id -> #'73717316-edf3-0d4d-b96f-250a2ed95c7d').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '9 December 2015 9:44:59 am')
})).
(#sourceCode -> '[:in :out | out addAll: in]')
})).
(#className -> #ViScriptStep).
(#definition -> #'73717316-edf3-0d4d-b96f-250a2ed95c7d').
(#iconCode -> 'nil').
(#id -> #'8aa22994-8321-5647-823f-8e9203115b01').
(#isProperty -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#after -> #(#senders)).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '9 December 2015 9:44:59 am')
}))
})