steps
step6a2bc04714abcb4fbd8a9a78f9bc2bea
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'faed7704-ad2d-7943-9478-67ede63ba768').
(#iconCode -> 'nil').
(#id -> #'6a2bc047-14ab-cb4f-bd8a-9a78f9bc2bea').
(#isProperty -> false).
(#isReference -> true).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '29 March 2019 5:00:11.33835 pm')}))})