steps
stepf7ba224a8f8ec1479bec928cd5537411
	<step>

	^ ((Dictionary new) add: (#definition->#'ae614fa7-bdf2-4940-8e18-ad7542e24f44'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'9 December 2015 1:06:03 pm'); yourself)); add: (#isProperty->false); add: (#next->#'ed4cdeb4-e8e8-f64a-9016-e09729155d02'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'f7ba224a-8f8e-c147-9bec-928cd5537411'); add: (#isReference->false); yourself)