steps
step800f6eb35d933a44b9d4965af821cc38
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'80d690ae-5ea9-2d40-87b4-2b8c1b10c7e4').
(#iconCode -> 'nil').
(#id -> #'800f6eb3-5d93-3a44-b9d4-965af821cc38').
(#label -> nil).
(#next -> #'a36810b7-a281-b34d-9d22-e1f1a585db30').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '23 September 2013 5:15:04 pm').
(#priority -> 4120)}))})