steps
step91c9c5aa8933524c908c609b3a1fc00a
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'889c4b1a-c134-b247-81b3-f1f186198c7e').
(#iconCode -> 'nil').
(#id -> #'91c9c5aa-8933-524c-908c-609b3a1fc00a').
(#label -> nil).
(#next -> #'e6cb8658-3697-3849-9a2c-fae04d157f52').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '6 June 2014 5:22:34 pm').
(#priority -> 6270)}))})