steps
stepdefaultPropertiesExtended
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'81e09cb2-b3ab-b345-b591-fd828ea01434').
(#iconCode -> 'nil').
(#id -> #defaultPropertiesExtended).
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'4ea99278-df36-f648-a9dc-f35da9d613ed').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '20 May 2015 2:52:45 pm')}))})