steps
step46326a4290717248854110159c34c0a8
	<step>

	^ ((Dictionary new) add: (#definition->#'0245d375-1a75-294e-8526-405c4f49aa48'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'15 December 2015 10:39:29 am'); yourself)); add: (#isProperty->true); add: (#next->#'489ae0c0-62e5-6543-9fde-b10d002ed318'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'46326a42-9071-7248-8541-10159c34c0a8'); add: (#isReference->false); yourself)