steps
step9116a93ca93f224dabf174f2e5067a77
	<step>

	^ ((Dictionary new) add: (#definition->#'8a196207-ea94-b944-901f-dd53bce5fd8a'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->String); add: (#priority->220); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'14 December 2015 11:30:58 am'); yourself)); add: (#isProperty->false); add: (#next->#'a718839b-0562-2649-8d2e-fcb3995dd716'); add: (#label->'Classes in category'); add: (#iconCode->'UiSilkIcons carIcon'); add: (#id->#'9116a93c-a93f-224d-abf1-74f2e5067a77'); add: (#isReference->false); yourself)