steps
step97b22eff73d84746b8774dc3d77e1208
	<step>

	^ (Dictionary newFrom: {
(#'_def' -> (Dictionary newFrom: {
(#block -> [:in :out | out addAll: in]).
(#className -> #ViScriptDefinition).
(#id -> #'5389ac08-4249-614e-961f-06d2d75458c6').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '20 May 2015 12:12:18 pm')
})).
(#sourceCode -> '[:in :out | out addAll: in]')
})).
(#className -> #ViScriptStep).
(#definition -> #'5389ac08-4249-614e-961f-06d2d75458c6').
(#iconCode -> 'nil').
(#id -> #'97b22eff-73d8-4746-b877-4dc3d77e1208').
(#isProperty -> false).
(#label -> nil).
(#next -> #'43dad8cd-aa5a-f540-bf91-5c505349e324').
(#properties -> (Dictionary newFrom: {
(#after -> #(#groups)).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '20 May 2015 12:12:18 pm')
}))
})