steps
step94e3fbd008adea49aa1d8bf2961de5fc
	<step>

	^ (Dictionary newFrom: {
(#'_def' -> (Dictionary newFrom: {
(#block -> [:in :out | out addAll: in]).
(#className -> #ViScriptDefinition).
(#id -> #'1b368e84-fb3a-6e42-b68e-7076124c7ab6').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 October 2015 11:12:34 am')
})).
(#sourceCode -> '[:in :out | out addAll: in]')
})).
(#className -> #ViScriptStep).
(#definition -> #'1b368e84-fb3a-6e42-b68e-7076124c7ab6').
(#iconCode -> 'nil').
(#id -> #'94e3fbd0-08ad-ea49-aa1d-8bf2961de5fc').
(#isProperty -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#after -> #(#groupsUnsorted)).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 October 2015 11:12:34 am').
(#inputKind -> #(nil nil))
}))
})