steps
step0166bc3dc272b14b97b82735b475543c
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'da496217-77f2-ba44-a2d7-0d804e4e9dee').
(#iconCode -> 'nil').
(#id -> #'0166bc3d-c272-b14b-97b8-2735b475543c').
(#isProperty -> false).
(#isReference -> true).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '29 March 2019 5:00:11.33835 pm')}))})