steps
step947402835bf2514e8eefb18ce867137a
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'7d5f2ec3-3445-3748-b2a2-7e6b8c4e2d84').
(#iconCode -> 'nil').
(#id -> #'94740283-5bf2-514e-8eef-b18ce867137a').
(#label -> nil).
(#next -> #'49d802a1-3f51-514e-accf-7854f6e8d622').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 February 2014 11:33:53 am').
(#priority -> 5560)}))})