steps
step42ef8b6b8cf0da4ab0750fb0146d805c
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'f9974083-86d5-d54f-9ee0-ba85d5b22720').
(#iconCode -> 'nil').
(#id -> #'42ef8b6b-8cf0-da4a-b075-0fb0146d805c').
(#label -> nil).
(#next -> #'1cd2a5a3-05f3-9046-8fd2-06f0a076f80b').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Size').
(#labelColor -> '#AAAAAA').
(#priority -> 2790)}))})