steps
step805f3b27a219f941ada8c489c9fd753d
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'0c32b445-e778-024f-8375-7de9bdce9985').
(#iconCode -> 'nil').
(#id -> #'805f3b27-a219-f941-ada8-c489c9fd753d').
(#isProperty -> false).
(#label -> nil).
(#next -> #'ebd29250-144e-7b45-bd3a-2ad394ef1b4a').
(#properties -> (Dictionary newFrom: {
(#after -> #(#groups)).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '20 May 2015 2:48:29 pm')
}))
})