steps
step3ded3e1d2e885448a30216e605bc65a0
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQuerySortStep).
(#definition -> #compareObjectsBySelector).
(#iconCode -> 'nil').
(#id -> #'3ded3e1d-2e88-5448-a302-16e605bc65a0').
(#label -> nil).
(#next -> #'d85efa7f-9578-8341-a110-19f9ca847c76').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 September 2013 7:36:18 pm').
(#priority -> 3500)}))})