steps
stepf977b925bca88e418e7a33672b08eb1d
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'7d6afad5-febc-a342-b987-8114fc622713').
(#iconCode -> 'nil').
(#id -> #'f977b925-bca8-8e41-8e7a-33672b08eb1d').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Message').
(#labelColor -> '#AAAAAA').
(#priority -> 2970)}))})