steps
step96d77081b7de93458536a0d326322f6e
	<step>

	^ (Dictionary newFrom: {
(#'_def' -> (Dictionary newFrom: {
(#block -> [:in :out | out addAll: in]).
(#className -> #ViScriptDefinition).
(#id -> #'75d09853-4032-ac47-a682-ee8bf116e232').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:11.705834 pm')
})).
(#sourceCode -> '[:in :out | out addAll: in]')
})).
(#className -> #ViScriptStep).
(#definition -> #'75d09853-4032-ac47-a682-ee8bf116e232').
(#iconCode -> 'UiFugueIcons arrowStepIcon').
(#id -> #'96d77081-b7de-9345-8536-a0d326322f6e').
(#isProperty -> false).
(#label -> 'References (recursive)').
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#after -> #(#'b510b1f4-2f4c-514a-bd82-a354adbf042f')).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '15 September 2013 5:49:24 pm').
(#priority -> 540).
(#view -> ViTreeViewExtended)
}))
})