steps
step1a584c05b8fcdc438564d48f2c2b954b
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'664dac2d-ff00-6c42-a83d-3a52f5a83749').
(#iconCode -> 'UiFugueIcons keyboardExclamationIcon').
(#id -> #'1a584c05-b8fc-dc43-8564-d48f2c2b954b').
(#label -> 'Inconsistent grab-/hasKeyboard').
(#next -> #'5b3d233e-c93c-0b42-b8ba-fafb41d70a9e').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 740)}))})