steps
step7585127607a784408574cc2965065a02
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'04cd8f62-90d7-d34d-9244-32acdce5c4a9').
(#iconCode -> 'nil').
(#id -> #'75851276-07a7-8440-8574-cc2965065a02').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'554c12a4-3ed5-904d-8ada-bb3d129a200a').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '21 February 2014 8:53:15 am').
(#headerText -> 'Write').
(#priority -> 5970)}))})