steps
stepworkspace
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'fece5f9a-89de-2e4e-b5e6-8f0c8255c2c5').
(#iconCode -> 'UiFugueIcons applicationTerminalIcon').
(#id -> #workspace).
(#isProperty -> false).
(#isReference -> false).
(#label -> 'Workspace').
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '24 August 2016 4:50:38 pm').
(#isGlobal -> true).
(#priority -> 500).
(#view -> ViWorkspaceView)}))})