steps
step2fca62099c2dc644823aacf2909bad0f
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupSortStep).
(#definition -> #compareObjectsAsStrings).
(#iconCode -> 'nil').
(#id -> #'2fca6209-9c2d-c644-823a-acf2909bad0f').
(#label -> nil).
(#next -> #'26f3a2b2-f47a-644b-ac5f-159e2365b955').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'2fca6209-9c2d-c644-823a-acf2909bad0f').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1280)}))})