steps
stepfcbd4f9fbe45b445ae2e7b432040e8fd
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'7b8f1fcb-2866-5a41-872d-15f9bd110ddf').
(#iconCode -> 'UiSilkIcons pageWhiteTextWidthIcon').
(#id -> #'fcbd4f9f-be45-b445-ae2e-7b432040e8fd').
(#label -> 'Load Text File').
(#next -> #'b0443283-7194-df4e-bcb6-2dc3d3395f1b').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 720)}))})