steps
step5c3b9aae476ecc4f96a1da5e5ab421ad
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'f5ef5258-c40e-b249-bb60-21345a72465d').
(#iconCode -> 'nil').
(#id -> #'5c3b9aae-476e-cc4f-96a1-da5e5ab421ad').
(#isProperty -> true).
(#label -> nil).
(#next -> #'9cab60cb-31ee-7f4b-8cac-34c9bed5c6ab').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Object').
(#priority -> 3140)
}))
})