steps
step985a7a4ba46d7744abf1de2be369fc56
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'dd5ac176-8ae8-5d49-b080-38900d03870b').
(#iconCode -> 'UiFugueIcons magnifierMediumIcon').
(#id -> #'985a7a4b-a46d-7744-abf1-de2be369fc56').
(#label -> 'Receiver Inspector').
(#next -> #'bce4eb13-a02d-144e-96b2-cd2944b85fee').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #identity).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 1:01:49 pm').
(#priority -> 5160)}))})