steps
step0bf4254ac61595498fa0434b920f8c2a
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'06752cb1-e5f3-b847-8946-50a90ce30938').
(#iconCode -> 'nil').
(#id -> #'0bf4254a-c615-9549-8fa0-434b920f8c2a').
(#label -> 'System categories').
(#next -> #'a4ac81fc-d21c-7240-abf8-68d76d2dc175').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 February 2014 3:56:01 pm').
(#priority -> 5620)}))})