steps
step0c69c004a3f9134e8ba6eafca2418592
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'1db1df87-dcb9-2542-b17b-bc902869ba5d').
(#iconCode -> 'UiSilkIcons starIcon').
(#id -> #'0c69c004-a3f9-134e-8ba6-eafca2418592').
(#label -> 'Singletons and defaults').
(#next -> #'f45b857e-e698-274c-b3d6-467851b2d5dc').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #defaultProperties).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 4430)}))})