steps
step1e6aa701f25e1844bcd03fbe2c74df42
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'a5bc60d1-63c3-8c42-9039-698a5f637754').
(#iconCode -> 'nil').
(#id -> #'1e6aa701-f25e-1844-bcd0-3fbe2c74df42').
(#label -> nil).
(#next -> #'074a7165-1020-0442-8a76-a2ce9f8ab3e6').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 September 2013 7:45:26 pm').
(#priority -> 760).
(#view -> ViTreeViewExtended)}))})