steps
step225b70fb8963d84aa825589a864d6670
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'7efc470b-3c31-7447-bde1-aa0d3880edeb').
(#iconCode -> 'nil').
(#id -> #'225b70fb-8963-d84a-a825-589a864d6670').
(#isProperty -> true).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Origin').
(#labelColor -> '#AAAAAA').
(#priority -> 2870)
}))
})