steps
stepbe6764e29533b84ead01796ac5f86383
	<step>

	^ ((Dictionary new) add: (#definition->#'e855e1ac-7b53-0348-9757-f5a8f7e54b1d'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'9 December 2015 1:06:03 pm'); yourself)); add: (#isProperty->true); add: (#next->#'f7ba224a-8f8e-c147-9bec-928cd5537411'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'be6764e2-9533-b84e-ad01-796ac5f86383'); add: (#isReference->false); yourself)