steps
stepe0f288dd4846714bbdc86b0065de1f63
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'47cabae4-3c61-3b4f-a16b-87529b48d989').
(#iconCode -> 'UiFugueIcons blockIcon').
(#id -> #'e0f288dd-4846-714b-bdc8-6b0065de1f63').
(#label -> 'Instance variable references').
(#next -> #'e505710c-f722-e34e-a85e-f914106ea5cb').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 270)}))})