steps
stepd7717fb24d049a42a74d4a8e8f3a891c
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'db7f0d5a-6752-f64d-84de-65b1da6f1009').
(#iconCode -> 'nil').
(#id -> #'d7717fb2-4d04-9a42-a74d-4a8e8f3a891c').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'e45648f8-4fef-f343-8972-cbb555789355').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '14 February 2014 11:06:30 am').
(#headerText -> #D).
(#priority -> 5280)}))})