steps
step8b960b669ca1c54bbae0ba8e5375c1f7
	<step>

	^ (Dictionary newFrom: {
(#'_def' -> (Dictionary newFrom: {
(#block -> [:in :out | out addAll: in]).
(#className -> #ViScriptDefinition).
(#id -> #'93eef3eb-9e6e-3941-9a7e-6f549bac420b').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:11.253834 pm')
})).
(#sourceCode -> '[:in :out | out addAll: in]')
})).
(#className -> #ViScriptStep).
(#definition -> #'93eef3eb-9e6e-3941-9a7e-6f549bac420b').
(#iconCode -> 'nil').
(#id -> #'8b960b66-9ca1-c54b-bae0-ba8e5375c1f7').
(#isProperty -> false).
(#label -> nil).
(#next -> #'e689b659-27f3-0f4a-9412-ab39abc2b63e').
(#properties -> (Dictionary newFrom: {
(#after -> #(#groupsMinimal)).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:11.251834 pm')
}))
})