steps
stepoutline
	<step>

	^ ((Dictionary new) add: (#definition->#'e50b9af1-42f0-5a44-ba3d-be27b8cb0fdf'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->ClassDescription); add: (#creationTimeStamp->'12 May 2015 4:39:25 pm'); add: (#view->[ViScriptPart useHorizontalLists
		ifTrue: [ViListView]
		ifFalse: [ViTreeViewExtended]]); add: (#creationAuthor->'mt'); add: (#priority->40); add: (#notifier->ViSystemChangeNotifier); add: (#isNew->false); add: (#orientation->[ViScriptPart useHorizontalLists
		ifTrue: [#horizontal]
		ifFalse: [#default]]); yourself)); add: (#isProperty->false); add: (#next->#'dd56b3e9-9e71-b44e-9a60-5319116f9cdd'); add: (#label->'Outline'); add: (#iconCode->'nil'); add: (#id->#outline); add: (#isReference->false); yourself)