steps
stepfdb69e0a57ea394aa74ab986817dca93
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'373bc1f9-5de5-fc4e-a4f5-40f4f88b3944').
(#iconCode -> 'nil').
(#id -> #'fdb69e0a-57ea-394a-a74a-b986817dca93').
(#isProperty -> true).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#labelColor -> '#AAAAAA').
(#priority -> 3190)
}))
})