steps
stepccdeb4ee852e184980822d3e37a2cf44
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'31152db4-2b7f-fe48-864d-bfc1f9f4ee9c').
(#iconCode -> 'nil').
(#id -> #'ccdeb4ee-852e-1849-8082-2d3e37a2cf44').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Timestamp').
(#labelColor -> '#AAAAAA').
(#priority -> 2930)}))})