steps
step8451e0da6c997f419483316176f07642
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'da8a8f50-3e4c-d44c-9f64-45781be27672').
(#iconCode -> 'nil').
(#id -> #'8451e0da-6c99-7f41-9483-316176f07642').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'dc34144d-6524-cf48-a9a5-903457596587').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '20 May 2015 2:49:42 pm')}))})