steps
step5e1d1190aaa3274982c2010ce8a97d2f
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'055d25a7-a977-1a44-990b-d742711caaf1').
(#iconCode -> 'nil').
(#id -> #'5e1d1190-aaa3-2749-82c2-010ce8a97d2f').
(#isProperty -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#after -> #(#'494bc6a5-c09d-fc4f-b22f-37955f890e49')).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '29 March 2019 5:00:11.33635 pm')
}))
})