steps
step2b022238c9a7fe4b8d2bfa5c2250af5d
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'a5066753-64c1-b04f-b645-d66d41db274d').
(#iconCode -> 'nil').
(#id -> #'2b022238-c9a7-fe4b-8d2b-fa5c2250af5d').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 February 2014 8:38:57 am').
(#priority -> 5520).
(#view -> #text)}))})