steps
stepa0430b669a7df044be09b17780bf171f
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'f39023a5-0e5c-b548-b9e4-f8b70a8bbc2f').
(#iconCode -> 'nil').
(#id -> #'a0430b66-9a7d-f044-be09-b17780bf171f').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'80d8228d-c6ed-1744-8301-762c72d90211').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 4810)}))})