steps
step201c9e15bd34ba46bf107b546e1fa6f8
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupSortStep).
(#definition -> #compareObjectsAsStrings).
(#iconCode -> 'nil').
(#id -> #'201c9e15-bd34-ba46-bf10-7b546e1fa6f8').
(#label -> nil).
(#next -> #'d1ab46b3-df50-534c-b593-d1e6683fe045').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1530)}))})