steps
step81adf2f92129c5449bc0ab5207f80462
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupSortStep).
(#definition -> #compareObjectsAsStrings).
(#iconCode -> 'nil').
(#id -> #'81adf2f9-2129-c544-9bc0-ab5207f80462').
(#label -> nil).
(#next -> #'e84072d2-c593-f549-a93c-d5dbeb2e3b94').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1360)}))})