steps
stepc2156a98722e7b46a844364bee591c7a
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'7500e5a0-9966-4645-a6e4-51a9ac020852').
(#iconCode -> 'nil').
(#id -> #'c2156a98-722e-7b46-a844-364bee591c7a').
(#label -> 'Preview').
(#next -> #'d62c8659-3292-5541-b3b6-08b9ff46de99').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #identity).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 1:01:49 pm').
(#priority -> 6230)}))})