steps
step4762774bb64ef14b8e4ad0fc1dc20251
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #allMethodsForClass).
(#iconCode -> 'nil').
(#id -> #'4762774b-b64e-f14b-8e4a-d0fc1dc20251').
(#label -> 'Methods w/ timestamp').
(#next -> #'172f485a-7e69-0d4a-a5ad-7233f83da2dc').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 240).
(#view -> ViTreeViewExtended)}))})