steps
step1b7534bd882c2d458ff704510695ae1c
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'532b388c-e4ee-b544-be59-7d3619e04e42').
(#iconCode -> 'nil').
(#id -> #'1b7534bd-882c-2d45-8ff7-04510695ae1c').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#copyOf -> #'e3c616ba-4453-c04b-b997-91416620222a').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 October 2015 2:07 pm').
(#view -> ViMultiPaneTiled)}))})