steps
step4b63ef1b75d9fc4d977720db142525af
	<step>

	^ ((Dictionary new) add: (#definition->#'61d466bc-34b3-d14d-ad0c-371ec9f29cbe'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->Object); add: (#priority->1000); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'9 December 2015 10:14:14 am'); yourself)); add: (#isProperty->false); add: (#next->#'efdca18a-2072-5c45-ac92-55b2a17ad4eb'); add: (#label->'Browse object''s class'); add: (#iconCode->'nil'); add: (#id->#'4b63ef1b-75d9-fc4d-9777-20db142525af'); add: (#isReference->false); yourself)