steps
step297515f311ce2e4594a2b23a6cad1586
	<step>

	^ ((Dictionary new) add: (#definition->#'7655c1c8-f426-3443-89a8-bb6a0b28181b'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->RBProgramNode); add: (#priority->300); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'9 December 2015 11:26:37 am'); add: (#isNew->false); yourself)); add: (#isProperty->true); add: (#next->#'d7ca2eac-e77d-c24a-9906-a486603160a0'); add: (#label->'AST'); add: (#iconCode->'nil'); add: (#id->#'297515f3-11ce-2e45-94a2-b23a6cad1586'); add: (#isReference->false); yourself)