steps
step31297e2396f54144a0413821519b9f1e
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'fef44613-dcb6-db48-b26e-678159464e39').
(#iconCode -> 'UiSilkIcons carDeleteIcon').
(#id -> #'31297e23-96f5-4144-a041-3821519b9f1e').
(#label -> 'Unused Classes').
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 September 2013 7:37:43 pm').
(#priority -> 770).
(#view -> ViTreeViewExtended)}))})