steps
step92fe37788879e9408170a3677bb8df1c
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryReferenceStep).
(#definition -> nil).
(#iconCode -> 'nil').
(#id -> #'92fe3778-8879-e940-8170-a3677bb8df1c').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '29 March 2019 5:05:19.02235 pm')})).
(#reference -> #'962950ed-4ad4-244b-9e1b-512547f2422f')})