steps
step25668ab353832a4b8bc25d22ac2cc3fe
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #copyToContext).
(#iconCode -> 'nil').
(#id -> #'25668ab3-5383-2a4b-8bc2-5d22ac2cc3fe').
(#label -> nil).
(#next -> #'12f3cc3b-319f-8842-a3d9-43b6034d0539').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 September 2013 7:19:58 pm').
(#priority -> 3430)}))})