steps
step58fabb91d27b8e47b2080f6ee4958df1
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'25ba5d71-aab6-224f-b0c7-1fe9151c9ecc').
(#iconCode -> 'nil').
(#id -> #'58fabb91-d27b-8e47-b208-0f6ee4958df1').
(#label -> nil).
(#next -> #'19aa31e9-da2d-0646-bcb5-c43217a64c10').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #defaultProperties).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 640)}))})