steps
step24d74d145e317641a5f6d6667eb3ffd2
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'33142aab-4e05-3248-ad60-a51e6685352b').
(#iconCode -> 'nil').
(#id -> #'24d74d14-5e31-7641-a5f6-d6667eb3ffd2').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'26f3a2b2-f47a-644b-ac5f-159e2365b955').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 6560)}))})