steps
step1ab8a66adb32f44587b20c2967596906
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'aea63ea8-7330-d94d-9826-f54d88aca22f').
(#iconCode -> 'nil').
(#id -> #'1ab8a66a-db32-f445-87b2-0c2967596906').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '23 July 2014 11:18:20 am').
(#priority -> 6570)}))})