steps
step3640f74268dde143aec9907f1f87a99b
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'0c53b73c-4e16-1542-b40c-cd76a3b1dda5').
(#iconCode -> 'nil').
(#id -> #'3640f742-68dd-e143-aec9-907f1f87a99b').
(#label -> nil).
(#next -> #'ef81aed0-ae2d-6548-904f-030b28e12e97').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 September 2013 7:15:17 pm').
(#priority -> 3810)}))})