steps
step263f43b53e25214b93bef88d5ecf84b5
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'77f98485-09d8-e34c-bb69-a66a7a0d4a45').
(#iconCode -> 'ViEclipseIcons breakpointViewIcon').
(#id -> #'263f43b5-3e25-214b-93be-f88d5ecf84b5').
(#label -> 'Breakpoints').
(#next -> #'829e7d5e-2892-544a-a015-d5efe0983785').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #defaultProperties).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 4010).
(#view -> ViTreeViewExtended)}))})