steps
step93b6233ea34ef54d9c6ab7eeef30e075
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'d905ce02-2192-9c48-9eb3-ceb8d1ceaf80').
(#iconCode -> 'nil').
(#id -> #'93b6233e-a34e-f54d-9c6a-b7eeef30e075').
(#label -> nil).
(#next -> #'fb5f9d48-49cf-774c-921f-e9598b74d2c7').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'d9634b11-bde6-1a40-a0b4-7be880afc37a').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 4320)}))})