steps
stepafb03b2b6810684f853c74918c6c73e3
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'92d66888-3e33-e449-82ee-fc6d9fdf72e6').
(#iconCode -> 'nil').
(#id -> #'afb03b2b-6810-684f-853c-74918c6c73e3').
(#label -> nil).
(#next -> #'d4231597-1147-6f42-8714-146585f297d8').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '20 February 2014 3:44:05 pm').
(#headerText -> 'Selector').
(#priority -> 5990)}))})