steps
step19aa31e9da2d0646bcb5c43217a64c10
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'002e2364-d450-4944-a460-20f93f2ada42').
(#iconCode -> 'nil').
(#id -> #'19aa31e9-da2d-0646-bcb5-c43217a64c10').
(#isProperty -> false).
(#isReference -> false).
(#label -> 'Classes by Author').
(#next -> #'7f7cb928-c2c5-c840-8c91-995fa40b1fd5').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 November 2013 4:16:23 pm').
(#inputKind -> String).
(#outputKind -> Behavior).
(#priority -> 4380).
(#view -> ViTreeViewExtended)}))})