steps
stepccb87580d74cdc47a558206c68840342
	<step>

	^ (Dictionary newFrom: {
(#'_def' -> (Dictionary newFrom: {
(#block -> [:in :out | out addAll: in]).
(#className -> #ViScriptDefinition).
(#id -> #'5fbe5c7f-6f1f-ad40-81ab-faf3f9ee4b4d').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '14 December 2015 11:53:32 am')
})).
(#sourceCode -> '[:in :out | out addAll: in]')
})).
(#className -> #ViScriptStep).
(#definition -> #'5fbe5c7f-6f1f-ad40-81ab-faf3f9ee4b4d').
(#iconCode -> 'nil').
(#id -> #'ccb87580-d74c-dc47-a558-206c68840342').
(#isProperty -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#after -> #(#'9b96cd37-e54b-5649-b04d-d585c24b8303')).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '14 December 2015 11:53:32 am')
}))
})