steps
step600d833722a7304b8565430e818154ce
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'eed54386-9a8f-024e-90ba-9efea47b5d59').
(#iconCode -> 'nil').
(#id -> #'600d8337-22a7-304b-8565-430e818154ce').
(#isProperty -> false).
(#isReference -> false).
(#label -> 'Classes by Category').
(#next -> #'0d396a44-b27e-f545-a69d-d25485dfe138').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'0bf4254a-c615-9549-8fa0-434b920f8c2a').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 February 2014 3:56:01 pm').
(#outputKind -> SystemOrganizer).
(#priority -> 5640).
(#view -> ViTreeViewExtended)}))})