steps
stepa0abb65a7c24ff4aa661579881ae45e7
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQuerySortStep).
(#definition -> #compareObjectsAsStrings).
(#iconCode -> 'nil').
(#id -> #'a0abb65a-7c24-ff4a-a661-579881ae45e7').
(#label -> nil).
(#next -> #'cf440614-e202-124f-830d-3b4a1d9eef00').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1620)}))})