steps
stepa8d8130a271c954eaca4bad9c8477a24
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'f5d1a80e-5581-d84c-a2d2-c5e8bcf5b4a4').
(#iconCode -> 'nil').
(#id -> #'a8d8130a-271c-954e-aca4-bad9c8477a24').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '8 November 2013 4:11:08 pm').
(#labelColor -> '#000000').
(#priority -> 4230)}))})