steps
stepeb55b2aeb8c0504395aba2f9497d4956
	<step>

	^ ((Dictionary new) add: (#definition->#'0a99bf89-fc80-d44d-83e9-2d70789cf056'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->ClassDescription); add: (#creationAuthor->'mt'); add: (#view->ViClassDefinitionEditorView); add: (#creationTimeStamp->'14 December 2015 11:20:18 am'); add: (#priority->300); yourself)); add: (#isProperty->false); add: (#next->nil); add: (#label->'Source code'); add: (#iconCode->'UiSilkIcons pencilIcon'); add: (#id->#'eb55b2ae-b8c0-5043-95ab-a2f9497d4956'); add: (#isReference->false); yourself)