steps
stepa8d9e9fc0bb3384b9baee3c1edb07163
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'0966e950-26e6-d542-a2aa-2e1e6ea3e0f6').
(#iconCode -> 'nil').
(#id -> #'a8d9e9fc-0bb3-384b-9bae-e3c1edb07163').
(#isProperty -> true).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 February 2014 11:23:26 am').
(#priority -> 5550)
}))
})