steps
step22d7a896a0a2af4d863ef70f5ed40ff9
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'8f3ecf9e-7b0b-4b46-86bd-db1d5af53071').
(#iconCode -> 'nil').
(#id -> #'22d7a896-a0a2-af4d-863e-f70f5ed40ff9').
(#isProperty -> false).
(#isReference -> true).
(#label -> nil).
(#next -> #'2b3d7c04-cf7f-9243-b02d-95fc7b500018').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:11.754834 pm')}))})