steps
stepc4ee7c1cd764114889bec82a7c91889c
	<step>

	^ ((Dictionary new) add: (#definition->#'0d9c1713-c12c-064e-b583-ff4df2c3f4de'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'15 June 2015 10:01:59 am'); yourself)); add: (#isProperty->false); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'c4ee7c1c-d764-1148-89be-c82a7c91889c'); add: (#isReference->true); yourself)