steps
step4a7a5822905db043b36956f156129b87
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'c37e89e8-8db6-4d44-85d0-ccaefc64a618').
(#iconCode -> 'nil').
(#id -> #'4a7a5822-905d-b043-b369-56f156129b87').
(#isProperty -> false).
(#label -> nil).
(#next -> #'78cd1987-8352-584e-9b6b-7582a5be6451').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '9 December 2015 11:02:31 am').
(#inputKind -> MethodReference).
(#priority -> 300).
(#view -> ViMethodEditorView)}))})