steps
stepca50309f543bc84583d0749a6f7cbb2e
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'c7130d64-9f4e-7247-bd60-9214f1d0f522').
(#iconCode -> 'nil').
(#id -> #'ca50309f-543b-c845-83d0-749a6f7cbb2e').
(#label -> nil).
(#next -> #'fdb69e0a-57ea-394a-a74a-b986817dca93').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#labelColor -> '#AAAAAA').
(#priority -> 3180)}))})