steps
stepd681c3f184e3ea45b9b7505c4216ddc5
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'51e565d5-fc7c-b94e-b558-b7c0bb51532a').
(#iconCode -> 'nil').
(#id -> #'d681c3f1-84e3-ea45-b9b7-505c4216ddc5').
(#isProperty -> false).
(#isReference -> true).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '29 March 2019 4:02:48.696009 pm').
(#view -> ViTreeViewExtended)}))})