steps
stepa7590d1be0ee6340a3d476e67ae30cfa
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'720a8d90-f7c1-334e-a4ea-5094ba285a8d').
(#iconCode -> 'nil').
(#id -> #'a7590d1b-e0ee-6340-a3d4-76e67ae30cfa').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 February 2014 4:58:32 pm').
(#priority -> 5690)}))})