steps
stepb1a70f2be9ad3c4aa7e8a582e829cc3a
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'f2f9dad4-8d50-4c45-b267-83c97a117df9').
(#iconCode -> 'nil').
(#id -> #'b1a70f2b-e9ad-3c4a-a7e8-a582e829cc3a').
(#label -> nil).
(#next -> #'a8d8130a-271c-954e-aca4-bad9c8477a24').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '8 November 2013 4:14:01 pm').
(#hAlignment -> #right).
(#priority -> 4240)}))})