steps
stepd0704ef90a640d4496817487f8ee4e7b
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #histogram).
(#iconCode -> 'nil').
(#id -> #'d0704ef9-0a64-0d44-9681-7487f8ee4e7b').
(#label -> nil).
(#next -> #'29a5b770-b982-f548-b9d2-9842b501cff9').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '3 January 2014 11:53:42 am').
(#priority -> 4590)}))})