steps
step34d74f0397696140afa3e3b7a3f2cd59
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'714534c0-32b8-8444-af6f-b7e2f4be6913').
(#iconCode -> 'UiFugueIcons uiTextFieldIcon').
(#id -> #'34d74f03-9769-6140-afa3-e3b7a3f2cd59').
(#isProperty -> false).
(#label -> 'Input field').
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '9 December 2015 10:56:04 am').
(#help -> 'Type something...').
(#priority -> 5000).
(#view -> ViLineEdit)
}))
})