steps
step2a5bc3f7fc5f4d42bc5d1a7c79ebf632
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryReferenceStep).
(#definition -> nil).
(#iconCode -> 'nil').
(#id -> #'2a5bc3f7-fc5f-4d42-bc5d-1a7c79ebf632').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '29 March 2019 5:00:11.33635 pm').
(#view -> ViTreeViewExtended)})).
(#reference -> #'580b86a1-54c0-3a4f-a37c-d12c765b21d4')})