steps
stepae6288a6a692bf4284df1174cbab45a4
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'9d4a27b4-8a76-bc4d-9738-0a575bc69f07').
(#iconCode -> 'nil').
(#id -> #'ae6288a6-a692-bf42-84df-1174cbab45a4').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '21 May 2014 6:12:20 pm').
(#priority -> 6350)}))})