steps
step08a45a5f4130084dbc955cbe8033b730
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'6b3d9fbe-3f81-8048-ab4b-2b31f970a06d').
(#iconCode -> 'nil').
(#id -> #'08a45a5f-4130-084d-bc95-5cbe8033b730').
(#label -> 'Message tally').
(#next -> #'b44723c5-0063-0f4d-a4b7-1bd13591ae84').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 380).
(#view -> ViTreeViewExtended)}))})