steps
steped98259d40bab843bb324e77d29904ec
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQuerySortStep).
(#definition -> #'a340d182-121d-a841-9378-c6dd65102090').
(#iconCode -> 'nil').
(#id -> #'ed98259d-40ba-b843-bb32-4e77d29904ec').
(#label -> nil).
(#next -> #'fd62bf2f-377c-e64a-b62a-4f2399a054e1').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1200)}))})