steps
step3d6e30b29587c542a2192c6dcc16e5f1
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'a7aba676-f57f-2448-b69e-3283d44ce403').
(#iconCode -> 'nil').
(#id -> #'3d6e30b2-9587-c542-a219-2c6dcc16e5f1').
(#isProperty -> false).
(#label -> nil).
(#next -> #'3722f203-3108-8f42-b6c8-174b0b028329').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '29 May 2018 9:18:47 am').
(#inputKind -> #(nil nil nil))}))})