steps
stepc70e68dd9e93cc44a8c35fe0395e21ac
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'471e5b7e-f93e-5445-a146-c2d6fa8de2fc').
(#iconCode -> 'nil').
(#id -> #'c70e68dd-9e93-cc44-a8c3-5fe0395e21ac').
(#label -> nil).
(#next -> #'ed57b1e0-4b74-094a-926b-2776acef9b31').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '14 February 2014 10:53:24 am').
(#headerText -> #scU).
(#priority -> 5360)}))})