steps
stepd346ff340c694d46ac758aa766aef148
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'f5ed8b90-0396-e14a-b7c7-a384000dcbea').
(#iconCode -> 'nil').
(#id -> #'d346ff34-0c69-4d46-ac75-8aa766aef148').
(#label -> 'Chase pointers').
(#next -> #'8173a10a-ef99-b643-819d-530c4a9f806f').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #defaultProperties).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#labelColor -> '#999999').
(#priority -> 2000)}))})