steps
step6cd4db5cd2de844892b74f3c52589cf8
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'64a657ed-d4df-e146-955a-7dfe7e5570db').
(#iconCode -> 'nil').
(#id -> #'6cd4db5c-d2de-8448-92b7-4f3c52589cf8').
(#label -> 'Count Instance Variables').
(#next -> #'61afd65e-d943-5642-bd31-15492112b6ad').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'728402d7-f870-e743-8d2a-abf2353efba1').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 4670)}))})