steps
step003ae1fe6781f9439e4dc1fa5bab39b0
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupSortStep).
(#definition -> #compareObjectsAsStrings).
(#iconCode -> 'nil').
(#id -> #'003ae1fe-6781-f943-9e4d-c1fa5bab39b0').
(#label -> nil).
(#next -> #'67636419-4db6-8c43-aa22-b3948e02e796').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 2770)}))})