steps
step0de86151e883cf4c9668960b4466822e
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'9c76ab37-6e8d-7746-a7c3-5b4f72b5552c').
(#iconCode -> 'nil').
(#id -> #'0de86151-e883-cf4c-9668-960b4466822e').
(#label -> nil).
(#next -> #'d30b0a27-e492-ab4c-807d-23bd5f7ccf4b').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Version').
(#labelColor -> '#AAAAAA').
(#priority -> 1110).
(#resizeMode -> #rigid)}))})