steps
step432a6001f00e514ea68e4605686f7755
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'9a983afb-1665-9c4f-b0c2-568c430c054c').
(#iconCode -> 'nil').
(#id -> #'432a6001-f00e-514e-a68e-4605686f7755').
(#isProperty -> true).
(#label -> nil).
(#next -> #'17c595bf-6cf3-1143-a13a-a297052fd4cc').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Object').
(#priority -> 2670)}))})