steps
step96d77081b7de93458536a0d326322f6e
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryReferenceStep).
(#definition -> nil).
(#iconCode -> 'UiFugueIcons arrowStepIcon').
(#id -> #'96d77081-b7de-9345-8536-a0d326322f6e').
(#label -> 'References (recursive)').
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '15 September 2013 5:49:24 pm').
(#priority -> 540)})).
(#reference -> #'b510b1f4-2f4c-514a-bd82-a354adbf042f')})