steps
steped778e6a6acee54084c3af7329c1f656
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'ef17b0c3-3ef9-274e-86d1-cf657d2f721b').
(#iconCode -> 'nil').
(#id -> #'ed778e6a-6ace-e540-84c3-af7329c1f656').
(#label -> 'Update Definitions').
(#next -> #'f4803742-eb44-0846-9085-92c09d525159').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '6 September 2013 8:27:31 pm').
(#priority -> 1000)}))})