steps
stepbe086e52473b3d4ba8336d796588f9e6
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'2f31c995-3a2b-9a41-8c9a-281f6d2a3ffa').
(#iconCode -> 'nil').
(#id -> #'be086e52-473b-3d4b-a833-6d796588f9e6').
(#label -> nil).
(#next -> #'e61b1b9c-dca8-0246-aff4-93c3b091547a').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Class').
(#labelColor -> '#AAAAAA').
(#priority -> 1550)}))})