steps
stepb44723c500630f4da4b71bd13591ae84
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupStep).
(#definition -> #'1d92a8e5-d139-ef4b-8c89-e9b7f36c881a').
(#iconCode -> 'nil').
(#id -> #'b44723c5-0063-0f4d-a4b7-1bd13591ae84').
(#label -> nil).
(#next -> #'89c40fb8-551c-9e46-9651-f11978e9ff30').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 2330)}))})