steps
step587641c1faabd84da0021c90308297e1
	<step>

	^ (Dictionary newFrom: {
(#'_def' -> (Dictionary newFrom: {
(#block -> [:in :out | out addAll: in]).
(#className -> #ViScriptDefinition).
(#id -> #'75c00022-426b-f341-b69f-a760df0ca037').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:12.206834 pm')
})).
(#sourceCode -> '[:in :out | out addAll: in]')
})).
(#className -> #ViScriptStep).
(#definition -> #'75c00022-426b-f341-b69f-a760df0ca037').
(#iconCode -> 'nil').
(#id -> #'587641c1-faab-d84d-a002-1c90308297e1').
(#isProperty -> false).
(#label -> nil).
(#next -> #'0022b353-daa6-014c-a245-38faec14e32e').
(#properties -> (Dictionary newFrom: {
(#after -> #(#groupsMinimal)).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:12.206834 pm')
}))
})