steps
stepa8f95d967f396744aca595cde8b9e75e
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #origin).
(#iconCode -> 'nil').
(#id -> #'a8f95d96-7f39-6744-aca5-95cde8b9e75e').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'d9634b11-bde6-1a40-a0b4-7be880afc37a').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 4800)}))})