steps
stepe614ad198010a4449759aaa2423cb69e
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'e122c028-6e2c-2348-8918-5640418abb8e').
(#iconCode -> 'nil').
(#id -> #'e614ad19-8010-a444-9759-aaa2423cb69e').
(#isProperty -> false).
(#isReference -> true).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '29 March 2019 5:00:11.34035 pm')}))})