steps
stepc7876b21782a494488e1399e5e82d6b5
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'8b1b3117-02c1-e140-a210-b0fc8a71e54a').
(#iconCode -> 'nil').
(#id -> #'c7876b21-782a-4944-88e1-399e5e82d6b5').
(#isProperty -> true).
(#label -> nil).
(#next -> #'20b77a9d-a691-b74e-950a-df46a318513c').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '29 May 2018 9:28:47 am').
(#inputKind -> #(nil nil))}))})