steps
stepb080bd39a8a31744b982fb270b04627f
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'ac1120b1-74b6-da40-ab65-2f200a111348').
(#iconCode -> 'nil').
(#id -> #'b080bd39-a8a3-1744-b982-fb270b04627f').
(#label -> nil).
(#next -> #'9a8f7fe5-e3fe-5e4e-8f65-c463b0cac3e9').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '14 February 2014 10:07:34 am').
(#headerText -> #DPi).
(#priority -> 5310)}))})