steps
stepb3b8787175165049b09272ad966f3216
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'29ef7ed7-ae7b-734e-983d-8f574ee9c654').
(#iconCode -> 'nil').
(#id -> #'b3b87871-7516-5049-b092-72ad966f3216').
(#label -> 'Special Queries').
(#next -> #'757cd24a-516e-bf45-ad50-d29635e9bbee').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #identity).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 1:01:49 pm').
(#priority -> 6670).
(#view -> ViTreeViewExtended)}))})