steps
stepcb92050bf3868b49bf36aacf195d2c3c
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'761d9487-66d3-fa41-91bb-711f3ec2e3da').
(#iconCode -> 'nil').
(#id -> #'cb92050b-f386-8b49-bf36-aacf195d2c3c').
(#isProperty -> false).
(#isReference -> true).
(#label -> nil).
(#next -> #'24a9922a-802c-1543-acf7-ff6d8dc30bbf').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:11.666834 pm')}))})