steps
step3f4d3ab2a67d054b9bf8eec6d9a0bfe2
	<step>

	^ ((Dictionary new) add: (#definition->#'5dae62e9-1976-c94d-bf24-d48085622337'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'14 December 2015 11:52:58 am'); yourself)); add: (#isProperty->false); add: (#next->#'9b96cd37-e54b-5649-b04d-d585c24b8303'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'3f4d3ab2-a67d-054b-9bf8-eec6d9a0bfe2'); add: (#isReference->false); yourself)