steps
stepfb5f9d4849cf774c921fe9598b74d2c7
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'9242cbac-4797-8d4c-9f3f-8d8dc15a9b9e').
(#iconCode -> 'nil').
(#id -> #'fb5f9d48-49cf-774c-921f-e9598b74d2c7').
(#label -> nil).
(#next -> #'33a2c2ee-bac8-3b4a-842d-faf5586d7042').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '12 November 2013 4:58:54 pm').
(#priority -> 4330)}))})