steps
step94eb9234d52f0e4a81c1de2c4191893e
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'a307fbaf-5ccd-d446-b2d2-73437708520f').
(#iconCode -> 'nil').
(#id -> #'94eb9234-d52f-0e4a-81c1-de2c4191893e').
(#label -> nil).
(#next -> #'427e325e-4f83-274f-aa3d-b1b3a19ef7e6').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'d9634b11-bde6-1a40-a0b4-7be880afc37a').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 4050)}))})