steps
stepaf7030042f554940abd6c3b1a717db27
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'be0082fe-f238-c54a-9220-32909fda1e3d').
(#iconCode -> 'nil').
(#id -> #'af703004-2f55-4940-abd6-c3b1a717db27').
(#isProperty -> false).
(#isReference -> false).
(#label -> 'Methods w/ Longest History').
(#next -> #'59e1a354-ea9e-3d4d-b4c6-70d3a9eb6d48').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#inputKind -> ProtoObject).
(#isGlobal -> true).
(#priority -> 930).
(#view -> ViTreeViewExtended)}))})