steps
stepe68d82d70f825e4f990d0b292c42da7f
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'afe544dd-ac95-9747-aa66-a354d9e820a0').
(#iconCode -> 'nil').
(#id -> #'e68d82d7-0f82-5e4f-990d-0b292c42da7f').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 November 2013 4:20:43 pm').
(#priority -> 4420)}))})