steps
stepfcae92ef09ebff47be9e9e35c33c4784
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'ac61d54e-889d-0840-9451-e8c31df3dc34').
(#iconCode -> 'nil').
(#id -> #'fcae92ef-09eb-ff47-be9e-9e35c33c4784').
(#label -> nil).
(#next -> #'bc34ef97-52af-6c49-b344-cdb766681c0c').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'f50a996d-d0c8-3e46-bfc9-b54c71e930d2').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 September 2013 6:31:32 pm').
(#priority -> 3830)}))})