steps
stepe62241f332bff545a0b1a632d1e53911
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'6a9cd53f-7fbb-d140-8d4d-d28b243e5465').
(#iconCode -> 'nil').
(#id -> #'e62241f3-32bf-f545-a0b1-a632d1e53911').
(#isProperty -> false).
(#isReference -> false).
(#label -> 'Pretty print class comments').
(#next -> #'da240e4d-2791-be42-a47a-879ff7f15f76').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 370).
(#view -> ViTreeViewExtended)}))})