steps
step5db2822b273db541b1f65ec634e49efa
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupSortStep).
(#definition -> #'85bc20f1-4a8e-5440-8c06-9b7261827cb1').
(#iconCode -> 'nil').
(#id -> #'5db2822b-273d-b541-b1f6-5ec634e49efa').
(#label -> nil).
(#next -> #'afd7936f-3466-6b44-84a7-2d8fc3dc21a4').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1950)}))})