steps
stepc47ab7eb21ab2048a04492202f71989f
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'bfa04c1c-116e-a34f-bda4-f81147cb89d9').
(#iconCode -> 'nil').
(#id -> #'c47ab7eb-21ab-2048-a044-92202f71989f').
(#isProperty -> false).
(#label -> nil).
(#next -> #'a4597f82-83f5-f145-8733-996443dff441').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '9 December 2015 11:26:37 am').
(#inputKind -> MethodReference).
(#priority -> 300).
(#view -> ViTreeViewExtended)}))})