steps
stepaba8446dad234a448fc1448e43f60d5d
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'4a0dff95-e55d-c442-b258-e5fd54236a7b').
(#iconCode -> 'nil').
(#id -> #'aba8446d-ad23-4a44-8fc1-448e43f60d5d').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'d9634b11-bde6-1a40-a0b4-7be880afc37a').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 4860)}))})