steps
step0022b353daa6014ca24538faec14e32e
	<step>

	^ (Dictionary newFrom: {
(#'_def' -> (Dictionary newFrom: {
(#block -> [:in :out | out addAll: ([:objects | objects] value: in)]).
(#className -> #ViScriptDefinition).
(#id -> #'49bc89f4-2040-6846-9c08-4b80785c6642').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')
})).
(#sourceCode -> '[:in :out | out addAll: ([:objects | objects] value: in)]')
})).
(#className -> #ViScriptStep).
(#definition -> #'49bc89f4-2040-6846-9c08-4b80785c6642').
(#iconCode -> 'nil').
(#id -> #'0022b353-daa6-014c-a245-38faec14e32e').
(#isProperty -> false).
(#label -> nil).
(#next -> #'d9976b61-dc4e-bf4a-a4a6-a44c2728904d').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 September 2013 3:08:26 pm').
(#priority -> 3960)
}))
})