steps
step5636df933a8fea449406e602b99e3101
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'9a7df9d0-e5c8-3b4a-bafc-5070caed44c3').
(#iconCode -> 'nil').
(#id -> #'5636df93-3a8f-ea44-9406-e602b99e3101').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '12 November 2013 4:58:54 pm').
(#priority -> 6390)}))})