steps
stepa3b79801e8b51848820eb0abaa56e111
	<step>

	^ ((Dictionary new) add: (#definition->#'358a8cd7-384c-fd42-9666-5553c6b4170b'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->CompiledMethod); add: (#priority->1000); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'9 December 2015 10:48:47 am'); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->#'0a45fa5f-6f7b-a74b-b15f-868dcf6a9799'); add: (#label->'Browse method''s class'); add: (#iconCode->'nil'); add: (#id->#'a3b79801-e8b5-1848-820e-b0abaa56e111'); add: (#isReference->false); yourself)