steps
stepe505710cf722e34ea85ef914106ea5cb
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQuerySortStep).
(#definition -> #'f5fcb65a-ce61-9f41-be89-945ee8be0d1b').
(#iconCode -> 'nil').
(#id -> #'e505710c-f722-e34e-a85e-f914106ea5cb').
(#label -> nil).
(#next -> #'b7982ee7-7baa-6b48-8f2a-1bbbf9c96888').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1930)}))})