steps
stepd2ab7b327b9eba48808cab0e89480da4
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'ec6def74-d020-7d49-81bb-9e355711a941').
(#iconCode -> 'nil').
(#id -> #'d2ab7b32-7b9e-ba48-808c-ab0e89480da4').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'ef81aed0-ae2d-6548-904f-030b28e12e97').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 September 2013 6:59:44 pm').
(#priority -> 3780)}))})