steps
stepa67a43efd74abf46b160bf00ef047753
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupSortStep).
(#definition -> #compareObjectsAsStrings).
(#iconCode -> 'nil').
(#id -> #'a67a43ef-d74a-bf46-b160-bf00ef047753').
(#label -> nil).
(#next -> #'6eab0da0-5a97-d94d-84a6-5f930edbbd06').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '21 May 2014 6:11:40 pm').
(#priority -> 6310)}))})