steps
step37aa1dbdbbd2b2429c7d2efb85ce5e27
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'e34d1bb9-2423-d34e-a16b-f84b0ab7ae75').
(#iconCode -> 'nil').
(#id -> #'37aa1dbd-bbd2-b242-9c7d-2efb85ce5e27').
(#label -> nil).
(#next -> #'9d1f7dc5-d93e-274b-b732-b08a5181ea6f').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '3 September 2013 3:27:42 pm').
(#priority -> 2400)}))})