steps
step399ab6754b80fd47b25972a0a44e0766
	<step>

	^ ((Dictionary new) add: (#definition->#'7ce23c08-31f0-c940-bd2d-0a209eb5f472'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->String); add: (#priority->230); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'14 December 2015 11:52:58 am'); yourself)); add: (#isProperty->false); add: (#next->#'ab5e2d3f-7d8b-c347-a60e-f14d4961675d'); add: (#label->'Classes in category (hierarchy)'); add: (#iconCode->'UiSilkIcons carIcon'); add: (#id->#'399ab675-4b80-fd47-b259-72a0a44e0766'); add: (#isReference->false); yourself)