steps
step3d61a6d34a433e41bba9ed11c74649e3
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'a4426d27-5a0b-2442-97d0-1a272d0f6e58').
(#iconCode -> 'nil').
(#id -> #'3d61a6d3-4a43-3e41-bba9-ed11c74649e3').
(#label -> 'Change Set Preamble').
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #identity).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 1:01:49 pm').
(#priority -> 6220).
(#view -> ViTreeViewExtended)}))})