steps
step08b44027bc56f8449826f94859a5b557
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'74d42c6d-fa57-e44c-958d-da199a3de398').
(#iconCode -> 'nil').
(#id -> #'08b44027-bc56-f844-9826-f94859a5b557').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '5 June 2014 5:03:50 pm').
(#priority -> 6430)}))})