steps
stepcafd96b46e9f904cbb728015ce0d112f
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #removeDuplicates).
(#iconCode -> 'nil').
(#id -> #'cafd96b4-6e9f-904c-bb72-8015ce0d112f').
(#label -> nil).
(#next -> #'efe97b23-18f7-b847-90a1-a8315d4344a7').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '17 January 2014 2:57:35 pm').
(#priority -> 4710)}))})