steps
step0d821eecf78fd44e80df96d6b534a947
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'d0608999-e6c6-b648-b748-5cdb7b3c81b3').
(#iconCode -> 'nil').
(#id -> #'0d821eec-f78f-d44e-80df-96d6b534a947').
(#label -> nil).
(#next -> #'f99cba1c-d720-4545-ac10-5a57f620226d').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 2460)}))})