steps
step3cce12f6e3d55b4082faff0f97f9844c
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupStep).
(#definition -> #'e0ddacbc-8104-ef48-a6ce-6ea24c435edc').
(#iconCode -> 'nil').
(#id -> #'3cce12f6-e3d5-5b40-82fa-ff0f97f9844c').
(#label -> nil).
(#next -> #'d45b0a75-2488-2c43-939b-ec29c77353af').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1080)}))})