steps
step8c98b390c0ff494e94e4be9cfaeea24c
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'c199aae4-73d9-5746-9016-4e66df9f6434').
(#iconCode -> 'nil').
(#id -> #'8c98b390-c0ff-494e-94e4-be9cfaeea24c').
(#isProperty -> false).
(#label -> nil).
(#next -> #'35047111-f49d-8b4e-bfe1-21c59e369af2').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '9 December 2015 11:55:27 am')}))})