steps
step0502fbc66bc851459f5d4b683a4318ed
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'5c5b7c8a-0ded-c846-ab7d-2177523597db').
(#iconCode -> 'nil').
(#id -> #'0502fbc6-6bc8-5145-9f5d-4b683a4318ed').
(#isProperty -> true).
(#label -> nil).
(#next -> #'c399546c-fcff-9046-bd66-0f7b1f946123').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '15 December 2015 10:39:29 am')
}))
})