steps
step14bc7fefbe90a94991f7a0b9c1d7f2ff
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'06656814-9c2f-5546-9f02-960250a4ed02').
(#iconCode -> 'nil').
(#id -> #'14bc7fef-be90-a949-91f7-a0b9c1d7f2ff').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#copyOf -> #'43bba950-dc26-5440-a6f8-7c8f5fb4648f').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '12 May 2015 4:36:46 pm')}))})