steps
stepdc8af77bcb54d74da9c2fbd92c4b2a44
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'d579b1f6-4466-8842-b908-ef4dcc51f0ad').
(#iconCode -> 'nil').
(#id -> #'dc8af77b-cb54-d74d-a9c2-fbd92c4b2a44').
(#label -> nil).
(#next -> #'2ebbfcc8-18ea-9643-96ea-4d38fe7cf10a').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '23 July 2014 2:44:48 pm').
(#priority -> 6690)}))})