steps
step9f787b5567835a4c97b93a19519d50db
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'55a165bf-5887-e44f-9658-d55ea8697ca7').
(#iconCode -> 'nil').
(#id -> #'9f787b55-6783-5a4c-97b9-3a19519d50db').
(#isProperty -> false).
(#label -> nil).
(#next -> #'9e7e3607-1a59-fe4a-a65e-f1f49efaba06').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '3 May 2019 10:51:34.248161 am')}))})