steps
step19aa31e9da2d0646bcb5c43217a64c10
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'c4058b30-3d6e-7348-a6e6-b421ac935378').
(#iconCode -> 'nil').
(#id -> #'19aa31e9-da2d-0646-bcb5-c43217a64c10').
(#label -> 'Classes by Author').
(#next -> #'7f7cb928-c2c5-c840-8c91-995fa40b1fd5').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 November 2013 4:16:23 pm').
(#priority -> 4380).
(#view -> ViTreeViewExtended)}))})