steps
step89162c9a88474744abdb1031a61c2898
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupStep).
(#definition -> #'db2f8193-a594-2c44-9742-393eda0eb826').
(#iconCode -> 'nil').
(#id -> #'89162c9a-8847-4744-abdb-1031a61c2898').
(#label -> nil).
(#next -> #'1816b6d5-ac08-7543-9b14-edd58be27deb').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 2420)}))})