steps
step53385c7bcff8c8428efde43b039db34b
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'7c3c31a6-c625-d741-9241-e745aec8f9e9').
(#iconCode -> 'nil').
(#id -> #'53385c7b-cff8-c842-8efd-e43b039db34b').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 November 2013 5:07:13 pm').
(#priority -> 4490)}))})