steps
step6900ffdc84145f4abab99602bbf21fae
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'29f516c5-189c-2544-bd3f-1417d9eea5fe').
(#iconCode -> 'nil').
(#id -> #'6900ffdc-8414-5f4a-bab9-9602bbf21fae').
(#label -> nil).
(#next -> #'a7590d1b-e0ee-6340-a3d4-76e67ae30cfa').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 February 2014 4:31:24 pm').
(#priority -> 5680)}))})