steps
stepafe34ca0aa48bd438eeb7d8059eae2d1
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'98f794ef-0196-6a4c-ac47-4064b701a2cd').
(#iconCode -> 'nil').
(#id -> #'afe34ca0-aa48-bd43-8eeb-7d8059eae2d1').
(#isProperty -> false).
(#label -> nil).
(#next -> #'809203fe-0963-ad41-98c8-acf61fac83bd').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '29 April 2016 5:54:15 pm')
}))
})