steps
step83cf71976cf5554eb5352b2ebf2fb60e
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'0e8d96d2-e161-4642-8ab8-9c4f1e307194').
(#iconCode -> 'nil').
(#id -> #'83cf7197-6cf5-554e-b535-2b2ebf2fb60e').
(#label -> 'Byte codes').
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '24 February 2014 10:42:49 am').
(#priority -> 5820).
(#view -> ViTreeViewExtended)}))})