steps
step322c353db95327439b11f8c0ae4041b1
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'a12460e4-9ff1-9340-a15f-254b7606678a').
(#iconCode -> 'nil').
(#id -> #'322c353d-b953-2743-9b11-f8c0ae4041b1').
(#label -> nil).
(#next -> #'7d7f7d20-939a-7c4e-9a80-1915e705d82e').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Origin').
(#labelColor -> '#AAAAAA').
(#priority -> 3080)}))})