steps
step11f0e87814f5b147a1c6e95064e1a62a
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupSortStep).
(#definition -> #compareObjectsAsStrings).
(#iconCode -> 'nil').
(#id -> #'11f0e878-14f5-b147-a1c6-e95064e1a62a').
(#label -> nil).
(#next -> #'ded083c3-3dd2-f04a-96cf-46c7dfe608dc').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '20 February 2014 6:30:20 pm').
(#priority -> 5780)}))})