steps
stepd977be3c9e8a6740bff763c0bd8811c0
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'58ea7896-8763-644c-a23f-47ea23baadcd').
(#iconCode -> 'nil').
(#id -> #'d977be3c-9e8a-6740-bff7-63c0bd8811c0').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Comment').
(#labelColor -> '#AAAAAA').
(#priority -> 2030)}))})