steps
steped4cdeb4e8e8f64a9016e09729155d02
	<step>

	^ (Dictionary newFrom: {
(#'_def' -> (Dictionary newFrom: {
(#block -> [:in :out | out addAll: in]).
(#className -> #ViScriptDefinition).
(#id -> #'6034a8ad-a5b2-e14b-9a6a-6ad8fcd2565e').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '9 December 2015 1:13:34 pm')
})).
(#sourceCode -> '[:in :out | out addAll: in]')
})).
(#className -> #ViScriptStep).
(#definition -> #'6034a8ad-a5b2-e14b-9a6a-6ad8fcd2565e').
(#iconCode -> 'nil').
(#id -> #'ed4cdeb4-e8e8-f64a-9016-e09729155d02').
(#isProperty -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#after -> #(#'4f14fbe5-65d1-c74f-ab1f-7751495fcf7c')).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '9 December 2015 1:13:34 pm')
}))
})