steps
step1bb9843febf1384882dc01ee3ed5468d
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'e4f148b7-a110-f34d-a934-f46bec7ee57e').
(#iconCode -> 'nil').
(#id -> #'1bb9843f-ebf1-3848-82dc-01ee3ed5468d').
(#label -> nil).
(#next -> #'78e13ff4-d093-1140-b575-be2225a6eaf7').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 February 2014 1:57:43 pm').
(#headerText -> 'cS').
(#priority -> 5390)}))})