steps
stepd681c3f184e3ea45b9b7505c4216ddc5
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryReferenceStep).
(#definition -> nil).
(#iconCode -> 'nil').
(#id -> #'d681c3f1-84e3-ea45-b9b7-505c4216ddc5').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '29 March 2019 4:02:48.696009 pm').
(#view -> ViTreeViewExtended)})).
(#reference -> #'d70d563f-bdd7-1842-9175-cf758450e227')})