steps
stepcffbfe830584d2418e7b068442bd8619
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'8d718606-a86d-3040-8705-106076cda276').
(#iconCode -> 'nil').
(#id -> #'cffbfe83-0584-d241-8e7b-068442bd8619').
(#label -> nil).
(#next -> #'a877e0b4-377f-244b-96e5-e6616c9f8247').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 February 2014 1:34:36 pm').
(#priority -> 5600)}))})