steps
step51682d2b50c72d4ebbad94af2dd69be7
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'b58ace2e-bc48-a344-94f4-5ce4bffd205d').
(#iconCode -> 'nil').
(#id -> #'51682d2b-50c7-2d4e-bbad-94af2dd69be7').
(#isProperty -> false).
(#isReference -> true).
(#label -> nil).
(#next -> #'d96e910a-df73-5a4c-b760-8811fac45378').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:12.960834 pm')}))})