steps
step417f42f73ebf834ea6ec8cecfbb75b84
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'052a74fa-7606-c941-9a37-1dead31a8a3e').
(#iconCode -> 'UiSilkIcons packageIcon').
(#id -> #'417f42f7-3ebf-834e-a6ec-8cecfbb75b84').
(#label -> 'Packages and Categories').
(#next -> #'35a0fb8d-428f-1b4e-9c15-e5fe341d5e61').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 900).
(#view -> ViTreeViewExtended)}))})