steps
step069180ba532da840b13313495d451f74
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'12af691a-ac0b-cd49-88c7-73fcb3a92686').
(#iconCode -> 'nil').
(#id -> #'069180ba-532d-a840-b133-13495d451f74').
(#label -> nil).
(#next -> #'7d49f967-e5fd-2d45-a452-864c859fa223').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '5 June 2014 5:05:04 pm').
(#priority -> 6410)}))})