steps
step594a2a29f4d79447bc7d0f50be719127
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'dceac215-ec7a-aa48-a9d9-0c1e45043057').
(#iconCode -> 'nil').
(#id -> #'594a2a29-f4d7-9447-bc7d-0f50be719127').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'ccb87580-d74c-dc47-a558-206c68840342').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '14 December 2015 11:52:58 am')}))})