steps
stepc68e2eafff3feb4b9f5174527cb495ac
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'dade81d8-25ea-b745-9fab-eccaa538e7b0').
(#iconCode -> 'nil').
(#id -> #'c68e2eaf-ff3f-eb4b-9f51-74527cb495ac').
(#isProperty -> true).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '7 December 2015 2:00:40 pm')
}))
})