steps
step99cac90068fd1449966b015ed7762e86
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'0adbab9d-1596-f94b-a7f9-9d3429abda97').
(#iconCode -> 'nil').
(#id -> #'99cac900-68fd-1449-966b-015ed7762e86').
(#isProperty -> false).
(#isReference -> false).
(#label -> '[DEBUG] Categorize lines of code').
(#next -> #'56b2492f-f394-db42-ade3-e2d633f5230d').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 1:01:49 pm').
(#inputKind -> CompiledMethod).
(#priority -> 5130).
(#view -> ViTreeViewExtended)}))})