steps
stepee9363991409634c81ff0389658bb3ce
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'f7713f3d-1af3-de43-9510-b66470425a96').
(#iconCode -> 'nil').
(#id -> #'ee936399-1409-634c-81ff-0389658bb3ce').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '6 December 2013 5:17:12 pm').
(#priority -> 4560)}))})