steps
stepce6fede41334d84b81765e5a33fd162f
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'e32d19a7-1850-b948-98f9-ab78e9051b1d').
(#iconCode -> 'nil').
(#id -> #'ce6fede4-1334-d84b-8176-5e5a33fd162f').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'0547837e-8ef9-cd4b-827d-5574ea1e1c91').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#outputKind -> Boolean).
(#priority -> 2180).
(#view -> ViTreeViewExtended)}))})