steps
step77862f460851124eb1ff6cb2e962a0c8
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'8a8d6ac7-0a64-2e4d-942f-654924a02c68').
(#iconCode -> 'UiDiagonaIcons icon0223Normal').
(#id -> #'77862f46-0851-124e-b1ff-6cb2e962a0c8').
(#label -> 'Flags').
(#next -> #'fd3c0b79-142a-ee4e-9f27-4da12eba946f').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'77862f46-0851-124e-b1ff-6cb2e962a0c8').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 September 2013 6:34:06 pm').
(#priority -> 3300)}))})