steps
stepb29c84be71bfb84cad6881df0d7196e7
	<step>

	^ ((Dictionary new) add: (#definition->#'70283200-b2d3-d743-9d8a-392461112f21'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->MethodReference); add: (#priority->200); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'9 December 2015 10:25:03 am'); yourself)); add: (#isProperty->false); add: (#next->#'b81e14ce-2c55-114e-a729-a2cb482e4b71'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'b29c84be-71bf-b84c-ad68-81df0d7196e7'); add: (#isReference->false); yourself)