steps
stepae6288a6a692bf4284df1174cbab45a4
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'d78e317f-b0d4-434c-898c-8619449b56c2').
(#iconCode -> 'nil').
(#id -> #'ae6288a6-a692-bf42-84df-1174cbab45a4').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '21 May 2014 6:12:20 pm').
(#priority -> 6350)}))})