steps
step754c7a1e5b33a8428a8ac5f6eef88890
	<step>

	^ (Dictionary newFrom: {
(#'_def' -> (Dictionary newFrom: {
(#block -> [:in :out | out addAll: in]).
(#className -> #ViScriptDefinition).
(#id -> #'cb0697a0-955c-f84e-821f-1a0301557b51').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:12.931834 pm')
})).
(#sourceCode -> '[:in :out | out addAll: in]')
})).
(#className -> #ViScriptStep).
(#definition -> #'cb0697a0-955c-f84e-821f-1a0301557b51').
(#iconCode -> 'nil').
(#id -> #'754c7a1e-5b33-a842-8a8a-c5f6eef88890').
(#isProperty -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#after -> #(#'8ed52473-9493-2142-94be-054478bc571b')).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '4 September 2013 12:59:17 pm').
(#priority -> 2580).
(#view -> ViTreeViewExtended)
}))
})