steps
step8c05883334df6a4ca7175b1be5ea7200
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'ecc7884c-a7d8-df46-85ee-57b6050211bc').
(#iconCode -> 'nil').
(#id -> #'8c058833-34df-6a4c-a717-5b1be5ea7200').
(#isProperty -> false).
(#label -> nil).
(#next -> #'bfc2203c-a7db-c84f-9574-1514d216b6e2').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '20 May 2015 2:36:10 pm')}))})