steps
step00ab51d869ddfb4a90da3e9a2f70ef75
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'0dbe7b5b-75fe-0548-89a6-fa450ff8259e').
(#iconCode -> 'nil').
(#id -> #'00ab51d8-69dd-fb4a-90da-3e9a2f70ef75').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '14 February 2014 2:48:40 pm').
(#headerText -> #o).
(#priority -> 5450)}))})