steps
step7badd43290e1ec4296d76085b40a0871
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'007df436-f9d4-7e4e-9bed-200cbef6b4d0').
(#iconCode -> 'nil').
(#id -> #'7badd432-90e1-ec42-96d7-6085b40a0871').
(#label -> nil).
(#next -> #'254519a4-d387-e145-98c4-9d0959d54bb0').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'7badd432-90e1-ec42-96d7-6085b40a0871').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '3 September 2013 1:58:21 pm').
(#priority -> 970)}))})