steps
step3949844d11c6dd41b185b338c3ca4dac
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'08d80dec-a983-554b-a810-d3f35644ff3e').
(#iconCode -> 'nil').
(#id -> #'3949844d-11c6-dd41-b185-b338c3ca4dac').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 September 2013 5:29:39 pm').
(#priority -> 3740)}))})