steps
stepb72e75d103bb7541a46e39fd55b28333
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'22391fed-589b-6449-8200-875e0c108886').
(#iconCode -> 'nil').
(#id -> #'b72e75d1-03bb-7541-a46e-39fd55b28333').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 September 2013 6:09:21 pm').
(#labelColor -> '000000').
(#priority -> 3290)}))})