steps
step391b43fb2481a944a2ffb8be04f07191
	<step>

	^ (Dictionary newFrom: {
(#'_def' -> (Dictionary newFrom: {
(#block -> [:in :out | [ExNote nonEmptyNotes] value in: [:result |
	out addAll: result asList]]).
(#className -> #ViScriptDefinition).
(#id -> #'0c4e7ddc-ae78-0c49-b7db-56b6426abca7').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '6 March 2020 1:27:41.520371 pm')
})).
(#sourceCode -> '[:in :out | [ExNote nonEmptyNotes] value in: [:result |
	out addAll: result asList]]')
})).
(#className -> #ViScriptStep).
(#definition -> #'0c4e7ddc-ae78-0c49-b7db-56b6426abca7').
(#iconCode -> 'nil').
(#id -> #'391b43fb-2481-a944-a2ff-b8be04f07191').
(#isProperty -> false).
(#label -> 'Exploratory Patterns').
(#next -> #'4cfb184f-6e31-984f-b334-1c3d3b508312').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '6 March 2020 1:27:41.520371 pm').
(#isGlobal -> true).
(#view -> ViTreeViewExtended)
}))
})