steps
step476a828e2f7b4b4a9c8ab515f83ac457
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'6ffb5883-25e9-4643-a943-7dd170e4169a').
(#iconCode -> 'nil').
(#id -> #'476a828e-2f7b-4b4a-9c8a-b515f83ac457').
(#label -> nil).
(#next -> #'fcc66484-4caf-354f-8f24-d727784b3424').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 2550)}))})