steps
step5e2dceb99ba3484cb969cc38d82aeaf1
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'452e9359-82a2-3f43-94fe-c108dfa3fef0').
(#iconCode -> 'UiFugueIcons balloonExclamationIcon').
(#id -> #'5e2dceb9-9ba3-484c-b969-cc38d82aeaf1').
(#label -> 'Unsent Messages').
(#next -> #'233b181d-fccc-094d-8b70-ba191cfe05ba').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 September 2013 7:06:50 pm').
(#priority -> 750)}))})