steps
stepcf42cf45c23cc14981f21b262f58b7d3
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQuerySortStep).
(#definition -> #'716cce77-e262-584d-a8b0-c71abe88be2e').
(#iconCode -> 'nil').
(#id -> #'cf42cf45-c23c-c149-81f2-1b262f58b7d3').
(#label -> nil).
(#next -> #'3342a24e-e4ed-a64f-980a-bc8e7c4674e4').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '23 May 2014 11:01:22 am').
(#priority -> 6290)}))})