steps
stepc95c6c53431dd44d895e41f83dbc02c4
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'12e82498-d1a4-694c-80a6-8ad84486b76a').
(#iconCode -> 'nil').
(#id -> #'c95c6c53-431d-d44d-895e-41f83dbc02c4').
(#label -> nil).
(#next -> #'4f59f26e-7806-f847-a4a5-10f389535b0e').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'86247f76-5b43-d748-82a2-b2d9e56e443a').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 September 2013 7:01:48 pm').
(#headerText -> 'Resource').
(#priority -> 3880)}))})