steps
stepda240e4d2791be42a47a879ff7f15f76
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQuerySortStep).
(#definition -> #'27493088-8837-484d-ba34-55061b4f955d').
(#iconCode -> 'nil').
(#id -> #'da240e4d-2791-be42-a47a-879ff7f15f76').
(#label -> nil).
(#next -> #'641df55b-dc10-f744-86f3-2f5eb3f970ab').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 2300)}))})