steps
step26cb48ed78b26d43893bab8f69e4090f
	<step>

	^ ((Dictionary new) add: (#definition->#'afcc3456-1c10-5d4c-aa94-a1fd5b3f1d66'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'9 December 2015 10:25:03 am'); yourself)); add: (#isProperty->false); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'26cb48ed-78b2-6d43-893b-ab8f69e4090f'); add: (#isReference->true); yourself)