steps
step554c12a43ed5904d8adabb3d129a200a
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'50041bc7-921e-c24f-be8c-5cf9144c4040').
(#iconCode -> 'nil').
(#id -> #'554c12a4-3ed5-904d-8ada-bb3d129a200a').
(#label -> nil).
(#next -> #'afb03b2b-6810-684f-853c-74918c6c73e3').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '21 February 2014 9:39:56 am').
(#headerText -> 'Spawn').
(#priority -> 5980)}))})