steps
stepf4f3c4ff456b3a46a1ae22320975be38
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'a66f00c9-22cb-0a48-a223-d73699b16746').
(#iconCode -> 'nil').
(#id -> #'f4f3c4ff-456b-3a46-a1ae-22320975be38').
(#label -> nil).
(#next -> #'0d821eec-f78f-d44e-80df-96d6b534a947').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 September 2013 1:08:17 pm').
(#headerText -> 'Type').
(#priority -> 3930)}))})