steps
stepa36810b7a281b34d9d22e1f1a585db30
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'88d3018f-75a8-cb45-a268-932557f847c5').
(#iconCode -> 'nil').
(#id -> #'a36810b7-a281-b34d-9d22-e1f1a585db30').
(#isProperty -> true).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '23 September 2013 5:12:03 pm').
(#priority -> 4130)}))})