steps
stepdb94be9eb0285f46bfad28f781b0ae9e
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'e80f2ecd-de69-4d47-a05a-3c9164d1d0c1').
(#iconCode -> 'nil').
(#id -> #'db94be9e-b028-5f46-bfad-28f781b0ae9e').
(#label -> nil).
(#next -> #'5e1d1190-aaa3-2749-82c2-010ce8a97d2f').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1660)}))})