steps
step17c595bf6cf31143a13aa297052fd4cc
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #origin).
(#iconCode -> 'nil').
(#id -> #'17c595bf-6cf3-1143-a13a-a297052fd4cc').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Origin').
(#labelColor -> '#AAAAAA').
(#priority -> 2680)}))})