steps
stepe45648f84feff3438972cbb555789355
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'246002fe-2c9b-5441-b641-536057242d4d').
(#iconCode -> 'nil').
(#id -> #'e45648f8-4fef-f343-8972-cbb555789355').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'62d361c4-2c39-6e47-989e-42b4f10c257c').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '14 February 2014 1:06:18 pm').
(#headerText -> #R).
(#priority -> 5290)}))})