steps
stepe91a4f525c394c4cb5c51311bacd5025
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'ce43fc0e-5e43-8649-b12f-662c9ac7d2a7').
(#iconCode -> 'nil').
(#id -> #'e91a4f52-5c39-4c4c-b5c5-1311bacd5025').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'8ebc1c71-5396-204d-98e9-e545b22d0823').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '15 June 2015 10:20:57 am')}))})