steps
step1af15768bcf7b14b83c1b420955ce1e4
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'f5282b30-1fcd-3143-9cd3-547c55e05dfb').
(#iconCode -> 'nil').
(#id -> #'1af15768-bcf7-b14b-83c1-b420955ce1e4').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#copyOf -> #'e9577839-3b92-8e4f-a413-365561ade680').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 October 2015 2:07 pm').
(#view -> ViPluggableButtonBarMorph)}))})