steps
step5810152a258e104482c6a1d1c4ad946a
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'e9bef106-e5e8-514c-ac3a-8648bb731c05').
(#iconCode -> 'nil').
(#id -> #'5810152a-258e-1044-82c6-a1d1c4ad946a').
(#label -> nil).
(#next -> #'a64e11c5-6bfc-5a42-a738-d78d947d80da').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 September 2013 8:01:35 pm').
(#priority -> 3550)}))})