steps
stepc0319874c45b744185fef6fe2ba7e2a9
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'740c7d8f-097a-4043-b903-fe5818cbf7b7').
(#iconCode -> 'nil').
(#id -> #'c0319874-c45b-7441-85fe-f6fe2ba7e2a9').
(#label -> nil).
(#next -> #'ce6fede4-1334-d84b-8176-5e5a33fd162f').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 2170)}))})