steps
stepf99cba1cd7204545ac105a57f620226d
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryReferenceStep).
(#definition -> nil).
(#iconCode -> 'nil').
(#id -> #'f99cba1c-d720-4545-ac10-5a57f620226d').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '29 March 2019 5:00:11.33835 pm')})).
(#reference -> #'e0d4454d-0188-6242-916d-1c1f2b47e445')})