steps
step0502fbc66bc851459f5d4b683a4318ed
	<step>

	^ ((Dictionary new) add: (#definition->#'5c5b7c8a-0ded-c846-ab7d-2177523597db'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'15 December 2015 10:39:29 am'); yourself)); add: (#isProperty->true); add: (#next->#'c399546c-fcff-9046-bd66-0f7b1f946123'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'0502fbc6-6bc8-5145-9f5d-4b683a4318ed'); add: (#isReference->false); yourself)