steps
step473ec1cf01e6db49a73158d0370843f8
	<step>

	^ ((Dictionary new) add: (#definition->#'767367b4-0c7d-cf41-9d85-fc2b543d0747'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'9 December 2015 11:26:37 am'); yourself)); add: (#isProperty->false); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'473ec1cf-01e6-db49-a731-58d0370843f8'); add: (#isReference->true); yourself)