steps
step1258312ca457db40aa96499fda6b7623
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'a1a2f2b4-c481-a045-a31a-47069edeec1a').
(#iconCode -> 'nil').
(#id -> #'1258312c-a457-db40-aa96-499fda6b7623').
(#isProperty -> true).
(#label -> nil).
(#next -> #'e68d82d7-0f82-5e4f-990d-0b292c42da7f').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 4410)
}))
})