steps
step6d395bc8bf7777499480a5230a30d62f
	<step>

	^ ((Dictionary new) add: (#definition->#'2f12cab0-c913-b847-9cf8-08603c49889e'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 October 2015 11:08:14 am'); yourself)); add: (#isProperty->false); add: (#next->#'94e3fbd0-08ad-ea49-aa1d-8bf2961de5fc'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'6d395bc8-bf77-7749-9480-a5230a30d62f'); add: (#isReference->false); yourself)