steps
step6dcf4d7c0337da4385f9526e23934ee9
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'1bf3602c-26fb-4b40-a55a-f0133f1f17d4').
(#iconCode -> 'nil').
(#id -> #'6dcf4d7c-0337-da43-85f9-526e23934ee9').
(#label -> nil).
(#next -> #'86247f76-5b43-d748-82a2-b2d9e56e443a').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'6dcf4d7c-0337-da43-85f9-526e23934ee9').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 September 2013 6:51:45 pm').
(#priority -> 3340)}))})