steps
stepe81669edebe0c84e95e77ac5889d8779
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'ecc82096-e22c-1446-9001-ba0f0f6d0be2').
(#iconCode -> 'nil').
(#id -> #'e81669ed-ebe0-c84e-95e7-7ac5889d8779').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'e81669ed-ebe0-c84e-95e7-7ac5889d8779').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '3 September 2013 1:56:59 pm').
(#priority -> 980)}))})