steps
step09e805941621c84da66da59ada9c72d2
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'9da4044a-6245-9f40-80d0-0effae24ca11').
(#iconCode -> 'nil').
(#id -> #'09e80594-1621-c84d-a66d-a59ada9c72d2').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'21c91c05-8d72-194f-bf60-b5aff02d7a97').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '22 March 2018 9:57:33 pm')}))})