steps
step6a945c46e2f2ac418b3edadc1328d8a3
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'0481a903-f8da-2d42-9c11-991745884f3d').
(#iconCode -> 'nil').
(#id -> #'6a945c46-e2f2-ac41-8b3e-dadc1328d8a3').
(#label -> 'Pretty print').
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '24 February 2014 11:02:55 am').
(#priority -> 5850)}))})