steps
step045e9d2cb29a4641b942d4b769535d4a
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #iconAndLabel).
(#iconCode -> 'nil').
(#id -> #'045e9d2c-b29a-4641-b942-d4b769535d4a').
(#label -> nil).
(#next -> #'ed827037-94ca-9a45-b223-3148d0dc9fc9').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 July 2014 2:13:16 pm').
(#priority -> 6500)}))})