steps
step9fe8fed8f944ec41b97b3eff6b3cf74f
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'6791d9d6-2faf-3448-8e22-0aa4c948acdc').
(#iconCode -> 'nil').
(#id -> #'9fe8fed8-f944-ec41-b97b-3eff6b3cf74f').
(#label -> nil).
(#next -> #'b3a5a8de-9e73-f64d-a960-3946a4e8fbe5').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 10:25:09 am').
(#labelColor -> '#006600').
(#priority -> 5060)}))})