steps
step34fc784ff4655b4d8acf4f6f5d16883e
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'63eaf355-b75d-db42-a29b-df015c798b3b').
(#iconCode -> 'nil').
(#id -> #'34fc784f-f465-5b4d-8acf-4f6f5d16883e').
(#isProperty -> false).
(#label -> nil).
(#next -> #'c8dbe40d-f1cc-f846-b4af-f648fc24e1da').
(#properties -> (Dictionary newFrom: {
(#after -> #(#defaultPropertiesExtended)).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '1 February 2016 2:01:31 pm')}))})