steps
step7f7cb928c2c5c8408c91995fa40b1fd5
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupStep).
(#definition -> #category).
(#iconCode -> 'nil').
(#id -> #'7f7cb928-c2c5-c840-8c91-995fa40b1fd5').
(#label -> nil).
(#next -> #'f54c9a3b-47b7-6a42-a9a4-1843fbd23ecd').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 November 2013 4:22:46 pm').
(#priority -> 4390)}))})