steps
stepebce0b0460c9a340a531b5c1f93c9a20
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQuerySortStep).
(#definition -> #'d94d89dd-c32f-f144-b8b5-f265d775a7f5').
(#iconCode -> 'nil').
(#id -> #'ebce0b04-60c9-a340-a531-b5c1f93c9a20').
(#label -> nil).
(#next -> #'3cce12f6-e3d5-5b40-82fa-ff0f97f9844c').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1070)}))})