steps
step47204d819a245149ad0701d582da03b4
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupStep).
(#definition -> #'eb2e0d5a-634c-fa40-9782-0e28013862b5').
(#iconCode -> 'nil').
(#id -> #'47204d81-9a24-5149-ad07-01d582da03b4').
(#label -> nil).
(#next -> #'3554a784-6c63-324c-aeca-db77b530eb36').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '8 November 2013 4:40:32 pm').
(#priority -> 4270)}))})