steps
step2a5bc3f7fc5f4d42bc5d1a7c79ebf632
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'02eb996a-482e-a94a-b607-47360c8f1033').
(#iconCode -> 'nil').
(#id -> #'2a5bc3f7-fc5f-4d42-bc5d-1a7c79ebf632').
(#isProperty -> false).
(#isReference -> true).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '29 March 2019 5:00:11.33635 pm').
(#view -> ViTreeViewExtended)}))})