steps
step1816b6d5ac0875439b14edd58be27deb
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupSortStep).
(#definition -> #compareObjectsAsStrings).
(#iconCode -> 'nil').
(#id -> #'1816b6d5-ac08-7543-9b14-edd58be27deb').
(#label -> nil).
(#next -> #'e0d4454d-0188-6242-916d-1c1f2b47e445').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 2430)}))})