steps
stepb15f906e0d17994c9585d7487285b6d2
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'6b27229b-8de9-af48-8277-e920eda66d72').
(#iconCode -> 'nil').
(#id -> #'b15f906e-0d17-994c-9585-d7487285b6d2').
(#isProperty -> true).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 October 2015 3:43 pm')}))})