steps
stepe95778393b928e4fa413365561ade680
	<step>

	^ ((Dictionary new) add: (#definition->#'1f219126-4aa6-c146-82bc-ec3355f25c46'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#view->ViPluggableButtonBarMorph); add: (#creationTimeStamp->'19 October 2015 11:47:09 am'); add: (#isNew->false); yourself)); add: (#isProperty->true); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'e9577839-3b92-8e4f-a413-365561ade680'); add: (#isReference->false); yourself)