steps
stepb2d07dee10329043b2c7876a7ef811bb
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'77a2ad58-1e74-ba40-b2b6-d596c594480b').
(#iconCode -> 'nil').
(#id -> #'b2d07dee-1032-9043-b2c7-876a7ef811bb').
(#label -> nil).
(#next -> #'d78c13da-2871-4040-8d24-eb9d6565f332').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1500)}))})