steps
step580b86a154c03a4fa37cd12c765b21d4
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'8287f41b-826f-0247-b83e-45b6688f9d76').
(#iconCode -> 'UiSilkIcons folderIcon').
(#id -> #'580b86a1-54c0-3a4f-a37c-d12c765b21d4').
(#label -> 'Folders (recursive)').
(#next -> #'c0319874-c45b-7441-85fe-f6fe2ba7e2a9').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 320).
(#view -> ViTreeViewExtended)}))})