steps
stepe25bde3e7c879f44800a93ffa8166301
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'7fc05c0b-ec63-9941-b2b9-23e072ab4367').
(#iconCode -> 'nil').
(#id -> #'e25bde3e-7c87-9f44-800a-93ffa8166301').
(#label -> 'Packages').
(#next -> #'ac3b5160-4403-e846-987b-b3be159ed5dc').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #identity).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 1:01:49 pm').
(#priority -> 6120).
(#view -> ViTreeViewExtended)}))})