steps
step00d6ab8802b8d34398bf44d2fb8c6ab5
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'7057516c-b98e-ea4a-8d54-c4c3a0f4ab33').
(#iconCode -> 'UiFugueIcons folderTreeIcon').
(#id -> #'00d6ab88-02b8-d343-98bf-44d2fb8c6ab5').
(#label -> 'Class Category (Eclipse)').
(#next -> #'5f25d26e-227f-9b45-abc1-644d5e129639').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 September 2013 3:28:44 pm').
(#priority -> 3690).
(#view -> ViTreeViewExtended)}))})