steps
step46075c8756092c4186d5a35e4089e966
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'97a39793-e99b-4d4c-a8f5-037c909dceb8').
(#iconCode -> 'nil').
(#id -> #'46075c87-5609-2c41-86d5-a35e4089e966').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'39e0739a-b359-364a-9c0f-a5b758f8f9c8').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1230)}))})