steps
step46075c8756092c4186d5a35e4089e966
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'9413f6fc-c294-b744-9b9c-dbb35ec66f2d').
(#iconCode -> 'nil').
(#id -> #'46075c87-5609-2c41-86d5-a35e4089e966').
(#label -> nil).
(#next -> #'39e0739a-b359-364a-9c0f-a5b758f8f9c8').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1230)}))})