steps
step72bf683031d81b429ddc991381a326f0
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'0f6ea484-5e59-cf42-903b-7c7ae1e08a1b').
(#iconCode -> 'nil').
(#id -> #'72bf6830-31d8-1b42-9ddc-991381a326f0').
(#label -> nil).
(#next -> #'3ded3e1d-2e88-5448-a302-16e605bc65a0').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 September 2013 7:22:26 pm').
(#priority -> 3440)}))})