steps
step73c14db0512955439fe9dab9298595fb
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'1aa3bb2f-4562-d742-aaaa-ad85451123a5').
(#iconCode -> 'nil').
(#id -> #'73c14db0-5129-5543-9fe9-dab9298595fb').
(#isProperty -> true).
(#label -> nil).
(#next -> #'97de0441-7aaf-e745-a263-7000ac4db432').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 5920)
}))
})