steps
stepd7ca2eace77dc24a9906a486603160a0
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'28d8d922-627d-b84c-bbd1-0c95cf39f776').
(#iconCode -> 'nil').
(#id -> #'d7ca2eac-e77d-c24a-9906-a486603160a0').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'fea2b084-266a-3849-818c-699ce7e7042e').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '9 December 2015 11:26:37 am')}))})