steps
step56b2492ff394db42ade3e2d633f5230d
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'da22d385-455e-8b43-aa55-c0c3094b1ca7').
(#iconCode -> 'nil').
(#id -> #'56b2492f-f394-db42-ade3-e2d633f5230d').
(#label -> nil).
(#next -> #'0369a0d4-6ce3-9f49-b251-c92b852ef534').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '14 February 2014 9:31:36 am').
(#headerText -> 'Code').
(#priority -> 5260).
(#resizeMode -> #rigid)}))})