steps
stepca622048bcebfd4db080661d9e6b7f04
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'376843ac-1b55-5d4d-a85c-383a3f1acd6b').
(#iconCode -> 'nil').
(#id -> #'ca622048-bceb-fd4d-b080-661d9e6b7f04').
(#label -> 'Test classes').
(#next -> #'94740283-5bf2-514e-8eef-b18ce867137a').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 February 2014 2:54:36 pm').
(#priority -> 5250).
(#view -> ViTreeViewExtended)}))})