steps
stepcf7fdd6602719544b4a93ecca1e4a611
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'4455276a-46f3-b44c-84b8-7d1a0ab966e7').
(#iconCode -> 'nil').
(#id -> #'cf7fdd66-0271-9544-b4a9-3ecca1e4a611').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '23 July 2014 2:54:01 pm').
(#priority -> 6720)}))})