steps
stepa877e0b4377f244b96e5e6616c9f8247
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'fae5da89-8939-834f-ba54-c95104e46383').
(#iconCode -> 'nil').
(#id -> #'a877e0b4-377f-244b-96e5-e6616c9f8247').
(#isProperty -> true).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 February 2014 1:38:46 pm').
(#priority -> 5610)}))})