steps
step146f1f571f03c0418896b575dce4a8a6
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'4f5f11a8-043d-b143-ab9c-3e5a3d19b98e').
(#iconCode -> 'nil').
(#id -> #'146f1f57-1f03-c041-8896-b575dce4a8a6').
(#isProperty -> false).
(#label -> nil).
(#next -> #'0d1c954a-7c22-e045-92ca-a8bcb394cef3').
(#properties -> (Dictionary newFrom: {
(#after -> #(#groups)).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '3 April 2019 9:01:28.848845 am').
(#inputKind -> #(nil nil))}))})