steps
step35c886413f5616459402f1e5b85047ff
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'0731793a-d6b7-5d48-8e1b-92baf48768d7').
(#iconCode -> 'nil').
(#id -> #'35c88641-3f56-1645-9402-f1e5b85047ff').
(#isProperty -> false).
(#isReference -> true).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '29 May 2018 9:10:14 am').
(#inputKind -> #(nil nil nil ))}))})