steps
step7d49f967e5fd2d45a452864c859fa223
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'a752cd53-f161-ce42-ab24-5f3cf26f1912').
(#iconCode -> 'nil').
(#id -> #'7d49f967-e5fd-2d45-a452-864c859fa223').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'08b44027-bc56-f844-9826-f94859a5b557').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '5 June 2014 4:58:07 pm').
(#priority -> 6420)}))})