steps
step9495a7a136da3645afa0bb85011e21d1
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'de8216a7-6374-7b49-9452-fe1b108395fb').
(#iconCode -> 'nil').
(#id -> #'9495a7a1-36da-3645-afa0-bb85011e21d1').
(#isProperty -> true).
(#isReference -> false).
(#label -> 'Recover Unsaved Changes').
(#next -> #'e3c616ba-4453-c04b-b997-91416620222a').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 October 2015 11:47:09 am').
(#isGlobal -> true).
(#optimalExtent -> (442@373)).
(#view -> ViMultiPaneTiled)}))})