steps
step24d74d145e317641a5f6d6667eb3ffd2
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'b223ce01-c9dc-c043-a935-af79dde0b9a3').
(#iconCode -> 'nil').
(#id -> #'24d74d14-5e31-7641-a5f6-d6667eb3ffd2').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 6560)}))})