steps
stepe0aac258e0208a48a68d1554883e5b23
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'b7e922d6-b6a0-954b-b9d3-8f173c16b524').
(#iconCode -> 'nil').
(#id -> #'e0aac258-e020-8a48-a68d-1554883e5b23').
(#isProperty -> false).
(#label -> nil).
(#next -> #'fa3a3d8c-6bcb-ec4a-8af2-2ee1195bbafe').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '1 February 2016 2:17:14 pm').
(#inputKind -> MethodReference).
(#priority -> 550).
(#view -> ViTreePlainView)}))})