steps
step7b56c7af5bd248489eaec2af03afefde
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'3cdd8b70-a7c2-6d42-997e-c34bdb23d9a3').
(#iconCode -> 'nil').
(#id -> #'7b56c7af-5bd2-4848-9eae-c2af03afefde').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Methods').
(#priority -> 2740)}))})