steps
step5bac288b036f3b409351de76b1f7cd03
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'2b0346c1-9ba9-fc4d-8a85-bc8c3dbc3189').
(#iconCode -> 'nil').
(#id -> #'5bac288b-036f-3b40-9351-de76b1f7cd03').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'NumVersions').
(#labelColor -> '#AAAAAA').
(#priority -> 3130)}))})