steps
steppaneHierarchy
	<step>

	^ ((Dictionary new) add: (#definition->#'506ca8c1-1c8f-d34d-b7a1-273cb36303e8'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->ViPane); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'1 June 2015 1:40:11 pm'); add: (#isNew->false); yourself)); add: (#isProperty->true); add: (#next->#'f58af729-af2a-594d-87eb-c499c1bc536b'); add: (#label->'Pane Hierarchy'); add: (#iconCode->'nil'); add: (#id->#paneHierarchy); add: (#isReference->false); yourself)