steps
step46b904bc22e5a84a8f30894b0f7df352
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'9a123eed-f732-304a-8061-5921223ef529').
(#iconCode -> 'nil').
(#id -> #'46b904bc-22e5-a84a-8f30-894b0f7df352').
(#label -> nil).
(#next -> #'2b022238-c9a7-fe4b-8d2b-fa5c2250af5d').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 February 2014 8:38:45 am').
(#priority -> 5510)}))})