steps
step2ebbfcc818ea964396ea4d38fe7cf10a
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'0ffa7f9a-df28-b24e-9fe9-0a8bcfefe2d9').
(#iconCode -> 'nil').
(#id -> #'2ebbfcc8-18ea-9643-96ea-4d38fe7cf10a').
(#label -> nil).
(#next -> #'41f64542-f4fb-c341-8ee9-d1adfceebe00').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '23 July 2014 2:46:54 pm').
(#priority -> 6700)}))})