steps
step90bb3b19d2be164ea30683db53cee32e
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'f576b8f9-6587-f948-af53-df89adad624e').
(#iconCode -> 'nil').
(#id -> #'90bb3b19-d2be-164e-a306-83db53cee32e').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'ecc9e9ca-455e-c148-8762-1714a939cbe9').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '7 November 2013 11:04:24 am').
(#priority -> 5490)}))})