steps
stepaa477db37d101f488339140e6d470e38
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #subclasses).
(#iconCode -> 'nil').
(#id -> #'aa477db3-7d10-1f48-8339-140e6d470e38').
(#label -> nil).
(#next -> #'f45253e3-1e61-2344-8ebb-69fad9e592af').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1730)}))})