steps
stepe84072d2c593f549a93cd5dbeb2e3b94
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'753003be-d44a-284c-b617-5f685c572efe').
(#iconCode -> 'nil').
(#id -> #'e84072d2-c593-f549-a93c-d5dbeb2e3b94').
(#isProperty -> true).
(#label -> nil).
(#next -> #'3723f748-fad3-d446-8f95-d2d495e9a9cc').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1370)
}))
})