steps
step8c98ea105364be4bb343835196faca7e
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'6f38796b-7a6d-494e-926e-a2dc03b50f2e').
(#iconCode -> 'nil').
(#id -> #'8c98ea10-5364-be4b-b343-835196faca7e').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 June 2014 3:50:32 pm').
(#priority -> 6370)}))})