steps
step6a945c46e2f2ac418b3edadc1328d8a3
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'2049b680-ff5b-9142-8d46-8747950a70d2').
(#iconCode -> 'nil').
(#id -> #'6a945c46-e2f2-ac41-8b3e-dadc1328d8a3').
(#isProperty -> true).
(#isReference -> false).
(#label -> 'Pretty print').
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '24 February 2014 11:02:55 am').
(#inputKind -> CompiledMethod).
(#priority -> 5850).
(#view -> ViTreeViewExtended)}))})