steps
step9cdc94fada62e04293a100f1773d45fc
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #iconAndLabel).
(#iconCode -> 'nil').
(#id -> #'9cdc94fa-da62-e042-93a1-00f1773d45fc').
(#label -> nil).
(#next -> #'322c353d-b953-2743-9b11-f8c0ae4041b1').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Object').
(#priority -> 3070)}))})