steps
stepa04dcc3b6be7fa429cc3a91b1141dcf1
	<step>

	^ ((Dictionary new) add: (#definition->#'2b3e53a8-8a74-4f4e-8009-e73f433a0b29'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'12 May 2015 4:36:46 pm'); add: (#copyOf->#'23141405-8b20-3243-95b5-5a3b8ad5566e'); yourself)); add: (#isProperty->false); add: (#next->#'4e96ab7f-cc8d-1040-aad0-ed4e9026b875'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'a04dcc3b-6be7-fa42-9cc3-a91b1141dcf1'); add: (#isReference->false); yourself)