steps
stepa6cec8a8300422479d7c1eb029cb617c
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'cba8c7af-20fe-4f44-a0d4-b014a53ded9f').
(#iconCode -> 'nil').
(#id -> #'a6cec8a8-3004-2247-9d7c-1eb029cb617c').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'f99fb960-e160-9e4b-aa91-0c8cd134d9c7').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '24 August 2016 4:50:38 pm')}))})