steps
step4483ab73df68ab43b4106de476dc855a
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'1bb9207e-4ee2-404a-8f53-21cee72442ae').
(#iconCode -> 'nil').
(#id -> #'4483ab73-df68-ab43-b410-6de476dc855a').
(#label -> nil).
(#next -> #'85478cdc-dec7-5648-b9af-bbf1c6a6d389').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 2210)}))})