steps
step4291e65fca68f04bbbb841cf2734c087
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'7dd11be7-db09-6d43-bc91-fbc818f50e1e').
(#iconCode -> 'nil').
(#id -> #'4291e65f-ca68-f04b-bbb8-41cf2734c087').
(#label -> nil).
(#next -> #'77862f46-0851-124e-b1ff-6cb2e962a0c8').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'4291e65f-ca68-f04b-bbb8-41cf2734c087').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 September 2013 6:45:44 pm').
(#priority -> 3310)}))})