steps
stepfcbd4f9fbe45b445ae2e7b432040e8fd
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'fdc64c2e-e431-d24d-a8da-ff219e7e9b9d').
(#iconCode -> 'UiSilkIcons pageWhiteTextWidthIcon').
(#id -> #'fcbd4f9f-be45-b445-ae2e-7b432040e8fd').
(#isProperty -> false).
(#label -> 'Load Text File').
(#next -> #'b0443283-7194-df4e-bcb6-2dc3d3395f1b').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#inputKind -> DirectoryEntryFile).
(#outputKind -> Text).
(#priority -> 720).
(#view -> ViTreeViewExtended)}))})