steps
step6432870100b2654ea36998b5ecac31fd
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'dfc52635-0f67-ec44-95da-0015581b3976').
(#iconCode -> 'nil').
(#id -> #'64328701-00b2-654e-a369-98b5ecac31fd').
(#label -> nil).
(#next -> #'5e941cab-2cc7-0646-9ed0-d8493d5d3d0e').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 November 2013 4:53:55 pm').
(#labelColor -> #AAAAAA).
(#priority -> 4460)}))})