steps
step8aa2299483215647823f8e9203115b01
	<step>

	^ ((Dictionary new) add: (#definition->#'73717316-edf3-0d4d-b96f-250a2ed95c7d'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'9 December 2015 9:44:59 am'); yourself)); add: (#isProperty->false); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'8aa22994-8321-5647-823f-8e9203115b01'); add: (#isReference->true); yourself)