steps
step052b52386b5004429f4f56eeaf6e07d7
	<step>

	^ ((Dictionary new) add: (#definition->#'e7b1027a-2aa4-634b-ac62-fdbf47813e8e'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'9 December 2015 11:42:44 am'); yourself)); add: (#isProperty->true); add: (#next->#'c68e2eaf-ff3f-eb4b-9f51-74527cb495ac'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'052b5238-6b50-0442-9f4f-56eeaf6e07d7'); add: (#isReference->false); yourself)