steps
stepb0d75ae30b0446498258e41f89b3bfc6
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'f3074b61-33cf-6746-b4b6-210a2eb131a0').
(#iconCode -> 'nil').
(#id -> #'b0d75ae3-0b04-4649-8258-e41f89b3bfc6').
(#isProperty -> false).
(#label -> nil).
(#next -> #'26f3a2b2-f47a-644b-ac5f-159e2365b955').
(#properties -> (Dictionary newFrom: {
(#after -> #(#groupsMinimal)).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:13.501834 pm')}))})