steps
step888352182a2edf43a18522dadbdc15d2
	<step>

	^ ((Dictionary new) add: (#definition->#'ac630cc7-c5d7-d840-9593-845690f6bb00'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isGlobal->true); add: (#creationAuthor->'mt'); add: (#view->ViLineEdit); add: (#creationTimeStamp->'9 December 2015 10:56:04 am'); add: (#priority->5000); add: (#isNew->false); add: (#help->'Type something...'); yourself)); add: (#isProperty->false); add: (#next->#'34d74f03-9769-6140-afa3-e3b7a3f2cd59'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'88835218-2a2e-df43-a185-22dadbdc15d2'); add: (#isReference->false); yourself)