steps
step2b3d7c04cf7f9243b02d95fc7b500018
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'f7ea5265-696e-8243-9cb0-c42c1201004d').
(#iconCode -> 'nil').
(#id -> #'2b3d7c04-cf7f-9243-b02d-95fc7b500018').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Methods').
(#priority -> 1330)}))})