steps
stepab2beffcf1ae014ea424a1270d4facd9
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'92d66888-3e33-e449-82ee-fc6d9fdf72e6').
(#iconCode -> 'nil').
(#id -> #'ab2beffc-f1ae-014e-a424-a1270d4facd9').
(#label -> nil).
(#next -> #'8d3e35af-10d4-a346-9157-f3ad76331d4d').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Object').
(#priority -> 2510)}))})