steps
stepf45b857ee698274cb3d6467851b2d5dc
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupStep).
(#definition -> #'49ccd054-1123-b244-8a4b-6541e357ab53').
(#iconCode -> 'nil').
(#id -> #'f45b857e-e698-274c-b3d6-467851b2d5dc').
(#label -> nil).
(#next -> #'5d53db96-8bb9-fb43-921c-fbcba4297063').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 November 2013 4:59:20 pm').
(#priority -> 4440)}))})