steps
stepcf440614e202124f830d3b4a1d9eef00
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupSortStep).
(#definition -> #compareObjectsAsStrings).
(#iconCode -> 'nil').
(#id -> #'cf440614-e202-124f-830d-3b4a1d9eef00').
(#label -> nil).
(#next -> #'494bc6a5-c09d-fc4f-b22f-37955f890e49').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1630)}))})