steps
step11b9014af6fa1a408446f63ddf69232f
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'df4edb83-23fe-dc47-a52e-67c69926d29a').
(#iconCode -> 'nil').
(#id -> #'11b9014a-f6fa-1a40-8446-f63ddf69232f').
(#label -> 'Processes').
(#next -> #'71efc7d9-c3cb-7246-9652-6b74bc022b8e').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'5a501a24-fd9a-8741-8e54-44a08209481a').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 6160)}))})