steps
step57ef0b8f46a4174480b46974ec1adc76
	<step>

	^ ((Dictionary new) add: (#definition->#'92af904a-14aa-db49-84ab-1697ba082636'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'12 May 2015 4:36:46 pm'); add: (#copyOf->#'1d933e47-9811-1b4a-ba4a-fb88f24d5086'); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->#'14bc7fef-be90-a949-91f7-a0b9c1d7f2ff'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'57ef0b8f-46a4-1744-80b4-6974ec1adc76'); add: (#isReference->false); yourself)