steps
stepe2aeb51f931d4e43a8d9a68001d03b29
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'396ebf06-2f4b-6749-a78e-54a72120ec81').
(#iconCode -> 'nil').
(#id -> #'e2aeb51f-931d-4e43-a8d9-a68001d03b29').
(#isProperty -> true).
(#isReference -> false).
(#label -> 'Annotation').
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#color -> (Color r: 0.553 g: 0.796 b: 0.553)).
(#copyOfStep -> #'6a945c46-e2f2-ac41-8b3e-dadc1328d8a3').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '24 February 2014 11:02:55 am').
(#inputKind -> CompiledMethod).
(#priority -> 5890).
(#view -> ViTreeViewExtended)}))})