steps
step21bca68025a51e4b8a4bde8ef046376f
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'045ec7be-6ef3-2448-b846-acab2248a757').
(#iconCode -> 'nil').
(#id -> #'21bca680-25a5-1e4b-8a4b-de8ef046376f').
(#isProperty -> false).
(#isReference -> true).
(#label -> nil).
(#next -> #'45fba510-b1f4-ca44-b321-5034c7e36e91').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 3:12:48.400594 pm')}))})