steps
step11525e3eab659643be1d444ca45f2674
	<step>

	^ ((Dictionary new) add: (#definition->#'f46d1419-d707-6b48-a23c-dc58d7717240'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'1 June 2015 1:44:24 pm'); yourself)); add: (#isProperty->false); add: (#next->#'8c87a9e9-a74c-3749-b4ba-b8960612b464'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'11525e3e-ab65-9643-be1d-444ca45f2674'); add: (#isReference->false); yourself)