steps
step9cab60cb31ee7f4b8cac34c9bed5c6ab
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'4c648ac4-8ed2-4e47-b5bf-224c33a1f999').
(#iconCode -> 'nil').
(#id -> #'9cab60cb-31ee-7f4b-8cac-34c9bed5c6ab').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Origin').
(#labelColor -> '#AAAAAA').
(#priority -> 3150)}))})