steps
step233b181dfccc094d8b70ba191cfe05ba
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'766d7729-fc4c-6d43-a99b-6b3c832c0d0d').
(#iconCode -> 'nil').
(#id -> #'233b181d-fccc-094d-8b70-ba191cfe05ba').
(#label -> nil).
(#next -> #'d8b2f450-0635-3046-bb39-a2cec077ae4c').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 September 2013 7:15:27 pm').
(#priority -> 3410)}))})