steps
stepe5bd3f6cf63fb14889bc82784354babd
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'064de4ea-4a9a-d549-942b-960508fd4d6c').
(#iconCode -> 'nil').
(#id -> #'e5bd3f6c-f63f-b148-89bc-82784354babd').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'57759e79-162b-7647-b6c7-af705463339b').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Modified').
(#labelColor -> '#AAAAAA').
(#priority -> 1160)}))})