steps
step5123647a039a3d47b703c3d759aefb93
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'c05078c3-60b7-974f-9638-11f50024055a').
(#iconCode -> 'UiSilkIcons carIcon').
(#id -> #'5123647a-039a-3d47-b703-c3d759aefb93').
(#isProperty -> false).
(#label -> 'Class hierarchy (subclasses)').
(#next -> #'4f14fbe5-65d1-c74f-ab1f-7751495fcf7c').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '9 December 2015 1:06:03 pm').
(#inputKind -> ClassDescription).
(#priority -> 300).
(#view -> ViTreeViewExtended)}))})