steps
step688b9e53cc309341a36854f6c47e402c
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'1445ab5c-9464-fc42-875c-7b4e4ec4fde0').
(#iconCode -> 'nil').
(#id -> #'688b9e53-cc30-9341-a368-54f6c47e402c').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'d86f12e2-c38d-4e4e-807e-4615652c2137').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'d9634b11-bde6-1a40-a0b4-7be880afc37a').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 3950)}))})