steps
stepf54c9a3b47b76a42a9a41843fbd23ecd
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupSortStep).
(#definition -> #compareObjectsAsStrings).
(#iconCode -> 'nil').
(#id -> #'f54c9a3b-47b7-6a42-a9a4-1843fbd23ecd').
(#label -> nil).
(#next -> #'1258312c-a457-db40-aa96-499fda6b7623').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 November 2013 4:23 pm').
(#priority -> 4400)}))})