steps
steped82703794ca9a45b2233148d0dc9fc9
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'e3554109-9f58-a54a-bcb3-b119f32adc6f').
(#iconCode -> 'nil').
(#id -> #'ed827037-94ca-9a45-b223-3148d0dc9fc9').
(#isProperty -> true).
(#label -> nil).
(#next -> #'88b2345b-3bda-5e41-a90f-b81c36b39fd8').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 July 2014 2:15:45 pm').
(#priority -> 6510)}))})