steps
stepd9a22b3cf29a7840bb49c3f6d664b189
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'c7130d64-9f4e-7247-bd60-9214f1d0f522').
(#iconCode -> 'nil').
(#id -> #'d9a22b3c-f29a-7840-bb49-c3f6d664b189').
(#label -> nil).
(#next -> #'73012cd9-6457-9649-bb16-3f77f5dea0d2').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 4:21:57 pm').
(#headerText -> 'Count').
(#labelColor -> '#AAAAAA').
(#priority -> 3220)}))})