steps
step7f804761434fc9439d9bd3e24e534b7f
	<step>

	^ (Dictionary newFrom: {
(#'_def' -> (Dictionary newFrom: {
(#block -> [:in :out | out addAll: in]).
(#className -> #ViScriptDefinition).
(#id -> #'6184071b-b12e-3b49-b5d1-9f830266433b').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '9 December 2015 10:30:20 am')
})).
(#sourceCode -> '[:in :out | out addAll: in]')
})).
(#className -> #ViScriptStep).
(#definition -> #'6184071b-b12e-3b49-b5d1-9f830266433b').
(#iconCode -> 'nil').
(#id -> #'7f804761-434f-c943-9d9b-d3e24e534b7f').
(#isProperty -> false).
(#label -> 'Remove duplicates').
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '9 December 2015 10:30:20 am').
(#out -> Set)
}))
})