steps
step7b32938cf398a742a1ca38108a4a569b
	<step>

	^ (Dictionary newFrom: {
(#'_def' -> (Dictionary newFrom: {
(#block -> [:in :out | out addAll: in]).
(#className -> #ViScriptDefinition).
(#id -> #'e7757bdb-25c1-5249-95ae-95baac8a366d').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '20 May 2015 2:55:26 pm')
})).
(#sourceCode -> '[:in :out | out addAll: in]')
})).
(#className -> #ViScriptStep).
(#definition -> #'e7757bdb-25c1-5249-95ae-95baac8a366d').
(#iconCode -> 'nil').
(#id -> #'7b32938c-f398-a742-a1ca-38108a4a569b').
(#isProperty -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#after -> #(#'8451e0da-6c99-7f41-9483-316176f07642')).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '20 May 2015 2:55:26 pm')
}))
})