steps
step05197a071395e04d90c79ba0a635f185
	<step>

	^ ((Dictionary new) add: (#definition->#'c77245e2-be55-c749-a0b3-b89f7bad59d9'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->PackageInfo); add: (#creationTimeStamp->'20 May 2015 2:43:15 pm'); add: (#priority->20); add: (#creationAuthor->'mt'); add: (#out->Set); add: (#view->ViTreeViewExtended); yourself)); add: (#isProperty->false); add: (#next->#'3bc53c43-eaf3-9240-8d99-587e9a09d49c'); add: (#label->'Class hierarchy'); add: (#iconCode->'UiSilkIcons carIcon'); add: (#id->#'05197a07-1395-e04d-90c7-9ba0a635f185'); add: (#isReference->false); yourself)