steps
stepa36810b7a281b34d9d22e1f1a585db30
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'6a55f686-f73f-d94c-b810-e6a946eb771a').
(#iconCode -> 'nil').
(#id -> #'a36810b7-a281-b34d-9d22-e1f1a585db30').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '23 September 2013 5:12:03 pm').
(#priority -> 4130)}))})