steps
step7d49f967e5fd2d45a452864c859fa223
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'92d66888-3e33-e449-82ee-fc6d9fdf72e6').
(#iconCode -> 'nil').
(#id -> #'7d49f967-e5fd-2d45-a452-864c859fa223').
(#label -> nil).
(#next -> #'08b44027-bc56-f844-9826-f94859a5b557').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '5 June 2014 4:58:07 pm').
(#priority -> 6420)}))})