steps
stepba4b7a9cc7c95145a45e2cdf2b0a3940
	<step>

	^ ((Dictionary new) add: (#definition->#'a24a8241-358e-5643-a2f1-62eed7d243c0'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->ClassDescription); add: (#priority->250); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'9 December 2015 11:55:27 am'); add: (#view->ViTreeView); yourself)); add: (#isProperty->false); add: (#next->#'95c74daf-50da-9d48-956b-a1e377ae9019'); add: (#label->'Vocabulary (for class)'); add: (#iconCode->'UiFugueIcons bookBrownIcon'); add: (#id->#'ba4b7a9c-c7c9-5145-a45e-2cdf2b0a3940'); add: (#isReference->false); yourself)