steps
stepb193f637d3a4cb4b9b3e94c7b7ba29e9
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'1e58328f-7884-9b46-aac3-15d4c0d243b5').
(#iconCode -> 'nil').
(#id -> #'b193f637-d3a4-cb4b-9b3e-94c7b7ba29e9').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'ab4af50f-105f-424d-95d1-36bfd2f47ad3').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 10:25:52 am').
(#priority -> 5070)}))})