steps
stepac3b51604403e846987bb3be159ed5dc
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQuerySortStep).
(#definition -> #'d94d89dd-c32f-f144-b8b5-f265d775a7f5').
(#iconCode -> 'nil').
(#id -> #'ac3b5160-4403-e846-987b-b3be159ed5dc').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '27 May 2014 2:54:18 pm').
(#priority -> 6360)}))})