steps
step4b91c6bda48d134e8d10515a06acf0cc
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'9286450b-e6b8-d94f-9454-366751f2fce5').
(#iconCode -> 'nil').
(#id -> #'4b91c6bd-a48d-134e-8d10-515a06acf0cc').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'1006fd36-1341-dc4a-8678-ca7e4315063f').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 1:09:51 pm').
(#isGlobal -> true).
(#outputKind -> PackageOrganizer).
(#priority -> 840).
(#view -> ViTreeViewExtended)}))})