steps
stepd89cc75273e40742ac29eb770d5d8fc5
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQuerySortStep).
(#definition -> #compareObjectsBySelector).
(#iconCode -> 'nil').
(#id -> #'d89cc752-73e4-0742-ac29-eb770d5d8fc5').
(#label -> nil).
(#next -> #'1d58d23a-244c-b84e-8448-52a3acfb1544').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1340)}))})