steps
step8eec0dd86d7cd54f8d45ff176d005f1b
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'b625a012-847e-c143-a9c1-1b958a07ffca').
(#iconCode -> 'nil').
(#id -> #'8eec0dd8-6d7c-d54f-8d45-ff176d005f1b').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 September 2013 6:51:45 pm').
(#headerText -> 'Type').
(#priority -> 3870)}))})