steps
stepaf7030042f554940abd6c3b1a717db27
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'60d51cf0-3914-2045-ae54-eea3e1bab488').
(#iconCode -> 'nil').
(#id -> #'af703004-2f55-4940-abd6-c3b1a717db27').
(#label -> 'Methods w/ Longest History').
(#next -> #'59e1a354-ea9e-3d4d-b4c6-70d3a9eb6d48').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 930)}))})