steps
stepformattedQueries
	<step>

	^ ((Dictionary new) add: (#definition->#'5c81b0a9-9ca8-4d4f-bf64-ec5c3d25c09f'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->ViQueryStep); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'7 December 2015 2:00:40 pm'); add: (#outputKind->ViQueryStep); add: (#view->ViTreeView); add: (#yieldOn->#(#activated )); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->#'1af811b8-5914-fa4a-a308-6a17174c3d9c'); add: (#label->'Scripts'); add: (#iconCode->'nil'); add: (#id->#formattedQueries); add: (#isReference->false); yourself)