steps
stepdd56b3e99e71b44e9a605319116f9cdd
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'8082cd62-4852-1c49-8e16-23b3ddd626bf').
(#iconCode -> 'nil').
(#id -> #'dd56b3e9-9e71-b44e-9a60-5319116f9cdd').
(#isProperty -> false).
(#label -> nil).
(#next -> #'e5f64c36-bb63-3b4e-b596-1aac061b81a3').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '12 May 2015 4:43:48 pm')}))})