steps
step0c8adf165e6c8046b0976a6dfeaa52ea
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupStep).
(#definition -> #'07203f12-f1b6-9746-9884-0b9e8f1a4f6b').
(#iconCode -> 'nil').
(#id -> #'0c8adf16-5e6c-8046-b097-6a6dfeaa52ea').
(#label -> nil).
(#next -> #'e4134486-b81a-2041-84a2-805061658e31').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1790)}))})