steps
step070104b018c47348bdce375fa5dbc93c
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'bf274afd-16df-a24b-bc4a-5f558b1d5f84').
(#iconCode -> 'nil').
(#id -> #'070104b0-18c4-7348-bdce-375fa5dbc93c').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'668146bb-9b8d-f241-b4ed-dcc75bd19810').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 2650)}))})