steps
step78cd19878352584e9b6b7582a5be6451
	<step>

	^ ((Dictionary new) add: (#definition->#'331ef878-24d5-f442-9676-04b6c451895a'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->CompiledMethod); add: (#priority->300); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'9 December 2015 11:02:31 am'); add: (#view->ViMethodEditorView); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->nil); add: (#label->'Source code'); add: (#iconCode->'UiSilkIcons pencilIcon'); add: (#id->#'78cd1987-8352-584e-9b6b-7582a5be6451'); add: (#isReference->false); yourself)