steps
stepd61e908712152d4eb336316c41064b72
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'7b526e28-633d-384d-b578-5dd745b36160').
(#iconCode -> 'nil').
(#id -> #'d61e9087-1215-2d4e-b336-316c41064b72').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '23 July 2014 1:18:56 pm').
(#priority -> 6650)}))})