steps
step251d8797f8c8a443891de54746e9e7e2
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'e329abbd-64b6-114f-b13c-ddc64cb852d5').
(#iconCode -> 'nil').
(#id -> #'251d8797-f8c8-a443-891d-e54746e9e7e2').
(#isProperty -> false).
(#label -> nil).
(#next -> #'f2876136-7eb8-e94b-864d-61f883d28db9').
(#properties -> (Dictionary newFrom: {
(#after -> #(#groupsMinimal)).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:13.532834 pm')
}))
})