steps
step8541e0243a147d4a9ac55c521a7c4f27
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'c7f13eaf-02b3-7046-8b08-c7d1a5a911dd').
(#iconCode -> 'nil').
(#id -> #'8541e024-3a14-7d4a-9ac5-5c521a7c4f27').
(#label -> 'Outline (w/ LOC categories)').
(#next -> #'f128659b-7f02-364d-afc1-143f418bf135').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'217e17d6-56aa-ff44-a6d3-2e3bf316d470').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 5140)}))})