steps
step3723f748fad3d4468f95d2d495e9a9cc
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'e8978022-c037-0a4b-9e33-a81e1e562382').
(#iconCode -> 'nil').
(#id -> #'3723f748-fad3-d446-8f95-d2d495e9a9cc').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#labelColor -> '#AAAAAA').
(#priority -> 1380)}))})