steps
step42ed5d046483c94482c80339789652e4
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'452e9359-82a2-3f43-94fe-c108dfa3fef0').
(#iconCode -> 'UiFugueIcons priceTagExclamationIcon').
(#id -> #'42ed5d04-6483-c944-82c8-0339789652e4').
(#label -> 'Unclassified methods').
(#next -> #'24f23db6-299d-cc46-bb92-693cb90073d6').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 690).
(#view -> ViTreeViewExtended)}))})