steps
step676364194db68c43aa22b3948e02e796
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'a88e9179-6a76-5743-8983-30aea2a491d1').
(#iconCode -> 'nil').
(#id -> #'67636419-4db6-8c43-aa22-b3948e02e796').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'42ef8b6b-8cf0-da4a-b075-0fb0146d805c').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Name').
(#priority -> 2780)}))})