steps
stepc70e68dd9e93cc44a8c35fe0395e21ac
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'5e210b4e-c77b-6847-8b84-3bce5313ac4d').
(#iconCode -> 'nil').
(#id -> #'c70e68dd-9e93-cc44-a8c3-5fe0395e21ac').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'ed57b1e0-4b74-094a-926b-2776acef9b31').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '14 February 2014 10:53:24 am').
(#headerText -> #scU).
(#priority -> 5360)}))})