steps
stepced9b6e36a4cee4c82843ecb2492159f
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'c4da742e-4271-244c-8108-eb04103dd8bd').
(#iconCode -> 'ViEclipseIcons packageIcon').
(#id -> #'ced9b6e3-6a4c-ee4c-8284-3ecb2492159f').
(#isProperty -> true).
(#label -> 'Package Explorer').
(#next -> #'157a5c4c-d1a5-cf4a-bced-696f7e70934d').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 September 2013 7:59:15 pm').
(#priority -> 3540).
(#view -> ViTreeViewExtended)}))})