steps
stepcdbe8071be1b984eb62a2c1b721153c0
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'83108bd2-fbfa-9b49-a141-f65fbcf9adf4').
(#iconCode -> 'nil').
(#id -> #'cdbe8071-be1b-984e-b62a-2c1b721153c0').
(#label -> nil).
(#next -> #'c95c6c53-431d-d44d-895e-41f83dbc02c4').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'4078cbfe-867e-564c-85b0-ac2edd21217d').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 September 2013 6:56:36 pm').
(#headerText -> 'Description').
(#labelColor -> '000000').
(#priority -> 3900).
(#resizeMode -> #rigid)}))})