steps
stepd85d6ab8f194f1429b0a05b44c7f6b73
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'afd99428-9871-f545-aecc-af8140ef7bec').
(#iconCode -> 'nil').
(#id -> #'d85d6ab8-f194-f142-9b0a-05b44c7f6b73').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'a04dcc3b-6be7-fa42-9cc3-a91b1141dcf1').
(#properties -> (Dictionary newFrom: {
(#copyOf -> #'5ab5bb13-a76a-a64d-864e-d4481003d295').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '12 May 2015 4:36:46 pm')}))})