steps
stepaa3ec915c019e9418b9bf9baa09fd69a
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'a5066753-64c1-b04f-b645-d66d41db274d').
(#iconCode -> 'nil').
(#id -> #'aa3ec915-c019-e941-8b9b-f9baa09fd69a').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 February 2014 10:22:16 am').
(#priority -> 5540).
(#view -> #text)}))})