steps
step73012cd964579649bb163f77f5dea0d2
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'e4592bf3-ca81-2446-be75-29fee8fe6683').
(#iconCode -> 'nil').
(#id -> #'73012cd9-6457-9649-bb16-3f77f5dea0d2').
(#label -> nil).
(#next -> #'2ae8b5e0-925f-904b-82ab-2fe17cce67ab').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 4:21:57 pm').
(#headerText -> 'Bar').
(#labelColor -> '#AAAAAA').
(#priority -> 3230)}))})