steps
step044ec24710c99946a6bc5044f6bc4a4d
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'757d1b47-15a6-c340-a4aa-7a62a3a4d909').
(#iconCode -> 'nil').
(#id -> #'044ec247-10c9-9946-a6bc-5044f6bc4a4d').
(#isProperty -> false).
(#label -> nil).
(#next -> #'0c69c004-a3f9-134e-8ba6-eafca2418592').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '10 February 2014 4:49:24 pm').
(#isGlobal -> true).
(#outputKind -> SystemNavigation).
(#priority -> 850).
(#view -> ViTreeViewExtended)
}))
})