steps
stepfdc9d7842f4f8a428553dfc7982b9585
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'b0fffbca-3097-5b44-8c4f-0ec8eb682a21').
(#iconCode -> 'nil').
(#id -> #'fdc9d784-2f4f-8a42-8553-dfc7982b9585').
(#label -> nil).
(#next -> #'e89d0b5a-e4fe-584b-aed4-96f20385b05c').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '5 June 2014 4:50:14 pm').
(#priority -> 6190)}))})