steps
stepfb419e86ae99874683208ef4c8c7e6d2
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'f6b1e906-d973-224e-866c-a78383bbeec8').
(#iconCode -> 'nil').
(#id -> #'fb419e86-ae99-8746-8320-8ef4c8c7e6d2').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'e81669ed-ebe0-c84e-95e7-7ac5889d8779').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'fb419e86-ae99-8746-8320-8ef4c8c7e6d2').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '6 September 2013 9:10:21 pm').
(#priority -> 1040)}))})