steps
step88b2345b3bda5e41a90fb81c36b39fd8
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'6731f25c-5705-6843-8e6f-0c4263ca2073').
(#iconCode -> 'nil').
(#id -> #'88b2345b-3bda-5e41-a90f-b81c36b39fd8').
(#label -> nil).
(#next -> #'045e9d2c-b29a-4641-b942-d4b769535d4a').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 July 2014 2:13:34 pm').
(#priority -> 6520)}))})