steps
stepc0cac2e3ab77904fa0ed936a31a423ea
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'c8b3a260-a50f-524a-9f5a-bafe2de5115d').
(#iconCode -> 'nil').
(#id -> #'c0cac2e3-ab77-904f-a0ed-936a31a423ea').
(#isProperty -> false).
(#isReference -> false).
(#label -> 'Snippet Definitions').
(#next -> #'4bab6171-1c6c-504b-98ae-553b38d3d886').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '6 September 2013 8:27:31 pm').
(#inputKind -> ViQueryStepDefinition).
(#outputKind -> ViQuerySnippetDefinition).
(#priority -> 4880).
(#view -> ViTreeViewExtended)}))})