steps
step0aef5c3f5e839a4f8a0b9fd4ca3e46f4
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #origin).
(#iconCode -> 'nil').
(#id -> #'0aef5c3f-5e83-9a4f-8a0b-9fd4ca3e46f4').
(#label -> nil).
(#next -> #'0bcec8d5-cada-9048-b7bf-ace560a17f4f').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#labelColor -> '#AAAAAA').
(#priority -> 2070)}))})