steps
step736c249139ee9f4c9abc4d4c87ef1a03
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #origin).
(#iconCode -> 'nil').
(#id -> #'736c2491-39ee-9f4c-9abc-4d4c87ef1a03').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'d9634b11-bde6-1a40-a0b4-7be880afc37a').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 4940)}))})