steps
step7950e293a009a34d80e65dbbb6ca46d5
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'619f16f4-f25c-ff43-aaf8-c3015d50f261').
(#iconCode -> 'UiSilkIcons cogIcon').
(#id -> #'7950e293-a009-a34d-80e6-5dbbb6ca46d5').
(#isProperty -> false).
(#label -> 'Execute Method (!)').
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '3 May 2019 4:19:23.790459 pm').
(#inputKind -> CompiledMethod).
(#priority -> 250)
}))
})