steps
step6f20da891a7ef64d96a68b4b22691ee4
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupStep).
(#definition -> #methodReferenceToPackageName).
(#iconCode -> 'nil').
(#id -> #'6f20da89-1a7e-f64d-96a6-8b4b22691ee4').
(#label -> nil).
(#next -> #'201c9e15-bd34-ba46-bf10-7b546e1fa6f8').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1520)}))})