steps
stepd1ab46b3df50534cb593d1e6683fe045
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #iconAndLabel).
(#iconCode -> 'nil').
(#id -> #'d1ab46b3-df50-534c-b593-d1e6683fe045').
(#label -> nil).
(#next -> #'be086e52-473b-3d4b-a833-6d796588f9e6').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Implementor').
(#priority -> 1540)}))})