steps
stepc0cac2e3ab77904fa0ed936a31a423ea
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'5ca20494-4fec-d94a-8cc4-ad0ae673270b').
(#iconCode -> 'nil').
(#id -> #'c0cac2e3-ab77-904f-a0ed-936a31a423ea').
(#label -> 'Snippet Definitions').
(#next -> #'4bab6171-1c6c-504b-98ae-553b38d3d886').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'ed778e6a-6ace-e540-84c3-af7329c1f656').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '6 September 2013 8:27:31 pm').
(#priority -> 4880)}))})