steps
stepgroups
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'1c6c47fd-f9bb-084a-9266-60bc0c3608bf').
(#iconCode -> 'nil').
(#id -> #groups).
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'1969ce03-4b3d-cd44-a47f-8a50c1ec3a4b').
(#properties -> (Dictionary newFrom: {
(#copyOf -> #groups).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '12 May 2015 4:36:46 pm').
(#inputKind -> {Object. Object}).
(#view -> ViTreeViewExtended)}))})