steps
stepd7717fb24d049a42a74d4a8e8f3a891c
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'3835be18-aea4-124e-a7f0-7455e1534b44').
(#iconCode -> 'nil').
(#id -> #'d7717fb2-4d04-9a42-a74d-4a8e8f3a891c').
(#label -> nil).
(#next -> #'e45648f8-4fef-f343-8972-cbb555789355').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '14 February 2014 11:06:30 am').
(#headerText -> #D).
(#priority -> 5280)}))})