steps
step7b87d63ff0ab524eb406502817498dbb
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'aa928fd1-48f4-084c-878b-5dd4ad186dbf').
(#iconCode -> 'nil').
(#id -> #'7b87d63f-f0ab-524e-b406-502817498dbb').
(#label -> nil).
(#next -> #'ae6288a6-a692-bf42-84df-1174cbab45a4').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '23 May 2014 11:10:45 am').
(#priority -> 6340)}))})