steps
step4ec4f26a3a169a4fbe55656f7ebc3abe
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'d1c87767-867e-af49-9a09-1e5f2934e9dd').
(#iconCode -> 'nil').
(#id -> #'4ec4f26a-3a16-9a4f-be55-656f7ebc3abe').
(#isProperty -> false).
(#label -> nil).
(#next -> #'cffbfe83-0584-d241-8e7b-068442bd8619').
(#properties -> (Dictionary newFrom: {
(#after -> #(#groupsMinimal)).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:13.434834 pm')}))})