steps
step4e83040adb7bc9418c4ff03b8556fca4
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'fa9ad535-af43-d64d-af54-6c375a48611e').
(#iconCode -> 'nil').
(#id -> #'4e83040a-db7b-c941-8c4f-f03b8556fca4').
(#isProperty -> false).
(#isReference -> false).
(#label -> 'Methods by Protocol').
(#next -> #'601f4f47-9545-0e4e-abef-e7b5dc4c0c3e').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 1:01:49 pm').
(#inputKind -> ClassDescription).
(#outputKind -> Association).
(#priority -> 5660).
(#view -> ViTreeViewExtended)}))})