steps
step254519a4d387e14598c49d0959d54bb0
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'f174d2db-b75f-9e47-9a1c-b1f72c5fc770').
(#iconCode -> 'nil').
(#id -> #'254519a4-d387-e145-98c4-9d0959d54bb0').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'fb419e86-ae99-8746-8320-8ef4c8c7e6d2').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'254519a4-d387-e145-98c4-9d0959d54bb0').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '6 September 2013 9:08:35 pm').
(#priority -> 1030)}))})