steps
steprecoverUnsavedScripts
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'110ae7b7-c003-5f4f-8bce-b8ec5d33741f').
(#iconCode -> 'nil').
(#id -> #recoverUnsavedScripts).
(#isProperty -> true).
(#isReference -> false).
(#label -> 'Recover Unsaved Scripts').
(#next -> #'1b7534bd-882c-2d45-8ff7-04510695ae1c').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 October 2015 2:07 pm').
(#isGlobal -> true).
(#optimalExtent -> (635@373)).
(#view -> ViMultiPaneTiled)}))})