steps
step78a4e23d75dc65458dfa2e3ec49b7eb8
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'be02a17d-cc98-1640-ae53-b8838236dad5').
(#iconCode -> 'nil').
(#id -> #'78a4e23d-75dc-6545-8dfa-2e3ec49b7eb8').
(#label -> 'Class metrics (NOM, NOA)').
(#next -> #'524b534f-b2f5-2447-a4d0-9a1769f2d123').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '14 August 2014 1:18:07 pm').
(#priority -> 6740).
(#view -> ViTreeViewExtended)}))})