steps
stepad40279566daaa47aa37eb2e5d035363
	<step>

	^ (Dictionary newFrom: {
(#'_def' -> (Dictionary newFrom: {
(#block -> [:in :out | [TestCase] value in: [:result |
	out addAll: result asList]]).
(#className -> #ViScriptDefinition).
(#id -> #'9ee998ec-877c-bb4f-9a00-1f268163aaa5').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 February 2014 12:43:11 pm')
})).
(#sourceCode -> '[:in :out | [TestCase] value in: [:result |
	out addAll: result asList]]')
})).
(#className -> #ViScriptStep).
(#definition -> #'9ee998ec-877c-bb4f-9a00-1f268163aaa5').
(#iconCode -> 'nil').
(#id -> #'ad402795-66da-aa47-aa37-eb2e5d035363').
(#isProperty -> false).
(#label -> 'All test classes').
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#after -> #(#classHierarchy)).
(#before -> #()).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 February 2014 12:43:11 pm').
(#expandAll -> true).
(#isGlobal -> true).
(#outputKind -> Behavior).
(#priority -> 5230).
(#view -> ViTreeViewExtended)
}))
})