steps
step29a5b770b982f548b9d29842b501cff9
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'8e9ff190-a41f-104d-a4cc-18f5118e7612').
(#iconCode -> 'nil').
(#id -> #'29a5b770-b982-f548-b9d2-9842b501cff9').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'d1d946a9-b78e-7243-8d30-c08accd864b6').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 4:21:57 pm').
(#priority -> 3200)}))})