steps
step9b96cd37e54b5649b04dd585c24b8303
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'f49420f9-0ade-2341-8634-7849db05d952').
(#iconCode -> 'nil').
(#id -> #'9b96cd37-e54b-5649-b04d-d585c24b8303').
(#isProperty -> false).
(#isReference -> true).
(#label -> nil).
(#next -> #'594a2a29-f4d7-9447-bc7d-0f50be719127').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '14 December 2015 11:52:58 am')}))})