steps
stepa718839b056226498d2efcb3995dd716
	<step>

	^ ((Dictionary new) add: (#definition->#'e107394e-979a-814b-b60f-d35cdf88fb2f'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'14 December 2015 11:30:58 am'); yourself)); add: (#isProperty->false); add: (#next->#'01ee0bd6-0573-124c-b84a-3d699a2e3263'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'a718839b-0562-2649-8d2e-fcb3995dd716'); add: (#isReference->false); yourself)