steps
stepf338abfbc08a5946a43d7540b0f26188
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'d2f75968-6c7c-2246-b2f6-eeadd32907da').
(#iconCode -> 'nil').
(#id -> #'f338abfb-c08a-5946-a43d-7540b0f26188').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'71efc7d9-c3cb-7246-9652-6b74bc022b8e').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '9 April 2019 6:34:37.320982 pm')}))})