steps
step1f64fb2e2ed1dc4eb553cf7d4f3742e4
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'f24deb2f-957d-ed4a-b730-d0ff697dc604').
(#iconCode -> 'nil').
(#id -> #'1f64fb2e-2ed1-dc4e-b553-cf7d4f3742e4').
(#isProperty -> false).
(#isReference -> false).
(#label -> 'View Definitions').
(#next -> #'2ea23721-a871-ea46-8798-6a4a5be4cb8e').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '7 September 2013 10:44:15 am').
(#inputKind -> ViQueryStepDefinition).
(#outputKind -> AnObsoleteViQueryViewDefinition).
(#priority -> 1050).
(#view -> ViTreeViewExtended)}))})