steps
stepc2ce4b2e2257424baf73a84bb479e75c
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupSortStep).
(#definition -> #'563021ef-44a7-e24e-beb7-6201088a6f24').
(#iconCode -> 'nil').
(#id -> #'c2ce4b2e-2257-424b-af73-a84bb479e75c').
(#label -> nil).
(#next -> #'9fe8fed8-f944-ec41-b97b-3eff6b3cf74f').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 10:20:31 am').
(#priority -> 5030)}))})