steps
step9cef732f20e3884c8e5f55e415a20f91
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupSortStep).
(#definition -> #compareObjectsAsStrings).
(#iconCode -> 'nil').
(#id -> #'9cef732f-20e3-884c-8e5f-55e415a20f91').
(#label -> nil).
(#next -> #'46075c87-5609-2c41-86d5-a35e4089e966').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1220)}))})