steps
step754c7a1e5b33a8428a8ac5f6eef88890
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryReferenceStep).
(#definition -> nil).
(#iconCode -> 'nil').
(#id -> #'754c7a1e-5b33-a842-8a8a-c5f6eef88890').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '4 September 2013 12:59:17 pm').
(#priority -> 2580)})).
(#reference -> #'8ed52473-9493-2142-94be-054478bc571b')})