steps
step55d465d1f7d0c04fa61b099f2ae6b6b9
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'397cc4e0-1a32-3d4d-af37-dcef863d4d5d').
(#iconCode -> 'nil').
(#id -> #'55d465d1-f7d0-c04f-a61b-099f2ae6b6b9').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'bb553ae0-c81d-4641-964f-7f27055d9c15').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'4483ab73-df68-ab43-b410-6de476dc855a').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Name').
(#priority -> 4540).
(#resizeMode -> #rigid)}))})