steps
step343a2282782f4d4b8e98ab5ca5e0fd36
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'38672103-9541-e64e-b28b-dd23aecc1c72').
(#iconCode -> 'nil').
(#id -> #'343a2282-782f-4d4b-8e98-ab5ca5e0fd36').
(#isProperty -> true).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Repository').
(#priority -> 2620)
}))
})