steps
stepde02f05659273144a71d76088dd47944
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'8287f41b-826f-0247-b83e-45b6688f9d76').
(#iconCode -> 'UiFugueIcons documentListIcon').
(#id -> #'de02f056-5927-3144-a71d-76088dd47944').
(#label -> 'Files').
(#next -> #'268f1e29-abfa-184e-9be9-0f251cf2d31b').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'d70d563f-bdd7-1842-9175-cf758450e227').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 590).
(#view -> ViTreeViewExtended)}))})