steps
stepe3bbc4b5b67ee74f98130e88bc195009
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'a185dd1d-edf5-484c-bf54-0b23eac4f70d').
(#iconCode -> 'nil').
(#id -> #'e3bbc4b5-b67e-e74f-9813-0e88bc195009').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '29 March 2019 2:44:51.113235 pm').
(#inputKind -> #(nil nil))}))})