steps
stepd8b2f45006353046bb39a2cec077ae4c
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'89b09f36-4977-6046-8942-1b42f21b88f0').
(#iconCode -> 'nil').
(#id -> #'d8b2f450-0635-3046-bb39-a2cec077ae4c').
(#label -> nil).
(#next -> #'25668ab3-5383-2a4b-8bc2-5d22ac2cc3fe').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 September 2013 7:19:15 pm').
(#priority -> 3420)}))})