steps
steporderedSteps
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'412dc831-637b-4b41-9ed1-e8eb3db97062').
(#iconCode -> 'UiFugueIcons scriptMediumIcon').
(#id -> #orderedSteps).
(#label -> 'Ordered Queries').
(#next -> #'7fd41212-698d-ee43-8d8f-0dc8fb2b9a9e').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '3 September 2013 3:26:55 pm').
(#priority -> 390)}))})