steps
step0bcec8d5cada9048b7bface560a17f4f
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #subclasses).
(#iconCode -> 'nil').
(#id -> #'0bcec8d5-cada-9048-b7bf-ace560a17f4f').
(#label -> nil).
(#next -> #'76221c32-5f94-c545-a4a4-cf57138ffe39').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 2080)}))})