steps
step473ec1cf01e6db49a73158d0370843f8
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'767367b4-0c7d-cf41-9d85-fc2b543d0747').
(#iconCode -> 'nil').
(#id -> #'473ec1cf-01e6-db49-a731-58d0370843f8').
(#isProperty -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#after -> #(#'297515f3-11ce-2e45-94a2-b23a6cad1586')).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '9 December 2015 11:26:37 am')}))})