steps
step53515aaf6982b048afb6e82af653f073
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'92d66888-3e33-e449-82ee-fc6d9fdf72e6').
(#iconCode -> 'nil').
(#id -> #'53515aaf-6982-b048-afb6-e82af653f073').
(#label -> nil).
(#next -> #'f4f3c4ff-456b-3a46-a1ae-22320975be38').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Object').
(#labelColor -> '#000000').
(#priority -> 2450).
(#resizeMode -> #rigid)}))})