steps
step087bc712e2101d43b27c50a4d240b0ea
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'b39587ef-2aca-9546-bb85-3051e3bef606').
(#iconCode -> 'nil').
(#id -> #'087bc712-e210-1d43-b27c-50a4d240b0ea').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'a8f95d96-7f39-6744-aca5-95cde8b9e75e').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #defaultProperties).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 4790)}))})