steps
stepb44be5e8ba080744812e8f9104bc951f
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'d2deefcc-b8da-9149-8ae5-14aca716349d').
(#iconCode -> 'nil').
(#id -> #'b44be5e8-ba08-0744-812e-8f9104bc951f').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'c0cac2e3-ab77-904f-a0ed-936a31a423ea').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #updateDefinitions).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '6 September 2013 8:27:11 pm').
(#inputKind -> ViQueryOrganizer).
(#outputKind -> ViQueryStepDefinition).
(#priority -> 4870).
(#view -> ViTreeViewExtended)}))})