steps
stepe63568e85926f6409527117c4e70e841
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'033c8dcb-925a-b04e-bac3-9802272f6cd1').
(#iconCode -> 'nil').
(#id -> #'e63568e8-5926-f640-9527-117c4e70e841').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'7badd432-90e1-ec42-96d7-6085b40a0871').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'e63568e8-5926-f640-9527-117c4e70e841').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '3 September 2013 1:57:12 pm').
(#priority -> 960)}))})