steps
stepac3b51604403e846987bb3be159ed5dc
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'bee7c683-9667-a94a-b75b-5d1f78775626').
(#iconCode -> 'nil').
(#id -> #'ac3b5160-4403-e846-987b-b3be159ed5dc').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '27 May 2014 2:54:18 pm').
(#inputKind -> PackageInfo).
(#outputKind -> Boolean).
(#priority -> 6360)}))})