steps
steped98259d40bab843bb324e77d29904ec
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'dac0f8b1-2ad8-6c42-9926-07278d236bb0').
(#iconCode -> 'nil').
(#id -> #'ed98259d-40ba-b843-bb32-4e77d29904ec').
(#isProperty -> false).
(#label -> nil).
(#next -> #'fd62bf2f-377c-e64a-b62a-4f2399a054e1').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#outputKind -> Boolean).
(#priority -> 1200)
}))
})