steps
step708f87dc3282814fa2afe89060b27f1b
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'addce144-9b97-fb46-b280-b5500d0f6a06').
(#iconCode -> 'nil').
(#id -> #'708f87dc-3282-814f-a2af-e89060b27f1b').
(#isProperty -> false).
(#label -> nil).
(#next -> #'4ce2b7cd-1c43-8241-a5bd-ca0484e682df').
(#properties -> (Dictionary newFrom: {
(#after -> #(#groupsMinimal)).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:11.295834 pm')}))})