steps
step2293cc01c88a35429a4dcaa8ba9c12c8
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'7edc593b-3bdd-fe4c-8177-cfab9dec78f2').
(#iconCode -> 'nil').
(#id -> #'2293cc01-c88a-3542-9a4d-caa8ba9c12c8').
(#isProperty -> false).
(#isReference -> false).
(#label -> 'Script objects in workspace').
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '21 January 2015 11:47:33 am').
(#view -> ViWorkspaceView)}))})