steps
stepcb96415c4b856247877c589b975e69c8
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'63fac752-5bc2-a14c-93db-1ae5f37af050').
(#iconCode -> 'nil').
(#id -> #'cb96415c-4b85-6247-877c-589b975e69c8').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '14 October 2013 5:10:11 pm').
(#priority -> 4160)}))})