steps
step1af811b85914fa4aa3086a17174c3d9c
	<step>

	^ ((Dictionary new) add: (#definition->#'b6ce0874-004f-4245-8c30-280b2bec1485'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'7 December 2015 2:00:40 pm'); yourself)); add: (#isProperty->true); add: (#next->#'c68e2eaf-ff3f-eb4b-9f51-74527cb495ac'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'1af811b8-5914-fa4a-a308-6a17174c3d9c'); add: (#isReference->false); yourself)