steps
step4b70743966b1c64b805a80c63759305e
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'3d0c7269-aed8-9e4a-9b3d-fa7ec52d2dc1').
(#iconCode -> 'nil').
(#id -> #'4b707439-66b1-c64b-805a-80c63759305e').
(#label -> nil).
(#next -> #'31f74b61-d090-a443-99cc-182ef8e9b039').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Property').
(#labelColor -> '#999999').
(#priority -> 2880)}))})