steps
step6b83183f11b1294bbfa711e681f78ad8
	<step>

	^ ((Dictionary new) add: (#definition->#'dbf9be41-0b05-0a49-82ad-d2ca591ea8d0'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'15 June 2015 10:20:57 am'); add: (#copyOf->#'4e96ab7f-cc8d-1040-aad0-ed4e9026b875'); yourself)); add: (#isProperty->false); add: (#next->#'c8d02930-5618-4644-9d24-456f53f464bc'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'6b83183f-11b1-294b-bfa7-11e681f78ad8'); add: (#isReference->false); yourself)