steps
stepe62a3f594f571c4ab8f12ea49415d52e
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'d64bb967-563b-634e-b3ca-edbff3f1cb72').
(#iconCode -> 'nil').
(#id -> #'e62a3f59-4f57-1c4a-b8f1-2ea49415d52e').
(#isProperty -> false).
(#label -> nil).
(#next -> #'72bf6830-31d8-1b42-9ddc-991381a326f0').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 September 2013 7:12:18 pm').
(#inputKind -> ByteSymbol).
(#outputKind -> ByteSymbol).
(#priority -> 3400)}))})