steps
step0a45fa5f6f7ba74bb15f868dcf6a9799
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'042fe827-9b71-854d-8413-7f5befe2d4a5').
(#iconCode -> 'nil').
(#id -> #'0a45fa5f-6f7b-a74b-b15f-868dcf6a9799').
(#isProperty -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#after -> #(#outline)).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '9 December 2015 10:48:47 am')
}))
})