steps
step012db9f44e1ecc49aa55265d82592ec7
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'b45c17af-a58f-0e4c-9df3-a0fe684a4ae0').
(#iconCode -> 'nil').
(#id -> #'012db9f4-4e1e-cc49-aa55-265d82592ec7').
(#isProperty -> true).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 October 2015 10:58:50 am')}))})