steps
step0bf4254ac61595498fa0434b920f8c2a
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'292e64dc-ce4c-7a42-964d-85da2486116c').
(#iconCode -> 'nil').
(#id -> #'0bf4254a-c615-9549-8fa0-434b920f8c2a').
(#isProperty -> false).
(#label -> 'System categories').
(#next -> #'a4ac81fc-d21c-7240-abf8-68d76d2dc175').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 February 2014 3:56:01 pm').
(#isGlobal -> true).
(#outputKind -> SystemOrganizer).
(#priority -> 5620).
(#view -> ViTreeViewExtended)
}))
})