steps
stepfca5ba471c0b0b4d8c617eca1715c0c5
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQuerySortStep).
(#definition -> #'b08835ac-24fe-3b43-87cb-ceb4b81fc6fb').
(#iconCode -> 'nil').
(#id -> #'fca5ba47-1c0b-0b4d-8c61-7eca1715c0c5').
(#label -> nil).
(#next -> #'8b5ec783-b069-bd44-a805-058c53c7f164').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1980)}))})