steps
stepa0dd65c0687c174a9c11369b8badfa15
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'6cc037e3-6bf3-f24e-bc65-d7b765664a5d').
(#iconCode -> 'nil').
(#id -> #'a0dd65c0-687c-174a-9c11-369b8badfa15').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 February 2014 11:57:29 am').
(#priority -> 5580)}))})