steps
step2a56df6169c833499b25d5afffcb60b1
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupSortStep).
(#definition -> #compareObjectsAsStrings).
(#iconCode -> 'nil').
(#id -> #'2a56df61-69c8-3349-9b25-d5afffcb60b1').
(#label -> nil).
(#next -> #'4ce2b7cd-1c43-8241-a5bd-ca0484e682df').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 2850)}))})