steps
step651607ab44293e44b61f86c177f0d112
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'60fafc92-17ae-4b40-af17-c13b35d42e25').
(#iconCode -> 'nil').
(#id -> #'651607ab-4429-3e44-b61f-86c177f0d112').
(#label -> nil).
(#next -> #'0caac112-a8fd-c443-bf49-f884e1be7743').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '23 July 2014 1:24:01 pm').
(#priority -> 6630)}))})