steps
stepac005f0e6178f74e9fdc206e86af0a7d
	<step>

	^ (Dictionary newFrom: {
(#'_def' -> (Dictionary newFrom: {
(#block -> [:in :out | out addAll: in]).
(#className -> #ViScriptDefinition).
(#id -> #'15c109e2-9b5a-3148-9fa2-081db09660f8').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:11.428834 pm')
})).
(#sourceCode -> '[:in :out | out addAll: in]')
})).
(#className -> #ViScriptStep).
(#definition -> #'15c109e2-9b5a-3148-9fa2-081db09660f8').
(#iconCode -> 'nil').
(#id -> #'ac005f0e-6178-f74e-9fdc-206e86af0a7d').
(#isProperty -> false).
(#label -> nil).
(#next -> #'e84072d2-c593-f549-a93c-d5dbeb2e3b94').
(#properties -> (Dictionary newFrom: {
(#after -> #(#groupsMinimal)).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:11.428834 pm')
}))
})