steps
stepe44e7438eba573448590a778889ab428
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'15e1f99a-0b69-104d-b81a-f6d4a89600b1').
(#iconCode -> 'nil').
(#id -> #'e44e7438-eba5-7344-8590-a778889ab428').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 10:22:01 am').
(#labelColor -> '#000000').
(#priority -> 5050)}))})