steps
step44f56402c21ba04c8d76cecb592b4509
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'d3ca57b2-b984-5b48-8630-ecbace3cf814').
(#iconCode -> 'nil').
(#id -> #'44f56402-c21b-a04c-8d76-cecb592b4509').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '6 March 2018 10:33:33 am')}))})