steps
step52a42afce8cf7d4593f8c5f88bd3f49b
	<step>

	^ (Dictionary newFrom: {
(#'_def' -> (Dictionary newFrom: {
(#block -> [:in :out | out addAll: ([:objects | objects select: [:obj | true]] value: in)]).
(#className -> #ViScriptDefinition).
(#id -> #'ecbd3c93-c96c-3249-9f9d-3fbb1097193d').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')
})).
(#sourceCode -> '[:in :out | out addAll: ([:objects | objects select: [:obj | true]] value: in)]')
})).
(#className -> #ViScriptStep).
(#definition -> #'ecbd3c93-c96c-3249-9f9d-3fbb1097193d').
(#iconCode -> 'nil').
(#id -> #'52a42afc-e8cf-7d45-93f8-c5f88bd3f49b').
(#isProperty -> false).
(#label -> nil).
(#next -> #'e614ad19-8010-a444-9759-aaa2423cb69e').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 September 2013 3:11:48 pm').
(#priority -> 3990)
}))
})