steps
step0369a0d46ce39f49b251c92b852ef534
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'716229ec-e92e-5347-8d5c-6b521c3d19d5').
(#iconCode -> 'nil').
(#id -> #'0369a0d4-6ce3-9f49-b251-c92b852ef534').
(#label -> nil).
(#next -> #'d7717fb2-4d04-9a42-a74d-4a8e8f3a891c').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '14 February 2014 9:54:14 am').
(#headerText -> #S).
(#priority -> 5270)}))})