steps
step18533aea2a404a4fb098e14e7fdcb291
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'a2abf774-50cf-1e40-97a2-fff5c93885ca').
(#iconCode -> 'nil').
(#id -> #'18533aea-2a40-4a4f-b098-e14e7fdcb291').
(#isProperty -> false).
(#isReference -> false).
(#label -> 'Change Sets').
(#next -> #'fdc9d784-2f4f-8a42-8553-dfc7982b9585').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '5 June 2014 4:48:11 pm').
(#isGlobal -> true).
(#priority -> 6180).
(#view -> ViTreeViewExtended)}))})