steps
step4b91c6bda48d134e8d10515a06acf0cc
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'03349ae0-0dab-b944-8a12-e55a675ab325').
(#iconCode -> 'nil').
(#id -> #'4b91c6bd-a48d-134e-8d10-515a06acf0cc').
(#label -> nil).
(#next -> #'1006fd36-1341-dc4a-8678-ca7e4315063f').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 1:09:51 pm').
(#priority -> 840).
(#view -> ViTreeViewExtended)}))})