steps
stepcfe6ad6fad06774fb19c5dc3bea7243e
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'a38a5806-b66e-564d-b9b3-38ff9f89c2af').
(#iconCode -> 'nil').
(#id -> #'cfe6ad6f-ad06-774f-b19c-5dc3bea7243e').
(#label -> nil).
(#next -> #'b72e75d1-03bb-7541-a46e-39fd55b28333').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 September 2013 6:08:11 pm').
(#labelColor -> #AAAAAA).
(#priority -> 3280)}))})