steps
step41ca5cdb0dc1394b8048c5f08293cdd7
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'39a8096b-1174-d848-af32-86daa4776f7c').
(#iconCode -> 'nil').
(#id -> #'41ca5cdb-0dc1-394b-8048-c5f08293cdd7').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 4:21:57 pm').
(#headerText -> 'Code').
(#labelColor -> '#AAAAAA').
(#priority -> 3250)}))})