steps
step0abf03ed09af8040a20becb26bba972c
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'dee40869-5cbf-5a4b-9ac4-763ea4a562a6').
(#iconCode -> 'nil').
(#id -> #'0abf03ed-09af-8040-a20b-ecb26bba972c').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'71efc7d9-c3cb-7246-9652-6b74bc022b8e').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '9 April 2019 6:25:50.977982 pm')}))})