steps
step578f3d1fbdb5b04b85fffe0c848c6af5
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'f88512ad-81dd-ac4c-8e82-ff004696fed6').
(#iconCode -> 'nil').
(#id -> #'578f3d1f-bdb5-b04b-85ff-fe0c848c6af5').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 September 2013 3:50:52 pm').
(#headerText -> 'Type').
(#labelColor -> '000000').
(#priority -> 4040)}))})