steps
stepe66f7ebe27a3584f836cee4cf8041d8b
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'2c677287-606b-6e44-89fb-01fb56357b98').
(#iconCode -> 'nil').
(#id -> #'e66f7ebe-27a3-584f-836c-ee4cf8041d8b').
(#label -> nil).
(#next -> #'22b325c1-285b-6242-8b45-bf948f7079a2').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Object').
(#priority -> 2010)}))})