steps
step6b45f38f77e7ee4aac7196c1987498fb
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'034fe71c-762e-3547-8e4b-d55060ebeba3').
(#iconCode -> 'nil').
(#id -> #'6b45f38f-77e7-ee4a-ac71-96c1987498fb').
(#label -> 'Empty Objects').
(#next -> #'894088c2-9d24-5b40-9246-2e1a298fe761').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 May 2014 2:58:16 pm').
(#priority -> 6130)}))})