steps
step0fdcdea85071914bab0c5d6335ce985f
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'fea3ce8f-7751-1047-8469-20e2e7346e54').
(#iconCode -> 'nil').
(#id -> #'0fdcdea8-5071-914b-ab0c-5d6335ce985f').
(#label -> nil).
(#next -> #'8ca5adad-9868-4e4c-a40e-2b9deba00f31').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 September 2013 3:14:17 pm').
(#priority -> 3670).
(#view -> ViTreeViewExtended)}))})