steps
step2c058a47d6e2a34fb699cb3781ed55cb
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'be7eabb7-04da-5848-b24a-35bba9fe2f6e').
(#iconCode -> 'nil').
(#id -> #'2c058a47-d6e2-a34f-b699-cb3781ed55cb').
(#label -> 'Outline').
(#next -> #'c7e12f64-1638-ba43-92a5-5110b39063f2').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #defaultProperties).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 3760).
(#view -> ViTreeViewExtended)}))})