steps
step8b5ec783b069bd44a805058c53c7f164
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'ca2791db-1dc9-2a4d-97e7-dd7c68d21eb3').
(#iconCode -> 'nil').
(#id -> #'8b5ec783-b069-bd44-a805-058c53c7f164').
(#isProperty -> false).
(#label -> nil).
(#next -> #'40d1ddb0-85db-2f4d-b36a-674fd76a74b3').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1990)
}))
})