steps
stepc2d0a6c291d42643a28f24b6ddd117c5
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'06e5144b-fda8-0840-93b3-272fe3238aa2').
(#iconCode -> 'nil').
(#id -> #'c2d0a6c2-91d4-2643-a28f-24b6ddd117c5').
(#label -> nil).
(#next -> #'ccdeb4ee-852e-1849-8082-2d3e37a2cf44').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Current').
(#labelColor -> '#AAAAAA').
(#priority -> 2920)}))})