steps
stepa0dd65c0687c174a9c11369b8badfa15
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'09894e45-157f-0148-b77c-181b1a03e0c4').
(#iconCode -> 'nil').
(#id -> #'a0dd65c0-687c-174a-9c11-369b8badfa15').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 February 2014 11:57:29 am').
(#inputKind -> Behavior).
(#priority -> 5580)}))})