steps
stepd45b0a7524882c43939bec29c77353af
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupSortStep).
(#definition -> #compareObjectsAsStrings).
(#iconCode -> 'nil').
(#id -> #'d45b0a75-2488-2c43-939b-ec29c77353af').
(#label -> nil).
(#next -> #'e689b659-27f3-0f4a-9412-ab39abc2b63e').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1090)}))})