steps
stepd86f12e2c38d4e4e807e4615652c2137
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #subclasses).
(#iconCode -> 'nil').
(#id -> #'d86f12e2-c38d-4e4e-807e-4615652c2137').
(#label -> nil).
(#next -> #'52a42afc-e8cf-7d45-93f8-c5f88bd3f49b').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 September 2013 3:10:18 pm').
(#priority -> 3980)}))})