steps
step7665bebe0cf425439977ca902db88134
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupStep).
(#definition -> #'353e01ce-518b-5d49-b095-04ef0d632d71').
(#iconCode -> 'nil').
(#id -> #'7665bebe-0cf4-2543-9977-ca902db88134').
(#label -> nil).
(#next -> #'f2876136-7eb8-e94b-864d-61f883d28db9').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '23 September 2013 5:12:29 pm').
(#priority -> 4090)}))})