steps
step0c4bac1c3acf1544bee1bf0f683849c7
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'c89a35be-d81a-e942-98a6-04cd534ba537').
(#iconCode -> 'UiFugueIcons plusSmallIcon').
(#id -> #'0c4bac1c-3acf-1544-bee1-bf0f683849c7').
(#label -> 'Extensions').
(#next -> #'ed98259d-40ba-b843-bb32-4e77d29904ec').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 80)}))})