steps
stepe689b65927f30f4a9412ab39abc2b63e
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'c638cccb-0c1e-2f45-9c0c-ff22d69ec199').
(#iconCode -> 'nil').
(#id -> #'e689b659-27f3-0f4a-9412-ab39abc2b63e').
(#label -> nil).
(#next -> #'0de86151-e883-cf4c-9668-960b4466822e').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Name').
(#priority -> 1100)}))})