steps
step62ec2d2dbc826d42a3177bfe67ea01bb
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'2abd92ca-7b65-5642-a12a-f91de89561d0').
(#iconCode -> 'nil').
(#id -> #'62ec2d2d-bc82-6d42-a317-7bfe67ea01bb').
(#label -> 'Load Picture').
(#next -> #'ee936399-1409-634c-81ff-0389658bb3ce').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #defaultProperties).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 780)}))})