steps
step0b1978b87b59484281f59f94cce1ec89
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'df4c72bc-599d-6b4e-9488-bb88e0a3e05f').
(#iconCode -> 'nil').
(#id -> #'0b1978b8-7b59-4842-81f5-9f94cce1ec89').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '17 January 2014 3:23:10 pm').
(#priority -> 4840)}))})