steps
step5e941cab2cc706469ed0d8493d5d3d0e
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'c8e4d891-577b-3745-9417-d647f783c713').
(#iconCode -> 'nil').
(#id -> #'5e941cab-2cc7-0646-9ed0-d8493d5d3d0e').
(#label -> nil).
(#next -> #'2b264d15-bb33-124e-8b3f-227ef7073118').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'d9634b11-bde6-1a40-a0b4-7be880afc37a').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#labelColor -> #'000000').
(#priority -> 4470)}))})