steps
step8ca5adad98684e4ca40e2b9deba00f31
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQuerySortStep).
(#definition -> #'563021ef-44a7-e24e-beb7-6201088a6f24').
(#iconCode -> 'nil').
(#id -> #'8ca5adad-9868-4e4c-a40e-2b9deba00f31').
(#label -> nil).
(#next -> #'c65a9646-727f-864b-9955-deeac8d8dcf4').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 September 2013 8:08:35 pm').
(#priority -> 3560).
(#view -> ViTreeViewExtended)}))})