steps
stepd89cc75273e40742ac29eb770d5d8fc5
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'c71cc86f-f780-d647-a84b-aa2569c11168').
(#iconCode -> 'nil').
(#id -> #'d89cc752-73e4-0742-ac29-eb770d5d8fc5').
(#isProperty -> false).
(#label -> nil).
(#next -> #'1d58d23a-244c-b84e-8448-52a3acfb1544').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#outputKind -> Boolean).
(#priority -> 1340)
}))
})