steps
step2b5f54a675dfcd49a19e8e22f687fb05
	<step>

	^ ((Dictionary new) add: (#definition->#'9d09ac24-315c-ac4c-af8b-ca5eb7b05f23'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->ClassDescription); add: (#creationAuthor->'mt'); add: (#view->[ViScriptPart useHorizontalLists
		ifTrue: [ViListView]
		ifFalse: [ViTreeViewExtended]]); add: (#creationTimeStamp->'18 October 2015 11:03:50 am'); add: (#priority->110); add: (#orientation->[ViScriptPart useHorizontalLists
		ifTrue: [#horizontal]
		ifFalse: [#default]]); yourself)); add: (#isProperty->false); add: (#next->#'8bea6122-a305-b242-8d58-322fca9d39ce'); add: (#label->'Protocols'); add: (#iconCode->'UiFugueIcons priceTagIcon'); add: (#id->#'2b5f54a6-75df-cd49-a19e-8e22f687fb05'); add: (#isReference->false); yourself)