steps
stepe5f64c36bb633b4eb5961aac061b81a3
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'0de61e46-38d5-0c40-9a76-c49f1d124a42').
(#iconCode -> 'nil').
(#id -> #'e5f64c36-bb63-3b4e-b596-1aac061b81a3').
(#isProperty -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#after -> #(#groups)).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '12 May 2015 5:22:22 pm')}))})