steps
step322373256bef9048a0d35e1f4a3e64ed
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'e70ded17-b47f-0b4d-b8ef-6ce1537f8fa3').
(#iconCode -> 'nil').
(#id -> #'32237325-6bef-9048-a0d3-5e1f4a3e64ed').
(#isProperty -> false).
(#label -> nil).
(#next -> #'aa3ec915-c019-e941-8b9b-f9baa09fd69a').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 February 2014 10:21:58 am').
(#priority -> 5530)
}))
})