steps
step668146bb9b8df241b4eddcc75bd19810
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'da405dca-a891-c342-babd-61ac10dcdf42').
(#iconCode -> 'nil').
(#id -> #'668146bb-9b8d-f241-b4ed-dcc75bd19810').
(#isProperty -> false).
(#label -> nil).
(#next -> #'432a6001-f00e-514e-a68e-4605686f7755').
(#properties -> (Dictionary newFrom: {
(#after -> #(#groupsMinimal)).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:12.904834 pm')}))})