steps
step82908026d4e4d04783ee741e175314a3
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'00bc571a-a6fc-de47-bfc5-b4253307a05a').
(#iconCode -> 'nil').
(#id -> #'82908026-d4e4-d047-83ee-741e175314a3').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Timestamp').
(#labelColor -> '#AAAAAA').
(#priority -> 1820)}))})