steps
step2dc88784e2eff54aa4eacf58d48dad44
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'07ea567a-2267-524e-a29d-64b1bfbbe3e4').
(#iconCode -> 'nil').
(#id -> #'2dc88784-e2ef-f54a-a4ea-cf58d48dad44').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'11525e3e-ab65-9643-be1d-444ca45f2674').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '1 June 2015 1:43:12 pm')}))})