steps
step07d98c15a20c0b459dc3ba44905e9a7a
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'d11fd676-c930-9041-9741-c3b05ed28509').
(#iconCode -> 'nil').
(#id -> #'07d98c15-a20c-0b45-9dc3-ba44905e9a7a').
(#isProperty -> false).
(#isReference -> true).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '29 March 2019 5:00:11.34035 pm').
(#view -> ViTreeViewExtended)}))})