steps
stepbfc2203ca7dbc84f95741514d216b6e2
	<step>

	^ ((Dictionary new) add: (#definition->#'934e4a55-01f2-e344-963c-6e32fe1b86a6'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'20 May 2015 2:36:10 pm'); add: (#copyOf->#'97b22eff-73d8-4746-b877-4dc3d77e1208'); yourself)); add: (#isProperty->false); add: (#next->#'969d8eb9-9007-b041-b58e-a1fd25a2d732'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'bfc2203c-a7db-c84f-9574-1514d216b6e2'); add: (#isReference->true); yourself)