steps
step554c12a43ed5904d8adabb3d129a200a
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'e3aa5ce4-5f9f-624a-ad51-0c4f711df2af').
(#iconCode -> 'nil').
(#id -> #'554c12a4-3ed5-904d-8ada-bb3d129a200a').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'afb03b2b-6810-684f-853c-74918c6c73e3').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '21 February 2014 9:39:56 am').
(#headerText -> 'Spawn').
(#priority -> 5980)}))})