steps
stepe412ba6347696448bdf0693f6bf51a84
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'cf0824b7-d1f2-2742-aff9-793511335e6b').
(#iconCode -> 'nil').
(#id -> #'e412ba63-4769-6448-bdf0-693f6bf51a84').
(#isProperty -> true).
(#label -> 'Documentation').
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 1:01:49 pm').
(#inputKind -> CompiledMethod).
(#priority -> 5790).
(#view -> ViTreeViewExtended)
}))
})