steps
step3d9d6bb7e6bc5444b1a396219e51fe10
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'ac4f2e74-c5ae-a445-b756-d91192f6a288').
(#iconCode -> 'nil').
(#id -> #'3d9d6bb7-e6bc-5444-b1a3-96219e51fe10').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '6 September 2013 8:38:52 pm').
(#inputKind -> ViScriptObject).
(#priority -> 4900)}))})