steps
step8eec0dd86d7cd54f8d45ff176d005f1b
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'f88512ad-81dd-ac4c-8e82-ff004696fed6').
(#iconCode -> 'nil').
(#id -> #'8eec0dd8-6d7c-d54f-8d45-ff176d005f1b').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'6dcf4d7c-0337-da43-85f9-526e23934ee9').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 September 2013 6:51:45 pm').
(#headerText -> 'Type').
(#priority -> 3870)}))})