steps
step9495a7a136da3645afa0bb85011e21d1
	<step>

	^ ((Dictionary new) add: (#definition->#'de8216a7-6374-7b49-9452-fe1b108395fb'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isGlobal->true); add: (#creationAuthor->'mt'); add: (#view->ViMultiPaneTiled); add: (#creationTimeStamp->'19 October 2015 11:47:09 am'); add: (#optimalExtent->(368@347)); yourself)); add: (#isProperty->true); add: (#next->#'e3c616ba-4453-c04b-b997-91416620222a'); add: (#label->'Recover Unsaved Changes'); add: (#iconCode->'nil'); add: (#id->#'9495a7a1-36da-3645-afa0-bb85011e21d1'); add: (#isReference->false); yourself)