steps
step8451e0da6c997f419483316176f07642
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'da8a8f50-3e4c-d44c-9f64-45781be27672').
(#iconCode -> 'nil').
(#id -> #'8451e0da-6c99-7f41-9483-316176f07642').
(#isProperty -> false).
(#label -> nil).
(#next -> #'322d0692-7c3f-a342-aeaa-e25dd5a1675c').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '20 May 2015 2:49:42 pm')}))})