steps
step0e3c9bf8357eb2458da233ae912ace9a
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'79318eae-5b50-684e-916c-334be89a9f45').
(#iconCode -> 'nil').
(#id -> #'0e3c9bf8-357e-b245-8da2-33ae912ace9a').
(#isProperty -> true).
(#label -> nil).
(#next -> #'5bac288b-036f-3b40-9351-de76b1f7cd03').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Origin').
(#labelColor -> '#AAAAAA').
(#priority -> 3120)}))})