steps
step778ab7d2583503478b0acb8214791085
	<step>

	^ (Dictionary newFrom: {
(#'_def' -> (Dictionary newFrom: {
(#block -> [:in :out | out addAll: in]).
(#className -> #ViScriptDefinition).
(#id -> #'307e8fdf-0a8e-9d47-b181-67c0d5f8a62b').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:11.404834 pm')
})).
(#sourceCode -> '[:in :out | out addAll: in]')
})).
(#className -> #ViScriptStep).
(#definition -> #'307e8fdf-0a8e-9d47-b181-67c0d5f8a62b').
(#iconCode -> 'nil').
(#id -> #'778ab7d2-5835-0347-8b0a-cb8214791085').
(#isProperty -> false).
(#label -> nil).
(#next -> #'2902b302-607d-7340-b97a-4a497764e9d3').
(#properties -> (Dictionary newFrom: {
(#after -> #(#groupsMinimal)).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:11.404834 pm')
}))
})