steps
stepunsavedScripts
	<step>

	^ ((Dictionary new) add: (#definition->#'5f15c46f-bfdc-c241-a11b-5cbbf6b9ef79'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#notifier->ViSystemChangeNotifier); add: (#creationTimeStamp->'19 October 2015 2:07 pm'); add: (#copyOf->#unsavedChanges); yourself)); add: (#isProperty->false); add: (#next->#'a709a161-d05f-ed44-97e2-165f6f140ada'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#unsavedScripts); add: (#isReference->false); yourself)