steps
step519d344ef0312a438e4234a9f07b61f9
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #iconAndLabel).
(#iconCode -> 'nil').
(#id -> #'519d344e-f031-2a43-8e42-34a9f07b61f9').
(#label -> nil).
(#next -> #'047d9a97-10d0-6c45-8228-c223ea969775').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Versions').
(#priority -> 1600)}))})