steps
step5550da938f7a934c93bf6f5174ab3ab2
	<step>

	^ (Dictionary newFrom: {
(#'_def' -> (Dictionary newFrom: {
(#block -> [:in :out | ([:all | all collect: [:o | (
	[:version | { #text -> version info message. #color -> (Color banana alpha: 0.3) }]
		value: o), { #object -> o }]]
			value: in) do: [:result | out add: result]]).
(#className -> #ViScriptDefinition).
(#id -> #'e2f1a90d-5bc6-3648-8c53-548207872e43').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '23 September 2019 10:41:47.204086 am')
})).
(#sourceCode -> '[:in :out | ([:all | all collect: [:o | (
	[:version | { #text -> version info message. #color -> (Color banana alpha: 0.3) }]
		value: o), { #object -> o }]]
			value: in) do: [:result | out add: result]]')
})).
(#className -> #ViScriptStep).
(#definition -> #'e2f1a90d-5bc6-3648-8c53-548207872e43').
(#iconCode -> 'nil').
(#id -> #'5550da93-8f7a-934c-93bf-6f5174ab3ab2').
(#isProperty -> true).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '23 September 2019 10:41:47.203086 am')
}))
})