steps
stepdefaultProperties
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'83fdd12e-c8ff-d04c-aca7-8a67eac8a477').
(#iconCode -> 'nil').
(#id -> #defaultProperties).
(#isProperty -> true).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '30 December 2014 5:04:25 pm').
(#view -> ViExplorerView)}))})