steps
step59e1a354ea9e3d4db4c670d3a9eb6d48
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQuerySortStep).
(#definition -> #'2e76e4da-8a81-b141-bbbc-e1c438ed5134').
(#iconCode -> 'nil').
(#id -> #'59e1a354-ea9e-3d4d-b4c6-70d3a9eb6d48').
(#label -> nil).
(#next -> #'d65616b9-310e-3c4d-88d4-b82f6ff8c6f5').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 3100)}))})