steps
step70abd3f8b6163145bfbe651358866ea6
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'80a0c58a-5558-7b4b-b933-1bd54f7214c0').
(#iconCode -> 'nil').
(#id -> #'70abd3f8-b616-3145-bfbe-651358866ea6').
(#isProperty -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#after -> #(#groupsMinimal)).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:11.654834 pm')
}))
})