steps
step2cd2a1cf90c5db48b1a2d74f204ecacf
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'55c88de4-6025-784a-be92-e1e5dc17e0e4').
(#iconCode -> 'nil').
(#id -> #'2cd2a1cf-90c5-db48-b1a2-d74f204ecacf').
(#label -> 'All superclasses').
(#next -> #'cc9afa06-dafe-3f47-8613-5b6306c75ac4').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 360)}))})