steps
step78e451dfad36ef4d9e212fb3e7bae0f1
	<step>

	^ (Dictionary newFrom: {
(#'_def' -> (Dictionary newFrom: {
(#block -> [:in :out | out addAll: in]).
(#className -> #ViScriptDefinition).
(#id -> #'ff1b9ab3-bfd3-544c-820a-325431fce6ee').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:11.714834 pm')
})).
(#sourceCode -> '[:in :out | out addAll: in]')
})).
(#className -> #ViScriptStep).
(#definition -> #'ff1b9ab3-bfd3-544c-820a-325431fce6ee').
(#iconCode -> 'nil').
(#id -> #'78e451df-ad36-ef4d-9e21-2fb3e7bae0f1').
(#isProperty -> false).
(#label -> nil).
(#next -> #'9fe8fed8-f944-ec41-b97b-3eff6b3cf74f').
(#properties -> (Dictionary newFrom: {
(#after -> #(#groupsMinimal)).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:11.714834 pm')
}))
})