steps
step1b7534bd882c2d458ff704510695ae1c
	<step>

	^ (Dictionary newFrom: {
(#'_def' -> (Dictionary newFrom: {
(#block -> [:in :out | out add: {#objects -> in}, [{
	#bounds -> (423@352 corner: 635@373).
	#current -> #'1af15768-bcf7-b14b-83c1-b420955ce1e4'.
	#scripts -> #(#'1af15768-bcf7-b14b-83c1-b420955ce1e4' ).
	#id -> #'4cc8c555-00fc-e049-b56d-1ca0013dea25'.
	#out -> #().
	#in -> #(#(#interactive #'40a98164-6ab3-db44-8db2-caa27b0c9f0c' ) ).
}] value]).
(#className -> #ViScriptDefinition).
(#id -> #'532b388c-e4ee-b544-be59-7d3619e04e42').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 October 2015 2:07 pm')
})).
(#sourceCode -> '[:in :out | out add: {#objects -> in}, [{
	#bounds -> (423@352 corner: 635@373).
	#current -> #''1af15768-bcf7-b14b-83c1-b420955ce1e4''.
	#scripts -> #(#''1af15768-bcf7-b14b-83c1-b420955ce1e4'' ).
	#id -> #''4cc8c555-00fc-e049-b56d-1ca0013dea25''.
	#out -> #().
	#in -> #(#(#interactive #''40a98164-6ab3-db44-8db2-caa27b0c9f0c'' ) ).
}] value]')
})).
(#className -> #ViScriptStep).
(#definition -> #'532b388c-e4ee-b544-be59-7d3619e04e42').
(#iconCode -> 'nil').
(#id -> #'1b7534bd-882c-2d45-8ff7-04510695ae1c').
(#isProperty -> true).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 October 2015 2:07 pm').
(#view -> ViMultiPaneTiled)
}))
})