steps
stepc7e12f641638ba4392a55110b39063f2
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupStep).
(#definition -> #'5f9c4c42-67c8-c44c-99bc-c4bbff0a8363').
(#iconCode -> 'nil').
(#id -> #'c7e12f64-1638-ba43-92a5-5110b39063f2').
(#label -> nil).
(#next -> #'4b813e3f-30bb-714c-9658-02f84e1ecc5b').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 September 2013 6:58:12 pm').
(#priority -> 3770)}))})