steps
stepb81e14ce2c55114ea729a2cb482e4b71
	<step>

	^ ((Dictionary new) add: (#definition->#'31c04a24-bcc1-b240-93ec-34ce9302545c'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->CompiledMethod); add: (#priority->200); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'9 December 2015 10:25:03 am'); yourself)); add: (#isProperty->false); add: (#next->#'26cb48ed-78b2-6d43-893b-ab8f69e4090f'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'b81e14ce-2c55-114e-a729-a2cb482e4b71'); add: (#isReference->false); yourself)