steps
stepa64e11c56bfc5a42a738d78d947d80da
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupStep).
(#definition -> #'6a44269a-e17d-f046-bf8f-b446ad7082d0').
(#iconCode -> 'nil').
(#id -> #'a64e11c5-6bfc-5a42-a738-d78d947d80da').
(#label -> nil).
(#next -> #'82277b8f-15e6-124f-96d4-0a482e6e0aab').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 September 2013 5:27:17 pm').
(#priority -> 3730)}))})