steps
step985a7a4ba46d7744abf1de2be369fc56
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'dd6f227e-c7bc-3843-aa10-7deb3094959a').
(#iconCode -> 'UiFugueIcons magnifierMediumIcon').
(#id -> #'985a7a4b-a46d-7744-abf1-de2be369fc56').
(#isProperty -> false).
(#isReference -> false).
(#label -> 'Receiver Inspector').
(#next -> #'bce4eb13-a02d-144e-96b2-cd2944b85fee').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #identity).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 1:01:49 pm').
(#inputKind -> Context).
(#priority -> 5160).
(#view -> ViTreeViewExtended)}))})