steps
stepa6bc57c78e46fc4ba64faccbe55ab577
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'bd2b1864-82cc-fc46-92ef-5e3b97a5317d').
(#iconCode -> 'nil').
(#id -> #'a6bc57c7-8e46-fc4b-a64f-accbe55ab577').
(#isProperty -> false).
(#label -> 'Closed objects').
(#next -> #'56d4e61d-ee76-514b-bc24-e352a53b0d46').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#inputKind -> ViStampedHistory).
(#priority -> 460).
(#view -> ViTreeViewExtended)}))})