steps
stepb30d31379d85cb4699bea7682d624290
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupSortStep).
(#definition -> #compareObjectsAsStrings).
(#iconCode -> 'nil').
(#id -> #'b30d3137-9d85-cb46-99be-a7682d624290').
(#label -> nil).
(#next -> #'7b56c7af-5bd2-4848-9eae-c2af03afefde').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 2730)}))})