steps
step8579d16a7cedf746893390568d7c97e0
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'ad1b51e5-029d-e247-bbb0-af3f31d87bd0').
(#iconCode -> 'nil').
(#id -> #'8579d16a-7ced-f746-8933-90568d7c97e0').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 September 2013 9:31:08 am').
(#headerText -> '2').
(#labelColor -> #'000000').
(#priority -> 3630)}))})