steps
step8f53a4cc854f7843a59c68a80249da1d
	<step>

	^ ((Dictionary new) add: (#definition->#'f1443833-1fa6-ac4c-8aee-069282594f6b'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'15 December 2015 10:39:29 am'); yourself)); add: (#isProperty->true); add: (#next->#'0502fbc6-6bc8-5145-9f5d-4b683a4318ed'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'8f53a4cc-854f-7843-a59c-68a80249da1d'); add: (#isReference->false); yourself)