steps
stepccb87580d74cdc47a558206c68840342
	<step>

	^ ((Dictionary new) add: (#definition->#'5fbe5c7f-6f1f-ad40-81ab-faf3f9ee4b4d'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'14 December 2015 11:53:32 am'); yourself)); add: (#isProperty->false); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'ccb87580-d74c-dc47-a558-206c68840342'); add: (#isReference->true); yourself)