steps
stepebce0b0460c9a340a531b5c1f93c9a20
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'a150785b-2faf-4140-8261-ca76555615a9').
(#iconCode -> 'nil').
(#id -> #'ebce0b04-60c9-a340-a531-b5c1f93c9a20').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'3cce12f6-e3d5-5b40-82fa-ff0f97f9844c').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#inputKind -> PackageInfo).
(#outputKind -> Boolean).
(#priority -> 1070)}))})