steps
step263f43b53e25214b93bef88d5ecf84b5
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'b41b99d3-9f47-6242-bf1f-28dcc2c72674').
(#iconCode -> 'ViEclipseIcons breakpointViewIcon').
(#id -> #'263f43b5-3e25-214b-93be-f88d5ecf84b5').
(#isProperty -> false).
(#isReference -> false).
(#label -> 'Breakpoints').
(#next -> #'829e7d5e-2892-544a-a015-d5efe0983785').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #defaultProperties).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#inputKind -> PackageInfo).
(#outputKind -> ViFlagComment).
(#priority -> 4010).
(#view -> ViTreeViewExtended)}))})