steps
step4e96ab7fcc8d1040aad0ed4e9026b875
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'a106f1b0-9632-e247-a7b3-e27d6eec5845').
(#iconCode -> 'nil').
(#id -> #'4e96ab7f-cc8d-1040-aad0-ed4e9026b875').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'57ef0b8f-46a4-1744-80b4-6974ec1adc76').
(#properties -> (Dictionary newFrom: {
(#copyOf -> #'8ed979bd-353a-934e-9977-6e22d8afc389').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '12 May 2015 4:36:46 pm')}))})