steps
step5123647a039a3d47b703c3d759aefb93
	<step>

	^ ((Dictionary new) add: (#definition->#'c05078c3-60b7-974f-9638-11f50024055a'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->ClassDescription); add: (#priority->300); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'9 December 2015 1:06:03 pm'); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->#'4f14fbe5-65d1-c74f-ab1f-7751495fcf7c'); add: (#label->'Class hierarchy (subclasses)'); add: (#iconCode->'UiSilkIcons carIcon'); add: (#id->#'5123647a-039a-3d47-b703-c3d759aefb93'); add: (#isReference->false); yourself)