steps
stepb234af3a9e84dd4a935c604a312f353f
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'2f28efd9-bc15-164f-8584-e049b306ecc8').
(#iconCode -> 'UiSilkIcons timeIcon').
(#id -> #'b234af3a-9e84-dd4a-935c-604a312f353f').
(#label -> 'Method Versions').
(#next -> #'4ee8e2d8-9bc6-7645-b541-f743df30fe9d').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 210)}))})