steps
step012db9f44e1ecc49aa55265d82592ec7
	<step>

	^ ((Dictionary new) add: (#definition->#'b45c17af-a58f-0e4c-9df3-a0fe684a4ae0'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 October 2015 10:58:50 am'); yourself)); add: (#isProperty->true); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'012db9f4-4e1e-cc49-aa55-265d82592ec7'); add: (#isReference->false); yourself)