steps
stepbce4eb13a02d144e96b2cd2944b85fee
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'78d34cba-9aaa-1743-b23e-2bc87f34d97a').
(#iconCode -> 'UiFugueIcons magnifierMediumIcon').
(#id -> #'bce4eb13-a02d-144e-96b2-cd2944b85fee').
(#isProperty -> false).
(#isReference -> false).
(#label -> 'Inspector').
(#next -> #'c50d0c14-b3eb-cf47-9e8a-7ba23cb2c4dd').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 February 2014 10:12:18 am').
(#outputKind -> Association).
(#priority -> 5170).
(#view -> ViTreeViewExtended)}))})