steps
step0f263fa973930a45ade8fdacace2318a
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'78ad143c-a506-de4f-b4ab-dc169e051970').
(#iconCode -> 'nil').
(#id -> #'0f263fa9-7393-0a45-ade8-fdacace2318a').
(#isProperty -> true).
(#label -> nil).
(#next -> #'d50e64dd-2c00-694f-9ed1-a81ee1b01b81').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 4310)
}))
})