steps
stepa4ac81fcd21c7240abf868d76d2dc175
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'068f96bd-e44f-e349-91d8-1a6a40a7afd0').
(#iconCode -> 'UiFugueIcons categoryIcon').
(#id -> #'a4ac81fc-d21c-7240-abf8-68d76d2dc175').
(#label -> 'Categories').
(#next -> #'3947aee4-5c3a-1649-8884-a37f2fcf75e9').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 150).
(#view -> ViTreeViewExtended)}))})