steps
step70f2866cc1934849bbc6734357c4521f
	<step>

	^ (Dictionary newFrom: {
(#'_def' -> (Dictionary newFrom: {
(#block -> [:in :out | out addAll: ([:objects | objects] value: in)]).
(#className -> #ViScriptDefinition).
(#id -> #'2909f9fe-4d35-8542-b0da-49fa6a8b6a35').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')
})).
(#sourceCode -> '[:in :out | out addAll: ([:objects | objects] value: in)]')
})).
(#className -> #ViScriptStep).
(#definition -> #'2909f9fe-4d35-8542-b0da-49fa6a8b6a35').
(#iconCode -> 'nil').
(#id -> #'70f2866c-c193-4849-bbc6-734357c4521f').
(#isProperty -> false).
(#label -> 'Script Objects').
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 1:01:49 pm').
(#priority -> 6590).
(#view -> ViTreeViewExtended)
}))
})