steps
step6538b2d10d571345abf64be841b78c42
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #allMethodsForClass).
(#iconCode -> 'nil').
(#id -> #'6538b2d1-0d57-1345-abf6-4be841b78c42').
(#label -> 'Methods (Signatures)').
(#next -> #'f0de7c84-7017-2d42-860d-e743620ce3b4').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'bec0a4ef-c091-a844-88ef-be4ea489648e').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 6490).
(#view -> ViTreeViewExtended)}))})