steps
step8290f350f0112348a5277cfb1d2a5a45
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'d0916bc9-7082-ad48-b568-cf6594d4730e').
(#iconCode -> 'nil').
(#id -> #'8290f350-f011-2348-a527-7cfb1d2a5a45').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Origin').
(#labelColor -> '#AAAAAA').
(#priority -> 2600)}))})