steps
step1f346fc9d1d0494c8f22fa56031636cb
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'25ba5d71-aab6-224f-b0c7-1fe9151c9ecc').
(#iconCode -> 'nil').
(#id -> #'1f346fc9-d1d0-494c-8f22-fa56031636cb').
(#label -> nil).
(#next -> #'46817f32-e66b-9342-a3ad-abe14e9713c9').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #defaultProperties).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 630)}))})