steps
step31f74b61d090a44399cc182ef8e9b039
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'92d66888-3e33-e449-82ee-fc6d9fdf72e6').
(#iconCode -> 'nil').
(#id -> #'31f74b61-d090-a443-99cc-182ef8e9b039').
(#label -> nil).
(#next -> #'0da6c0f0-1c3d-3e41-a670-8bc5919f788a').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Value').
(#labelColor -> '#000000').
(#priority -> 2890)}))})