steps
stepe44e7438eba573448590a778889ab428
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'2d539c1b-df9b-604e-ae8d-70eff84ca13e').
(#iconCode -> 'nil').
(#id -> #'e44e7438-eba5-7344-8590-a778889ab428').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 10:22:01 am').
(#labelColor -> '#000000').
(#priority -> 5050)}))})