steps
stepbfc2203ca7dbc84f95741514d216b6e2
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'934e4a55-01f2-e344-963c-6e32fe1b86a6').
(#iconCode -> 'nil').
(#id -> #'bfc2203c-a7db-c84f-9574-1514d216b6e2').
(#isProperty -> false).
(#label -> nil).
(#next -> #'969d8eb9-9007-b041-b58e-a1fd25a2d732').
(#properties -> (Dictionary newFrom: {
(#after -> #(#groups)).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '20 May 2015 2:36:10 pm')}))})