steps
step594a2a29f4d79447bc7d0f50be719127
	<step>

	^ ((Dictionary new) add: (#definition->#'dceac215-ec7a-aa48-a9d9-0c1e45043057'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'14 December 2015 11:52:58 am'); yourself)); add: (#isProperty->false); add: (#next->#'ccb87580-d74c-dc47-a558-206c68840342'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'594a2a29-f4d7-9447-bc7d-0f50be719127'); add: (#isReference->false); yourself)