steps
stepa8d9e9fc0bb3384b9baee3c1edb07163
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'e61081e3-2255-064f-8d98-82b88eaac9b4').
(#iconCode -> 'nil').
(#id -> #'a8d9e9fc-0bb3-384b-9bae-e3c1edb07163').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 February 2014 11:23:26 am').
(#priority -> 5550)}))})