steps
step5bac288b036f3b409351de76b1f7cd03
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'58e3ab98-ca82-5642-86d7-05c3b94c72d8').
(#iconCode -> 'nil').
(#id -> #'5bac288b-036f-3b40-9351-de76b1f7cd03').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'NumVersions').
(#labelColor -> '#AAAAAA').
(#priority -> 3130)}))})