steps
step26cb48ed78b26d43893bab8f69e4090f
	<step>

	^ (Dictionary newFrom: {
(#'_def' -> (Dictionary newFrom: {
(#block -> [:in :out | out addAll: in]).
(#className -> #ViScriptDefinition).
(#id -> #'afcc3456-1c10-5d4c-aa94-a1fd5b3f1d66').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '9 December 2015 10:25:03 am')
})).
(#sourceCode -> '[:in :out | out addAll: in]')
})).
(#className -> #ViScriptStep).
(#definition -> #'afcc3456-1c10-5d4c-aa94-a1fd5b3f1d66').
(#iconCode -> 'nil').
(#id -> #'26cb48ed-78b2-6d43-893b-ab8f69e4090f').
(#isProperty -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#after -> #(#implementors)).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '9 December 2015 10:25:03 am')
}))
})