steps
step7fd41212698dee438d8f0dc8fb2b9a9e
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'ce888f55-7ca5-8b44-b649-95ab16e5edfc').
(#iconCode -> 'nil').
(#id -> #'7fd41212-698d-ee43-8d8f-0dc8fb2b9a9e').
(#label -> nil).
(#next -> #'574aa5e1-9265-754a-9cdb-57e45108ee46').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '3 September 2013 3:35:47 pm').
(#priority -> 2380)}))})