steps
stepe33fe689cff8ff4fb574d2a3b3986f94
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'e56dcef1-1fe0-4645-b354-b85dc88c7cf7').
(#iconCode -> 'nil').
(#id -> #'e33fe689-cff8-ff4f-b574-d2a3b3986f94').
(#label -> nil).
(#next -> #'3544ebd4-2cab-b84a-88d2-0c15dde14360').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 February 2014 1:08:29 pm').
(#headerText -> #DMf).
(#priority -> 5330)}))})