steps
step177406757772764181dc431205cff3b8
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'e1847060-7932-f24c-bb49-9605f81a15d2').
(#iconCode -> 'nil').
(#id -> #'17740675-7772-7641-81dc-431205cff3b8').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '9 September 2013 2:59:20 pm').
(#priority -> 3260)}))})