steps
step89c40fb8551c9e469651f11978e9ff30
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'90e36e33-cecf-6c4a-b7a9-0c4f6192bed2').
(#iconCode -> 'nil').
(#id -> #'89c40fb8-551c-9e46-9651-f11978e9ff30').
(#label -> nil).
(#next -> #'4c0b175c-ebc3-fb4e-9b1c-31b8b5b5660d').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Object').
(#priority -> 2340)}))})