steps
step60f99406f09f354a9ed291ddd9060fc4
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'6f88a5a4-246a-344e-a485-3b15cb6fa9ea').
(#iconCode -> 'nil').
(#id -> #'60f99406-f09f-354a-9ed2-91ddd9060fc4').
(#label -> nil).
(#next -> #'cafd96b4-6e9f-904c-bb72-8015ce0d112f').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '17 January 2014 2:56:58 pm').
(#priority -> 4700)}))})