steps
step03a844ab437b6c418cf915f9a8aab212
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupSortStep).
(#definition -> #compareObjectsAsStrings).
(#iconCode -> 'nil').
(#id -> #'03a844ab-437b-6c41-8cf9-15f9a8aab212').
(#label -> nil).
(#next -> #'e4cedfc1-3419-6a46-a306-65067830a9bf').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'d8173faa-7721-b340-afaa-a4d664743096').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '7 November 2013 10:52:48 am').
(#priority -> 5470)}))})