steps
step8ebc1c715396204d98e9e545b22d0823
	<step>

	^ ((Dictionary new) add: (#definition->#'e35033ec-dd91-fe4b-8f59-13e3c734740e'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'15 June 2015 10:20:57 am'); add: (#copyOf->#'a04dcc3b-6be7-fa42-9cc3-a91b1141dcf1'); yourself)); add: (#isProperty->false); add: (#next->#'6b83183f-11b1-294b-bfa7-11e681f78ad8'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'8ebc1c71-5396-204d-98e9-e545b22d0823'); add: (#isReference->false); yourself)