steps
stepfcae92ef09ebff47be9e9e35c33c4784
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'7d2c6d83-7fc4-8849-b932-417e83f5471a').
(#iconCode -> 'nil').
(#id -> #'fcae92ef-09eb-ff47-be9e-9e35c33c4784').
(#isProperty -> false).
(#label -> nil).
(#next -> #'bc34ef97-52af-6c49-b344-cdb766681c0c').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 September 2013 6:31:32 pm').
(#inputKind -> PackageInfo).
(#outputKind -> Behavior).
(#priority -> 3830).
(#view -> ViTreeViewExtended)
}))
})