steps
step524b534fb2f52447a4d09a1769f2d123
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'298c9fc0-b1c0-174e-8db4-7f9f8cee2ea6').
(#iconCode -> 'nil').
(#id -> #'524b534f-b2f5-2447-a4d0-9a1769f2d123').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '14 August 2014 1:19:01 pm').
(#priority -> 6750)}))})