steps
step6d55d7d63c09b044b03a0105386e67a4
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #removeDuplicates).
(#iconCode -> 'nil').
(#id -> #'6d55d7d6-3c09-b044-b03a-0105386e67a4').
(#label -> nil).
(#next -> #'3dbca45d-ef24-5e49-975e-38f04a9a7729').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'b90e4eaa-f8ab-8b47-aca3-f78a5dadde3e').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '4 October 2013 6:33:02 pm').
(#priority -> 4500)}))})