steps
stepf0de7c8470172d42860de743620ce3b4
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'299c3043-060f-d940-ae3c-d1d0609486d6').
(#iconCode -> 'nil').
(#id -> #'f0de7c84-7017-2d42-860d-e743620ce3b4').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'36a4ecd2-893b-604c-9199-84cbfbffa8d4').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'dd7cc162-78d3-5946-8ad0-7e30f7b46f6d').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#outputKind -> Boolean).
(#priority -> 6530)}))})