steps
stepb0043854ca340844a516d5c81e51c885
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'15beca97-e0c0-1e44-81d7-45840aeb820b').
(#iconCode -> 'nil').
(#id -> #'b0043854-ca34-0844-a516-d5c81e51c885').
(#label -> 'Variables for whileTrue senders').
(#next -> #'5c3b9aae-476e-cc4f-96a1-da5e5ab421ad').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 940).
(#view -> ViTreeViewExtended)}))})