steps
stepfdb69e0a57ea394aa74ab986817dca93
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'e4592bf3-ca81-2446-be75-29fee8fe6683').
(#iconCode -> 'nil').
(#id -> #'fdb69e0a-57ea-394a-a74a-b986817dca93').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#labelColor -> '#AAAAAA').
(#priority -> 3190)}))})