steps
step3952d601cc18de4e81ebdbdbeb2ba7c2
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'0359b0f1-42e5-ef4c-b993-3022fe9fa515').
(#iconCode -> 'nil').
(#id -> #'3952d601-cc18-de4e-81eb-dbdbeb2ba7c2').
(#label -> 'File tree').
(#next -> #'2d21437b-3606-d343-9872-5e357a12de36').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 710)}))})