steps
step24f23db6299dcc46bb92693cb90073d6
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'f96e87d9-b692-1b47-a3c7-e03bebbb78f1').
(#iconCode -> 'nil').
(#id -> #'24f23db6-299d-cc46-bb92-693cb90073d6').
(#label -> nil).
(#next -> #'3eddb241-9533-1349-8650-c86422ca0395').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 2630)}))})