steps
stepf99fb960e1609e4baa910c8cd134d9c7
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'177fc530-e045-5f4c-96d6-d074e991c669').
(#iconCode -> 'nil').
(#id -> #'f99fb960-e160-9e4b-aa91-0c8cd134d9c7').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '24 August 2016 4:50:38 pm')}))})