steps
step4c3d8ed222690a47a18673b16354aa6d
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'4481e683-9fc3-cd47-b821-4ed126ef9c54').
(#iconCode -> 'nil').
(#id -> #'4c3d8ed2-2269-0a47-a186-73b16354aa6d').
(#isProperty -> false).
(#label -> 'Lines of Code').
(#next -> #'e6c86a4e-3d9c-de46-afc1-e019ab13b011').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 4740).
(#view -> ViTreeViewExtended)}))})