steps
step5ec063434180cf4da211f78d46a2112e
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQuerySortStep).
(#definition -> #compareObjectsByName).
(#iconCode -> 'nil').
(#id -> #'5ec06343-4180-cf4d-a211-f78d46a2112e').
(#label -> nil).
(#next -> #'55d465d1-f7d0-c04f-a61b-099f2ae6b6b9').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'164491a2-978d-5d4e-8931-03fff9ded75e').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 4530)}))})