steps
stepe0d4454d01886242916d1c1f2b47e445
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'3d0c7269-aed8-9e4a-9b3d-fa7ec52d2dc1').
(#iconCode -> 'nil').
(#id -> #'e0d4454d-0188-6242-916d-1c1f2b47e445').
(#label -> nil).
(#next -> #'53515aaf-6982-b048-afb6-e82af653f073').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Name').
(#labelColor -> '#999999').
(#priority -> 2440)}))})