steps
step5401af50ff0b9941b85035ffa4179d50
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'2415ac87-fed6-5649-afa6-88ac79e1aa8d').
(#iconCode -> 'nil').
(#id -> #'5401af50-ff0b-9941-b850-35ffa4179d50').
(#label -> nil).
(#next -> #'5c2e7b34-3c99-9341-badb-b111a003abb4').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'T').
(#labelColor -> '#AAAAAA').
(#priority -> 1180)}))})