steps
step252b6d01f4902640a5fc6b968dc12be4
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupSortStep).
(#definition -> #compareObjectsAsStrings).
(#iconCode -> 'nil').
(#id -> #'252b6d01-f490-2640-a5fc-6b968dc12be4').
(#label -> nil).
(#next -> #'432a6001-f00e-514e-a68e-4605686f7755').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 2660)}))})