steps
step427e325e4f83274faa3db1b3a19ef7e6
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'0bf69775-247f-af43-b081-d9faa1a7243e').
(#iconCode -> 'nil').
(#id -> #'427e325e-4f83-274f-aa3d-b1b3a19ef7e6').
(#isProperty -> true).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 September 2013 5:36:31 pm').
(#priority -> 4060)
}))
})