steps
stepcf7fdd6602719544b4a93ecca1e4a611
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'aded2941-6919-d94c-91cd-6c548f123171').
(#iconCode -> 'nil').
(#id -> #'cf7fdd66-0271-9544-b4a9-3ecca1e4a611').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '23 July 2014 2:54:01 pm').
(#headerText -> 'view class').
(#priority -> 6720)}))})