steps
step641df55bdc10f74486f32f5eb3f970ab
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'a8b54fbe-9013-8a46-8a7a-a5ea605d17f5').
(#iconCode -> 'nil').
(#id -> #'641df55b-dc10-f744-86f3-2f5eb3f970ab').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'c185247b-7a50-f045-a2a1-b24c4e26d2b4').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Comment').
(#priority -> 2310)}))})