steps
stepb04432837194df4ebcb62dc3d3395f1b
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'993c7c50-6983-824c-abac-e6c222d6a2dd').
(#iconCode -> 'nil').
(#id -> #'b0443283-7194-df4e-bcb6-2dc3d3395f1b').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Contents').
(#priority -> 2810)}))})