steps
stepformattedQueries
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'5c81b0a9-9ca8-4d4f-bf64-ec5c3d25c09f').
(#iconCode -> 'nil').
(#id -> #formattedQueries).
(#isProperty -> false).
(#isReference -> false).
(#label -> 'Scripts').
(#next -> #'1af811b8-5914-fa4a-a308-6a17174c3d9c').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '7 December 2015 2:00:40 pm').
(#inputKind -> ViScriptStep).
(#outputKind -> ViScriptStep).
(#view -> ViTreeView).
(#yieldOn -> #(#activated))}))})