steps
stepfb29cb249914764a864e6e8e1cf8ace2
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'14f96a52-b520-9b45-9532-ecfdfb233f09').
(#iconCode -> 'nil').
(#id -> #'fb29cb24-9914-764a-864e-6e8e1cf8ace2').
(#isProperty -> false).
(#isReference -> true).
(#label -> nil).
(#next -> #'89c40fb8-551c-9e46-9651-f11978e9ff30').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:11.276834 pm')}))})