steps
step047d9a9710d06c458228c223ea969775
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #origin).
(#iconCode -> 'nil').
(#id -> #'047d9a97-10d0-6c45-8228-c223ea969775').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Author').
(#labelColor -> '#AAAAAA').
(#priority -> 1610)}))})