steps
step52a42afce8cf7d4593f8c5f88bd3f49b
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #selectByContext).
(#iconCode -> 'nil').
(#id -> #'52a42afc-e8cf-7d45-93f8-c5f88bd3f49b').
(#label -> nil).
(#next -> #'688b9e53-cc30-9341-a368-54f6c47e402c').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 September 2013 3:11:48 pm').
(#priority -> 3990)}))})