steps
step9116a93ca93f224dabf174f2e5067a77
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'8a196207-ea94-b944-901f-dd53bce5fd8a').
(#iconCode -> 'UiSilkIcons carIcon').
(#id -> #'9116a93c-a93f-224d-abf1-74f2e5067a77').
(#isProperty -> false).
(#label -> 'Classes in category').
(#next -> #'a718839b-0562-2649-8d2e-fcb3995dd716').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '14 December 2015 11:30:58 am').
(#inputKind -> String).
(#priority -> 220)}))})