steps
step5a2edad8c307144aa4b6dfdddd2c429d
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'ca63f41a-42ba-4a4c-8fc3-39f3fd8428b2').
(#iconCode -> 'nil').
(#id -> #'5a2edad8-c307-144a-a4b6-dfdddd2c429d').
(#label -> nil).
(#next -> #'e5bd3f6c-f63f-b148-89bc-82784354babd').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Origin').
(#labelColor -> '#AAAAAA').
(#priority -> 1150)}))})