steps
step240cc4b3dcec8c4ebbe829ff7c118338
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'411fe2ba-bf14-1b42-894f-51e6b19391e2').
(#iconCode -> 'nil').
(#id -> #'240cc4b3-dcec-8c4e-bbe8-29ff7c118338').
(#isProperty -> true).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '9 January 2014 11:34:40 am').
(#priority -> 4620)}))})