steps
stepba4b7a9cc7c95145a45e2cdf2b0a3940
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'a24a8241-358e-5643-a2f1-62eed7d243c0').
(#iconCode -> 'UiFugueIcons bookBrownIcon').
(#id -> #'ba4b7a9c-c7c9-5145-a45e-2cdf2b0a3940').
(#isProperty -> false).
(#isReference -> false).
(#label -> 'Vocabulary (for class)').
(#next -> #'95c74daf-50da-9d48-956b-a1e377ae9019').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '9 December 2015 11:55:27 am').
(#inputKind -> ClassDescription).
(#priority -> 250).
(#view -> ViTreeView)}))})