steps
step0d7618526cd4fd4e82641ec9396e2865
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'f05ec723-94c8-1c40-82d5-f606aade5b23').
(#iconCode -> 'nil').
(#id -> #'0d761852-6cd4-fd4e-8264-1ec9396e2865').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '29 May 2018 9:29:06 am').
(#inputKind -> #(nil nil))}))})