steps
stepe84072d2c593f549a93cd5dbeb2e3b94
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #iconAndLabel).
(#iconCode -> 'nil').
(#id -> #'e84072d2-c593-f549-a93c-d5dbeb2e3b94').
(#label -> nil).
(#next -> #'3723f748-fad3-d446-8f95-d2d495e9a9cc').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1370)}))})