steps
step200451f46f37ab48876b2719c863b2c9
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'f009b85e-fe0f-544e-be07-32772fd16970').
(#iconCode -> 'nil').
(#id -> #'200451f4-6f37-ab48-876b-2719c863b2c9').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '6 March 2018 10:31 am')}))})