steps
stepd423159711476f428714146585f297d8
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'74d42c6d-fa57-e44c-958d-da199a3de398').
(#iconCode -> 'nil').
(#id -> #'d4231597-1147-6f42-8714-146585f297d8').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '20 February 2014 6:23 pm').
(#headerText -> 'Class').
(#priority -> 6000)}))})