steps
step3a028d6521d5c7409ce22d16d0b47a42
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'2240fd95-5e9a-f745-97eb-38ddbce8c00e').
(#iconCode -> 'nil').
(#id -> #'3a028d65-21d5-c740-9ce2-2d16d0b47a42').
(#label -> nil).
(#next -> #'b3b87871-7516-5049-b092-72ad966f3216').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '23 July 2014 3:01:21 pm').
(#priority -> 6660)}))})