steps
step1af15768bcf7b14b83c1b420955ce1e4
	<step>

	^ ((Dictionary new) add: (#definition->#'f5282b30-1fcd-3143-9cd3-547c55e05dfb'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#view->ViPluggableButtonBarMorph); add: (#creationTimeStamp->'19 October 2015 2:07 pm'); add: (#copyOf->#'e9577839-3b92-8e4f-a413-365561ade680'); add: (#isNew->false); yourself)); add: (#isProperty->true); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'1af15768-bcf7-b14b-83c1-b420955ce1e4'); add: (#isReference->false); yourself)