steps
stepf45253e31e6123448ebb69fad9e592af
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'fb02d8cf-feb7-7540-b0db-23ee748e30c0').
(#iconCode -> 'nil').
(#id -> #'f45253e3-1e61-2344-8ebb-69fad9e592af').
(#label -> nil).
(#next -> #'ed47392d-e9cf-e24c-9069-a3a89fba2ea6').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1720)}))})