steps
stepa7590d1be0ee6340a3d476e67ae30cfa
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'9b7536b8-2ed2-7d4a-8f9a-08d09080a025').
(#iconCode -> 'nil').
(#id -> #'a7590d1b-e0ee-6340-a3d4-76e67ae30cfa').
(#isProperty -> true).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 February 2014 4:58:32 pm').
(#priority -> 5690)}))})