steps
step79c77c1fcaea9342ab06db5aad7909f0
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupStep).
(#definition -> #'09aee677-4dd4-a647-8067-b5f15a60f5ff').
(#iconCode -> 'nil').
(#id -> #'79c77c1f-caea-9342-ab06-db5aad7909f0').
(#label -> nil).
(#next -> #'e5522090-7365-c442-8d15-94253ec1d77e').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1310)}))})