steps
stepe6c86a4e3d9cde46afc1e019ab13b011
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQuerySortStep).
(#definition -> #compareObjectsByName).
(#iconCode -> 'nil').
(#id -> #'e6c86a4e-3d9c-de46-afc1-e019ab13b011').
(#label -> nil).
(#next -> #'a0430b66-9a7d-f044-be09-b17780bf171f').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '12 February 2014 3:28:35 pm').
(#priority -> 5100)}))})