steps
stepa4597f8283f5f1458733996443dff441
	<step>

	^ ((Dictionary new) add: (#definition->#'11a05738-cd99-4b4c-8219-090dd6bf4a19'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->CompiledMethod); add: (#priority->300); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'9 December 2015 11:26:37 am'); add: (#view->ViTreeViewExtended); yourself)); add: (#isProperty->false); add: (#next->#'297515f3-11ce-2e45-94a2-b23a6cad1586'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'a4597f82-83f5-f145-8733-996443dff441'); add: (#isReference->false); yourself)