steps
step9d1dec9fcad6de45b2c203c8cd59b8d7
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'1155c220-eeaa-5a49-849d-1aad1424f1f6').
(#iconCode -> 'nil').
(#id -> #'9d1dec9f-cad6-de45-b2c2-03c8cd59b8d7').
(#label -> 'Diff').
(#next -> #'64c67351-149a-5b41-9de2-aa23b19628a8').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #defaultProperties).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 3610)}))})