steps
step76221c325f94c545a4a4cf57138ffe39
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQuerySortStep).
(#definition -> #compareObjectsByName).
(#iconCode -> 'nil').
(#id -> #'76221c32-5f94-c545-a4a4-cf57138ffe39').
(#label -> nil).
(#next -> #'19536a17-53f2-a544-90d1-73c5acc3cb61').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '12 February 2014 3:22:59 pm').
(#priority -> 5090)}))})