steps
step78cd19878352584e9b6b7582a5be6451
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'331ef878-24d5-f442-9676-04b6c451895a').
(#iconCode -> 'UiSilkIcons pencilIcon').
(#id -> #'78cd1987-8352-584e-9b6b-7582a5be6451').
(#isProperty -> false).
(#label -> 'Source code').
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '9 December 2015 11:02:31 am').
(#inputKind -> CompiledMethod).
(#priority -> 300).
(#view -> ViMethodEditorView)}))})