steps
step22e026ff792b1741bbcc329cf28fe2a8
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'72a4c948-9151-484f-8179-69c61e660828').
(#iconCode -> 'nil').
(#id -> #'22e026ff-792b-1741-bbcc-329cf28fe2a8').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'71efc7d9-c3cb-7246-9652-6b74bc022b8e').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '9 April 2019 6:53:50.673982 pm')}))})