steps
stepe45648f84feff3438972cbb555789355
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'c2f8f931-ca17-4e4c-bcca-2d77e7ab06db').
(#iconCode -> 'nil').
(#id -> #'e45648f8-4fef-f343-8972-cbb555789355').
(#label -> nil).
(#next -> #'62d361c4-2c39-6e47-989e-42b4f10c257c').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '14 February 2014 1:06:18 pm').
(#headerText -> #R).
(#priority -> 5290)}))})