steps
step522c315128b49e49ab9b469da3243562
	<step>

	^ (Dictionary newFrom: {
(#'_def' -> (Dictionary newFrom: {
(#block -> [:in :out | out addAll: ([:tuples | tuples asGroups] value: in) asList]).
(#className -> #ViScriptDefinition).
(#id -> #'4155320e-9514-8042-a222-ad8ecbe43679').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '23 September 2019 10:15:11.317086 am')
})).
(#sourceCode -> '[:in :out | out addAll: ([:tuples | tuples asGroups] value: in) asList]')
})).
(#className -> #ViScriptStep).
(#definition -> #'4155320e-9514-8042-a222-ad8ecbe43679').
(#iconCode -> 'nil').
(#id -> #'522c3151-28b4-9e49-ab9b-469da3243562').
(#isProperty -> false).
(#label -> nil).
(#next -> #'d9549549-4466-474a-910f-42c951f8e7bb').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '23 September 2019 10:15:11.316086 am')
}))
})