steps
stepa5b8674146bd5b47ab8da79879a3b859
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'89be9797-2710-5844-ab5e-b2bdd7f82581').
(#iconCode -> 'nil').
(#id -> #'a5b86741-46bd-5b47-ab8d-a79879a3b859').
(#label -> nil).
(#next -> #'c2d0a6c2-91d4-2643-a28f-24b6ddd117c5').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Name').
(#priority -> 2910)}))})