steps
step757cd24a516ebf45ad50d29635e9bbee
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'325e9e39-f956-f342-8b16-5d6be68397d0').
(#iconCode -> 'nil').
(#id -> #'757cd24a-516e-bf45-ad50-d29635e9bbee').
(#label -> nil).
(#next -> #'dc8af77b-cb54-d74d-a9c2-fbd92c4b2a44').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '23 July 2014 2:45:39 pm').
(#priority -> 6680)}))})