steps
stepa950d677aaeb11409923f5a2a659e541
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'79f52e45-0935-2543-8aab-381d461f7c56').
(#iconCode -> 'nil').
(#id -> #'a950d677-aaeb-1140-9923-f5a2a659e541').
(#isProperty -> false).
(#label -> 'Mail Sender Histogram').
(#next -> #'200451f4-6f37-ab48-876b-2719c863b2c9').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '6 March 2018 10:30:21 am').
(#labelHeight -> 120).
(#view -> ViBarChart)}))})