steps
stepe614ad198010a4449759aaa2423cb69e
	<step>

	^ (Dictionary newFrom: {
(#'_def' -> (Dictionary newFrom: {
(#block -> [:in :out | out addAll: in]).
(#className -> #ViScriptDefinition).
(#id -> #'e122c028-6e2c-2348-8918-5640418abb8e').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:11.743834 pm')
})).
(#sourceCode -> '[:in :out | out addAll: in]')
})).
(#className -> #ViScriptStep).
(#definition -> #'e122c028-6e2c-2348-8918-5640418abb8e').
(#iconCode -> 'nil').
(#id -> #'e614ad19-8010-a444-9759-aaa2423cb69e').
(#isProperty -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#after -> #(#'688b9e53-cc30-9341-a368-54f6c47e402c')).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '29 March 2019 5:00:11.34035 pm')
}))
})