steps
step6a2bc04714abcb4fbd8a9a78f9bc2bea
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryReferenceStep).
(#definition -> nil).
(#iconCode -> 'nil').
(#id -> #'6a2bc047-14ab-cb4f-bd8a-9a78f9bc2bea').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '29 March 2019 5:00:11.33835 pm')})).
(#reference -> #'89c40fb8-551c-9e46-9651-f11978e9ff30')})