steps
stepec77d931b152e14d83f0ca3d29ac8796
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'736d0173-87df-b44a-b06a-e1600b6b3dd9').
(#iconCode -> 'nil').
(#id -> #'ec77d931-b152-e14d-83f0-ca3d29ac8796').
(#isProperty -> true).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '20 May 2015 2:35:48 pm')}))})