steps
steped57b1e04b74094a926b2776acef9b31
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'b80b03b6-e21d-bb48-a012-435e7ab6205a').
(#iconCode -> 'nil').
(#id -> #'ed57b1e0-4b74-094a-926b-2776acef9b31').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'117962c3-a327-154a-b531-9a15adc69887').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 February 2014 1:10:45 pm').
(#headerText -> #scH).
(#priority -> 5370)}))})