steps
stepe1378983156c1d4a88b1eae6654e7fb0
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'69d88582-5b2f-ab48-8b64-99d72b1432a0').
(#iconCode -> 'UiFugueIcons layersStackArrangeIcon').
(#id -> #'e1378983-156c-1d4a-88b1-eae6654e7fb0').
(#label -> 'Call stack').
(#next -> #'1bb6538b-c256-b34b-958e-5996dea59092').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 450)}))})