steps
stepe6902a58ee3c7a4993758c1501d23175
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'4ed2999c-683e-9f40-88c2-c418e4a5ae9e').
(#iconCode -> 'nil').
(#id -> #'e6902a58-ee3c-7a49-9375-8c1501d23175').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'458cbad9-3001-ab46-8458-4bb4c3232229').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '15 September 2013 5:35:42 pm').
(#priority -> 3570)}))})