steps
stepb0a45afe6a847a47a7ee76e55a59ca80
	<step>

	^ (Dictionary newFrom: {
(#'_def' -> (Dictionary newFrom: {
(#block -> [:in :out | (
	[:objects | objects collect: [:array | array "Hmpf..."]]
		value: in) do: [:result | out addAll: result asList]]).
(#className -> #ViScriptDefinition).
(#id -> #'14e06b0b-a8b5-4f45-a6bc-4621bab2e4d5').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2019 10:02:44.810728 am')
})).
(#sourceCode -> '[:in :out | (
	[:objects | objects collect: [:array | array "Hmpf..."]]
		value: in) do: [:result | out addAll: result asList]]')
})).
(#className -> #ViScriptStep).
(#definition -> #'14e06b0b-a8b5-4f45-a6bc-4621bab2e4d5').
(#iconCode -> 'nil').
(#id -> #'b0a45afe-6a84-7a47-a7ee-76e55a59ca80').
(#isProperty -> false).
(#label -> nil).
(#next -> #'e9b91bdd-c3aa-964e-aa7f-2ccb2baacc78').
(#properties -> (Dictionary newFrom: {
(#color -> (Color r: 0.553 g: 0.796 b: 0.553)).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2019 10:02:44.808728 am')
}))
})