steps
stepc50d0c14b3ebcf479e8a7ba23cb2c4dd
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'727d53ad-887c-6c41-8d2d-12fa488d95af').
(#iconCode -> 'nil').
(#id -> #'c50d0c14-b3eb-cf47-9e8a-7ba23cb2c4dd').
(#label -> nil).
(#next -> #'46b904bc-22e5-a84a-8f30-894b0f7df352').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 February 2014 8:36:52 am').
(#priority -> 5200)}))})