steps
stepd7ca2eace77dc24a9906a486603160a0
	<step>

	^ ((Dictionary new) add: (#definition->#'28d8d922-627d-b84c-bbd1-0c95cf39f776'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'9 December 2015 11:26:37 am'); yourself)); add: (#isProperty->true); add: (#next->#'fea2b084-266a-3849-818c-699ce7e7042e'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'d7ca2eac-e77d-c24a-9906-a486603160a0'); add: (#isReference->false); yourself)