steps
step829e7d5e2892544aa015d5efe0983785
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'12e82498-d1a4-694c-80a6-8ad84486b76a').
(#iconCode -> 'nil').
(#id -> #'829e7d5e-2892-544a-a015-d5efe0983785').
(#label -> nil).
(#next -> #'5406f229-d72e-9840-a58d-c61752a3b24a').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 September 2013 3:48:13 pm').
(#headerText -> 'Resource').
(#labelColor -> '000000').
(#priority -> 4020)}))})