steps
stepd1fc3ac8c0bbcf47955a7e0b24221803
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'bbd4f630-2da3-354f-a120-7cf2c22b5c1e').
(#iconCode -> 'nil').
(#id -> #'d1fc3ac8-c0bb-cf47-955a-7e0b24221803').
(#isProperty -> true).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 5500)}))})