steps
stepbda64b7c17f63247be1d13159655ec28
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'1b047488-6502-e74e-83f2-05ae0fbf0400').
(#iconCode -> 'nil').
(#id -> #'bda64b7c-17f6-3247-be1d-13159655ec28').
(#label -> nil).
(#next -> #'2a5bc3f7-fc5f-4d42-bc5d-1a7c79ebf632').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '3 January 2014 3:20:50 pm').
(#priority -> 470)}))})