steps
stepe2c47fce01c22d40aef44fae92dba501
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryReferenceStep).
(#definition -> nil).
(#iconCode -> 'nil').
(#id -> #'e2c47fce-01c2-2d40-aef4-4fae92dba501').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '29 March 2019 5:00:11.34035 pm')})).
(#reference -> #'045e9d2c-b29a-4641-b942-d4b769535d4a')})