steps
step1bb6538bc256b34b958e5996dea59092
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'fa732aca-0a2e-bc42-8970-29b6cd5204e5').
(#iconCode -> 'nil').
(#id -> #'1bb6538b-c256-b34b-958e-5996dea59092').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'2d49b98d-3f27-e14f-aaa8-aee4706a6a0a').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 2470)}))})