steps
step3722f20331088f42b6c8174b0b028329
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'e447d0ec-6603-e945-a1d1-0c460e642dd6').
(#iconCode -> 'nil').
(#id -> #'3722f203-3108-8f42-b6c8-174b0b028329').
(#isProperty -> false).
(#isReference -> true).
(#label -> nil).
(#next -> #'c7876b21-782a-4944-88e1-399e5e82d6b5').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '29 May 2018 9:05:46 am').
(#inputKind -> #(nil nil nil ))}))})