steps
step5b500dbee712874d9c3c5abcc18d9283
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'e8e62b19-5b87-ca49-a282-32293d421ec2').
(#iconCode -> 'nil').
(#id -> #'5b500dbe-e712-874d-9c3c-5abcc18d9283').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'09e80594-1621-c84d-a66d-a59ada9c72d2').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '22 March 2018 9:31:01 pm')}))})