steps
step14f6246e2fd7f947b063767bfa454a39
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'e177696f-f6a5-474f-adf4-979f59f7bba0').
(#iconCode -> 'nil').
(#id -> #'14f6246e-2fd7-f947-b063-767bfa454a39').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'75851276-07a7-8440-8574-cc2965065a02').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '21 February 2014 8:52:10 am').
(#headerText -> 'Setup').
(#priority -> 5960)}))})