steps
step086c59441e512c4d8e179ee9bffc0d2a
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'b04c23b7-7d38-904a-b96b-4259bcf0de66').
(#iconCode -> 'nil').
(#id -> #'086c5944-1e51-2c4d-8e17-9ee9bffc0d2a').
(#isProperty -> true).
(#label -> nil).
(#next -> #'0b1978b8-7b59-4842-81f5-9f94cce1ec89').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '17 January 2014 3:22:32 pm').
(#priority -> 4830)}))})