steps
step172f485a7e690d4aa5ad7233f83da2dc
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'8b83bb1f-a784-964d-96e6-f16fbb119489').
(#iconCode -> 'nil').
(#id -> #'172f485a-7e69-0d4a-a5ad-7233f83da2dc').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'0c8adf16-5e6c-8046-b097-6a6dfeaa52ea').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#outputKind -> Boolean).
(#priority -> 1780)}))})