steps
stepa709a161d05fed4497e2165f6f140ada
	<step>

	^ ((Dictionary new) add: (#definition->#'8f437653-76f4-7543-b2e3-bce0f89efa11'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 October 2015 2:08:34 pm'); yourself)); add: (#isProperty->false); add: (#next->#'a58a2d7b-4328-1740-a7b5-288db0764a2b'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'a709a161-d05f-ed44-97e2-165f6f140ada'); add: (#isReference->false); yourself)