steps
step3554a7846c63324caecadb77b530eb36
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupSortStep).
(#definition -> #compareObjectsAsStrings).
(#iconCode -> 'nil').
(#id -> #'3554a784-6c63-324c-aeca-db77b530eb36').
(#label -> nil).
(#next -> #'a1816fcb-1266-bb43-8500-bf8b71248ede').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '8 November 2013 4:44:03 pm').
(#priority -> 4280)}))})