steps
step33a2c2eebac83b4a842dfaf5586d7042
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'6f38796b-7a6d-494e-926e-a2dc03b50f2e').
(#iconCode -> 'nil').
(#id -> #'33a2c2ee-bac8-3b4a-842d-faf5586d7042').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '12 November 2013 5:02:54 pm').
(#priority -> 4340)}))})