steps
step2e490b12bdf77341b90718df5b218b85
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'1b047488-6502-e74e-83f2-05ae0fbf0400').
(#iconCode -> 'nil').
(#id -> #'2e490b12-bdf7-7341-b907-18df5b218b85').
(#label -> nil).
(#next -> #'d681c3f1-84e3-ea45-b9b7-505c4216ddc5').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '3 January 2014 3:37:49 pm').
(#priority -> 480).
(#view -> ViTreeViewExtended)}))})