steps
stepf4803742eb440846908592c09d525159
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'8c2c398c-c701-8d43-9f84-dc0db8a4f024').
(#iconCode -> 'nil').
(#id -> #'f4803742-eb44-0846-9085-92c09d525159').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'69e497c2-4f93-4d49-84b1-94178c53e847').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '6 September 2013 8:28:17 pm').
(#inputKind -> ViQueryStepDefinition).
(#priority -> 1010)}))})