steps
step96d9ab1f38366b4c9f56ee9989b7d3a8
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'514e33c1-49ef-db4a-ab27-1b67d793b46b').
(#iconCode -> 'nil').
(#id -> #'96d9ab1f-3836-6b4c-9f56-ee9989b7d3a8').
(#label -> nil).
(#next -> #'83cf7197-6cf5-554e-b535-2b2ebf2fb60e').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #identity).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 1:01:49 pm').
(#priority -> 5810).
(#view -> ViTreeViewExtended)}))})