steps
step2771411b78421340b34e9817cf81fa72
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'70cb528b-aeee-6e45-997a-8d2c21c4f555').
(#iconCode -> 'nil').
(#id -> #'2771411b-7842-1340-b34e-9817cf81fa72').
(#isProperty -> false).
(#label -> nil).
(#next -> #'24d74d14-5e31-7641-a5f6-d6667eb3ffd2').
(#properties -> (Dictionary newFrom: {
(#after -> #(#groupsMinimal)).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:11.512834 pm')}))})