steps
step22b325c1285b62428b45bf948f7079a2
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'c6a08f05-9e2f-4542-bdfc-23dbd53617cc').
(#iconCode -> 'nil').
(#id -> #'22b325c1-285b-6242-8b45-bf948f7079a2').
(#label -> nil).
(#next -> #'d977be3c-9e8a-6740-bff7-63c0bd8811c0').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Origin').
(#labelColor -> '#AAAAAA').
(#priority -> 2020)}))})