steps
stepcf18cd020e0b344ca7ee82358865b598
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupStep).
(#definition -> #'efde47c0-b44a-7b49-9f37-ea3243404447').
(#iconCode -> 'nil').
(#id -> #'cf18cd02-0e0b-344c-a7ee-82358865b598').
(#label -> nil).
(#next -> #'44a90e06-f665-1a44-923a-22a2103ad8ba').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'cf18cd02-0e0b-344c-a7ee-82358865b598').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 September 2013 6:49:23 pm').
(#priority -> 3320)}))})