steps
step5caa8ce0090bdc41baa3624188233e5f
	<step>

	^ ((Dictionary new) add: (#definition->#'02954be5-d532-1844-ba67-d5577598c1a6'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->ViAnimatedImageMorph); add: (#creationTimeStamp->'12 May 2015 3:24:26 pm'); add: (#priority->30); add: (#creationAuthor->'mt'); add: (#view->ViMorphView); yourself)); add: (#isProperty->false); add: (#next->nil); add: (#label->'Animation'); add: (#iconCode->'nil'); add: (#id->#'5caa8ce0-090b-dc41-baa3-624188233e5f'); add: (#isReference->false); yourself)