steps
step01ee0bd60573124cb84a3d699a2e3263
	<step>

	^ ((Dictionary new) add: (#definition->#'2d4505f2-f723-6c42-ba5b-f3cc0d3c03c7'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'14 December 2015 11:30:58 am'); yourself)); add: (#isProperty->false); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'01ee0bd6-0573-124c-b84a-3d699a2e3263'); add: (#isReference->true); yourself)