steps
step53385c7bcff8c8428efde43b039db34b
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'d387d29c-ec6c-d744-9b76-f0019c974b66').
(#iconCode -> 'nil').
(#id -> #'53385c7b-cff8-c842-8efd-e43b039db34b').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 November 2013 5:07:13 pm').
(#priority -> 4490)}))})