steps
step1b33173f22e52e40a2da55d68ca21ac8
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'b9f8c25a-20b9-5146-a00e-d518fa163d93').
(#iconCode -> 'nil').
(#id -> #'1b33173f-22e5-2e40-a2da-55d68ca21ac8').
(#label -> nil).
(#next -> #'66e483d2-5312-9349-bb3e-4742bac11240').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Protocol').
(#labelColor -> '#AAAAAA').
(#priority -> 2270)}))})