steps
stepe12b2fbe9eec2c4d90cd9cddd8d57668
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'4c51ca21-654b-ac4d-9005-d94684f62695').
(#iconCode -> 'nil').
(#id -> #'e12b2fbe-9eec-2c4d-90cd-9cddd8d57668').
(#isProperty -> false).
(#isReference -> true).
(#label -> nil).
(#next -> #'d82ec0a6-a967-514a-953c-27fcb67ec3d3').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:12.337834 pm')}))})