steps
step5b3d233ec93c0b42b8bafafb41d70a9e
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'9ff42a61-06de-db4f-8bde-f07db577c02f').
(#iconCode -> 'nil').
(#id -> #'5b3d233e-c93c-0b42-b8ba-fafb41d70a9e').
(#label -> nil).
(#next -> #'35e3497e-2aff-7d4a-a4e9-6ab0b798b3ed').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 2820)}))})