steps
steped1b8e40bde84443972aed9b1112c7e0
	<step>

	^ (Dictionary newFrom: {
(#'_def' -> (Dictionary newFrom: {
(#block -> [:in :out | out addAll: in]).
(#className -> #ViScriptDefinition).
(#id -> #'35817d04-0159-944e-94be-3b7a22e5a89c').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:11.324834 pm')
})).
(#sourceCode -> '[:in :out | out addAll: in]')
})).
(#className -> #ViScriptStep).
(#definition -> #'35817d04-0159-944e-94be-3b7a22e5a89c').
(#iconCode -> 'nil').
(#id -> #'ed1b8e40-bde8-4443-972a-ed9b1112c7e0').
(#isProperty -> false).
(#label -> nil).
(#next -> #'ded083c3-3dd2-f04a-96cf-46c7dfe608dc').
(#properties -> (Dictionary newFrom: {
(#after -> #(#groupsMinimal)).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:11.324834 pm')
}))
})