steps
stepa58a2d7b43281740a7b5288db0764a2b
	<step>

	^ ((Dictionary new) add: (#definition->#'80e4df8f-da7e-e94c-b861-23e0e23d386d'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 October 2015 2:07 pm'); add: (#copyOf->#'012db9f4-4e1e-cc49-aa55-265d82592ec7'); yourself)); add: (#isProperty->true); add: (#next->#'b15f906e-0d17-994c-9585-d7487285b6d2'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'a58a2d7b-4328-1740-a7b5-288db0764a2b'); add: (#isReference->false); yourself)