steps
step70f2866cc1934849bbc6734357c4521f
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'2909f9fe-4d35-8542-b0da-49fa6a8b6a35').
(#iconCode -> 'nil').
(#id -> #'70f2866c-c193-4849-bbc6-734357c4521f').
(#isProperty -> false).
(#isReference -> false).
(#label -> 'Script Objects').
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #identity).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 1:01:49 pm').
(#priority -> 6590).
(#view -> ViTreeViewExtended)}))})