steps
stepe4cedfc134196a46a30665067830a9bf
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'af03fa7c-bf5f-1b47-b33f-3937e26398b6').
(#iconCode -> 'nil').
(#id -> #'e4cedfc1-3419-6a46-a306-65067830a9bf').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'90bb3b19-d2be-164e-a306-83db53cee32e').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 5480)}))})