steps
stepab4af50f105f424d95d136bfd2f47ad3
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupStep).
(#definition -> #'49ccd054-1123-b244-8a4b-6541e357ab53').
(#iconCode -> 'nil').
(#id -> #'ab4af50f-105f-424d-95d1-36bfd2f47ad3').
(#label -> nil).
(#next -> #'c2ce4b2e-2257-424b-af73-a84bb479e75c').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 10:18:31 am').
(#priority -> 5020)}))})