steps
stepd65616b9310e3c4d88d4b82f6ff8c6f5
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #iconAndLabel).
(#iconCode -> 'nil').
(#id -> #'d65616b9-310e-3c4d-88d4-b82f6ff8c6f5').
(#label -> nil).
(#next -> #'0e3c9bf8-357e-b245-8da2-33ae912ace9a').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Object').
(#priority -> 3110)}))})