steps
step8d3e35af10d4a3469157f3ad76331d4d
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'ad4d80ac-c0c0-3e47-a673-d51547ce89b8').
(#iconCode -> 'nil').
(#id -> #'8d3e35af-10d4-a346-9157-f3ad76331d4d').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Origin').
(#labelColor -> '#AAAAAA').
(#priority -> 2520)}))})