steps
step59836c629af9f5428a727f3fcdba7f0a
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'cac998b8-e21c-da49-ac93-f204a193cbd9').
(#iconCode -> 'nil').
(#id -> #'59836c62-9af9-f542-8a72-7f3fcdba7f0a').
(#isProperty -> false).
(#isReference -> true).
(#label -> nil).
(#next -> #'ab2beffc-f1ae-014e-a424-a1270d4facd9').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:13.403834 pm')}))})