steps
stepded083c33dd2f04a96cf46c7dfe608dc
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'8a26523b-af6c-b44c-b301-5574cb83e74f').
(#iconCode -> 'nil').
(#id -> #'ded083c3-3dd2-f04a-96cf-46c7dfe608dc').
(#label -> nil).
(#next -> #'14f6246e-2fd7-f947-b063-767bfa454a39').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '20 February 2014 3:45:20 pm').
(#headerText -> 'Read').
(#priority -> 5950)}))})