steps
stepec77d931b152e14d83f0ca3d29ac8796
	<step>

	^ ((Dictionary new) add: (#definition->#'736d0173-87df-b44a-b06a-e1600b6b3dd9'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#isNew->false); add: (#creationTimeStamp->'20 May 2015 2:35:48 pm'); yourself)); add: (#isProperty->true); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'ec77d931-b152-e14d-83f0-ca3d29ac8796'); add: (#isReference->false); yourself)