steps
step85478cdcdec75648b9afbbf1c6a6d389
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'f9974083-86d5-d54f-9ee0-ba85d5b22720').
(#iconCode -> 'nil').
(#id -> #'85478cdc-dec7-5648-b9af-bbf1c6a6d389').
(#label -> nil).
(#next -> #'fa4cb8bf-f5a3-134c-8ce1-40866732e786').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#hAlignment -> #right).
(#labelColor -> '#AAAAAA').
(#priority -> 2220).
(#view -> ViTreeViewExtended)}))})