steps
stepd1d946a9b78e72438d30c08accd864b6
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'bfee3c65-a004-8f47-bd94-d9d92eaee86b').
(#iconCode -> 'nil').
(#id -> #'d1d946a9-b78e-7243-8d30-c08accd864b6').
(#label -> nil).
(#next -> #'d9a22b3c-f29a-7840-bb49-c3f6d664b189').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 4:21:57 pm').
(#headerText -> 'Type').
(#priority -> 3210)}))})