steps
stepc47ab7eb21ab2048a04492202f71989f
	<step>

	^ ((Dictionary new) add: (#definition->#'bfa04c1c-116e-a34f-bda4-f81147cb89d9'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->MethodReference); add: (#priority->300); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'9 December 2015 11:26:37 am'); add: (#view->ViTreeViewExtended); yourself)); add: (#isProperty->false); add: (#next->#'a4597f82-83f5-f145-8733-996443dff441'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'c47ab7eb-21ab-2048-a044-92202f71989f'); add: (#isReference->false); yourself)