steps
step495622065589a546a3dceec92fbc070e
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'5c1958ef-9e37-214f-bf56-900cd00d8b9c').
(#iconCode -> 'nil').
(#id -> #'49562206-5589-a546-a3dc-eec92fbc070e').
(#isProperty -> false).
(#label -> nil).
(#next -> #'28f1d911-a981-d447-b801-226c1b2a529c').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '29 April 2016 6:01:07 pm')}))})