steps
step6b45f38f77e7ee4aac7196c1987498fb
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'a2fbc9b1-b3f2-9d4f-85eb-12128c1679ad').
(#iconCode -> 'nil').
(#id -> #'6b45f38f-77e7-ee4a-ac71-96c1987498fb').
(#isProperty -> false).
(#isReference -> false).
(#label -> 'Empty Objects').
(#next -> #'894088c2-9d24-5b40-9246-2e1a298fe761').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 May 2014 2:58:16 pm').
(#isGlobal -> true).
(#outputKind -> Bag).
(#priority -> 6130).
(#view -> ViTreeViewExtended)}))})