steps
step2d21437b3606d34398725e357a12de36
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQuerySortStep).
(#definition -> #compareObjectsByName).
(#iconCode -> 'nil').
(#id -> #'2d21437b-3606-d343-9872-5e357a12de36').
(#label -> nil).
(#next -> #'f8f2564d-0b66-d645-9646-191f5736dcef').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 2750)}))})