steps
step989369d4032d1d49adaeb70b2f36ea1e
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'ae2d4e1f-0fff-3647-905c-89c71c1c5b06').
(#iconCode -> 'nil').
(#id -> #'989369d4-032d-1d49-adae-b70b2f36ea1e').
(#isProperty -> true).
(#isReference -> false).
(#label -> 'Diff w/ pretty print').
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '24 February 2014 11:02:55 am').
(#inputKind -> CompiledMethod).
(#priority -> 5880).
(#view -> ViTreeViewExtended)}))})