steps
step6b51cd4ec681064ab60de1552154d686
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'a539ca0e-4d70-fe4f-a94a-c06bbbdc25db').
(#iconCode -> 'nil').
(#id -> #'6b51cd4e-c681-064a-b60d-e1552154d686').
(#isProperty -> false).
(#isReference -> true).
(#label -> nil).
(#next -> #'087bc712-e210-1d43-b27c-50a4d240b0ea').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:11.619834 pm')}))})