steps
step0b1978b87b59484281f59f94cce1ec89
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'76130d1c-3734-3d46-a44e-7310846af40e').
(#iconCode -> 'nil').
(#id -> #'0b1978b8-7b59-4842-81f5-9f94cce1ec89').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '17 January 2014 3:23:10 pm').
(#priority -> 4840)}))})