steps
stepfea2b084266a3849818c699ce7e7042e
	<step>

	^ ((Dictionary new) add: (#definition->#'fa4a701a-27a2-fd47-a62c-b5c018b350f6'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'9 December 2015 11:26:37 am'); yourself)); add: (#isProperty->true); add: (#next->#'51b916eb-489b-fe4b-a058-2713f79eca04'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'fea2b084-266a-3849-818c-699ce7e7042e'); add: (#isReference->false); yourself)