steps
step157a5c4cd1a5cf4abced696f7e70934d
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'6d65793d-81a2-4342-bdd9-35a1e8b2f927').
(#iconCode -> 'nil').
(#id -> #'157a5c4c-d1a5-cf4a-bced-696f7e70934d').
(#label -> nil).
(#next -> #'fb20347b-7a6f-be43-bd78-88492dc2d4b1').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 September 2013 4:34:58 pm').
(#priority -> 3710).
(#view -> ViTreeViewExtended)}))})