steps
stepc7876b21782a494488e1399e5e82d6b5
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'8b1b3117-02c1-e140-a210-b0fc8a71e54a').
(#iconCode -> 'nil').
(#id -> #'c7876b21-782a-4944-88e1-399e5e82d6b5').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'14e205f5-0445-584a-8c5f-729f6226210c').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '29 May 2018 9:28:47 am').
(#inputKind -> #(nil nil ))}))})