steps
step40361e300f77964fb3b5a7fb7cc955d9
	<step>

	^ (Dictionary newFrom: {
(#'_def' -> (Dictionary newFrom: {
(#block -> [:in :out | out addAll: in]).
(#className -> #ViScriptDefinition).
(#id -> #'8e8afd87-a8ec-b048-bf33-e99e5d6f9484').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:12.890834 pm')
})).
(#sourceCode -> '[:in :out | out addAll: in]')
})).
(#className -> #ViScriptStep).
(#definition -> #'8e8afd87-a8ec-b048-bf33-e99e5d6f9484').
(#iconCode -> 'nil').
(#id -> #'40361e30-0f77-964f-b3b5-a7fb7cc955d9').
(#isProperty -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#after -> #(#'ef81aed0-ae2d-6548-904f-030b28e12e97')).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '29 March 2019 5:00:11.33835 pm')
}))
})