steps
step5406f229d72e9840a58dc61752a3b24a
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'5b769677-da05-e745-88b8-1321cef197a9').
(#iconCode -> 'nil').
(#id -> #'5406f229-d72e-9840-a58d-c61752a3b24a').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'578f3d1f-bdb5-b04b-85ff-fe0c848c6af5').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 September 2013 3:49:48 pm').
(#headerText -> 'Line').
(#labelColor -> '000000').
(#priority -> 4030)}))})