steps
stepee9363991409634c81ff0389658bb3ce
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'188219f8-61bc-014f-aba1-8a8ba9a79756').
(#iconCode -> 'nil').
(#id -> #'ee936399-1409-634c-81ff-0389658bb3ce').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '6 December 2013 5:17:12 pm').
(#priority -> 4560)}))})