steps
stepfd3c0b79142aee4e9f274da12eba946f
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQuerySortStep).
(#definition -> #'12f30814-5104-df41-8cad-fee1eb31343d').
(#iconCode -> 'nil').
(#id -> #'fd3c0b79-142a-ee4e-9f27-4da12eba946f').
(#label -> nil).
(#next -> #'cf18cd02-0e0b-344c-a7ee-82358865b598').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'fd3c0b79-142a-ee4e-9f27-4da12eba946f').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 September 2013 7:00:36 pm').
(#priority -> 3360)}))})