steps
stepc17a5204307f044bb7845a13673d0684
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'a12aae2c-4046-a943-95a7-6af0c90ad490').
(#iconCode -> 'nil').
(#id -> #'c17a5204-307f-044b-b784-5a13673d0684').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '15 September 2013 5:43:59 pm').
(#priority -> 3580)}))})