steps
step6f505e41acfd5d4fada277cdc48e1601
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #iconAndLabel).
(#iconCode -> 'nil').
(#id -> #'6f505e41-acfd-5d4f-ada2-77cdc48e1601').
(#label -> nil).
(#next -> #'6db1e613-5156-9940-b0a6-eb4acb825df1').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Sender').
(#priority -> 1480)}))})