steps
step57addd329f038e449c7146497f3e7209
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #iconAndLabel).
(#iconCode -> 'nil').
(#id -> #'57addd32-9f03-8e44-9c71-46497f3e7209').
(#label -> nil).
(#next -> #'736c2491-39ee-9f4c-9abc-4d4c87ef1a03').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #defaultProperties).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 4930)}))})