steps
step1cd2a5a305f390468fd206f0a076f80b
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'772cc5f9-cfec-4f49-9902-686bc54662cf').
(#iconCode -> 'nil').
(#id -> #'1cd2a5a3-05f3-9046-8fd2-06f0a076f80b').
(#label -> nil).
(#next -> #'0166bc3d-c272-b14b-97b8-2735b475543c').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 2800)}))})