steps
stepfa3a3d8c6bcbec4a8af22ee1195bbafe
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'c634d795-89e7-0249-88d2-e94f6ad48bba').
(#iconCode -> 'nil').
(#id -> #'fa3a3d8c-6bcb-ec4a-8af2-2ee1195bbafe').
(#isProperty -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#after -> #(#inheritance)).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '1 February 2016 2:17:14 pm')
}))
})