steps
step181275cdbd0c36429b0d9373d885260e
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'80f0269f-b617-f943-859a-aa2c5674a5f4').
(#iconCode -> 'nil').
(#id -> #'181275cd-bd0c-3642-9b0d-9373d885260e').
(#isProperty -> false).
(#label -> nil).
(#next -> #'708f87dc-3282-814f-a2af-e89060b27f1b').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 2840)}))})