steps
step80d8228dc6ed17448301762c72d90211
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'e30bd6d0-ea56-c045-ac85-bf39bbf4bdee').
(#iconCode -> 'nil').
(#id -> #'80d8228d-c6ed-1744-8301-762c72d90211').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'086c5944-1e51-2c4d-8e17-9ee9bffc0d2a').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'d9634b11-bde6-1a40-a0b4-7be880afc37a').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 4820)}))})