steps
stepc8d02930561846449d24456f53f464bc
	<step>

	^ ((Dictionary new) add: (#definition->#'0f9ac2ef-3c10-1e4d-b61f-4780483b5f29'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'15 June 2015 10:20:57 am'); add: (#copyOf->#'57ef0b8f-46a4-1744-80b4-6974ec1adc76'); yourself)); add: (#isProperty->false); add: (#next->#'ed5b130b-8850-004d-a2e4-fa5157edc3b8'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'c8d02930-5618-4644-9d24-456f53f464bc'); add: (#isReference->false); yourself)