steps
step240cc4b3dcec8c4ebbe829ff7c118338
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'60127c92-d0d0-f544-8437-975ef4eeb195').
(#iconCode -> 'nil').
(#id -> #'240cc4b3-dcec-8c4e-bbe8-29ff7c118338').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '9 January 2014 11:34:40 am').
(#priority -> 4620)}))})