steps
stepdebuggerBindings
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'1c0a54ab-f2e4-7747-a0b9-5b9444e5d0dd').
(#iconCode -> 'UiFugueIcons blockIcon').
(#id -> #debuggerBindings).
(#isProperty -> false).
(#label -> 'Bindings').
(#next -> #'89162c9a-8847-4744-abdb-1031a61c2898').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 430).
(#view -> ViTreeViewExtended)}))})