steps
stepe81669edebe0c84e95e77ac5889d8779
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'23fed4d2-1ab1-5f4d-88fe-906f5906f308').
(#iconCode -> 'nil').
(#id -> #'e81669ed-ebe0-c84e-95e7-7ac5889d8779').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'e81669ed-ebe0-c84e-95e7-7ac5889d8779').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '3 September 2013 1:56:59 pm').
(#inputKind -> ViAbstractQueryPart).
(#priority -> 980)}))})