steps
stepc31cf538fe894242bd60cf299527d31f
	<step>

	^ ((Dictionary new) add: (#definition->#'e64a1338-3b92-4a46-a650-cd9b6c5ca8dc'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'22 July 2015 9:48:05 am'); yourself)); add: (#isProperty->false); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'c31cf538-fe89-4242-bd60-cf299527d31f'); add: (#isReference->true); yourself)