steps
step63c840019d52ee47b4a7446b7242ea74
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'b7a301c0-bb5c-a14f-a13d-b6e45ed4d473').
(#iconCode -> 'nil').
(#id -> #'63c84001-9d52-ee47-b4a7-446b7242ea74').
(#label -> nil).
(#next -> #'dfb2af53-c012-e14a-ae23-1ee9009c0034').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 3050)}))})