steps
stepe67a3ef77a93634e86af5740774f3bb9
	<step>

	^ ((Dictionary new) add: (#definition->#'1d5b5851-231c-fb4e-80df-f487c7e36540'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'20 May 2015 12:09:54 pm'); yourself)); add: (#isProperty->false); add: (#next->#'97b22eff-73d8-4746-b877-4dc3d77e1208'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'e67a3ef7-7a93-634e-86af-5740774f3bb9'); add: (#isReference->false); yourself)