steps
stepad40279566daaa47aa37eb2e5d035363
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'9ee998ec-877c-bb4f-9a00-1f268163aaa5').
(#iconCode -> 'nil').
(#id -> #'ad402795-66da-aa47-aa37-eb2e5d035363').
(#isProperty -> false).
(#label -> 'All test classes').
(#next -> #'94740283-5bf2-514e-8eef-b18ce867137a').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 February 2014 12:43:11 pm').
(#isGlobal -> true).
(#outputKind -> Behavior).
(#priority -> 5230).
(#view -> ViTreeViewExtended)}))})