steps
step1fb44024f23f3244bc57a9be90f3ccdb
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'68e5d13a-ced8-2246-bed5-463df2170ccb').
(#iconCode -> 'nil').
(#id -> #'1fb44024-f23f-3244-bc57-a9be90f3ccdb').
(#isProperty -> false).
(#isReference -> true).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '15 December 2015 10:40:06 am')}))})