steps
step08b44027bc56f8449826f94859a5b557
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'9ed0d382-3615-0649-aedc-88c3288cebbd').
(#iconCode -> 'nil').
(#id -> #'08b44027-bc56-f844-9826-f94859a5b557').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '5 June 2014 5:03:50 pm').
(#priority -> 6430)}))})