steps
stepcb3aaeaa1407b74d8f5e8838680974b5
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'c3d14c30-79e4-7e49-976d-60b6548c297e').
(#iconCode -> 'nil').
(#id -> #'cb3aaeaa-1407-b74d-8f5e-8838680974b5').
(#label -> 'Bookmarks').
(#next -> #'acccd738-5017-5e44-ba68-cc46761670dc').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '20 May 2014 11:59:48 am').
(#priority -> 6090).
(#view -> ViTreeViewExtended)}))})