steps
stepe6cb8658369738499a2cfae04d157f52
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'4184f17b-2fd8-da49-bf5b-1d66f0c421df').
(#iconCode -> 'nil').
(#id -> #'e6cb8658-3697-3849-9a2c-fae04d157f52').
(#isProperty -> false).
(#isReference -> true).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '29 March 2019 5:00:11.34035 pm')}))})