steps
step2d49b98d3f27e14faaa8aee4706a6a0a
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'e2b4597c-c351-224e-86de-ee5cb0cff6b5').
(#iconCode -> 'nil').
(#id -> #'2d49b98d-3f27-e14f-aaa8-aee4706a6a0a').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#labelColor -> '#AAAAAA').
(#priority -> 2480)}))})