steps
stepoutline
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'e50b9af1-42f0-5a44-ba3d-be27b8cb0fdf').
(#iconCode -> 'nil').
(#id -> #outline).
(#isProperty -> false).
(#label -> 'Outline').
(#next -> #'dd56b3e9-9e71-b44e-9a60-5319116f9cdd').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '12 May 2015 4:39:25 pm').
(#inputKind -> ClassDescription).
(#notifier -> ViSystemChangeNotifier).
(#orientation -> #default).
(#priority -> 40).
(#view -> ViTreeViewExtended)}))})