steps
stepb3a5a8de9e73f64da9603946a4e8fbe5
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'86393cf7-e7c5-e54d-a0ed-a9bad31b33d1').
(#iconCode -> 'nil').
(#id -> #'b3a5a8de-9e73-f64d-a960-3946a4e8fbe5').
(#label -> nil).
(#next -> #'e44e7438-eba5-7344-8590-a778889ab428').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 10:20:51 am').
(#labelColor -> #AAAAAA).
(#priority -> 5040)}))})