steps
stepacc3ad3129c9cd458ccce801aaadd858
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'f6032f7a-baab-7446-9764-e0f1e97f6d34').
(#iconCode -> 'nil').
(#id -> #'acc3ad31-29c9-cd45-8ccc-e801aaadd858').
(#label -> nil).
(#next -> #'cdbe8071-be1b-984e-b62a-2c1b721153c0').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 September 2013 7:46:49 pm').
(#priority -> 3910)}))})