steps
stepdebuggerBindings
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'4f4a5855-cc44-7948-bb20-0381aae59f41').
(#iconCode -> 'UiFugueIcons blockIcon').
(#id -> #debuggerBindings).
(#label -> 'Bindings').
(#next -> #'89162c9a-8847-4744-abdb-1031a61c2898').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 430)}))})