steps
stepd1fc3ac8c0bbcf47955a7e0b24221803
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'5048347c-a13d-fb4a-8309-562b9f9b5478').
(#iconCode -> 'nil').
(#id -> #'d1fc3ac8-c0bb-cf47-955a-7e0b24221803').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'1bb6538b-c256-b34b-958e-5996dea59092').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 5500)}))})