steps
step57addd329f038e449c7146497f3e7209
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'17258eb1-1b3f-474d-9bee-ade709e6d9ad').
(#iconCode -> 'nil').
(#id -> #'57addd32-9f03-8e44-9c71-46497f3e7209').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'736c2491-39ee-9f4c-9abc-4d4c87ef1a03').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 4930)}))})