steps
step61afd65ed9435642bd3115492112b6ad
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'41e28d6b-077d-474b-b28a-e30838864205').
(#iconCode -> 'nil').
(#id -> #'61afd65e-d943-5642-bd31-15492112b6ad').
(#label -> nil).
(#next -> #'bf2d198a-d977-ed49-86f9-225cbfd68155').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 January 2014 4:32:08 pm').
(#priority -> 4760)}))})