steps
step358482e02cf1e948a6570a354613e3ad
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupSortStep).
(#definition -> #'2ef099b5-ca0a-3a4e-934e-823156b061a9').
(#iconCode -> 'nil').
(#id -> #'358482e0-2cf1-e948-a657-0a354613e3ad').
(#label -> nil).
(#next -> #'ab2beffc-f1ae-014e-a424-a1270d4facd9').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 2500)}))})