steps
step8d3e35af10d4a3469157f3ad76331d4d
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'87d65ab2-c8f8-bf48-b6d4-8c0ef92a7673').
(#iconCode -> 'nil').
(#id -> #'8d3e35af-10d4-a346-9157-f3ad76331d4d').
(#isProperty -> true).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Origin').
(#labelColor -> '#AAAAAA').
(#priority -> 2520)}))})