steps
step37e691f67120684bbf420c4cb40440b1
	<step>

	^ ((Dictionary new) add: (#definition->#'4847dd58-68b2-864d-94ae-889117f97643'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->Object); add: (#priority->500); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'9 December 2015 11:55:27 am'); add: (#view->ViTreeView); yourself)); add: (#isProperty->false); add: (#next->#'ba4b7a9c-c7c9-5145-a45e-2cdf2b0a3940'); add: (#label->'Vocabulary'); add: (#iconCode->'nil'); add: (#id->#'37e691f6-7120-684b-bf42-0c4cb40440b1'); add: (#isReference->false); yourself)