steps
stepa34edfe9887173439abcb10f76365684
	<step>

	^ ((Dictionary new) add: (#definition->#'6975eef0-4e5f-5542-b7b0-e35b1872410b'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->520); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'9 September 2013 11:55:52 am'); yourself)); add: (#id->#'a34edfe9-8871-7343-9abc-b10f76365684'); add: (#iconCode->'UiFugueIcons arrowStepIcon'); add: (#next->#'47ebfeaf-f6ff-624a-8fc6-078f452527db'); add: (#label->'References'); yourself)