steps
stepe68d82d70f825e4f990d0b292c42da7f
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'7cd85634-af2e-024a-b9bd-4efef21f461d').
(#iconCode -> 'nil').
(#id -> #'e68d82d7-0f82-5e4f-990d-0b292c42da7f').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 November 2013 4:20:43 pm').
(#priority -> 4420)}))})