steps
step601f4f4795450e4eabefe7b5dc4c0c3e
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'6791d9d6-2faf-3448-8e22-0aa4c948acdc').
(#iconCode -> 'nil').
(#id -> #'601f4f47-9545-0e4e-abef-e7b5dc4c0c3e').
(#label -> nil).
(#next -> #'6900ffdc-8414-5f4a-bab9-9602bbf21fae').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 February 2014 4:31:11 pm').
(#priority -> 5670)}))})