steps
stepad40279566daaa47aa37eb2e5d035363
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'07e0d51c-6985-144c-bc8d-08c8e9bb8d4d').
(#iconCode -> 'nil').
(#id -> #'ad402795-66da-aa47-aa37-eb2e5d035363').
(#label -> 'All test classes').
(#next -> #'94740283-5bf2-514e-8eef-b18ce867137a').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 February 2014 12:43:11 pm').
(#priority -> 5230).
(#view -> ViTreeViewExtended)}))})