steps
step767345095fc32841a506a361aa9446c4
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'ff90c055-cbd6-794d-8d17-4f11adb2bd9a').
(#iconCode -> 'nil').
(#id -> #'76734509-5fc3-2841-a506-a361aa9446c4').
(#isProperty -> false).
(#label -> nil).
(#next -> #'67636419-4db6-8c43-aa22-b3948e02e796').
(#properties -> (Dictionary newFrom: {
(#after -> #(#groupsMinimal)).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:12.484834 pm')
}))
})