steps
step82277b8f15e6124f96d40a482e6e0aab
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'72345acc-63d9-a649-9a3c-a8e82b0f7f94').
(#iconCode -> 'nil').
(#id -> #'82277b8f-15e6-124f-96d4-0a482e6e0aab').
(#isProperty -> false).
(#label -> nil).
(#next -> #'3949844d-11c6-dd41-b185-b338c3ca4dac').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 September 2013 6:14:18 pm').
(#outputKind -> Boolean).
(#priority -> 3750)}))})