steps
step8541e0243a147d4a9ac55c521a7c4f27
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'399a97f5-613f-be4e-a73c-ac19a0a147e6').
(#iconCode -> 'nil').
(#id -> #'8541e024-3a14-7d4a-9ac5-5c521a7c4f27').
(#isProperty -> false).
(#label -> 'Outline (w/ LOC categories)').
(#next -> #'f128659b-7f02-364d-afc1-143f418bf135').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#inputKind -> ClassDescription).
(#outputKind -> CompiledMethod).
(#priority -> 5140).
(#view -> ViTreeViewExtended)
}))
})