steps
step8729d44582f27f4dabfa8044a4165d7f
	<step>

	^ (Dictionary newFrom: {
(#'_def' -> (Dictionary newFrom: {
(#block -> [:in :out | out addAll: in]).
(#className -> #ViScriptDefinition).
(#id -> #'3db9e05c-a8c5-5d4f-aca8-c7191361aa1a').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:11.442834 pm')
})).
(#sourceCode -> '[:in :out | out addAll: in]')
})).
(#className -> #ViScriptStep).
(#definition -> #'3db9e05c-a8c5-5d4f-aca8-c7191361aa1a').
(#iconCode -> 'nil').
(#id -> #'8729d445-82f2-7f4d-abfa-8044a4165d7f').
(#isProperty -> false).
(#label -> nil).
(#next -> #'45fb3a38-39dc-2144-a747-a51f5e49f729').
(#properties -> (Dictionary newFrom: {
(#after -> #(#groupsMinimal)).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:11.442834 pm')
}))
})