steps
step71ddcad37128514caaa79edb1e6953b8
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'1198e55b-a78e-6842-8a27-3a6403912dca').
(#iconCode -> 'nil').
(#id -> #'71ddcad3-7128-514c-aaa7-9edb1e6953b8').
(#label -> 'Method tags').
(#next -> #'d5db789c-076f-b740-9144-a2bd2740df7f').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #identity).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 1:01:49 pm').
(#priority -> 5750)}))})