steps
step322c353db95327439b11f8c0ae4041b1
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'27c95d08-e21a-5347-ab59-c725e38f7fef').
(#iconCode -> 'nil').
(#id -> #'322c353d-b953-2743-9b11-f8c0ae4041b1').
(#isProperty -> true).
(#label -> nil).
(#next -> #'7d7f7d20-939a-7c4e-9a80-1915e705d82e').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Origin').
(#labelColor -> '#AAAAAA').
(#priority -> 3080)
}))
})