steps
stepbec0a4efc091a84488efbe4ea489648e
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #allMethodsForClass).
(#iconCode -> 'nil').
(#id -> #'bec0a4ef-c091-a844-88ef-be4ea489648e').
(#label -> 'Methods').
(#next -> #'dd7cc162-78d3-5946-8ad0-7e30f7b46f6d').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'bec0a4ef-c091-a844-88ef-be4ea489648e').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 100)}))})