steps
step8c98b390c0ff494e94e4be9cfaeea24c
	<step>

	^ ((Dictionary new) add: (#definition->#'c199aae4-73d9-5746-9016-4e66df9f6434'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'9 December 2015 11:55:27 am'); yourself)); add: (#isProperty->false); add: (#next->#'35047111-f49d-8b4e-bfe1-21c59e369af2'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'8c98b390-c0ff-494e-94e4-be9cfaeea24c'); add: (#isReference->false); yourself)