steps
step46817f32e66b9342a3adabe14e9713c9
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'8f1f4f52-b29d-3946-94c0-c84409867443').
(#iconCode -> 'nil').
(#id -> #'46817f32-e66b-9342-a3ad-abe14e9713c9').
(#label -> 'Methods by Author').
(#next -> #'51d8a538-95c9-ce4b-9e21-ac726be7665b').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 November 2013 3:50:08 pm').
(#priority -> 4370)}))})