steps
stepefdca18a20725c45ac9255b2a17ad4eb
	<step>

	^ (Dictionary newFrom: {
(#'_def' -> (Dictionary newFrom: {
(#block -> [:in :out | out addAll: in]).
(#className -> #ViScriptDefinition).
(#id -> #'0c8f9b64-ae23-9e4a-b4c8-7fbd8f29d864').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '9 December 2015 10:14:14 am')
})).
(#sourceCode -> '[:in :out | out addAll: in]')
})).
(#className -> #ViScriptStep).
(#definition -> #'0c8f9b64-ae23-9e4a-b4c8-7fbd8f29d864').
(#iconCode -> 'nil').
(#id -> #'efdca18a-2072-5c45-ac92-55b2a17ad4eb').
(#isProperty -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#after -> #(#outline)).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '9 December 2015 10:14:14 am')
}))
})