steps
step58fabb91d27b8e47b2080f6ee4958df1
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'2123e223-61ff-2145-856f-1a7f64283322').
(#iconCode -> 'nil').
(#id -> #'58fabb91-d27b-8e47-b208-0f6ee4958df1').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'19aa31e9-da2d-0646-bcb5-c43217a64c10').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#inputKind -> Array).
(#priority -> 640).
(#view -> ViTreeViewExtended)}))})