steps
stepd96e910adf735a4cb7608811fac45378
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'1d6bdedc-fe37-864b-8af7-6847c2ec88a1').
(#iconCode -> 'nil').
(#id -> #'d96e910a-df73-5a4c-b760-8811fac45378').
(#isProperty -> true).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#hAlignment -> #left).
(#headerText -> 'Origin').
(#itemOrientation -> #horizontalMaxHeight).
(#priority -> 2570).
(#vAlignment -> #top)
}))
})