steps
stepedcd89de8046a844bfdec7aca99dba50
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'6f431f2f-fd85-3841-a679-a7cb8348ba6f').
(#iconCode -> 'UiFugueIcons categoryIcon').
(#id -> #'edcd89de-8046-a844-bfde-c7aca99dba50').
(#label -> 'Categories').
(#next -> #'e9f4b617-ab3a-cd41-9a5b-9f547aa04c9d').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 90).
(#view -> ViTreeViewExtended)}))})