steps
stepe957bc9e51f13b4eac097f23d6c54160
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #identity).
(#iconCode -> 'nil').
(#id -> #'e957bc9e-51f1-3b4e-ac09-7f23d6c54160').
(#label -> 'Commands').
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #identity).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 1:01:49 pm').
(#priority -> 6450)}))})