steps
step56d4e61dee76514bbc24e352a53b0d46
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupStep).
(#definition -> #'66cd48ee-25f8-f845-b648-77d9a1ca2dfe').
(#iconCode -> 'nil').
(#id -> #'56d4e61d-ee76-514b-bc24-e352a53b0d46').
(#label -> nil).
(#next -> #'358482e0-2cf1-e948-a657-0a354613e3ad').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 2490)}))})