steps
step3eddb241953313498650c86422ca0395
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQuerySortStep).
(#definition -> #compareObjectsBySelector).
(#iconCode -> 'nil').
(#id -> #'3eddb241-9533-1349-8650-c86422ca0395').
(#label -> nil).
(#next -> #'070104b0-18c4-7348-bdce-375fa5dbc93c').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 2640)}))})