steps
stepacccd73850175e44ba68cc46761670dc
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'33ed3fa1-213a-bf45-8092-90ada0211906').
(#iconCode -> 'nil').
(#id -> #'acccd738-5017-5e44-ba68-cc46761670dc').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '20 May 2014 12:01:18 pm').
(#priority -> 6100)}))})