steps
stepdebuggerStack
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'d89728bf-0d8f-1143-9a93-e4a1aad379f4').
(#iconCode -> 'nil').
(#id -> #debuggerStack).
(#label -> 'Suspended context').
(#next -> #'2fdb319c-765a-1a43-863e-792e14de2c1e').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #defaultProperties).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 570)}))})