steps
step65a025ef589eed41bba54b8135bf3ba9
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'0fa14eda-ce75-1248-9b4f-e75d404c3e3d').
(#iconCode -> 'nil').
(#id -> #'65a025ef-589e-ed41-bba5-4b8135bf3ba9').
(#isProperty -> false).
(#label -> nil).
(#next -> #'68476311-41ac-3445-9df5-321d8834e6f7').
(#properties -> (Dictionary newFrom: {
(#after -> #(#groupsMinimal)).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:12.527834 pm')
}))
})