steps
step2defa63a99915e4285200d0db861b77c
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupSortStep).
(#definition -> #compareObjectsAsStrings).
(#iconCode -> 'nil').
(#id -> #'2defa63a-9991-5e42-8520-0d0db861b77c').
(#label -> nil).
(#next -> #'e66f7ebe-27a3-584f-836c-ee4cf8041d8b').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 2000)}))})