steps
step85478cdcdec75648b9afbbf1c6a6d389
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'6a9de74b-baf2-2449-82f0-0e7dfe4af645').
(#iconCode -> 'nil').
(#id -> #'85478cdc-dec7-5648-b9af-bbf1c6a6d389').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'fa4cb8bf-f5a3-134c-8ce1-40866732e786').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#hAlignment -> #right).
(#labelColor -> '#AAAAAA').
(#priority -> 2220).
(#view -> ViTreeViewExtended)}))})