steps
stepfd62bf2f377ce64ab62a4f2399a054e1
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupStep).
(#definition -> #'236a8c89-659c-5349-a716-fd2bed0f7486').
(#iconCode -> 'nil').
(#id -> #'fd62bf2f-377c-e64a-b62a-4f2399a054e1').
(#label -> nil).
(#next -> #'9cef732f-20e3-884c-8e5f-55e415a20f91').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1210)}))})