steps
step3d016ef80310db4f87895b9171c48227
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'8c0ac0a2-9769-c841-abfe-99b3700b8070').
(#iconCode -> 'nil').
(#id -> #'3d016ef8-0310-db4f-8789-5b9171c48227').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'71efc7d9-c3cb-7246-9652-6b74bc022b8e').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '9 April 2019 6:30:38.572982 pm')}))})