steps
step0d396a44b27ef545a69dd25485dfe138
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'07db93e4-9707-644c-8344-528719c82bd1').
(#iconCode -> 'nil').
(#id -> #'0d396a44-b27e-f545-a69d-d25485dfe138').
(#label -> nil).
(#next -> #'73c14db0-5129-5543-9fe9-dab9298595fb').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 February 2014 4:24:55 pm').
(#priority -> 5650)}))})