steps
step35047111f49d8b4ebfe121c59e369af2
	<step>

	^ ((Dictionary new) add: (#definition->#'a58b2a6f-0eb3-2648-b37a-6e73442844b7'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'9 December 2015 11:55:27 am'); yourself)); add: (#isProperty->false); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'35047111-f49d-8b4e-bfe1-21c59e369af2'); add: (#isReference->true); yourself)