steps
stepd70d563fbdd718429175cf758450e227
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'8287f41b-826f-0247-b83e-45b6688f9d76').
(#iconCode -> 'UiSilkIcons folderIcon').
(#id -> #'d70d563f-bdd7-1842-9175-cf758450e227').
(#label -> 'Files & Folders').
(#next -> #'6094f78a-9d34-d844-8e98-bc414b414eb2').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 330)}))})