steps
step888352182a2edf43a18522dadbdc15d2
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'ac630cc7-c5d7-d840-9593-845690f6bb00').
(#iconCode -> 'nil').
(#id -> #'88835218-2a2e-df43-a185-22dadbdc15d2').
(#isProperty -> false).
(#label -> nil).
(#next -> #'34d74f03-9769-6140-afa3-e3b7a3f2cd59').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '9 December 2015 10:56:04 am').
(#help -> 'Type something...').
(#isGlobal -> true).
(#priority -> 5000).
(#view -> ViLineEdit)
}))
})