steps
step6d55d7d63c09b044b03a0105386e67a4
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'b0a98b49-85a1-d74b-b2e4-90c3298e1081').
(#iconCode -> 'nil').
(#id -> #'6d55d7d6-3c09-b044-b03a-0105386e67a4').
(#isProperty -> false).
(#label -> nil).
(#next -> #'3dbca45d-ef24-5e49-975e-38f04a9a7729').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '4 October 2013 6:33:02 pm').
(#priority -> 4500).
(#view -> ViTreeViewExtended)
}))
})