steps
stepe55220907365c4428d1594253ec1d77e
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupSortStep).
(#definition -> #compareObjectsAsStrings).
(#iconCode -> 'nil').
(#id -> #'e5522090-7365-c442-8d15-94253ec1d77e').
(#label -> nil).
(#next -> #'2b3d7c04-cf7f-9243-b02d-95fc7b500018').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1320)}))})