steps
step3a028d6521d5c7409ce22d16d0b47a42
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'1ceed05f-3e46-bb44-863a-75e15728b9af').
(#iconCode -> 'nil').
(#id -> #'3a028d65-21d5-c740-9ce2-2d16d0b47a42').
(#isProperty -> false).
(#label -> nil).
(#next -> #'b3b87871-7516-5049-b092-72ad966f3216').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '23 July 2014 3:01:21 pm').
(#isGlobal -> true).
(#outputKind -> ViScriptOrganizer).
(#priority -> 6660).
(#view -> ViTreeViewExtended)
}))
})