steps
stepff9ce8ad7d0d4744afbaf53a7a933bd9
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupStep).
(#definition -> #'52e3e131-1ce2-6941-86f6-ba307bf8e791').
(#iconCode -> 'nil').
(#id -> #'ff9ce8ad-7d0d-4744-afba-f53a7a933bd9').
(#label -> nil).
(#next -> #'11f0e878-14f5-b147-a1c6-e95064e1a62a').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '20 February 2014 6:28:37 pm').
(#priority -> 5770)}))})