steps
step5d53db968bb9fb43921cfbcba4297063
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupSortStep).
(#definition -> #compareObjectsAsStrings).
(#iconCode -> 'nil').
(#id -> #'5d53db96-8bb9-fb43-921c-fbcba4297063').
(#label -> nil).
(#next -> #'64328701-00b2-654e-a369-98b5ecac31fd').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 November 2013 5:01:12 pm').
(#priority -> 4450)}))})