steps
step2fdb319c765a1a43863e792e14de2c1e
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'a9a2b6a9-705b-9347-bad3-3abd6d56975c').
(#iconCode -> 'nil').
(#id -> #'2fdb319c-765a-1a43-863e-792e14de2c1e').
(#label -> nil).
(#next -> #'e1378983-156c-1d4a-88b1-eae6654e7fb0').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '12 November 2013 5:16:28 pm').
(#priority -> 4290).
(#view -> ViTreeViewExtended)}))})