steps
step1d71708a545679429c1cc6c37baec8c9
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'89840f33-9922-7b41-aa52-38aa526f3aaa').
(#iconCode -> 'nil').
(#id -> #'1d71708a-5456-7942-9c1c-c6c37baec8c9').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 February 2014 4:12:57 pm').
(#priority -> 5940)}))})