steps
stepd5cb07566c54dd4da1181174174246ff
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'551413ab-6968-7f47-8cba-689cdf389704').
(#iconCode -> 'nil').
(#id -> #'d5cb0756-6c54-dd4d-a118-1174174246ff').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'3f2ccc8f-3fd6-2243-b5e4-1a2f686ed9bc').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 1:01:49 pm').
(#inputKind -> Context).
(#outputKind -> CompiledMethod).
(#priority -> 5840).
(#view -> ViTreeViewExtended)}))})