steps
stepa8227c3d4a3a76458c9c09a52524ccbc
	<step>

	^ ((Dictionary new) add: (#definition->#'1ffcc481-1d37-ca47-802f-a4783a24e092'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->Morph); add: (#priority->600); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'15 December 2015 10:39:29 am'); add: (#view->ViTreeViewExtended); yourself)); add: (#isProperty->false); add: (#next->#'494f08ea-fbe5-8341-b949-c5ac1b22c09b'); add: (#label->'Layout properties'); add: (#iconCode->'nil'); add: (#id->#'a8227c3d-4a3a-7645-8c9c-09a52524ccbc'); add: (#isReference->false); yourself)