steps
stepc9ff51f897e3cf46ba3f4d71325c942d
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #subclasses).
(#iconCode -> 'nil').
(#id -> #'c9ff51f8-97e3-cf46-ba3f-4d71325c942d').
(#label -> nil).
(#next -> #'962950ed-4ad4-244b-9e1b-512547f2422f').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 2150)}))})