steps
step4bab61711c6c504b98ae553b38d3d886
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'1a63b3b5-dd5b-c242-b723-24e2fb3768d7').
(#iconCode -> 'nil').
(#id -> #'4bab6171-1c6c-504b-98ae-553b38d3d886').
(#label -> nil).
(#next -> #'0d9ec3b0-a6f2-3642-a305-d1b6a7827856').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'f4803742-eb44-0846-9085-92c09d525159').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '6 September 2013 8:28:17 pm').
(#priority -> 4890)}))})