steps
step43770565281690488e6e7364ba7aab35
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQuerySortStep).
(#definition -> #'3a43e006-f8b9-6c4b-8214-c5f909d653f2').
(#iconCode -> 'nil').
(#id -> #'43770565-2816-9048-8e6e-7364ba7aab35').
(#label -> nil).
(#next -> #'94eb9234-d52f-0e4a-81c1-de2c4191893e').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '23 September 2013 4:37:47 pm').
(#priority -> 4080)}))})