steps
step96d77081b7de93458536a0d326322f6e
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'75d09853-4032-ac47-a682-ee8bf116e232').
(#iconCode -> 'UiFugueIcons arrowStepIcon').
(#id -> #'96d77081-b7de-9345-8536-a0d326322f6e').
(#isProperty -> false).
(#isReference -> true).
(#label -> 'References (recursive)').
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '15 September 2013 5:49:24 pm').
(#priority -> 540).
(#view -> ViTreeViewExtended)}))})