steps
step9d1d6fe1e07c9f4a97aa452c1fbcc9af
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'a5322375-d829-bb40-9181-f4ce0b5ec1fd').
(#iconCode -> 'nil').
(#id -> #'9d1d6fe1-e07c-9f4a-97aa-452c1fbcc9af').
(#label -> nil).
(#next -> #'8290f350-f011-2348-a527-7cfb1d2a5a45').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Object').
(#priority -> 2590)}))})