steps
stepa1816fcb1266bb438500bf8b71248ede
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'0fee1e3f-c9f8-9042-b646-88feee2a13c8').
(#iconCode -> 'nil').
(#id -> #'a1816fcb-1266-bb43-8500-bf8b71248ede').
(#label -> nil).
(#next -> #'9f893a6b-d441-944d-b366-1a2e90eb5cb4').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '8 November 2013 4:10:44 pm').
(#hAlignment -> #right).
(#labelColor -> '#AAAAAA').
(#priority -> 4220)}))})