steps
stepc9208feb9579b54e83a343ffb87e69fa
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'b20e028e-3d01-a342-b258-dedd27d970e2').
(#iconCode -> 'nil').
(#id -> #'c9208feb-9579-b54e-83a3-43ffb87e69fa').
(#isProperty -> true).
(#label -> 'Diff').
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 1:01:49 pm').
(#inputKind -> RBAddMethodChange).
(#priority -> 6260).
(#view -> ViTreeViewExtended)
}))
})