steps
stepbe086e52473b3d4ba8336d796588f9e6
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'0dd38407-434f-4e4c-b128-867eb22c193e').
(#iconCode -> 'nil').
(#id -> #'be086e52-473b-3d4b-a833-6d796588f9e6').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'e61b1b9c-dca8-0246-aff4-93c3b091547a').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Class').
(#labelColor -> '#AAAAAA').
(#priority -> 1550)}))})