steps
step8bef757c004d634e9db4167dccfb28d7
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'70408b61-4313-c047-9375-8bceac479cca').
(#iconCode -> 'UiSilkIcons bulletFeedIcon').
(#id -> #'8bef757c-004d-634e-9db4-167dccfb28d7').
(#label -> 'Changed/Update Aspects').
(#next -> #'fca5ba47-1c0b-0b4d-8c61-7eca1715c0c5').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 280)}))})