steps
step8579d16a7cedf746893390568d7c97e0
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'5f906dca-7493-5644-b7f0-b981e9f82243').
(#iconCode -> 'nil').
(#id -> #'8579d16a-7ced-f746-8933-90568d7c97e0').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 September 2013 9:31:08 am').
(#headerText -> '2').
(#inputKind -> ViAbstractQueryPart).
(#labelColor -> #'000000').
(#priority -> 3630)}))})