steps
stepa62c64219b1098418280932805e5b88b
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'b3493c79-1f39-ee43-adf3-ac6248655918').
(#iconCode -> 'nil').
(#id -> #'a62c6421-9b10-9841-8280-932805e5b88b').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'e12b2fbe-9eec-2c4d-90cd-9cddd8d57668').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 January 2014 4:40:37 pm').
(#priority -> 4780)}))})