steps
stepd96e910adf735a4cb7608811fac45378
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'d06feec8-587b-1b4b-8b63-a5aeb5f665b2').
(#iconCode -> 'nil').
(#id -> #'d96e910a-df73-5a4c-b760-8811fac45378').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#hAlignment -> #left).
(#headerText -> 'Origin').
(#itemOrientation -> #horizontalMaxHeight).
(#priority -> 2570).
(#vAlignment -> #top)}))})