steps
step70f2866cc1934849bbc6734357c4521f
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #identity).
(#iconCode -> 'nil').
(#id -> #'70f2866c-c193-4849-bbc6-734357c4521f').
(#label -> 'Script Objects').
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #identity).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 1:01:49 pm').
(#priority -> 6590)}))})