steps
step11617cd4f3dab347b26437a8dd9e6a46
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'637834ff-c53d-7046-a8b0-edf73f34ff52').
(#iconCode -> 'nil').
(#id -> #'11617cd4-f3da-b347-b264-37a8dd9e6a46').
(#label -> 'Users').
(#next -> #'43770565-2816-9048-8e6e-7364ba7aab35').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #defaultProperties).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 550)}))})