steps
stepd9a22b3cf29a7840bb49c3f6d664b189
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'95806f39-bb46-9348-aa78-fd1fd8c16eb0').
(#iconCode -> 'nil').
(#id -> #'d9a22b3c-f29a-7840-bb49-c3f6d664b189').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'73012cd9-6457-9649-bb16-3f77f5dea0d2').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 4:21:57 pm').
(#headerText -> 'Count').
(#labelColor -> '#AAAAAA').
(#priority -> 3220)}))})