steps
step91d1fa51dc09754da0520d922d3eb3d8
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'7c8ea3fa-1ef0-4447-9c03-fc9d497225e5').
(#iconCode -> 'nil').
(#id -> #'91d1fa51-dc09-754d-a052-0d922d3eb3d8').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'71efc7d9-c3cb-7246-9652-6b74bc022b8e').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '9 April 2019 6:53:40.298982 pm')}))})