steps
step82908026d4e4d04783ee741e175314a3
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'946d491e-650f-4847-95e2-69b1d7757dae').
(#iconCode -> 'nil').
(#id -> #'82908026-d4e4-d047-83ee-741e175314a3').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Timestamp').
(#labelColor -> '#AAAAAA').
(#priority -> 1820)}))})