steps
step1a41c168d8968c4dbdc8b6e9ecdd16ea
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'81d3e689-36bf-1048-aa2e-201f5e8c5032').
(#iconCode -> 'nil').
(#id -> #'1a41c168-d896-8c4d-bdc8-b6e9ecdd16ea').
(#isProperty -> false).
(#isReference -> true).
(#label -> nil).
(#next -> #'4b813e3f-30bb-714c-9658-02f84e1ecc5b').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:12.651834 pm')}))})