steps
step3bc53c43eaf392408d99587e9a09d49c
	<step>

	^ ((Dictionary new) add: (#definition->#'6fc7a56d-e6dd-4844-92de-c7d721dfc839'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#notifier->ViSystemChangeNotifier); add: (#creationTimeStamp->'20 May 2015 2:47:36 pm'); yourself)); add: (#isProperty->false); add: (#next->#'a515840f-a24c-b440-8344-6f05ddcb59fb'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'3bc53c43-eaf3-9240-8d99-587e9a09d49c'); add: (#isReference->false); yourself)