steps
step3dbca45def245e49975e38f04a9a7729
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQuerySortStep).
(#definition -> #'f054ff68-004c-ac4a-8a95-e8b6414caa98').
(#iconCode -> 'nil').
(#id -> #'3dbca45d-ef24-5e49-975e-38f04a9a7729').
(#label -> nil).
(#next -> #'8ed52473-9493-2142-94be-054478bc571b').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '4 December 2013 8:37:28 am').
(#priority -> 4510)}))})