steps
step378f9f6a6cdf2d488649a57c4661aac7
	<step>

	^ (Dictionary newFrom: {
(#'_def' -> (Dictionary newFrom: {
(#block -> [:in :out | out addAll: in]).
(#className -> #ViScriptDefinition).
(#id -> #'dff698d7-d435-0f4a-9560-73ee7b97388f').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:12.910834 pm')
})).
(#sourceCode -> '[:in :out | out addAll: in]')
})).
(#className -> #ViScriptStep).
(#definition -> #'dff698d7-d435-0f4a-9560-73ee7b97388f').
(#iconCode -> 'nil').
(#id -> #'378f9f6a-6cdf-2d48-8649-a57c4661aac7').
(#isProperty -> false).
(#label -> nil).
(#next -> #'6dcf4d7c-0337-da43-85f9-526e23934ee9').
(#properties -> (Dictionary newFrom: {
(#after -> #(#groupsMinimal)).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:12.910834 pm')
}))
})