steps
step2ae8b5e0925f904b82ab2fe17cce67ab
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'b97f6d95-b634-f543-998d-d494f141665c').
(#iconCode -> 'nil').
(#id -> #'2ae8b5e0-925f-904b-82ab-2fe17cce67ab').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'41ca5cdb-0dc1-394b-8048-c5f08293cdd7').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 4:21:57 pm').
(#headerText -> 'ID').
(#labelColor -> '#AAAAAA').
(#priority -> 3240)}))})