steps
stepe578a963cfd45641b9426e1eef180ad2
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'c63e57c9-2b56-ab49-895d-f8f9a22907a6').
(#iconCode -> 'nil').
(#id -> #'e578a963-cfd4-5641-b942-6e1eef180ad2').
(#label -> nil).
(#next -> #'37989d23-0602-ed44-ad37-440cccc8d6d9').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 March 2014 10:13:57 am').
(#priority -> 6030)}))})