steps
step8290f350f0112348a5277cfb1d2a5a45
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'6c0f164a-3db1-d647-ab16-17eac019f86b').
(#iconCode -> 'nil').
(#id -> #'8290f350-f011-2348-a527-7cfb1d2a5a45').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Origin').
(#labelColor -> '#AAAAAA').
(#priority -> 2600)}))})