steps
step6db1e61351569940b0a6eb4acb825df1
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #origin).
(#iconCode -> 'nil').
(#id -> #'6db1e613-5156-9940-b0a6-eb4acb825df1').
(#label -> nil).
(#next -> #'b2d07dee-1032-9043-b2c7-876a7ef811bb').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Class').
(#labelColor -> '#AAAAAA').
(#priority -> 1490)}))})