steps
step225b70fb8963d84aa825589a864d6670
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'6aae7226-e240-b447-8aab-0375cca970f6').
(#iconCode -> 'nil').
(#id -> #'225b70fb-8963-d84a-a825-589a864d6670').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Origin').
(#labelColor -> '#AAAAAA').
(#priority -> 2870)}))})