steps
step2a5bc3f7fc5f4d42bc5d1a7c79ebf632
	<step>

	^ (Dictionary newFrom: {
(#'_def' -> (Dictionary newFrom: {
(#block -> [:in :out | out addAll: in]).
(#className -> #ViScriptDefinition).
(#id -> #'02eb996a-482e-a94a-b607-47360c8f1033').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:11.508834 pm')
})).
(#sourceCode -> '[:in :out | out addAll: in]')
})).
(#className -> #ViScriptStep).
(#definition -> #'02eb996a-482e-a94a-b607-47360c8f1033').
(#iconCode -> 'nil').
(#id -> #'2a5bc3f7-fc5f-4d42-bc5d-1a7c79ebf632').
(#isProperty -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#after -> #(#'580b86a1-54c0-3a4f-a37c-d12c765b21d4')).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '29 March 2019 5:00:11.33635 pm').
(#view -> ViTreeViewExtended)
}))
})