steps
step962950ed4ad4244b9e1b512547f2422f
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #iconAndLabel).
(#iconCode -> 'nil').
(#id -> #'962950ed-4ad4-244b-9e1b-512547f2422f').
(#label -> nil).
(#next -> #'c9ff51f8-97e3-cf46-ba3f-4d71325c942d').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Classes').
(#priority -> 2140)}))})