steps
step9495a7a136da3645afa0bb85011e21d1
	<step>

	^ (Dictionary newFrom: {
(#'_def' -> (Dictionary newFrom: {
(#block -> [:in :out | out add: {#objects -> in}, [{
	#bounds -> (292@336 corner: 442@373).
	#current -> #'e9577839-3b92-8e4f-a413-365561ade680'.
	#scripts -> #(#'e9577839-3b92-8e4f-a413-365561ade680' ).
	#id -> #'4cc8c555-00fc-e049-b56d-1ca0013dea25'.
	#out -> #().
	#in -> #(#(#interactive #'40a98164-6ab3-db44-8db2-caa27b0c9f0c' ) ).
}] value]).
(#className -> #ViScriptDefinition).
(#id -> #'de8216a7-6374-7b49-9452-fe1b108395fb').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 October 2015 11:47:09 am')
})).
(#sourceCode -> '[:in :out | out add: {#objects -> in}, [{
	#bounds -> (292@336 corner: 442@373).
	#current -> #''e9577839-3b92-8e4f-a413-365561ade680''.
	#scripts -> #(#''e9577839-3b92-8e4f-a413-365561ade680'' ).
	#id -> #''4cc8c555-00fc-e049-b56d-1ca0013dea25''.
	#out -> #().
	#in -> #(#(#interactive #''40a98164-6ab3-db44-8db2-caa27b0c9f0c'' ) ).
}] value]')
})).
(#className -> #ViScriptStep).
(#definition -> #'de8216a7-6374-7b49-9452-fe1b108395fb').
(#iconCode -> 'nil').
(#id -> #'9495a7a1-36da-3645-afa0-bb85011e21d1').
(#isProperty -> true).
(#label -> 'Recover Unsaved Changes').
(#next -> #'e3c616ba-4453-c04b-b997-91416620222a').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 October 2015 11:47:09 am').
(#isGlobal -> true).
(#optimalExtent -> (442@373)).
(#view -> ViMultiPaneTiled)
}))
})