steps
step4078cbfe867e564c85b0ac2edd21217d
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'ed9f3ef7-7d17-c541-b7cf-2821cca31d6b').
(#iconCode -> 'nil').
(#id -> #'4078cbfe-867e-564c-85b0-ac2edd21217d').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'4078cbfe-867e-564c-85b0-ac2edd21217d').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 September 2013 6:56:36 pm').
(#labelColor -> '007F00').
(#priority -> 3350)}))})