steps
step40361e300f77964fb3b5a7fb7cc955d9
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'8e8afd87-a8ec-b048-bf33-e99e5d6f9484').
(#iconCode -> 'nil').
(#id -> #'40361e30-0f77-964f-b3b5-a7fb7cc955d9').
(#isProperty -> false).
(#isReference -> true).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '29 March 2019 5:00:11.33835 pm')}))})