steps
step0ea571f72db0b843a9ee8203b56d13c9
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'fb0952f5-6689-a64e-8c53-3eb6e274a0b4').
(#iconCode -> 'UiFugueIcons scriptAttributeMIcon').
(#id -> #'0ea571f7-2db0-b843-a9ee-8203b56d13c9').
(#isProperty -> false).
(#label -> 'Metacello Projects').
(#next -> #'a5b86741-46bd-5b47-ab8d-a79879a3b859').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#isGlobal -> true).
(#priority -> 880).
(#view -> ViTreeViewExtended)}))})