steps
step2fdb319c765a1a43863e792e14de2c1e
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'43f66406-1f2f-c347-ad03-64f1f9a82bd6').
(#iconCode -> 'nil').
(#id -> #'2fdb319c-765a-1a43-863e-792e14de2c1e').
(#isProperty -> false).
(#label -> nil).
(#next -> #'e1378983-156c-1d4a-88b1-eae6654e7fb0').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '12 November 2013 5:16:28 pm').
(#priority -> 4290).
(#view -> ViTreeViewExtended)}))})