steps
stepacccd73850175e44ba68cc46761670dc
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'4e5774bd-f105-5c4c-b2aa-dc1bf152d439').
(#iconCode -> 'nil').
(#id -> #'acccd738-5017-5e44-ba68-cc46761670dc').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '20 May 2014 12:01:18 pm').
(#priority -> 6100)}))})