steps
step5a501a24fd9a87418e5444a08209481a
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'df4edb83-23fe-dc47-a52e-67c69926d29a').
(#iconCode -> 'nil').
(#id -> #'5a501a24-fd9a-8741-8e54-44a08209481a').
(#label -> 'Processes').
(#next -> #'93b6233e-a34e-f54d-9c6a-b7eeef30e075').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #defaultProperties).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 870)}))})