steps
stepb1afac3a000085449dceebfda96b30b6
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'51d9c6f1-45c9-814c-8d67-6864979fb6a0').
(#iconCode -> 'nil').
(#id -> #'b1afac3a-0000-8544-9dce-ebfda96b30b6').
(#label -> 'DBLP Result').
(#next -> #'cf42cf45-c23c-c149-81f2-1b262f58b7d3').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #identity).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 1:01:49 pm').
(#priority -> 6280)}))})