steps
step181275cdbd0c36429b0d9373d885260e
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupStep).
(#definition -> #category).
(#iconCode -> 'nil').
(#id -> #'181275cd-bd0c-3642-9b0d-9373d885260e').
(#label -> nil).
(#next -> #'2a56df61-69c8-3349-9b25-d5afffcb60b1').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 2840)}))})