steps
step6d395bc8bf7777499480a5230a30d62f
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'2f12cab0-c913-b847-9cf8-08603c49889e').
(#iconCode -> 'nil').
(#id -> #'6d395bc8-bf77-7749-9480-a5230a30d62f').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'94e3fbd0-08ad-ea49-aa1d-8bf2961de5fc').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 October 2015 11:08:14 am')}))})