steps
stepc65a9646727f864b9955deeac8d8dcf4
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'fe876151-7d88-f645-9e7d-c53ca687513d').
(#iconCode -> 'nil').
(#id -> #'c65a9646-727f-864b-9955-deeac8d8dcf4').
(#label -> nil).
(#next -> #'00d6ab88-02b8-d343-98bf-44d2fb8c6ab5').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 September 2013 3:21:01 pm').
(#priority -> 3680).
(#view -> ViTreeViewExtended)}))})