steps
stepd41601c5addb2e419d9040c5759c9647
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'dbd1a944-8a6a-8545-99c1-8dbd3aeacad4').
(#iconCode -> 'nil').
(#id -> #'d41601c5-addb-2e41-9d90-40c5759c9647').
(#isProperty -> false).
(#label -> 'Scripts in Archive').
(#next -> #'76abd232-f0e2-2044-8211-6504f20d1cfe').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '14 April 2019 4:42:23.130086 pm').
(#inputKind -> MethodReference).
(#priority -> 205)
}))
})