steps
step78e13ff4d0931140b575be2225a6eaf7
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'f677255c-a160-7b4a-9153-982f6f991f80').
(#iconCode -> 'nil').
(#id -> #'78e13ff4-d093-1140-b575-be2225a6eaf7').
(#label -> nil).
(#next -> #'3a47c56d-3e11-344a-8b45-cc59f6ba7fb5').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '14 February 2014 10:53:40 am').
(#headerText -> #cU).
(#priority -> 5400)}))})