steps
step4a7a5822905db043b36956f156129b87
	<step>

	^ ((Dictionary new) add: (#definition->#'c37e89e8-8db6-4d44-85d0-ccaefc64a618'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->MethodReference); add: (#priority->300); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'9 December 2015 11:02:31 am'); add: (#view->ViMethodEditorView); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->#'78cd1987-8352-584e-9b6b-7582a5be6451'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'4a7a5822-905d-b043-b369-56f156129b87'); add: (#isReference->false); yourself)