steps
step6eab0da05a97d94d84a65f930edbbd06
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'2d64642b-996d-4549-b799-afb46cd159ae').
(#iconCode -> 'nil').
(#id -> #'6eab0da0-5a97-d94d-84a6-5f930edbbd06').
(#label -> nil).
(#next -> #'244a371f-7663-214d-932d-5512b30c3e35').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '21 May 2014 2:37:53 pm').
(#priority -> 6320)}))})