steps
step95c74daf50da9d48956ba1e377ae9019
	<step>

	^ ((Dictionary new) add: (#definition->#'def35c40-345a-5047-9824-66d86dfdfbc4'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'9 December 2015 11:55:27 am'); yourself)); add: (#isProperty->false); add: (#next->#'8c98b390-c0ff-494e-94e4-be9cfaeea24c'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'95c74daf-50da-9d48-956b-a1e377ae9019'); add: (#isReference->false); yourself)