steps
step8fe6639eeac54041bebf7f8ad4f3f3b6
	<step>

	^ (Dictionary newFrom: {
(#'_def' -> (Dictionary newFrom: {
(#block -> [:in :out | out addAll: ([:tuples | tuples asGroups] value: in) asList]).
(#className -> #ViScriptDefinition).
(#id -> #'f06a0fe5-9cde-8b4a-9944-fa0542da96f7').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2019 9:38:28.534728 am')
})).
(#sourceCode -> '[:in :out | out addAll: ([:tuples | tuples asGroups] value: in) asList]')
})).
(#className -> #ViScriptStep).
(#definition -> #'f06a0fe5-9cde-8b4a-9944-fa0542da96f7').
(#iconCode -> 'nil').
(#id -> #'8fe6639e-eac5-4041-bebf-7f8ad4f3f3b6').
(#isProperty -> false).
(#label -> nil).
(#next -> #'66f64b27-8ccb-0549-a387-9ab332d35ab1').
(#properties -> (Dictionary newFrom: {
(#color -> (Color r: 0.553 g: 0.796 b: 0.553)).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2019 9:38:28.534728 am')
}))
})