steps
step4ee8e2d89bc67645b541f743df30fe9d
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQuerySortStep).
(#definition -> #'0bc0ce7e-2194-504a-b60b-9cd9c19cef01').
(#iconCode -> 'nil').
(#id -> #'4ee8e2d8-9bc6-7645-b541-f743df30fe9d').
(#label -> nil).
(#next -> #'ba683fae-91bb-ed4c-985f-8c12b3504e50').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1570)}))})