steps
stepee9363991409634c81ff0389658bb3ce
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'58d9e6a5-81eb-e946-8243-7b088803d44e').
(#iconCode -> 'nil').
(#id -> #'ee936399-1409-634c-81ff-0389658bb3ce').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '6 December 2013 5:17:12 pm').
(#priority -> 4560)}))})