steps
step39e0739ab359364a9c0fa5b758f8f9c8
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'8dfc8e4e-7de0-9045-bce6-69a0b33fca64').
(#iconCode -> 'nil').
(#id -> #'39e0739a-b359-364a-9c0f-a5b758f8f9c8').
(#label -> nil).
(#next -> #'240cc4b3-dcec-8c4e-bbe8-29ff7c118338').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#labelColor -> '#AAAAAA').
(#priority -> 1240)}))})