steps
step2ae8b5e0925f904b82ab2fe17cce67ab
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'98b3f729-31d1-cd46-b092-2db0dbc473e2').
(#iconCode -> 'nil').
(#id -> #'2ae8b5e0-925f-904b-82ab-2fe17cce67ab').
(#label -> nil).
(#next -> #'41ca5cdb-0dc1-394b-8048-c5f08293cdd7').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 4:21:57 pm').
(#headerText -> 'ID').
(#labelColor -> '#AAAAAA').
(#priority -> 3240)}))})