steps
stepd30b0a27e492ab4c807d23bd5f7ccf4b
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'b8cd1ee3-55ca-104d-af64-03448b83aed8').
(#iconCode -> 'nil').
(#id -> #'d30b0a27-e492-ab4c-807d-23bd5f7ccf4b').
(#isProperty -> true).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 1:47:30 pm').
(#priority -> 5080)
}))
})