steps
step64c67351149a5b419de2aa23b19628a8
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'aa5e9c44-1dea-fa44-a31f-e5b5194f0eb9').
(#iconCode -> 'nil').
(#id -> #'64c67351-149a-5b41-9de2-aa23b19628a8').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'8729d445-82f2-7f4d-abfa-8044a4165d7f').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 September 2013 9:56:21 am').
(#inputKind -> ViAbstractQueryPart).
(#outputKind -> String).
(#priority -> 3640)}))})