steps
steped5b130b8850004da2e4fa5157edc3b8
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'41b850e6-6841-4440-bb74-7dd967c38067').
(#iconCode -> 'nil').
(#id -> #'ed5b130b-8850-004d-a2e4-fa5157edc3b8').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '15 June 2015 10:20:57 am')}))})