steps
stepd5cb07566c54dd4da1181174174246ff
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'514e33c1-49ef-db4a-ab27-1b67d793b46b').
(#iconCode -> 'nil').
(#id -> #'d5cb0756-6c54-dd4d-a118-1174174246ff').
(#label -> nil).
(#next -> #'3f2ccc8f-3fd6-2243-b5e4-1a2f686ed9bc').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #identity).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 1:01:49 pm').
(#priority -> 5840).
(#view -> ViTreeViewExtended)}))})