steps
step0caac112a8fdc443bf49f884e1be7743
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'705e187c-d0f6-f64d-9f4f-f2eef6af67a6').
(#iconCode -> 'nil').
(#id -> #'0caac112-a8fd-c443-bf49-f884e1be7743').
(#label -> nil).
(#next -> #'d61e9087-1215-2d4e-b336-316c41064b72').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '23 July 2014 1:16:41 pm').
(#priority -> 6640)}))})