steps
stepe1cedd4ab4647243ad426ec318525434
	<step>

	^ (Dictionary newFrom: {
(#'_def' -> (Dictionary newFrom: {
(#block -> [:in :out | out addAll: in]).
(#className -> #ViScriptDefinition).
(#id -> #'0c0126cc-6239-604a-9855-f5691441cab3').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '14 November 2019 10:32:20.306893 am')
})).
(#sourceCode -> '[:in :out | out addAll: in]')
})).
(#className -> #ViScriptStep).
(#definition -> #'0c0126cc-6239-604a-9855-f5691441cab3').
(#iconCode -> 'nil').
(#id -> #'e1cedd4a-b464-7243-ad42-6ec318525434').
(#isProperty -> false).
(#label -> nil).
(#next -> #'fe5b7b59-78d3-234f-8d11-af30f055cb25').
(#properties -> (Dictionary newFrom: {
(#after -> #(#groups)).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '14 November 2019 10:32:20.306893 am')
}))
})