steps
step33a2c2eebac83b4a842dfaf5586d7042
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'df6987de-ab9d-cc43-8eb3-cc1732da21cb').
(#iconCode -> 'nil').
(#id -> #'33a2c2ee-bac8-3b4a-842d-faf5586d7042').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '12 November 2013 5:02:54 pm').
(#priority -> 4340)}))})