steps
step7df281f135709440b69ef00d41128ad0
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'6f04a572-9605-1d48-b407-ababe4363a9b').
(#iconCode -> 'nil').
(#id -> #'7df281f1-3570-9440-b69e-f00d41128ad0').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'aba8446d-ad23-4a44-8fc1-448e43f60d5d').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #defaultProperties).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 4850)}))})