steps
stepsenders
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'fa044112-0baa-3e4d-abc2-c54a247e5236').
(#iconCode -> 'UiFugueIcons arrowStepIcon').
(#id -> #senders).
(#isProperty -> false).
(#isReference -> false).
(#label -> 'Senders').
(#next -> #'e67a3ef7-7a93-634e-86af-5740774f3bb9').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '20 May 2015 12:08:55 pm').
(#inputKind -> ByteSymbol).
(#notifier -> ViSystemChangeNotifier).
(#out -> Set).
(#view -> ViTreeViewExtended)}))})