steps
step23d4adf141b29845aeb22b496e4ea663
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'bf222edf-ff5f-7149-8f7e-d65994f90ce9').
(#iconCode -> 'nil').
(#id -> #'23d4adf1-41b2-9845-aeb2-2b496e4ea663').
(#label -> nil).
(#next -> #'8579d16a-7ced-f746-8933-90568d7c97e0').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'d9634b11-bde6-1a40-a0b4-7be880afc37a').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 3620)}))})