steps
step02e8ebf69dc2a14288660da7a72f9253
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'b9270222-242d-d041-9224-403ba422d264').
(#iconCode -> 'nil').
(#id -> #'02e8ebf6-9dc2-a142-8866-0da7a72f9253').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'ae3c2d41-a712-8f44-a52a-cd39fdb3459b').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '14 February 2014 10:44:15 am').
(#headerText -> #cM).
(#priority -> 5420)}))})