steps
stepb8dcfbd64325b94bbf953a44025557dc
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'b47ce5fd-48ca-be4e-a9ec-085c8c0d5546').
(#iconCode -> 'nil').
(#id -> #'b8dcfbd6-4325-b94b-bf95-3a44025557dc').
(#label -> 'Query Properties').
(#next -> #'874bd769-4b84-dd45-9644-c5e3a23f29de').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #identity).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 1:01:49 pm').
(#priority -> 6600).
(#view -> ViTreeViewExtended)}))})