steps
step1fb44024f23f3244bc57a9be90f3ccdb
	<step>

	^ ((Dictionary new) add: (#definition->#'68e5d13a-ced8-2246-bed5-463df2170ccb'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'15 December 2015 10:40:06 am'); yourself)); add: (#isProperty->false); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'1fb44024-f23f-3244-bc57-a9be90f3ccdb'); add: (#isReference->true); yourself)