steps
step8ebf9a995fb3ba48ae1ee67f7a28e0ed
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'b866d5b8-d4d7-7443-96d0-241ce986ce5f').
(#iconCode -> 'nil').
(#id -> #'8ebf9a99-5fb3-ba48-ae1e-e67f7a28e0ed').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'14e205f5-0445-584a-8c5f-729f6226210c').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '10 April 2019 11:09:43.02611 am')}))})