steps
step2ea23721a871ea4687986a4a5be4cb8e
	<step>

	^ ((Dictionary new) add: (#definition->nil); add: (#class->ViQueryReferenceStep); add: (#properties->((Dictionary new) add: (#priority->1060); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'7 September 2013 10:46:54 am'); yourself)); add: (#id->#'2ea23721-a871-ea46-8798-6a4a5be4cb8e'); add: (#iconCode->'nil'); add: (#next->nil); add: (#reference->#'f4803742-eb44-0846-9085-92c09d525159'); add: (#label->nil); yourself)