steps
step99cac90068fd1449966b015ed7762e86
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'187d2c6e-fa01-5d4a-b748-1a739c679b7b').
(#iconCode -> 'nil').
(#id -> #'99cac900-68fd-1449-966b-015ed7762e86').
(#label -> '[DEBUG] Categorize lines of code').
(#next -> #'56b2492f-f394-db42-ade3-e2d633f5230d').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #identity).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 1:01:49 pm').
(#priority -> 5130).
(#view -> ViTreeViewExtended)}))})