steps
step51d8a53895c9ce4b9e21ac726be7665b
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQuerySortStep).
(#definition -> #compareObjectsBySelector).
(#iconCode -> 'nil').
(#id -> #'51d8a538-95c9-ce4b-9e21-ac726be7665b').
(#label -> nil).
(#next -> #'6f20da89-1a7e-f64d-96a6-8b4b22691ee4').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1510)}))})