steps
step8b5ec783b069bd44a805058c53c7f164
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupStep).
(#definition -> #'f88512ad-81dd-ac4c-8e82-ff004696fed6').
(#iconCode -> 'nil').
(#id -> #'8b5ec783-b069-bd44-a805-058c53c7f164').
(#label -> nil).
(#next -> #'2defa63a-9991-5e42-8520-0d0db861b77c').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1990)}))})