steps
step1d71708a545679429c1cc6c37baec8c9
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'163e8051-6261-6b4f-8d17-6d1d49dce384').
(#iconCode -> 'nil').
(#id -> #'1d71708a-5456-7942-9c1c-c6c37baec8c9').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 February 2014 4:12:57 pm').
(#priority -> 5940)}))})