steps
stepe9f4b617ab3acd419a5b9f547aa04c9d
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQuerySortStep).
(#definition -> #'563021ef-44a7-e24e-beb7-6201088a6f24').
(#iconCode -> 'nil').
(#id -> #'e9f4b617-ab3a-cd41-9a5b-9f547aa04c9d').
(#label -> nil).
(#next -> #'cb96415c-4b85-6247-877c-589b975e69c8').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1250)}))})