steps
step71efc7d9c3cb724696526b74bc022b8e
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'53b0702c-c7b9-b74c-94b3-d4f943c6e9bc').
(#iconCode -> 'nil').
(#id -> #'71efc7d9-c3cb-7246-9652-6b74bc022b8e').
(#label -> nil).
(#next -> #'5636df93-3a8f-ea44-9406-e602b99e3101').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'93b6233e-a34e-f54d-9c6a-b7eeef30e075').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 6380)}))})