steps
step4078cbfe867e564c85b0ac2edd21217d
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'8a784482-fd3d-5147-8554-97a28d8db945').
(#iconCode -> 'nil').
(#id -> #'4078cbfe-867e-564c-85b0-ac2edd21217d').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'4078cbfe-867e-564c-85b0-ac2edd21217d').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 September 2013 6:56:36 pm').
(#labelColor -> '007F00').
(#priority -> 3350)}))})