steps
step894088c29d245b4092462e1a298fe761
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #histogram).
(#iconCode -> 'UiSilkIcons chartBarIcon').
(#id -> #'894088c2-9d24-5b40-9246-2e1a298fe761').
(#label -> 'Sorted Bars').
(#next -> #'d740eb73-4267-9240-86ce-b2cb2018f68a').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 November 2013 3:30:24 pm').
(#priority -> 4360)}))})