steps
step328d2fd9190c6f40accdafc2029f12c4
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupStep).
(#definition -> #'0b7a9508-db02-4244-ac2b-4ea7ff772056').
(#iconCode -> 'nil').
(#id -> #'328d2fd9-190c-6f40-accd-afc2029f12c4').
(#label -> nil).
(#next -> #'0022b353-daa6-014c-a245-38faec14e32e').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 September 2013 3:17:34 pm').
(#priority -> 4000)}))})