steps
step266651fd1b710244ac4579f564404cc5
	<step>

	^ (Dictionary newFrom: {
(#'_def' -> (Dictionary newFrom: {
(#block -> [:in :out | out addAll: in]).
(#className -> #ViScriptDefinition).
(#id -> #'ca3d6e76-a3c5-0249-a7b3-e758bb2ade33').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:12.545834 pm')
})).
(#sourceCode -> '[:in :out | out addAll: in]')
})).
(#className -> #ViScriptStep).
(#definition -> #'ca3d6e76-a3c5-0249-a7b3-e758bb2ade33').
(#iconCode -> 'nil').
(#id -> #'266651fd-1b71-0244-ac45-79f564404cc5').
(#isProperty -> false).
(#label -> nil).
(#next -> #'e4cedfc1-3419-6a46-a306-65067830a9bf').
(#properties -> (Dictionary newFrom: {
(#after -> #(#groupsMinimal)).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:12.545834 pm')
}))
})