steps
step2ea23721a871ea4687986a4a5be4cb8e
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryReferenceStep).
(#definition -> nil).
(#iconCode -> 'nil').
(#id -> #'2ea23721-a871-ea46-8798-6a4a5be4cb8e').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '7 September 2013 10:46:54 am').
(#priority -> 1060)})).
(#reference -> #'f4803742-eb44-0846-9085-92c09d525159')})