steps
step8ed524739493214294be054478bc571b
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'1a63b3b5-dd5b-c242-b723-24e2fb3768d7').
(#iconCode -> 'nil').
(#id -> #'8ed52473-9493-2142-94be-054478bc571b').
(#label -> 'Properties for Map Definitions').
(#next -> #'e63568e8-5926-f640-9527-117c4e70e841').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'8ed52473-9493-2142-94be-054478bc571b').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '3 September 2013 1:56:12 pm').
(#priority -> 660).
(#view -> ViTreeViewExtended)}))})