steps
stepf977b925bca88e418e7a33672b08eb1d
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'ab097827-d773-694d-bec1-8bf8e939ec71').
(#iconCode -> 'nil').
(#id -> #'f977b925-bca8-8e41-8e7a-33672b08eb1d').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Message').
(#labelColor -> '#AAAAAA').
(#priority -> 2970)}))})