steps
step1e74bf855561eb4d808c4e7eb6401a04
	<step>

	^ (Dictionary newFrom: {
(#'_def' -> (Dictionary newFrom: {
(#block -> [:in :out | out addAll: in]).
(#className -> #ViScriptDefinition).
(#id -> #'6026e2fe-064b-694e-8712-9dee79b258ec').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:11.999834 pm')
})).
(#sourceCode -> '[:in :out | out addAll: in]')
})).
(#className -> #ViScriptStep).
(#definition -> #'6026e2fe-064b-694e-8712-9dee79b258ec').
(#iconCode -> 'nil').
(#id -> #'1e74bf85-5561-eb4d-808c-4e7eb6401a04').
(#isProperty -> false).
(#label -> nil).
(#next -> #'64328701-00b2-654e-a369-98b5ecac31fd').
(#properties -> (Dictionary newFrom: {
(#after -> #(#groupsMinimal)).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:11.999834 pm')
}))
})