steps
step8173a10aef99b643819d530c4a9f806f
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'c832c425-3742-784c-81f6-541b0f9ae50a').
(#iconCode -> 'nil').
(#id -> #'8173a10a-ef99-b643-819d-530c4a9f806f').
(#label -> nil).
(#next -> #'9af0df5a-068a-a649-9aa4-230c1f0217cc').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '8 November 2013 3:19:19 pm').
(#priority -> 4210)}))})