steps
step4b56b9216888f2468e50b89ba30bbd13
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'f05a146d-14f7-aa4d-bdae-826bab156f47').
(#iconCode -> 'nil').
(#id -> #'4b56b921-6888-f246-8e50-b89ba30bbd13').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#copyOf -> #'ec77d931-b152-e14d-83f0-ca3d29ac8796').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '20 May 2015 2:36:10 pm')}))})