steps
stepd681c3f184e3ea45b9b7505c4216ddc5
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'51e565d5-fc7c-b94e-b558-b7c0bb51532a').
(#iconCode -> 'nil').
(#id -> #'d681c3f1-84e3-ea45-b9b7-505c4216ddc5').
(#isProperty -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#after -> #(#'d70d563f-bdd7-1842-9175-cf758450e227')).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '29 March 2019 4:02:48.696009 pm').
(#view -> ViTreeViewExtended)
}))
})