steps
step1bb9843febf1384882dc01ee3ed5468d
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'79316033-e6c3-c840-bf52-000bdfb04da3').
(#iconCode -> 'nil').
(#id -> #'1bb9843f-ebf1-3848-82dc-01ee3ed5468d').
(#isProperty -> true).
(#label -> nil).
(#next -> #'78e13ff4-d093-1140-b575-be2225a6eaf7').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 February 2014 1:57:43 pm').
(#headerText -> 'cS').
(#priority -> 5390)}))})