steps
stepcf42cf45c23cc14981f21b262f58b7d3
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'9d669321-3928-7c41-a7f3-3d492fde2d92').
(#iconCode -> 'nil').
(#id -> #'cf42cf45-c23c-c149-81f2-1b262f58b7d3').
(#isProperty -> false).
(#label -> nil).
(#next -> #'3342a24e-e4ed-a64f-980a-bc8e7c4674e4').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '23 May 2014 11:01:22 am').
(#priority -> 6290)}))})