steps
step117962c3a327154ab5319a15adc69887
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'14767347-73da-b249-817d-740c37a6ba4d').
(#iconCode -> 'nil').
(#id -> #'117962c3-a327-154a-b531-9a15adc69887').
(#label -> nil).
(#next -> #'1bb9843f-ebf1-3848-82dc-01ee3ed5468d').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 February 2014 1:11:39 pm').
(#headerText -> #scM).
(#priority -> 5380)}))})