steps
step4011a5c2e1deed4885b3ef688751c3b8
	<step>

	^ ((Dictionary new) add: (#definition->#'d38699e6-bec1-344c-9a51-ed500e0bf6dd'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->CompiledMethod); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'9 December 2015 9:44:59 am'); add: (#priority->200); add: (#view->ViTreeViewExtended); yourself)); add: (#isProperty->false); add: (#next->#'8aa22994-8321-5647-823f-8e9203115b01'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'4011a5c2-e1de-ed48-85b3-ef688751c3b8'); add: (#isReference->false); yourself)