steps
step41f64542f4fbc3418ee9d1adfceebe00
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'86dd3fe0-1fb1-324d-9bf1-d4bef5df2a5c').
(#iconCode -> 'nil').
(#id -> #'41f64542-f4fb-c341-8ee9-d1adfceebe00').
(#label -> nil).
(#next -> #'cf7fdd66-0271-9544-b4a9-3ecca1e4a611').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '23 July 2014 2:47:45 pm').
(#priority -> 6710)}))})