steps
step00ab51d869ddfb4a90da3e9a2f70ef75
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'6a694a4e-65b5-7942-9697-978ac471ca74').
(#iconCode -> 'nil').
(#id -> #'00ab51d8-69dd-fb4a-90da-3e9a2f70ef75').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '14 February 2014 2:48:40 pm').
(#headerText -> #o).
(#priority -> 5450)}))})