steps
step51b916eb489bfe4ba0582713f79eca04
	<step>

	^ ((Dictionary new) add: (#definition->#'70b027c4-9ba5-1d4c-999d-ea125ea39eaa'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'9 December 2015 11:26:37 am'); yourself)); add: (#isProperty->false); add: (#next->#'473ec1cf-01e6-db49-a731-58d0370843f8'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'51b916eb-489b-fe4b-a058-2713f79eca04'); add: (#isReference->false); yourself)