steps
stepaa53c07584c54b40b6f36bcfd0ac3b68
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'72afa9e5-7d79-104b-97b0-accfde7204b7').
(#iconCode -> 'UiFugueIcons picturesIcon').
(#id -> #'aa53c075-84c5-4b40-b6f3-6bcfd0ac3b68').
(#label -> 'Pictures').
(#next -> #'78d3db6d-6a90-614d-88f9-eed2f96f9d05').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 500).
(#view -> ViTreeViewExtended)}))})