steps
step2902b302607d7340b97a4a497764e9d3
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'9c23f6ea-935a-e84c-81ce-33f9f1373aed').
(#iconCode -> 'nil').
(#id -> #'2902b302-607d-7340-b97a-4a497764e9d3').
(#isProperty -> true).
(#label -> nil).
(#next -> #'82908026-d4e4-d047-83ee-741e175314a3').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Methods').
(#priority -> 1810)
}))
})