steps
step5e941cab2cc706469ed0d8493d5d3d0e
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'8572f770-da04-804b-a566-2b332c424ef9').
(#iconCode -> 'nil').
(#id -> #'5e941cab-2cc7-0646-9ed0-d8493d5d3d0e').
(#isProperty -> true).
(#label -> nil).
(#next -> #'2b264d15-bb33-124e-8b3f-227ef7073118').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#labelColor -> #'000000').
(#priority -> 4470)
}))
})