steps
step661f2767d34f6a4fb8ff8ec4307d757f
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'59426283-fdda-b346-92ea-5fb39aebb54b').
(#iconCode -> 'nil').
(#id -> #'661f2767-d34f-6a4f-b8ff-8ec4307d757f').
(#isProperty -> false).
(#label -> 'Recently Opened').
(#next -> #'c31cf538-fe89-4242-bd60-cf299527d31f').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '22 July 2015 9:47:58 am').
(#isGlobal -> true)}))})