steps
step23d4adf141b29845aeb22b496e4ea663
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'903e00a6-afed-b14d-b5e4-45f59787fc1b').
(#iconCode -> 'nil').
(#id -> #'23d4adf1-41b2-9845-aeb2-2b496e4ea663').
(#isProperty -> true).
(#label -> nil).
(#next -> #'8579d16a-7ced-f746-8933-90568d7c97e0').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#inputKind -> ViScriptObject).
(#priority -> 3620)
}))
})