steps
stepd78c13da287140408d24eb9d6565f332
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryReferenceStep).
(#definition -> nil).
(#iconCode -> 'nil').
(#id -> #'d78c13da-2871-4040-8d24-eb9d6565f332').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '29 March 2019 5:05:19.01935 pm')})).
(#reference -> #'6f505e41-acfd-5d4f-ada2-77cdc48e1601')})