steps
stepac1f8319046ce04db22a43df31b7abef
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'e43c93d0-ee96-e542-8395-df731e1f9503').
(#iconCode -> 'nil').
(#id -> #'ac1f8319-046c-e04d-b22a-43df31b7abef').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#hAlignment -> #center).
(#headerText -> 'Origin').
(#itemOrientation -> #vertical).
(#priority -> 2540).
(#vAlignment -> #bottom)}))})