steps
step0f80a3d1e8c57848b5ef561321c3d70e
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'de45825b-35e8-204e-bbdd-4b6a784be13c').
(#iconCode -> 'nil').
(#id -> #'0f80a3d1-e8c5-7848-b5ef-561321c3d70e').
(#isProperty -> false).
(#label -> nil).
(#next -> #'7b56c7af-5bd2-4848-9eae-c2af03afefde').
(#properties -> (Dictionary newFrom: {
(#after -> #(#groupsMinimal)).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:11.896834 pm')}))})