steps
step3723f748fad3d4468f95d2d495e9a9cc
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'cfa0942b-69fc-bd43-94d0-7987e2819ec3').
(#iconCode -> 'nil').
(#id -> #'3723f748-fad3-d446-8f95-d2d495e9a9cc').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#labelColor -> '#AAAAAA').
(#priority -> 1380)}))})