steps
stepe61b1b9cdca80246aff493c3b091547a
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #category).
(#iconCode -> 'nil').
(#id -> #'e61b1b9c-dca8-0246-aff4-93c3b091547a').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Protocol').
(#labelColor -> '#AAAAAA').
(#priority -> 1560)}))})