steps
stepcodeDefinitions
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'4f03e8b9-0386-0f42-90f9-b17a09d3f17c').
(#iconCode -> 'nil').
(#id -> #codeDefinitions).
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'65524c28-e06a-0e4b-85de-f973d5fa91df').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #codeDefinitions).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '3 September 2013 1:46 pm').
(#inputKind -> ViQueryOrganizer).
(#outputKind -> ViQueryStepDefinition).
(#priority -> 400).
(#view -> ViTreeViewExtended)}))})