steps
stepupdateDefinitions
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'e3fc3413-7646-b546-aaa2-33c636945da4').
(#iconCode -> 'nil').
(#id -> #updateDefinitions).
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'ed778e6a-6ace-e540-84c3-af7329c1f656').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '6 September 2013 8:27:11 pm').
(#inputKind -> ViQueryOrganizer).
(#outputKind -> ViQueryStepDefinition).
(#priority -> 410).
(#view -> ViTreeViewExtended)}))})