steps
step8ed524739493214294be054478bc571b
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'49e2992c-3cde-a648-8e86-83a5cebe767e').
(#iconCode -> 'nil').
(#id -> #'8ed52473-9493-2142-94be-054478bc571b').
(#isProperty -> true).
(#isReference -> false).
(#label -> 'Properties for Map Definitions').
(#next -> #'e63568e8-5926-f640-9527-117c4e70e841').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '3 September 2013 1:56:12 pm').
(#inputKind -> ViQueryStepDefinition).
(#priority -> 660).
(#view -> ViTreeViewExtended)}))})