steps
stepb44be5e8ba080744812e8f9104bc951f
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'eaacc8b2-4e11-bb4c-ab2b-7aa0583b7467').
(#iconCode -> 'nil').
(#id -> #'b44be5e8-ba08-0744-812e-8f9104bc951f').
(#label -> nil).
(#next -> #'c0cac2e3-ab77-904f-a0ed-936a31a423ea').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #updateDefinitions).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '6 September 2013 8:27:11 pm').
(#priority -> 4870)}))})