steps
stepcb3aaeaa1407b74d8f5e8838680974b5
	<step>

	^ (Dictionary newFrom: {
(#'_def' -> (Dictionary newFrom: {
(#block -> [:in :out | [ViProfile active bookmarks] value in: [:result |
	out addAll: result asList]]).
(#className -> #ViScriptDefinition).
(#id -> #'4c57df18-603f-524d-a007-62a79be224e6').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '20 May 2014 11:59:48 am')
})).
(#sourceCode -> '[:in :out | [ViProfile active bookmarks] value in: [:result |
	out addAll: result asList]]')
})).
(#className -> #ViScriptStep).
(#definition -> #'4c57df18-603f-524d-a007-62a79be224e6').
(#iconCode -> 'nil').
(#id -> #'cb3aaeaa-1407-b74d-8f5e-8838680974b5').
(#isProperty -> false).
(#label -> 'Bookmarks').
(#next -> #'acccd738-5017-5e44-ba68-cc46761670dc').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '20 May 2014 11:59:48 am').
(#isGlobal -> true).
(#priority -> 6090).
(#view -> ViTreeViewExtended)
}))
})