steps
step74960bc87b305845b46c415c93eeb270
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'cb6b83e6-95ae-d740-8fb0-d1e1aa59c007').
(#iconCode -> 'nil').
(#id -> #'74960bc8-7b30-5845-b46c-415c93eeb270').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'21c91c05-8d72-194f-bf60-b5aff02d7a97').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '14 February 2018 9:19:23 am')}))})