steps
stepe89d0b5ae4fe584baed496f20385b05c
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'ae87be09-3c23-5743-bab5-e2d9aae7bdfb').
(#iconCode -> 'nil').
(#id -> #'e89d0b5a-e4fe-584b-aed4-96f20385b05c').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '5 June 2014 4:52:37 pm').
(#priority -> 6200)}))})