steps
step45fba510b1f4ca44b3215034c7e36e91
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'038ed42c-83a7-fb4d-a82e-3db71584ebc8').
(#iconCode -> 'nil').
(#id -> #'45fba510-b1f4-ca44-b321-5034c7e36e91').
(#isProperty -> true).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 3:12:48.400594 pm')}))})