steps
stepcc9afa06dafe3f4786135b6306c75ac4
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'bd65b8b9-309f-8641-a7c0-39cf095ed2da').
(#iconCode -> 'nil').
(#id -> #'cc9afa06-dafe-3f47-8613-5b6306c75ac4').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Classes').
(#priority -> 2290)}))})