steps
step4f14fbe565d1c74fab1f7751495fcf7c
	<step>

	^ ((Dictionary new) add: (#definition->#'7356b474-6dca-ab40-a55d-79bc5aaba65e'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'9 December 2015 1:12:24 pm'); yourself)); add: (#isProperty->true); add: (#next->#'be6764e2-9533-b84e-ad01-796ac5f86383'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'4f14fbe5-65d1-c74f-ab1f-7751495fcf7c'); add: (#isReference->false); yourself)