steps
step09ffbad63a278b489dad264b9c41c6f9
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'1c82c7d6-37c7-4a4d-ae5c-617902522935').
(#iconCode -> 'nil').
(#id -> #'09ffbad6-3a27-8b48-9dad-264b9c41c6f9').
(#isProperty -> false).
(#label -> 'World submorphs').
(#next -> #'045e9d2c-b29a-4641-b942-d4b769535d4a').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 July 2014 2:12:59 pm').
(#isGlobal -> true).
(#priority -> 6470).
(#view -> ViTreeViewExtended)}))})