steps
step5636df933a8fea449406e602b99e3101
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'9242cbac-4797-8d4c-9f3f-8d8dc15a9b9e').
(#iconCode -> 'nil').
(#id -> #'5636df93-3a8f-ea44-9406-e602b99e3101').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'fb5f9d48-49cf-774c-921f-e9598b74d2c7').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '12 November 2013 4:58:54 pm').
(#priority -> 6390)}))})