steps
stepb7982ee77baa6b488f2a1bbbf9c96888
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupStep).
(#definition -> #'ef07cc37-d75c-aa4c-bac0-87ad92606d23').
(#iconCode -> 'nil').
(#id -> #'b7982ee7-7baa-6b48-8f2a-1bbbf9c96888').
(#label -> nil).
(#next -> #'5db2822b-273d-b541-b1f6-5ec634e49efa').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1940)}))})