steps
stepa86abb2d0d7b2049a6f8c1cde8336246
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'f1cce3f5-58af-3c4b-aa95-0e040206ff75').
(#iconCode -> 'nil').
(#id -> #'a86abb2d-0d7b-2049-a6f8-c1cde8336246').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '29 March 2019 2:52:43.113235 pm')}))})