steps
stepa34edfe9887173439abcb10f76365684
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'6975eef0-4e5f-5542-b7b0-e35b1872410b').
(#iconCode -> 'UiFugueIcons arrowStepIcon').
(#id -> #'a34edfe9-8871-7343-9abc-b10f76365684').
(#label -> 'References').
(#next -> #'47ebfeaf-f6ff-624a-8fc6-078f452527db').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '9 September 2013 11:55:52 am').
(#priority -> 520).
(#view -> ViTreeViewExtended)}))})