steps
step7f804761434fc9439d9bd3e24e534b7f
	<step>

	^ ((Dictionary new) add: (#definition->#'6184071b-b12e-3b49-b5d1-9f830266433b'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'9 December 2015 10:30:20 am'); add: (#out->Set); yourself)); add: (#isProperty->false); add: (#next->nil); add: (#label->'Remove duplicates'); add: (#iconCode->'nil'); add: (#id->#'7f804761-434f-c943-9d9b-d3e24e534b7f'); add: (#isReference->false); yourself)