steps
step328d2fd9190c6f40accdafc2029f12c4
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'dea80ea8-d8f4-d643-b24b-c7b6174863ff').
(#iconCode -> 'nil').
(#id -> #'328d2fd9-190c-6f40-accd-afc2029f12c4').
(#isProperty -> false).
(#label -> nil).
(#next -> #'587641c1-faab-d84d-a002-1c90308297e1').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 September 2013 3:17:34 pm').
(#priority -> 4000)
}))
})