steps
step676364194db68c43aa22b3948e02e796
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'1bb9207e-4ee2-404a-8f53-21cee72442ae').
(#iconCode -> 'nil').
(#id -> #'67636419-4db6-8c43-aa22-b3948e02e796').
(#label -> nil).
(#next -> #'42ef8b6b-8cf0-da4a-b075-0fb0146d805c').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Name').
(#priority -> 2780)}))})