steps
step268f1e29abfa184e9be90f251cf2d31b
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'f7a44457-58fa-9242-a06b-06f5a7784f40').
(#iconCode -> 'nil').
(#id -> #'268f1e29-abfa-184e-9be9-0f251cf2d31b').
(#label -> nil).
(#next -> #'5ec06343-4180-cf4d-a211-f78d46a2112e').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '6 December 2013 4:50:48 pm').
(#priority -> 4520)}))})