steps
step3f2ccc8f3fd62243b5e41a2f686ed9bc
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'9b0b0af6-2af2-9d44-a8d0-acb6157978ac').
(#iconCode -> 'nil').
(#id -> #'3f2ccc8f-3fd6-2243-b5e4-1a2f686ed9bc').
(#label -> 'Decompile w/ temps').
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '24 February 2014 10:52:06 am').
(#priority -> 5830).
(#view -> ViTreeViewExtended)}))})