steps
step1862e9705ce1734a85a5265acadcd23e
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'534e7917-9687-cf48-bf46-5d72f3fe518d').
(#iconCode -> 'nil').
(#id -> #'1862e970-5ce1-734a-85a5-265acadcd23e').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Object').
(#priority -> 3000)}))})