steps
step37989d230602ed44ad37440cccc8d6d9
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'761d4da3-eb4c-104a-80c8-256368e993f0').
(#iconCode -> 'nil').
(#id -> #'37989d23-0602-ed44-ad37-440cccc8d6d9').
(#isProperty -> false).
(#isReference -> false).
(#label -> 'Submorphs').
(#next -> #'9a36a312-8950-9d4e-9c29-7386596f007f').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #identity).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 1:01:49 pm').
(#inputKind -> Morph).
(#outputKind -> Morph).
(#priority -> 6010).
(#view -> ViTreeViewExtended)}))})