steps
step1b7534bd882c2d458ff704510695ae1c
	<step>

	^ ((Dictionary new) add: (#definition->#'532b388c-e4ee-b544-be59-7d3619e04e42'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#view->ViMultiPaneTiled); add: (#creationTimeStamp->'19 October 2015 2:07 pm'); add: (#copyOf->#'e3c616ba-4453-c04b-b997-91416620222a'); yourself)); add: (#isProperty->true); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'1b7534bd-882c-2d45-8ff7-04510695ae1c'); add: (#isReference->false); yourself)