steps
step31eeb1cd153aa246b7d86a6b7f6a95b8
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #iconAndLabel).
(#iconCode -> 'nil').
(#id -> #'31eeb1cd-153a-a246-b7d8-6a6b7f6a95b8').
(#label -> nil).
(#next -> #'2af25f9b-ebc0-104e-b6f8-795b2094d0ee').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '15 November 2014 4:29:41 pm').
(#priority -> 8410)}))})