steps
step0bca51add3bce949a5c734cfdb3e7c9e
	<step>

	^ (Dictionary newFrom: {
(#'_def' -> (Dictionary newFrom: {
(#block -> [:in :out | [ExTag knownTags values] value in: [:result |
	out addAll: result asList]]).
(#className -> #ViScriptDefinition).
(#id -> #'7635bfa6-9c0a-5643-88a8-2483e89c6b6f').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '6 March 2020 2:45:23.792696 pm')
})).
(#sourceCode -> '[:in :out | [ExTag knownTags values] value in: [:result |
	out addAll: result asList]]')
})).
(#className -> #ViScriptStep).
(#definition -> #'7635bfa6-9c0a-5643-88a8-2483e89c6b6f').
(#iconCode -> 'nil').
(#id -> #'0bca51ad-d3bc-e949-a5c7-34cfdb3e7c9e').
(#isProperty -> false).
(#label -> 'Exploratory Tags').
(#next -> #'aaf8c9be-2a91-464e-aa05-ba436d51c006').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '6 March 2020 2:45:23.792696 pm').
(#dragType -> #tags).
(#isGlobal -> true).
(#view -> ViTreeViewExtended)
}))
})