steps
step69e497c24f934d4984b194178c53e847
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'ecc82096-e22c-1446-9001-ba0f0f6d0be2').
(#iconCode -> 'nil').
(#id -> #'69e497c2-4f93-4d49-84b1-94178c53e847').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '6 September 2013 8:38:52 pm').
(#priority -> 1020)}))})