steps
stepsimilarDefinitions
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'bcbc9f73-3ca4-0d4e-9933-e2a6d2ea32e4').
(#iconCode -> 'nil').
(#id -> #similarDefinitions).
(#label -> 'Similar Map Definitions').
(#next -> #'754c7a1e-5b33-a842-8a8a-c5f6eef88890').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '4 September 2013 12:59:07 pm').
(#priority -> 650).
(#view -> ViTreeViewExtended)}))})