steps
stepe36efb5e3ac6e540af1c498872dec4b2
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'6dd427e2-9e4e-b745-bda4-948a2487eccb').
(#iconCode -> 'ViEclipseIcons classHiIcon').
(#id -> #'e36efb5e-3ac6-e540-af1c-498872dec4b2').
(#isProperty -> false).
(#label -> 'Type Hierarchy').
(#next -> #'328d2fd9-190c-6f40-accd-afc2029f12c4').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#inputKind -> PackageInfo).
(#outputKind -> ClassDescription).
(#priority -> 3940).
(#view -> ViTreeViewExtended)}))})