steps
stepa8f95d967f396744aca595cde8b9e75e
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'49c0317d-47c4-2c45-9418-f3da6dc99160').
(#iconCode -> 'nil').
(#id -> #'a8f95d96-7f39-6744-aca5-95cde8b9e75e').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 4800)}))})