steps
step45fb3a3839dc2144a747a51f5e49f729
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQuerySortStep).
(#definition -> #'8a71e074-1c14-8145-9e08-3c3261d5d008').
(#iconCode -> 'nil').
(#id -> #'45fb3a38-39dc-2144-a747-a51f5e49f729').
(#label -> nil).
(#next -> #'23d4adf1-41b2-9845-aeb2-2b496e4ea663').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 September 2013 10:17:33 am').
(#priority -> 3660)}))})