steps
stepb873757c58201f4190513c4d8552563b
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'d0b5a035-9bf2-de4c-b1cb-3a62102d515a').
(#iconCode -> 'nil').
(#id -> #'b873757c-5820-1f41-9051-3c4d8552563b').
(#isProperty -> false).
(#label -> nil).
(#next -> #'9e7e3607-1a59-fe4a-a65e-f1f49efaba06').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '3 May 2019 10:53:39.302161 am')}))})