steps
step15556af2d4c72546a09408a896f718e0
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'65c357c4-72de-574c-b285-4b1be70e18e0').
(#iconCode -> 'nil').
(#id -> #'15556af2-d4c7-2546-a094-08a896f718e0').
(#isProperty -> false).
(#label -> nil).
(#next -> #'4af81413-f2f7-de42-9952-7ad762137e12').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 May 2018 5:15:08 pm').
(#inputKind -> #(nil nil))
}))
})