steps
step489ae0c062e565439fdeb10d002ed318
	<step>

	^ ((Dictionary new) add: (#definition->#'ca556f32-a18b-064d-b6a3-28f7d13a5371'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'15 December 2015 10:39:29 am'); yourself)); add: (#isProperty->true); add: (#next->#'8f53a4cc-854f-7843-a59c-68a80249da1d'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'489ae0c0-62e5-6543-9fde-b10d002ed318'); add: (#isReference->false); yourself)