steps
step73c14db0512955439fe9dab9298595fb
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'b5109e4e-f190-3846-b637-5583d25abcce').
(#iconCode -> 'nil').
(#id -> #'73c14db0-5129-5543-9fe9-dab9298595fb').
(#label -> nil).
(#next -> #'97de0441-7aaf-e745-a263-7000ac4db432').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'3947aee4-5c3a-1649-8884-a37f2fcf75e9').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 5920)}))})