steps
stepefdca18a20725c45ac9255b2a17ad4eb
	<step>

	^ ((Dictionary new) add: (#definition->#'0c8f9b64-ae23-9e4a-b4c8-7fbd8f29d864'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'9 December 2015 10:14:14 am'); yourself)); add: (#isProperty->false); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'efdca18a-2072-5c45-ac92-55b2a17ad4eb'); add: (#isReference->true); yourself)