steps
step923010874a3b9841bf34cfaaef53c085
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'4b95cec2-4f9b-6248-a751-79d4c7797732').
(#iconCode -> 'nil').
(#id -> #'92301087-4a3b-9841-bf34-cfaaef53c085').
(#isProperty -> false).
(#label -> nil).
(#next -> #'9caa8ce4-2b82-9b4f-8466-269ee432cdd8').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#outputKind -> Boolean).
(#priority -> 2710)}))})