steps
stepd87b686730987841b98b559b668d9869
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'84ee52f9-c014-804b-b364-628e00c875d7').
(#iconCode -> 'nil').
(#id -> #'d87b6867-3098-7841-b98b-559b668d9869').
(#label -> 'Methods (class-side)').
(#next -> #'92301087-4a3b-9841-bf34-cfaaef53c085').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 700)}))})