steps
stepa127f2fae9457b48b6ca53f8cdfab01b
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'2a4b9a22-ca9a-9e4b-b865-d53c9d8ed827').
(#iconCode -> 'nil').
(#id -> #'a127f2fa-e945-7b48-b6ca-53f8cdfab01b').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'6b51cd4e-c681-064a-b60d-e1552154d686').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '17 January 2014 3:00:32 pm').
(#priority -> 4730)}))})