steps
stepb2c2bd304cbcac47a5a04f683a40bf26
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'25c58bc0-e985-aa41-b91c-42a88a9a8019').
(#iconCode -> 'nil').
(#id -> #'b2c2bd30-4cbc-ac47-a5a0-4f683a40bf26').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'1862e970-5ce1-734a-85a5-265acadcd23e').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#oldTreePaths -> '[:all :obj | {PackageOrganizer default packageOfSystemCategory: obj ifNone: [''(unpackaged)'']. obj}]').
(#priority -> 2990)}))})