steps
step8137f2f30fb0d44ba9b5af172fdbc83d
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupStep).
(#definition -> #'6791d9d6-2faf-3448-8e22-0aa4c948acdc').
(#iconCode -> 'nil').
(#id -> #'8137f2f3-0fb0-d44b-a9b5-af172fdbc83d').
(#label -> nil).
(#next -> #'cffbfe83-0584-d241-8e7b-068442bd8619').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 February 2014 1:34:17 pm').
(#priority -> 5590)}))})