steps
step0a45fa5f6f7ba74bb15f868dcf6a9799
	<step>

	^ ((Dictionary new) add: (#definition->#'042fe827-9b71-854d-8413-7f5befe2d4a5'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'9 December 2015 10:48:47 am'); yourself)); add: (#isProperty->false); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'0a45fa5f-6f7b-a74b-b15f-868dcf6a9799'); add: (#isReference->true); yourself)