steps
step9af0df5a068aa6499aa4230c1f0217cc
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'699d78cd-6dca-ff43-b630-3cdfecd1d06f').
(#iconCode -> 'nil').
(#id -> #'9af0df5a-068a-a649-9aa4-230c1f0217cc').
(#label -> nil).
(#next -> #'47204d81-9a24-5149-ad07-01d582da03b4').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '8 November 2013 4:30:17 pm').
(#priority -> 4260)}))})