steps
step5c2e7b343c999341badbb111a003abb4
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'c7b9f779-af5c-f242-acdd-5b98ebc17cb5').
(#iconCode -> 'nil').
(#id -> #'5c2e7b34-3c99-9341-badb-b111a003abb4').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'P').
(#labelColor -> '#AAAAAA').
(#priority -> 1190)}))})