steps
step4ea99278df36f648a9dcf35da9d613ed
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'650145d8-9f4b-5d4f-9df5-c3b826d9cb0d').
(#iconCode -> 'nil').
(#id -> #'4ea99278-df36-f648-a9dc-f35da9d613ed').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '26 April 2019 8:15:35.2891 am')}))})