steps
stepupdateDefinitions
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'eaacc8b2-4e11-bb4c-ab2b-7aa0583b7467').
(#iconCode -> 'nil').
(#id -> #updateDefinitions).
(#label -> nil).
(#next -> #'ed778e6a-6ace-e540-84c3-af7329c1f656').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '6 September 2013 8:27:11 pm').
(#priority -> 410).
(#view -> ViTreeViewExtended)}))})