steps
step57759e79162b7647b6c7af705463339b
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'6878b8b4-4e3f-354b-86df-a7a1607b09fc').
(#iconCode -> 'nil').
(#id -> #'57759e79-162b-7647-b6c7-af705463339b').
(#label -> nil).
(#next -> #'5401af50-ff0b-9941-b850-35ffa4179d50').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'S').
(#labelColor -> '#AAAAAA').
(#priority -> 1170)}))})