steps
step89d7f52e82713f47b6958c06854f6a85
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'6b3d9fbe-3f81-8048-ab4b-2b31f970a06d').
(#iconCode -> 'nil').
(#id -> #'89d7f52e-8271-3f47-b695-8c06854f6a85').
(#label -> nil).
(#next -> #'89c40fb8-551c-9e46-9651-f11978e9ff30').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 2370)}))})