steps
step37989d230602ed44ad37440cccc8d6d9
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'6731f25c-5705-6843-8e6f-0c4263ca2073').
(#iconCode -> 'nil').
(#id -> #'37989d23-0602-ed44-ad37-440cccc8d6d9').
(#label -> 'Submorphs').
(#next -> #'9a36a312-8950-9d4e-9c29-7386596f007f').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #identity).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 1:01:49 pm').
(#priority -> 6010)}))})