steps
stepae3c2d41a7128f44a52acd39fdb3459b
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'0793b03d-149f-1f4c-bd83-b4baede6bcb3').
(#iconCode -> 'nil').
(#id -> #'ae3c2d41-a712-8f44-a52a-cd39fdb3459b').
(#label -> nil).
(#next -> #'e50787c6-1e43-ad46-9f85-4bc28d2d5568').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 February 2014 1:13:30 pm').
(#headerText -> #cX).
(#priority -> 5430)}))})