steps
step574aa5e19265754a9cdb57e45108ee46
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupStep).
(#definition -> #'f2158056-1072-954d-8dcd-b9744f5a6849').
(#iconCode -> 'nil').
(#id -> #'574aa5e1-9265-754a-9cdb-57e45108ee46').
(#label -> nil).
(#next -> #'37aa1dbd-bbd2-b242-9c7d-2efb85ce5e27').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '3 September 2013 3:36:18 pm').
(#priority -> 2390)}))})