steps
step2ea23721a871ea4687986a4a5be4cb8e
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'59f27a24-23d1-9d49-a383-5d12c3815d83').
(#iconCode -> 'nil').
(#id -> #'2ea23721-a871-ea46-8798-6a4a5be4cb8e').
(#isProperty -> false).
(#isReference -> true).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '7 September 2013 10:46:54 am').
(#priority -> 1060)}))})