steps
step688b9e53cc309341a36854f6c47e402c
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'0c53b73c-4e16-1542-b40c-cd76a3b1dda5').
(#iconCode -> 'nil').
(#id -> #'688b9e53-cc30-9341-a368-54f6c47e402c').
(#label -> nil).
(#next -> #'d86f12e2-c38d-4e4e-807e-4615652c2137').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'d9634b11-bde6-1a40-a0b4-7be880afc37a').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 3950)}))})