steps
step25668ab353832a4b8bc25d22ac2cc3fe
	<step>

	^ (Dictionary newFrom: {
(#'_def' -> (Dictionary newFrom: {
(#block -> [:in :out | out addAll: ([:objects | objects] value: in)]).
(#className -> #ViScriptDefinition).
(#id -> #'dbc59c50-40d2-ff48-a609-d212aa403acf').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')
})).
(#sourceCode -> '[:in :out | out addAll: ([:objects | objects] value: in)]')
})).
(#className -> #ViScriptStep).
(#definition -> #'dbc59c50-40d2-ff48-a609-d212aa403acf').
(#iconCode -> 'nil').
(#id -> #'25668ab3-5383-2a4b-8bc2-5d22ac2cc3fe').
(#isProperty -> false).
(#label -> nil).
(#next -> #'12f3cc3b-319f-8842-a3d9-43b6034d0539').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 September 2013 7:19:58 pm').
(#priority -> 3430)
}))
})