steps
step800f6eb35d933a44b9d4965af821cc38
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'d29a5c0a-426e-9347-9436-95c9da32e38c').
(#iconCode -> 'nil').
(#id -> #'800f6eb3-5d93-3a44-b9d4-965af821cc38').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'a36810b7-a281-b34d-9d22-e1f1a585db30').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '23 September 2013 5:15:04 pm').
(#priority -> 4120)}))})