steps
step894088c29d245b4092462e1a298fe761
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'405e59d0-1889-a842-a4e4-d779e69f8968').
(#iconCode -> 'UiSilkIcons chartBarIcon').
(#id -> #'894088c2-9d24-5b40-9246-2e1a298fe761').
(#isProperty -> false).
(#isReference -> false).
(#label -> 'Sorted Bars').
(#next -> #'d740eb73-4267-9240-86ce-b2cb2018f68a').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 November 2013 3:30:24 pm').
(#inputKind -> Bag).
(#priority -> 4360).
(#view -> ViTreeViewExtended)}))})