steps
stepe6cb8658369738499a2cfae04d157f52
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryReferenceStep).
(#definition -> nil).
(#iconCode -> 'nil').
(#id -> #'e6cb8658-3697-3849-9a2c-fae04d157f52').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '29 March 2019 5:00:11.34035 pm')})).
(#reference -> #'d62c8659-3292-5541-b3b6-08b9ff46de99')})