steps
step07540f0c6cdad44eb2729d619e7cdcff
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'595f22af-5b39-df47-82fc-bfe9343c2c57').
(#iconCode -> 'nil').
(#id -> #'07540f0c-6cda-d44e-b272-9d619e7cdcff').
(#label -> nil).
(#next -> #'635ee7ee-dfa7-1342-a9c2-f1e54ca14660').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Implementor').
(#priority -> 2250)}))})