steps
step3947aee45c3a16498884a37f2fcf75e9
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'d8985e4a-16e9-8643-9143-06e11ad06235').
(#iconCode -> 'nil').
(#id -> #'3947aee4-5c3a-1649-8884-a37f2fcf75e9').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1390)}))})