steps
stepd74bf7b995099b4caa8731ad835a95b3
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'eb571ae7-5c70-8146-bc63-3c95f8732935').
(#iconCode -> 'nil').
(#id -> #'d74bf7b9-9509-9b4c-aa87-31ad835a95b3').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '14 February 2018 9:22:10 am').
(#hAlignment -> #right)}))})