steps
step78e13ff4d0931140b575be2225a6eaf7
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'e5934e3d-2e4b-1248-a3b8-c63c2ff2c3c2').
(#iconCode -> 'nil').
(#id -> #'78e13ff4-d093-1140-b575-be2225a6eaf7').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'3a47c56d-3e11-344a-8b45-cc59f6ba7fb5').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '14 February 2014 10:53:40 am').
(#headerText -> #cU).
(#priority -> 5400)}))})