steps
stepfa4cb8bff5a3134c8ce140866732e786
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'40093673-2fdf-b840-88df-27cb7e5cce38').
(#iconCode -> 'nil').
(#id -> #'fa4cb8bf-f5a3-134c-8ce1-40866732e786').
(#isProperty -> false).
(#label -> nil).
(#next -> #'2e490b12-bdf7-7341-b907-18df5b218b85').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '3 January 2014 3:44:19 pm').
(#inputKind -> DirectoryEntry).
(#outputKind -> DirectoryEntryDirectory).
(#priority -> 4610).
(#view -> ViTreeViewExtended)
}))
})