steps
step11617cd4f3dab347b26437a8dd9e6a46
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'096ea106-96b9-854f-a70b-c5a6e40a7fe9').
(#iconCode -> 'nil').
(#id -> #'11617cd4-f3da-b347-b264-37a8dd9e6a46').
(#isProperty -> false).
(#isReference -> false).
(#label -> 'Users').
(#next -> #'43770565-2816-9048-8e6e-7364ba7aab35').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#inputKind -> ViSmalltalkHub).
(#priority -> 550).
(#view -> ViTreeViewExtended)}))})