steps
steped47392de9cfe24c9069a3a89fba2ea6
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'22e2e96d-767f-7242-ac18-79b9438046bc').
(#iconCode -> 'nil').
(#id -> #'ed47392d-e9cf-e24c-9069-a3a89fba2ea6').
(#label -> nil).
(#next -> #'aa477db3-7d10-1f48-8339-140e6d470e38').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 February 2014 9:43 am').
(#priority -> 5110)}))})