steps
stepb15f906e0d17994c9585d7487285b6d2
	<step>

	^ ((Dictionary new) add: (#definition->#'6b27229b-8de9-af48-8277-e920eda66d72'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 October 2015 3:43 pm'); yourself)); add: (#isProperty->true); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'b15f906e-0d17-994c-9585-d7487285b6d2'); add: (#isReference->false); yourself)