steps
step1a584c05b8fcdc438564d48f2c2b954b
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'712a4be8-7568-4e4c-8210-de3af483673b').
(#iconCode -> 'UiFugueIcons keyboardExclamationIcon').
(#id -> #'1a584c05-b8fc-dc43-8564-d48f2c2b954b').
(#isProperty -> false).
(#label -> 'Inconsistent grab-/hasKeyboard').
(#next -> #'5b3d233e-c93c-0b42-b8ba-fafb41d70a9e').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#inputKind -> PackageInfo).
(#priority -> 740).
(#view -> ViTreeViewExtended)}))})