steps
stepe548783510a59d408ab06f95df9b5740
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'5cb3fb68-7cf3-d14f-95fa-7e7848b86e0a').
(#iconCode -> 'nil').
(#id -> #'e5487835-10a5-9d40-8ab0-6f95df9b5740').
(#isProperty -> false).
(#isReference -> false).
(#label -> 'DBLP Search').
(#next -> #'b1afac3a-0000-8544-9dce-ebfda96b30b6').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '21 May 2014 5:56:13 pm').
(#inputKind -> String).
(#priority -> 6110).
(#view -> ViTreeViewExtended)}))})