steps
step40560165a4c74042974090e250b56bd7
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupSortStep).
(#definition -> #'563021ef-44a7-e24e-beb7-6201088a6f24').
(#iconCode -> 'nil').
(#id -> #'40560165-a4c7-4042-9740-90e250b56bd7').
(#label -> nil).
(#next -> #'24a9922a-802c-1543-acf7-ff6d8dc30bbf').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 September 2013 7:28:52 pm').
(#priority -> 3460)}))})