steps
step41ca5cdb0dc1394b8048c5f08293cdd7
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'e896078d-10f0-8d44-8b3e-4005b2543810').
(#iconCode -> 'nil').
(#id -> #'41ca5cdb-0dc1-394b-8048-c5f08293cdd7').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 4:21:57 pm').
(#headerText -> 'Code').
(#labelColor -> '#AAAAAA').
(#priority -> 3250)}))})