steps
step494bc6a5c09dfc4fb22f37955f890e49
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'595f22af-5b39-df47-82fc-bfe9343c2c57').
(#iconCode -> 'nil').
(#id -> #'494bc6a5-c09d-fc4f-b22f-37955f890e49').
(#label -> nil).
(#next -> #'31d2b64c-44d3-5c47-964f-83802a1f927f').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Implementor').
(#priority -> 1640)}))})