steps
stepe5bd3f6cf63fb14889bc82784354babd
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'71ff792c-38c4-3940-af3d-ef08247f2377').
(#iconCode -> 'nil').
(#id -> #'e5bd3f6c-f63f-b148-89bc-82784354babd').
(#label -> nil).
(#next -> #'57759e79-162b-7647-b6c7-af705463339b').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Modified').
(#labelColor -> '#AAAAAA').
(#priority -> 1160)}))})