steps
stepf7ba224a8f8ec1479bec928cd5537411
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'ae614fa7-bdf2-4940-8e18-ad7542e24f44').
(#iconCode -> 'nil').
(#id -> #'f7ba224a-8f8e-c147-9bec-928cd5537411').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'ed4cdeb4-e8e8-f64a-9016-e09729155d02').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '9 December 2015 1:06:03 pm')}))})