steps
stepcfe6ad6fad06774fb19c5dc3bea7243e
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'6d70e1a8-c3b4-5645-b670-8094af824d8f').
(#iconCode -> 'nil').
(#id -> #'cfe6ad6f-ad06-774f-b19c-5dc3bea7243e').
(#isProperty -> true).
(#label -> nil).
(#next -> #'b72e75d1-03bb-7541-a46e-39fd55b28333').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 September 2013 6:08:11 pm').
(#labelColor -> #AAAAAA).
(#priority -> 3280)}))})