steps
step4ce2b7cd1c438241a5bdca0484e682df
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'6f810333-b153-6840-9279-c28ab3ecd6e1').
(#iconCode -> 'nil').
(#id -> #'4ce2b7cd-1c43-8241-a5bd-ca0484e682df').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'225b70fb-8963-d84a-a825-589a864d6670').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Object').
(#priority -> 2860)}))})