steps
stepc399546cfcff9046bd660f7b1f946123
	<step>

	^ ((Dictionary new) add: (#definition->#'22c0349c-80c3-a744-b79a-34b8a256c7f4'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'15 December 2015 10:39:58 am'); yourself)); add: (#isProperty->false); add: (#next->#'1fb44024-f23f-3244-bc57-a9be90f3ccdb'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'c399546c-fcff-9046-bd66-0f7b1f946123'); add: (#isReference->false); yourself)