steps
step9e7e36071a59fe4aa65ef1f49efaba06
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'7756d9a8-ea6d-8741-9a96-2007bf30c05b').
(#iconCode -> 'nil').
(#id -> #'9e7e3607-1a59-fe4a-a65e-f1f49efaba06').
(#isProperty -> true).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '3 May 2019 10:47:42.408161 am')}))})