steps
stepdd25524a769693498a4fd4d5e5251018
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'1195debd-b461-4a4c-8786-7b2843fb0c9b').
(#iconCode -> 'nil').
(#id -> #'dd25524a-7696-9349-8a4f-d4d5e5251018').
(#isProperty -> false).
(#isReference -> true).
(#label -> nil).
(#next -> #'d1ab46b3-df50-534c-b593-d1e6683fe045').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:12.926834 pm')}))})