steps
stepd26547cfb2f4db40936bbd8537ca6228
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'753f301e-b355-874c-bfcf-680be25ffbaf').
(#iconCode -> 'nil').
(#id -> #'d26547cf-b2f4-db40-936b-bd8537ca6228').
(#isProperty -> false).
(#label -> nil).
(#next -> #'34fc784f-f465-5b4d-8acf-4f6f5d16883e').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '1 February 2016 2:00:11 pm').
(#inputKind -> #(nil nil))}))})