steps
step91982915045f1f44ab9b723d7bbdf298
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupSortStep).
(#definition -> #'b9a69dcc-6839-3a4a-a9c3-adae96c6c0e4').
(#iconCode -> 'nil').
(#id -> #'91982915-045f-1f44-ab9b-723d7bbdf298').
(#label -> nil).
(#next -> #'519d344e-f031-2a43-8e42-34a9f07b61f9').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1590)}))})