steps
stepc185247b7a50f045a2a1b24c4e26d2b4
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'4b0169bd-ee95-3241-bfef-5821cab9ce45').
(#iconCode -> 'nil').
(#id -> #'c185247b-7a50-f045-a2a1-b24c4e26d2b4').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Class').
(#labelColor -> '#AAAAAA').
(#priority -> 2320)}))})