steps
stepfb20347b7a6fbe43bd7888492dc2d4b1
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'8068b6a4-5651-ed4e-bf4b-38809290491d').
(#iconCode -> 'nil').
(#id -> #'fb20347b-7a6f-be43-bd78-88492dc2d4b1').
(#label -> nil).
(#next -> #'0fdcdea8-5071-914b-ab0c-5d6335ce985f').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '18 September 2013 4:35:12 pm').
(#priority -> 3720)}))})