steps
stepa58a2d7b43281740a7b5288db0764a2b
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'80e4df8f-da7e-e94c-b861-23e0e23d386d').
(#iconCode -> 'nil').
(#id -> #'a58a2d7b-4328-1740-a7b5-288db0764a2b').
(#isProperty -> true).
(#label -> nil).
(#next -> #'b15f906e-0d17-994c-9585-d7487285b6d2').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 October 2015 2:07 pm')
}))
})