steps
stepunsavedChanges
	<step>

	^ ((Dictionary new) add: (#definition->#'2822a617-9ef3-d644-98ed-f98dbb95168f'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#notifier->ViSystemChangeNotifier); add: (#creationTimeStamp->'19 October 2015 10:57:19 am'); yourself)); add: (#isProperty->false); add: (#next->#'012db9f4-4e1e-cc49-aa55-265d82592ec7'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#unsavedChanges); add: (#isReference->false); yourself)