steps
stepc68e2eafff3feb4b9f5174527cb495ac
	<step>

	^ ((Dictionary new) add: (#definition->#'dade81d8-25ea-b745-9fab-eccaa538e7b0'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'7 December 2015 2:00:40 pm'); yourself)); add: (#isProperty->true); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'c68e2eaf-ff3f-eb4b-9f51-74527cb495ac'); add: (#isReference->false); yourself)