steps
step0d821eecf78fd44e80df96d6b534a947
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'421e61ea-a76a-f04c-9881-4c68845a862d').
(#iconCode -> 'nil').
(#id -> #'0d821eec-f78f-d44e-80df-96d6b534a947').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'f99cba1c-d720-4545-ac10-5a57f620226d').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 2460)}))})