steps
step02594c645f169449af33fb7d5bcdd662
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupStep).
(#definition -> #'4bd59430-a20c-da41-8120-fdbb4aeeefc3').
(#iconCode -> 'nil').
(#id -> #'02594c64-5f16-9449-af33-fb7d5bcdd662').
(#label -> nil).
(#next -> #'68476311-41ac-3445-9df5-321d8834e6f7').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1130)}))})