steps
stepfd62bf2f377ce64ab62a4f2399a054e1
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'5158517a-5763-7048-a1fc-00307cafd0c1').
(#iconCode -> 'nil').
(#id -> #'fd62bf2f-377c-e64a-b62a-4f2399a054e1').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'4b13c5ec-1484-1b45-b800-ac2bd6af1360').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#inputKind -> MethodReference).
(#outputKind -> String).
(#priority -> 1210)}))})