steps
steprecoverUnsavedScripts
	<step>

	^ ((Dictionary new) add: (#definition->#'110ae7b7-c003-5f4f-8bce-b8ec5d33741f'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isGlobal->true); add: (#creationAuthor->'mt'); add: (#view->ViMultiPaneTiled); add: (#creationTimeStamp->'19 October 2015 2:07 pm'); add: (#copyOf->#'9495a7a1-36da-3645-afa0-bb85011e21d1'); add: (#isNew->false); add: (#optimalExtent->(638@382)); yourself)); add: (#isProperty->true); add: (#next->#'1b7534bd-882c-2d45-8ff7-04510695ae1c'); add: (#label->'Recover Unsaved Scripts'); add: (#iconCode->'nil'); add: (#id->#recoverUnsavedScripts); add: (#isReference->false); yourself)