steps
step661f2767d34f6a4fb8ff8ec4307d757f
	<step>

	^ ((Dictionary new) add: (#definition->#'59426283-fdda-b346-92ea-5fb39aebb54b'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isGlobal->true); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'22 July 2015 9:47:58 am'); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->#'c31cf538-fe89-4242-bd60-cf299527d31f'); add: (#label->'Recently Opened'); add: (#iconCode->'nil'); add: (#id->#'661f2767-d34f-6a4f-b8ff-8ec4307d757f'); add: (#isReference->false); yourself)