steps
step4b63ef1b75d9fc4d977720db142525af
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'61d466bc-34b3-d14d-ad0c-371ec9f29cbe').
(#iconCode -> 'nil').
(#id -> #'4b63ef1b-75d9-fc4d-9777-20db142525af').
(#isProperty -> false).
(#label -> 'Browse object''s class').
(#next -> #'efdca18a-2072-5c45-ac92-55b2a17ad4eb').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '9 December 2015 10:14:14 am').
(#inputKind -> Object).
(#priority -> 1000)
}))
})