steps
steped4cdeb4e8e8f64a9016e09729155d02
	<step>

	^ ((Dictionary new) add: (#definition->#'6034a8ad-a5b2-e14b-9a6a-6ad8fcd2565e'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'9 December 2015 1:13:34 pm'); yourself)); add: (#isProperty->false); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'ed4cdeb4-e8e8-f64a-9016-e09729155d02'); add: (#isReference->true); yourself)