steps
step2d85f346bb1a7248b288a0b9d762b977
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'61579026-79be-ff43-b0de-f9ca7b8e6c4c').
(#iconCode -> 'nil').
(#id -> #'2d85f346-bb1a-7248-b288-a0b9d762b977').
(#label -> 'Large Methods').
(#next -> #'63c84001-9d52-ee47-b4a7-446b7242ea74').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 920)}))})