steps
stepobjectExplorer
	<step>

	^ ((Dictionary new) add: (#definition->#'9f3b781a-255d-f245-bee1-3fcf39040b9d'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#priority->500); add: (#view->ViExplorerView); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'12 November 2015 11:56:40 am'); yourself)); add: (#isProperty->false); add: (#next->nil); add: (#label->'Inspector'); add: (#iconCode->'UiFugueIcons magnifierMediumIcon'); add: (#id->#objectExplorer); add: (#isReference->false); yourself)