steps
stepab4af50f105f424d95d136bfd2f47ad3
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'0f52af7d-7abd-8649-9ab1-e4f61fd55256').
(#iconCode -> 'nil').
(#id -> #'ab4af50f-105f-424d-95d1-36bfd2f47ad3').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'78e451df-ad36-ef4d-9e21-2fb3e7bae0f1').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 10:18:31 am').
(#priority -> 5020)}))})