steps
stepd5db789c076fb7409144a2bd2740df7f
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQuerySortStep).
(#definition -> #'4ed0c304-26af-fe48-8259-0553dbe3f8e0').
(#iconCode -> 'nil').
(#id -> #'d5db789c-076f-b740-9144-a2bd2740df7f').
(#label -> nil).
(#next -> #'ff9ce8ad-7d0d-4744-afba-f53a7a933bd9').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '20 February 2014 6:27:55 pm').
(#priority -> 5760)}))})