steps
step074a7165102004428a76a2ce9f8ab3e6
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'08224455-89e8-1b48-b01d-de8f5a01861d').
(#iconCode -> 'UiFugueIcons questionBalloonIcon').
(#id -> #'074a7165-1020-0442-8a76-a2ce9f8ab3e6').
(#label -> 'Uncommented Classes').
(#next -> #'e847db70-263a-3b49-a792-9d80a42da426').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '13 September 2013 7:46:24 pm').
(#priority -> 3510)}))})