steps
stepb732f87518c21841b5ddbd4145efb573
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'656c8166-7060-fa4b-b228-496749942bb7').
(#iconCode -> 'nil').
(#id -> #'b732f875-18c2-1841-b5dd-bd4145efb573').
(#isProperty -> false).
(#isReference -> false).
(#label -> 'Categories w/ tests').
(#next -> #'317d2dd4-f602-6f42-8e66-0e85184667f6').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 February 2014 11:25:12 am').
(#outputKind -> Behavior).
(#priority -> 5220).
(#view -> ViTreeViewExtended)}))})