steps
step044ec24710c99946a6bc5044f6bc4a4d
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'982afa1e-5280-254c-b404-f3f9ba5ff8c6').
(#iconCode -> 'nil').
(#id -> #'044ec247-10c9-9946-a6bc-5044f6bc4a4d').
(#label -> nil).
(#next -> #'0c69c004-a3f9-134e-8ba6-eafca2418592').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '10 February 2014 4:49:24 pm').
(#priority -> 850).
(#view -> ViTreeViewExtended)}))})