steps
step3db4c5e34863b44d8ff1423f40829e70
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'95c882ee-df97-bb48-bfb5-fadeedf09205').
(#iconCode -> 'UiFugueIcons scriptsTextIcon').
(#id -> #'3db4c5e3-4863-b44d-8ff1-423f40829e70').
(#label -> 'Methods').
(#next -> #'d89cc752-73e4-0742-ac29-eb770d5d8fc5').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 140)}))})