steps
step94656720b2617643b66b32d00c16754b
	<step>

	^ (Dictionary newFrom: {
(#className -> #ViScriptStep).
(#definition -> #'a5d3d64d-28a1-be49-85df-9c94537ddf9a').
(#iconCode -> 'nil').
(#id -> #'94656720-b261-7643-b66b-32d00c16754b').
(#isProperty -> true).
(#label -> nil).
(#next -> #'22eb1ddf-ec8c-aa42-8df3-0d982e958000').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '10 April 2019 11:10:50.31711 am')
}))
})