steps
stepab5e2d3f7d8bc347a60ef14d4961675d
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptStep).
(#definition -> #'50e9a0ec-2167-c64a-bee7-229f874422b8').
(#iconCode -> 'nil').
(#id -> #'ab5e2d3f-7d8b-c347-a60e-f14d4961675d').
(#isProperty -> false).
(#label -> nil).
(#next -> #'3f4d3ab2-a67d-054b-9bf8-eec6d9a0bfe2').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '14 December 2015 11:52:58 am')}))})