steps
step4a7cf538185acd4d8cc2bfea887bdc3f
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'489f8155-83b3-5d42-8ac0-16fea5427b26').
(#iconCode -> 'nil').
(#id -> #'4a7cf538-185a-cd4d-8cc2-bfea887bdc3f').
(#label -> 'Lines of Code').
(#next -> #'7df281f1-3570-9440-b69e-f00d41128ad0').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'728402d7-f870-e743-8d2a-abf2353efba1').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 4750)}))})