steps
stepb3b8787175165049b09272ad966f3216
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'06f98eeb-a401-204f-b4af-9c40942ce7b0').
(#iconCode -> 'nil').
(#id -> #'b3b87871-7516-5049-b092-72ad966f3216').
(#isProperty -> false).
(#isReference -> false).
(#label -> 'Special Scripts').
(#next -> #'757cd24a-516e-bf45-ad50-d29635e9bbee').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 1:01:49 pm').
(#inputKind -> ViScriptOrganizer).
(#outputKind -> ViQueryStep).
(#priority -> 300).
(#view -> ViTreeViewExtended)}))})