steps
stepf28761367eb8e94b864d61f883d28db9
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'1d838e84-c8f6-1549-b787-c8352fea384d').
(#iconCode -> 'nil').
(#id -> #'f2876136-7eb8-e94b-864d-61f883d28db9').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'1f71149b-9a66-7343-a8bc-932007c75e1f').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '23 September 2013 5:09:20 pm').
(#priority -> 4100)}))})