steps
step4e83040adb7bc9418c4ff03b8556fca4
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'8c0498e4-ef4a-7d40-9aa5-9449da21d72b').
(#iconCode -> 'nil').
(#id -> #'4e83040a-db7b-c941-8c4f-f03b8556fca4').
(#label -> 'Methods by Protocol').
(#next -> #'601f4f47-9545-0e4e-abef-e7b5dc4c0c3e').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #identity).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 1:01:49 pm').
(#priority -> 5660).
(#view -> ViTreeViewExtended)}))})