steps
step01ee0bd60573124cb84a3d699a2e3263
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'2d4505f2-f723-6c42-ba5b-f3cc0d3c03c7').
(#iconCode -> 'nil').
(#id -> #'01ee0bd6-0573-124c-b84a-3d699a2e3263').
(#isProperty -> false).
(#isReference -> true).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '14 December 2015 11:30:58 am')}))})