steps
stepf26673ea2933404485916b54ef8f3949
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'af6f56fc-2069-b84a-a1cb-5dcd0c363c67').
(#iconCode -> 'nil').
(#id -> #'f26673ea-2933-4044-8591-6b54ef8f3949').
(#isProperty -> false).
(#isReference -> true).
(#label -> nil).
(#next -> #'519d344e-f031-2a43-8e42-34a9f07b61f9').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 April 2019 4:48:12.292834 pm')}))})