steps
stepc656fd1e4df72247b673381f86e04eef
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'8cd44e71-e224-234c-84af-614a4b0ac44f').
(#iconCode -> 'nil').
(#id -> #'c656fd1e-4df7-2247-b673-381f86e04eef').
(#label -> nil).
(#next -> #'89d7f52e-8271-3f47-b695-8c06854f6a85').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Tally').
(#labelColor -> '#AAAAAA').
(#priority -> 2360)}))})