steps
stepe957bc9e51f13b4eac097f23d6c54160
	<step>

	^ (Dictionary newFrom: {
(#'_def' -> (Dictionary newFrom: {
(#block -> [:in :out | out addAll: ([:objects | objects] value: in)]).
(#className -> #ViScriptDefinition).
(#id -> #'a47ba519-4202-6e41-b76e-c19d8e8ab81a').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')
})).
(#sourceCode -> '[:in :out | out addAll: ([:objects | objects] value: in)]')
})).
(#className -> #ViScriptStep).
(#definition -> #'a47ba519-4202-6e41-b76e-c19d8e8ab81a').
(#iconCode -> 'nil').
(#id -> #'e957bc9e-51f1-3b4e-ac09-7f23d6c54160').
(#isProperty -> false).
(#label -> 'Commands').
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 1:01:49 pm').
(#priority -> 6450).
(#view -> ViTreeViewExtended)
}))
})