pages
keyboardShortcuts

	^ ViHelpTopic
		title: 'Keyboard Shortcuts'
		icon: UiFugueIcons keyboardIcon
		contents: '<b>Keyboard Shortcuts</b>

1. General
<tab>cmd + k<tab><tab>... open locator
<tab>cmd + left/right<tab>... toggle list/query side
<tab>cmd + up/down<tab>... navigate artifacts
<tab>cmd + w<tab><tab>... close artifact

2. Source Code Editors
<tab>cmd + s<tab>... accept changes
<tab>cmd + l<tab><tab>... reject changes
<tab>cmd + t<tab><tab>... execute and trace piece of code
<tab>cmd + o<tab>... open selected symbol (i.e., selector, class, global variable)
<tab>cmd + d<tab>... do it
<tab>cmd + i<tab><tab>... inspect it
<tab>cmd + shift + i<tab>... explore it (same as inspect)
<tab>cmd + b<tab>... browse classes, packages

3. In-place Editors
<font color="#AAAAAA">For example, pressing the space bar on bookmarked objects.</font>
<tab>escape<tab>... reject changes
<tab>return<tab>... accept changes
<tab>space<tab>... invoke in-place editor

4. Editable Lists
<tab>del<tab>... remove entry
'