pages
readme

	^ ViHelpTopic
		title: 'Important Notes'
		icon: UiFugueIcons stickyNotesTextIcon
		contents: '<b>Important Notes</b><br>
1. Restoring Editor States
The class <b>Vivide</b> keeps track of bookmarked editor states. Clear all states with #editorStatesClear. Restore entry points with #addTranscriptState.

2. Drag and Drop
Almost everything in VIVIDE is about drag and drop. Every list item can be dragged and dropped into other lists.
'