*VivideContextS-commands
command8373d15fa388904891c210897796b269
	<command>

	^ ((Dictionary new) add: (#definition->#'cd9c47a9-0d3a-5049-b600-37ebdf0e6fdd'); add: (#class->ViQueryCommand); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'23 May 2014 1:34:09 pm'); yourself)); add: (#id->#'8373d15f-a388-9048-91c2-10897796b269'); add: (#iconCode->'nil'); add: (#label->'Unpause'); yourself)