*VivideContextS-commands
command2bf8c246262b0a46ab339f7cb92791b3
	<command>

	^ ((Dictionary new) add: (#definition->#'a832b6cc-f85c-494a-8d83-acf2650ca60f'); add: (#class->ViQueryCommand); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'23 May 2014 3:11 pm'); yourself)); add: (#id->#'2bf8c246-262b-0a46-ab33-9f7cb92791b3'); add: (#iconCode->'nil'); add: (#label->'Deactivate Global'); yourself)