*VivideContextS-commands
commandd64b094467e9b4439071117cf67f75b6
	<command>

	^ ((Dictionary new) add: (#definition->#'78b61279-0710-b24c-8c58-bfb46f0981be'); add: (#class->ViQueryCommand); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'23 May 2014 1:33:45 pm'); yourself)); add: (#id->#'d64b0944-67e9-b443-9071-117cf67f75b6'); add: (#iconCode->'nil'); add: (#label->'Pause'); yourself)