*VivideContextS-commands
commandca2681fc2274bb418f71dbf158770b94
	<command>

	^ ((Dictionary new) add: (#definition->#'52ac1185-8984-ec44-80be-ebbdc0e50134'); add: (#class->ViQueryCommand); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 May 2014 1:12:59 pm'); yourself)); add: (#id->#'ca2681fc-2274-bb41-8f71-dbf158770b94'); add: (#iconCode->'nil'); add: (#label->'Activate'); yourself)