*VivideContextS-commands
command3708832d091b1643aad7c8257be63119
	<command>

	^ ((Dictionary new) add: (#definition->#'bef8011e-aa73-284e-98b3-80cfaa34869d'); add: (#class->ViQueryCommand); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 May 2014 1:13:08 pm'); yourself)); add: (#id->#'3708832d-091b-1643-aad7-c8257be63119'); add: (#iconCode->'nil'); add: (#label->'Deactivate'); yourself)