*VivideContextS-definitions
def0cdd7d37bb9fbc41aeecdf79cd5e8854
	<definition>

	^ ((Dictionary new) add: (#inputKind->CSPartialMethod); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'2 June 2014 5:44:56 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'0cdd7d37-bb9f-bc41-aeec-df79cd5e8854'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:partialMethod | #text -> partialMethod method getSource]'); add: (#mapType->#each); add: (#block->[:partialMethod | #text -> partialMethod method getSource]); yourself)