*VivideContextS-definitions
def0d1ad7896b313446bda5282984dc7b6d
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'3 June 2014 11:03:51 am'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'0d1ad789-6b31-3446-bda5-282984dc7b6d'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:method | method isContextSMethod
	ifFalse: [{method}]
	ifTrue: [(method methodChainFor: Processor activeProcess csInfo activeLayers)]]'); add: (#mapType->#each); add: (#block->[:method | method isContextSMethod
	ifFalse: [{method}]
	ifTrue: [(method methodChainFor: Processor activeProcess csInfo activeLayers)]]); yourself)