*VivideContextS-definitions
def1922f79b8c99dd4a9d048ddb2ce7aa39
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'24 May 2014 6:18:30 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'1922f79b-8c99-dd4a-9d04-8ddb2ce7aa39'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:method | method asPartialMethod]'); add: (#mapType->#each); add: (#block->[:method | method asPartialMethod]); yourself)