*VivideContextS-definitions
def179f66ed713fcc4cb4d489137a8864b3
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'10 January 2014 9:16:26 am'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'179f66ed-713f-cc4c-b4d4-89137a8864b3'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:method | (method methodClass organization categoryOfElement: method selector) ifNil: [''(no protocol)'']]'); add: (#mapType->#each); add: (#block->[:method | (method methodClass organization categoryOfElement: method selector) ifNil: ['(no protocol)']]); yourself)