*VivideContextS-definitions
def2c62f0239bde3740bac368e27a73f19f
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'24 May 2014 6:23:09 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'2c62f023-9bde-3740-bac3-68e27a73f19f'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:pm | {#text -> (pm layers ifEmpty: [''<base>'']). #icon -> ViIcons blankIcon}]'); add: (#mapType->#each); add: (#block->[:pm | {#text -> (pm layers ifEmpty: ['<base>']). #icon -> ViIcons blankIcon}]); yourself)