*VivideContextS-definitions
def347ae8d237725444af7bdad76fa6d741
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'15 May 2014 11:58:28 am'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'347ae8d2-3772-5444-af7b-dad76fa6d741'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:layer | layer allContainingPartialMethods]'); add: (#mapType->#each); add: (#block->[:layer | layer allContainingPartialMethods]); yourself)