*VivideContextS-definitions
def4d76a99a96d7c94281baba84c6acfde1
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'2 June 2014 5:39:22 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'4d76a99a-96d7-c942-81ba-ba84c6acfde1'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:partialMethod | #text -> partialMethod methodClass]'); add: (#mapType->#each); add: (#block->[:partialMethod | #text -> partialMethod methodClass]); yourself)