*VivideContextS-definitions
def52ac11858984ec4480beebbdc0e50134
	<definition>

	^ ((Dictionary new) add: (#class->ViQuerySnippetDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 May 2014 1:12:19 pm'); yourself)); add: (#id->#'52ac1185-8984-ec44-80be-ebbdc0e50134'); add: (#inputKind->CSLayer); add: (#block->nil); add: (#sourceCode->'self layerName activateLayerInCurrentProcess.'); add: (#receiverIsCollection->false); yourself)