*VivideContextS-definitions
def51bc4aec08241e40a75ec6e7c19124ee
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'23 May 2014 11:59:28 am'); yourself)); add: (#updateClearDefinition->#'da5a4e6c-d742-3945-ba5c-b1e6625d0dcf'); add: (#outputKind->Object); add: (#id->#'51bc4aec-0824-1e40-a75e-c6e7c19124ee'); add: (#updateSetDefinition->#'9d46436c-f164-ed49-bd02-da3fa8e10342'); add: (#sourceCode->'[:csInfo | csInfo activeLayers collect: [:layerName | CSLayer layerNamed: layerName]]'); add: (#mapType->#each); add: (#block->[:csInfo | csInfo activeLayers collect: [:layerName | CSLayer layerNamed: layerName]]); yourself)