*VivideContextS-definitions
def618e53edeaf54d4aa8b275f8ad843c99
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'10 January 2014 9:21:38 am'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'618e53ed-eaf5-4d4a-a8b2-75f8ad843c99'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:pm | {
	#text -> pm layers.
	#icon -> ((pm method literalStrings anySatisfy: [:literal | literal asString startsWith: #proceed])
		ifTrue: [UiFugueIcons control000SmallIcon] ifFalse: [ViIconService blankIcon])}]'); add: (#mapType->#each); add: (#block->[:pm | {
	#text -> pm layers.
	#icon -> ((pm method literalStrings anySatisfy: [:literal | literal asString startsWith: #proceed])
		ifTrue: [UiFugueIcons control000SmallIcon] ifFalse: [ViIconService blankIcon])}]); yourself)