*VivideContextS-definitions
def7d71234755d73042816324efc7032741
	<definition>

	^ ((Dictionary new) add: (#inputKind->Process); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'23 May 2014 11:58:50 am'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'7d712347-55d7-3042-8163-24efc7032741'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:process | process csInfo]'); add: (#mapType->#each); add: (#block->[:process | process csInfo]); yourself)