*VivideContextS-definitions
def7ee45678c6058543932de918a1ed92e1
	<definition>

	^ ((Dictionary new) add: (#inputKind->PackageInfo); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'15 May 2014 1:26:28 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'7ee45678-c605-8543-932d-e918a1ed92e1'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:pkg |
	#(withLayerDo: withLayersDo: activateLayersInCurrentProcess activateLayerInCurrentProcess) gather: [:message |
	SystemNavigation default allCallsOn: message localToPackage: pkg]]'); add: (#mapType->#each); add: (#block->[:pkg |
	#(withLayerDo: withLayersDo: activateLayersInCurrentProcess activateLayerInCurrentProcess) gather: [:message |
	SystemNavigation default allCallsOn: message localToPackage: pkg]]); yourself)