*VivideContextS-definitions
def78b612790710b24c8c58bfb46f0981be
	<definition>

	^ ((Dictionary new) add: (#class->ViQuerySnippetDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'23 May 2014 1:32:38 pm'); yourself)); add: (#id->#'78b61279-0710-b24c-8c58-bfb46f0981be'); add: (#inputKind->nil); add: (#block->nil); add: (#sourceCode->'self allMorphsDo: [:m | (m isKindOf: BoMovingMorph) ifTrue: [m stopStepping]]'); add: (#receiverIsCollection->false); yourself)