*VivideContextS-definitions
def8202f1486dd1e04a928b1d5703d71dfe
	<definition>

	^ ((Dictionary new) add: (#inputKind->PackageInfo); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 May 2014 11:09:20 am'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'8202f148-6dd1-e04a-928b-1d5703d71dfe'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:pkg | #(#deactivateLayerInCurrentProcess #deactivateLayersInCurrentProcess )
		gather: [:message | SystemNavigation default allCallsOn: message localToPackage: pkg]]'); add: (#mapType->#each); add: (#block->[:pkg | #(#deactivateLayerInCurrentProcess #deactivateLayersInCurrentProcess )
		gather: [:message | SystemNavigation default allCallsOn: message localToPackage: pkg]]); yourself)