*VivideContextS-definitions
def9eb72dc26c670f4ea26a2d64d494fcb3
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'10 January 2014 10:46:28 am'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'9eb72dc2-6c67-0f4e-a26a-2d64d494fcb3'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:layer | #text -> layer]'); add: (#mapType->#each); add: (#block->[:layer | #text -> layer]); yourself)