*VivideContextS-definitions
def9e863b888c1d0c46a191a34377b7d223
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'10 January 2014 9:26:53 am'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'9e863b88-8c1d-0c46-a191-a34377b7d223'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:p1 :p2 | p1 layers first <= p2 layers first]'); add: (#mapType->#twoArgs); add: (#block->[:p1 :p2 | p1 layers first <= p2 layers first]); yourself)