*VivideContextS-definitions
def9d833cb673945b4196e4230a42c0e0e5
	<definition>

	^ ((Dictionary new) add: (#inputKind->CSLayer); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'15 May 2014 11:56:36 am'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'9d833cb6-7394-5b41-96e4-230a42c0e0e5'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:l1 :l2 | l1 layerName <= l2 layerName]'); add: (#mapType->#twoArgs); add: (#block->[:l1 :l2 | l1 layerName <= l2 layerName]); yourself)