*VivideContextS-definitions
defb1d1bcb94dd42346bdb3b286f557c852
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'2 June 2014 5:38:59 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'b1d1bcb9-4dd4-2346-bdb3-b286f557c852'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:partialMethod | #text -> partialMethod selector]'); add: (#mapType->#each); add: (#block->[:partialMethod | #text -> partialMethod selector]); yourself)