*VivideContextS-definitions
defbab2344a1a967942abc46a67f049b639
	<definition>

	^ ((Dictionary new) add: (#inputKind->ByteSymbol); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'15 May 2014 11:51:57 am'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->CSLayer); add: (#id->#'bab2344a-1a96-7942-abc4-6a67f049b639'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:layerName | CSLayer layerNamed: layerName]'); add: (#mapType->#each); add: (#block->[:layerName | CSLayer layerNamed: layerName]); yourself)