*VivideContextS-definitions
defce7360645e826d41b709eb385c72d33d
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'10 January 2014 9:08:59 am'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'ce736064-5e82-6d41-b709-eb385c72d33d'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:method | (method isContextSMethod and: [method baseMethod notNil])
	ifTrue: [method baseMethod] ifFalse: [method]]'); add: (#mapType->#each); add: (#block->[:method | (method isContextSMethod and: [method baseMethod notNil])
	ifTrue: [method baseMethod] ifFalse: [method]]); yourself)