*VivideContextS-definitions
defcd9c47a90d3a5049b60037ebdf0e6fdd
	<definition>

	^ ((Dictionary new) add: (#class->ViQuerySnippetDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'23 May 2014 1:32:48 pm'); yourself)); add: (#id->#'cd9c47a9-0d3a-5049-b600-37ebdf0e6fdd'); add: (#inputKind->nil); add: (#block->nil); add: (#sourceCode->'self allMorphsDo: [:m | (m isKindOf: BoMovingMorph) ifTrue: [m startStepping]]'); add: (#receiverIsCollection->false); yourself)