*VivideContextS-definitions
defde8a5f00b6f75c48b1e25117007cf46e
	<definition>

	^ ((Dictionary new) add: (#inputKind->PackageInfo); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'15 May 2014 11:51:39 am'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'de8a5f00-b6f7-5c48-b1e2-5117007cf46e'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:pkg | (pkg layeredMethods gather: [:ref | ref method layers]) asSet asArray]'); add: (#mapType->#each); add: (#block->[:pkg | (pkg layeredMethods gather: [:ref | ref method layers]) asSet asArray]); yourself)