*VivideContextS-definitions
defd5cd322a5a3e7b4d91dec590ee255da2
	<definition>

	^ ((Dictionary new) add: (#inputKind->ByteSymbol); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 May 2014 11:41:14 am'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'d5cd322a-5a3e-7b4d-91de-c590ee255da2'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:layerName | (#(#withLayerDo: #withLayersDo: #activateLayersInCurrentProcess #activateLayerInCurrentProcess )
		gather: [:message | SystemNavigation default allCallsOn: message])
		select: [:ref | ref compiledMethod literalStrings includes: layerName]]'); add: (#mapType->#each); add: (#block->[:layerName | (#(#withLayerDo: #withLayersDo: #activateLayersInCurrentProcess #activateLayerInCurrentProcess )
		gather: [:message | SystemNavigation default allCallsOn: message])
		select: [:ref | ref compiledMethod literalStrings includes: layerName]]); yourself)