*VivideContextS-definitions
defea18c0ef83b0c644b63a26d0b8f56f2e
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'3 June 2014 10:27:42 am'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'ea18c0ef-83b0-c644-b63a-26d0b8f56f2e'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:csInfo | csInfo activeLayers]'); add: (#mapType->#each); add: (#block->[:csInfo | csInfo activeLayers]); yourself)