*VivideContextS-definitions
defe91e5289e2e1034284c8c62103a76da0
	<definition>

	^ ((Dictionary new) add: (#inputKind->CSLayer); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'15 May 2014 11:57:01 am'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'e91e5289-e2e1-0342-84c8-c62103a76da0'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:layer | layer layerName]'); add: (#mapType->#each); add: (#block->[:layer | layer layerName]); yourself)