*VivideContextS-definitions
deff4893d626ba8ea45bab61e257252c540
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'10 January 2014 10:37:44 am'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'f4893d62-6ba8-ea45-bab6-1e257252c540'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:cls | cls allInvolvedLayers asArray]'); add: (#mapType->#each); add: (#block->[:cls | cls allInvolvedLayers asArray]); yourself)