*VivideContextS-steps
step75111f0cdb3bf343997dda79d1ad8b94
	<step>

	^ ((Dictionary new) add: (#definition->#'f4893d62-6ba8-ea45-bab6-1e257252c540'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->6950); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 May 2014 10:48:32 am'); yourself)); add: (#id->#'75111f0c-db3b-f343-997d-da79d1ad8b94'); add: (#iconCode->'nil'); add: (#next->#'ec491ed1-1220-6643-ba3c-5b7b0901ef10'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)