*VivideContextS-steps
stepd032c0ffc1f22e489f65ef693e889750
	<step>

	^ ((Dictionary new) add: (#definition->#'d28c9140-19c1-0d4d-b110-e9b32d1a40df'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->7090); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'11 February 2014 1:01:49 pm'); add: (#copyOfStep->#identity); yourself)); add: (#id->#'d032c0ff-c1f2-2e48-9f65-ef693e889750'); add: (#iconCode->'nil'); add: (#next->#'06609544-d768-1b48-9593-9a6741a5b93c'); add: (#viewDefinition->#treePlain); add: (#label->'Layers'); yourself)