*VivideContextS-steps
step1473f6cd6920194ba3fb92c67bb777ea
	<step>

	^ ((Dictionary new) add: (#definition->#'7d712347-55d7-3042-8163-24efc7032741'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->7120); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'11 February 2014 1:01:49 pm'); add: (#copyOfStep->#'4d7ed994-8c4d-d941-ad50-0bbed9ea223d'); yourself)); add: (#id->#'1473f6cd-6920-194b-a3fb-92c67bb777ea'); add: (#iconCode->'nil'); add: (#next->#'61a348f1-8a2d-f54e-94e6-fa06f1612200'); add: (#viewDefinition->#treePlain); add: (#label->'Active Layers'); yourself)