*VivideContextS-steps
stepac7d5dddb248624693e8e03ad79141db
	<step>

	^ ((Dictionary new) add: (#definition->#origin); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->7210); add: (#copyOfStep->#'2d49b98d-3f27-e14f-aaa8-aee4706a6a0a'); yourself)); add: (#id->#'ac7d5ddd-b248-6246-93e8-e03ad79141db'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)