*VivideContextS-steps
step5850af79e0f7e94fbaab3be7c960f8e7
	<step>

	^ ((Dictionary new) add: (#definition->#'7d1bbd4f-e9ca-bc47-9364-473821b90e00'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->7100); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'11 February 2014 1:01:49 pm'); add: (#copyOfStep->#identity); yourself)); add: (#id->#'5850af79-e0f7-e94f-baab-3be7c960f8e7'); add: (#iconCode->'nil'); add: (#next->#'b9d1181a-d177-9748-bdc8-fe679a71c9e6'); add: (#viewDefinition->#treePlain); add: (#label->'Partial Methods'); yourself)