*VivideContextS-steps
step6d284a8998af7a4c9f4e8a26f2698501
	<step>

	^ ((Dictionary new) add: (#definition->#copyToContext); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->6780); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#'728402d7-f870-e743-8d2a-abf2353efba1'); yourself)); add: (#id->#'6d284a89-98af-7a4c-9f4e-8a26f2698501'); add: (#iconCode->'nil'); add: (#next->#'49b84cd3-b343-a740-aa77-44fbe7b4403e'); add: (#viewDefinition->#treeView); add: (#label->'Layers (COP)'); yourself)