*VivideContextS-steps
step107906f95c656f48948afeda809c3bca
	<step>

	^ ((Dictionary new) add: (#definition->#'347ae8d2-3772-5444-af7b-dad76fa6d741'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->7140); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'15 May 2014 11:58:28 am'); yourself)); add: (#id->#'107906f9-5c65-6f48-948a-feda809c3bca'); add: (#iconCode->'nil'); add: (#next->#'c1762aae-a093-a24f-98fc-bcd4bf87f0b1'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)