*VivideContextS-steps
step4d7ed9948c4dd941ad500bbed9ea223d
	<step>

	^ ((Dictionary new) add: (#definition->#'7d712347-55d7-3042-8163-24efc7032741'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->7060); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'11 February 2014 1:01:49 pm'); add: (#copyOfStep->#identity); yourself)); add: (#id->#'4d7ed994-8c4d-d941-ad50-0bbed9ea223d'); add: (#iconCode->'nil'); add: (#next->#'fc4f0101-b13a-614f-b5b7-f29f62d44885'); add: (#viewDefinition->#treeView); add: (#label->'Active Layers'); yourself)