*VivideContextS-steps
step8a88eef5ad0ba04f95e6fb8b42a29f2f
	<step>

	^ ((Dictionary new) add: (#definition->#'179f66ed-713f-cc4c-b4d4-89137a8864b3'); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->6820); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#'92eb4914-ce3c-1f4f-b813-4bd8cf3c75a6'); yourself)); add: (#id->#'8a88eef5-ad0b-a04f-95e6-fb8b42a29f2f'); add: (#iconCode->'nil'); add: (#next->#'48890660-fcb9-ca46-9690-f51788fdab94'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)