*VivideContextS-steps
step06609544d7681b4895939a6741a5b93c
	<step>

	^ ((Dictionary new) add: (#definition->#'9eb72dc2-6c67-0f4e-a26a-2d64d494fcb3'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->7300); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'2 June 2014 3:54:12 pm'); yourself)); add: (#id->#'06609544-d768-1b48-9593-9a6741a5b93c'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)