*VivideContextS-steps
step61a348f18a2df54e94e6fa06f1612200
	<step>

	^ ((Dictionary new) add: (#definition->#'ea18c0ef-83b0-c644-b63a-26d0b8f56f2e'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->7330); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'23 May 2014 11:59:28 am'); add: (#copyOfStep->#'fc4f0101-b13a-614f-b5b7-f29f62d44885'); yourself)); add: (#id->#'61a348f1-8a2d-f54e-94e6-fa06f1612200'); add: (#iconCode->'nil'); add: (#next->#'35750e17-2578-1b4d-ad6a-724e3bf9999c'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)