*VivideContextS-steps
stepd6f5f400160b80419c1d21b7e666077b
	<step>

	^ ((Dictionary new) add: (#definition->#'8202f148-6dd1-e04a-928b-1d5703d71dfe'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->6990); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 May 2014 11:09:20 am'); yourself)); add: (#id->#'d6f5f400-160b-8041-9c1d-21b7e666077b'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->'Layer Deactivations'); yourself)