*VivideContextS-steps
stepd9d2bf4693775241b6c64e6898db267c
	<step>

	^ ((Dictionary new) add: (#definition->#'618e53ed-eaf5-4d4a-a8b2-75f8ad843c99'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->6870); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'10 January 2014 9:20:25 am'); yourself)); add: (#id->#'d9d2bf46-9377-5241-b6c6-4e6898db267c'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)