*VivideContextS-steps
stepec91551dc9877349b61eb23a3e62ac5a
	<step>

	^ ((Dictionary new) add: (#definition->#'ce736064-5e82-6d41-b709-eb385c72d33d'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->6790); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'10 January 2014 9:08:59 am'); yourself)); add: (#id->#'ec91551d-c987-7349-b61e-b23a3e62ac5a'); add: (#iconCode->'nil'); add: (#next->#'3003656a-b188-a947-ac66-5599e133d6ea'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)