*VivideContextS-steps
step5e28943d2366c54ba47ab8ca5d9dd647
	<step>

	^ ((Dictionary new) add: (#definition->#'69d88582-5b2f-ab48-8b64-99d72b1432a0'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->7180); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#'e1378983-156c-1d4a-88b1-eae6654e7fb0'); yourself)); add: (#id->#'5e28943d-2366-c54b-a47a-b8ca5d9dd647'); add: (#iconCode->'UiFugueIcons layersStackArrangeIcon'); add: (#next->#'7968d544-29c4-3a4f-8f76-4716e7816044'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)