*VivideContextS-steps
step7da69373ff421b4789b5663921021bb7
	<step>

	^ ((Dictionary new) add: (#definition->#allMethodsForClass); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->6770); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#'bec0a4ef-c091-a844-88ef-be4ea489648e'); yourself)); add: (#id->#'7da69373-ff42-1b47-89b5-663921021bb7'); add: (#iconCode->'nil'); add: (#next->#'ec91551d-c987-7349-b61e-b23a3e62ac5a'); add: (#viewDefinition->#treeView); add: (#label->'Methods (COP)'); yourself)