*VivideContextS-steps
step40958115eae7be44a7ec62ce165d57c7
	<step>

	^ ((Dictionary new) add: (#definition->#'de8a5f00-b6f7-5c48-b1e2-5117007cf46e'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->6930); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'11 February 2014 1:01:49 pm'); add: (#copyOfStep->#identity); yourself)); add: (#id->#'40958115-eae7-be44-a7ec-62ce165d57c7'); add: (#iconCode->'nil'); add: (#next->#'ec491ed1-1220-6643-ba3c-5b7b0901ef10'); add: (#viewDefinition->#treePlain); add: (#label->nil); yourself)