*VivideContextS-steps
stepd4230f6398388843b9451b0fcfa6806f
	<step>

	^ ((Dictionary new) add: (#definition->#'a9a2b6a9-705b-9347-bad3-3abd6d56975c'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->7170); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'12 November 2013 5:16:28 pm'); add: (#copyOfStep->#'2fdb319c-765a-1a43-863e-792e14de2c1e'); yourself)); add: (#id->#'d4230f63-9838-8843-b945-1b0fcfa6806f'); add: (#iconCode->'nil'); add: (#next->#'5e28943d-2366-c54b-a47a-b8ca5d9dd647'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)