*VivideContextS-steps
step8eccaa4b552920499fa13d4a75662360
	<step>

	^ ((Dictionary new) add: (#definition->#'9d833cb6-7394-5b41-96e4-230a42c0e0e5'); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->6970); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'15 May 2014 11:56:36 am'); yourself)); add: (#id->#'8eccaa4b-5529-2049-9fa1-3d4a75662360'); add: (#iconCode->'nil'); add: (#next->#'90d4a2be-8443-974c-8d7d-38b4251fe917'); add: (#viewDefinition->#treeView); add: (#label->'Layers'); yourself)