*VivideContextS-steps
stepe217532a22a4c749a8f145862d799c0a
	<step>

	^ ((Dictionary new) add: (#definition->#iconAndLabel); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->7250); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#'4353ebb8-0528-4b4e-bd1b-cd49f50ae740'); yourself)); add: (#id->#'e217532a-22a4-c749-a8f1-45862d799c0a'); add: (#iconCode->'nil'); add: (#next->#'e6168f38-3ee5-b042-841f-52c134095aa8'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)