*VivideContextS-steps
step2594865764f88e41bc1184adad24467b
	<step>

	^ ((Dictionary new) add: (#definition->#'9e863b88-8c1d-0c46-a191-a34377b7d223'); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->6860); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'10 January 2014 9:26:53 am'); yourself)); add: (#id->#'25948657-64f8-8e41-bc11-84adad24467b'); add: (#iconCode->'nil'); add: (#next->#'d9d2bf46-9377-5241-b6c6-4e6898db267c'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)