*VivideContextS-steps
stepe6168f383ee5b042841f52c134095aa8
	<step>

	^ ((Dictionary new) add: (#definition->#'8332100e-7b33-804e-8ae9-6c858810d0a0'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->7260); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'10 January 2014 9:16:45 am'); add: (#copyOfStep->#'e2cb0f44-9798-4042-9ba9-fc06d6fc5d55'); yourself)); add: (#id->#'e6168f38-3ee5-b042-841f-52c134095aa8'); add: (#iconCode->'nil'); add: (#next->#'11968f16-3536-9e40-8690-f5d5ea0fb8e8'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)