*VivideContextS-steps
step4353ebb805284b4ebd1bcd49f50ae740
	<step>

	^ ((Dictionary new) add: (#definition->#iconAndLabel); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->6840); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#'26f3a2b2-f47a-644b-ac5f-159e2365b955'); yourself)); add: (#id->#'4353ebb8-0528-4b4e-bd1b-cd49f50ae740'); add: (#iconCode->'nil'); add: (#next->#'e2cb0f44-9798-4042-9ba9-fc06d6fc5d55'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)