*VivideContextS-steps
stepf1b6a380193b244ebc0c7bbd33949c5a
	<step>

	^ ((Dictionary new) add: (#definition->#allMethodsForClass); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->7080); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#'7da69373-ff42-1b47-89b5-663921021bb7'); yourself)); add: (#id->#'f1b6a380-193b-244e-bc0c-7bbd33949c5a'); add: (#iconCode->'nil'); add: (#next->#'01cd1e2e-3d03-1b40-abcd-2357c55f7448'); add: (#viewDefinition->#treeView); add: (#label->'Active Methods (COP)'); yourself)