*VivideContextS-steps
step7e8e26e67a67c248a0a7bab1c1e24bd6
	<step>

	^ ((Dictionary new) add: (#definition->#iconAndLabel); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->7200); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#'1bb6538b-c256-b34b-958e-5996dea59092'); yourself)); add: (#id->#'7e8e26e6-7a67-c248-a0a7-bab1c1e24bd6'); add: (#iconCode->'nil'); add: (#next->#'ac7d5ddd-b248-6246-93e8-e03ad79141db'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)