*VivideContextS-steps
step44d1c2293377e147b474443de25cda00
	<step>

	^ ((Dictionary new) add: (#definition->#'179f66ed-713f-cc4c-b4d4-89137a8864b3'); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->7230); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#'8a88eef5-ad0b-a04f-95e6-fb8b42a29f2f'); yourself)); add: (#id->#'44d1c229-3377-e147-b474-443de25cda00'); add: (#iconCode->'nil'); add: (#next->#'4a66fc2e-6a79-c14f-b26e-3201ab0a766b'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)