*VivideContextS-steps
stepae183c71b5a77741b990ebddbaea6584
	<step>

	^ ((Dictionary new) add: (#definition->#'0d1ad789-6b31-3446-bda5-282984dc7b6d'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->7360); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'3 June 2014 11:03:51 am'); yourself)); add: (#id->#'ae183c71-b5a7-7741-b990-ebddbaea6584'); add: (#iconCode->'nil'); add: (#next->#'02f1a5f4-e8ce-5649-8b16-b88fc3ac7439'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)