*VivideContextS-steps
step02f1a5f4e8ce56498b16b88fc3ac7439
	<step>

	^ ((Dictionary new) add: (#definition->#'b1d1bcb9-4dd4-2346-bdb3-b286f557c852'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->7370); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'3 June 2014 11:10:17 am'); yourself)); add: (#id->#'02f1a5f4-e8ce-5649-8b16-b88fc3ac7439'); add: (#iconCode->'nil'); add: (#next->#'7afe6cb3-d298-7e46-9be2-9599e1cb1b8f'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)