*VivideContextS-steps
step94ca05e288adb7478f0db50e8ba7d233
	<step>

	^ ((Dictionary new) add: (#definition->#'e91e5289-e2e1-0342-84c8-c62103a76da0'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->7020); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 May 2014 11:45:13 am'); yourself)); add: (#id->#'94ca05e2-88ad-b747-8f0d-b50e8ba7d233'); add: (#iconCode->'nil'); add: (#next->#'9772a751-8c5b-2442-9ad1-70ad8b28067a'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)