*VivideContextS-steps
step2cfbfdccbcd0ae429961b7284d3f8e03
	<step>

	^ ((Dictionary new) add: (#definition->#'0cdd7d37-bb9f-bc41-aeec-df79cd5e8854'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->7110); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'11 February 2014 1:01:49 pm'); add: (#copyOfStep->#identity); yourself)); add: (#id->#'2cfbfdcc-bcd0-ae42-9961-b7284d3f8e03'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#textView); add: (#label->'Code'); yourself)