*VivideContextS-steps
stepf52c2c3d5811744db7e55181397f15bc
	<step>

	^ ((Dictionary new) add: (#definition->#'d5cd322a-5a3e-7b4d-91de-c590ee255da2'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->7000); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 May 2014 11:41:14 am'); yourself)); add: (#id->#'f52c2c3d-5811-744d-b7e5-5181397f15bc'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->'Layer Activations'); yourself)