*VivideContextS-steps
stepf366ce580207894687d45c1fb21278a7
	<step>

	^ ((Dictionary new) add: (#definition->#'c501d634-32d5-f54a-99f1-20c76249131a'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->7030); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 May 2014 11:45:02 am'); yourself)); add: (#id->#'f366ce58-0207-8946-87d4-5c1fb21278a7'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->'Layer Deactivations'); yourself)