*VivideContextS-steps
stepfc4f0101b13a614fb5b7f29f62d44885
	<step>

	^ ((Dictionary new) add: (#definition->#'51bc4aec-0824-1e40-a75e-c6e7c19124ee'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->7160); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'23 May 2014 11:59:28 am'); yourself)); add: (#id->#'fc4f0101-b13a-614f-b5b7-f29f62d44885'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)