*VivideContextS-steps
stepc1762aaea093a24f98fcbcd4bf87f0b1
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsBySelector); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->7150); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'15 May 2014 1:05:19 pm'); yourself)); add: (#id->#'c1762aae-a093-a24f-98fc-bcd4bf87f0b1'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)