*VivideContextS-steps
stepec491ed112206643ba3c5b7b0901ef10
	<step>

	^ ((Dictionary new) add: (#definition->#'bab2344a-1a96-7942-abc4-6a67f049b639'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->6960); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'15 May 2014 11:51:57 am'); yourself)); add: (#id->#'ec491ed1-1220-6643-ba3c-5b7b0901ef10'); add: (#iconCode->'nil'); add: (#next->#'8eccaa4b-5529-2049-9fa1-3d4a75662360'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)