*VivideContextS-steps
stepbe669b62cd43f74a91e8f18a64eeffc1
	<step>

	^ ((Dictionary new) add: (#definition->#'2c62f023-9bde-3740-bac3-68e27a73f19f'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->7290); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'10 January 2014 9:20:25 am'); add: (#copyOfStep->#'d9d2bf46-9377-5241-b6c6-4e6898db267c'); yourself)); add: (#id->#'be669b62-cd43-f74a-91e8-f18a64eeffc1'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)