*VivideContextS-steps
stepb9d1181ad1779748bdc8fe679a71c9e6
	<step>

	^ ((Dictionary new) add: (#definition->#'b1d1bcb9-4dd4-2346-bdb3-b286f557c852'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->7310); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'2 June 2014 5:38:59 pm'); yourself)); add: (#id->#'b9d1181a-d177-9748-bdc8-fe679a71c9e6'); add: (#iconCode->'nil'); add: (#next->#'7d904661-2850-c44f-8a2f-c7f480ead56a'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)