*VivideContextS-steps
step43744ed2c1093e4c823b611d1b40c223
	<step>

	^ ((Dictionary new) add: (#definition->#'a51d601c-c1f2-d540-8878-0769cf929b4d'); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->7040); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 May 2014 11:51:13 am'); yourself)); add: (#id->#'43744ed2-c109-3e4c-823b-611d1b40c223'); add: (#iconCode->'nil'); add: (#next->#'f52c2c3d-5811-744d-b7e5-5181397f15bc'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)