*VivideContextS-steps
step01cd1e2e3d031b40abcd2357c55f7448
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsBySelector); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->7220); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#'20234a2f-3864-0f4f-abe5-2e59077e4a05'); yourself)); add: (#id->#'01cd1e2e-3d03-1b40-abcd-2357c55f7448'); add: (#iconCode->'nil'); add: (#next->#'44d1c229-3377-e147-b474-443de25cda00'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)