*VivideContextS-steps
step35750e1725781b4dad6a724e3bf9999c
	<step>

	^ ((Dictionary new) add: (#definition->#'9eb72dc2-6c67-0f4e-a26a-2d64d494fcb3'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->7340); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'3 June 2014 10:27:54 am'); yourself)); add: (#id->#'35750e17-2578-1b4d-ad6a-724e3bf9999c'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)