*VivideContextS-steps
step3003656ab188a947ac665599e133d6ea
	<step>

	^ ((Dictionary new) add: (#definition->#'a9a2b6a9-705b-9347-bad3-3abd6d56975c'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->6800); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'10 January 2014 9:15:18 am'); yourself)); add: (#id->#'3003656a-b188-a947-ac66-5599e133d6ea'); add: (#iconCode->'nil'); add: (#next->#'20234a2f-3864-0f4f-abe5-2e59077e4a05'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)