*VivideContextS-steps
stepf7aa94992865a540ae1df9da60715d74
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsAsStrings); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->6890); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'10 January 2014 10:38:21 am'); yourself)); add: (#id->#'f7aa9499-2865-a540-ae1d-f9da60715d74'); add: (#iconCode->'nil'); add: (#next->#'35612483-5c51-d54b-b641-932fd1270912'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)