*VivideContextS-steps
step074b0251606a4f43bd483c1f9c429582
	<step>

	^ ((Dictionary new) add: (#definition->#'7ee45678-c605-8543-932d-e918a1ed92e1'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->6940); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'11 February 2014 1:01:49 pm'); add: (#copyOfStep->#identity); yourself)); add: (#id->#'074b0251-606a-4f43-bd48-3c1f9c429582'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->'Layer Activations'); yourself)