*VivideContextS-steps
step7afe6cb3d2987e469be29599e1cb1b8f
	<step>

	^ ((Dictionary new) add: (#definition->#'4d76a99a-96d7-c942-81ba-ba84c6acfde1'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->7380); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'3 June 2014 11:10:31 am'); yourself)); add: (#id->#'7afe6cb3-d298-7e46-9be2-9599e1cb1b8f'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)