*VivideContextS-steps
step90d4a2be8443974c8d7d38b4251fe917
	<step>

	^ ((Dictionary new) add: (#definition->#'e91e5289-e2e1-0342-84c8-c62103a76da0'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->6980); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'15 May 2014 11:57:01 am'); yourself)); add: (#id->#'90d4a2be-8443-974c-8d7d-38b4251fe917'); add: (#iconCode->'nil'); add: (#next->#'107906f9-5c65-6f48-948a-feda809c3bca'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)