*VivideContextS-steps
step7d9046612850c44f8a2fc7f480ead56a
	<step>

	^ ((Dictionary new) add: (#definition->#'4d76a99a-96d7-c942-81ba-ba84c6acfde1'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->7320); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'2 June 2014 5:39:22 pm'); yourself)); add: (#id->#'7d904661-2850-c44f-8a2f-c7f480ead56a'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)