*VivideContextS-steps
step49b84cd3b343a740aa7744fbe7b4403e
	<step>

	^ ((Dictionary new) add: (#definition->#'f4893d62-6ba8-ea45-bab6-1e257252c540'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->6880); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'10 January 2014 10:39:24 am'); yourself)); add: (#id->#'49b84cd3-b343-a740-aa77-44fbe7b4403e'); add: (#iconCode->'nil'); add: (#next->#'f7aa9499-2865-a540-ae1d-f9da60715d74'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)