*VivideContextS-steps
step48890660fcb9ca469690f51788fdab94
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsAsStrings); add: (#class->ViQueryGroupSortStep); add: (#properties->((Dictionary new) add: (#priority->6830); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#'2fca6209-9c2d-c644-823a-acf2909bad0f'); yourself)); add: (#id->#'48890660-fcb9-ca46-9690-f51788fdab94'); add: (#iconCode->'nil'); add: (#next->#'4353ebb8-0528-4b4e-bd1b-cd49f50ae740'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)