*VivideContextS-steps
step356124835c51d54bb641932fd1270912
	<step>

	^ ((Dictionary new) add: (#definition->#'9eb72dc2-6c67-0f4e-a26a-2d64d494fcb3'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->6900); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#defaultProperties); yourself)); add: (#id->#'35612483-5c51-d54b-b641-932fd1270912'); add: (#iconCode->'nil'); add: (#next->#'6efcf418-7829-7040-af65-473625d0fecb'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)