*VivideContextS-steps
step11968f1635369e408690f5d5ea0fb8e8
	<step>

	^ ((Dictionary new) add: (#definition->#'1922f79b-8c99-dd4a-9d04-8ddb2ce7aa39'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->7270); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'24 May 2014 6:18:30 pm'); yourself)); add: (#id->#'11968f16-3536-9e40-8690-f5d5ea0fb8e8'); add: (#iconCode->'nil'); add: (#next->#'1e5f4df6-aec6-1a40-b9f1-5b5206a2e688'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)