*VivideContextS-steps
step1e5f4df6aec61a40b9f15b5206a2e688
	<step>

	^ ((Dictionary new) add: (#definition->#'c08a299c-c3a0-d943-8dcc-9e44b206a1cb'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->7280); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'24 May 2014 6:19:42 pm'); yourself)); add: (#id->#'1e5f4df6-aec6-1a40-b9f1-5b5206a2e688'); add: (#iconCode->'nil'); add: (#next->#'be669b62-cd43-f74a-91e8-f18a64eeffc1'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)