*VivideContextS-steps
step20234a2f38640f4fabe52e59077e4a05
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsBySelector); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->6810); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#'dd7cc162-78d3-5946-8ad0-7e30f7b46f6d'); yourself)); add: (#id->#'20234a2f-3864-0f4f-abe5-2e59077e4a05'); add: (#iconCode->'nil'); add: (#next->#'8a88eef5-ad0b-a04f-95e6-fb8b42a29f2f'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)