*VivideContextS-steps
step4cd7a5a9f728a041b92561724c01b818
	<step>

	^ ((Dictionary new) add: (#definition->#'d89728bf-0d8f-1143-9a93-e4a1aad379f4'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->7070); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#debuggerStack); yourself)); add: (#id->#'4cd7a5a9-f728-a041-b925-61724c01b818'); add: (#iconCode->'nil'); add: (#next->#'d4230f63-9838-8843-b945-1b0fcfa6806f'); add: (#viewDefinition->#treeView); add: (#label->'Suspended context (COP)'); yourself)