definitions
def08309815e0768343acd458f380aa3063
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'3 February 2015 4:12:43 pm'); yourself)); add: (#id->#'08309815-e076-8343-acd4-58f380aa3063'); add: (#block->[:in :out | out add: {#objects -> in}, [{
	#bounds -> (1@336 corner: 448@498).
	#current -> #'7a9abe0a-e73f-614c-8a83-069b0bb7b273'.
	#id -> #'efcd36c0-98e8-1649-84ff-12de542edb0e'.
	#out -> #().
	#in -> #(#(#interactive #'b19d1e81-f72b-064d-9266-07889d1f7f09' ) ).
}] value]); add: (#sourceCode->'[:in :out | out add: {#objects -> in}, [{
	#bounds -> (1@336 corner: 448@498).
	#current -> #''7a9abe0a-e73f-614c-8a83-069b0bb7b273''.
	#id -> #''efcd36c0-98e8-1649-84ff-12de542edb0e''.
	#out -> #().
	#in -> #(#(#interactive #''b19d1e81-f72b-064d-9266-07889d1f7f09'' ) ).
}] value]'); yourself)