definitions
def3f51b8cf696e474a9d73f9cc60fb465e
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'4 February 2015 10:49:45 am'); yourself)); add: (#id->#'3f51b8cf-696e-474a-9d73-f9cc60fb465e'); add: (#block->[:in :out | out add: {#objects -> in}, [{
	#bounds -> (1@305 corner: 450@498).
	#current -> #'983eae46-3d9f-314a-8161-02f19dbbb98c'.
	#id -> #'8b24e406-5d31-5042-8874-cf7435adbdbe'.
	#out -> #().
	#in -> #(#(#interactive #'2f643e14-46f7-744d-8915-ee1dff9fa09b' ) ).
}] value]); add: (#sourceCode->'[:in :out | out add: {#objects -> in}, [{
	#bounds -> (1@305 corner: 450@498).
	#current -> #''983eae46-3d9f-314a-8161-02f19dbbb98c''.
	#id -> #''8b24e406-5d31-5042-8874-cf7435adbdbe''.
	#out -> #().
	#in -> #(#(#interactive #''2f643e14-46f7-744d-8915-ee1dff9fa09b'' ) ).
}] value]'); yourself)