definitions
def41d0c7aab491cc49a8b71f9182c1d35d
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'1 February 2015 2:29:06 pm'); yourself)); add: (#id->#'41d0c7aa-b491-cc49-a8b7-1f9182c1d35d'); add: (#block->[:in :out | out addAll: ([:tuples | tuples asGroups] value: in)]); add: (#sourceCode->'[:in :out | out addAll: ([:tuples | tuples asGroups] value: in)]'); yourself)