definitions
def50a1ea952b59164bb122a62bf3d2a937
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'4 February 2015 10:50 am'); yourself)); add: (#id->#'50a1ea95-2b59-164b-b122-a62bf3d2a937'); add: (#block->[:in :out | out add: {#objects -> in}, [{
	#bounds -> (1@1 corner: 450@300).
	#current -> #'69de04f8-df1a-c445-890d-9d631fbfe47c'.
	#id -> #'2f643e14-46f7-744d-8915-ee1dff9fa09b'.
	#out -> #(#(#interactive #'8b24e406-5d31-5042-8874-cf7435adbdbe' ) ).
	#in -> #(#(#interactive #outer ) ).
}] value]); add: (#sourceCode->'[:in :out | out add: {#objects -> in}, [{
	#bounds -> (1@1 corner: 450@300).
	#current -> #''69de04f8-df1a-c445-890d-9d631fbfe47c''.
	#id -> #''2f643e14-46f7-744d-8915-ee1dff9fa09b''.
	#out -> #(#(#interactive #''8b24e406-5d31-5042-8874-cf7435adbdbe'' ) ).
	#in -> #(#(#interactive #outer ) ).
}] value]'); yourself)