definitions
def6fb75a9bbcd0d54589c309131b155ca9
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'1 February 2015 7:28:08 pm'); yourself)); add: (#id->#'6fb75a9b-bcd0-d545-89c3-09131b155ca9'); add: (#block->[:in :out | out add: {#objects -> in}, [{
	#bounds -> (206@0 corner: 728@293).
	#current -> #'4082edcf-60a9-bd4d-b315-5eced8f0aca4'.
	#id -> #'1852e678-307f-0e49-b617-b2582af01333'.
	#out -> #().
	#in -> #(#(#interactive #'135cc636-e29b-e240-aa69-088c60096aa8' ) ).
}] value]); add: (#sourceCode->'[:in :out | out add: {#objects -> in}, [{
	#bounds -> (206@0 corner: 728@293).
	#current -> #''4082edcf-60a9-bd4d-b315-5eced8f0aca4''.
	#id -> #''1852e678-307f-0e49-b617-b2582af01333''.
	#out -> #().
	#in -> #(#(#interactive #''135cc636-e29b-e240-aa69-088c60096aa8'' ) ).
}] value]'); yourself)