definitions
def71a7364162467d4f8afe43ce35ccbf18
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'1 February 2015 2:29:06 pm'); yourself)); add: (#id->#'71a73641-6246-7d4f-8afe-43ce35ccbf18'); add: (#block->[:in :out | out addAll: ([:classes | classes
		sorted: [:c1 :c2 | c1 name <= c2 name]] value: in)]); add: (#sourceCode->'[:in :out | out addAll: ([:classes | classes
		sorted: [:c1 :c2 | c1 name <= c2 name]] value: in)]'); yourself)