definitions
def99f856ce8ba38244825a6aa15cf37ccc
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'3 February 2015 4:12:45 pm'); yourself)); add: (#id->#'99f856ce-8ba3-8244-825a-6aa15cf37ccc'); add: (#block->[:in :out | out add: {#objects -> in}, [{
	#bounds -> (1@1 corner: 448@302).
	#current -> #'b3ac919a-01a0-3540-a0d5-d54df7e353e4'.
	#id -> #'b19d1e81-f72b-064d-9266-07889d1f7f09'.
	#out -> #(#(#interactive #'efcd36c0-98e8-1649-84ff-12de542edb0e' ) #(#interactive #'e469428c-ef86-344c-aaa1-5ee0239ca482' ) ).
	#in -> #(#(#automatic #outer ) ).
}] value]); add: (#sourceCode->'[:in :out | out add: {#objects -> in}, [{
	#bounds -> (1@1 corner: 448@302).
	#current -> #''b3ac919a-01a0-3540-a0d5-d54df7e353e4''.
	#id -> #''b19d1e81-f72b-064d-9266-07889d1f7f09''.
	#out -> #(#(#interactive #''efcd36c0-98e8-1649-84ff-12de542edb0e'' ) #(#interactive #''e469428c-ef86-344c-aaa1-5ee0239ca482'' ) ).
	#in -> #(#(#automatic #outer ) ).
}] value]'); yourself)