definitions
defaaf50dec8d706344a08148f24e2fe649
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'1 February 2015 7:25:43 pm'); yourself)); add: (#id->#'aaf50dec-8d70-6344-a081-48f24e2fe649'); add: (#block->[:in :out | out add: {#objects -> in}, [{
	#bounds -> (1@0 corner: 201@293).
	#current -> #'2892dfae-4342-ae46-90cb-12514c314497'.
	#id -> #'135cc636-e29b-e240-aa69-088c60096aa8'.
	#out -> #(#(#interactive #'1852e678-307f-0e49-b617-b2582af01333' ) ).
	#in -> #(#(#automatic #outer ) ).
}] value]); add: (#sourceCode->'[:in :out | out add: {#objects -> in}, [{
	#bounds -> (1@0 corner: 201@293).
	#current -> #''2892dfae-4342-ae46-90cb-12514c314497''.
	#id -> #''135cc636-e29b-e240-aa69-088c60096aa8''.
	#out -> #(#(#interactive #''1852e678-307f-0e49-b617-b2582af01333'' ) ).
	#in -> #(#(#automatic #outer ) ).
}] value]'); yourself)