definitions
defa384b9b7d902dd429acf0bb1eef34ba3
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'4 February 2015 10:53:29 am'); yourself)); add: (#id->#'a384b9b7-d902-dd42-9acf-0bb1eef34ba3'); add: (#block->[:in :out | out add: {#objects -> in}, [{
	#bounds -> (1@303 corner: 449@498).
	#current -> #'ef6d55a3-4118-0247-9411-fff83bf09d2a'.
	#id -> #'83b81eaf-98d5-a843-88d7-e0c54a5f3fa1'.
	#out -> #().
	#in -> #(#(#interactive #'ebad0b52-46e4-bb43-8cf3-611a41b6b254' ) ).
}] value]); add: (#sourceCode->'[:in :out | out add: {#objects -> in}, [{
	#bounds -> (1@303 corner: 449@498).
	#current -> #''ef6d55a3-4118-0247-9411-fff83bf09d2a''.
	#id -> #''83b81eaf-98d5-a843-88d7-e0c54a5f3fa1''.
	#out -> #().
	#in -> #(#(#interactive #''ebad0b52-46e4-bb43-8cf3-611a41b6b254'' ) ).
}] value]'); yourself)