definitions
defbaa47b83196a1948b5ee8709c9179460
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'4 February 2015 10:54:01 am'); yourself)); add: (#id->#'baa47b83-196a-1948-b5ee-8709c9179460'); add: (#block->[:in :out | out add: {#objects -> in}, [{
	#bounds -> (1@1 corner: 449@298).
	#current -> #'b3438573-96f1-9541-bb4c-40f516a958ce'.
	#id -> #'ebad0b52-46e4-bb43-8cf3-611a41b6b254'.
	#out -> #(#(#interactive #'83b81eaf-98d5-a843-88d7-e0c54a5f3fa1' ) ).
	#in -> #((interactive outer)).
}] value]); add: (#sourceCode->'[:in :out | out add: {#objects -> in}, [{
	#bounds -> (1@1 corner: 449@298).
	#current -> #''b3438573-96f1-9541-bb4c-40f516a958ce''.
	#id -> #''ebad0b52-46e4-bb43-8cf3-611a41b6b254''.
	#out -> #(#(#interactive #''83b81eaf-98d5-a843-88d7-e0c54a5f3fa1'' ) ).
	#in -> #((interactive outer)).
}] value]'); yourself)