steps
step5ab5bb13a76aa64d864ed4481003d295
	<step>

	^ ((Dictionary new) add: (#definition->#'c7223154-d83c-2f4a-916a-f0bfd27be3bd'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'1 February 2015 2:29:06 pm'); yourself)); add: (#isProperty->false); add: (#next->#'23141405-8b20-3243-95b5-5a3b8ad5566e'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'5ab5bb13-a76a-a64d-864e-d4481003d295'); add: (#isReference->false); add: (#viewDefinition->#treePlain); yourself)