steps
stepdefaultProperties
	<step>

	^ ((Dictionary new) add: (#definition->#'307cf63e-ed6f-a04f-abe2-7bd595751791'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'1 February 2015 2:29:06 pm'); yourself)); add: (#isProperty->true); add: (#next->#'4a0351ad-0fcb-6f4c-a714-01785a66f4b4'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#defaultProperties); add: (#isReference->false); add: (#viewDefinition->#treePlain); yourself)