steps
stepd0b7f42b8fdcc84e85a7b16d4e26dc6f
	<step>

	^ ((Dictionary new) add: (#definition->#'6fb75a9b-bcd0-d545-89c3-09131b155ca9'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#view->ViMultiPaneWidget); add: (#creationTimeStamp->'1 February 2015 7:28:08 pm'); add: (#isNew->false); yourself)); add: (#isProperty->true); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'d0b7f42b-8fdc-c84e-85a7-b16d4e26dc6f'); add: (#isReference->false); add: (#viewDefinition->#treePlain); yourself)