steps
step7a9abe0ae73f614c8a83069b0bb7b273
	<step>

	^ ((Dictionary new) add: (#definition->#'cd662511-34d3-6347-b508-f1f814153716'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#view->ViMethodContextEditorView); add: (#creationTimeStamp->'3 February 2015 6:20:15 pm'); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'7a9abe0a-e73f-614c-8a83-069b0bb7b273'); add: (#isReference->false); add: (#viewDefinition->#treePlain); yourself)