steps
stepa93655fb81c630478b6e983132118000
	<step>

	^ ((Dictionary new) add: (#definition->#'10940101-9b7e-b244-a726-daec8deffe61'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->PackageInfo); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'1 February 2015 2:29:06 pm'); add: (#outputKind->ClassDescription); add: (#view->ViTreeView); add: (#priority->45); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->#'5776f1f4-0fee-dc4a-83cd-860007aa5906'); add: (#label->'Package Outline'); add: (#iconCode->'nil'); add: (#id->#'a93655fb-81c6-3047-8b6e-983132118000'); add: (#isReference->false); add: (#viewDefinition->#treePlain); yourself)