steps
stepcd133650b096054bb4123f46bcaa6942
	<step>

	^ ((Dictionary new) add: (#definition->#'ba33fb6b-f6f8-5947-b0e3-d70108ea1c6c'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'3 February 2015 5:51:10 pm'); yourself)); add: (#isProperty->true); add: (#next->#'d0f0bf90-4870-6f42-ad30-d725d7383a62'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'cd133650-b096-054b-b412-3f46bcaa6942'); add: (#isReference->false); add: (#viewDefinition->#treePlain); yourself)