steps
step231414058b20324395b55a3b8ad5566e
	<step>

	^ ((Dictionary new) add: (#definition->#'68068e65-5860-4944-9c02-f840fd3b31ec'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'1 February 2015 2:29:06 pm'); yourself)); add: (#isProperty->false); add: (#next->#'8ed979bd-353a-934e-9977-6e22d8afc389'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'23141405-8b20-3243-95b5-5a3b8ad5566e'); add: (#isReference->false); add: (#viewDefinition->#treePlain); yourself)