steps
step4e7903b2cae1bc4eb11a3061ac0a54a1
	<step>

	^ ((Dictionary new) add: (#definition->#'a9f30680-4915-8649-848b-c44854d2d48f'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#view->ViMultiPaneWidget); add: (#creationTimeStamp->'3 February 2015 6:24:32 pm'); add: (#isNew->false); yourself)); add: (#isProperty->true); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'4e7903b2-cae1-bc4e-b11a-3061ac0a54a1'); add: (#isReference->false); add: (#viewDefinition->#treePlain); yourself)