steps
stepa8cfc3d203645840a724686bce97e394
	<step>

	^ ((Dictionary new) add: (#definition->#'1387c558-c9e5-3f48-a5c1-4c0d73af91f3'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'1 February 2015 7:07:58 pm'); add: (#copyOf->#'e5b8b5f7-3d60-924c-954c-91f7d95b0078'); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->#'278ea3ef-f377-f445-841c-0b5f22626cb3'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'a8cfc3d2-0364-5840-a724-686bce97e394'); add: (#isReference->false); add: (#viewDefinition->#treePlain); yourself)