steps
stepae1b56b268bdb74e83f2ba7124c5f847
	<step>

	^ ((Dictionary new) add: (#definition->#'baa47b83-196a-1948-b5ee-8709c9179460'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#view->ViMultiPaneWidget); add: (#creationTimeStamp->'4 February 2015 10:54:01 am'); add: (#isNew->false); yourself)); add: (#isProperty->true); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'ae1b56b2-68bd-b74e-83f2-ba7124c5f847'); add: (#isReference->false); add: (#viewDefinition->#treePlain); yourself)