steps
step5776f1f40feedc4a83cd860007aa5906
	<step>

	^ ((Dictionary new) add: (#definition->#'71a73641-6246-7d4f-8afe-43ce35ccbf18'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'1 February 2015 2:29:06 pm'); yourself)); add: (#isProperty->false); add: (#next->#'3984d437-235d-2445-a9eb-21f0d7f216e8'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'5776f1f4-0fee-dc4a-83cd-860007aa5906'); add: (#isReference->false); add: (#viewDefinition->#treePlain); yourself)