steps
step3984d437235d2445a9eb21f0d7f216e8
	<step>

	^ ((Dictionary new) add: (#definition->#'3fa7e3fc-6307-da4d-aeb2-5dc2d4cd8b81'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'1 February 2015 2:29:06 pm'); yourself)); add: (#isProperty->false); add: (#next->#'66cac3e2-6ebd-6f4e-b1ab-a71547babc9e'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'3984d437-235d-2445-a9eb-21f0d7f216e8'); add: (#isReference->false); add: (#viewDefinition->#treePlain); yourself)