steps
step2892dfae4342ae4690cb12514c314497
	<step>

	^ ((Dictionary new) add: (#definition->#'b0dc829a-7a6b-ad49-9a23-cc47fcf87129'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->ClassDescription); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'1 February 2015 7:07:58 pm'); add: (#outputKind->CompiledMethod); add: (#view->ViTreeView); add: (#copyOf->#outline); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->#'a8cfc3d2-0364-5840-a724-686bce97e394'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'2892dfae-4342-ae46-90cb-12514c314497'); add: (#isReference->false); add: (#viewDefinition->#treePlain); yourself)