steps
step983eae463d9f314a816102f19dbbb98c
	<step>

	^ ((Dictionary new) add: (#definition->#'96356d37-80c5-7c4a-bff3-ccf8cccb5955'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#view->ViMethodEditorView); add: (#creationTimeStamp->'4 February 2015 10:49:45 am'); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'983eae46-3d9f-314a-8161-02f19dbbb98c'); add: (#isReference->false); add: (#viewDefinition->#treePlain); yourself)