steps
stepsnippets
	<step>

	^ ((Dictionary new) add: (#definition->#'6be066bf-3af7-1643-9473-ee0129f79b51'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'1 February 2015 2:29:06 pm'); add: (#outputKind->ViQuerySnippetDefinition); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#snippets); add: (#isReference->false); add: (#viewDefinition->#treePlain); yourself)