steps
stepgroups
	<step>

	^ ((Dictionary new) add: (#definition->#'41d0c7aa-b491-cc49-a8b7-1f9182c1d35d'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->((Array new: 2) at: 1 put: Object; at: 2 put: Object; yourself)); add: (#creationAuthor->'mt'); add: (#view->ViTreeViewExtended); add: (#creationTimeStamp->'1 February 2015 2:29:06 pm'); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->#'5ab5bb13-a76a-a64d-864e-d4481003d295'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#groups); add: (#isReference->false); add: (#viewDefinition->#treePlain); yourself)