steps
stepb3ac919a01a03540a0d5d54df7e353e4
	<step>

	^ ((Dictionary new) add: (#definition->#'50ffd2e1-ebaf-734d-9e55-ca8a7196fc87'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'3 February 2015 4:07:24 pm'); yourself)); add: (#isProperty->false); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'b3ac919a-01a0-3540-a0d5-d54df7e353e4'); add: (#isReference->false); add: (#viewDefinition->#treePlain); yourself)