steps
step1d933e4798111b4aba4afb88f24d5086
	<step>

	^ ((Dictionary new) add: (#definition->#'593bdfb3-b5e1-b340-a2b6-b560265da52c'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'1 February 2015 2:29:06 pm'); yourself)); add: (#isProperty->false); add: (#next->#'43bba950-dc26-5440-a6f8-7c8f5fb4648f'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'1d933e47-9811-1b4a-ba4a-fb88f24d5086'); add: (#isReference->false); add: (#viewDefinition->#treePlain); yourself)