steps
step1f17c07d6d9c91428df10f55fb419d27
	<step>

	^ ((Dictionary new) add: (#definition->#'53e29783-17f6-4a46-81a1-9b8ffb2d6353'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->ViAnimatedImageMorph); add: (#creationAuthor->'mt'); add: (#view->ViMorphView); add: (#creationTimeStamp->'4 March 2015 1:21:42 pm'); add: (#priority->30); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->nil); add: (#label->'Animation'); add: (#iconCode->'nil'); add: (#id->#'1f17c07d-6d9c-9142-8df1-0f55fb419d27'); add: (#isReference->false); add: (#viewDefinition->nil); yourself)