steps
stepinstVarRefs
	<step>

	^ ((Dictionary new) add: (#definition->#'3624cff4-e63c-7e4b-a23f-273a85248ee5'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->ClassDescription); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'5 February 2015 11:04:13 am'); add: (#priority->41); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->#'0247b980-eb3f-2943-8e5d-f710aa04069d'); add: (#label->'Variables'); add: (#iconCode->'nil'); add: (#id->#instVarRefs); add: (#isReference->false); add: (#viewDefinition->#treePlain); yourself)