steps
stepartifacts
	<step>

	^ ((Dictionary new) add: (#definition->#'735b153b-f4f0-4545-af83-af1c287b4c26'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#view->ViArtifactListView2); add: (#creationTimeStamp->'1 February 2015 2:29:06 pm'); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->nil); add: (#label->'List of Objects'); add: (#iconCode->'nil'); add: (#id->#artifacts); add: (#isReference->false); add: (#viewDefinition->#treePlain); yourself)