steps
stepa2d181f5415d5c4eafa9b41ec20c9deb
	<step>

	^ ((Dictionary new) add: (#definition->#'206be9d8-39a4-2149-ad4b-63f679b3cc70'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'5 February 2015 11:09:19 am'); yourself)); add: (#isProperty->false); add: (#next->#'f5b6fe79-d737-a741-8544-d9a42eab1492'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'a2d181f5-415d-5c4e-afa9-b41ec20c9deb'); add: (#isReference->false); add: (#viewDefinition->#treePlain); yourself)