steps
step66cac3e26ebd6f4eb1aba71547babc9e
	<step>

	^ ((Dictionary new) add: (#definition->#'e5b70798-4c82-ff47-b620-a3d13fb9fc21'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'1 February 2015 2:29:06 pm'); yourself)); add: (#isProperty->false); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'66cac3e2-6ebd-6f4e-b1ab-a71547babc9e'); add: (#isReference->true); add: (#viewDefinition->#treePlain); yourself)