steps
step4d1cb0fa8a93e341b02ace3252c4b39f
	<step>

	^ ((Dictionary new) add: (#definition->#'39199be1-b491-d345-a8cb-61ca01ab3043'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'3 February 2015 6:40:31 pm'); yourself)); add: (#isProperty->true); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'4d1cb0fa-8a93-e341-b02a-ce3252c4b39f'); add: (#isReference->false); add: (#viewDefinition->#treePlain); yourself)