steps
step4a0351ad0fcb6f4ca71401785a66f4b4
	<step>

	^ ((Dictionary new) add: (#definition->#'720612ff-edd2-9d45-a7c6-f5fa133912d1'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'1 February 2015 2:29:06 pm'); yourself)); add: (#isProperty->true); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'4a0351ad-0fcb-6f4c-a714-01785a66f4b4'); add: (#isReference->false); add: (#viewDefinition->#treePlain); yourself)