steps
step74e4cc7d7496be4fb46dbbf2540a2e31
	<step>

	^ ((Dictionary new) add: (#definition->#'5ad872f3-d01a-e845-a6d5-e81dcd7e77bf'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->((Array new: 2) at: 1 put: Object; at: 2 put: Object; yourself)); add: (#creationAuthor->'mt'); add: (#view->ViButtonBarView); add: (#creationTimeStamp->'3 February 2015 4:10:25 pm'); add: (#isNew->false); add: (#selectionMode->UiViewSingleSelection); yourself)); add: (#isProperty->true); add: (#next->#'ed3eb6ec-5cca-d241-9a6f-d7f82707202e'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'74e4cc7d-7496-be4f-b46d-bbf2540a2e31'); add: (#isReference->false); add: (#viewDefinition->#treePlain); yourself)