steps
step43bba950dc265440a6f87c8f5fb4648f
	<step>

	^ ((Dictionary new) add: (#definition->#'8c63945a-c92d-404c-ae87-63a80050d688'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'1 February 2015 2:29:06 pm'); add: (#isNew->false); yourself)); add: (#isProperty->true); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'43bba950-dc26-5440-a6f8-7c8f5fb4648f'); add: (#isReference->false); add: (#viewDefinition->#treePlain); yourself)