steps
stepb343857396f19541bb4c40f516a958ce
	<step>

	^ ((Dictionary new) add: (#definition->#'51c71ed8-e88d-4745-b563-698c743e443f'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->ByteSymbol); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'4 February 2015 10:53:21 am'); add: (#outputKind->MethodReference); add: (#view->ViTreeView); add: (#copyOf->#implementors); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'b3438573-96f1-9541-bb4c-40f516a958ce'); add: (#isReference->false); add: (#viewDefinition->#treePlain); yourself)