steps
step100fcf121183134490b72ebea5055db2
	<step>

	^ ((Dictionary new) add: (#definition->#'67f71d38-a1f5-8341-b467-5d004c4bb4d1'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'1 February 2015 2:29:06 pm'); yourself)); add: (#isProperty->true); add: (#next->#'75195fdf-e652-8747-833e-3ddf61a021e2'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'100fcf12-1183-1344-90b7-2ebea5055db2'); add: (#isReference->false); add: (#viewDefinition->#treePlain); yourself)