steps
stepformattedQueries
	<step>

	^ ((Dictionary new) add: (#definition->#'6492bdcc-bf9b-0d49-9b89-7d0bb90d7cd9'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->ViQueryStep); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'1 February 2015 2:29:06 pm'); add: (#outputKind->ViQueryStep); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->#'100fcf12-1183-1344-90b7-2ebea5055db2'); add: (#label->'Scripts'); add: (#iconCode->'nil'); add: (#id->#formattedQueries); add: (#isReference->false); add: (#viewDefinition->#treePlain); yourself)