steps
step1267c09f589b5249b2a0143bc69bcfa3
	<step>

	^ ((Dictionary new) add: (#definition->#'50a1ea95-2b59-164b-b122-a62bf3d2a937'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#view->ViMultiPaneWidget); add: (#creationTimeStamp->'4 February 2015 10:50 am'); add: (#isNew->false); yourself)); add: (#isProperty->true); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'1267c09f-589b-5249-b2a0-143bc69bcfa3'); add: (#isReference->false); add: (#viewDefinition->#treePlain); yourself)