steps
stepsenders
	<step>

	^ ((Dictionary new) add: (#definition->#'3f51b8cf-696e-474a-9d73-f9cc60fb465e'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->ByteSymbol); add: (#creationAuthor->'mt'); add: (#view->ViMultiPaneWidget); add: (#creationTimeStamp->'4 February 2015 10:49:45 am'); add: (#isNew->false); add: (#optimalExtent->(451@498)); add: (#locked->true); yourself)); add: (#isProperty->true); add: (#next->#'1267c09f-589b-5249-b2a0-143bc69bcfa3'); add: (#label->'Senders'); add: (#iconCode->'nil'); add: (#id->#senders); add: (#isReference->false); add: (#viewDefinition->#treePlain); yourself)