steps
step69de04f8df1ac445890d9d631fbfe47c
	<step>

	^ ((Dictionary new) add: (#definition->#'0de64ad3-bfdd-7e42-bba5-b117e6943e81'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->ByteSymbol); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'4 February 2015 10:49:35 am'); add: (#outputKind->MethodReference); add: (#view->ViTreeView); add: (#copyOf->#senders); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'69de04f8-df1a-c445-890d-9d631fbfe47c'); add: (#isReference->false); add: (#viewDefinition->#treePlain); yourself)