steps
step71050fb29c47e94494f01f80db18e4a2
	<step>

	^ ((Dictionary new) add: (#definition->#'18c970ce-e5f9-3f41-9f29-a9ea7cf38df5'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'3 February 2015 5:50:30 pm'); yourself)); add: (#isProperty->true); add: (#next->#'cd133650-b096-054b-b412-3f46bcaa6942'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'71050fb2-9c47-e944-94f0-1f80db18e4a2'); add: (#isReference->false); add: (#viewDefinition->#treePlain); yourself)