steps
stepobjectExplorer
	<step>

	^ ((Dictionary new) add: (#definition->#'823b1e15-db4f-a340-9cb8-8dd1287a4cd5'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#view->ViExplorerView); add: (#creationTimeStamp->'1 February 2015 2:29:06 pm'); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->nil); add: (#label->'Inspector'); add: (#iconCode->'nil'); add: (#id->#objectExplorer); add: (#isReference->false); add: (#viewDefinition->#treePlain); yourself)