steps
stepbcc98b37002ca44f80c64880fba87a3c
	<step>

	^ ((Dictionary new) add: (#definition->#'5eae18b8-b4a4-ab4c-859c-42bce119083b'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'1 February 2015 7:07:58 pm'); add: (#copyOf->#'1c9c810c-9551-b945-b2b0-0ecb6eb717d8'); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'bcc98b37-002c-a44f-80c6-4880fba87a3c'); add: (#isReference->true); add: (#viewDefinition->#treePlain); yourself)