steps
steped3eb6ec5ccad2419a6fd7f82707202e
	<step>

	^ ((Dictionary new) add: (#definition->#'530ad07a-916f-7b46-9f17-06c2fb61c62c'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->((Array new: 2) at: 1 put: Object; at: 2 put: Object; yourself)); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'3 February 2015 4:19:07 pm'); add: (#isNew->false); yourself)); add: (#isProperty->true); add: (#next->#'71050fb2-9c47-e944-94f0-1f80db18e4a2'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'ed3eb6ec-5cca-d241-9a6f-d7f82707202e'); add: (#isReference->false); add: (#viewDefinition->#treePlain); yourself)