steps
step6f93908fc336d2429ec34045634ab6df
	<step>

	^ ((Dictionary new) add: (#definition->#'3af630fa-2840-094a-a64a-cd8d723edc3a'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'5 February 2015 5:19:08 pm'); yourself)); add: (#isProperty->true); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'6f93908f-c336-d242-9ec3-4045634ab6df'); add: (#isReference->false); add: (#viewDefinition->#treePlain); yourself)