steps
stepimplementors
	<step>

	^ ((Dictionary new) add: (#definition->#'a384b9b7-d902-dd42-9acf-0bb1eef34ba3'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->ByteSymbol); add: (#creationAuthor->'mt'); add: (#view->ViMultiPaneWidget); add: (#creationTimeStamp->'4 February 2015 10:53:29 am'); add: (#isNew->false); add: (#optimalExtent->(450@498)); add: (#locked->true); yourself)); add: (#isProperty->true); add: (#next->#'ae1b56b2-68bd-b74e-83f2-ba7124c5f847'); add: (#label->'Implementors'); add: (#iconCode->'nil'); add: (#id->#implementors); add: (#isReference->false); add: (#viewDefinition->#treePlain); yourself)