steps
step931d2a748b0f394ea9240cde9505c977
	<step>

	^ ((Dictionary new) add: (#definition->#'99f856ce-8ba3-8244-825a-6aa15cf37ccc'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#view->ViMultiPaneWidget); add: (#creationTimeStamp->'3 February 2015 4:12:45 pm'); add: (#isNew->false); yourself)); add: (#isProperty->true); add: (#next->#'4e7903b2-cae1-bc4e-b11a-3061ac0a54a1'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'931d2a74-8b0f-394e-a924-0cde9505c977'); add: (#isReference->false); add: (#viewDefinition->#treePlain); yourself)