steps
stepeditor
	<step>

	^ ((Dictionary new) add: (#definition->#'6eb21c02-6884-bf4e-860c-30036dd6e410'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#view->ViEditorView); add: (#creationTimeStamp->'4 February 2015 5:24:24 pm'); add: (#priority->50); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->nil); add: (#label->'Editor'); add: (#iconCode->'nil'); add: (#id->#editor); add: (#isReference->false); add: (#viewDefinition->#treePlain); yourself)