steps
stepef6d55a3411802479411fff83bf09d2a
	<step>

	^ ((Dictionary new) add: (#definition->#'efc422cf-5bc3-6442-af25-039c006e05e8'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#view->ViMethodEditorView); add: (#creationTimeStamp->'4 February 2015 10:53:29 am'); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'ef6d55a3-4118-0247-9411-fff83bf09d2a'); add: (#isReference->false); add: (#viewDefinition->#treePlain); yourself)