steps
step75195fdfe6528747833e3ddf61a021e2
	<step>

	^ ((Dictionary new) add: (#definition->#'8024196d-45df-9742-94a0-95ae43c36e0c'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'1 February 2015 2:29:06 pm'); yourself)); add: (#isProperty->true); add: (#next->#'6f93908f-c336-d242-9ec3-4045634ab6df'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'75195fdf-e652-8747-833e-3ddf61a021e2'); add: (#isReference->false); add: (#viewDefinition->#treePlain); yourself)