steps
step8ed979bd353a934e99776e22d8afc389
	<step>

	^ ((Dictionary new) add: (#definition->#'f4e5f3bd-7592-a54e-8b8b-8ef60b4e9cd6'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'1 February 2015 2:29:06 pm'); yourself)); add: (#isProperty->false); add: (#next->#'1d933e47-9811-1b4a-ba4a-fb88f24d5086'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'8ed979bd-353a-934e-9977-6e22d8afc389'); add: (#isReference->false); add: (#viewDefinition->#treePlain); yourself)