steps
stepf5b6fe79d737a7418544d9a42eab1492
	<step>

	^ ((Dictionary new) add: (#definition->#'031fa7ee-1f71-1c45-9f1c-d564b6f4fe3f'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'5 February 2015 11:07:09 am'); yourself)); add: (#isProperty->false); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'f5b6fe79-d737-a741-8544-d9a42eab1492'); add: (#isReference->true); add: (#viewDefinition->#treePlain); yourself)