steps
stepdebugger
	<step>

	^ ((Dictionary new) add: (#definition->#'08309815-e076-8343-acd4-58f380aa3063'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->Debugger); add: (#creationAuthor->'mt'); add: (#view->ViMultiPaneWidget); add: (#creationTimeStamp->'3 February 2015 4:12:43 pm'); add: (#isNew->false); add: (#optimalExtent->(448@498)); add: (#locked->true); yourself)); add: (#isProperty->true); add: (#next->#'931d2a74-8b0f-394e-a924-0cde9505c977'); add: (#label->'Debugger'); add: (#iconCode->'nil'); add: (#id->#debugger); add: (#isReference->false); add: (#viewDefinition->#treePlain); yourself)