steps
step4082edcf60a9bd4db3155eced8f0aca4
	<step>

	^ ((Dictionary new) add: (#definition->#'cb5a8f25-e75f-044a-bb13-07d5c14b0c16'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#view->ViArtifactListView2); add: (#creationTimeStamp->'1 February 2015 7:25:43 pm'); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'4082edcf-60a9-bd4d-b315-5eced8f0aca4'); add: (#isReference->false); add: (#viewDefinition->#treePlain); yourself)