steps
step0247b980eb3f29438e5df710aa04069d
	<step>

	^ ((Dictionary new) add: (#definition->#'7425312b-ce63-104f-907a-61011f4f8dbc'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'5 February 2015 12:29:20 pm'); yourself)); add: (#isProperty->false); add: (#next->#'a2d181f5-415d-5c4e-afa9-b41ec20c9deb'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'0247b980-eb3f-2943-8e5d-f710aa04069d'); add: (#isReference->false); add: (#viewDefinition->#treePlain); yourself)