commands
command9898b9d44d00954d98fd7ad14fbe2dee
	<command>

	^ ((Dictionary new) add: (#definition->#'250805b9-1be7-c744-9a12-2ccaa6d3670c'); add: (#class->ViQueryCommand); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'10 February 2014 3:57:18 pm'); yourself)); add: (#id->#'9898b9d4-4d00-954d-98fd-7ad14fbe2dee'); add: (#iconCode->'UiFugueIcons controlPauseIcon'); add: (#label->'Suspend'); yourself)