commands
command5b8a8a71a0bbb944bdc260b3f367317e
	<command>

	^ ((Dictionary new) add: (#definition->#'b4a6a1f0-3bb5-9e46-bc4d-84a9213e28d8'); add: (#class->ViQueryCommand); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 February 2014 5:35:38 pm'); yourself)); add: (#id->#'5b8a8a71-a0bb-b944-bdc2-60b3f367317e'); add: (#iconCode->'nil'); add: (#label->'Unwind'); yourself)