commands
command26271ef3bb086643ac172a09d20761ea
	<command>

	^ ((Dictionary new) add: (#definition->#'80db6f1a-d17b-8c4e-a2b9-35243e24ef05'); add: (#class->ViQueryCommand); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'5 February 2014 4:42:14 pm'); yourself)); add: (#id->#'26271ef3-bb08-6643-ac17-2a09d20761ea'); add: (#iconCode->'UiFugueIcons layerPlusIcon'); add: (#label->'Create morph in hand'); yourself)