commands
command93bc2c1d521151468b304317d085c09d
	<command>

	^ ((Dictionary new) add: (#definition->#'4dcfff32-64f3-a54d-955e-faab62251b7d'); add: (#class->ViQueryCommand); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'7 February 2014 2:29:31 pm'); yourself)); add: (#id->#'93bc2c1d-5211-5146-8b30-4317d085c09d'); add: (#iconCode->'UiFugueIcons arrowStepOverIcon'); add: (#label->'Over'); yourself)