commands
command81bfe1b01618de48a67d8913eb4b4564
	<command>

	^ ((Dictionary new) add: (#definition->#'690e8c35-7eef-244c-85c1-020bccc1243e'); add: (#class->ViQueryCommand); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'10 February 2014 3:50:17 pm'); yourself)); add: (#id->#'81bfe1b0-1618-de48-a67d-8913eb4b4564'); add: (#iconCode->'UiFugueIcons controlStopSquareIcon'); add: (#label->'Terminate'); yourself)