commands
command94f658350c5e014ea42c2408e26ff3b2
	<command>

	^ ((Dictionary new) add: (#definition->#'e75b2027-7d4f-e24d-8ad3-4f7a91ea05e6'); add: (#class->ViQueryCommand); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'6 June 2014 11:30:26 am'); yourself)); add: (#id->#'94f65835-0c5e-014e-a42c-2408e26ff3b2'); add: (#iconCode->'UiSilkIcons cogIcon'); add: (#label->nil); yourself)