commands
command4fea03ad94df94469c816ac378d2d0e5
	<command>

	^ ((Dictionary new) add: (#definition->#'c1709374-1f27-5d45-9131-8defe81a40da'); add: (#class->ViQueryCommand); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 February 2014 1:06:19 pm'); yourself)); add: (#id->#'4fea03ad-94df-9446-9c81-6ac378d2d0e5'); add: (#iconCode->'nil'); add: (#label->'Run Selected'); yourself)