commands
commandc93610dc3aebb645bec6eb824792657c
	<command>

	^ ((Dictionary new) add: (#definition->#'afd86e99-aa29-7e41-ad95-b40388cb2cde'); add: (#class->ViQueryCommand); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 February 2014 2:20:02 pm'); yourself)); add: (#id->#'c93610dc-3aeb-b645-bec6-eb824792657c'); add: (#iconCode->'nil'); add: (#label->'Run failures'); yourself)