definitions
def0d9c1713c12c064eb583ff4df2c3f4de
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'15 June 2015 10:01:59 am'); yourself)); add: (#id->#'0d9c1713-c12c-064e-b583-ff4df2c3f4de'); add: (#block->[:in :out | [#groupsUnsorted] value in: [:result |
	out addAll: result asList]]); add: (#sourceCode->'[:in :out | [#groupsUnsorted] value in: [:result |
	out addAll: result asList]]'); yourself)