definitions
def0359b0f142e5ef4cb9933022fe9fa515
	<definition>

	^ ((Dictionary new) add: (#inputKind->FileDirectory); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'0359b0f1-42e5-ef4c-b993-3022fe9fa515'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:dirs | dirs gather: [:dir | dir entries]]'); add: (#mapType->#all); add: (#block->[:dirs | dirs gather: [:dir | dir entries]]); yourself)