definitions
def0f6ea4845e59cf42903b7c7ae1e08a1b
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 September 2013 7:22:26 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'0f6ea484-5e59-cf42-903b-7c7ae1e08a1b'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:selectors :context | context contents select: [:ref | selectors includes: ref selector]]'); add: (#mapType->#all); add: (#block->[:selectors :context | context contents select: [:ref | selectors includes: ref selector]]); yourself)