definitions
def06752cb1e5f3b847894650a90ce30938
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 February 2014 3:56:01 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->SystemOrganizer); add: (#id->#'06752cb1-e5f3-b847-8946-50a90ce30938'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[SystemOrganization]'); add: (#mapType->#all); add: (#block->[SystemOrganization]); yourself)