definitions
def0ef356e72ba99e49a8996f24e6c8fda2
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'3 February 2014 5:06:25 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'0ef356e7-2ba9-9e49-a899-6f24e6c8fda2'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | obj hResizing]'); add: (#mapType->#each); add: (#block->[:obj | obj hResizing]); yourself)