definitions
def0fee1e3fc9f89042b64688feee2a13c8
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'8 November 2013 4:10:44 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'0fee1e3f-c9f8-9042-b646-88feee2a13c8'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | obj value identityHash]'); add: (#mapType->#each); add: (#block->[:obj | obj value identityHash]); yourself)