definitions
def07e0d51c6985144cbc8d08c8e9bb8d4d
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 February 2014 12:43:11 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Behavior); add: (#id->#'07e0d51c-6985-144c-bc8d-08c8e9bb8d4d'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[TestCase withAllSubclasses]'); add: (#mapType->#all); add: (#block->[TestCase withAllSubclasses]); yourself)