definitions
def0500ed1b71282d43b30789fd1223197d
	<definition>

	^ ((Dictionary new) add: (#inputKind->MethodReference); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'10 January 2014 12:45:19 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->CompiledMethod); add: (#id->#'0500ed1b-7128-2d43-b307-89fd1223197d'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:ref | ref compiledMethod]'); add: (#mapType->#each); add: (#block->[:ref | ref compiledMethod]); yourself)