definitions
def0bc0ce7e2194504ab60b9cd9c19cef01
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Boolean); add: (#id->#'0bc0ce7e-2194-504a-b60b-9cd9c19cef01'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj1 :obj2 | obj1 timeStamp >= obj2 timeStamp]'); add: (#mapType->#twoArgs); add: (#block->[:obj1 :obj2 | obj1 timeStamp >= obj2 timeStamp]); yourself)