definitions
def0323673bfb73094980cbc60b8a50300c
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'20 September 2014 12:07 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'0323673b-fb73-0949-80cb-c60b8a50300c'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:o | {o. 1}]'); add: (#mapType->#each); add: (#block->[:o | {o. 1}]); yourself)