definitions
def0822445589e81b48b01dde8f5a01861d
	<definition>

	^ ((Dictionary new) add: (#inputKind->Class); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 September 2013 7:46:24 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Class); add: (#id->#'08224455-89e8-1b48-b01d-de8f5a01861d'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:classes | classes select: [:cls | cls organization classComment isEmpty]]'); add: (#mapType->#all); add: (#block->[:classes | classes select: [:cls | cls organization classComment isEmpty]]); yourself)