definitions
def010d5fed1ded83408190604f3aec0c66
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'17 January 2014 3:00:32 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'010d5fed-1ded-8340-8190-604f3aec0c66'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:cls | (PackageOrganizer default packageOfClass: cls ifNone: [])
	ifNil: [''local'']
	ifNotNil: [:pkg | pkg name]]'); add: (#mapType->#each); add: (#block->[:cls | (PackageOrganizer default packageOfClass: cls ifNone: [])
	ifNil: ['local']
	ifNotNil: [:pkg | pkg name]]); yourself)