definitions
def052a74fa7606c9419a371dead31a8a3e
	<definition>

	^ ((Dictionary new) add: (#inputKind->Categorizer); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'052a74fa-7606-c941-9a37-1dead31a8a3e'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:objs | objs gather: [:obj | obj categories]]'); add: (#mapType->#all); add: (#block->[:objs | objs gather: [:obj | obj categories]]); yourself)