definitions
def06639145042cc047b4ce1c80d1cb3a1d
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'23 June 2014 9:21:07 am'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'06639145-042c-c047-b4ce-1c80d1cb3a1d'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | obj inputKind]'); add: (#mapType->#each); add: (#block->[:obj | obj inputKind]); yourself)