definitions
def0b9b9237a5c1a54d854e19b74df33a48
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'2 May 2014 1:33:49 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'0b9b9237-a5c1-a54d-854e-19b74df33a48'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:object | #text -> object asString]'); add: (#mapType->#each); add: (#block->[:object | #text -> object asString]); yourself)