definitions
def0f87191735c9bc4c99309e114ddd246f
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'7 August 2014 5:16:32 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'0f871917-35c9-bc4c-9930-9e114ddd246f'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:numbers | numbers select: [:number | number even]]'); add: (#mapType->#all); add: (#block->[:numbers | numbers select: [:number | number even]]); yourself)