definitions
def15e12cef2062054cb8ea00b1897b9aac
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'23 August 2014 4:11:18 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'15e12cef-2062-054c-b8ea-00b1897b9aac'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:morph :bindings | #bindings -> bindings]'); add: (#mapType->#each); add: (#block->[:morph :bindings | #bindings -> bindings]); yourself)