definitions
def10e1bc48e516e64196b85951358362c2
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryUpdateDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'31 January 2014 5:13 pm'); yourself)); add: (#id->#'10e1bc48-e516-e641-96b8-5951358362c2'); add: (#block->[:model | SystemChangeNotifier uniqueInstance
	notify: model ofSystemChangesOfItem: AbstractEvent expressionKind change: DoItEvent changeKind using: #refresh]); add: (#sourceCode->'[:model | SystemChangeNotifier uniqueInstance
	notify: model ofSystemChangesOfItem: AbstractEvent expressionKind change: DoItEvent changeKind using: #refresh]'); yourself)