definitions
def110cd1a97a947345a3d8482f7c4670f9
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'25 July 2014 6:20:43 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'110cd1a9-7a94-7345-a3d8-482f7c4670f9'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | #text -> obj printString]'); add: (#mapType->#each); add: (#block->[:obj | #text -> obj printString]); yourself)