definitions
def12e82498d1a4694c80a68ad84486b76a
	<definition>

	^ ((Dictionary new) add: (#inputKind->ViFlagComment); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 September 2013 9:22:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'12e82498-d1a4-694c-80a6-8ad84486b76a'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:flag | {
	#icon -> (ViIconServiceForEclipse doObject: flag reference). 
	#text -> ((ViLabelServiceForEclipse doObject: flag reference),
		'' ('', (ViLabelServiceForEclipse doObject: flag reference actualClass), '')'')}]'); add: (#mapType->#each); add: (#block->[:flag | {
	#icon -> (ViIconServiceForEclipse doObject: flag reference). 
	#text -> ((ViLabelServiceForEclipse doObject: flag reference),
		' (', (ViLabelServiceForEclipse doObject: flag reference actualClass), ')')}]); yourself)