definitions
def1b0474886502e74e83f205ae0fbf0400
	<definition>

	^ ((Dictionary new) add: (#inputKind->DirectoryEntryDirectory); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'3 January 2014 3:14:09 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->FileDirectory); add: (#id->#'1b047488-6502-e74e-83f2-05ae0fbf0400'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:entry | entry asFileDirectory]'); add: (#mapType->#each); add: (#block->[:entry | entry asFileDirectory]); yourself)