definitions
def12390d96f96ae34ea8b159c6c8d26fa1
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'12390d96-f96a-e34e-a8b1-59c6c8d26fa1'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | #text -> ((obj isKindOf: MethodReference)
	ifTrue: [obj category] ifFalse: [''''])]'); add: (#mapType->#each); add: (#block->[:obj | #text -> ((obj isKindOf: MethodReference)
	ifTrue: [obj category] ifFalse: [''])]); yourself)