definitions
def145841e8e96d2243acbf2de9c5697829
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 November 2013 4:59:12 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'145841e8-e96d-2243-acbf-2de9c5697829'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | ''a '', obj value class name]'); add: (#mapType->#each); add: (#block->[:obj | 'a ', obj value class name]); yourself)