definitions
def16b05fc9d8ef7845a1ef2347666faaab
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 January 2014 4:37:27 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'16b05fc9-d8ef-7845-a1ef-2347666faaab'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:o1 :o2 | o2 third withAllSuperclasses includes: o1 third]'); add: (#mapType->#twoArgs); add: (#block->[:o1 :o2 | o2 third withAllSuperclasses includes: o1 third]); yourself)