definitions
def16098badc8bf434ea06d18cd2a87edf8
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'15 November 2014 5:03:59 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'16098bad-c8bf-434e-a06d-18cd2a87edf8'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:objects | objects]'); add: (#mapType->#all); add: (#block->[:objects | objects]); yourself)