definitions
def1a63b3b5dd5bc242b72324e2fb3768d7
	<definition>

	^ ((Dictionary new) add: (#inputKind->ViQueryStepDefinition); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'3 September 2013 1:56:12 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'1a63b3b5-dd5b-c242-b723-24e2fb3768d7'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:def | #text -> (ViTextStyler new styledTextFor: def sourceCode asText)]'); add: (#mapType->#each); add: (#block->[:def | #text -> (ViTextStyler new styledTextFor: def sourceCode asText)]); yourself)