definitions
def2f28efd9bc15164f8584e049b306ecc8
	<definition>

	^ ((Dictionary new) add: (#inputKind->MethodReference); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'2f28efd9-bc15-164f-8584-e049b306ecc8'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:refs | refs gather: [:ref | ViMethodVersion versionsOfMethod: ref]]'); add: (#mapType->#all); add: (#block->[:refs | refs gather: [:ref | ViMethodVersion versionsOfMethod: ref]]); yourself)