definitions
def288a24da71d54941a763480ec269c6ea
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'288a24da-71d5-4941-a763-480ec269c6ea'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | (obj isKindOf: DirectoryEntryDirectory) ifTrue: [''a) Folders''] ifFalse: [''b) Files'']]'); add: (#mapType->#each); add: (#block->[:obj | (obj isKindOf: DirectoryEntryDirectory) ifTrue: ['a) Folders'] ifFalse: ['b) Files']]); yourself)