definitions
def2e76e4da8a81b141bbbce1c438ed5134
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Boolean); add: (#id->#'2e76e4da-8a81-b141-bbbc-e1c438ed5134'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj1 :obj2 | 
	(ViMethodVersion versionsOfMethod: obj1 methodReference) size >= 
	(ViMethodVersion versionsOfMethod: obj2 methodReference) size]'); add: (#mapType->#twoArgs); add: (#block->[:obj1 :obj2 | 
	(ViMethodVersion versionsOfMethod: obj1 methodReference) size >= 
	(ViMethodVersion versionsOfMethod: obj2 methodReference) size]); yourself)