definitions
def2aa15952d2b0a040a12d33a4aab9d51e
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryUpdateDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'16 November 2013 5:18:43 pm'); yourself)); add: (#id->#'2aa15952-d2b0-a040-a12d-33a4aab9d51e'); add: (#block->[:model | self connect: ViObjectHistory lastExceptions signal: #objectAdded: to: model selector: #refresh]); add: (#sourceCode->'[:model | self connect: ViObjectHistory lastExceptions signal: #objectAdded: to: model selector: #refresh]'); yourself)