definitions
def25ba5d71aab6224fb0c71fe9151c9ecc
	<definition>

	^ ((Dictionary new) add: (#inputKind->Array); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 November 2013 3:49:56 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'25ba5d71-aab6-224f-b0c7-1fe9151c9ecc'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:histogramSpec | histogramSpec third]'); add: (#mapType->#each); add: (#block->[:histogramSpec | histogramSpec third]); yourself)