definitions
def29d5729db656f14bb9f8bc0f01bcbc1b
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'25 July 2014 6:36:24 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'29d5729d-b656-f14b-b9f8-bc0f01bcbc1b'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:layer | {
	#text -> ''Activate''.
	#clicked -> [[layer activateLayerInCurrentProcess]]}]'); add: (#mapType->#each); add: (#block->[:layer | {
	#text -> 'Activate'.
	#clicked -> [[layer activateLayerInCurrentProcess]]}]); yourself)