definitions
def29ef7ed7ae7b734e983d8f574ee9c654
	<definition>

	^ ((Dictionary new) add: (#inputKind->ViQueryOrganizer); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'23 July 2014 2:43:44 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->ViQueryStep); add: (#id->#'29ef7ed7-ae7b-734e-983d-8f574ee9c654'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:orga | orga orderedSteps select: [:step | step isSpecial]]'); add: (#mapType->#each); add: (#block->[:orga | orga orderedSteps select: [:step | step isSpecial]]); yourself)