definitions
def24bf9bee27659c47bee307990a61c4a5
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'3 February 2014 5:08:07 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'24bf9bee-2765-9c47-bee3-07990a61c4a5'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | obj listDirection]'); add: (#mapType->#each); add: (#block->[:obj | obj listDirection]); yourself)