definitions
def2ed393602ab36649a7e6e69fbd93007d
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryUpdateDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'12 November 2013 5:04:17 pm'); yourself)); add: (#id->#'2ed39360-2ab3-6649-a7e6-e69fbd93007d'); add: (#block->[:model | (ViTimer named: model identityHash) delete]); add: (#sourceCode->'[:model | (ViTimer named: model identityHash) delete]'); yourself)