definitions
def239f5618cfad964689cbd2162d14e9c0
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'239f5618-cfad-9646-89cb-d2162d14e9c0'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:ref | ref classSymbol]'); add: (#mapType->#each); add: (#block->[:ref | ref classSymbol]); yourself)