definitions
def24c3b0255a000544aae1cdc7bb5acbd7
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'3 June 2014 11:01:14 am'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'24c3b025-5a00-0544-aae1-cdc7bb5acbd7'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:object | object class]'); add: (#mapType->#each); add: (#block->[:object | object class]); yourself)