definitions
def274930888837484dba3455061b4f955d
	<definition>

	^ ((Dictionary new) add: (#inputKind->ViClassComment); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Boolean); add: (#id->#'27493088-8837-484d-ba34-55061b4f955d'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj1 :obj2 | obj1 theClass name <= obj2 theClass name]'); add: (#mapType->#twoArgs); add: (#block->[:obj1 :obj2 | obj1 theClass name <= obj2 theClass name]); yourself)