definitions
def20b57dc387193442a59158a5621a7c33
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'25 July 2014 5:55:48 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'20b57dc3-8719-3442-a591-58a5621a7c33'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:partialMethod | #text -> partialMethod layers]'); add: (#mapType->#each); add: (#block->[:partialMethod | #text -> partialMethod layers]); yourself)