definitions
def26b2f1c93a623243a8c50bed5177fefc
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'25 July 2014 6:00:59 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'26b2f1c9-3a62-3243-a8c5-0bed5177fefc'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:method | #text -> method selector]'); add: (#mapType->#each); add: (#block->[:method | #text -> method selector]); yourself)