definitions
def2db5197302ae8443983798655c770597
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'24 August 2014 2:05:23 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'2db51973-02ae-8443-9837-98655c770597'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:node | #text -> (ViLabelService doObject: node clientMethod)]'); add: (#mapType->#each); add: (#block->[:node | #text -> (ViLabelService doObject: node clientMethod)]); yourself)