definitions
def2f2ca70660a53745978233256331f57f
	<definition>

	^ ((Dictionary new) add: (#inputKind->ViQueryMapDefinition); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'3 September 2013 1:58:21 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'2f2ca706-60a5-3745-9782-33256331f57f'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:def | ViLabelService doObject: def outputKind].'); add: (#mapType->#each); add: (#block->[:def | ViLabelService doObject: def outputKind]); yourself)