definitions
def236a8c89659c5349a716fd2bed0f7486
	<definition>

	^ ((Dictionary new) add: (#inputKind->MethodReference); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'9 January 2014 11:37 am'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->String); add: (#id->#'236a8c89-659c-5349-a716-fd2bed0f7486'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:ref | (PackageOrganizer default packageOfClass: ref actualClass ifNone: [])
	ifNil: [''(no package)''] ifNotNil: [:pkg | pkg name]]'); add: (#mapType->#each); add: (#block->[:ref | (PackageOrganizer default packageOfClass: ref actualClass ifNone: [])
	ifNil: ['(no package)'] ifNotNil: [:pkg | pkg name]]); yourself)