definitions
def2402473a838e5b4895fefe6648dcc28a
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'8 November 2013 4:22:27 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'2402473a-838e-5b48-95fe-fe6648dcc28a'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | obj isVariableBinding ifFalse: [#()] ifTrue: [
	{#icon -> UiFugueIcons tagSmallIcon. #balloonText -> ''Binding''}]]'); add: (#mapType->#each); add: (#block->[:obj | obj isVariableBinding ifFalse: [#()] ifTrue: [
	{#icon -> UiFugueIcons tagSmallIcon. #balloonText -> 'Binding'}]]); yourself)