definitions
def241c9e86fb0eb54ea1efe82d736786f3
	<definition>

	^ ((Dictionary new) add: (#inputKind->Set); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'20 February 2014 2:08:29 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'241c9e86-fb0e-b54e-a1ef-e82d736786f3'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:set | set asArray]'); add: (#mapType->#each); add: (#block->[:set | set asArray]); yourself)