definitions
def33f8655103cb684293b260ab7739faa3
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'25 July 2014 5:00:56 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'33f86551-03cb-6842-93b2-60ab7739faa3'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[#()]'); add: (#mapType->#all); add: (#block->[#()]); yourself)