definitions
def3eebee4c21b7944994fc5a6e31e7d282
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryUpdateDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 September 2013 6:19:02 pm'); yourself)); add: (#id->#'3eebee4c-21b7-9449-94fc-5a6e31e7d282'); add: (#block->[:model | self connect: ViObjectHistory transcriptHistory signal: #objectAdded: to: model selector: #refresh]); add: (#sourceCode->'[:model | self connect: ViObjectHistory transcriptHistory signal: #objectAdded: to: model selector: #refresh]'); yourself)