definitions
def325e9e39f956f3428b165d6be68397d0
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'23 July 2014 2:45:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'325e9e39-f956-f342-8b16-5d6be68397d0'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:steps | steps sorted: [:s1 :s2 | s1 id <= s2 id]]'); add: (#mapType->#all); add: (#block->[:steps | steps sorted: [:s1 :s2 | s1 id <= s2 id]]); yourself)