definitions
def3a43e006f8b96c4b8214c5f909d653f2
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'23 September 2013 4:37:47 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'3a43e006-f8b9-6c4b-8214-c5f909d653f2'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:u1 :u2 | (u1 at: #fullName) asLowercase <= (u2 at: #fullName) asLowercase]'); add: (#mapType->#twoArgs); add: (#block->[:u1 :u2 | (u1 at: #fullName) asLowercase <= (u2 at: #fullName) asLowercase]); yourself)