definitions
def3effbacd72525f499e88402670a2fd5e
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'7 August 2014 5:16:36 pm'); yourself)); add: (#id->#'3effbacd-7252-5f49-9e88-402670a2fd5e'); add: (#block->[:morph | morph submorphs]); add: (#sourceCode->'[:morph | morph submorphs]'); yourself)