definitions
def3512b514223f4e4a8c8da3a0c4594138
	<definition>

	^ ((Dictionary new) add: (#inputKind->ByteSymbol); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'8 October 2014 10:24:14 am'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->MethodReference); add: (#id->#'3512b514-223f-4e4a-8c8d-a3a0c4594138'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:symbol | SystemNavigation default allCallsOn: symbol]'); add: (#mapType->#each); add: (#block->[:symbol | SystemNavigation default allCallsOn: symbol]); yourself)