definitions
def3d30f84866236f4bb599ca6fffd99810
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Boolean); add: (#id->#'3d30f848-6623-6f4b-b599-ca6fffd99810'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:p1 :p2 | p1 baseName asLowercase <= p2 baseName asLowercase]'); add: (#mapType->#twoArgs); add: (#block->[:p1 :p2 | p1 baseName asLowercase <= p2 baseName asLowercase]); yourself)