definitions
def3bdecc0789339f418381c3e613996d08
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 September 2013 7:03:26 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'3bdecc07-8933-9f41-8381-c3e613996d08'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:flag | #text -> (ViObjectOriginService doObject: flag reference)]'); add: (#mapType->#each); add: (#block->[:flag | #text -> (ViObjectOriginService doObject: flag reference)]); yourself)