definitions
def3ef99323b3c060468f1325fd163dc315
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'25 July 2014 6:33:56 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'3ef99323-b3c0-6046-8f13-25fd163dc315'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:process | process csInfo activeLayers]'); add: (#mapType->#each); add: (#block->[:process | process csInfo activeLayers]); yourself)