definitions
def305fb70989ff5047a907b30525b1cfdb
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'25 July 2014 5:53:11 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'305fb709-89ff-5047-a907-b30525b1cfdb'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:class | class methodDict values]'); add: (#mapType->#each); add: (#block->[:class | class methodDict values]); yourself)