definitions
def37242639304c7d40a3b17ac5c718ca3e
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'7 October 2014 12:55:13 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'37242639-304c-7d40-a3b1-7ac5c718ca3e'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | obj color]'); add: (#mapType->#each); add: (#block->[:obj | obj color]); yourself)