definitions
def48f0bb0fb73d4d4a89a4d68e5f89f019
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'11 February 2014 10:25:52 am'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'48f0bb0f-b73d-4d4a-89a4-d68e5f89f019'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:ass1 :ass2 | ass1 key <= ass2 key]'); add: (#mapType->#twoArgs); add: (#block->[:ass1 :ass2 | ass1 key <= ass2 key]); yourself)