definitions
def4faf0cdee73acc4082248c497290e51f
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'14 January 2014 1:18:03 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'4faf0cde-e73a-cc40-8224-8c497290e51f'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | #text -> obj category]'); add: (#mapType->#each); add: (#block->[:obj | #text -> obj category]); yourself)