definitions
def42b080f1f789de468d53de288f085a5a
	<definition>

	^ ((Dictionary new) add: (#inputKind->ViExceptionHistory); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'16 November 2013 4:51:28 pm'); yourself)); add: (#updateClearDefinition->#'acc7835d-73e6-1c45-80c0-4dcbfc225273'); add: (#outputKind->Object); add: (#id->#'42b080f1-f789-de46-8d53-de288f085a5a'); add: (#updateSetDefinition->#'2aa15952-d2b0-a040-a12d-33a4aab9d51e'); add: (#sourceCode->'[:history | history objects reversed]'); add: (#mapType->#each); add: (#block->[:history | history objects reversed]); yourself)