definitions
def4ed0c30426affe4882590553dbe3f8e0
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'20 February 2014 6:27:55 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'4ed0c304-26af-fe48-8259-0553dbe3f8e0'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:o1 :o2 | o1 value selector <= o2 value selector]'); add: (#mapType->#twoArgs); add: (#block->[:o1 :o2 | o1 value selector <= o2 value selector]); yourself)