definitions
def4b7d9fc60087ba48adab369028443808
	<definition>

	^ ((Dictionary new) add: (#inputKind->Number); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'7 August 2014 5:16:26 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Number); add: (#id->#'4b7d9fc6-0087-ba48-adab-369028443808'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:o | o]'); add: (#mapType->nil); add: (#block->[:o | o]); yourself)