definitions
def4716640ebeab794084463c1703cbc16c
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'25 July 2014 5:57:23 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'4716640e-beab-7940-8446-3c1703cbc16c'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[PackageOrganizer default packageOfClass: BoBreakout]'); add: (#mapType->#all); add: (#block->[PackageOrganizer default packageOfClass: BoBreakout]); yourself)