definitions
def44bdd3d3ea3e54468a1a5edacc6d70f1
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'20 October 2014 6:54:14 am'); yourself)); add: (#id->#'44bdd3d3-ea3e-5446-8a1a-5edacc6d70f1'); add: (#block->[:in :out | out addAll: in]); add: (#sourceCode->'[:in :out | out addAll: in]'); yourself)