definitions
def47cabae43c613b4fa16b87529b48d989
	<definition>

	^ ((Dictionary new) add: (#inputKind->ClassDescription); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'47cabae4-3c61-3b4f-a16b-87529b48d989'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:classes | classes gather: [:cls |
	cls allInstVarNames collect: [:nm |
		nm -> cls]]]'); add: (#mapType->#all); add: (#block->[:classes | classes gather: [:cls |
	cls allInstVarNames collect: [:nm |
		nm -> cls]]]); yourself)