definitions
def42833415c0c15547a2d42379c3d211c3
	<definition>

	^ ((Dictionary new) add: (#inputKind->ProtoObject); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'42833415-c0c1-5547-a2d4-2379c3d211c3'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:objs | objs collect: [:obj | #root -> obj]]'); add: (#mapType->#all); add: (#block->[:objs | objs collect: [:obj | #root -> obj]]); yourself)