definitions
def4d86db4d38b87d42b937130dce32f786
	<definition>

	^ ((Dictionary new) add: (#inputKind->ViFlagComment); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 September 2013 9:29:04 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'4d86db4d-38b8-7d42-b937-130dce32f786'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:flag | #text -> (ViObjectOriginServiceForEclipse doObject: flag reference)]'); add: (#mapType->#each); add: (#block->[:flag | #text -> (ViObjectOriginServiceForEclipse doObject: flag reference)]); yourself)