definitions
def41c2edc3e4a9ac419961471d263f2bb3
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'25 July 2014 3:50:03 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'41c2edc3-e4a9-ac41-9961-471d263f2bb3'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:method | #text -> method selector]'); add: (#mapType->#each); add: (#block->[:method | #text -> method selector]); yourself)