definitions
def490cdda445bc414db6a5e84c85f44b30
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'11 February 2014 10:06:57 am'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'490cdda4-45bc-414d-b6a5-e84c85f44b30'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[(Smalltalk globals instVarNamed: #bindings) associations select: [:assoc |
		assoc value isBehavior not]]'); add: (#mapType->#all); add: (#block->[(Smalltalk globals instVarNamed: #bindings) associations select: [:assoc |
		assoc value isBehavior not]]); yourself)