definitions
def47f39abb007bd644ab86327d7a0b38b9
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'24 August 2014 1:42:40 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'47f39abb-007b-d644-ab86-327d7a0b38b9'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:o | o]'); add: (#mapType->#each); add: (#block->[:o | o]); yourself)