definitions
def4ff8fae9936f1e42bbcff1996db5a9b2
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'25 July 2014 6:07:41 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'4ff8fae9-936f-1e42-bbcf-f1996db5a9b2'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:layer | {
	#text -> ''Activate''.
	#clicked -> [[layer activateLayerInCurrentProcess]]}]'); add: (#mapType->#each); add: (#block->[:layer | {
	#text -> 'Activate'.
	#clicked -> [[layer activateLayerInCurrentProcess]]}]); yourself)