definitions
def455ad2d30d117742930183c3bf906e8b
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Boolean); add: (#id->#'455ad2d3-0d11-7742-9301-83c3bf906e8b'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj1 :obj2 | obj1 value <= obj2 value]'); add: (#mapType->#twoArgs); add: (#block->[:obj1 :obj2 | obj1 value <= obj2 value]); yourself)