definitions
def514e33c149efdb4aab271b67d793b46b
	<definition>

	^ ((Dictionary new) add: (#inputKind->MethodContext); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'31 January 2014 6:41:42 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->CompiledMethod); add: (#id->#'514e33c1-49ef-db4a-ab27-1b67d793b46b'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:ctxt | ctxt method]'); add: (#mapType->#each); add: (#block->[:ctxt | ctxt method]); yourself)