definitions
def5373c261bd631849a4700982b3e49dc4
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'7 August 2014 5:16:34 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'5373c261-bd63-1849-a470-0982b3e49dc4'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:morph | morph submorphs]'); add: (#mapType->#all); add: (#block->[:morph | morph submorphs]); yourself)