definitions
def5bcb73c59ad5054d90c6997215e79578
	<definition>

	^ ((Dictionary new) add: (#inputKind->ViTranscriptHistory); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 November 2013 9:09:07 am'); yourself)); add: (#updateClearDefinition->#'a1bf1391-ab8a-9a43-bbe0-f9ecf7d38994'); add: (#outputKind->Object); add: (#id->#'5bcb73c5-9ad5-054d-90c6-997215e79578'); add: (#updateSetDefinition->#'3eebee4c-21b7-9449-94fc-5a6e31e7d282'); add: (#sourceCode->'[:history | history objects]'); add: (#mapType->#each); add: (#block->[:history | history objects]); yourself)