definitions
def5145e01072f64445928e4c29d9b0e577
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'7 October 2014 12:55:25 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'5145e010-72f6-4445-928e-4c29d9b0e577'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | #text -> obj asString]'); add: (#mapType->#each); add: (#block->[:obj | #text -> obj asString]); yourself)