definitions
def5ca6f96bb7e5ae47b4422abfa2f51046
	<definition>

	^ ((Dictionary new) add: (#inputKind->ClassDescription); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'17 January 2014 3:22:32 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'5ca6f96b-b7e5-ae47-b442-2abfa2f51046'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:cls | cls methodDict values size + cls class methodDict values size]'); add: (#mapType->#each); add: (#block->[:cls | cls methodDict values size + cls class methodDict values size]); yourself)