definitions
def512b0ad50883a9489a82ebb513c66ded
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'25 July 2014 6:30:59 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'512b0ad5-0883-a948-9a82-ebb513c66ded'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:ref | ref method layers]'); add: (#mapType->#each); add: (#block->[:ref | ref method layers]); yourself)