definitions
def5e5e8f9b8b6b5c49b1687778f6a70821
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'25 July 2014 2:17:38 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'5e5e8f9b-8b6b-5c49-b168-7778f6a70821'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:layer |
	{#text -> ''Activate''.
	#clicked -> [[layer layerName activateLayerInCurrentProcess]]}].'); add: (#mapType->#each); add: (#block->[:layer |
	{#text -> 'Activate'.
	#clicked -> [[layer layerName activateLayerInCurrentProcess]]}]); yourself)