definitions
def5cffadc0186c6549ba944aad637db20e
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'29 January 2015 9:06:41 am'); yourself)); add: (#id->#'5cffadc0-186c-6549-ba94-4aad637db20e'); add: (#block->[:in :out | out add: {#objects -> in}, [{
	#bounds -> (1@240 corner: 496@479).
	#current -> #'97c5c552-1f75-204a-8c7d-09950799f3c9'.
	#id -> #'366396d9-b3f1-0c42-92e3-3dce19bbdfba'.
	#out -> #().
	#in -> #(#(#interactive #'8abaf74e-bf8e-d74a-9903-f078692babb2' ) ).
}] value]); add: (#sourceCode->'[:in :out | out add: {#objects -> in}, [{
	#bounds -> (1@240 corner: 496@479).
	#current -> #''97c5c552-1f75-204a-8c7d-09950799f3c9''.
	#id -> #''366396d9-b3f1-0c42-92e3-3dce19bbdfba''.
	#out -> #().
	#in -> #(#(#interactive #''8abaf74e-bf8e-d74a-9903-f078692babb2'' ) ).
}] value]'); yourself)