definitions
def59640e42b31e9b4a9c48776e3acd55bc
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'59640e42-b31e-9b4a-9c48-776e3acd55bc'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | {#text -> obj description. #icon -> UiSilkIcons databaseIcon}]'); add: (#mapType->#each); add: (#block->[:obj | {#text -> obj description. #icon -> UiSilkIcons databaseIcon}]); yourself)