definitions
def5461ed6457d6df478ea96c72de426d1d
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'20 December 2013 11:55:55 am'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'5461ed64-57d6-df47-8ea9-6c72de426d1d'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:step | (step steps collect: [:s | s category ifNil: #default]) asSet asArray asString]'); add: (#mapType->#each); add: (#block->[:step | (step steps collect: [:s | s category ifNil: #default]) asSet asArray asString]); yourself)