definitions
def5d37fd8fae041049a2558c3fd77a5406
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'30 August 2014 2:09:20 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'5d37fd8f-ae04-1049-a255-8c3fd77a5406'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:dict | #bindings -> dict]'); add: (#mapType->#each); add: (#block->[:dict | #bindings -> dict]); yourself)