definitions
def69d885825b2fab488b6499d72b1432a0
	<definition>

	^ ((Dictionary new) add: (#inputKind->ContextPart); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'69d88582-5b2f-ab48-8b64-99d72b1432a0'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:ctxts | ctxts gather: [:ctxt | ctxt stack]]'); add: (#mapType->#all); add: (#block->[:ctxts | ctxts gather: [:ctxt | ctxt stack]]); yourself)