definitions
def6b3d9fbe3f818048ab4b2b31f970a06d
	<definition>

	^ ((Dictionary new) add: (#inputKind->MessageTally); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->MessageTally); add: (#id->#'6b3d9fbe-3f81-8048-ab4b-2b31f970a06d'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:tally | (tally sonsOver: 0) sort]'); add: (#mapType->#each); add: (#block->[:tally | (tally sonsOver: 0) sort]); yourself)