definitions
def690b17d5dad2a44ba4d23fbdb4438517
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'25 July 2014 4:16:09 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'690b17d5-dad2-a44b-a4d2-3fbdb4438517'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:method | #text -> method methodClass name]'); add: (#mapType->#each); add: (#block->[:method | #text -> method methodClass name]); yourself)