definitions
def6f38796b7a6d494e926ea2dc03b50f2e
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'6f38796b-7a6d-494e-926e-a2dc03b50f2e'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:entry | #text -> entry name]'); add: (#mapType->#each); add: (#block->[:entry | #text -> entry name]); yourself)