definitions
def60c838c8d1a17d4ca00f3210018bcdaa
	<definition>

	^ ((Dictionary new) add: (#class->ViQuerySnippetDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'10 February 2014 4:40:47 pm'); yourself)); add: (#id->#'60c838c8-d1a1-7d4c-a00f-3210018bcdaa'); add: (#inputKind->ViToolSet class); add: (#block->nil); add: (#sourceCode->'ViProfile active serializeIntoArchive.'); add: (#receiverIsCollection->false); yourself)