definitions
def6d71677a79c43e4ca18031bd087f6170
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 August 2014 10:38:28 am'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'6d71677a-79c4-3e4c-a180-31bd087f6170'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:class | class name]'); add: (#mapType->#each); add: (#block->[:class | class name]); yourself)