definitions
def6a55f686f73fd94cb810e6a946eb771a
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'23 September 2013 5:12:03 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'6a55f686-f73f-d94c-b810-e6a946eb771a'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | obj at: #website]'); add: (#mapType->#each); add: (#block->[:obj | obj at: #website]); yourself)