definitions
def64d8a552c5676b4eaa78382859927a24
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 September 2013 6:06:33 pm'); yourself)); add: (#updateClearDefinition->#'a1bf1391-ab8a-9a43-bbe0-f9ecf7d38994'); add: (#outputKind->ViObjectHistory); add: (#id->#'64d8a552-c567-6b4e-aa78-382859927a24'); add: (#updateSetDefinition->#'3eebee4c-21b7-9449-94fc-5a6e31e7d282'); add: (#sourceCode->'[ViObjectHistory transcriptHistory]'); add: (#mapType->#all); add: (#block->[ViObjectHistory transcriptHistory]); yourself)