definitions
def6fc21acaed2f29478bb3cdc18cec4300
	<definition>

	^ ((Dictionary new) add: (#inputKind->((Array new: 3) at: 1 put: CompiledMethod; at: 2 put: Dictionary; at: 3 put: Object; yourself)); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'23 August 2014 4:20:41 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'6fc21aca-ed2f-2947-8bb3-cdc18cec4300'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:method :bindings :receiver | {
	#text -> method selector.
	#bindings -> bindings.
	#self -> receiver.
	}]'); add: (#mapType->#each); add: (#block->[:method :bindings :receiver | {
	#text -> method selector.
	#bindings -> bindings.
	#self -> receiver.
	}]); yourself)