definitions
def6ef6e1035dab61468b8fcac1e892db2c
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'25 July 2014 6:30:30 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'6ef6e103-5dab-6146-8b8f-cac1e892db2c'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:package | package layeredMethods]'); add: (#mapType->#each); add: (#block->[:package | package layeredMethods]); yourself)