definitions
def6f431f2ffd853841a679a7cb8348ba6f
	<definition>

	^ ((Dictionary new) add: (#inputKind->PackageInfo); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'6f431f2f-fd85-3841-a679-a7cb8348ba6f'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:packages | packages gather: [:pkg | pkg systemCategories]]'); add: (#mapType->#all); add: (#block->[:packages | packages gather: [:pkg | pkg systemCategories]]); yourself)