definitions
def6a44269ae17df046bf8fb446ad7082d0
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 September 2013 5:27:17 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'6a44269a-e17d-f046-bf8f-b446ad7082d0'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | obj isVariableBinding ifTrue: [''variables''] ifFalse: [''methods'']]'); add: (#mapType->#each); add: (#block->[:obj | obj isVariableBinding ifTrue: ['variables'] ifFalse: ['methods']]); yourself)