definitions
def6975eef04e5f5542b7b0e35b1872410b
	<definition>

	^ ((Dictionary new) add: (#inputKind->ViQueryStepDefinition); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'9 September 2013 12:03:08 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->ViAbstractQueryPart); add: (#id->#'6975eef0-4e5f-5542-b7b0-e35b1872410b'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:def | def organization referencesToDefinition: def]'); add: (#mapType->#each); add: (#block->[:def | def organization referencesToDefinition: def]); yourself)