definitions
def6b3817b2b8c827428d61c505ff2e3811
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'25 July 2014 4:12:23 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'6b3817b2-b8c8-2742-8d61-c505ff2e3811'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:layer | (CSLayer layerNamed: layer) allContainingPartialMethods]'); add: (#mapType->#each); add: (#block->[:layer | (CSLayer layerNamed: layer) allContainingPartialMethods]); yourself)