definitions
def66cd48ee25f8f845b64877d9a1ca2dfe
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'66cd48ee-25f8-f845-b648-77d9a1ca2dfe'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:binding | ViToolSet printRelativeTimeStamp: binding key]'); add: (#mapType->#each); add: (#block->[:binding | ViToolSet printRelativeTimeStamp: binding key]); yourself)