definitions
def6c95cc6b0e48154685023a80b7c40f2f
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'25 July 2014 6:04:12 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'6c95cc6b-0e48-1546-8502-3a80b7c40f2f'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:process | process csInfo activeLayers]'); add: (#mapType->#each); add: (#block->[:process | process csInfo activeLayers]); yourself)