definitions
def637834ffc53d7046a8b0edf73f34ff52
	<definition>

	^ ((Dictionary new) add: (#inputKind->ViSmalltalkHub); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 September 2013 5:31:55 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'637834ff-c53d-7046-a8b0-edf73f34ff52'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:hub | hub users collect: [:username | hub user: username]]'); add: (#mapType->#each); add: (#block->[:hub | hub users collect: [:username | hub user: username]]); yourself)