definitions
def7fbeb02017a5a44b8452d00317b036af
	<definition>

	^ ((Dictionary new) add: (#inputKind->CompiledMethod); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'10 January 2014 12:44:36 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->RBProgramNode); add: (#id->#'7fbeb020-17a5-a44b-8452-d00317b036af'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:method | RBParser parseMethod: method getSource asString]'); add: (#mapType->#each); add: (#block->[:method | RBParser parseMethod: method getSource asString]); yourself)