definitions
def73e8373651448f47ba713ddb8ee006e5
	<definition>

	^ ((Dictionary new) add: (#inputKind->ClassDescription); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'73e83736-5144-8f47-ba71-3ddb8ee006e5'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:classes | classes, (classes gather: [:cls | cls allSubclasses])]'); add: (#mapType->#all); add: (#block->[:classes | classes, (classes gather: [:cls | cls allSubclasses])]); yourself)