definitions
def7f5468a31dc7134092124ad1ee77effc
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'3 February 2014 5:06:08 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'7f5468a3-1dc7-1340-9212-4ad1ee77effc'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | obj class name]'); add: (#mapType->#each); add: (#block->[:obj | obj class name]); yourself)