definitions
def7fc05c0bec639941b2b923e072ab4367
	<definition>

	^ ((Dictionary new) add: (#inputKind->PackageOrganizer); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'11 February 2014 1:08:56 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->PackageInfo); add: (#id->#'7fc05c0b-ec63-9941-b2b9-23e072ab4367'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:packageOrganizer | packageOrganizer packages]'); add: (#mapType->#each); add: (#block->[:packageOrganizer | packageOrganizer packages]); yourself)