definitions
def76f36645fc82934fb3dc39bbd55f0230
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'29 January 2015 9:05:26 am'); yourself)); add: (#id->#'76f36645-fc82-934f-b3dc-39bbd55f0230'); add: (#block->[:in :out | out add: {#objects -> in}, [{
	#bounds -> (1@484 corner: 496@554).
	#current -> #'3287c263-0d1a-e846-bf34-db0b5784a8f6'.
	#id -> #'07957917-91c1-5742-9bcf-8067e699de3b'.
	#out -> #().
	#in -> #(#(#interactive #'8abaf74e-bf8e-d74a-9903-f078692babb2' ) ).
}] value]); add: (#sourceCode->'[:in :out | out add: {#objects -> in}, [{
	#bounds -> (1@484 corner: 496@554).
	#current -> #''3287c263-0d1a-e846-bf34-db0b5784a8f6''.
	#id -> #''07957917-91c1-5742-9bcf-8067e699de3b''.
	#out -> #().
	#in -> #(#(#interactive #''8abaf74e-bf8e-d74a-9903-f078692babb2'' ) ).
}] value]'); yourself)