definitions
def7500e5a099664645a6e451a9ac020852
	<definition>

	^ ((Dictionary new) add: (#inputKind->RBRefactoring); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'6 June 2014 4:16:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'7500e5a0-9966-4645-a6e4-51a9ac020852'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:refactoring | refactoring changes changes]'); add: (#mapType->#each); add: (#block->[:refactoring | refactoring changes changes]); yourself)