definitions
def7bf109e4f6d27c4da0840e72ff4d8753
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'3 January 2014 3:39:51 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Boolean); add: (#id->#'7bf109e4-f6d2-7c4d-a084-0e72ff4d8753'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:e1 :e2 | e1 isDirectory or: [e2 isDirectory not]]'); add: (#mapType->#twoArgs); add: (#block->[:e1 :e2 | e1 isDirectory or: [e2 isDirectory not]]); yourself)