definitions
def76130d1c37343d46a44e7310846af40e
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'17 January 2014 3:23:10 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'76130d1c-3734-3d46-a44e-7310846af40e'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:cls | ViToolSet linesOfCodeForClassWithoutExtensions: cls]'); add: (#mapType->#each); add: (#block->[:cls | ViToolSet linesOfCodeForClassWithoutExtensions: cls]); yourself)