definitions
def72afa9e57d79104b97b0accfde7204b7
	<definition>

	^ ((Dictionary new) add: (#inputKind->DirectoryEntryDirectory); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'72afa9e5-7d79-104b-97b0-accfde7204b7'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:entries | entries gather: [:entry | entry asFileDirectory entries]]'); add: (#mapType->#all); add: (#block->[:entries | entries gather: [:entry | entry asFileDirectory entries]]); yourself)