definitions
def7057516cb98eea4a8d54c4c3a0f4ab33
	<definition>

	^ ((Dictionary new) add: (#inputKind->String); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 September 2013 3:28:44 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->ClassDescription); add: (#id->#'7057516c-b98e-ea4a-8d54-c4c3a0f4ab33'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:cat | (SystemOrganization listAtCategoryNamed: cat)
	collect: [:nm | Smalltalk at: nm]]'); add: (#mapType->#each); add: (#block->[:cat | (SystemOrganization listAtCategoryNamed: cat)
	collect: [:nm | Smalltalk at: nm]]); yourself)