definitions
def76818b85e9f0ae41a3771dbdede88b86
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'25 July 2014 4:15:33 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'76818b85-e9f0-ae41-a377-1dbdede88b86'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:method | #text -> method selector]'); add: (#mapType->#each); add: (#block->[:method | #text -> method selector]); yourself)