definitions
def718de26927aad24a9303013c573b12ba
	<definition>

	^ ((Dictionary new) add: (#inputKind->ClassDescription); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->#noSystemChangeNotifications); add: (#outputKind->Object); add: (#id->#'718de269-27aa-d24a-9303-013c573b12ba'); add: (#updateSetDefinition->#notifyClassReorganized); add: (#sourceCode->'[:classes | classes gather: [:cls |
	ViProtocol protocolsForClass: cls]]'); add: (#mapType->#all); add: (#block->[:classes | classes gather: [:cls |
	ViProtocol protocolsForClass: cls]]); yourself)