definitions
def711855da9b0f69418d5b0364dc0475b6
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'21 September 2014 9:17:19 am'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'711855da-9b0f-6941-8d5b-0364dc0475b6'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:o :n | n]'); add: (#mapType->#each); add: (#block->[:o :n | n]); yourself)