definitions
def76166f6fe315444d8b1603ecadf46fc8
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'20 September 2014 12:08:38 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'76166f6f-e315-444d-8b16-03ecadf46fc8'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:o :n |
	#text -> o]'); add: (#mapType->#each); add: (#block->[:o :n |
	#text -> o]); yourself)