definitions
def740c7d8f097a4043b903fe5818cbf7b7
	<definition>

	^ ((Dictionary new) add: (#inputKind->DirectoryEntry); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->DirectoryEntryDirectory); add: (#id->#'740c7d8f-097a-4043-b903-fe5818cbf7b7'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:entries | entries select: [:entry | entry isDirectory]].'); add: (#mapType->#all); add: (#block->[:entries | entries select: [:entry | entry isDirectory]]); yourself)