definitions
def74d42c6dfa57e44c958dda199a3de398
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'20 February 2014 6:23 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'74d42c6d-fa57-e44c-958d-da199a3de398'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:tag | #text -> (ViObjectOriginService doObject: tag value)]'); add: (#mapType->#each); add: (#block->[:tag | #text -> (ViObjectOriginService doObject: tag value)]); yourself)