definitions
def7c23c01a65fd544babea397579ad97af
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'25 July 2014 6:32:28 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'7c23c01a-65fd-544b-abea-397579ad97af'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:method | #text -> method selector]'); add: (#mapType->#each); add: (#block->[:method | #text -> method selector]); yourself)