definitions
def716cce77e262584da8b0c71abe88be2e
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'23 May 2014 11:01:22 am'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'716cce77-e262-584d-a8b0-c71abe88be2e'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:hit1 :hit2 | (hit1 at: ''@score'') asInteger >= (hit2 at: ''@score'') asInteger]'); add: (#mapType->#twoArgs); add: (#block->[:hit1 :hit2 | (hit1 at: '@score') asInteger >= (hit2 at: '@score') asInteger]); yourself)