definitions
def7f7384b34b62aa46b5d5b91053a66277
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'7f7384b3-4b62-aa46-b5d5-b91053a66277'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:key :context | context contents first at: key]'); add: (#mapType->#each); add: (#block->[:key :context | context contents first at: key]); yourself)