definitions
def80db6f1ad17b8c4ea2b935243e24ef05
	<definition>

	^ ((Dictionary new) add: (#class->ViQuerySnippetDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'5 February 2014 4:37:11 pm'); yourself)); add: (#id->#'80db6f1a-d17b-8c4e-a2b9-35243e24ef05'); add: (#inputKind->UndefinedObject); add: (#block->nil); add: (#sourceCode->'Morph new openInHand.'); add: (#receiverIsCollection->false); yourself)