definitions
def8739979f8b09c347b65a39e7e63faa3a
	<definition>

	^ ((Dictionary new) add: (#class->ViQuerySnippetDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'7 February 2014 2:31:40 pm'); yourself)); add: (#id->#'8739979f-8b09-c347-b65a-39e7e63faa3a'); add: (#inputKind->Process); add: (#block->nil); add: (#sourceCode->'self stepToHome: self suspendedContext.
self stepToSendOrReturn.'); add: (#receiverIsCollection->false); yourself)