definitions
def8c0498e4ef4a7d409aa59449da21d72b
	<definition>

	^ ((Dictionary new) add: (#inputKind->ClassDescription); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 February 2014 4:28:07 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Association); add: (#id->#'8c0498e4-ef4a-7d40-9aa5-9449da21d72b'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:class | {
	ClassOrganizer allCategory -> class},
	(class organization categories collect: [:category | category -> class])]'); add: (#mapType->#each); add: (#block->[:class | {
	ClassOrganizer allCategory -> class},
	(class organization categories collect: [:category | category -> class])]); yourself)