definitions
def8f0021f92ab14144b627335dfe0f2977
	<definition>

	^ ((Dictionary new) add: (#inputKind->Behavior); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 February 2014 12:40:04 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Behavior); add: (#id->#'8f0021f9-2ab1-4144-b627-335dfe0f2977'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:classes :offset | offset contents: (classes ifEmpty: [0] ifNotEmpty: [:o | o first allSuperclasses size]). classes]'); add: (#mapType->#all); add: (#block->[:classes :offset | offset contents: (classes ifEmpty: [0] ifNotEmpty: [:o | o first allSuperclasses size]). classes]); yourself)