definitions
def8bab16cf82084b43abb2ab6ad8964984
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'8bab16cf-8208-4b43-abb2-ab6ad8964984'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:ref | {
	#text -> (ref isSymbol ifTrue: [''''] ifFalse: [ViObjectOriginService doObject: ref])}]'); add: (#mapType->#each); add: (#block->[:ref | {
	#text -> (ref isSymbol ifTrue: [''] ifFalse: [ViObjectOriginService doObject: ref])}]); yourself)