definitions
def86ecc589bfac754a92b469704fa9b84b
	<definition>

	^ ((Dictionary new) add: (#inputKind->ByteSymbol); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 September 2013 7:12:18 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->ByteSymbol); add: (#id->#'86ecc589-bfac-754a-92b4-69704fa9b84b'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:selectors | SystemNavigation allUnSentMessagesIn: selectors]'); add: (#mapType->#all); add: (#block->[:selectors | SystemNavigation allUnSentMessagesIn: selectors]); yourself)