definitions
def89be979727105844ab5eb2bdd7f82581
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'89be9797-2710-5844-ab5e-b2bdd7f82581'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:project | #text -> (project label allButFirst: 15)]'); add: (#mapType->#each); add: (#block->[:project | #text -> (project label allButFirst: 15)]); yourself)