definitions
def85bc20f14a8e54408c069b7261827cb1
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Boolean); add: (#id->#'85bc20f1-4a8e-5440-8c06-9b7261827cb1'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:cls1 :cls2 | cls2 inheritsFrom: cls1]'); add: (#mapType->#twoArgs); add: (#block->[:cls1 :cls2 | cls2 inheritsFrom: cls1]); yourself)