definitions
def8af1f58613a1974baa820f88b776ed11
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'25 July 2014 4:29:23 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'8af1f586-13a1-974b-aa82-0f88b776ed11'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:layer |
	{#text -> ''Deactivate''.
	#clicked -> [[layer layerName deactivateLayerInCurrentProcess]]}].'); add: (#mapType->#each); add: (#block->[:layer |
	{#text -> 'Deactivate'.
	#clicked -> [[layer layerName deactivateLayerInCurrentProcess]]}]); yourself)