definitions
def9242cbac47978d4c9f3f8d8dc15a9b9e
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'12 November 2013 4:58:54 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'9242cbac-4797-8d4c-9f3f-8d8dc15a9b9e'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:process | #text -> process priority]'); add: (#mapType->#each); add: (#block->[:process | #text -> process priority]); yourself)