definitions
def9ff9a38b16384e4780a78390c89b325b
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'9ff9a38b-1638-4e47-80a7-8390c89b325b'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:protocol | protocol containingPackage
	ifNil: [''(no package)'']
	ifNotNil: [:pkg | pkg name]]'); add: (#mapType->#each); add: (#block->[:protocol | protocol containingPackage
	ifNil: ['(no package)']
	ifNotNil: [:pkg | pkg name]]); yourself)