definitions
def9a9c508c1e4ee34d8c19fd40ba02b9f0
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'25 July 2014 2:20:46 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'9a9c508c-1e4e-e34d-8c19-fd40ba02b9f0'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:layer |
	{#text -> ''Deactivate''.
	#clicked -> [[layer layerName deactivateLayerInCurrentProcess]]}].'); add: (#mapType->#each); add: (#block->[:layer |
	{#text -> 'Deactivate'.
	#clicked -> [[layer layerName deactivateLayerInCurrentProcess]]}]); yourself)