definitions
def9c7d2184d97f0a4fa361192c038a7b1c
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'9c7d2184-d97f-0a4f-a361-192c038a7b1c'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[Smalltalk classNames
	select: [:nm | nm beginsWith: #ConfigurationOf]
	thenCollect: [:nm | (Smalltalk at: nm) project]]'); add: (#mapType->#all); add: (#block->[Smalltalk classNames
	select: [:nm | nm beginsWith: #ConfigurationOf]
	thenCollect: [:nm | (Smalltalk at: nm) project]]); yourself)