definitions
def9d46436cf164ed49bd02da3fa8e10342
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryUpdateDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'23 May 2014 12:00:21 pm'); yourself)); add: (#id->#'9d46436c-f164-ed49-bd02-da3fa8e10342'); add: (#block->[:model | (ViTimer named: #activeLayers) every: 500 send: #refresh to: model]); add: (#sourceCode->'[:model | (ViTimer named: #activeLayers) every: 500 send: #refresh to: model]'); yourself)