definitions
def93525b3f5fdebb4cad941c2c3a53fd53
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'3 September 2013 3:29:42 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'93525b3f-5fde-bb4c-ad94-1c2c3a53fd53'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:step | #text -> (step baseClassName asText
	addAttribute: (TextColor color: (Color fromString: #AAAAAA));
	yourself)]'); add: (#mapType->#each); add: (#block->[:step | #text -> (step baseClassName asText
	addAttribute: (TextColor color: (Color fromString: #AAAAAA));
	yourself)]); yourself)