definitions
def989bcdd3fbbafd4e8afaefcbe811f73d
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'30 August 2014 2:16:08 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'989bcdd3-fbba-fd4e-8afa-efcbe811f73d'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:o | o]'); add: (#mapType->#each); add: (#block->[:o | o]); yourself)