definitions
def9df8dcd1de88bd498862d5cdef8b0e79
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'24 August 2014 12:35:21 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'9df8dcd1-de88-bd49-8862-d5cdef8b0e79'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:o | o]'); add: (#mapType->#each); add: (#block->[:o | o]); yourself)