definitions
def9b0b0af62af29d44a8d0acb6157978ac
	<definition>

	^ ((Dictionary new) add: (#inputKind->CompiledMethod); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'24 February 2014 10:52:06 am'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'9b0b0af6-2af2-9d44-a8d0-acb6157978ac'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:method | #text -> (method decompileWithTemps decompileString asText makeSelectorBoldIn: method methodClass)]'); add: (#mapType->#each); add: (#block->[:method | #text -> (method decompileWithTemps decompileString asText makeSelectorBoldIn: method methodClass)]); yourself)