definitions
defa8e1f6d259e50b4e8254e152fcc315d7
	<definition>

	^ ((Dictionary new) add: (#inputKind->CompiledMethod); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'21 July 2014 10:35:46 am'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->STestReference); add: (#id->#'a8e1f6d2-59e5-0b4e-8254-e152fcc315d7'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:method | STestReference class: method methodClass selector: method selector]'); add: (#mapType->#each); add: (#block->[:method | STestReference class: method methodClass selector: method selector]); yourself)