definitions
defa1bf1391ab8a9a43bbe0f9ecf7d38994
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryUpdateDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 September 2013 6:19:02 pm'); yourself)); add: (#id->#'a1bf1391-ab8a-9a43-bbe0-f9ecf7d38994'); add: (#block->[:model | ViObjectHistory transcriptHistory disconnectSignal: #objectAdded: from: model selector: #refresh]); add: (#sourceCode->'[:model | ViObjectHistory transcriptHistory disconnectSignal: #objectAdded: from: model selector: #refresh]'); yourself)