definitions
defa502b2c49d6d2249823d854142f6e94a
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'24 August 2014 2:07 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'a502b2c4-9d6d-2249-823d-854142f6e94a'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:node | node children]'); add: (#mapType->#each); add: (#block->[:node | node children]); yourself)