definitions
defaf231d3ed1f89640bb55df10e7c0a213
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'25 July 2014 5:58:49 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'af231d3e-d1f8-9640-bb55-df10e7c0a213'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:layer | (CSLayer layerNamed: layer) allContainingPartialMethods]'); add: (#mapType->#each); add: (#block->[:layer | (CSLayer layerNamed: layer) allContainingPartialMethods]); yourself)