definitions
defa9634057f4f92540b4941d7666d20238
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'7 August 2014 5:16:35 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'a9634057-f4f9-2540-b494-1d7666d20238'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:package | package classesAndMetaClassses]'); add: (#mapType->#each); add: (#block->[:package | package classesAndMetaClassses]); yourself)