definitions
defafd994289871f545aeccaf8140ef7bec
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#copyOf->#'c7223154-d83c-2f4a-916a-f0bfd27be3bd'); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'12 May 2015 4:36:46 pm'); yourself)); add: (#id->#'afd99428-9871-f545-aecc-af8140ef7bec'); add: (#block->[:in :out | out addAll: ([:groups | groups
		sorted: [:g1 :g2 | g1 first asString <= g2 first asString]] value: in)]); add: (#sourceCode->'[:in :out | out addAll: ([:groups | groups
		sorted: [:g1 :g2 | g1 first asString <= g2 first asString]] value: in)]'); yourself)