definitions
defa60ddb4943c2aa4cbe446d3ad8626714
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'25 July 2014 6:30:18 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'a60ddb49-43c2-aa4c-be44-6d3ad8626714'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[PackageOrganizer default packageOfClass: BoBreakout]'); add: (#mapType->#all); add: (#block->[PackageOrganizer default packageOfClass: BoBreakout]); yourself)