definitions
defa720f19ae820a542ae4a0cf5bd44b149
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'25 July 2014 5:58:27 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'a720f19a-e820-a542-ae4a-0cf5bd44b149'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:layer | #text -> layer]'); add: (#mapType->#each); add: (#block->[:layer | #text -> layer]); yourself)