definitions
defa5322375d829bb409181f4ce0b5ec1fd
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'a5322375-d829-bb40-9181-f4ce0b5ec1fd'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | {#text -> (ViLabelService doObject: obj key). #icon -> (ViIconService doObject: obj key)}]'); add: (#mapType->#each); add: (#block->[:obj | {#text -> (ViLabelService doObject: obj key). #icon -> (ViIconService doObject: obj key)}]); yourself)