definitions
defacc7835d73e61c4580c04dcbfc225273
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryUpdateDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'16 November 2013 5:18:43 pm'); yourself)); add: (#id->#'acc7835d-73e6-1c45-80c0-4dcbfc225273'); add: (#block->[:model | ViObjectHistory lastExceptions disconnectSignal: #objectAdded: from: model selector: #refresh]); add: (#sourceCode->'[:model | ViObjectHistory lastExceptions disconnectSignal: #objectAdded: from: model selector: #refresh]'); yourself)