definitions
defaf245767eb73ed4a8a6bdb06d7369d6a
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'25 August 2014 3:03:24 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'af245767-eb73-ed4a-8a6b-db06d7369d6a'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:o | o]'); add: (#mapType->#each); add: (#block->[:o | o]); yourself)