definitions
defaf7194c47ad5134ba040368387dd4009
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'6 September 2013 9:08:35 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'af7194c4-7ad5-134b-a040-368387dd4009'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:def | #icon -> (def updateSetDefinition
	ifNil: [UiFugueIcons crossSmallIcon]
	ifNotNil: [UiFugueIcons tickSmallIcon])]'); add: (#mapType->#each); add: (#block->[:def | #icon -> (def updateSetDefinition
	ifNil: [UiFugueIcons crossSmallIcon]
	ifNotNil: [UiFugueIcons tickSmallIcon])]); yourself)