definitions
defaa928fd148f4084c878b5dd4ad186dbf
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'23 May 2014 11:10:45 am'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'aa928fd1-48f4-084c-878b-5dd4ad186dbf'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:hit | #text -> (((hit at: #info) at: #venue) at: ''@journal'' ifAbsent: [''-''])]'); add: (#mapType->#each); add: (#block->[:hit | #text -> (((hit at: #info) at: #venue) at: '@journal' ifAbsent: ['-'])]); yourself)