definitions
defa6effdc4d6cac64ca7e411dd4cfc4625
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 February 2014 4:26:16 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'a6effdc4-d6ca-c64c-a7e4-11dd4cfc4625'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:assoc | (assoc value listAtCategoryNamed: assoc key)
	collect: [:nm | Smalltalk at: nm]]'); add: (#mapType->#each); add: (#block->[:assoc | (assoc value listAtCategoryNamed: assoc key)
	collect: [:nm | Smalltalk at: nm]]); yourself)