definitions
defb333ec1c585c2243b6904161607177bf
	<definition>

	^ ((Dictionary new) add: (#inputKind->ViQueryStepDefinition); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'6 September 2013 8:27:31 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->ViQueryViewDefinition); add: (#id->#'b333ec1c-585c-2243-b690-4161607177bf'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:definitions | definitions select: [:def | def isViewDefinition]]'); add: (#mapType->#all); add: (#block->[:definitions | definitions select: [:def | def isViewDefinition]]); yourself)