definitions
defb9f6a5ee172baa4fa1445f4846fd338d
	<definition>

	^ ((Dictionary new) add: (#inputKind->((Array new: 2) at: 1 put: Text; at: 2 put: CompiledMethod; yourself)); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'24 August 2014 1:44:34 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->((Array new: 2) at: 1 put: String; at: 2 put: CompiledMethod; yourself)); add: (#id->#'b9f6a5ee-172b-aa4f-a144-5f4846fd338d'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:text :method | {text asString. method}]'); add: (#mapType->#each); add: (#block->[:text :method | {text asString. method}]); yourself)