definitions
defb0109de9e34d834d871902ff7b7f2d66
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'25 July 2014 6:32:42 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'b0109de9-e34d-834d-8719-02ff7b7f2d66'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:method | #text -> method methodClass name]'); add: (#mapType->#each); add: (#block->[:method | #text -> method methodClass name]); yourself)