definitions
defb80a7bcf1a9b764491b8e86a4767d667
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'20 September 2014 12:06:45 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'b80a7bcf-1a9b-7644-91b8-e86a4767d667'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[#(a a b b c c)]'); add: (#mapType->#all); add: (#block->[#(a a b b c c)]); yourself)