definitions
defbec809e3f45af243afd97ee00ef209ae
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'25 July 2014 6:01:12 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'bec809e3-f45a-f243-afd9-7ee00ef209ae'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:method | #text -> method methodClass name]'); add: (#mapType->#each); add: (#block->[:method | #text -> method methodClass name]); yourself)