definitions
defba88ab3404fa7e4086c0293a59f0c1a6
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'25 July 2014 6:37:14 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'ba88ab34-04fa-7e40-86c0-293a59f0c1a6'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:layer | {
	#text -> ''Deactivate''.
	#clicked -> [[layer deactivateLayerInCurrentProcess]]}]'); add: (#mapType->#each); add: (#block->[:layer | {
	#text -> 'Deactivate'.
	#clicked -> [[layer deactivateLayerInCurrentProcess]]}]); yourself)