definitions
defbdac2fd55d6d8944917974eb2b720a88
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 November 2013 8:47:26 am'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'bdac2fd5-5d6d-8944-9179-74eb2b720a88'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:stamp | stamp value lastStep]'); add: (#mapType->#each); add: (#block->[:stamp | stamp value lastStep]); yourself)