definitions
defb9f8c25a20b95146a00ed518fa163d93
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'b9f8c25a-20b9-5146-a00e-d518fa163d93'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:ref | #text -> (ref isSymbol ifTrue: [''''] ifFalse: [ref category])]'); add: (#mapType->#each); add: (#block->[:ref | #text -> (ref isSymbol ifTrue: [''] ifFalse: [ref category])]); yourself)