definitions
defb0fe6ff5386f3c49b42dd2f2c7c96a1a
	<definition>

	^ ((Dictionary new) add: (#inputKind->ViQueryOrganizer); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'5 October 2013 5:06:48 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Bag); add: (#id->#'b0fe6ff5-386f-3c49-b42d-d2f2c7c96a1a'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:organizer | organizer useFrequencyForDefinitions]'); add: (#mapType->#each); add: (#block->[:organizer | organizer useFrequencyForDefinitions]); yourself)