definitions
defbef8011eaa73284e98b380cfaa34869d
	<definition>

	^ ((Dictionary new) add: (#class->ViQuerySnippetDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 May 2014 1:12:25 pm'); yourself)); add: (#id->#'bef8011e-aa73-284e-98b3-80cfaa34869d'); add: (#inputKind->CSLayer); add: (#block->nil); add: (#sourceCode->'self layerName deactivateLayerInCurrentProcess.'); add: (#receiverIsCollection->false); yourself)