definitions
defbe02a17dcc981640ae53b8838236dad5
	<definition>

	^ ((Dictionary new) add: (#inputKind->PackageInfo); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'2 June 2014 3:49:58 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->ClassDescription); add: (#id->#'be02a17d-cc98-1640-ae53-b8838236dad5'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:package | package classes]'); add: (#mapType->#each); add: (#block->[:package | package classes]); yourself)