definitions
defbcbc9f733ca40d4e9933e2a6d2ea32e4
	<definition>

	^ ((Dictionary new) add: (#inputKind->ViQueryStepDefinition); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'4 September 2013 12:59:07 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->ViQueryStepDefinition); add: (#id->#'bcbc9f73-3ca4-0d4e-9933-e2a6d2ea32e4'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:definition | definition organization codeDefinitions
	select: [:def | def mapType == definition mapType]]'); add: (#mapType->#each); add: (#block->[:definition | definition organization codeDefinitions
	select: [:def | def mapType == definition mapType]]); yourself)