definitions
defbfe36700f08a1845b1d3c30eccf37a29
	<definition>

	^ ((Dictionary new) add: (#inputKind->PackageInfo); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'20 September 2013 4:54:16 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'bfe36700-f08a-1845-b1d3-c30eccf37a29'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:pkg | pkg systemCategories]'); add: (#mapType->#each); add: (#block->[:pkg | pkg systemCategories]); yourself)