definitions
defb5c1ed0e8dab2647a457d97b0b697e26
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'25 July 2014 3:54:38 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'b5c1ed0e-8dab-2647-a457-d97b0b697e26'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:pm | #text -> pm layers]'); add: (#mapType->#each); add: (#block->[:pm | #text -> pm layers]); yourself)