definitions
defb08835ac24fe3b4387cbceb4b81fc6fb
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Boolean); add: (#id->#'b08835ac-24fe-3b43-87cb-ceb4b81fc6fb'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj1 :obj2 | obj1 reference selector <= obj2 reference selector asString]'); add: (#mapType->#twoArgs); add: (#block->[:obj1 :obj2 | obj1 reference selector <= obj2 reference selector asString]); yourself)