definitions
defbce4e3b8edbacb48a82d0dfa730e08d5
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'25 July 2014 4:10:45 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'bce4e3b8-edba-cb48-a82d-0dfa730e08d5'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:layer | #text -> layer]'); add: (#mapType->#each); add: (#block->[:layer | #text -> layer]); yourself)