definitions
defb9a69dcc68393a4aa9c3adae96c6c0e4
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Boolean); add: (#id->#'b9a69dcc-6839-3a4a-a9c3-adae96c6c0e4'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj1 :obj2 | (ViMethodVersion relativeDateLabels indexOf: obj1) <= (ViMethodVersion relativeDateLabels indexOf: obj2)]'); add: (#mapType->#twoArgs); add: (#block->[:obj1 :obj2 | (ViMethodVersion relativeDateLabels indexOf: obj1) <= (ViMethodVersion relativeDateLabels indexOf: obj2)]); yourself)