definitions
defc5c5e6af5c6873468f742b8ce9d21204
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'c5c5e6af-5c68-7346-8f74-2b8ce9d21204'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:entry | entry creationDateAndTime asDate asString]'); add: (#mapType->#each); add: (#block->[:entry | entry creationDateAndTime asDate asString]); yourself)