definitions
defc70a89eb72fb1846be69841c75c0a435
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'2 March 2014 10:06:15 am'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'c70a89eb-72fb-1846-be69-841c75c0a435'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:morph | #text -> morph class name]'); add: (#mapType->#each); add: (#block->[:morph | #text -> morph class name]); yourself)