definitions
defcc1b19c6a4552b4da44be8f7feb150f9
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'25 July 2014 5:57:54 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'cc1b19c6-a455-2b4d-a44b-e8f7feb150f9'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:layers | layers asSet asArray]'); add: (#mapType->#all); add: (#block->[:layers | layers asSet asArray]); yourself)