definitions
defc25e78681c1a4647ab325182e547450a
	<definition>

	^ ((Dictionary new) add: (#inputKind->ChangeSet); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'5 June 2014 4:56:12 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'c25e7868-1c1a-4647-ab32-5182e547450a'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:cs | cs methodChanges associations]'); add: (#mapType->#each); add: (#block->[:cs | cs methodChanges associations]); yourself)