definitions
defcf62d1d09733004b9b8712ea60dc9569
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'25 July 2014 6:31:47 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'cf62d1d0-9733-004b-9b87-12ea60dc9569'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:layer | (CSLayer layerNamed: layer) allContainingPartialMethods]'); add: (#mapType->#each); add: (#block->[:layer | (CSLayer layerNamed: layer) allContainingPartialMethods]); yourself)