definitions
defc3d14c3079e47e49976d60b6548c297e
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'20 May 2014 11:59:48 am'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'c3d14c30-79e4-7e49-976d-60b6548c297e'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[Vivide editorStates]'); add: (#mapType->#all); add: (#block->[Vivide editorStates]); yourself)