definitions
defc5e79a5514299047b9169f616017f84a
	<definition>

	^ ((Dictionary new) add: (#inputKind->ClassDescription); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'17 January 2014 2:55:42 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'c5e79a55-1429-9047-b916-9f616017f84a'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:cls | cls methodDict values, cls class methodDict values]'); add: (#mapType->#each); add: (#block->[:cls | cls methodDict values, cls class methodDict values]); yourself)