definitions
defce888f557ca58b44b64995ab16e5edfc
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'3 September 2013 3:35:47 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'ce888f55-7ca5-8b44-b649-95ab16e5edfc'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:objs | objs select: [:step | step nextLabel notNil]]'); add: (#mapType->#all); add: (#block->[:objs | objs select: [:step | step nextLabel notNil]]); yourself)