definitions
defc9ef82bddb12d446a43f558a04f98be2
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#copyOf->#'1c6c47fd-f9bb-084a-9266-60bc0c3608bf'); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'15 June 2015 10:20:57 am'); yourself)); add: (#id->#'c9ef82bd-db12-d446-a43f-558a04f98be2'); add: (#block->[:in :out | out addAll: ([:tuples | tuples] value: in)]); add: (#sourceCode->'[:in :out | out addAll: ([:tuples | tuples] value: in)]'); yourself)