definitions
defcc64cee2709eca4cbf27654f86ee2d52
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'30 August 2014 2:14:15 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'cc64cee2-709e-ca4c-bf27-654f86ee2d52'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[]'); add: (#mapType->#all); add: (#block->[]); yourself)