definitions
defc035c6a1305ee04a80d7cdfd6931f68b
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'25 July 2014 5:52:20 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'c035c6a1-305e-e04a-80d7-cdfd6931f68b'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:class | #text -> class name]'); add: (#mapType->#each); add: (#block->[:class | #text -> class name]); yourself)