definitions
defcdd17af089f3f94dbf9a6610214e4bcd
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'25 July 2014 5:52:05 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'cdd17af0-89f3-f94d-bf9a-6610214e4bcd'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:pkg | pkg classes]'); add: (#mapType->#each); add: (#block->[:pkg | pkg classes]); yourself)