definitions
defce6afbe5bac68d438242117271d13401
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 September 2013 5:36:31 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'ce6afbe5-bac6-8d43-8242-117271d13401'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | obj at: #email]'); add: (#mapType->#each); add: (#block->[:obj | obj at: #email]); yourself)