definitions
defcd024c1f6fc84948812e87c1459e9d96
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'16 October 2014 4:30:55 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'cd024c1f-6fc8-4948-812e-87c1459e9d96'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:objects | #self -> objects]'); add: (#mapType->#each); add: (#block->[:objects | #self -> objects]); yourself)