definitions
defce710d02e55be74885cf67baa093cd49
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 February 2014 11:25:12 am'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Behavior); add: (#id->#'ce710d02-e55b-e748-85cf-67baa093cd49'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[TestCase]'); add: (#mapType->#all); add: (#block->[TestCase]); yourself)