definitions
defc3ea1545f452484c8c978118ee648839
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Boolean); add: (#id->#'c3ea1545-f452-484c-8c97-8118ee648839'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj1 :obj2 | obj1 compiledMethod linesOfCode
	>= obj2 compiledMethod linesOfCode]'); add: (#mapType->#twoArgs); add: (#block->[:obj1 :obj2 | obj1 compiledMethod linesOfCode
	>= obj2 compiledMethod linesOfCode]); yourself)