definitions
defd758d84fb788554e8a419ab488564dc4
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'25 July 2014 6:31:27 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'d758d84f-b788-554e-8a41-9ab488564dc4'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:layers | layers asSet asArray]'); add: (#mapType->#all); add: (#block->[:layers | layers asSet asArray]); yourself)