definitions
defdcdcf6c99bcf2a4abb179e1b2af3cfe7
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'25 July 2014 4:26:04 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'dcdcf6c9-9bcf-2a4a-bb17-9e1b2af3cfe7'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:layer |
	{#text -> ''Activate''.
	#clicked -> [[layer layerName activateLayerInCurrentProcess]]}].'); add: (#mapType->#each); add: (#block->[:layer |
	{#text -> 'Activate'.
	#clicked -> [[layer layerName activateLayerInCurrentProcess]]}]); yourself)