definitions
defd90a894f095c5c43ac7b5c0f959c349c
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 July 2014 2:12:59 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'d90a894f-095c-5c43-ac7b-5c0f959c349c'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[ActiveWorld submorphs]'); add: (#mapType->#all); add: (#block->[ActiveWorld submorphs]); yourself)