definitions
defdf4edb8323fedc47a52e67c69926d29a
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'12 November 2013 4:48:45 pm'); yourself)); add: (#updateClearDefinition->#'2ed39360-2ab3-6649-a7e6-e69fbd93007d'); add: (#outputKind->Object); add: (#id->#'df4edb83-23fe-dc47-a52e-67c69926d29a'); add: (#updateSetDefinition->#'8b1d3ca6-cd15-5d44-b329-87bbaf5dd3c7'); add: (#sourceCode->'[(((Processor instVarNamed: #quiescentProcessLists)
	gather: [:ll | ll asOrderedCollection])
	copyWith: Processor activeProcess)]'); add: (#mapType->#all); add: (#block->[(((Processor instVarNamed: #quiescentProcessLists)
	gather: [:ll | ll asOrderedCollection])
	copyWith: Processor activeProcess)]); yourself)