definitions
defda22d385455e8b43aa55c0c3094b1ca7
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'14 February 2014 9:31:36 am'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'da22d385-455e-8b43-aa55-c0c3094b1ca7'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:line | #text -> line value]'); add: (#mapType->#each); add: (#block->[:line | #text -> line value]); yourself)