definitions
defd2b5ee0ffa430d4cae8565dd381015bc
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'25 July 2014 6:26:21 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'d2b5ee0f-fa43-0d4c-ae85-65dd381015bc'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:pkg | pkg classes]'); add: (#mapType->#each); add: (#block->[:pkg | pkg classes]); yourself)