definitions
defdd79ea8cb89aa347a5efc47e4d255871
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'25 July 2014 4:09:48 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'dd79ea8c-b89a-a347-a5ef-c47e4d255871'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:ref | ref method layers]'); add: (#mapType->#each); add: (#block->[:ref | ref method layers]); yourself)