definitions
defd579b1f644668842b908ef4dcc51f0ad
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'23 July 2014 2:44:48 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'d579b1f6-4466-8842-b908-ef4dcc51f0ad'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:step | #text -> step id]'); add: (#mapType->#each); add: (#block->[:step | #text -> step id]); yourself)