definitions
defd0d48ca25848de409dec499bcb0ef520
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'11 February 2014 1:47:30 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'d0d48ca2-5848-de40-9dec-499bcb0ef520'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:pkg | #morph -> (Morph new color: Color green muchDarker; extent: (pkg linesOfCode // 100) @ 10)]'); add: (#mapType->#each); add: (#block->[:pkg | #morph -> (Morph new color: Color green muchDarker; extent: (pkg linesOfCode // 100) @ 10)]); yourself)