definitions
defda5a4e6cd7423945ba5cb1e6625d0dcf
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryUpdateDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'23 May 2014 12:00:21 pm'); yourself)); add: (#id->#'da5a4e6c-d742-3945-ba5c-b1e6625d0dcf'); add: (#block->[:model | (ViTimer named: #activeLayers) delete]); add: (#sourceCode->'[:model | (ViTimer named: #activeLayers) delete]'); yourself)