definitions
defed9f3ef77d17c541b7cf2821cca31d6b
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationTimeStamp->'18 September 2013 9:36:30 pm'); add: (#creationAuthor->'mt'); add: (#labelColor->'007F00'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'ed9f3ef7-7d17-c541-b7cf-2821cca31d6b'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:flag | flag comment]'); add: (#mapType->#each); add: (#block->[:flag | flag comment]); yourself)