definitions
defef138ae341722d4982254cc0e676959b
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'25 July 2014 6:08:35 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'ef138ae3-4172-2d49-8225-4cc0e676959b'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:layer | {
	#text -> ''Deactivate''.
	#clicked -> [[layer deactivateLayerInCurrentProcess]]}]'); add: (#mapType->#each); add: (#block->[:layer | {
	#text -> 'Deactivate'.
	#clicked -> [[layer deactivateLayerInCurrentProcess]]}]); yourself)