definitions
defe41f5f5bca8c09469f029a0f2dc0269e
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 4:21:57 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'e41f5f5b-ca8c-0946-9f02-9a0f2dc0269e'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:objects :context | objects select: [:obj | obj third notNil]].'); add: (#mapType->#all); add: (#block->[:objects :context | objects select: [:obj | obj third notNil]]); yourself)