definitions
defebcac69e2cc2de4eaa3c0ca991911cc4
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'24 August 2014 2:06:08 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'ebcac69e-2cc2-de4e-aa3c-0ca991911cc4'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:node | #text -> (ViObjectOriginService doObject: node clientMethod)]'); add: (#mapType->#each); add: (#block->[:node | #text -> (ViObjectOriginService doObject: node clientMethod)]); yourself)