definitions
defe06097d21a384845ae0ed68113bd2be5
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'20 October 2014 7:29:40 am'); yourself)); add: (#id->#'e06097d2-1a38-4845-ae0e-d68113bd2be5'); add: (#block->[:in :out | in do: [:obj | (out includes: obj) ifFalse: [out add: obj]]]); add: (#sourceCode->'[:in :out | in do: [:obj | (out includes: obj) ifFalse: [out add: obj]]]'); yourself)