definitions
defe897d6965b3af44ba096aee9e1b612cf
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'25 July 2014 6:04:35 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'e897d696-5b3a-f44b-a096-aee9e1b612cf'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:layer | #text -> layer]'); add: (#mapType->#each); add: (#block->[:layer | #text -> layer]); yourself)