definitions
defef07cc37d75caa4cbac087ad92606d23
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'ef07cc37-d75c-aa4c-bac0-87ad92606d23'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:assoc | assoc value]'); add: (#mapType->#each); add: (#block->[:assoc | assoc value]); yourself)