definitions
defefde47c0b44a7b499f37ea3243404447
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 September 2013 6:49:23 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'efde47c0-b44a-7b49-9f37-ea3243404447'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:flag | flag reference actualClass category]'); add: (#mapType->#each); add: (#block->[:flag | flag reference actualClass category]); yourself)