definitions
defef17b0c33ef9274e86d1cf657d2f721b
	<definition>

	^ ((Dictionary new) add: (#inputKind->ViQueryStepDefinition); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'6 September 2013 8:27:31 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->ViQueryUpdateDefinition); add: (#id->#'ef17b0c3-3ef9-274e-86d1-cf657d2f721b'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:definitions | definitions select: [:def | def isUpdateDefinition]]'); add: (#mapType->#all); add: (#block->[:definitions | definitions select: [:def | def isUpdateDefinition]]); yourself)