definitions
defeaacc8b24e11bb4cab2b7aa0583b7467
	<definition>

	^ ((Dictionary new) add: (#inputKind->ViQueryOrganizer); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'6 September 2013 8:27:11 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->ViQueryStepDefinition); add: (#id->#'eaacc8b2-4e11-bb4c-ab2b-7aa0583b7467'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:organizer | organizer orderedDefinitions]'); add: (#mapType->#each); add: (#block->[:organizer | organizer orderedDefinitions]); yourself)