definitions
deffa6a9923220aa84fa21144562dda182e
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'25 August 2014 11:05:29 am'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'fa6a9923-220a-a84f-a211-44562dda182e'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:bindings | 
	bindings isDictionary
		ifTrue: [#bindings -> bindings]
		ifFalse: [{}]]'); add: (#mapType->#each); add: (#block->[:bindings | 
	bindings isDictionary
		ifTrue: [#bindings -> bindings]
		ifFalse: [{}]]); yourself)