definitions
deffa585967f2b4bf439b5ecc34c15d0e26
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'fa585967-f2b4-bf43-9b5e-cc34c15d0e26'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:dict | dict keys sorted: [:k1 :k2 | k1 asString <= k2 asString]]'); add: (#mapType->#each); add: (#block->[:dict | dict keys sorted: [:k1 :k2 | k1 asString <= k2 asString]]); yourself)