definitions
deff1e390588fc6ea47a5166eedee86a1eb
	<definition>

	^ ((Dictionary new) add: (#inputKind->ClassDescription); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'3 October 2013 6:26:24 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'f1e39058-8fc6-ea47-a516-6eedee86a1eb'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:cls | cls withAllSuperclasses gather: [:scls |
	scls theNonMetaClass methodDict values, scls theMetaClass methodDict values]]'); add: (#mapType->#each); add: (#block->[:cls | cls withAllSuperclasses gather: [:scls |
	scls theNonMetaClass methodDict values, scls theMetaClass methodDict values]]); yourself)