definitions
deff88512ad81ddac4c8e82ff004696fed6
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'f88512ad-81dd-ac4c-8e82-ff004696fed6'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | obj symbol]'); add: (#mapType->#each); add: (#block->[:obj | obj symbol]); yourself)