definitions
deff2ed1c1c53bafb4794cd6f1a39fb69f9
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'25 July 2014 5:57:45 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'f2ed1c1c-53ba-fb47-94cd-6f1a39fb69f9'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:ref | ref method layers]'); add: (#mapType->#each); add: (#block->[:ref | ref method layers]); yourself)