definitions
deff96e87d9b6921b47a3c7e03bebbb78f1
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'f96e87d9-b692-1b47-a3c7-e03bebbb78f1'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:objects :context | objects select: [:ref | ref category = ''as yet unclassified'' or: [ref category = ''nil'']]].'); add: (#mapType->#all); add: (#block->[:objects :context | objects select: [:ref | ref category = 'as yet unclassified' or: [ref category = 'nil']]]); yourself)