definitions
deff5ed8b900396e14ab7c7a384000dcbea
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'8 November 2013 3:52:47 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->ObjectExplorerWrapper); add: (#id->#'f5ed8b90-0396-e14a-b7c7-a384000dcbea'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | (PointerExplorerWrapper with: obj) contents]'); add: (#mapType->#each); add: (#block->[:obj | (PointerExplorerWrapper with: obj) contents]); yourself)