definitions
deff09a7901d8686c4da809bd45bde16a09
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'f09a7901-d868-6c4d-a809-bd45bde16a09'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | #text -> obj info time]'); add: (#mapType->#each); add: (#block->[:obj | #text -> obj info time]); yourself)