definitions
deffe8761517d88f6459e7dc53ca687513d
	<definition>

	^ ((Dictionary new) add: (#inputKind->String); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 September 2013 3:21:01 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'fe876151-7d88-f645-9e7d-c53ca687513d'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:cat | {
	#text -> (ViLabelServiceForEclipse new doSystemCategory: cat).
	#icon -> (ViIconServiceForEclipse new doSystemCategory: cat)}]'); add: (#mapType->#each); add: (#block->[:cat | {
	#text -> (ViLabelServiceForEclipse new doSystemCategory: cat).
	#icon -> (ViIconServiceForEclipse new doSystemCategory: cat)}]); yourself)