steps
step0022b353daa6014ca24538faec14e32e
	<step>

	^ ((Dictionary new) add: (#definition->#copyToContext); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->3960); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 September 2013 3:08:26 pm'); yourself)); add: (#id->#'0022b353-daa6-014c-a245-38faec14e32e'); add: (#iconCode->'nil'); add: (#next->#'d9976b61-dc4e-bf4a-a4a6-a44c2728904d'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)