steps
stepe5bd3f6cf63fb14889bc82784354babd
	<step>

	^ ((Dictionary new) add: (#definition->#'71ff792c-38c4-3940-af3d-ef08247f2377'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->1160); add: (#headerText->'Modified'); yourself)); add: (#id->#'e5bd3f6c-f63f-b148-89bc-82784354babd'); add: (#iconCode->'nil'); add: (#next->#'57759e79-162b-7647-b6c7-af705463339b'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)