steps
step73c14db0512955439fe9dab9298595fb
	<step>

	^ ((Dictionary new) add: (#definition->#'6791d9d6-2faf-3448-8e22-0aa4c948acdc'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->5920); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#'3947aee4-5c3a-1649-8884-a37f2fcf75e9'); yourself)); add: (#id->#'73c14db0-5129-5543-9fe9-dab9298595fb'); add: (#iconCode->'nil'); add: (#next->#'97de0441-7aaf-e745-a263-7000ac4db432'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)