steps
step9d1dec9fcad6de45b2c203c8cd59b8d7
	<step>

	^ ((Dictionary new) add: (#definition->#'1155c220-eeaa-5a49-849d-1aad1424f1f6'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->3610); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#defaultProperties); yourself)); add: (#id->#'9d1dec9f-cad6-de45-b2c2-03c8cd59b8d7'); add: (#iconCode->'nil'); add: (#next->#'64c67351-149a-5b41-9de2-aa23b19628a8'); add: (#viewDefinition->#treeViewExtended); add: (#label->'Diff'); yourself)