steps
step57addd329f038e449c7146497f3e7209
	<step>

	^ ((Dictionary new) add: (#definition->#iconAndLabel); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->4930); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#defaultProperties); yourself)); add: (#id->#'57addd32-9f03-8e44-9c71-46497f3e7209'); add: (#iconCode->'nil'); add: (#next->#'736c2491-39ee-9f4c-9abc-4d4c87ef1a03'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)