steps
step432a6001f00e514ea68e4605686f7755
	<step>

	^ ((Dictionary new) add: (#definition->#iconAndLabel); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->2670); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#headerText->'Object'); yourself)); add: (#id->#'432a6001-f00e-514e-a68e-4605686f7755'); add: (#iconCode->'nil'); add: (#next->#'17c595bf-6cf3-1143-a13a-a297052fd4cc'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)