steps
step2b022238c9a7fe4b8d2bfa5c2250af5d
	<step>

	^ ((Dictionary new) add: (#definition->#'a5066753-64c1-b04f-b645-d66d41db274d'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->5520); add: (#view->#text); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 February 2014 8:38:57 am'); yourself)); add: (#id->#'2b022238-c9a7-fe4b-8d2b-fa5c2250af5d'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)