steps
step38378fb083d95243a5024e4e62e18131
	<step>

	^ ((Dictionary new) add: (#definition->#'1a63b3b5-dd5b-c242-b723-24e2fb3768d7'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#showCommands->false); add: (#priority->5010); add: (#copyOfStep->#'d9634b11-bde6-1a40-a0b4-7be880afc37a'); yourself)); add: (#id->#'38378fb0-83d9-5243-a502-4e4e62e18131'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)