steps
stepac3b51604403e846987bb3be159ed5dc
	<step>

	^ ((Dictionary new) add: (#definition->#'d94d89dd-c32f-f144-b8b5-f265d775a7f5'); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->6360); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'27 May 2014 2:54:18 pm'); yourself)); add: (#id->#'ac3b5160-4403-e846-987b-b3be159ed5dc'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)