steps
stepdb94be9eb0285f46bfad28f781b0ae9e
	<step>

	^ ((Dictionary new) add: (#definition->#'e80f2ecd-de69-4d47-a05a-3c9164d1d0c1'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->1660); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'db94be9e-b028-5f46-bfad-28f781b0ae9e'); add: (#iconCode->'nil'); add: (#next->#'494bc6a5-c09d-fc4f-b22f-37955f890e49'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)