steps
step2b3d7c04cf7f9243b02d95fc7b500018
	<step>

	^ ((Dictionary new) add: (#definition->#'f7ea5265-696e-8243-9cb0-c42c1201004d'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->1330); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#headerText->'Methods'); yourself)); add: (#id->#'2b3d7c04-cf7f-9243-b02d-95fc7b500018'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)