steps
step70ad9734c28e424792a7f4d788a34977
	<step>

	^ ((Dictionary new) add: (#definition->#iconAndLabel); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->1430); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#headerText->'Sender'); yourself)); add: (#id->#'70ad9734-c28e-4247-92a7-f4d788a34977'); add: (#iconCode->'nil'); add: (#next->#'22529fa5-2b89-7d44-835d-e28f42d667a0'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)