steps
step86247f765b43d74882a2b2d9e56e443a
	<step>

	^ ((Dictionary new) add: (#definition->#'3b295445-8233-4343-b8f5-28fbcc5e1319'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->3370); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 September 2013 7:01:48 pm'); add: (#copyOfStep->#'86247f76-5b43-d748-82a2-b2d9e56e443a'); yourself)); add: (#id->#'86247f76-5b43-d748-82a2-b2d9e56e443a'); add: (#iconCode->'nil'); add: (#next->#'cb114238-013b-3e4d-9bf9-73b27ef3dd5a'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)