steps
step8173a10aef99b643819d530c4a9f806f
	<step>

	^ ((Dictionary new) add: (#definition->#'c832c425-3742-784c-81f6-541b0f9ae50a'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->4210); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'8 November 2013 3:19:19 pm'); yourself)); add: (#id->#'8173a10a-ef99-b643-819d-530c4a9f806f'); add: (#iconCode->'nil'); add: (#next->#'9af0df5a-068a-a649-9aa4-230c1f0217cc'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)