steps
step08b44027bc56f8449826f94859a5b557
	<step>

	^ ((Dictionary new) add: (#definition->#'74d42c6d-fa57-e44c-958d-da199a3de398'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->6430); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'5 June 2014 5:03:50 pm'); yourself)); add: (#id->#'08b44027-bc56-f844-9826-f94859a5b557'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)