steps
stepc2156a98722e7b46a844364bee591c7a
	<step>

	^ ((Dictionary new) add: (#definition->#'7500e5a0-9966-4645-a6e4-51a9ac020852'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->6230); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'11 February 2014 1:01:49 pm'); add: (#copyOfStep->#identity); yourself)); add: (#id->#'c2156a98-722e-7b46-a844-364bee591c7a'); add: (#iconCode->'nil'); add: (#next->#'d62c8659-3292-5541-b3b6-08b9ff46de99'); add: (#viewDefinition->#treeView); add: (#label->'Preview'); yourself)