steps
stepbee7ccaa7d429641b8d578a0c4f7224d
	<step>

	^ ((Dictionary new) add: (#definition->#'baae0367-2eb9-2745-b6af-c747b95925ac'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->6580); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'23 July 2014 12:56:18 pm'); yourself)); add: (#id->#'bee7ccaa-7d42-9641-b8d5-78a0c4f7224d'); add: (#iconCode->'nil'); add: (#next->#'c753d700-0c1c-024c-a7d1-68ffe3bc4166'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)