steps
stepb04432837194df4ebcb62dc3d3395f1b
	<step>

	^ ((Dictionary new) add: (#definition->#'2ce2840e-16d1-9f43-8532-2ba99b6eebef'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->2810); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#headerText->'Contents'); yourself)); add: (#id->#'b0443283-7194-df4e-bcb6-2dc3d3395f1b'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)