steps
stepf657b277fa4dd346b18c6ff6ffe558fa
	<step>

	^ ((Dictionary new) add: (#definition->#'05e20c00-19c2-b546-be31-ae5d98b374f1'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->6170); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'11 February 2014 1:01:49 pm'); add: (#copyOfStep->#identity); yourself)); add: (#id->#'f657b277-fa4d-d346-b18c-6ff6ffe558fa'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#textView); add: (#label->'Code'); yourself)