steps
step0caac112a8fdc443bf49f884e1be7743
	<step>

	^ ((Dictionary new) add: (#definition->#'705e187c-d0f6-f64d-9f4f-f2eef6af67a6'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->6640); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'23 July 2014 1:16:41 pm'); yourself)); add: (#id->#'0caac112-a8fd-c443-bf49-f884e1be7743'); add: (#iconCode->'nil'); add: (#next->#'d61e9087-1215-2d4e-b336-316c41064b72'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)