steps
step7585127607a784408574cc2965065a02
	<step>

	^ ((Dictionary new) add: (#definition->#'59ff4013-a7b4-c14b-a0ba-c43f66cb1658'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->5970); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'21 February 2014 8:53:15 am'); add: (#headerText->'Write'); yourself)); add: (#id->#'75851276-07a7-8440-8574-cc2965065a02'); add: (#iconCode->'nil'); add: (#next->#'554c12a4-3ed5-904d-8ada-bb3d129a200a'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)