steps
step80d8228dc6ed17448301762c72d90211
	<step>

	^ ((Dictionary new) add: (#definition->#origin); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->4820); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#'d9634b11-bde6-1a40-a0b4-7be880afc37a'); yourself)); add: (#id->#'80d8228d-c6ed-1744-8301-762c72d90211'); add: (#iconCode->'nil'); add: (#next->#'086c5944-1e51-2c4d-8e17-9ee9bffc0d2a'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)