steps
stepdd197842f4184e4fa3050fdfc97e60d6
	<step>

	^ ((Dictionary new) add: (#definition->#'42833415-c0c1-5547-a2d4-2379c3d211c3'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->790); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'dd197842-f418-4e4f-a305-0fdfc97e60d6'); add: (#iconCode->'UiFugueIcons blockIcon'); add: (#next->#'4b707439-66b1-c64b-805a-80c63759305e'); add: (#viewDefinition->#treeView); add: (#label->'Instance variables'); yourself)