steps
step72bf683031d81b429ddc991381a326f0
	<step>

	^ ((Dictionary new) add: (#definition->#'0f6ea484-5e59-cf42-903b-7c7ae1e08a1b'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->3440); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 September 2013 7:22:26 pm'); yourself)); add: (#id->#'72bf6830-31d8-1b42-9ddc-991381a326f0'); add: (#iconCode->'nil'); add: (#next->#'3ded3e1d-2e88-5448-a302-16e605bc65a0'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)