steps
stepb30d31379d85cb4699bea7682d624290
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsAsStrings); add: (#class->ViQueryGroupSortStep); add: (#properties->((Dictionary new) add: (#priority->2730); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'b30d3137-9d85-cb46-99be-a7682d624290'); add: (#iconCode->'nil'); add: (#next->#'7b56c7af-5bd2-4848-9eae-c2af03afefde'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)