steps
step2ebbfcc818ea964396ea4d38fe7cf10a
	<step>

	^ ((Dictionary new) add: (#definition->#'0ffa7f9a-df28-b24e-9fe9-0a8bcfefe2d9'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->6700); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'23 July 2014 2:46:54 pm'); yourself)); add: (#id->#'2ebbfcc8-18ea-9643-96ea-4d38fe7cf10a'); add: (#iconCode->'nil'); add: (#next->#'41f64542-f4fb-c341-8ee9-d1adfceebe00'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)