steps
step88256e17259b9c43973b01a903ccc633
	<step>

	^ ((Dictionary new) add: (#definition->#'11c68f4b-f94e-e44c-973f-d41b8b7f2351'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->5240); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'11 February 2014 1:01:49 pm'); add: (#copyOfStep->#identity); yourself)); add: (#id->#'88256e17-259b-9c43-973b-01a903ccc633'); add: (#iconCode->'nil'); add: (#next->#'8137f2f3-0fb0-d44b-a9b5-af172fdbc83d'); add: (#viewDefinition->#treeView); add: (#label->'Test results'); yourself)