steps
stepaa53c07584c54b40b6f36bcfd0ac3b68
	<step>

	^ ((Dictionary new) add: (#definition->#'72afa9e5-7d79-104b-97b0-accfde7204b7'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->500); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'aa53c075-84c5-4b40-b6f3-6bcfd0ac3b68'); add: (#iconCode->'UiFugueIcons picturesIcon'); add: (#next->#'78d3db6d-6a90-614d-88f9-eed2f96f9d05'); add: (#viewDefinition->#tileView); add: (#label->'Pictures'); yourself)