steps
step601f4f4795450e4eabefe7b5dc4c0c3e
	<step>

	^ ((Dictionary new) add: (#definition->#'6791d9d6-2faf-3448-8e22-0aa4c948acdc'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->5670); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 February 2014 4:31:11 pm'); yourself)); add: (#id->#'601f4f47-9545-0e4e-abef-e7b5dc4c0c3e'); add: (#iconCode->'nil'); add: (#next->#'6900ffdc-8414-5f4a-bab9-9602bbf21fae'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)