steps
step37aa1dbdbbd2b2429c7d2efb85ce5e27
	<step>

	^ ((Dictionary new) add: (#definition->#'e34d1bb9-2423-d34e-a16b-f84b0ab7ae75'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->2400); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'3 September 2013 3:27:42 pm'); yourself)); add: (#id->#'37aa1dbd-bbd2-b242-9c7d-2efb85ce5e27'); add: (#iconCode->'nil'); add: (#next->#'9d1f7dc5-d93e-274b-b732-b08a5181ea6f'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)