steps
stepe746a613ae44894a94a1f23d4ce7da40
	<step>

	^ ((Dictionary new) add: (#definition->#'1b047488-6502-e74e-83f2-05ae0fbf0400'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->490); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'3 January 2014 3:14:09 pm'); yourself)); add: (#id->#'e746a613-ae44-894a-94a1-f23d4ce7da40'); add: (#iconCode->'nil'); add: (#next->#'de02f056-5927-3144-a71d-76088dd47944'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)