steps
stepprintString
	<step>

	^ ((Dictionary new) add: (#definition->#'110cd1a9-7a94-7345-a3d8-482f7c4670f9'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->6730); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'25 July 2014 6:20:43 pm'); yourself)); add: (#id->#printString); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treePlain); add: (#label->nil); yourself)