steps
step2af25f9bebc0104eb6f8795b2094d0ee
	<step>

	^ ((Dictionary new) add: (#definition->#origin); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->8420); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'15 November 2014 4:30:01 pm'); yourself)); add: (#id->#'2af25f9b-ebc0-104e-b6f8-795b2094d0ee'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treePlain); add: (#label->nil); yourself)