steps
step9fe8fed8f944ec41b97b3eff6b3cf74f
	<step>

	^ ((Dictionary new) add: (#definition->#'6791d9d6-2faf-3448-8e22-0aa4c948acdc'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#006600'); add: (#creationAuthor->'mt'); add: (#priority->5060); add: (#creationTimeStamp->'11 February 2014 10:25:09 am'); yourself)); add: (#id->#'9fe8fed8-f944-ec41-b97b-3eff6b3cf74f'); add: (#iconCode->'nil'); add: (#next->#'b3a5a8de-9e73-f64d-a960-3946a4e8fbe5'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)