steps
step7b2e046b6047f542938be853216b364e
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsAsStrings); add: (#class->ViQueryGroupSortStep); add: (#properties->((Dictionary new) add: (#priority->1470); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'7b2e046b-6047-f542-938b-e853216b364e'); add: (#iconCode->'nil'); add: (#next->#'6f505e41-acfd-5d4f-ada2-77cdc48e1601'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)