steps
step72e942e1e871e04981f1f42f104b8324
	<step>

	^ ((Dictionary new) add: (#definition->#'00806058-79d3-8d44-8c2a-8cf4e9596925'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#view->ViMultiPaneWidget); add: (#creationTimeStamp->'29 January 2015 9:10:49 am'); add: (#isNew->false); yourself)); add: (#isProperty->true); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'72e942e1-e871-e049-81f1-f42f104b8324'); add: (#isReference->false); add: (#viewDefinition->#treePlain); yourself)