steps
stepd5cb07566c54dd4da1181174174246ff
	<step>

	^ ((Dictionary new) add: (#definition->#'514e33c1-49ef-db4a-ab27-1b67d793b46b'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->5840); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'11 February 2014 1:01:49 pm'); add: (#copyOfStep->#identity); yourself)); add: (#id->#'d5cb0756-6c54-dd4d-a118-1174174246ff'); add: (#iconCode->'nil'); add: (#next->#'3f2ccc8f-3fd6-2243-b5e4-1a2f686ed9bc'); add: (#viewDefinition->#textView); add: (#label->nil); yourself)