steps
step3544ebd42cabb84a88d20c15dde14360
	<step>

	^ ((Dictionary new) add: (#definition->#'ac70833a-9344-3c4c-9a24-8205b1501f40'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->5340); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 February 2014 1:08:55 pm'); add: (#headerText->#DMa); yourself)); add: (#id->#'3544ebd4-2cab-b84a-88d2-0c15dde14360'); add: (#iconCode->'nil'); add: (#next->#'c8c572a5-657f-6b41-aa8f-0014cda12185'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)