steps
stepd50e64dd2c00694f9ed1a81ee1b01b81
	<step>

	^ ((Dictionary new) add: (#definition->#'bdac2fd5-5d6d-8944-9179-74eb2b720a88'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->4350); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 November 2013 8:47:26 am'); yourself)); add: (#id->#'d50e64dd-2c00-694f-9ed1-a81ee1b01b81'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)