steps
step7907fbd5fb8347458cfd3c35462e6004
	<step>

	^ ((Dictionary new) add: (#definition->#'3e52466c-3192-4f4c-8bee-44755adf71a2'); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->4190); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#'dd7cc162-78d3-5946-8ad0-7e30f7b46f6d'); yourself)); add: (#id->#'7907fbd5-fb83-4745-8cfd-3c35462e6004'); add: (#iconCode->'nil'); add: (#next->#'ecc9e9ca-455e-c148-8762-1714a939cbe9'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)