steps
step5e2dceb99ba3484cb969cc38d82aeaf1
	<step>

	^ ((Dictionary new) add: (#definition->#'452e9359-82a2-3f43-94fe-c108dfa3fef0'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->750); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 September 2013 7:06:50 pm'); yourself)); add: (#id->#'5e2dceb9-9ba3-484c-b969-cc38d82aeaf1'); add: (#iconCode->'UiFugueIcons balloonExclamationIcon'); add: (#next->#'233b181d-fccc-094d-8b70-ba191cfe05ba'); add: (#viewDefinition->#treeView); add: (#label->'Unsent Messages'); yourself)