steps
step31d2b64c44d35c47964f83802a1f927f
	<step>

	^ ((Dictionary new) add: (#definition->#'8bab16cf-8208-4b43-abb2-ab6ad8964984'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->1650); add: (#headerText->'Class'); yourself)); add: (#id->#'31d2b64c-44d3-5c47-964f-83802a1f927f'); add: (#iconCode->'nil'); add: (#next->#'db94be9e-b028-5f46-bfad-28f781b0ae9e'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)