steps
stepe2aeb51f931d4e43a8d9a68001d03b29
	<step>

	^ ((Dictionary new) add: (#definition->#'419ba584-3e61-8c4f-9be1-0a92b213b108'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->5890); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'24 February 2014 11:02:55 am'); add: (#copyOfStep->#'6a945c46-e2f2-ac41-8b3e-dadc1328d8a3'); yourself)); add: (#id->#'e2aeb51f-931d-4e43-a8d9-a68001d03b29'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#textView); add: (#label->'Annotation'); yourself)