steps
step0d9ec3b0a6f23642a305d1b6a7827856
	<step>

	^ ((Dictionary new) add: (#definition->#'4fae4afe-0c3e-7441-9597-e7f50787e6e4'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->4910); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'31 January 2014 5:10:11 pm'); yourself)); add: (#id->#'0d9ec3b0-a6f2-3642-a305-d1b6a7827856'); add: (#iconCode->'nil'); add: (#next->#'3d9d6bb7-e6bc-5444-b1a3-96219e51fe10'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)