steps
step2a56df6169c833499b25d5afffcb60b1
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsAsStrings); add: (#class->ViQueryGroupSortStep); add: (#properties->((Dictionary new) add: (#priority->2850); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'2a56df61-69c8-3349-9b25-d5afffcb60b1'); add: (#iconCode->'nil'); add: (#next->#'4ce2b7cd-1c43-8241-a5bd-ca0484e682df'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)