steps
stepe45648f84feff3438972cbb555789355
	<step>

	^ ((Dictionary new) add: (#definition->#'c2f8f931-ca17-4e4c-bcca-2d77e7ab06db'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->5290); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'14 February 2014 1:06:18 pm'); add: (#headerText->#R); yourself)); add: (#id->#'e45648f8-4fef-f343-8972-cbb555789355'); add: (#iconCode->'nil'); add: (#next->#'62d361c4-2c39-6e47-989e-42b4f10c257c'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)