steps
stepcffbfe830584d2418e7b068442bd8619
	<step>

	^ ((Dictionary new) add: (#definition->#'8d718606-a86d-3040-8705-106076cda276'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->5600); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 February 2014 1:34:36 pm'); yourself)); add: (#id->#'cffbfe83-0584-d241-8e7b-068442bd8619'); add: (#iconCode->'nil'); add: (#next->#'a877e0b4-377f-244b-96e5-e6616c9f8247'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)