steps
stepb1afac3a000085449dceebfda96b30b6
	<step>

	^ ((Dictionary new) add: (#definition->#'51d9c6f1-45c9-814c-8d67-6864979fb6a0'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->6280); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'11 February 2014 1:01:49 pm'); add: (#copyOfStep->#identity); yourself)); add: (#id->#'b1afac3a-0000-8544-9dce-ebfda96b30b6'); add: (#iconCode->'nil'); add: (#next->#'cf42cf45-c23c-c149-81f2-1b262f58b7d3'); add: (#viewDefinition->#treeView); add: (#label->'DBLP Result'); yourself)