steps
step8ed524739493214294be054478bc571b
	<step>

	^ ((Dictionary new) add: (#definition->#'1a63b3b5-dd5b-c242-b723-24e2fb3768d7'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->660); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'3 September 2013 1:56:12 pm'); add: (#copyOfStep->#'8ed52473-9493-2142-94be-054478bc571b'); yourself)); add: (#id->#'8ed52473-9493-2142-94be-054478bc571b'); add: (#iconCode->'nil'); add: (#next->#'e63568e8-5926-f640-9527-117c4e70e841'); add: (#viewDefinition->#treeView); add: (#label->'Properties for Map Definitions'); yourself)