steps
step63c840019d52ee47b4a7446b7242ea74
	<step>

	^ ((Dictionary new) add: (#definition->#'b7a301c0-bb5c-a14f-a13d-b6e45ed4d473'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->3050); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'63c84001-9d52-ee47-b4a7-446b7242ea74'); add: (#iconCode->'nil'); add: (#next->#'dfb2af53-c012-e14a-ae23-1ee9009c0034'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)