steps
step02e8ebf69dc2a14288660da7a72f9253
	<step>

	^ ((Dictionary new) add: (#definition->#'d44f5d86-0853-4b42-b9ae-3fe3de077cf3'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->5420); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'14 February 2014 10:44:15 am'); add: (#headerText->#cM); yourself)); add: (#id->#'02e8ebf6-9dc2-a142-8866-0da7a72f9253'); add: (#iconCode->'nil'); add: (#next->#'ae3c2d41-a712-8f44-a52a-cd39fdb3459b'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)