steps
step574aa5e19265754a9cdb57e45108ee46
	<step>

	^ ((Dictionary new) add: (#definition->#'f2158056-1072-954d-8dcd-b9744f5a6849'); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->2390); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'3 September 2013 3:36:18 pm'); yourself)); add: (#id->#'574aa5e1-9265-754a-9cdb-57e45108ee46'); add: (#iconCode->'nil'); add: (#next->#'37aa1dbd-bbd2-b242-9c7d-2efb85ce5e27'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)