steps
stepcbc74d476dbd6e47a260f98c9364d715
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsAsStrings); add: (#class->ViQueryGroupSortStep); add: (#properties->((Dictionary new) add: (#priority->1700); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'cbc74d47-6dbd-6e47-a260-f98c9364d715'); add: (#iconCode->'nil'); add: (#next->#'71dfa65f-9c44-2a41-8cf3-08ac2c9154d8'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)