steps
step1969ce034b3dcd44a47f8a50c1ec3a4b
	<step>

	^ ((Dictionary new) add: (#definition->#'17e5fd35-6230-f348-a789-da694c0d0f55'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'12 May 2015 6:23:49 pm'); yourself)); add: (#isProperty->false); add: (#next->#'d85d6ab8-f194-f142-9b0a-05b44c7f6b73'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'1969ce03-4b3d-cd44-a47f-8a50c1ec3a4b'); add: (#isReference->false); yourself)