steps
stepcdbe8071be1b984eb62a2c1b721153c0
	<step>

	^ ((Dictionary new) add: (#definition->#'83108bd2-fbfa-9b49-a141-f65fbcf9adf4'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'000000'); add: (#creationTimeStamp->'13 September 2013 6:56:36 pm'); add: (#creationAuthor->'mt'); add: (#priority->3900); add: (#copyOfStep->#'4078cbfe-867e-564c-85b0-ac2edd21217d'); add: (#headerText->'Description'); add: (#resizeMode->#rigid); yourself)); add: (#id->#'cdbe8071-be1b-984e-b62a-2c1b721153c0'); add: (#iconCode->'nil'); add: (#next->#'c95c6c53-431d-d44d-895e-41f83dbc02c4'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)