steps
stepd96e910adf735a4cb7608811fac45378
	<step>

	^ ((Dictionary new) add: (#definition->#'d06feec8-587b-1b4b-8b63-a5aeb5f665b2'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#hAlignment->#left); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#itemOrientation->#horizontalMaxHeight); add: (#creationAuthor->'mt'); add: (#vAlignment->#top); add: (#priority->2570); add: (#headerText->'Origin'); yourself)); add: (#id->#'d96e910a-df73-5a4c-b760-8811fac45378'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)