steps
step8137f2f30fb0d44ba9b5af172fdbc83d
	<step>

	^ ((Dictionary new) add: (#definition->#'6791d9d6-2faf-3448-8e22-0aa4c948acdc'); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->5590); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 February 2014 1:34:17 pm'); yourself)); add: (#id->#'8137f2f3-0fb0-d44b-a9b5-af172fdbc83d'); add: (#iconCode->'nil'); add: (#next->#'cffbfe83-0584-d241-8e7b-068442bd8619'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)