steps
step6538b2d10d571345abf64be841b78c42
	<step>

	^ ((Dictionary new) add: (#definition->#allMethodsForClass); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->6490); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#'bec0a4ef-c091-a844-88ef-be4ea489648e'); yourself)); add: (#id->#'6538b2d1-0d57-1345-abf6-4be841b78c42'); add: (#iconCode->'nil'); add: (#next->#'f0de7c84-7017-2d42-860d-e743620ce3b4'); add: (#viewDefinition->#treeViewExtended); add: (#label->'Methods (Signatures)'); yourself)