steps
step99cac90068fd1449966b015ed7762e86
	<step>

	^ ((Dictionary new) add: (#definition->#'187d2c6e-fa01-5d4a-b748-1a739c679b7b'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->5130); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'11 February 2014 1:01:49 pm'); add: (#copyOfStep->#identity); yourself)); add: (#id->#'99cac900-68fd-1449-966b-015ed7762e86'); add: (#iconCode->'nil'); add: (#next->#'56b2492f-f394-db42-ade3-e2d633f5230d'); add: (#viewDefinition->#treeViewExtended); add: (#label->'Line of code category'); yourself)