steps
stepa62c64219b1098418280932805e5b88b
	<step>

	^ ((Dictionary new) add: (#definition->#'aa89602f-a4cc-7841-a21c-eaf6f17bee2a'); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->4780); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 January 2014 4:40:37 pm'); yourself)); add: (#id->#'a62c6421-9b10-9841-8280-932805e5b88b'); add: (#iconCode->'nil'); add: (#next->#'d82ec0a6-a967-514a-953c-27fcb67ec3d3'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)