steps
step9735da59b580ce419647a3fd1ed024a5
	<step>

	^ ((Dictionary new) add: (#definition->#'e51b5817-2aa3-0e4a-bd10-68436cd94de6'); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->1690); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'9735da59-b580-ce41-9647-a3fd1ed024a5'); add: (#iconCode->'nil'); add: (#next->#'cbc74d47-6dbd-6e47-a260-f98c9364d715'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)