steps
stepfd62bf2f377ce64ab62a4f2399a054e1
	<step>

	^ ((Dictionary new) add: (#definition->#'236a8c89-659c-5349-a716-fd2bed0f7486'); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->1210); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'fd62bf2f-377c-e64a-b62a-4f2399a054e1'); add: (#iconCode->'nil'); add: (#next->#'9cef732f-20e3-884c-8e5f-55e415a20f91'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)