steps
step240cc4b3dcec8c4ebbe829ff7c118338
	<step>

	^ ((Dictionary new) add: (#definition->#'dead5eeb-1ecf-8040-aa1c-9f2476397298'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->4620); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'9 January 2014 11:34:40 am'); yourself)); add: (#id->#'240cc4b3-dcec-8c4e-bbe8-29ff7c118338'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)