steps
stepf54c9a3b47b76a42a9a41843fbd23ecd
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsAsStrings); add: (#class->ViQueryGroupSortStep); add: (#properties->((Dictionary new) add: (#priority->4400); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 November 2013 4:23 pm'); yourself)); add: (#id->#'f54c9a3b-47b7-6a42-a9a4-1843fbd23ecd'); add: (#iconCode->'nil'); add: (#next->#'1258312c-a457-db40-aa96-499fda6b7623'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)