steps
stepe68b5fc66c4c504baaa0628d9063c113
	<step>

	^ ((Dictionary new) add: (#definition->#iconAndLabel); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->1860); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#headerText->'Methods'); yourself)); add: (#id->#'e68b5fc6-6c4c-504b-aaa0-628d9063c113'); add: (#iconCode->'nil'); add: (#next->#'4a5e36f9-9a70-394a-a39b-c0891bc2e99b'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)