steps
stepa6bc57c78e46fc4ba64faccbe55ab577
	<step>

	^ ((Dictionary new) add: (#definition->#'18acd9e0-dfe4-5e4f-bf30-f837199c504f'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->460); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'a6bc57c7-8e46-fc4b-a64f-accbe55ab577'); add: (#iconCode->'nil'); add: (#next->#'56d4e61d-ee76-514b-bc24-e352a53b0d46'); add: (#viewDefinition->#treeView); add: (#label->'Closed objects'); yourself)