steps
step41a224d783bca848a1fcb3e16df604f9
	<step>

	^ ((Dictionary new) add: (#definition->#'baae0367-2eb9-2745-b6af-c747b95925ac'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->200); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#'8c0c7c2f-de5c-284d-9d9a-2d20961a1db5'); yourself)); add: (#id->#'41a224d7-83bc-a848-a1fc-b3e16df604f9'); add: (#iconCode->'nil'); add: (#next->#'659bb790-ed7e-4a44-93d4-298862236d0b'); add: (#viewDefinition->#treeViewExtended); add: (#label->nil); yourself)