steps
step4ce2b7cd1c438241a5bdca0484e682df
	<step>

	^ ((Dictionary new) add: (#definition->#iconAndLabel); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->2860); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#headerText->'Object'); yourself)); add: (#id->#'4ce2b7cd-1c43-8241-a5bd-ca0484e682df'); add: (#iconCode->'nil'); add: (#next->#'225b70fb-8963-d84a-a825-589a864d6670'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)