steps
stepd85efa7f95788341a11019f9ca847c76
	<step>

	^ ((Dictionary new) add: (#definition->#'6615e26b-6ca7-2a4e-b214-c4e0bc0ca8f3'); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->3450); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 September 2013 7:28:32 pm'); yourself)); add: (#id->#'d85efa7f-9578-8341-a110-19f9ca847c76'); add: (#iconCode->'nil'); add: (#next->#'40560165-a4c7-4042-9740-90e250b56bd7'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)