steps
step4fc198280194f04685e2a6f160b52f5b
	<step>

	^ ((Dictionary new) add: (#definition->#'94349485-e72e-6d47-b370-a6a240d8da9f'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->4570); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#defaultProperties); yourself)); add: (#id->#'4fc19828-0194-f046-85e2-a6f160b52f5b'); add: (#iconCode->'UiSilkIcons lightningDeleteIcon'); add: (#next->nil); add: (#viewDefinition->#tileView); add: (#label->'Reject Errors'); yourself)