steps
step76221c325f94c545a4a4cf57138ffe39
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsByName); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->5090); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'12 February 2014 3:22:59 pm'); yourself)); add: (#id->#'76221c32-5f94-c545-a4a4-cf57138ffe39'); add: (#iconCode->'nil'); add: (#next->#'19536a17-53f2-a544-90d1-73c5acc3cb61'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)