steps
stepaba8446dad234a448fc1448e43f60d5d
	<step>

	^ ((Dictionary new) add: (#definition->#origin); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#copyOfStep->#'d9634b11-bde6-1a40-a0b4-7be880afc37a'); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'aba8446d-ad23-4a44-8fc1-448e43f60d5d'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)