steps
steped47392de9cfe24c9069a3a89fba2ea6
	<step>

	^ ((Dictionary new) add: (#definition->#'22e2e96d-767f-7242-ac18-79b9438046bc'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->5110); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 February 2014 9:43 am'); yourself)); add: (#id->#'ed47392d-e9cf-e24c-9069-a3a89fba2ea6'); add: (#iconCode->'nil'); add: (#next->#'aa477db3-7d10-1f48-8339-140e6d470e38'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)