steps
step074a7165102004428a76a2ce9f8ab3e6
	<step>

	^ ((Dictionary new) add: (#definition->#'08224455-89e8-1b48-b01d-de8f5a01861d'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->3510); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 September 2013 7:46:24 pm'); yourself)); add: (#id->#'074a7165-1020-0442-8a76-a2ce9f8ab3e6'); add: (#iconCode->'UiFugueIcons questionBalloonIcon'); add: (#next->#'e847db70-263a-3b49-a792-9d80a42da426'); add: (#viewDefinition->#treeView); add: (#label->'Uncommented Classes'); yourself)