steps
stepcd28236371fbf94a9a4c49ce99c79f7b
	<step>

	^ ((Dictionary new) add: (#definition->#'0f8f45f9-a0cc-c34a-9b8f-6d1a4f00e403'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->1970); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'cd282363-71fb-f94a-9a4c-49ce99c79f7b'); add: (#iconCode->'nil'); add: (#next->#'31eeb1cd-153a-a246-b7d8-6a6b7f6a95b8'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)