steps
stepe84072d2c593f549a93cd5dbeb2e3b94
	<step>

	^ ((Dictionary new) add: (#definition->#iconAndLabel); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->1370); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'e84072d2-c593-f549-a93c-d5dbeb2e3b94'); add: (#iconCode->'nil'); add: (#next->#'3723f748-fad3-d446-8f95-d2d495e9a9cc'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)