steps
stepa8d8130a271c954eaca4bad9c8477a24
	<step>

	^ ((Dictionary new) add: (#definition->#'e34d1bb9-2423-d34e-a16b-f84b0ab7ae75'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#000000'); add: (#creationAuthor->'mt'); add: (#priority->4230); add: (#creationTimeStamp->'8 November 2013 4:11:08 pm'); yourself)); add: (#id->#'a8d8130a-271c-954e-aca4-bad9c8477a24'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)