steps
stepe4cedfc134196a46a30665067830a9bf
	<step>

	^ ((Dictionary new) add: (#definition->#'3e52466c-3192-4f4c-8bee-44755adf71a2'); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->5480); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#'7907fbd5-fb83-4745-8cfd-3c35462e6004'); yourself)); add: (#id->#'e4cedfc1-3419-6a46-a306-65067830a9bf'); add: (#iconCode->'nil'); add: (#next->#'90bb3b19-d2be-164e-a306-83db53cee32e'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)