steps
step659bb790ed7e4a4493d4298862236d0b
	<step>

	^ ((Dictionary new) add: (#definition->#'720a8d90-f7c1-334e-a4ea-5094ba285a8d'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->4660); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'10 January 2014 12:51:45 pm'); yourself)); add: (#id->#'659bb790-ed7e-4a44-93d4-298862236d0b'); add: (#iconCode->'nil'); add: (#next->#'1d5de9cf-9877-a848-91b4-9715373f1ad1'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)