steps
step53515aaf6982b048afb6e82af653f073
	<step>

	^ ((Dictionary new) add: (#definition->#'92d66888-3e33-e449-82ee-fc6d9fdf72e6'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#000000'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->2450); add: (#resizeMode->#rigid); add: (#headerText->'Object'); yourself)); add: (#id->#'53515aaf-6982-b048-afb6-e82af653f073'); add: (#iconCode->'nil'); add: (#next->#'f4f3c4ff-456b-3a46-a1ae-22320975be38'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)