steps
stepaa477db37d101f488339140e6d470e38
	<step>

	^ ((Dictionary new) add: (#definition->#subclasses); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'aa477db3-7d10-1f48-8339-140e6d470e38'); add: (#iconCode->'nil'); add: (#next->#'6a85aea6-6f46-5941-8895-484cadece99b'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)