steps
stepe4134486b81a204184a2805061658e31
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsAsStrings); add: (#class->ViQueryGroupSortStep); add: (#properties->((Dictionary new) add: (#priority->1800); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'e4134486-b81a-2041-84a2-805061658e31'); add: (#iconCode->'nil'); add: (#next->#'2902b302-607d-7340-b97a-4a497764e9d3'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)