steps
step8392e394aff92645be373e9da7fa6019
	<step>

	^ ((Dictionary new) add: (#definition->#'5e31638a-be43-9f4b-bbc3-0248666964f2'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'21 October 2014 4:03:58 pm'); yourself)); add: (#isProperty->false); add: (#next->#'8e0086dc-e5de-f948-b5b5-b355fc568037'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'8392e394-aff9-2645-be37-3e9da7fa6019'); add: (#viewDefinition->#treePlain); yourself)