steps
step959bb1be74008b46bbf7ad6fc02146e4
	<step>

	^ ((Dictionary new) add: (#definition->#'3d30f848-6623-6f4b-b599-ca6fffd99810'); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->1740); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'959bb1be-7400-8b46-bbf7-ad6fc02146e4'); add: (#iconCode->'nil'); add: (#next->#'d70ca6fc-bf5e-ee4a-ae39-89d3d351c3bb'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)