steps
step472051050b027048a7ad720e9ca31a7f
	<step>

	^ ((Dictionary new) add: (#definition->#'fa585967-f2b4-bf43-9b5e-cc34c15d0e26'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'47205105-0b02-7048-a7ad-720e9ca31a7f'); add: (#iconCode->'nil'); add: (#next->#'afd7936f-3466-6b44-84a7-2d8fc3dc21a4'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)