steps
step97b22eff73d84746b8774dc3d77e1208
	<step>

	^ ((Dictionary new) add: (#definition->#'5389ac08-4249-614e-961f-06d2d75458c6'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'20 May 2015 12:12:18 pm'); yourself)); add: (#isProperty->false); add: (#next->#'43dad8cd-aa5a-f540-bf91-5c505349e324'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'97b22eff-73d8-4746-b877-4dc3d77e1208'); add: (#isReference->true); yourself)