steps
step28be63168868744c9db70ec219020611
	<step>

	^ ((Dictionary new) add: (#definition->#'5bcb73c5-9ad5-054d-90c6-997215e79578'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->50); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 November 2013 9:09:07 am'); yourself)); add: (#id->#'28be6316-8868-744c-9db7-0ec219020611'); add: (#iconCode->'nil'); add: (#next->#'cfe6ad6f-ad06-774f-b19c-5dc3bea7243e'); add: (#viewDefinition->#treeView); add: (#label->'Transcript'); yourself)