steps
stepc9ff51f897e3cf46ba3f4d71325c942d
	<step>

	^ ((Dictionary new) add: (#definition->#subclasses); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->2150); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'c9ff51f8-97e3-cf46-ba3f-4d71325c942d'); add: (#iconCode->'nil'); add: (#next->#'0598baea-8006-ef4e-a2f2-6d5412d6ab3c'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)