steps
stepe6c86a4e3d9cde46afc1e019ab13b011
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsByName); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->5100); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'12 February 2014 3:28:35 pm'); yourself)); add: (#id->#'e6c86a4e-3d9c-de46-afc1-e019ab13b011'); add: (#iconCode->'nil'); add: (#next->#'a0430b66-9a7d-f044-be09-b17780bf171f'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)