steps
stepe0d4454d01886242916d1c1f2b47e445
	<step>

	^ ((Dictionary new) add: (#definition->#'3d0c7269-aed8-9e4a-9b3d-fa7ec52d2dc1'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#999999'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->2440); add: (#headerText->'Name'); yourself)); add: (#id->#'e0d4454d-0188-6242-916d-1c1f2b47e445'); add: (#iconCode->'nil'); add: (#next->#'53515aaf-6982-b048-afb6-e82af653f073'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)