steps
step8451e0da6c997f419483316176f07642
	<step>

	^ ((Dictionary new) add: (#definition->#'da8a8f50-3e4c-d44c-9f64-45781be27672'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'20 May 2015 2:49:42 pm'); yourself)); add: (#isProperty->false); add: (#next->#'dc34144d-6524-cf48-a9a5-903457596587'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'8451e0da-6c99-7f41-9483-316176f07642'); add: (#isReference->false); add: (#viewDefinition->nil); yourself)