steps
stepeac8722e840ed245906beb6a01ac58a1
	<step>

	^ ((Dictionary new) add: (#definition->#'718de269-27aa-d24a-9303-013c573b12ba'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->110); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'eac8722e-840e-d245-906b-eb6a01ac58a1'); add: (#iconCode->'UiFugueIcons priceTagIcon'); add: (#next->#'959bb1be-7400-8b46-bbf7-ad6fc02146e4'); add: (#viewDefinition->#treeView); add: (#label->'Protocols (objectified)'); yourself)