steps
step2defa63a99915e4285200d0db861b77c
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsAsStrings); add: (#class->ViQueryGroupSortStep); add: (#properties->((Dictionary new) add: (#priority->2000); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'2defa63a-9991-5e42-8520-0d0db861b77c'); add: (#iconCode->'nil'); add: (#next->#'e66f7ebe-27a3-584f-836c-ee4cf8041d8b'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)