steps
step5e40bd1a93876f42948e0dc9439c31c8
	<step>

	^ ((Dictionary new) add: (#definition->#'d5487647-ffe9-154b-9d5c-3cc2c971450e'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->220); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'5e40bd1a-9387-6f42-948e-0dc9439c31c8'); add: (#iconCode->'UiFugueIcons scriptArrowIcon'); add: (#next->#'a0abb65a-7c24-ff4a-a661-579881ae45e7'); add: (#viewDefinition->#treeView); add: (#label->'Implementors (recursive, symbols only)'); yourself)