steps
stepe9f4b617ab3acd419a5b9f547aa04c9d
	<step>

	^ ((Dictionary new) add: (#definition->#'563021ef-44a7-e24e-beb7-6201088a6f24'); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->1250); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'e9f4b617-ab3a-cd41-9a5b-9f547aa04c9d'); add: (#iconCode->'nil'); add: (#next->#'cb96415c-4b85-6247-877c-589b975e69c8'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)