steps
step1cd2a5a305f390468fd206f0a076f80b
	<step>

	^ ((Dictionary new) add: (#definition->#'772cc5f9-cfec-4f49-9902-686bc54662cf'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->2800); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'1cd2a5a3-05f3-9046-8fd2-06f0a076f80b'); add: (#iconCode->'nil'); add: (#next->#'67636419-4db6-8c43-aa22-b3948e02e796'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)