steps
stepe55220907365c4428d1594253ec1d77e
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsAsStrings); add: (#class->ViQueryGroupSortStep); add: (#properties->((Dictionary new) add: (#priority->1320); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'e5522090-7365-c442-8d15-94253ec1d77e'); add: (#iconCode->'nil'); add: (#next->#'2b3d7c04-cf7f-9243-b02d-95fc7b500018'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)