steps
stepd35e7fe288dc344291c23bf94fe89b02
	<step>

	^ ((Dictionary new) add: (#definition->#methodReferenceToPackageName); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->1460); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'d35e7fe2-88dc-3442-91c2-3bf94fe89b02'); add: (#iconCode->'nil'); add: (#next->#'7b2e046b-6047-f542-938b-e853216b364e'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)