steps
stepb44723c500630f4da4b71bd13591ae84
	<step>

	^ ((Dictionary new) add: (#definition->#'1d92a8e5-d139-ef4b-8c89-e9b7f36c881a'); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->2330); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'b44723c5-0063-0f4d-a4b7-1bd13591ae84'); add: (#iconCode->'nil'); add: (#next->#'89c40fb8-551c-9e46-9651-f11978e9ff30'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)