steps
step93b6233ea34ef54d9c6ab7eeef30e075
	<step>

	^ ((Dictionary new) add: (#definition->#'d905ce02-2192-9c48-9eb3-ceb8d1ceaf80'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->4320); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#'d9634b11-bde6-1a40-a0b4-7be880afc37a'); yourself)); add: (#id->#'93b6233e-a34e-f54d-9c6a-b7eeef30e075'); add: (#iconCode->'nil'); add: (#next->#'fb5f9d48-49cf-774c-921f-e9598b74d2c7'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)