steps
step1bb6538bc256b34b958e5996dea59092
	<step>

	^ ((Dictionary new) add: (#definition->#iconAndLabel); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->2470); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'1bb6538b-c256-b34b-958e-5996dea59092'); add: (#iconCode->'nil'); add: (#next->#'2d49b98d-3f27-e14f-aaa8-aee4706a6a0a'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)