steps
step4e06ed51665de446a53c44763032a14c
	<step>

	^ ((Dictionary new) add: (#definition->#methodReferenceToPackageName); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->2230); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'4e06ed51-665d-e446-a53c-44763032a14c'); add: (#iconCode->'nil'); add: (#next->#'ed426c8e-af11-614e-8389-4c0d36c6c86b'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)