steps
step5bac288b036f3b409351de76b1f7cd03
	<step>

	^ ((Dictionary new) add: (#definition->#'58e3ab98-ca82-5642-86d7-05c3b94c72d8'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->3130); add: (#headerText->'NumVersions'); yourself)); add: (#id->#'5bac288b-036f-3b40-9351-de76b1f7cd03'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)