steps
step1bb9843febf1384882dc01ee3ed5468d
	<step>

	^ ((Dictionary new) add: (#definition->#'e4f148b7-a110-f34d-a934-f46bec7ee57e'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->5390); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 February 2014 1:57:43 pm'); add: (#headerText->'cS'); yourself)); add: (#id->#'1bb9843f-ebf1-3848-82dc-01ee3ed5468d'); add: (#iconCode->'nil'); add: (#next->#'78e13ff4-d093-1140-b575-be2225a6eaf7'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)