steps
step18533aea2a404a4fb098e14e7fdcb291
	<step>

	^ ((Dictionary new) add: (#definition->#'245c4ce0-a93e-6943-8f4e-042ef3efa6a8'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->6180); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'5 June 2014 4:48:11 pm'); yourself)); add: (#id->#'18533aea-2a40-4a4f-b098-e14e7fdcb291'); add: (#iconCode->'nil'); add: (#next->#'fdc9d784-2f4f-8a42-8553-dfc7982b9585'); add: (#viewDefinition->#treeView); add: (#label->'Change Sets'); yourself)