steps
step3947aee45c3a16498884a37f2fcf75e9
	<step>

	^ ((Dictionary new) add: (#definition->#'d8985e4a-16e9-8643-9143-06e11ad06235'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->1390); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'3947aee4-5c3a-1649-8884-a37f2fcf75e9'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)