steps
stepf977b925bca88e418e7a33672b08eb1d
	<step>

	^ ((Dictionary new) add: (#definition->#'ab097827-d773-694d-bec1-8bf8e939ec71'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->2970); add: (#headerText->'Message'); yourself)); add: (#id->#'f977b925-bca8-8e41-8e7a-33672b08eb1d'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)