steps
step6432870100b2654ea36998b5ecac31fd
	<step>

	^ ((Dictionary new) add: (#definition->#'0fee1e3f-c9f8-9042-b646-88feee2a13c8'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->#AAAAAA); add: (#creationAuthor->'mt'); add: (#priority->4460); add: (#creationTimeStamp->'18 November 2013 4:53:55 pm'); yourself)); add: (#id->#'64328701-00b2-654e-a369-98b5ecac31fd'); add: (#iconCode->'nil'); add: (#next->#'5e941cab-2cc7-0646-9ed0-d8493d5d3d0e'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)