steps
step5406f229d72e9840a58dc61752a3b24a
	<step>

	^ ((Dictionary new) add: (#definition->#'8d04e4fb-3e37-ca47-9678-68392bce2475'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'000000'); add: (#creationTimeStamp->'19 September 2013 3:49:48 pm'); add: (#creationAuthor->'mt'); add: (#priority->4030); add: (#headerText->'Line'); yourself)); add: (#id->#'5406f229-d72e-9840-a58d-c61752a3b24a'); add: (#iconCode->'nil'); add: (#next->#'578f3d1f-bdb5-b04b-85ff-fe0c848c6af5'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)