steps
step6d55d7d63c09b044b03a0105386e67a4
	<step>

	^ ((Dictionary new) add: (#definition->#removeDuplicates); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->4500); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'4 October 2013 6:33:02 pm'); add: (#copyOfStep->#'b90e4eaa-f8ab-8b47-aca3-f78a5dadde3e'); yourself)); add: (#id->#'6d55d7d6-3c09-b044-b03a-0105386e67a4'); add: (#iconCode->'nil'); add: (#next->#'3dbca45d-ef24-5e49-975e-38f04a9a7729'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)