steps
step6a945c46e2f2ac418b3edadc1328d8a3
	<step>

	^ ((Dictionary new) add: (#definition->#'0481a903-f8da-2d42-9c11-991745884f3d'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->5850); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'24 February 2014 11:02:55 am'); yourself)); add: (#id->#'6a945c46-e2f2-ac41-8b3e-dadc1328d8a3'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#textView); add: (#label->'Pretty print'); yourself)