steps
step24d74d145e317641a5f6d6667eb3ffd2
	<step>

	^ ((Dictionary new) add: (#definition->#'33142aab-4e05-3248-ad60-a51e6685352b'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->6560); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#'26f3a2b2-f47a-644b-ac5f-159e2365b955'); yourself)); add: (#id->#'24d74d14-5e31-7641-a5f6-d6667eb3ffd2'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)