steps
step5d53db968bb9fb43921cfbcba4297063
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsAsStrings); add: (#class->ViQueryGroupSortStep); add: (#properties->((Dictionary new) add: (#priority->4450); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 November 2013 5:01:12 pm'); yourself)); add: (#id->#'5d53db96-8bb9-fb43-921c-fbcba4297063'); add: (#iconCode->'nil'); add: (#next->#'64328701-00b2-654e-a369-98b5ecac31fd'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)