steps
step19cadf89e6012b45be3bc5bcf0de5b35
	<step>

	^ ((Dictionary new) add: (#definition->#'b0fe6ff5-386f-3c49-b42d-d2f2c7c96a1a'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->950); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 4:21:57 pm'); yourself)); add: (#id->#'19cadf89-e601-2b45-be3b-c5bcf0de5b35'); add: (#iconCode->'UiSilkIcons chartBarIcon'); add: (#next->#'d0704ef9-0a64-0d44-9681-7487f8ee4e7b'); add: (#viewDefinition->#treeView); add: (#label->'Frequency of Step Definitions'); yourself)