steps
step252b6d01f4902640a5fc6b968dc12be4
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsAsStrings); add: (#class->ViQueryGroupSortStep); add: (#properties->((Dictionary new) add: (#priority->2660); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'252b6d01-f490-2640-a5fc-6b968dc12be4'); add: (#iconCode->'nil'); add: (#next->#'432a6001-f00e-514e-a68e-4605686f7755'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)