steps
step08b0757a37bb0142973e5faca3677989
	<step>

	^ ((Dictionary new) add: (#definition->#'2706f4db-41f1-fc4c-a2f8-7373edfc7b36'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#view->ViTextEdit); add: (#copyOf->#identity); add: (#creationTimeStamp->'21 October 2014 2:50:51 pm'); add: (#priority->8390); yourself)); add: (#isProperty->false); add: (#next->#'14c2d4d3-e9a4-a049-b911-1bd24ba1ee34'); add: (#label->'Question Body'); add: (#iconCode->'nil'); add: (#id->#'08b0757a-37bb-0142-973e-5faca3677989'); add: (#viewDefinition->#treePlain); yourself)