steps
step244a371f7663214d932d5512b30c3e35
	<step>

	^ ((Dictionary new) add: (#definition->#'d77d8164-faa6-574d-9abc-f9712d2c6d20'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->6330); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'23 May 2014 11:09:25 am'); yourself)); add: (#id->#'244a371f-7663-214d-932d-5512b30c3e35'); add: (#iconCode->'nil'); add: (#next->#'7b87d63f-f0ab-524e-b406-502817498dbb'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)