steps
stepa7051ae5cc1f664ab65e64ffad87b981
	<step>

	^ ((Dictionary new) add: (#definition->#copyToContext); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'a7051ae5-cc1f-664a-b65e-64ffad87b981'); add: (#iconCode->'nil'); add: (#next->#'47205105-0b02-7048-a7ad-720e9ca31a7f'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)