steps
stepe36efb5e3ac6e540af1c498872dec4b2
	<step>

	^ ((Dictionary new) add: (#definition->#'a5bc60d1-63c3-8c42-9039-698a5f637754'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->3940); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#defaultProperties); yourself)); add: (#id->#'e36efb5e-3ac6-e540-af1c-498872dec4b2'); add: (#iconCode->'ViEclipseIcons classHiIcon'); add: (#next->#'328d2fd9-190c-6f40-accd-afc2029f12c4'); add: (#viewDefinition->#treeView); add: (#label->'Type Hierarchy'); yourself)