steps
stepeae7856b17a82746aa42f06591c95280
	<step>

	^ ((Dictionary new) add: (#definition->#origin); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->3490); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 September 2013 7:35:35 pm'); yourself)); add: (#id->#'eae7856b-17a8-2746-aa42-f06591c95280'); add: (#iconCode->'nil'); add: (#next->#'7faad50a-ce32-d04b-93a5-abcb22ff458e'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)