steps
step29a5b770b982f548b9d29842b501cff9
	<step>

	^ ((Dictionary new) add: (#definition->#'e41f5f5b-ca8c-0946-9f02-9a0f2dc0269e'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->3200); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 4:21:57 pm'); yourself)); add: (#id->#'29a5b770-b982-f548-b9d2-9842b501cff9'); add: (#iconCode->'nil'); add: (#next->#'d1d946a9-b78e-7243-8d30-c08accd864b6'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)