steps
stepdefaultPropertiesExtended
	<step>

	^ ((Dictionary new) add: (#definition->#'81e09cb2-b3ab-b345-b591-fd828ea01434'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'20 May 2015 2:52:45 pm'); yourself)); add: (#isProperty->true); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#defaultPropertiesExtended); add: (#isReference->false); add: (#viewDefinition->nil); yourself)