steps
stepebd29250144e7b45bd3a2ad394ef1b4a
	<step>

	^ ((Dictionary new) add: (#definition->#'4edf993e-53de-4942-aaa2-45bbb7e72321'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'20 May 2015 2:48:49 pm'); yourself)); add: (#isProperty->false); add: (#next->#'8451e0da-6c99-7f41-9483-316176f07642'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'ebd29250-144e-7b45-bd3a-2ad394ef1b4a'); add: (#isReference->false); yourself)