steps
step3f7e4a145a931c4484e012fc74706383
	<step>

	^ ((Dictionary new) add: (#definition->#'be02a17d-cc98-1640-ae53-b8838236dad5'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->6140); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'11 February 2014 1:01:49 pm'); add: (#copyOfStep->#identity); yourself)); add: (#id->#'3f7e4a14-5a93-1c44-84e0-12fc74706383'); add: (#iconCode->'nil'); add: (#next->#'8c98ea10-5364-be4b-b343-835196faca7e'); add: (#viewDefinition->#treePlain); add: (#label->'Classes'); yourself)