steps
step11680fd2f33fd14ab414ed7067db4d47
	<step>

	^ ((Dictionary new) add: (#definition->#'058d3529-d310-e847-b148-dadf47ff31b9'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->6760); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'11 February 2014 1:01:49 pm'); add: (#copyOfStep->#identity); yourself)); add: (#id->#'11680fd2-f33f-d14a-b414-ed7067db4d47'); add: (#iconCode->'nil'); add: (#next->#senders); add: (#viewDefinition->#treePlain); add: (#label->nil); yourself)