steps
stepd5db789c076fb7409144a2bd2740df7f
	<step>

	^ ((Dictionary new) add: (#definition->#'4ed0c304-26af-fe48-8259-0553dbe3f8e0'); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->5760); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'20 February 2014 6:27:55 pm'); yourself)); add: (#id->#'d5db789c-076f-b740-9144-a2bd2740df7f'); add: (#iconCode->'nil'); add: (#next->#'ff9ce8ad-7d0d-4744-afba-f53a7a933bd9'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)