steps
stepa877e0b4377f244b96e5e6616c9f8247
	<step>

	^ ((Dictionary new) add: (#definition->#'954dc6a5-194d-a143-9928-d69d3079d47a'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->5610); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 February 2014 1:38:46 pm'); yourself)); add: (#id->#'a877e0b4-377f-244b-96e5-e6616c9f8247'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)