steps
step3949844d11c6dd41b185b338c3ca4dac
	<step>

	^ ((Dictionary new) add: (#definition->#'0c53b73c-4e16-1542-b40c-cd76a3b1dda5'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->3740); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 September 2013 5:29:39 pm'); yourself)); add: (#id->#'3949844d-11c6-dd41-b185-b338c3ca4dac'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)