steps
stepe0f288dd4846714bbdc86b0065de1f63
	<step>

	^ ((Dictionary new) add: (#definition->#'47cabae4-3c61-3b4f-a16b-87529b48d989'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->270); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'e0f288dd-4846-714b-bdc8-6b0065de1f63'); add: (#iconCode->'UiFugueIcons blockIcon'); add: (#next->#'e505710c-f722-e34e-a85e-f914106ea5cb'); add: (#viewDefinition->#treeView); add: (#label->'Instance variable references'); yourself)