steps
stepb0e115e36fb8f84c87f4f21d46eb5c7e
	<step>

	^ ((Dictionary new) add: (#definition->#'9f165395-722b-6b41-979e-695440a8254b'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->3010); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#headerText->'Type'); yourself)); add: (#id->#'b0e115e3-6fb8-f84c-87f4-f21d46eb5c7e'); add: (#iconCode->'UiFugueIcons documentNodeIcon'); add: (#next->#'6c0a1727-d1af-3a4a-a6b8-79445faf91a2'); add: (#viewDefinition->#treeView); add: (#label->'Abstract Syntax Tree'); yourself)