steps
stepbfabd5302b5ec74cb43f4b3b4d090d46
	<step>

	^ ((Dictionary new) add: (#definition->#'4faf0cde-e73a-cc40-8224-8c497290e51f'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->4680); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'14 January 2014 1:18:03 pm'); yourself)); add: (#id->#'bfabd530-2b5e-c74c-b43f-4b3b4d090d46'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)