steps
step3342a24ee4eda64f980abc8e7c4674e4
	<step>

	^ ((Dictionary new) add: (#definition->#'3f2640f2-b131-9d46-82fd-e7424438668c'); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->6300); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'21 May 2014 6:11:06 pm'); yourself)); add: (#id->#'3342a24e-e4ed-a64f-980a-bc8e7c4674e4'); add: (#iconCode->'nil'); add: (#next->#'a67a43ef-d74a-bf46-b160-bf00ef047753'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)