steps
step343a2282782f4d4b8e98ab5ca5e0fd36
	<step>

	^ ((Dictionary new) add: (#definition->#'59640e42-b31e-9b4a-9c48-776e3acd55bc'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->2620); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#headerText->'Repository'); yourself)); add: (#id->#'343a2282-782f-4d4b-8e98-ab5ca5e0fd36'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)