steps
stepab2beffcf1ae014ea424a1270d4facd9
	<step>

	^ ((Dictionary new) add: (#definition->#'92d66888-3e33-e449-82ee-fc6d9fdf72e6'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->2510); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#headerText->'Object'); yourself)); add: (#id->#'ab2beffc-f1ae-014e-a424-a1270d4facd9'); add: (#iconCode->'nil'); add: (#next->#'8d3e35af-10d4-a346-9157-f3ad76331d4d'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)