steps
stepb732f87518c21841b5ddbd4145efb573
	<step>

	^ ((Dictionary new) add: (#definition->#'ce710d02-e55b-e748-85cf-67baa093cd49'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->5220); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 February 2014 11:25:12 am'); yourself)); add: (#id->#'b732f875-18c2-1841-b5dd-bd4145efb573'); add: (#iconCode->'nil'); add: (#next->#'317d2dd4-f602-6f42-8e66-0e85184667f6'); add: (#viewDefinition->#listView); add: (#label->'Categories w/ tests'); yourself)