steps
stepded083c33dd2f04a96cf46c7dfe608dc
	<step>

	^ ((Dictionary new) add: (#definition->#'8a26523b-af6c-b44c-b301-5574cb83e74f'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->5950); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'20 February 2014 3:45:20 pm'); add: (#headerText->'Read'); yourself)); add: (#id->#'ded083c3-3dd2-f04a-96cf-46c7dfe608dc'); add: (#iconCode->'nil'); add: (#next->#'14f6246e-2fd7-f947-b063-767bfa454a39'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)