steps
stepsenders
	<step>

	^ ((Dictionary new) add: (#definition->#'fa044112-0baa-3e4d-abc2-c54a247e5236'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->ByteSymbol); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'20 May 2015 12:08:55 pm'); add: (#view->ViTreeViewExtended); add: (#out->Set); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->#'e67a3ef7-7a93-634e-86af-5740774f3bb9'); add: (#label->'Senders'); add: (#iconCode->'nil'); add: (#id->#senders); add: (#isReference->false); add: (#viewDefinition->nil); yourself)