steps
step263f43b53e25214b93bef88d5ecf84b5
	<step>

	^ ((Dictionary new) add: (#definition->#'77f98485-09d8-e34c-bb69-a66a7a0d4a45'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->4010); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#defaultProperties); yourself)); add: (#id->#'263f43b5-3e25-214b-93be-f88d5ecf84b5'); add: (#iconCode->'ViEclipseIcons breakpointViewIcon'); add: (#next->#'829e7d5e-2892-544a-a015-d5efe0983785'); add: (#viewDefinition->#tableView); add: (#label->'Breakpoints'); yourself)