steps
stepb44be5e8ba080744812e8f9104bc951f
	<step>

	^ ((Dictionary new) add: (#definition->#'eaacc8b2-4e11-bb4c-ab2b-7aa0583b7467'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->4870); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'6 September 2013 8:27:11 pm'); add: (#copyOfStep->#updateDefinitions); yourself)); add: (#id->#'b44be5e8-ba08-0744-812e-8f9104bc951f'); add: (#iconCode->'nil'); add: (#next->#'c0cac2e3-ab77-904f-a0ed-936a31a423ea'); add: (#viewDefinition->#treeViewExtended); add: (#label->nil); yourself)