steps
stepfa4cb8bff5a3134c8ce140866732e786
	<step>

	^ ((Dictionary new) add: (#definition->#'740c7d8f-097a-4043-b903-fe5818cbf7b7'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->4610); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'3 January 2014 3:44:19 pm'); yourself)); add: (#id->#'fa4cb8bf-f5a3-134c-8ce1-40866732e786'); add: (#iconCode->'nil'); add: (#next->#'2e490b12-bdf7-7341-b907-18df5b218b85'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)