steps
step3f2ccc8f3fd62243b5e41a2f686ed9bc
	<step>

	^ ((Dictionary new) add: (#definition->#'9b0b0af6-2af2-9d44-a8d0-acb6157978ac'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->5830); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'24 February 2014 10:52:06 am'); yourself)); add: (#id->#'3f2ccc8f-3fd6-2243-b5e4-1a2f686ed9bc'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#textView); add: (#label->'Decompile w/ temps'); yourself)