steps
stepfb419e86ae99874683208ef4c8c7e6d2
	<step>

	^ ((Dictionary new) add: (#definition->#'a048b1ae-2042-5848-a30a-57a958be6864'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->1040); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'6 September 2013 9:10:21 pm'); add: (#copyOfStep->#'fb419e86-ae99-8746-8320-8ef4c8c7e6d2'); yourself)); add: (#id->#'fb419e86-ae99-8746-8320-8ef4c8c7e6d2'); add: (#iconCode->'nil'); add: (#next->#'e81669ed-ebe0-c84e-95e7-7ac5889d8779'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)