steps
stepf4f3c4ff456b3a46a1ae22320975be38
	<step>

	^ ((Dictionary new) add: (#definition->#'a66f00c9-22cb-0a48-a223-d73699b16746'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->3930); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 September 2013 1:08:17 pm'); add: (#headerText->'Type'); yourself)); add: (#id->#'f4f3c4ff-456b-3a46-a1ae-22320975be38'); add: (#iconCode->'nil'); add: (#next->#'0d821eec-f78f-d44e-80df-96d6b534a947'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)