steps
stepc67f97849909ad419da597b166608217
	<step>

	^ ((Dictionary new) add: (#definition->#'fe8f5044-ec69-a14b-9b35-29325b9ddcc8'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->6400); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'5 June 2014 4:59:33 pm'); yourself)); add: (#id->#'c67f9784-9909-ad41-9da5-97b166608217'); add: (#iconCode->'nil'); add: (#next->#'069180ba-532d-a840-b133-13495d451f74'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)