steps
step458cbad93001ab4684584bb4c3232229
	<step>

	^ ((Dictionary new) add: (#definition->#'93525b3f-5fde-bb4c-ad94-1c2c3a53fd53'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->3590); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'15 September 2013 5:47:16 pm'); yourself)); add: (#id->#'458cbad9-3001-ab46-8458-4bb4c3232229'); add: (#iconCode->'nil'); add: (#next->#'c17a5204-307f-044b-b784-5a13673d0684'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)