steps
stepd423159711476f428714146585f297d8
	<step>

	^ ((Dictionary new) add: (#definition->#'74d42c6d-fa57-e44c-958d-da199a3de398'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->6000); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'20 February 2014 6:23 pm'); add: (#headerText->'Class'); yourself)); add: (#id->#'d4231597-1147-6f42-8714-146585f297d8'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)