steps
step8579d16a7cedf746893390568d7c97e0
	<step>

	^ ((Dictionary new) add: (#definition->#'ad1b51e5-029d-e247-bbb0-af3f31d87bd0'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->#'000000'); add: (#creationTimeStamp->'18 September 2013 9:31:08 am'); add: (#creationAuthor->'mt'); add: (#priority->3630); add: (#headerText->'2'); yourself)); add: (#id->#'8579d16a-7ced-f746-8933-90568d7c97e0'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)