steps
step962950ed4ad4244b9e1b512547f2422f
	<step>

	^ ((Dictionary new) add: (#definition->#iconAndLabel); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->2140); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#headerText->'Classes'); yourself)); add: (#id->#'962950ed-4ad4-244b-9e1b-512547f2422f'); add: (#iconCode->'nil'); add: (#next->#'c9ff51f8-97e3-cf46-ba3f-4d71325c942d'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)