steps
step19536a1753f2a54490d173c5acc3cb61
	<step>

	^ ((Dictionary new) add: (#definition->#iconAndLabel); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->2060); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'19536a17-53f2-a544-90d1-73c5acc3cb61'); add: (#iconCode->'nil'); add: (#next->#'0aef5c3f-5e83-9a4f-8a0b-9fd4ca3e46f4'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)