steps
step82277b8f15e6124f96d40a482e6e0aab
	<step>

	^ ((Dictionary new) add: (#definition->#'d681b31e-f0fa-9142-9339-56de9318a643'); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->3750); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 September 2013 6:14:18 pm'); yourself)); add: (#id->#'82277b8f-15e6-124f-96d4-0a482e6e0aab'); add: (#iconCode->'nil'); add: (#next->#'3949844d-11c6-dd41-b185-b338c3ca4dac'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)