steps
step3cce12f6e3d55b4082faff0f97f9844c
	<step>

	^ ((Dictionary new) add: (#definition->#'e0ddacbc-8104-ef48-a6ce-6ea24c435edc'); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->1080); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'3cce12f6-e3d5-5b40-82fa-ff0f97f9844c'); add: (#iconCode->'nil'); add: (#next->#'d45b0a75-2488-2c43-939b-ec29c77353af'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)