steps
step42ed5d046483c94482c80339789652e4
	<step>

	^ ((Dictionary new) add: (#definition->#'452e9359-82a2-3f43-94fe-c108dfa3fef0'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->690); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'42ed5d04-6483-c944-82c8-0339789652e4'); add: (#iconCode->'UiFugueIcons priceTagExclamationIcon'); add: (#next->#'24f23db6-299d-cc46-bb92-693cb90073d6'); add: (#viewDefinition->#treeView); add: (#label->'Unclassified methods'); yourself)