steps
stepbb553ae0c81d4641964f7f27055d9c15
	<step>

	^ ((Dictionary new) add: (#definition->#'f9974083-86d5-d54f-9ee0-ba85d5b22720'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#hAlignment->#right); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#priority->4550); add: (#copyOfStep->#'85478cdc-dec7-5648-b9af-bbf1c6a6d389'); add: (#headerText->'Size'); yourself)); add: (#id->#'bb553ae0-c81d-4641-964f-7f27055d9c15'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)