steps
step6094f78a9d34d8448e98bc414b414eb2
	<step>

	^ ((Dictionary new) add: (#definition->#'38b1fcda-ea44-fc4b-acfc-118dc0d54db5'); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->4600); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'3 January 2014 3:41:26 pm'); yourself)); add: (#id->#'6094f78a-9d34-d844-8e98-bc414b414eb2'); add: (#iconCode->'nil'); add: (#next->#'164491a2-978d-5d4e-8931-03fff9ded75e'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)