steps
stepextendedProperties
	<step>

	^ ((Dictionary new) add: (#definition->#iconAndLabel); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->610); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#defaultProperties); yourself)); add: (#id->#extendedProperties); add: (#iconCode->'nil'); add: (#next->#'d0751873-113e-5342-a056-84f838b9df4b'); add: (#label->nil); yourself)