steps
stepgroups
	<step>

	^ ((Dictionary new) add: (#definition->#'1c6c47fd-f9bb-084a-9266-60bc0c3608bf'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->((Array new: 2) at: 1 put: Object; at: 2 put: Object; yourself)); add: (#creationAuthor->'mt'); add: (#view->ViTreeViewExtended); add: (#creationTimeStamp->'12 May 2015 4:36:46 pm'); add: (#copyOf->#groups); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->#'1969ce03-4b3d-cd44-a47f-8a50c1ec3a4b'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#groups); add: (#isReference->false); yourself)