steps
step5866e81bba191a42bcba6b513172dc16
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsByName); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->2040); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'5866e81b-ba19-1a42-bcba-6b513172dc16'); add: (#iconCode->'nil'); add: (#next->#'97ad3fc7-6ae6-8145-a279-4414ebdd6804'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)