steps
stepa0dd65c0687c174a9c11369b8badfa15
	<step>

	^ ((Dictionary new) add: (#definition->#'6cc037e3-6bf3-f24e-bc65-d7b765664a5d'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->5580); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 February 2014 11:57:29 am'); yourself)); add: (#id->#'a0dd65c0-687c-174a-9c11-369b8badfa15'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)