steps
stepc50d0c14b3ebcf479e8a7ba23cb2c4dd
	<step>

	^ ((Dictionary new) add: (#definition->#'6791d9d6-2faf-3448-8e22-0aa4c948acdc'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->5200); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 February 2014 8:36:52 am'); yourself)); add: (#id->#'c50d0c14-b3eb-cf47-9e8a-7ba23cb2c4dd'); add: (#iconCode->'nil'); add: (#next->#'46b904bc-22e5-a84a-8f30-894b0f7df352'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)