steps
stepacc3ad3129c9cd458ccce801aaadd858
	<step>

	^ ((Dictionary new) add: (#definition->#'f6032f7a-baab-7446-9764-e0f1e97f6d34'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->3910); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 September 2013 7:46:49 pm'); yourself)); add: (#id->#'acc3ad31-29c9-cd45-8ccc-e801aaadd858'); add: (#iconCode->'nil'); add: (#next->#'cdbe8071-be1b-984e-b62a-2c1b721153c0'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)