steps
stepca50309f543bc84583d0749a6f7cbb2e
	<step>

	^ ((Dictionary new) add: (#definition->#'c7130d64-9f4e-7247-bd60-9214f1d0f522'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationAuthor->'mt'); add: (#priority->3180); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'ca50309f-543b-c845-83d0-749a6f7cbb2e'); add: (#iconCode->'nil'); add: (#next->#'fdb69e0a-57ea-394a-a74a-b986817dca93'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)