steps
stepa0430b669a7df044be09b17780bf171f
	<step>

	^ ((Dictionary new) add: (#definition->#iconAndLabel); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->4810); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#defaultProperties); yourself)); add: (#id->#'a0430b66-9a7d-f044-be09-b17780bf171f'); add: (#iconCode->'nil'); add: (#next->#'80d8228d-c6ed-1744-8301-762c72d90211'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)