steps
step8e0086dce5def948b5b5b355fc568037
	<step>

	^ ((Dictionary new) add: (#definition->#'eeac0bd5-d8d9-2f4f-ac60-7fd29bee41b8'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'21 October 2014 3:25:39 pm'); yourself)); add: (#isProperty->false); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'8e0086dc-e5de-f948-b5b5-b355fc568037'); add: (#viewDefinition->#treePlain); yourself)