steps
stepe89d0b5ae4fe584baed496f20385b05c
	<step>

	^ ((Dictionary new) add: (#definition->#'ae87be09-3c23-5743-bab5-e2d9aae7bdfb'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->6200); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'5 June 2014 4:52:37 pm'); yourself)); add: (#id->#'e89d0b5a-e4fe-584b-aed4-96f20385b05c'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)