steps
step201c9e15bd34ba46bf107b546e1fa6f8
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsAsStrings); add: (#class->ViQueryGroupSortStep); add: (#properties->((Dictionary new) add: (#priority->1530); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'201c9e15-bd34-ba46-bf10-7b546e1fa6f8'); add: (#iconCode->'nil'); add: (#next->#'d1ab46b3-df50-534c-b593-d1e6683fe045'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)