steps
step5a2edad8c307144aa4b6dfdddd2c429d
	<step>

	^ ((Dictionary new) add: (#definition->#'ca63f41a-42ba-4a4c-8fc3-39f3fd8428b2'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->1150); add: (#headerText->'Origin'); yourself)); add: (#id->#'5a2edad8-c307-144a-a4b6-dfdddd2c429d'); add: (#iconCode->'nil'); add: (#next->#'e5bd3f6c-f63f-b148-89bc-82784354babd'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)