steps
step044ec24710c99946a6bc5044f6bc4a4d
	<step>

	^ ((Dictionary new) add: (#definition->#'982afa1e-5280-254c-b404-f3f9ba5ff8c6'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->850); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'10 February 2014 4:49:24 pm'); yourself)); add: (#id->#'044ec247-10c9-9946-a6bc-5044f6bc4a4d'); add: (#iconCode->'nil'); add: (#next->#'0c69c004-a3f9-134e-8ba6-eafca2418592'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)