steps
stepba683fae91bbed4c985f8c12b3504e50
	<step>

	^ ((Dictionary new) add: (#definition->#'bdf7d30c-9546-6b4e-8111-e1ca31bd5be9'); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->1580); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'ba683fae-91bb-ed4c-985f-8c12b3504e50'); add: (#iconCode->'nil'); add: (#next->#'91982915-045f-1f44-ab9b-723d7bbdf298'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)