steps
step73012cd964579649bb163f77f5dea0d2
	<step>

	^ ((Dictionary new) add: (#definition->#'e4592bf3-ca81-2446-be75-29fee8fe6683'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 4:21:57 pm'); add: (#creationAuthor->'mt'); add: (#priority->3230); add: (#headerText->'Bar'); yourself)); add: (#id->#'73012cd9-6457-9649-bb16-3f77f5dea0d2'); add: (#iconCode->'nil'); add: (#next->#'2ae8b5e0-925f-904b-82ab-2fe17cce67ab'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)