steps
step070104b018c47348bdce375fa5dbc93c
	<step>

	^ ((Dictionary new) add: (#definition->#'6615e26b-6ca7-2a4e-b214-c4e0bc0ca8f3'); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->2650); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'070104b0-18c4-7348-bdce-375fa5dbc93c'); add: (#iconCode->'nil'); add: (#next->#'252b6d01-f490-2640-a5fc-6b968dc12be4'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)