steps
step3723f748fad3d4468f95d2d495e9a9cc
	<step>

	^ ((Dictionary new) add: (#definition->#'e8978022-c037-0a4b-9e33-a81e1e562382'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationAuthor->'mt'); add: (#priority->1380); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'3723f748-fad3-d446-8f95-d2d495e9a9cc'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)