steps
step4c25e30468cbd3499eea97514506a5aa
	<step>

	^ ((Dictionary new) add: (#definition->#'3994d384-d109-e44e-8b92-9a64780ce685'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->4970); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'3 February 2014 5:06:28 pm'); yourself)); add: (#id->#'4c25e304-68cb-d349-9eea-97514506a5aa'); add: (#iconCode->'nil'); add: (#next->#'eb2eeadd-07f1-b046-a798-7eeff5e3eeda'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)