steps
step14f6246e2fd7f947b063767bfa454a39
	<step>

	^ ((Dictionary new) add: (#definition->#'27cdfb02-cbbd-0443-b356-ea5e023a3a75'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->5960); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'21 February 2014 8:52:10 am'); add: (#headerText->'Setup'); yourself)); add: (#id->#'14f6246e-2fd7-f947-b063-767bfa454a39'); add: (#iconCode->'nil'); add: (#next->#'75851276-07a7-8440-8574-cc2965065a02'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)