steps
step989369d4032d1d49adaeb70b2f36ea1e
	<step>

	^ ((Dictionary new) add: (#definition->#'58a553a7-f441-2a48-bb8c-94162c137fd8'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->5880); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'24 February 2014 11:02:55 am'); add: (#copyOfStep->#'6a945c46-e2f2-ac41-8b3e-dadc1328d8a3'); yourself)); add: (#id->#'989369d4-032d-1d49-adae-b70b2f36ea1e'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#textView); add: (#label->'Diff w/ pretty print'); yourself)