steps
stepoutline
	<step>

	^ ((Dictionary new) add: (#definition->#'c7f13eaf-02b3-7046-8b08-c7d1a5a911dd'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->40); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#'bec0a4ef-c091-a844-88ef-be4ea489648e'); yourself)); add: (#id->#outline); add: (#iconCode->'nil'); add: (#next->#'b9b1a3c9-cfc9-ea4b-a67b-6a2ce4d34918'); add: (#viewDefinition->#treeViewExtended); add: (#label->'Outline'); yourself)