steps
step8c0c7c2fde5c284d9d9a2d20961a1db5
	<step>

	^ ((Dictionary new) add: (#definition->#'baae0367-2eb9-2745-b6af-c747b95925ac'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->160); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'8c0c7c2f-de5c-284d-9d9a-2d20961a1db5'); add: (#iconCode->'nil'); add: (#next->#'68eda666-8d64-144e-b349-065974fd20f2'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)