steps
stepb193f637d3a4cb4b9b3e94c7b7ba29e9
	<step>

	^ ((Dictionary new) add: (#definition->#'48f0bb0f-b73d-4d4a-89a4-d68e5f89f019'); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->5070); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'11 February 2014 10:25:52 am'); yourself)); add: (#id->#'b193f637-d3a4-cb4b-9b3e-94c7b7ba29e9'); add: (#iconCode->'nil'); add: (#next->#'ab4af50f-105f-424d-95d1-36bfd2f47ad3'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)