steps
stepdfb2af53c012e14aae231ee9009c0034
	<step>

	^ ((Dictionary new) add: (#definition->#'c3ea1545-f452-484c-8c97-8118ee648839'); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->3060); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'dfb2af53-c012-e14a-ae23-1ee9009c0034'); add: (#iconCode->'nil'); add: (#next->#'9cdc94fa-da62-e042-93a1-00f1773d45fc'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)