steps
step969d8eb99007b041b58ea1fd25a2d732
	<step>

	^ ((Dictionary new) add: (#definition->#'335dc170-fec4-de42-a955-63c658bd56ee'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'20 May 2015 2:36:10 pm'); add: (#copyOf->#'43dad8cd-aa5a-f540-bf91-5c505349e324'); add: (#isNew->false); yourself)); add: (#isProperty->true); add: (#next->#'4b56b921-6888-f246-8e50-b89ba30bbd13'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'969d8eb9-9007-b041-b58e-a1fd25a2d732'); add: (#isReference->false); yourself)