steps
step36a4ecd2893b604c919984cbfbffa8d4
	<step>

	^ ((Dictionary new) add: (#definition->#'07203f12-f1b6-9746-9884-0b9e8f1a4f6b'); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->6540); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#'92eb4914-ce3c-1f4f-b813-4bd8cf3c75a6'); yourself)); add: (#id->#'36a4ecd2-893b-604c-9199-84cbfbffa8d4'); add: (#iconCode->'nil'); add: (#next->#'40631e0e-1210-ba40-b78a-f96a2cefc0b0'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)