steps
step47204d819a245149ad0701d582da03b4
	<step>

	^ ((Dictionary new) add: (#definition->#'eb2e0d5a-634c-fa40-9782-0e28013862b5'); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->4270); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'8 November 2013 4:40:32 pm'); yourself)); add: (#id->#'47204d81-9a24-5149-ad07-01d582da03b4'); add: (#iconCode->'nil'); add: (#next->#'3554a784-6c63-324c-aeca-db77b530eb36'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)