steps
step90bb3b19d2be164ea30683db53cee32e
	<step>

	^ ((Dictionary new) add: (#definition->#'6be69cd7-f2c0-c742-9f95-84b0ab6e803d'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->5490); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'7 November 2013 11:04:24 am'); add: (#copyOfStep->#'ecc9e9ca-455e-c148-8762-1714a939cbe9'); yourself)); add: (#id->#'90bb3b19-d2be-164e-a306-83db53cee32e'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)