steps
step5ec063434180cf4da211f78d46a2112e
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsByName); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->4530); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#'164491a2-978d-5d4e-8931-03fff9ded75e'); yourself)); add: (#id->#'5ec06343-4180-cf4d-a211-f78d46a2112e'); add: (#iconCode->'nil'); add: (#next->#'55d465d1-f7d0-c04f-a61b-099f2ae6b6b9'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)