steps
step519d344ef0312a438e4234a9f07b61f9
	<step>

	^ ((Dictionary new) add: (#definition->#iconAndLabel); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->1600); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#headerText->'Versions'); yourself)); add: (#id->#'519d344e-f031-2a43-8e42-34a9f07b61f9'); add: (#iconCode->'nil'); add: (#next->#'047d9a97-10d0-6c45-8228-c223ea969775'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)