steps
step874bd7694b84dd459644c5e3a23f29de
	<step>

	^ ((Dictionary new) add: (#definition->#'06e06871-2a40-0646-9096-16438991067d'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->6610); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'23 July 2014 1:18:19 pm'); yourself)); add: (#id->#'874bd769-4b84-dd45-9644-c5e3a23f29de'); add: (#iconCode->'nil'); add: (#next->#'4a0e6861-42f9-6642-808b-5c122c31721a'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)