steps
step8eec0dd86d7cd54f8d45ff176d005f1b
	<step>

	^ ((Dictionary new) add: (#definition->#'f88512ad-81dd-ac4c-8e82-ff004696fed6'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 September 2013 6:51:45 pm'); add: (#priority->3870); add: (#copyOfStep->#'6dcf4d7c-0337-da43-85f9-526e23934ee9'); add: (#headerText->'Type'); yourself)); add: (#id->#'8eec0dd8-6d7c-d54f-8d45-ff176d005f1b'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)