steps
stepe578a963cfd45641b9426e1eef180ad2
	<step>

	^ ((Dictionary new) add: (#definition->#'c63e57c9-2b56-ab49-895d-f8f9a22907a6'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->6030); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'2 March 2014 10:13:57 am'); yourself)); add: (#id->#'e578a963-cfd4-5641-b942-6e1eef180ad2'); add: (#iconCode->'nil'); add: (#next->#'37989d23-0602-ed44-ad37-440cccc8d6d9'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)