steps
step265f5360f208fe42b68ae42b58b5ff93
	<step>

	^ ((Dictionary new) add: (#definition->#iconAndLabel); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->1910); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#headerText->'Methods'); yourself)); add: (#id->#'265f5360-f208-fe42-b68a-e42b58b5ff93'); add: (#iconCode->'nil'); add: (#next->#'38cdc208-e708-0b47-b9d5-d9fb2a99fce1'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)