steps
step82908026d4e4d04783ee741e175314a3
	<step>

	^ ((Dictionary new) add: (#definition->#'946d491e-650f-4847-95e2-69b1d7757dae'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->1820); add: (#headerText->'Timestamp'); yourself)); add: (#id->#'82908026-d4e4-d047-83ee-741e175314a3'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)