steps
step8290f350f0112348a5277cfb1d2a5a45
	<step>

	^ ((Dictionary new) add: (#definition->#'d0916bc9-7082-ad48-b568-cf6594d4730e'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->2600); add: (#headerText->'Origin'); yourself)); add: (#id->#'8290f350-f011-2348-a527-7cfb1d2a5a45'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)