steps
stepedcd89de8046a844bfdec7aca99dba50
	<step>

	^ ((Dictionary new) add: (#definition->#'6f431f2f-fd85-3841-a679-a7cb8348ba6f'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->90); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'edcd89de-8046-a844-bfde-c7aca99dba50'); add: (#iconCode->'UiFugueIcons categoryIcon'); add: (#next->#'e9f4b617-ab3a-cd41-9a5b-9f547aa04c9d'); add: (#viewDefinition->#treeView); add: (#label->'Categories'); yourself)