steps
stepd9976b61dc4ebf4aa4a6a44c2728904d
	<step>

	^ ((Dictionary new) add: (#definition->#toplevelClasses); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->3970); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 September 2013 3:08:45 pm'); yourself)); add: (#id->#'d9976b61-dc4e-bf4a-a4a6-a44c2728904d'); add: (#iconCode->'nil'); add: (#next->#'688b9e53-cc30-9341-a368-54f6c47e402c'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)