steps
step92eb4914ce3c1f4fb8134bd8cf3c75a6
	<step>

	^ ((Dictionary new) add: (#definition->#'07203f12-f1b6-9746-9884-0b9e8f1a4f6b'); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->1270); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#'92eb4914-ce3c-1f4f-b813-4bd8cf3c75a6'); yourself)); add: (#id->#'92eb4914-ce3c-1f4f-b813-4bd8cf3c75a6'); add: (#iconCode->'nil'); add: (#next->#'2fca6209-9c2d-c644-823a-acf2909bad0f'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)