steps
step6eab0da05a97d94d84a65f930edbbd06
	<step>

	^ ((Dictionary new) add: (#definition->#'2d64642b-996d-4549-b799-afb46cd159ae'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->6320); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'21 May 2014 2:37:53 pm'); yourself)); add: (#id->#'6eab0da0-5a97-d94d-84a6-5f930edbbd06'); add: (#iconCode->'nil'); add: (#next->#'244a371f-7663-214d-932d-5512b30c3e35'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)