steps
stepd7717fb24d049a42a74d4a8e8f3a891c
	<step>

	^ ((Dictionary new) add: (#definition->#'3835be18-aea4-124e-a7f0-7455e1534b44'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->5280); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'14 February 2014 11:06:30 am'); add: (#headerText->#D); yourself)); add: (#id->#'d7717fb2-4d04-9a42-a74d-4a8e8f3a891c'); add: (#iconCode->'nil'); add: (#next->#'e45648f8-4fef-f343-8972-cbb555789355'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)