steps
stepe505710cf722e34ea85ef914106ea5cb
	<step>

	^ ((Dictionary new) add: (#definition->#'f5fcb65a-ce61-9f41-be89-945ee8be0d1b'); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->1930); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'e505710c-f722-e34e-a85e-f914106ea5cb'); add: (#iconCode->'nil'); add: (#next->#'b7982ee7-7baa-6b48-8f2a-1bbbf9c96888'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)