steps
stepe63568e85926f6409527117c4e70e841
	<step>

	^ ((Dictionary new) add: (#definition->#'9f1a0cb8-5c03-5548-9ce5-2268a2a18cd6'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->960); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'3 September 2013 1:57:12 pm'); add: (#copyOfStep->#'e63568e8-5926-f640-9527-117c4e70e841'); yourself)); add: (#id->#'e63568e8-5926-f640-9527-117c4e70e841'); add: (#iconCode->'nil'); add: (#next->#'7badd432-90e1-ec42-96d7-6085b40a0871'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)