steps
step66e483d253129349bb3e4742bac11240
	<step>

	^ ((Dictionary new) add: (#definition->#'e80f2ecd-de69-4d47-a05a-3c9164d1d0c1'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->2280); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'66e483d2-5312-9349-bb3e-4742bac11240'); add: (#iconCode->'nil'); add: (#next->#'07540f0c-6cda-d44e-b272-9d619e7cdcff'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)