steps
steporderedSteps
	<step>

	^ ((Dictionary new) add: (#definition->#'412dc831-637b-4b41-9ed1-e8eb3db97062'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->390); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'3 September 2013 3:26:55 pm'); yourself)); add: (#id->#orderedSteps); add: (#iconCode->'UiFugueIcons scriptMediumIcon'); add: (#next->#'7fd41212-698d-ee43-8d8f-0dc8fb2b9a9e'); add: (#viewDefinition->#treeView); add: (#label->'Ordered Queries'); yourself)