steps
step6900ffdc84145f4abab99602bbf21fae
	<step>

	^ ((Dictionary new) add: (#definition->#'29f516c5-189c-2544-bd3f-1417d9eea5fe'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->5680); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 February 2014 4:31:24 pm'); yourself)); add: (#id->#'6900ffdc-8414-5f4a-bab9-9602bbf21fae'); add: (#iconCode->'nil'); add: (#next->#'a7590d1b-e0ee-6340-a3d4-76e67ae30cfa'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)