steps
stepb234af3a9e84dd4a935c604a312f353f
	<step>

	^ ((Dictionary new) add: (#definition->#'2f28efd9-bc15-164f-8584-e049b306ecc8'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->210); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'b234af3a-9e84-dd4a-935c-604a312f353f'); add: (#iconCode->'UiSilkIcons timeIcon'); add: (#next->#'4ee8e2d8-9bc6-7645-b541-f743df30fe9d'); add: (#viewDefinition->#treeView); add: (#label->'Method Versions'); yourself)