steps
step22529fa52b897d44835de28f42d667a0
	<step>

	^ ((Dictionary new) add: (#definition->#'2f31c995-3a2b-9a41-8c9a-281f6d2a3ffa'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->1440); add: (#headerText->'Class'); yourself)); add: (#id->#'22529fa5-2b89-7d44-835d-e28f42d667a0'); add: (#iconCode->'nil'); add: (#next->#'bfabd530-2b5e-c74c-b43f-4b3b4d090d46'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)