steps
stepc753d7000c1c024ca7d168ffe3bc4166
	<step>

	^ ((Dictionary new) add: (#definition->#'cfeaece5-e6ec-3a44-9e8b-e84b31e5ed0e'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->6150); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'11 February 2014 1:01:49 pm'); add: (#copyOfStep->#identity); yourself)); add: (#id->#'c753d700-0c1c-024c-a7d1-68ffe3bc4166'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#textView); add: (#label->'Code'); yourself)