steps
step2cd2a1cf90c5db48b1a2d74f204ecacf
	<step>

	^ ((Dictionary new) add: (#definition->#'55c88de4-6025-784a-be92-e1e5dc17e0e4'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->360); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'2cd2a1cf-90c5-db48-b1a2-d74f204ecacf'); add: (#iconCode->'nil'); add: (#next->#'cc9afa06-dafe-3f47-8613-5b6306c75ac4'); add: (#viewDefinition->#treeView); add: (#label->'All superclasses'); yourself)