steps
step3dcd19258f140c4ca86106178920b36d
	<step>

	^ ((Dictionary new) add: (#definition->#'86d28519-df3a-904a-b8e7-fb583d88b992'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->5120); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'11 February 2014 1:01:49 pm'); add: (#copyOfStep->#identity); yourself)); add: (#id->#'3dcd1925-8f14-0c4c-a861-06178920b36d'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#artifactsView); add: (#label->'Pretty printed methods'); yourself)