steps
step07540f0c6cdad44eb2729d619e7cdcff
	<step>

	^ ((Dictionary new) add: (#definition->#'595f22af-5b39-df47-82fc-bfe9343c2c57'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->2250); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#headerText->'Implementor'); yourself)); add: (#id->#'07540f0c-6cda-d44e-b272-9d619e7cdcff'); add: (#iconCode->'nil'); add: (#next->#'635ee7ee-dfa7-1342-a9c2-f1e54ca14660'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)