steps
stepf8f2564d0b66d6459646191f5736dcef
	<step>

	^ ((Dictionary new) add: (#definition->#'288a24da-71d5-4941-a763-480ec269c6ea'); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->2760); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'f8f2564d-0b66-d645-9646-191f5736dcef'); add: (#iconCode->'nil'); add: (#next->#'003ae1fe-6781-f943-9e4d-c1fa5bab39b0'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)