steps
stepe689b65927f30f4a9412ab39abc2b63e
	<step>

	^ ((Dictionary new) add: (#definition->#'c638cccb-0c1e-2f45-9c0c-ff22d69ec199'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->1100); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#headerText->'Name'); yourself)); add: (#id->#'e689b659-27f3-0f4a-9412-ab39abc2b63e'); add: (#iconCode->'nil'); add: (#next->#'0de86151-e883-cf4c-9668-960b4466822e'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)