steps
stepd61e908712152d4eb336316c41064b72
	<step>

	^ ((Dictionary new) add: (#definition->#'7b526e28-633d-384d-b578-5dd745b36160'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->6650); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'23 July 2014 1:18:56 pm'); yourself)); add: (#id->#'d61e9087-1215-2d4e-b336-316c41064b72'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)