steps
step358482e02cf1e948a6570a354613e3ad
	<step>

	^ ((Dictionary new) add: (#definition->#'2ef099b5-ca0a-3a4e-934e-823156b061a9'); add: (#class->ViQueryGroupSortStep); add: (#properties->((Dictionary new) add: (#priority->2500); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'358482e0-2cf1-e948-a657-0a354613e3ad'); add: (#iconCode->'nil'); add: (#next->#'ab2beffc-f1ae-014e-a424-a1270d4facd9'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)