steps
step2fdb319c765a1a43863e792e14de2c1e
	<step>

	^ ((Dictionary new) add: (#definition->#'a9a2b6a9-705b-9347-bad3-3abd6d56975c'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->4290); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'12 November 2013 5:16:28 pm'); yourself)); add: (#id->#'2fdb319c-765a-1a43-863e-792e14de2c1e'); add: (#iconCode->'nil'); add: (#next->#'e1378983-156c-1d4a-88b1-eae6654e7fb0'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)