steps
step31f74b61d090a44399cc182ef8e9b039
	<step>

	^ ((Dictionary new) add: (#definition->#'92d66888-3e33-e449-82ee-fc6d9fdf72e6'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#000000'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->2890); add: (#headerText->'Value'); yourself)); add: (#id->#'31f74b61-d090-a443-99cc-182ef8e9b039'); add: (#iconCode->'nil'); add: (#next->#'0da6c0f0-1c3d-3e41-a670-8bc5919f788a'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)