steps
stepe847db70263a3b49a7929d80a42da426
	<step>

	^ ((Dictionary new) add: (#definition->#category); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->3520); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 September 2013 7:52:25 pm'); yourself)); add: (#id->#'e847db70-263a-3b49-a792-9d80a42da426'); add: (#iconCode->'nil'); add: (#next->#'2c2a1c1a-775d-6244-a1e8-34f737246a95'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)