steps
step07d417c7f8719c41873d4413efec391d
	<step>

	^ ((Dictionary new) add: (#definition->#'6791d9d6-2faf-3448-8e22-0aa4c948acdc'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->5190); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 February 2014 10:20:56 am'); yourself)); add: (#id->#'07d417c7-f871-9c41-873d-4413efec391d'); add: (#iconCode->'nil'); add: (#next->#'32237325-6bef-9048-a0d3-5e1f4a3e64ed'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)