steps
step62ec2d2dbc826d42a3177bfe67ea01bb
	<step>

	^ ((Dictionary new) add: (#definition->#'2abd92ca-7b65-5642-a12a-f91de89561d0'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->780); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#defaultProperties); yourself)); add: (#id->#'62ec2d2d-bc82-6d42-a317-7bfe67ea01bb'); add: (#iconCode->'nil'); add: (#next->#'ee936399-1409-634c-81ff-0389658bb3ce'); add: (#viewDefinition->#textView); add: (#label->'Load Picture'); yourself)