steps
stepaa3ec915c019e9418b9bf9baa09fd69a
	<step>

	^ ((Dictionary new) add: (#definition->#'a5066753-64c1-b04f-b645-d66d41db274d'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->5540); add: (#view->#text); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 February 2014 10:22:16 am'); yourself)); add: (#id->#'aa3ec915-c019-e941-8b9b-f9baa09fd69a'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)