steps
stepa00864aca9da7b4c856684d8a849fe5e
	<step>

	^ ((Dictionary new) add: (#definition->#'ca489b64-d3e0-c343-b5e1-c28e5999d55a'); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->1880); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'a00864ac-a9da-7b4c-8566-84d8a849fe5e'); add: (#iconCode->'nil'); add: (#next->#'4e23cd6b-405e-e94f-8485-22afd117448c'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)