steps
stepd89cc75273e40742ac29eb770d5d8fc5
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsBySelector); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->1340); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'d89cc752-73e4-0742-ac29-eb770d5d8fc5'); add: (#iconCode->'nil'); add: (#next->#'1d58d23a-244c-b84e-8448-52a3acfb1544'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)