steps
step26f3a2b2f47a644bac5f159e2365b955
	<step>

	^ ((Dictionary new) add: (#definition->#iconAndLabel); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->3600); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#'26f3a2b2-f47a-644b-ac5f-159e2365b955'); yourself)); add: (#id->#'26f3a2b2-f47a-644b-ac5f-159e2365b955'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)