steps
step45fb3a3839dc2144a747a51f5e49f729
	<step>

	^ ((Dictionary new) add: (#definition->#'8a71e074-1c14-8145-9e08-3c3261d5d008'); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->3660); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 September 2013 10:17:33 am'); yourself)); add: (#id->#'45fb3a38-39dc-2144-a747-a51f5e49f729'); add: (#iconCode->'nil'); add: (#next->#'23d4adf1-41b2-9845-aeb2-2b496e4ea663'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)