steps
stepf128659b7f02364dafc1143f418bf135
	<step>

	^ ((Dictionary new) add: (#definition->#'10e4c6d0-30b8-1549-afbb-d936fb6c7a9c'); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->5460); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'7 November 2013 10:51:34 am'); add: (#copyOfStep->#'b9b1a3c9-cfc9-ea4b-a67b-6a2ce4d34918'); yourself)); add: (#id->#'f128659b-7f02-364d-afc1-143f418bf135'); add: (#iconCode->'nil'); add: (#next->#'03a844ab-437b-6c41-8cf9-15f9a8aab212'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)