steps
step72a1887e14c8bb4b8816c1a83b525e41
	<step>

	^ ((Dictionary new) add: (#definition->#'c3876e02-15ba-414a-ae61-c41de8ba4e72'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->340); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'72a1887e-14c8-bb4b-8816-c1a83b525e41'); add: (#iconCode->'UiFugueIcons scriptsTextIcon'); add: (#next->#'4e06ed51-665d-e446-a53c-44763032a14c'); add: (#viewDefinition->#treeView); add: (#label->'Implementors (recursive)'); yourself)