steps
step36f18c66dd991f43b7a8edc44c309ebc
	<step>

	^ ((Dictionary new) add: (#definition->#'48dfdaac-2ace-7f49-9ec6-2cf94bccd64b'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#headerText->'Class'); yourself)); add: (#id->#'36f18c66-dd99-1f43-b7a8-edc44c309ebc'); add: (#iconCode->'nil'); add: (#next->#'cd282363-71fb-f94a-9a4c-49ce99c79f7b'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)