steps
step40560165a4c74042974090e250b56bd7
	<step>

	^ ((Dictionary new) add: (#definition->#'563021ef-44a7-e24e-beb7-6201088a6f24'); add: (#class->ViQueryGroupSortStep); add: (#properties->((Dictionary new) add: (#priority->3460); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 September 2013 7:28:52 pm'); yourself)); add: (#id->#'40560165-a4c7-4042-9740-90e250b56bd7'); add: (#iconCode->'nil'); add: (#next->#'24a9922a-802c-1543-acf7-ff6d8dc30bbf'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)