steps
step39e0739ab359364a9c0fa5b758f8f9c8
	<step>

	^ ((Dictionary new) add: (#definition->#origin); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationAuthor->'mt'); add: (#priority->1240); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'39e0739a-b359-364a-9c0f-a5b758f8f9c8'); add: (#iconCode->'nil'); add: (#next->#'240cc4b3-dcec-8c4e-bbe8-29ff7c118338'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)