steps
step11f5a6a9b26d4742bf5e938ff2e033c1
	<step>

	^ ((Dictionary new) add: (#definition->#'ed772df8-b782-5f49-aca7-191fdb5a5fce'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->5180); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'11 February 2014 1:01:49 pm'); add: (#copyOfStep->#identity); yourself)); add: (#id->#'11f5a6a9-b26d-4742-bf5e-938ff2e033c1'); add: (#iconCode->'nil'); add: (#next->#'07d417c7-f871-9c41-873d-4413efec391d'); add: (#viewDefinition->#multiPane); add: (#label->'Context Inspector'); yourself)