steps
step1e6aa701f25e1844bcd03fbe2c74df42
	<step>

	^ ((Dictionary new) add: (#definition->#'a5bc60d1-63c3-8c42-9039-698a5f637754'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->760); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 September 2013 7:45:26 pm'); yourself)); add: (#id->#'1e6aa701-f25e-1844-bcd0-3fbe2c74df42'); add: (#iconCode->'nil'); add: (#next->#'074a7165-1020-0442-8a76-a2ce9f8ab3e6'); add: (#viewDefinition->#tileView); add: (#label->nil); yourself)