steps
step4cf7f9df0d150d42b7924c26bd39cbe1
	<step>

	^ ((Dictionary new) add: (#definition->#'23cf0ae6-f7f5-794b-8d4d-d25816a58874'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->8400); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'15 November 2014 1:48:33 pm'); yourself)); add: (#id->#'4cf7f9df-0d15-0d42-b792-4c26bd39cbe1'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treePlain); add: (#label->nil); yourself)