steps
step14c2d4d3e9a4a049b9111bd24ba1ee34
	<step>

	^ ((Dictionary new) add: (#definition->#'ef49f0fb-b0d0-3548-9949-13882c7248a3'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'21 October 2014 3:26:15 pm'); yourself)); add: (#isProperty->false); add: (#next->#'8392e394-aff9-2645-be37-3e9da7fa6019'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'14c2d4d3-e9a4-a049-b911-1bd24ba1ee34'); add: (#viewDefinition->#treePlain); yourself)