steps
stepbc34ef9752af6c49b344cdb766681c0c
	<step>

	^ ((Dictionary new) add: (#definition->#'7dd11be7-db09-6d43-bc91-fbc818f50e1e'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->3840); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 September 2013 6:45:44 pm'); add: (#copyOfStep->#'4291e65f-ca68-f04b-bbb8-41cf2734c087'); yourself)); add: (#id->#'bc34ef97-52af-6c49-b344-cdb766681c0c'); add: (#iconCode->'nil'); add: (#next->#'6bb09add-d327-dd4a-bd4b-47d25202dbf7'); add: (#viewDefinition->#tableView); add: (#label->nil); yourself)