steps
stepartifacts
	<step>

	^ ((Dictionary new) add: (#definition->#identity); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#copyOfStep->#identity); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'11 February 2014 1:01:49 pm'); yourself)); add: (#id->#artifacts); add: (#iconCode->'nil'); add: (#next->#'e91a3922-7238-d847-ab9c-4bbd53eece98'); add: (#viewDefinition->#artifactsView); add: (#label->'Artifacts'); yourself)