steps
step6f20da891a7ef64d96a68b4b22691ee4
	<step>

	^ ((Dictionary new) add: (#definition->#methodReferenceToPackageName); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->1520); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'6f20da89-1a7e-f64d-96a6-8b4b22691ee4'); add: (#iconCode->'nil'); add: (#next->#'201c9e15-bd34-ba46-bf10-7b546e1fa6f8'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)