steps
step4a5e36f99a70394aa39bc0891bc2e99b
	<step>

	^ ((Dictionary new) add: (#definition->#'81d4bba3-fa92-5a44-9759-d980ccef208a'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->1870); add: (#headerText->'Protocol'); yourself)); add: (#id->#'4a5e36f9-9a70-394a-a39b-c0891bc2e99b'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)