steps
step8c87a9e9a74c3749b4bab8960612b464
	<step>

	^ ((Dictionary new) add: (#definition->#'524c9479-77b0-664a-87a3-626871241adc'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'1 June 2015 1:44:09 pm'); yourself)); add: (#isProperty->false); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'8c87a9e9-a74c-3749-b4ba-b8960612b464'); add: (#isReference->true); yourself)