steps
stepafb03b2b6810684f853c74918c6c73e3
	<step>

	^ ((Dictionary new) add: (#definition->#'92d66888-3e33-e449-82ee-fc6d9fdf72e6'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->5990); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'20 February 2014 3:44:05 pm'); add: (#headerText->'Selector'); yourself)); add: (#id->#'afb03b2b-6810-684f-853c-74918c6c73e3'); add: (#iconCode->'nil'); add: (#next->#'d4231597-1147-6f42-8714-146585f297d8'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)