steps
step81adf2f92129c5449bc0ab5207f80462
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsAsStrings); add: (#class->ViQueryGroupSortStep); add: (#properties->((Dictionary new) add: (#priority->1360); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'81adf2f9-2129-c544-9bc0-ab5207f80462'); add: (#iconCode->'nil'); add: (#next->#'e84072d2-c593-f549-a93c-d5dbeb2e3b94'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)