steps
step11f0e87814f5b147a1c6e95064e1a62a
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsAsStrings); add: (#class->ViQueryGroupSortStep); add: (#properties->((Dictionary new) add: (#priority->5780); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'20 February 2014 6:30:20 pm'); yourself)); add: (#id->#'11f0e878-14f5-b147-a1c6-e95064e1a62a'); add: (#iconCode->'nil'); add: (#next->#'ded083c3-3dd2-f04a-96cf-46c7dfe608dc'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)