steps
stepbf1af6b68f8af7469c2a1ab4fad1e340
	<step>

	^ ((Dictionary new) add: (#definition->#'a5225250-57d6-8047-aa81-bfc079234e49'); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->1120); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'bf1af6b6-8f8a-f746-9c2a-1ab4fad1e340'); add: (#iconCode->'nil'); add: (#next->#'02594c64-5f16-9449-af33-fb7d5bcdd662'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)