steps
stepfb5f9d4849cf774c921fe9598b74d2c7
	<step>

	^ ((Dictionary new) add: (#definition->#'9242cbac-4797-8d4c-9f3f-8d8dc15a9b9e'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->4330); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'12 November 2013 4:58:54 pm'); yourself)); add: (#id->#'fb5f9d48-49cf-774c-921f-e9598b74d2c7'); add: (#iconCode->'nil'); add: (#next->#'33a2c2ee-bac8-3b4a-842d-faf5586d7042'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)