steps
stepef81aed0ae2d6548904f030b28e12e97
	<step>

	^ ((Dictionary new) add: (#definition->#'642bd6ce-ae5f-4447-9fe4-ba08475a3dbd'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->3800); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 September 2013 7:05:18 pm'); yourself)); add: (#id->#'ef81aed0-ae2d-6548-904f-030b28e12e97'); add: (#iconCode->'nil'); add: (#next->#'cc0ed406-f999-fe49-b8f7-f627deb6cb53'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)