steps
step4a0e686142f96642808b5c122c31721a
	<step>

	^ ((Dictionary new) add: (#definition->#'bab5f2db-8d7a-f64f-a50c-0dd4e0569db6'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->6620); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'23 July 2014 1:19:25 pm'); yourself)); add: (#id->#'4a0e6861-42f9-6642-808b-5c122c31721a'); add: (#iconCode->'nil'); add: (#next->#'651607ab-4429-3e44-b61f-86c177f0d112'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)