steps
step43770565281690488e6e7364ba7aab35
	<step>

	^ ((Dictionary new) add: (#definition->#'3a43e006-f8b9-6c4b-8214-c5f909d653f2'); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->4080); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'23 September 2013 4:37:47 pm'); yourself)); add: (#id->#'43770565-2816-9048-8e6e-7364ba7aab35'); add: (#iconCode->'nil'); add: (#next->#'94eb9234-d52f-0e4a-81c1-de2c4191893e'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)