steps
step688b9e53cc309341a36854f6c47e402c
	<step>

	^ ((Dictionary new) add: (#definition->#'0c53b73c-4e16-1542-b40c-cd76a3b1dda5'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->3950); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#'d9634b11-bde6-1a40-a0b4-7be880afc37a'); yourself)); add: (#id->#'688b9e53-cc30-9341-a368-54f6c47e402c'); add: (#iconCode->'nil'); add: (#next->#'d86f12e2-c38d-4e4e-807e-4615652c2137'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)