steps
step40631e0e1210ba40b78af96a2cefc0b0
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsAsStrings); add: (#class->ViQueryGroupSortStep); add: (#properties->((Dictionary new) add: (#priority->6550); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#'2fca6209-9c2d-c644-823a-acf2909bad0f'); yourself)); add: (#id->#'40631e0e-1210-ba40-b78a-f96a2cefc0b0'); add: (#iconCode->'nil'); add: (#next->#'24d74d14-5e31-7641-a5f6-d6667eb3ffd2'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)