steps
stepd8173faa7721b340afaaa4d664743096
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsAsStrings); add: (#class->ViQueryGroupSortStep); add: (#properties->((Dictionary new) add: (#priority->4180); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'7 November 2013 10:52:48 am'); yourself)); add: (#id->#'d8173faa-7721-b340-afaa-a4d664743096'); add: (#iconCode->'nil'); add: (#next->#'7907fbd5-fb83-4745-8cfd-3c35462e6004'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)