steps
step3ded3e1d2e885448a30216e605bc65a0
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsBySelector); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->3500); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 September 2013 7:36:18 pm'); yourself)); add: (#id->#'3ded3e1d-2e88-5448-a302-16e605bc65a0'); add: (#iconCode->'nil'); add: (#next->#'d85efa7f-9578-8341-a110-19f9ca847c76'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)