steps
stepcfe6ad6fad06774fb19c5dc3bea7243e
	<step>

	^ ((Dictionary new) add: (#definition->#'a38a5806-b66e-564d-b9b3-38ff9f89c2af'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->#AAAAAA); add: (#creationAuthor->'mt'); add: (#priority->3280); add: (#creationTimeStamp->'13 September 2013 6:08:11 pm'); yourself)); add: (#id->#'cfe6ad6f-ad06-774f-b19c-5dc3bea7243e'); add: (#iconCode->'nil'); add: (#next->#'b72e75d1-03bb-7541-a46e-39fd55b28333'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)