steps
step4e23cd6b405ee94f848522afd117448c
	<step>

	^ ((Dictionary new) add: (#definition->#'07161242-230e-1049-93b7-2f75e3deef7b'); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->1890); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'4e23cd6b-405e-e94f-8485-22afd117448c'); add: (#iconCode->'nil'); add: (#next->#'8e40f69c-6657-8340-838b-dd4fb3a4e0b8'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)