steps
step00ab51d869ddfb4a90da3e9a2f70ef75
	<step>

	^ ((Dictionary new) add: (#definition->#'6a694a4e-65b5-7942-9697-978ac471ca74'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->5450); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'14 February 2014 2:48:40 pm'); add: (#headerText->#o); yourself)); add: (#id->#'00ab51d8-69dd-fb4a-90da-3e9a2f70ef75'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)