steps
step2fca62099c2dc644823aacf2909bad0f
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsAsStrings); add: (#class->ViQueryGroupSortStep); add: (#properties->((Dictionary new) add: (#priority->1280); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#'2fca6209-9c2d-c644-823a-acf2909bad0f'); yourself)); add: (#id->#'2fca6209-9c2d-c644-823a-acf2909bad0f'); add: (#iconCode->'nil'); add: (#next->#'26f3a2b2-f47a-644b-ac5f-159e2365b955'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)