steps
stepe44e7438eba573448590a778889ab428
	<step>

	^ ((Dictionary new) add: (#definition->#'2d539c1b-df9b-604e-ae8d-70eff84ca13e'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#000000'); add: (#creationAuthor->'mt'); add: (#priority->5050); add: (#creationTimeStamp->'11 February 2014 10:22:01 am'); yourself)); add: (#id->#'e44e7438-eba5-7344-8590-a778889ab428'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)