steps
step0aef5c3f5e839a4f8a0b9fd4ca3e46f4
	<step>

	^ ((Dictionary new) add: (#definition->#origin); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationAuthor->'mt'); add: (#priority->2070); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'0aef5c3f-5e83-9a4f-8a0b-9fd4ca3e46f4'); add: (#iconCode->'nil'); add: (#next->#'0bcec8d5-cada-9048-b7bf-ace560a17f4f'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)