steps
step6add0b0f920d894b8c607e275fc7080f
	<step>

	^ ((Dictionary new) add: (#definition->#'8ad783be-1900-e64d-8e3c-ec7881484f24'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'10 December 2014 10:17:08 am'); yourself)); add: (#id->#'6add0b0f-920d-894b-8c60-7e275fc7080f'); add: (#iconCode->'nil'); add: (#next->#'cd563aef-8bdc-1746-b414-80fad70add58'); add: (#viewDefinition->#treePlain); add: (#label->nil); yourself)