steps
step97de04417aafe745a2637000ac4db432
	<step>

	^ ((Dictionary new) add: (#definition->#'a6effdc4-d6ca-c64c-a7e4-11dd4cfc4625'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->5930); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 February 2014 4:12:20 pm'); yourself)); add: (#id->#'97de0441-7aaf-e745-a263-7000ac4db432'); add: (#iconCode->'nil'); add: (#next->#'1d71708a-5456-7942-9c1c-c6c37baec8c9'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)