steps
step524b534fb2f52447a4d09a1769f2d123
	<step>

	^ ((Dictionary new) add: (#definition->#'298c9fc0-b1c0-174e-8db4-7f9f8cee2ea6'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->6750); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'14 August 2014 1:19:01 pm'); yourself)); add: (#id->#'524b534f-b2f5-2447-a4d0-9a1769f2d123'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treePlain); add: (#label->nil); yourself)