steps
step7422d4b077d42d43b1a27c93516983f7
	<step>

	^ ((Dictionary new) add: (#definition->#'73e83736-5144-8f47-ba71-3ddb8ee006e5'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->300); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'7422d4b0-77d4-2d43-b1a2-7c93516983f7'); add: (#iconCode->'nil'); add: (#next->#'97267cb4-71a7-4142-9525-0f6435c13a81'); add: (#viewDefinition->#treeView); add: (#label->'All subclasses'); yourself)