steps
stepcd563aef8bdc1746b41480fad70add58
	<step>

	^ ((Dictionary new) add: (#definition->#'93525b3f-5fde-bb4c-ad94-1c2c3a53fd53'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->6070); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'5 May 2014 2:26:38 pm'); yourself)); add: (#id->#'cd563aef-8bdc-1746-b414-80fad70add58'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)