steps
step635ee7eedfa71342a9c2f1e54ca14660
	<step>

	^ ((Dictionary new) add: (#definition->#'8bab16cf-8208-4b43-abb2-ab6ad8964984'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->2260); add: (#headerText->'Class'); yourself)); add: (#id->#'635ee7ee-dfa7-1342-a9c2-f1e54ca14660'); add: (#iconCode->'nil'); add: (#next->#'1b33173f-22e5-2e40-a2da-55d68ca21ac8'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)