steps
stepc65592367b069748a18d09f2ae6515f8
	<step>

	^ ((Dictionary new) add: (#definition->#'6731f25c-5705-6843-8e6f-0c4263ca2073'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->4990); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'3 February 2014 4:57:24 pm'); yourself)); add: (#id->#'c6559236-7b06-9748-a18d-09f2ae6515f8'); add: (#iconCode->'nil'); add: (#next->#'31f89720-da42-cf44-b43e-1de2fca6bfa1'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)