steps
stepee9363991409634c81ff0389658bb3ce
	<step>

	^ ((Dictionary new) add: (#definition->#'f7713f3d-1af3-de43-9510-b66470425a96'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->4560); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'6 December 2013 5:17:12 pm'); yourself)); add: (#id->#'ee936399-1409-634c-81ff-0389658bb3ce'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)