steps
stepbe086e52473b3d4ba8336d796588f9e6
	<step>

	^ ((Dictionary new) add: (#definition->#'2f31c995-3a2b-9a41-8c9a-281f6d2a3ffa'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->1550); add: (#headerText->'Class'); yourself)); add: (#id->#'be086e52-473b-3d4b-a833-6d796588f9e6'); add: (#iconCode->'nil'); add: (#next->#'e61b1b9c-dca8-0246-aff4-93c3b091547a'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)