steps
step78a4e23d75dc65458dfa2e3ec49b7eb8
	<step>

	^ ((Dictionary new) add: (#definition->#'be02a17d-cc98-1640-ae53-b8838236dad5'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->6740); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'14 August 2014 1:18:07 pm'); yourself)); add: (#id->#'78a4e23d-75dc-6545-8dfa-2e3ec49b7eb8'); add: (#iconCode->'nil'); add: (#next->#'524b534f-b2f5-2447-a4d0-9a1769f2d123'); add: (#viewDefinition->#tileView); add: (#label->'Class metrics (NOM, NOA)'); yourself)