steps
stepe50787c61e43ad469f854bc28d2d5568
	<step>

	^ ((Dictionary new) add: (#definition->#'18785ca0-a55b-1148-b426-989c2cb1cc19'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->5440); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'14 February 2014 10:56:38 am'); add: (#headerText->#t); yourself)); add: (#id->#'e50787c6-1e43-ad46-9f85-4bc28d2d5568'); add: (#iconCode->'nil'); add: (#next->#'00ab51d8-69dd-fb4a-90da-3e9a2f70ef75'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)