steps
step9f893a6bd441944db3661a2e90eb5cb4
	<step>

	^ ((Dictionary new) add: (#definition->#'2402473a-838e-5b48-95fe-fe6648dcc28a'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->4250); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'8 November 2013 4:22:27 pm'); yourself)); add: (#id->#'9f893a6b-d441-944d-b366-1a2e90eb5cb4'); add: (#iconCode->'nil'); add: (#next->#'b1a70f2b-e9ad-3c4a-a7e8-a582e829cc3a'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)