steps
step5befbc74c4bae34d9e58bcf93827d5e8
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsByName); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->2100); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'5befbc74-c4ba-e34d-9e58-bcf93827d5e8'); add: (#iconCode->'nil'); add: (#next->#'e9e1bde1-1735-284c-be1f-6b99473e1678'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)