steps
step31f89720da42cf44b43e1de2fca6bfa1
	<step>

	^ ((Dictionary new) add: (#definition->#'7f5468a3-1dc7-1340-9212-4ad1ee77effc'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->600); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#defaultProperties); yourself)); add: (#id->#'31f89720-da42-cf44-b43e-1de2fca6bfa1'); add: (#iconCode->'nil'); add: (#next->#'e80d4dc3-ffec-204d-8587-d4bb97880132'); add: (#viewDefinition->#treeView); add: (#label->'Layout Properties'); yourself)