steps
step7951779362590c4d852f1225f668aba2
	<step>

	^ ((Dictionary new) add: (#definition->#'bfe36700-f08a-1845-b1d3-c30eccf37a29'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->4070); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#'edcd89de-8046-a844-bfde-c7aca99dba50'); yourself)); add: (#id->#'79517793-6259-0c4d-852f-1225f668aba2'); add: (#iconCode->'nil'); add: (#next->#'00d6ab88-02b8-d343-98bf-44d2fb8c6ab5'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)