steps
step985a7a4ba46d7744abf1de2be369fc56
	<step>

	^ ((Dictionary new) add: (#definition->#'dd5ac176-8ae8-5d49-b080-38900d03870b'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->5160); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'11 February 2014 1:01:49 pm'); add: (#copyOfStep->#identity); yourself)); add: (#id->#'985a7a4b-a46d-7744-abf1-de2be369fc56'); add: (#iconCode->'UiFugueIcons magnifierMediumIcon'); add: (#next->#'bce4eb13-a02d-144e-96b2-cd2944b85fee'); add: (#viewDefinition->#multiPane); add: (#label->'Receiver Inspector'); yourself)