steps
step676364194db68c43aa22b3948e02e796
	<step>

	^ ((Dictionary new) add: (#definition->#'1bb9207e-4ee2-404a-8f53-21cee72442ae'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->2780); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#headerText->'Name'); yourself)); add: (#id->#'67636419-4db6-8c43-aa22-b3948e02e796'); add: (#iconCode->'nil'); add: (#next->#'42ef8b6b-8cf0-da4a-b075-0fb0146d805c'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)