steps
step9cef732f20e3884c8e5f55e415a20f91
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsAsStrings); add: (#class->ViQueryGroupSortStep); add: (#properties->((Dictionary new) add: (#priority->1220); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'9cef732f-20e3-884c-8e5f-55e415a20f91'); add: (#iconCode->'nil'); add: (#next->#'46075c87-5609-2c41-86d5-a35e4089e966'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)