steps
step7d49f967e5fd2d45a452864c859fa223
	<step>

	^ ((Dictionary new) add: (#definition->#'92d66888-3e33-e449-82ee-fc6d9fdf72e6'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->6420); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'5 June 2014 4:58:07 pm'); yourself)); add: (#id->#'7d49f967-e5fd-2d45-a452-864c859fa223'); add: (#iconCode->'nil'); add: (#next->#'08b44027-bc56-f844-9826-f94859a5b557'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)