steps
step24a9922a802c1543acf7ff6d8dc30bbf
	<step>

	^ ((Dictionary new) add: (#definition->#iconAndLabel); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->3470); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 September 2013 7:33:25 pm'); yourself)); add: (#id->#'24a9922a-802c-1543-acf7-ff6d8dc30bbf'); add: (#iconCode->'nil'); add: (#next->#'eae7856b-17a8-2746-aa42-f06591c95280'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)