steps
step086c59441e512c4d8e179ee9bffc0d2a
	<step>

	^ ((Dictionary new) add: (#definition->#'5ca6f96b-b7e5-ae47-b442-2abfa2f51046'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->4830); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'17 January 2014 3:22:32 pm'); yourself)); add: (#id->#'086c5944-1e51-2c4d-8e17-9ee9bffc0d2a'); add: (#iconCode->'nil'); add: (#next->#'0b1978b8-7b59-4842-81f5-9f94cce1ec89'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)