steps
stepa4ac81fcd21c7240abf868d76d2dc175
	<step>

	^ ((Dictionary new) add: (#definition->#'068f96bd-e44f-e349-91d8-1a6a40a7afd0'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->150); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'a4ac81fc-d21c-7240-abf8-68d76d2dc175'); add: (#iconCode->'UiFugueIcons categoryIcon'); add: (#next->#'3947aee4-5c3a-1649-8884-a37f2fcf75e9'); add: (#viewDefinition->#treeView); add: (#label->'Categories'); yourself)