steps
step0547837e8ef9cd4b827d5574ea1e1c91
	<step>

	^ ((Dictionary new) add: (#definition->#'1bb9207e-4ee2-404a-8f53-21cee72442ae'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->2190); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'0547837e-8ef9-cd4b-827d-5574ea1e1c91'); add: (#iconCode->'nil'); add: (#next->#'bda64b7c-17f6-3247-be1d-13159655ec28'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)