steps
step33a2c2eebac83b4a842dfaf5586d7042
	<step>

	^ ((Dictionary new) add: (#definition->#'6f38796b-7a6d-494e-926e-a2dc03b50f2e'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->4340); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'12 November 2013 5:02:54 pm'); yourself)); add: (#id->#'33a2c2ee-bac8-3b4a-842d-faf5586d7042'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)