steps
stepd30b0a27e492ab4c807d23bd5f7ccf4b
	<step>

	^ ((Dictionary new) add: (#definition->#'d0d48ca2-5848-de40-9dec-499bcb0ef520'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->5080); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'11 February 2014 1:47:30 pm'); yourself)); add: (#id->#'d30b0a27-e492-ab4c-807d-23bd5f7ccf4b'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)