steps
stepecc9e9ca455ec14887621714a939cbe9
	<step>

	^ ((Dictionary new) add: (#definition->#'119de777-f025-874c-9828-ec6ead11f625'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->4200); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'7 November 2013 11:04:24 am'); yourself)); add: (#id->#'ecc9e9ca-455e-c148-8762-1714a939cbe9'); add: (#iconCode->'nil'); add: (#next->#'4cf7f9df-0d15-0d42-b792-4c26bd39cbe1'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)