steps
stepsenders
	<step>

	^ ((Dictionary new) add: (#definition->#'a3a0aaa7-1711-094f-8621-bac1067b8ab0'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->350); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#senders); add: (#iconCode->'UiFugueIcons arrowStepIcon'); add: (#next->#'b90e4eaa-f8ab-8b47-aca3-f78a5dadde3e'); add: (#viewDefinition->#treeView); add: (#label->'Senders'); yourself)