steps
stepaf7030042f554940abd6c3b1a717db27
	<step>

	^ ((Dictionary new) add: (#definition->#'60d51cf0-3914-2045-ae54-eea3e1bab488'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->930); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'af703004-2f55-4940-abd6-c3b1a717db27'); add: (#iconCode->'nil'); add: (#next->#'59e1a354-ea9e-3d4d-b4c6-70d3a9eb6d48'); add: (#viewDefinition->#treeView); add: (#label->'Methods w/ Longest History'); yourself)