steps
stepe80d4dc3ffec204d8587d4bb97880132
	<step>

	^ ((Dictionary new) add: (#definition->#'bd42b84b-e2e0-3f44-9361-626b76d2721f'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->4950); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'3 February 2014 5:07:16 pm'); yourself)); add: (#id->#'e80d4dc3-ffec-204d-8587-d4bb97880132'); add: (#iconCode->'nil'); add: (#next->#'69e4b48a-26f2-2947-920e-1ddf9f97ad0e'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)