steps
stepfdc9d7842f4f8a428553dfc7982b9585
	<step>

	^ ((Dictionary new) add: (#definition->#'b0fffbca-3097-5b44-8c4f-0ec8eb682a21'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->6190); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'5 June 2014 4:50:14 pm'); yourself)); add: (#id->#'fdc9d784-2f4f-8a42-8553-dfc7982b9585'); add: (#iconCode->'nil'); add: (#next->#'e89d0b5a-e4fe-584b-aed4-96f20385b05c'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)