steps
step9caa8ce42b829b4f8466269ee432cdd8
	<step>

	^ ((Dictionary new) add: (#definition->#'07203f12-f1b6-9746-9884-0b9e8f1a4f6b'); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->2720); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'9caa8ce4-2b82-9b4f-8466-269ee432cdd8'); add: (#iconCode->'nil'); add: (#next->#'b30d3137-9d85-cb46-99be-a7682d624290'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)