steps
step5c2e7b343c999341badbb111a003abb4
	<step>

	^ ((Dictionary new) add: (#definition->#'c7b9f779-af5c-f242-acdd-5b98ebc17cb5'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->1190); add: (#headerText->'P'); yourself)); add: (#id->#'5c2e7b34-3c99-9341-badb-b111a003abb4'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)