steps
step4da4bc91ca767546ba411367a631812d
	<step>

	^ ((Dictionary new) add: (#definition->#'c25e7868-1c1a-4647-ab32-5182e547450a'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->6210); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'11 February 2014 1:01:49 pm'); add: (#copyOfStep->#identity); yourself)); add: (#id->#'4da4bc91-ca76-7546-ba41-1367a631812d'); add: (#iconCode->'nil'); add: (#next->#'c67f9784-9909-ad41-9da5-97b166608217'); add: (#viewDefinition->#treeViewExtended); add: (#label->'Change Set'); yourself)