steps
stepa127f2fae9457b48b6ca53f8cdfab01b
	<step>

	^ ((Dictionary new) add: (#definition->#'010d5fed-1ded-8340-8190-604f3aec0c66'); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->4730); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'17 January 2014 3:00:32 pm'); yourself)); add: (#id->#'a127f2fa-e945-7b48-b6ca-53f8cdfab01b'); add: (#iconCode->'nil'); add: (#next->#'087bc712-e210-1d43-b27c-50a4d240b0ea'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)