steps
stepgroupsUnsorted
	<step>

	^ ((Dictionary new) add: (#definition->#'c9ef82bd-db12-d446-a43f-558a04f98be2'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->((Array new: 2) at: 1 put: Object; at: 2 put: Object; yourself)); add: (#creationTimeStamp->'15 June 2015 10:20:57 am'); add: (#view->ViTreeViewExtended); add: (#creationAuthor->'mt'); add: (#copyOf->#groups); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->#'e91a4f52-5c39-4c4c-b5c5-1311bacd5025'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#groupsUnsorted); add: (#isReference->false); yourself)