steps
step2b264d15bb33124e8b3f227ef7073118
	<step>

	^ ((Dictionary new) add: (#definition->#'a5322375-d829-bb40-9181-f4ce0b5ec1fd'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->4480); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 November 2013 5:02:56 pm'); yourself)); add: (#id->#'2b264d15-bb33-124e-8b3f-227ef7073118'); add: (#iconCode->'nil'); add: (#next->#'53385c7b-cff8-c842-8efd-e43b039db34b'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)