steps
step68eda6668d64144eb349065974fd20f2
	<step>

	^ ((Dictionary new) add: (#definition->#'720a8d90-f7c1-334e-a4ea-5094ba285a8d'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->4640); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'10 January 2014 12:49:11 pm'); yourself)); add: (#id->#'68eda666-8d64-144e-b349-065974fd20f2'); add: (#iconCode->'nil'); add: (#next->#senders); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)