steps
step1c8ee05c15a80443a950ee7f922427c5
	<step>

	^ ((Dictionary new) add: (#definition->#'77dcecde-da90-d24e-a615-4c212b400adc'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->820); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'1c8ee05c-15a8-0443-a950-ee7f922427c5'); add: (#iconCode->'nil'); add: (#next->#'894088c2-9d24-5b40-9246-2e1a298fe761'); add: (#viewDefinition->#treePlain); add: (#label->'Count Instances'); yourself)