steps
stepfcc664844caf354f8f24d727784b3424
	<step>

	^ ((Dictionary new) add: (#definition->#'c5c5e6af-5c68-7346-8f74-2b8ce9d21204'); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->2560); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'fcc66484-4caf-354f-8f24-d727784b3424'); add: (#iconCode->'nil'); add: (#next->#'d96e910a-df73-5a4c-b760-8811fac45378'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)