steps
step77862f460851124eb1ff6cb2e962a0c8
	<step>

	^ ((Dictionary new) add: (#definition->#'8a8d6ac7-0a64-2e4d-942f-654924a02c68'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->3300); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 September 2013 6:34:06 pm'); add: (#copyOfStep->#'77862f46-0851-124e-b1ff-6cb2e962a0c8'); yourself)); add: (#id->#'77862f46-0851-124e-b1ff-6cb2e962a0c8'); add: (#iconCode->'UiDiagonaIcons icon0223Normal'); add: (#next->#'fd3c0b79-142a-ee4e-9f27-4da12eba946f'); add: (#viewDefinition->#treeView); add: (#label->'Flags'); yourself)