steps
stepimplementors
	<step>

	^ ((Dictionary new) add: (#definition->#'c3876e02-15ba-414a-ae61-c41de8ba4e72'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->310); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#implementors); add: (#iconCode->'UiFugueIcons scriptsTextIcon'); add: (#next->#'51d8a538-95c9-ce4b-9e21-ac726be7665b'); add: (#viewDefinition->#treeView); add: (#label->'Implementors'); yourself)