steps
stepd2ab7b327b9eba48808cab0e89480da4
	<step>

	^ ((Dictionary new) add: (#definition->#'0c53b73c-4e16-1542-b40c-cd76a3b1dda5'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->3780); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 September 2013 6:59:44 pm'); yourself)); add: (#id->#'d2ab7b32-7b9e-ba48-808c-ab0e89480da4'); add: (#iconCode->'nil'); add: (#next->#'ef81aed0-ae2d-6548-904f-030b28e12e97'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)