steps
step2293cc01c88a35429a4dcaa8ba9c12c8
	<step>

	^ ((Dictionary new) add: (#definition->#'7edc593b-3bdd-fe4c-8177-cfab9dec78f2'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#view->ViWorkspaceView); add: (#creationTimeStamp->'21 January 2015 11:47:33 am'); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->nil); add: (#label->'Workspace'); add: (#iconCode->'nil'); add: (#id->#'2293cc01-c88a-3542-9a4d-caa8ba9c12c8'); add: (#isReference->false); add: (#viewDefinition->#treePlain); yourself)