steps
step61009caeb7fb434cbfab3a240dc5768a
	<step>

	^ ((Dictionary new) add: (#definition->#'3c4ea291-ae2b-6344-9d06-94315e411bf1'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->1290); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'61009cae-b7fb-434c-bfab-3a240dc5768a'); add: (#iconCode->'nil'); add: (#next->#'904c20d9-4fe8-d644-bd0d-ec510cf667f3'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)