steps
step9a8f7fe5e3fe5e4e8f65c463b0cac3e9
	<step>

	^ ((Dictionary new) add: (#definition->#'5ac85d37-1b76-e741-892a-74402b5cc58e'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->5320); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 February 2014 1:08:14 pm'); add: (#headerText->#DMr); yourself)); add: (#id->#'9a8f7fe5-e3fe-5e4e-8f65-c463b0cac3e9'); add: (#iconCode->'nil'); add: (#next->#'e33fe689-cff8-ff4f-b574-d2a3b3986f94'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)