steps
stepc4cd5013fa6d7a44966e79cfcaa59612
	<step>

	^ ((Dictionary new) add: (#definition->#'5461ed64-57d6-df47-8ea9-6c72de426d1d'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->4580); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'20 December 2013 11:55:55 am'); yourself)); add: (#id->#'c4cd5013-fa6d-7a44-966e-79cfcaa59612'); add: (#iconCode->'nil'); add: (#next->#'1ab8a66a-db32-f445-87b2-0c2967596906'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)