steps
step6bb09addd327dd4abd4b47d25202dbf7
	<step>

	^ ((Dictionary new) add: (#definition->#'8a8d6ac7-0a64-2e4d-942f-654924a02c68'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->3850); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 September 2013 6:34:06 pm'); add: (#copyOfStep->#'77862f46-0851-124e-b1ff-6cb2e962a0c8'); yourself)); add: (#id->#'6bb09add-d327-dd4a-bd4b-47d25202dbf7'); add: (#iconCode->'ViEclipseIcons tasksTskIcon'); add: (#next->#'5b87b137-752e-b346-a7fb-46bd574a4330'); add: (#viewDefinition->#tableView); add: (#label->'Tasks'); yourself)