steps
step89d7f52e82713f47b6958c06854f6a85
	<step>

	^ ((Dictionary new) add: (#definition->#'6b3d9fbe-3f81-8048-ab4b-2b31f970a06d'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->2370); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'89d7f52e-8271-3f47-b695-8c06854f6a85'); add: (#iconCode->'nil'); add: (#next->#'89c40fb8-551c-9e46-9651-f11978e9ff30'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)