steps
stepc7e12f641638ba4392a55110b39063f2
	<step>

	^ ((Dictionary new) add: (#definition->#'5f9c4c42-67c8-c44c-99bc-c4bbff0a8363'); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->3770); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 September 2013 6:58:12 pm'); yourself)); add: (#id->#'c7e12f64-1638-ba43-92a5-5110b39063f2'); add: (#iconCode->'nil'); add: (#next->#'4b813e3f-30bb-714c-9658-02f84e1ecc5b'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)