steps
stepc0319874c45b744185fef6fe2ba7e2a9
	<step>

	^ ((Dictionary new) add: (#definition->#'740c7d8f-097a-4043-b903-fe5818cbf7b7'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->2170); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'c0319874-c45b-7441-85fe-f6fe2ba7e2a9'); add: (#iconCode->'nil'); add: (#next->#'ce6fede4-1334-d84b-8176-5e5a33fd162f'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)