steps
step5810152a258e104482c6a1d1c4ad946a
	<step>

	^ ((Dictionary new) add: (#definition->#'e9bef106-e5e8-514c-ac3a-8648bb731c05'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->3550); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 September 2013 8:01:35 pm'); yourself)); add: (#id->#'5810152a-258e-1044-82c6-a1d1c4ad946a'); add: (#iconCode->'nil'); add: (#next->#'a64e11c5-6bfc-5a42-a738-d78d947d80da'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)