steps
step4e96ab7fcc8d1040aad0ed4e9026b875
	<step>

	^ ((Dictionary new) add: (#definition->#'a106f1b0-9632-e247-a7b3-e27d6eec5845'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'12 May 2015 4:36:46 pm'); add: (#copyOf->#'8ed979bd-353a-934e-9977-6e22d8afc389'); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->#'57ef0b8f-46a4-1744-80b4-6974ec1adc76'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'4e96ab7f-cc8d-1040-aad0-ed4e9026b875'); add: (#isReference->false); yourself)