steps
step2d21437b3606d34398725e357a12de36
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsByName); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->2750); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'2d21437b-3606-d343-9872-5e357a12de36'); add: (#iconCode->'nil'); add: (#next->#'f8f2564d-0b66-d645-9646-191f5736dcef'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)