steps
step36a77c635f453d4f9e19299ea147b037
	<step>

	^ ((Dictionary new) add: (#definition->#copyToContext); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'36a77c63-5f45-3d4f-9e19-299ea147b037'); add: (#iconCode->'UiSilkIcons carIcon'); add: (#next->#'9f6bdb10-99c0-0845-806f-e60405d4bebd'); add: (#viewDefinition->#treeView); add: (#label->'Class hierarchy'); yourself)