steps
step2e490b12bdf77341b90718df5b218b85
	<step>

	^ ((Dictionary new) add: (#definition->#'1b047488-6502-e74e-83f2-05ae0fbf0400'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->480); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'3 January 2014 3:37:49 pm'); yourself)); add: (#id->#'2e490b12-bdf7-7341-b907-18df5b218b85'); add: (#iconCode->'nil'); add: (#next->#'d70d563f-bdd7-1842-9175-cf758450e227'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)