steps
stepfdb69e0a57ea394aa74ab986817dca93
	<step>

	^ ((Dictionary new) add: (#definition->#'e4592bf3-ca81-2446-be75-29fee8fe6683'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationAuthor->'mt'); add: (#priority->3190); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'fdb69e0a-57ea-394a-a74a-b986817dca93'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)