steps
stepefe97b2318f7b84790a1a8315d4344a7
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsByName); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->4720); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'17 January 2014 3:00:13 pm'); yourself)); add: (#id->#'efe97b23-18f7-b847-90a1-a8315d4344a7'); add: (#iconCode->'nil'); add: (#next->#'a127f2fa-e945-7b48-b6ca-53f8cdfab01b'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)