steps
stepa7590d1be0ee6340a3d476e67ae30cfa
	<step>

	^ ((Dictionary new) add: (#definition->#'720a8d90-f7c1-334e-a4ea-5094ba285a8d'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->5690); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 February 2014 4:58:32 pm'); yourself)); add: (#id->#'a7590d1b-e0ee-6340-a3d4-76e67ae30cfa'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)