steps
step7faad50ace32d04b93a5abcb22ff458e
	<step>

	^ ((Dictionary new) add: (#definition->#category); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->3480); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 September 2013 7:33:49 pm'); yourself)); add: (#id->#'7faad50a-ce32-d04b-93a5-abcb22ff458e'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)