steps
step003ae1fe6781f9439e4dc1fa5bab39b0
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsAsStrings); add: (#class->ViQueryGroupSortStep); add: (#properties->((Dictionary new) add: (#priority->2770); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'003ae1fe-6781-f943-9e4d-c1fa5bab39b0'); add: (#iconCode->'nil'); add: (#next->#'67636419-4db6-8c43-aa22-b3948e02e796'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)