steps
stepe66f7ebe27a3584f836cee4cf8041d8b
	<step>

	^ ((Dictionary new) add: (#definition->#'2c677287-606b-6e44-89fb-01fb56357b98'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->2010); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#headerText->'Object'); yourself)); add: (#id->#'e66f7ebe-27a3-584f-836c-ee4cf8041d8b'); add: (#iconCode->'nil'); add: (#next->#'22b325c1-285b-6242-8b45-bf948f7079a2'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)