steps
stepd977be3c9e8a6740bff763c0bd8811c0
	<step>

	^ ((Dictionary new) add: (#definition->#'58ea7896-8763-644c-a23f-47ea23baadcd'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->2030); add: (#headerText->'Comment'); yourself)); add: (#id->#'d977be3c-9e8a-6740-bff7-63c0bd8811c0'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)