steps
step572ceaba6d90a54daa5c1091a08ad960
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsAsStrings); add: (#class->ViQueryGroupSortStep); add: (#properties->((Dictionary new) add: (#priority->1760); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'572ceaba-6d90-a54d-aa5c-1091a08ad960'); add: (#iconCode->'nil'); add: (#next->#'6984c6e0-9766-4d45-8520-38f66da3cd32'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)