steps
step087bc712e2101d43b27c50a4d240b0ea
	<step>

	^ ((Dictionary new) add: (#definition->#iconAndLabel); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->4790); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#defaultProperties); yourself)); add: (#id->#'087bc712-e210-1d43-b27c-50a4d240b0ea'); add: (#iconCode->'nil'); add: (#next->#'a8f95d96-7f39-6744-aca5-95cde8b9e75e'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)