steps
step761098d48a292a47be447677570b352e
	<step>

	^ ((Dictionary new) add: (#definition->#'490cdda4-45bc-414d-b6a5-e84c85f44b30'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->860); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'11 February 2014 10:06:57 am'); yourself)); add: (#id->#'761098d4-8a29-2a47-be44-7677570b352e'); add: (#iconCode->'nil'); add: (#next->#'b193f637-d3a4-cb4b-9b3e-94c7b7ba29e9'); add: (#viewDefinition->#treeView); add: (#label->'Global variables'); yourself)