steps
stepf50a996dd0c83e46bfc9b54c71e930d2
	<step>

	^ ((Dictionary new) add: (#definition->#'ac61d54e-889d-0840-9451-e8c31df3dc34'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->730); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 September 2013 6:31:32 pm'); add: (#copyOfStep->#'f50a996d-d0c8-3e46-bfc9-b54c71e930d2'); yourself)); add: (#id->#'f50a996d-d0c8-3e46-bfc9-b54c71e930d2'); add: (#iconCode->'nil'); add: (#next->#'4291e65f-ca68-f04b-bbb8-41cf2734c087'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)