steps
step4762774bb64ef14b8e4ad0fc1dc20251
	<step>

	^ ((Dictionary new) add: (#definition->#allMethodsForClass); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->240); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'4762774b-b64e-f14b-8e4a-d0fc1dc20251'); add: (#iconCode->'nil'); add: (#next->#'172f485a-7e69-0d4a-a5ad-7233f83da2dc'); add: (#viewDefinition->#treeView); add: (#label->'Methods w/ timestamp'); yourself)