steps
step61afd65ed9435642bd3115492112b6ad
	<step>

	^ ((Dictionary new) add: (#definition->#'41e28d6b-077d-474b-b28a-e30838864205'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->4760); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 January 2014 4:32:08 pm'); yourself)); add: (#id->#'61afd65e-d943-5642-bd31-15492112b6ad'); add: (#iconCode->'nil'); add: (#next->#'bf2d198a-d977-ed49-86f9-225cbfd68155'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)