steps
stepe33fe689cff8ff4fb574d2a3b3986f94
	<step>

	^ ((Dictionary new) add: (#definition->#'e56dcef1-1fe0-4645-b354-b85dc88c7cf7'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->5330); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 February 2014 1:08:29 pm'); add: (#headerText->#DMf); yourself)); add: (#id->#'e33fe689-cff8-ff4f-b574-d2a3b3986f94'); add: (#iconCode->'nil'); add: (#next->#'3544ebd4-2cab-b84a-88d2-0c15dde14360'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)