steps
step3eddb241953313498650c86422ca0395
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsBySelector); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->2640); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'3eddb241-9533-1349-8650-c86422ca0395'); add: (#iconCode->'nil'); add: (#next->#'070104b0-18c4-7348-bdce-375fa5dbc93c'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)