steps
step25668ab353832a4b8bc25d22ac2cc3fe
	<step>

	^ ((Dictionary new) add: (#definition->#copyToContext); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->3430); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 September 2013 7:19:58 pm'); yourself)); add: (#id->#'25668ab3-5383-2a4b-8bc2-5d22ac2cc3fe'); add: (#iconCode->'nil'); add: (#next->#'12f3cc3b-319f-8842-a3d9-43b6034d0539'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)