steps
stepa1816fcb1266bb438500bf8b71248ede
	<step>

	^ ((Dictionary new) add: (#definition->#'0fee1e3f-c9f8-9042-b646-88feee2a13c8'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#hAlignment->#right); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'8 November 2013 4:10:44 pm'); add: (#priority->4220); yourself)); add: (#id->#'a1816fcb-1266-bb43-8500-bf8b71248ede'); add: (#iconCode->'nil'); add: (#next->#'9f893a6b-d441-944d-b366-1a2e90eb5cb4'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)