steps
stepc8ae512dfe018e479ddf034ee4da41b3
	<step>

	^ ((Dictionary new) add: (#definition->#'12390d96-f96a-e34e-a8b1-59c6c8d26fa1'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#headerText->'Protocol'); yourself)); add: (#id->#'c8ae512d-fe01-8e47-9ddf-034ee4da41b3'); add: (#iconCode->'nil'); add: (#next->#'36f18c66-dd99-1f43-b7a8-edc44c309ebc'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)