steps
step4f59f26e7806f847a4a510f389535b0e
	<step>

	^ ((Dictionary new) add: (#definition->#'4d86db4d-38b8-7d42-b937-130dce32f786'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 September 2013 7:03:26 pm'); add: (#priority->3890); add: (#copyOfStep->#'cb114238-013b-3e4d-9bf9-73b27ef3dd5a'); add: (#headerText->'Path'); yourself)); add: (#id->#'4f59f26e-7806-f847-a4a5-10f389535b0e'); add: (#iconCode->'nil'); add: (#next->#'475707d2-2203-3e46-886e-f4249d390390'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)