steps
step70f2866cc1934849bbc6734357c4521f
	<step>

	^ ((Dictionary new) add: (#definition->#identity); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->6590); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'11 February 2014 1:01:49 pm'); add: (#copyOfStep->#identity); yourself)); add: (#id->#'70f2866c-c193-4849-bbc6-734357c4521f'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#workspace); add: (#label->'Script Objects'); yourself)