steps
step91c9c5aa8933524c908c609b3a1fc00a
	<step>

	^ ((Dictionary new) add: (#definition->#'889c4b1a-c134-b247-81b3-f1f186198c7e'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->6270); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'6 June 2014 5:22:34 pm'); yourself)); add: (#id->#'91c9c5aa-8933-524c-908c-609b3a1fc00a'); add: (#iconCode->'nil'); add: (#next->#'d62c8659-3292-5541-b3b6-08b9ff46de99'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)