steps
stepac1f8319046ce04db22a43df31b7abef
	<step>

	^ ((Dictionary new) add: (#definition->#'e43c93d0-ee96-e542-8395-df731e1f9503'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#hAlignment->#center); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#itemOrientation->#vertical); add: (#creationAuthor->'mt'); add: (#vAlignment->#bottom); add: (#priority->2540); add: (#headerText->'Origin'); yourself)); add: (#id->#'ac1f8319-046c-e04d-b22a-43df31b7abef'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)