steps
step0d396a44b27ef545a69dd25485dfe138
	<step>

	^ ((Dictionary new) add: (#definition->#'07db93e4-9707-644c-8344-528719c82bd1'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->5650); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 February 2014 4:24:55 pm'); yourself)); add: (#id->#'0d396a44-b27e-f545-a69d-d25485dfe138'); add: (#iconCode->'nil'); add: (#next->#'73c14db0-5129-5543-9fe9-dab9298595fb'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)