steps
stepa941a591235f754098d68df3ef643eb5
	<step>

	^ ((Dictionary new) add: (#definition->#'79a5a7cf-a1e8-694a-9c9a-4d45e160f7f5'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->670); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'a941a591-235f-7540-98d6-8df3ef643eb5'); add: (#iconCode->'UiSilkIcons databaseIcon'); add: (#next->#'9d1d6fe1-e07c-9f4a-97aa-452c1fbcc9af'); add: (#viewDefinition->#treeView); add: (#label->'MC File Repository'); yourself)