steps
step51d8a53895c9ce4b9e21ac726be7665b
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsBySelector); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->1510); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'51d8a538-95c9-ce4b-9e21-ac726be7665b'); add: (#iconCode->'nil'); add: (#next->#'6f20da89-1a7e-f64d-96a6-8b4b22691ee4'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)