steps
step71ddcad37128514caaa79edb1e6953b8
	<step>

	^ ((Dictionary new) add: (#definition->#'1198e55b-a78e-6842-8a27-3a6403912dca'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->5750); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'11 February 2014 1:01:49 pm'); add: (#copyOfStep->#identity); yourself)); add: (#id->#'71ddcad3-7128-514c-aaa7-9edb1e6953b8'); add: (#iconCode->'nil'); add: (#next->#'d5db789c-076f-b740-9144-a2bd2740df7f'); add: (#viewDefinition->#treeViewExtended); add: (#label->'Method tags'); yourself)