steps
stepd1d946a9b78e72438d30c08accd864b6
	<step>

	^ ((Dictionary new) add: (#definition->#'bfee3c65-a004-8f47-bd94-d9d92eaee86b'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->3210); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 4:21:57 pm'); add: (#headerText->'Type'); yourself)); add: (#id->#'d1d946a9-b78e-7243-8d30-c08accd864b6'); add: (#iconCode->'nil'); add: (#next->#'d9a22b3c-f29a-7840-bb49-c3f6d664b189'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)