steps
step1f64fb2e2ed1dc4eb553cf7d4f3742e4
	<step>

	^ ((Dictionary new) add: (#definition->#'b333ec1c-585c-2243-b690-4161607177bf'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->1050); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'7 September 2013 10:44:15 am'); yourself)); add: (#id->#'1f64fb2e-2ed1-dc4e-b553-cf7d4f3742e4'); add: (#iconCode->'nil'); add: (#next->#'2ea23721-a871-ea46-8798-6a4a5be4cb8e'); add: (#viewDefinition->#treeViewExtended); add: (#label->'View Definitions'); yourself)