steps
stepcc0ed406f999fe49b8f7f627deb6cb53
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsByName); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->3820); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 September 2013 7:16:26 pm'); yourself)); add: (#id->#'cc0ed406-f999-fe49-b8f7-f627deb6cb53'); add: (#iconCode->'nil'); add: (#next->#'3640f742-68dd-e143-aec9-907f1f87a99b'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)