steps
stepa405ca756b83f64d85a7334f3151cfcf
	<step>

	^ ((Dictionary new) add: (#definition->#'7057516c-b98e-ea4a-8d54-c4c3a0f4ab33'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->5630); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'11 February 2014 1:01:49 pm'); add: (#copyOfStep->#identity); yourself)); add: (#id->#'a405ca75-6b83-f64d-85a7-334f3151cfcf'); add: (#iconCode->'nil'); add: (#next->#'5cb7a38d-cab6-d44e-b38f-779f66faf736'); add: (#viewDefinition->#listView); add: (#label->'Classes'); yourself)