steps
stepd8b2f45006353046bb39a2cec077ae4c
	<step>

	^ ((Dictionary new) add: (#definition->#'89b09f36-4977-6046-8942-1b42f21b88f0'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->3420); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 September 2013 7:19:15 pm'); yourself)); add: (#id->#'d8b2f450-0635-3046-bb39-a2cec077ae4c'); add: (#iconCode->'nil'); add: (#next->#'25668ab3-5383-2a4b-8bc2-5d22ac2cc3fe'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)