steps
step63749d6ed32b814e8bc78d3f7f291949
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsBySelector); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->1830); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'63749d6e-d32b-814e-8bc7-8d3f7f291949'); add: (#iconCode->'nil'); add: (#next->#'746c8ffb-51de-a64c-8988-517485778a87'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)