steps
stepcc847404aa05ab4086cf2fa34232d0d8
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsAsStrings); add: (#class->ViQueryGroupSortStep); add: (#properties->((Dictionary new) add: (#priority->1420); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'cc847404-aa05-ab40-86cf-2fa34232d0d8'); add: (#iconCode->'nil'); add: (#next->#'70ad9734-c28e-4247-92a7-f4d788a34977'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)