steps
step0fdcdea85071914bab0c5d6335ce985f
	<step>

	^ ((Dictionary new) add: (#definition->#'fea3ce8f-7751-1047-8469-20e2e7346e54'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->3670); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 September 2013 3:14:17 pm'); yourself)); add: (#id->#'0fdcdea8-5071-914b-ab0c-5d6335ce985f'); add: (#iconCode->'nil'); add: (#next->#'8ca5adad-9868-4e4c-a40e-2b9deba00f31'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)