steps
stepbda64b7c17f63247be1d13159655ec28
	<step>

	^ ((Dictionary new) add: (#definition->#'1b047488-6502-e74e-83f2-05ae0fbf0400'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->470); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'3 January 2014 3:20:50 pm'); yourself)); add: (#id->#'bda64b7c-17f6-3247-be1d-13159655ec28'); add: (#iconCode->'nil'); add: (#next->#'580b86a1-54c0-3a4f-a37c-d12c765b21d4'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)