steps
step0de86151e883cf4c9668960b4466822e
	<step>

	^ ((Dictionary new) add: (#definition->#'9c76ab37-6e8d-7746-a7c3-5b4f72b5552c'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->1110); add: (#resizeMode->#rigid); add: (#headerText->'Version'); yourself)); add: (#id->#'0de86151-e883-cf4c-9668-960b4466822e'); add: (#iconCode->'nil'); add: (#next->#'d30b0a27-e492-ab4c-807d-23bd5f7ccf4b'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)