steps
step5db2822b273db541b1f65ec634e49efa
	<step>

	^ ((Dictionary new) add: (#definition->#'85bc20f1-4a8e-5440-8c06-9b7261827cb1'); add: (#class->ViQueryGroupSortStep); add: (#properties->((Dictionary new) add: (#priority->1950); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'5db2822b-273d-b541-b1f6-5ec634e49efa'); add: (#iconCode->'nil'); add: (#next->#'afd7936f-3466-6b44-84a7-2d8fc3dc21a4'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)