steps
stepf55a783828beae4d829ce8132ee78d9e
	<step>

	^ ((Dictionary new) add: (#definition->#'455ad2d3-0d11-7742-9301-83c3bf906e8b'); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->2690); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'f55a7838-28be-ae4d-829c-e8132ee78d9e'); add: (#iconCode->'nil'); add: (#next->#'648936db-9a22-ed48-a05e-4f1c8c9c94fd'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)