steps
stepcafd96b46e9f904cbb728015ce0d112f
	<step>

	^ ((Dictionary new) add: (#definition->#removeDuplicates); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->4710); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'17 January 2014 2:57:35 pm'); yourself)); add: (#id->#'cafd96b4-6e9f-904c-bb72-8015ce0d112f'); add: (#iconCode->'nil'); add: (#next->#'efe97b23-18f7-b847-90a1-a8315d4344a7'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)