steps
step754c7a1e5b33a8428a8ac5f6eef88890
	<step>

	^ ((Dictionary new) add: (#definition->nil); add: (#class->ViQueryReferenceStep); add: (#properties->((Dictionary new) add: (#priority->2580); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'4 September 2013 12:59:17 pm'); yourself)); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#reference->#'8ed52473-9493-2142-94be-054478bc571b'); add: (#id->#'754c7a1e-5b33-a842-8a8a-c5f6eef88890'); add: (#viewDefinition->#treeView); yourself)