steps
stepd45b0a7524882c43939bec29c77353af
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsAsStrings); add: (#class->ViQueryGroupSortStep); add: (#properties->((Dictionary new) add: (#priority->1090); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'d45b0a75-2488-2c43-939b-ec29c77353af'); add: (#iconCode->'nil'); add: (#next->#'e689b659-27f3-0f4a-9412-ab39abc2b63e'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)