steps
stepdc8af77bcb54d74da9c2fbd92c4b2a44
	<step>

	^ ((Dictionary new) add: (#definition->#'d579b1f6-4466-8842-b908-ef4dcc51f0ad'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->6690); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'23 July 2014 2:44:48 pm'); yourself)); add: (#id->#'dc8af77b-cb54-d74d-a9c2-fbd92c4b2a44'); add: (#iconCode->'nil'); add: (#next->#'2ebbfcc8-18ea-9643-96ea-4d38fe7cf10a'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)