steps
step7badd43290e1ec4296d76085b40a0871
	<step>

	^ ((Dictionary new) add: (#definition->#'2f2ca706-60a5-3745-9782-33256331f57f'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->970); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'3 September 2013 1:58:21 pm'); add: (#copyOfStep->#'7badd432-90e1-ec42-96d7-6085b40a0871'); yourself)); add: (#id->#'7badd432-90e1-ec42-96d7-6085b40a0871'); add: (#iconCode->'nil'); add: (#next->#'254519a4-d387-e145-98c4-9d0959d54bb0'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)