steps
stepviewDefinitions
	<step>

	^ ((Dictionary new) add: (#definition->#'eaacc8b2-4e11-bb4c-ab2b-7aa0583b7467'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->420); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'7 September 2013 10:43:19 am'); yourself)); add: (#id->#viewDefinitions); add: (#iconCode->'nil'); add: (#next->#'1f64fb2e-2ed1-dc4e-b553-cf7d4f3742e4'); add: (#viewDefinition->#treeViewExtended); add: (#label->nil); yourself)