steps
steped778e6a6acee54084c3af7329c1f656
	<step>

	^ ((Dictionary new) add: (#definition->#'ef17b0c3-3ef9-274e-86d1-cf657d2f721b'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->1000); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'6 September 2013 8:27:31 pm'); yourself)); add: (#id->#'ed778e6a-6ace-e540-84c3-af7329c1f656'); add: (#iconCode->'nil'); add: (#next->#'f4803742-eb44-0846-9085-92c09d525159'); add: (#viewDefinition->#treeViewExtended); add: (#label->'Update Definitions'); yourself)