steps
stepdc34144d6524cf48a9a5903457596587
	<step>

	^ ((Dictionary new) add: (#definition->#'b6af371e-5fd6-394f-a44a-c2e4a425ed61'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#isNew->false); add: (#creationTimeStamp->'20 May 2015 2:55:12 pm'); yourself)); add: (#isProperty->false); add: (#next->#'7b32938c-f398-a742-a1ca-38108a4a569b'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'dc34144d-6524-cf48-a9a5-903457596587'); add: (#isReference->true); yourself)