steps
step5b3d233ec93c0b42b8bafafb41d70a9e
	<step>

	^ ((Dictionary new) add: (#definition->#'9ff42a61-06de-db4f-8bde-f07db577c02f'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->2820); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'5b3d233e-c93c-0b42-b8ba-fafb41d70a9e'); add: (#iconCode->'nil'); add: (#next->#'35e3497e-2aff-7d4a-a4e9-6ab0b798b3ed'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)