steps
stepfcae92ef09ebff47be9e9e35c33c4784
	<step>

	^ ((Dictionary new) add: (#definition->#'ac61d54e-889d-0840-9451-e8c31df3dc34'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->3830); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 September 2013 6:31:32 pm'); add: (#copyOfStep->#'f50a996d-d0c8-3e46-bfc9-b54c71e930d2'); yourself)); add: (#id->#'fcae92ef-09eb-ff47-be9e-9e35c33c4784'); add: (#iconCode->'nil'); add: (#next->#'bc34ef97-52af-6c49-b344-cdb766681c0c'); add: (#viewDefinition->#tableView); add: (#label->nil); yourself)