steps
step0cd634b5d35d3a4c8c1f9515a57e3adb
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsBySelector); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->1450); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'0cd634b5-d35d-3a4c-8c1f-9515a57e3adb'); add: (#iconCode->'nil'); add: (#next->#'d35e7fe2-88dc-3442-91c2-3bf94fe89b02'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)