steps
step7b32938cf398a742a1ca38108a4a569b
	<step>

	^ ((Dictionary new) add: (#definition->#'e7757bdb-25c1-5249-95ae-95baac8a366d'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'20 May 2015 2:55:26 pm'); yourself)); add: (#isProperty->false); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'7b32938c-f398-a742-a1ca-38108a4a569b'); add: (#isReference->true); add: (#viewDefinition->nil); yourself)