steps
step04d9ad191a9d044eb09b5ee3ca88e3ff
	<step>

	^ ((Dictionary new) add: (#definition->#'5cffadc0-186c-6549-ba94-4aad637db20e'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#view->ViMultiPaneWidget); add: (#creationTimeStamp->'29 January 2015 9:06:41 am'); add: (#isNew->false); yourself)); add: (#isProperty->true); add: (#next->#'72e942e1-e871-e049-81f1-f42f104b8324'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'04d9ad19-1a9d-044e-b09b-5ee3ca88e3ff'); add: (#isReference->false); add: (#viewDefinition->#treePlain); yourself)