steps
step417f42f73ebf834ea6ec8cecfbb75b84
	<step>

	^ ((Dictionary new) add: (#definition->#'052a74fa-7606-c941-9a37-1dead31a8a3e'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->900); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'417f42f7-3ebf-834e-a6ec-8cecfbb75b84'); add: (#iconCode->'UiSilkIcons packageIcon'); add: (#next->#'35a0fb8d-428f-1b4e-9c15-e5fe341d5e61'); add: (#viewDefinition->#treeView); add: (#label->'Packages and Categories'); yourself)