steps
step49d802a13f51514eaccf7854f6e8d622
	<step>

	^ ((Dictionary new) add: (#definition->#'8f0021f9-2ab1-4144-b627-335dfe0f2977'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->5570); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 February 2014 12:40:04 pm'); yourself)); add: (#id->#'49d802a1-3f51-514e-accf-7854f6e8d622'); add: (#iconCode->'nil'); add: (#next->#'a0dd65c0-687c-174a-9c11-369b8badfa15'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)