steps
step5401af50ff0b9941b85035ffa4179d50
	<step>

	^ ((Dictionary new) add: (#definition->#'2415ac87-fed6-5649-afa6-88ac79e1aa8d'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->1180); add: (#headerText->'T'); yourself)); add: (#id->#'5401af50-ff0b-9941-b850-35ffa4179d50'); add: (#iconCode->'nil'); add: (#next->#'5c2e7b34-3c99-9341-badb-b111a003abb4'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)