steps
stepformattedQueries
	<step>

	^ ((Dictionary new) add: (#definition->#'7e9d16d4-7549-f441-bf3d-74fbe6115750'); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->6060); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'11 February 2014 1:01:49 pm'); add: (#copyOfStep->#identity); yourself)); add: (#id->#formattedQueries); add: (#iconCode->'nil'); add: (#next->#'6add0b0f-920d-894b-8c60-7e275fc7080f'); add: (#viewDefinition->#treeView); add: (#label->'Formatted Queries'); yourself)