steps
step578f3d1fbdb5b04b85fffe0c848c6af5
	<step>

	^ ((Dictionary new) add: (#definition->#'f88512ad-81dd-ac4c-8e82-ff004696fed6'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'000000'); add: (#creationTimeStamp->'19 September 2013 3:50:52 pm'); add: (#creationAuthor->'mt'); add: (#priority->4040); add: (#headerText->'Type'); yourself)); add: (#id->#'578f3d1f-bdb5-b04b-85ff-fe0c848c6af5'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)