steps
stepbcf11958a60a6546a0c1c08cb69f40df
	<step>

	^ ((Dictionary new) add: (#definition->#'bd23428f-5e24-8b4e-a1da-f1a684f38d81'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->4140); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'24 September 2013 8:01 am'); yourself)); add: (#id->#'bcf11958-a60a-6546-a0c1-c08cb69f40df'); add: (#iconCode->'nil'); add: (#next->#'800f6eb3-5d93-3a44-b9d4-965af821cc38'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)