steps
step045e9d2cb29a4641b942d4b769535d4a
	<step>

	^ ((Dictionary new) add: (#definition->#iconAndLabel); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->6500); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 July 2014 2:13:16 pm'); yourself)); add: (#id->#'045e9d2c-b29a-4641-b942-d4b769535d4a'); add: (#iconCode->'nil'); add: (#next->#'ed827037-94ca-9a45-b223-3148d0dc9fc9'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)