steps
step5b87b137752eb346a7fb46bd574a4330
	<step>

	^ ((Dictionary new) add: (#definition->#'12f30814-5104-df41-8cad-fee1eb31343d'); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->3860); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 September 2013 7:00:36 pm'); add: (#copyOfStep->#'fd3c0b79-142a-ee4e-9f27-4da12eba946f'); yourself)); add: (#id->#'5b87b137-752e-b346-a7fb-46bd574a4330'); add: (#iconCode->'nil'); add: (#next->#'acc3ad31-29c9-cd45-8ccc-e801aaadd858'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)