steps
step38cdc208e7080b47b9d5d9fb2a99fce1
	<step>

	^ ((Dictionary new) add: (#definition->#'81d4bba3-fa92-5a44-9759-d980ccef208a'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->1920); add: (#headerText->'Protocol'); yourself)); add: (#id->#'38cdc208-e708-0b47-b9d5-d9fb2a99fce1'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)