steps
step475707d222033e46886ef4249d390390
	<step>

	^ ((Dictionary new) add: (#definition->#'8d04e4fb-3e37-ca47-9678-68392bce2475'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->3920); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 September 2013 9:12:52 pm'); add: (#headerText->'Location'); yourself)); add: (#id->#'475707d2-2203-3e46-886e-f4249d390390'); add: (#iconCode->'nil'); add: (#next->#'8eec0dd8-6d7c-d54f-8d45-ff176d005f1b'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)