steps
stepdf738ebd688287439dbb746c1bba0641
	<step>

	^ ((Dictionary new) add: (#definition->#'a49c3cf6-94f7-3441-a8cc-666a06f23d42'); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->2610); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'df738ebd-6882-8743-9dbb-746c1bba0641'); add: (#iconCode->'nil'); add: (#next->#'343a2282-782f-4d4b-8e98-ab5ca5e0fd36'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)