steps
step1d71708a545679429c1cc6c37baec8c9
	<step>

	^ ((Dictionary new) add: (#definition->#'058d3529-d310-e847-b148-dadf47ff31b9'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->5940); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 February 2014 4:12:57 pm'); yourself)); add: (#id->#'1d71708a-5456-7942-9c1c-c6c37baec8c9'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)