steps
stepd003dd9abd31c14fbc56ea9cd47b3bb1
	<step>

	^ ((Dictionary new) add: (#definition->#'8d2906a9-399e-5747-8b83-d1b9309cb1db'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->ViExperiment); add: (#creationAuthor->'mt'); add: (#view->ViExperimentView); add: (#creationTimeStamp->'20 May 2015 10:56:21 pm'); add: (#priority->10); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->nil); add: (#label->'Experiment'); add: (#iconCode->'nil'); add: (#id->#'d003dd9a-bd31-c14f-bc56-ea9cd47b3bb1'); add: (#isReference->false); add: (#viewDefinition->nil); yourself)