steps
step2d85f346bb1a7248b288a0b9d762b977
	<step>

	^ ((Dictionary new) add: (#definition->#'61579026-79be-ff43-b0de-f9ca7b8e6c4c'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->920); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'2d85f346-bb1a-7248-b288-a0b9d762b977'); add: (#iconCode->'nil'); add: (#next->#'63c84001-9d52-ee47-b4a7-446b7242ea74'); add: (#viewDefinition->#treeView); add: (#label->'Large Methods'); yourself)