steps
stepc9208feb9579b54e83a343ffb87e69fa
	<step>

	^ ((Dictionary new) add: (#definition->#'91921a92-85c1-4046-bacf-5b8d2c22f236'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->6260); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'11 February 2014 1:01:49 pm'); add: (#copyOfStep->#identity); yourself)); add: (#id->#'c9208feb-9579-b54e-83a3-43ffb87e69fa'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#textView); add: (#label->'Diff'); yourself)