steps
step3db4c5e34863b44d8ff1423f40829e70
	<step>

	^ ((Dictionary new) add: (#definition->#'95c882ee-df97-bb48-bfb5-fadeedf09205'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->140); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'3db4c5e3-4863-b44d-8ff1-423f40829e70'); add: (#iconCode->'UiFugueIcons scriptsTextIcon'); add: (#next->#'d89cc752-73e4-0742-ac29-eb770d5d8fc5'); add: (#viewDefinition->#treeView); add: (#label->'Methods'); yourself)