steps
steped426c8eaf11614e83894c0d36c6c86b
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsAsStrings); add: (#class->ViQueryGroupSortStep); add: (#properties->((Dictionary new) add: (#priority->2240); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'ed426c8e-af11-614e-8389-4c0d36c6c86b'); add: (#iconCode->'nil'); add: (#next->#'07540f0c-6cda-d44e-b272-9d619e7cdcff'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)