steps
step181275cdbd0c36429b0d9373d885260e
	<step>

	^ ((Dictionary new) add: (#definition->#category); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->2840); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'181275cd-bd0c-3642-9b0d-9373d885260e'); add: (#iconCode->'nil'); add: (#next->#'2a56df61-69c8-3349-9b25-d5afffcb60b1'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)