steps
stepb0a9b90b4e094242901f0787b2807798
	<step>

	^ ((Dictionary new) add: (#definition->#'6cd6a18b-1a41-b542-83de-912a9e7bca74'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->3650); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 September 2013 10:03:33 am'); yourself)); add: (#id->#'b0a9b90b-4e09-4242-901f-0787b2807798'); add: (#iconCode->'nil'); add: (#next->#'9d1dec9f-cad6-de45-b2c2-03c8cd59b8d7'); add: (#viewDefinition->#treeViewExtended); add: (#label->'Diff to default archive'); yourself)