steps
step931fac93b85b1c42bcc2435f7486a3e6
	<step>

	^ ((Dictionary new) add: (#definition->#'9b5abd16-76eb-5248-b99e-5ae7c8cce33b'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->4300); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'16 November 2013 4:58:02 pm'); yourself)); add: (#id->#'931fac93-b85b-1c42-bcc2-435f7486a3e6'); add: (#iconCode->'nil'); add: (#next->#'0f263fa9-7393-0a45-ade8-fdacace2318a'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)