steps
step8c98ea105364be4bb343835196faca7e
	<step>

	^ ((Dictionary new) add: (#definition->#'6f38796b-7a6d-494e-926e-a2dc03b50f2e'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->6370); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'2 June 2014 3:50:32 pm'); yourself)); add: (#id->#'8c98ea10-5364-be4b-b343-835196faca7e'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)