steps
step0bf4254ac61595498fa0434b920f8c2a
	<step>

	^ ((Dictionary new) add: (#definition->#'06752cb1-e5f3-b847-8946-50a90ce30938'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->5620); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 February 2014 3:56:01 pm'); yourself)); add: (#id->#'0bf4254a-c615-9549-8fa0-434b920f8c2a'); add: (#iconCode->'nil'); add: (#next->#'a4ac81fc-d21c-7240-abf8-68d76d2dc175'); add: (#viewDefinition->#listView); add: (#label->'System categories'); yourself)