steps
step5e29ea34ab1f4c40912236f7572fc535
	<step>

	^ ((Dictionary new) add: (#definition->#'f08f246c-85f1-3d49-90d6-0dd64af2c127'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->ViQueryStepDefinition); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'8 June 2015 6:08:58 pm'); add: (#isNew->false); yourself)); add: (#isProperty->true); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'5e29ea34-ab1f-4c40-9122-36f7572fc535'); add: (#isReference->false); yourself)