steps
step71dfa65f9c442a418cf308ac2c9154d8
	<step>

	^ ((Dictionary new) add: (#definition->#'9d5a860e-218e-3f48-b99c-c85e33aa4e5f'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->1710); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'71dfa65f-9c44-2a41-8cf3-08ac2c9154d8'); add: (#iconCode->'nil'); add: (#next->#'f45253e3-1e61-2344-8ebb-69fad9e592af'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)