steps
step494bc6a5c09dfc4fb22f37955f890e49
	<step>

	^ ((Dictionary new) add: (#definition->#'595f22af-5b39-df47-82fc-bfe9343c2c57'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->1640); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#headerText->'Implementor'); yourself)); add: (#id->#'494bc6a5-c09d-fc4f-b22f-37955f890e49'); add: (#iconCode->'nil'); add: (#next->#'31d2b64c-44d3-5c47-964f-83802a1f927f'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)