steps
step5a31d872749d6d4d8b6f4075ef69c27b
	<step>

	^ ((Dictionary new) add: (#definition->#'e69a74c0-8b63-6e47-ad84-74d68829579b'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->260); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'5a31d872-749d-6d4d-8b6f-4075ef69c27b'); add: (#iconCode->'nil'); add: (#next->#'a00864ac-a9da-7b4c-8566-84d8a849fe5e'); add: (#viewDefinition->#treeView); add: (#label->'Methods (full w/o ProtoObject, Object)'); yourself)