steps
step88139d33b92eb047953e68600692e3a7
	<step>

	^ ((Dictionary new) add: (#definition->#'514e33c1-49ef-db4a-ab27-1b67d793b46b'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->5870); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'11 February 2014 1:01:49 pm'); add: (#copyOfStep->#'01ee1d9f-96a4-3848-870d-e4f6e865c0a6'); yourself)); add: (#id->#'88139d33-b92e-b047-953e-68600692e3a7'); add: (#iconCode->'nil'); add: (#next->#'989369d4-032d-1d49-adae-b70b2f36ea1e'); add: (#viewDefinition->#textView); add: (#label->nil); yourself)