steps
stepe65452ed42156b4db57885e9c478d9d5
	<step>

	^ ((Dictionary new) add: (#definition->#'514e33c1-49ef-db4a-ab27-1b67d793b46b'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->5800); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'24 February 2014 10:39:45 am'); yourself)); add: (#id->#'e65452ed-4215-6b4d-b578-85e9c478d9d5'); add: (#iconCode->'nil'); add: (#next->#'e412ba63-4769-6448-bdf0-693f6bf51a84'); add: (#viewDefinition->#textView); add: (#label->nil); yourself)