steps
stepb9b1a3c9cfc9ea4ba67b6a2ce4d34918
	<step>

	^ ((Dictionary new) add: (#definition->#'10e4c6d0-30b8-1549-afbb-d936fb6c7a9c'); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->4170); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'7 November 2013 10:51:34 am'); yourself)); add: (#id->#'b9b1a3c9-cfc9-ea4b-a67b-6a2ce4d34918'); add: (#iconCode->'nil'); add: (#next->#'d8173faa-7721-b340-afaa-a4d664743096'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)