steps
step1e371f1464f0004c94cae667218e38e4
	<step>

	^ ((Dictionary new) add: (#definition->#'c70a89eb-72fb-1846-be69-841c75c0a435'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->6250); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'6 June 2014 4:25:10 pm'); yourself)); add: (#id->#'1e371f14-64f0-004c-94ca-e667218e38e4'); add: (#iconCode->'nil'); add: (#next->#'91c9c5aa-8933-524c-908c-609b3a1fc00a'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)