steps
stepad40279566daaa47aa37eb2e5d035363
	<step>

	^ ((Dictionary new) add: (#definition->#'07e0d51c-6985-144c-bc8d-08c8e9bb8d4d'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->5230); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 February 2014 12:43:11 pm'); yourself)); add: (#id->#'ad402795-66da-aa47-aa37-eb2e5d035363'); add: (#iconCode->'nil'); add: (#next->#'94740283-5bf2-514e-8eef-b18ce867137a'); add: (#viewDefinition->#listView); add: (#label->'All test classes'); yourself)