steps
step9727e8f33a467549adebb57ccead9114
	<step>

	^ ((Dictionary new) add: (#definition->#'720a8d90-f7c1-334e-a4ea-5094ba285a8d'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->180); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'9727e8f3-3a46-7549-adeb-b57ccead9114'); add: (#iconCode->'nil'); add: (#next->#implementors); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)