steps
stepformattedQueries
	<step>

	^ ((Dictionary new) add: (#definition->#'67e6843f-98b0-044f-8903-62eacc3a5308'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#copyOfStep->#identity); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'11 February 2014 1:01:49 pm'); yourself)); add: (#id->#formattedQueries); add: (#iconCode->'nil'); add: (#next->#'cd563aef-8bdc-1746-b414-80fad70add58'); add: (#viewDefinition->#treeView); add: (#label->'Formatted Queries'); yourself)