steps
steped98259d40bab843bb324e77d29904ec
	<step>

	^ ((Dictionary new) add: (#definition->#'a340d182-121d-a841-9378-c6dd65102090'); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->1200); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'ed98259d-40ba-b843-bb32-4e77d29904ec'); add: (#iconCode->'nil'); add: (#next->#'fd62bf2f-377c-e64a-b62a-4f2399a054e1'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)