steps
stepa5bdd4b483af304c89f8f7f04e06f35c
	<step>

	^ ((Dictionary new) add: (#definition->#'07203f12-f1b6-9746-9884-0b9e8f1a4f6b'); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->5730); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'20 February 2014 2:04:23 pm'); yourself)); add: (#id->#'a5bdd4b4-83af-304c-89f8-f7f04e06f35c'); add: (#iconCode->'nil'); add: (#next->#'6c7c1766-19c3-924c-954e-2cc22258ca1c'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)