steps
stepartifacts
	<step>

	^ ((Dictionary new) add: (#definition->#'e06097d2-1a38-4845-ae0e-d68113bd2be5'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#view->ViArtifactListView2); add: (#creationTimeStamp->'20 October 2014 7:29:40 am'); add: (#priority->21); yourself)); add: (#isProperty->false); add: (#next->#'11ba89fb-aa6d-264a-92c1-cba5506abae1'); add: (#label->'Artifacts'); add: (#iconCode->'nil'); add: (#id->#artifacts); add: (#viewDefinition->#treePlain); yourself)