steps
stepb2b4ae7898c6784491b087f17deed68c
	<step>

	^ ((Dictionary new) add: (#definition->#'7fbeb020-17a5-a44b-8452-d00317b036af'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->4630); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'10 January 2014 12:44:36 pm'); yourself)); add: (#id->#'b2b4ae78-98c6-7844-91b0-87f17deed68c'); add: (#iconCode->'nil'); add: (#next->#'b0e115e3-6fb8-f84c-87f4-f21d46eb5c7e'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)