steps
step6cd4db5cd2de844892b74f3c52589cf8
	<step>

	^ ((Dictionary new) add: (#definition->#'64a657ed-d4df-e146-955a-7dfe7e5570db'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->4670); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#'728402d7-f870-e743-8d2a-abf2353efba1'); yourself)); add: (#id->#'6cd4db5c-d2de-8448-92b7-4f3c52589cf8'); add: (#iconCode->'nil'); add: (#next->#'61afd65e-d943-5642-bd31-15492112b6ad'); add: (#viewDefinition->#treeView); add: (#label->'Count Instance Variables'); yourself)