steps
stepe548783510a59d408ab06f95df9b5740
	<step>

	^ ((Dictionary new) add: (#definition->#'71a073f6-23bc-c947-8277-cf251478913e'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->6110); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'21 May 2014 5:56:13 pm'); yourself)); add: (#id->#'e5487835-10a5-9d40-8ab0-6f95df9b5740'); add: (#iconCode->'nil'); add: (#next->#'b1afac3a-0000-8544-9dce-ebfda96b30b6'); add: (#viewDefinition->#treeView); add: (#label->'DBLP Search'); yourself)