steps
step757cd24a516ebf45ad50d29635e9bbee
	<step>

	^ ((Dictionary new) add: (#definition->#'325e9e39-f956-f342-8b16-5d6be68397d0'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->6680); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'23 July 2014 2:45:39 pm'); yourself)); add: (#id->#'757cd24a-516e-bf45-ad50-d29635e9bbee'); add: (#iconCode->'nil'); add: (#next->#'dc8af77b-cb54-d74d-a9c2-fbd92c4b2a44'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)