steps
stepsimilarDefinitions
	<step>

	^ ((Dictionary new) add: (#definition->#'bcbc9f73-3ca4-0d4e-9933-e2a6d2ea32e4'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->650); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'4 September 2013 12:59:07 pm'); yourself)); add: (#id->#similarDefinitions); add: (#iconCode->'nil'); add: (#next->#'754c7a1e-5b33-a842-8a8a-c5f6eef88890'); add: (#viewDefinition->#treeViewExtended); add: (#label->'Similar Map Definitions'); yourself)