steps
stepcf440614e202124f830d3b4a1d9eef00
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsAsStrings); add: (#class->ViQueryGroupSortStep); add: (#properties->((Dictionary new) add: (#priority->1630); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'cf440614-e202-124f-830d-3b4a1d9eef00'); add: (#iconCode->'nil'); add: (#next->#'494bc6a5-c09d-fc4f-b22f-37955f890e49'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)