steps
stepbce4eb13a02d144e96b2cd2944b85fee
	<step>

	^ ((Dictionary new) add: (#definition->#'d92c0fde-916e-364d-8dc7-9c4cdc7e5d6e'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->5170); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 February 2014 10:12:18 am'); yourself)); add: (#id->#'bce4eb13-a02d-144e-96b2-cd2944b85fee'); add: (#iconCode->'UiFugueIcons magnifierMediumIcon'); add: (#next->#'c50d0c14-b3eb-cf47-9e8a-7ba23cb2c4dd'); add: (#viewDefinition->#multiPane); add: (#label->'Inspector'); yourself)