steps
stepd9a22b3cf29a7840bb49c3f6d664b189
	<step>

	^ ((Dictionary new) add: (#definition->#'c7130d64-9f4e-7247-bd60-9214f1d0f522'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 4:21:57 pm'); add: (#creationAuthor->'mt'); add: (#priority->3220); add: (#headerText->'Count'); yourself)); add: (#id->#'d9a22b3c-f29a-7840-bb49-c3f6d664b189'); add: (#iconCode->'nil'); add: (#next->#'73012cd9-6457-9649-bb16-3f77f5dea0d2'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)