steps
step63358b8e81f81445b9a65e43e6316331
	<step>

	^ ((Dictionary new) add: (#definition->#allMethodsForClass); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->130); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'63358b8e-81f8-1445-b9a6-5e43e6316331'); add: (#iconCode->'UiDiagonaIcons icon0135Normal'); add: (#next->#'61009cae-b7fb-434c-bfab-3a240dc5768a'); add: (#viewDefinition->#tileView); add: (#label->'Icons'); yourself)