steps
stepimplementors
	<step>

	^ ((Dictionary new) add: (#definition->#'43a540d6-480d-1243-9f91-69cbaedd58ab'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->ByteSymbol); add: (#creationTimeStamp->'20 May 2015 2:36:10 pm'); add: (#view->ViTreeViewExtended); add: (#creationAuthor->'mt'); add: (#out->Set); add: (#copyOf->#senders); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->#'8c058833-34df-6a4c-a717-5b1be5ea7200'); add: (#label->'Implementors'); add: (#iconCode->'nil'); add: (#id->#implementors); add: (#isReference->false); yourself)