steps
step78e13ff4d0931140b575be2225a6eaf7
	<step>

	^ ((Dictionary new) add: (#definition->#'f677255c-a160-7b4a-9153-982f6f991f80'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->5400); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'14 February 2014 10:53:40 am'); add: (#headerText->#cU); yourself)); add: (#id->#'78e13ff4-d093-1140-b575-be2225a6eaf7'); add: (#iconCode->'nil'); add: (#next->#'3a47c56d-3e11-344a-8b45-cc59f6ba7fb5'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)