steps
stepcf7fdd6602719544b4a93ecca1e4a611
	<step>

	^ ((Dictionary new) add: (#definition->#'4455276a-46f3-b44c-84b8-7d1a0ab966e7'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->6720); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'23 July 2014 2:54:01 pm'); yourself)); add: (#id->#'cf7fdd66-0271-9544-b4a9-3ecca1e4a611'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)