steps
step9af0df5a068aa6499aa4230c1f0217cc
	<step>

	^ ((Dictionary new) add: (#definition->#'699d78cd-6dca-ff43-b630-3cdfecd1d06f'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->4260); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'8 November 2013 4:30:17 pm'); yourself)); add: (#id->#'9af0df5a-068a-a649-9aa4-230c1f0217cc'); add: (#iconCode->'nil'); add: (#next->#'47204d81-9a24-5149-ad07-01d582da03b4'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)