steps
stepbd2cba9d0fb42e479e837e3ddec6640f
	<step>

	^ ((Dictionary new) add: (#definition->#'f09a7901-d868-6c4d-a809-bd45bde16a09'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->2960); add: (#headerText->'Time'); yourself)); add: (#id->#'bd2cba9d-0fb4-2e47-9e83-7e3ddec6640f'); add: (#iconCode->'nil'); add: (#next->#'f977b925-bca8-8e41-8e7a-33672b08eb1d'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)