steps
stepdd7cc16278d359468ad07e30f7b46f6d
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsBySelector); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->1260); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#'dd7cc162-78d3-5946-8ad0-7e30f7b46f6d'); yourself)); add: (#id->#'dd7cc162-78d3-5946-8ad0-7e30f7b46f6d'); add: (#iconCode->'nil'); add: (#next->#'92eb4914-ce3c-1f4f-b813-4bd8cf3c75a6'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)