steps
step0d87f2242efe7b449e62ddef7dfe44b9
	<step>

	^ ((Dictionary new) add: (#definition->#'baae0367-2eb9-2745-b6af-c747b95925ac'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->170); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'0d87f224-2efe-7b44-9e62-ddef7dfe44b9'); add: (#iconCode->'nil'); add: (#next->#'6d7f9bea-0e5c-c94c-a4cb-7c20ea715fa8'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)