steps
step5b4abb4561e5164d96ae140ddcba171d
	<step>

	^ ((Dictionary new) add: (#definition->#'c5e79a55-1429-9047-b916-9f616017f84a'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->4690); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#'728402d7-f870-e743-8d2a-abf2353efba1'); yourself)); add: (#id->#'5b4abb45-61e5-164d-96ae-140ddcba171d'); add: (#iconCode->'nil'); add: (#next->#'60f99406-f09f-354a-9ed2-91ddd9060fc4'); add: (#viewDefinition->#treeView); add: (#label->'Referenced Behaviors'); yourself)