steps
step0da6c0f01c3d3e41a6708bc5919f788a
	<step>

	^ ((Dictionary new) add: (#definition->#'d0608999-e6c6-b648-b748-5cdb7b3c81b3'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->2900); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'0da6c0f0-1c3d-3e41-a670-8bc5919f788a'); add: (#iconCode->'nil'); add: (#next->#'4b707439-66b1-c64b-805a-80c63759305e'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)