steps
step31297e2396f54144a0413821519b9f1e
	<step>

	^ ((Dictionary new) add: (#definition->#'fef44613-dcb6-db48-b26e-678159464e39'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->770); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 September 2013 7:37:43 pm'); yourself)); add: (#id->#'31297e23-96f5-4144-a041-3821519b9f1e'); add: (#iconCode->'UiSilkIcons carDeleteIcon'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->'Unused Classes'); yourself)