steps
step648936db9a22ed48a05e4f1c8c9c94fd
	<step>

	^ ((Dictionary new) add: (#definition->#'308ec58a-07f8-bc41-91de-d5f7e6f778ae'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->2700); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'648936db-9a22-ed48-a05e-4f1c8c9c94fd'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)