steps
steprefToStep
	<step>

	^ ((Dictionary new) add: (#definition->#'9bcd7a3d-1618-064f-856d-386ada70cdca'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->530); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'15 September 2013 5:33:06 pm'); yourself)); add: (#id->#refToStep); add: (#iconCode->'UiFugueIcons arrowStepIcon'); add: (#next->#'e6902a58-ee3c-7a49-9375-8c1501d23175'); add: (#viewDefinition->#treeView); add: (#label->'References'); yourself)