steps
step59e1a354ea9e3d4db4c670d3a9eb6d48
	<step>

	^ ((Dictionary new) add: (#definition->#'2e76e4da-8a81-b141-bbbc-e1c438ed5134'); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->3100); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'59e1a354-ea9e-3d4d-b4c6-70d3a9eb6d48'); add: (#iconCode->'nil'); add: (#next->#'d65616b9-310e-3c4d-88d4-b82f6ff8c6f5'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)