steps
step3cd2b495be4e004181d833250b0006e8
	<step>

	^ ((Dictionary new) add: (#definition->#'eb01a990-c76c-494e-aba1-18ba6d51bb19'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->680); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'3cd2b495-be4e-0041-81d8-33250b0006e8'); add: (#iconCode->'UiSilkIcons worldIcon'); add: (#next->#'df738ebd-6882-8743-9dbb-746c1bba0641'); add: (#viewDefinition->#treeView); add: (#label->'MC Repositories'); yourself)