steps
step3dbca45def245e49975e38f04a9a7729
	<step>

	^ ((Dictionary new) add: (#definition->#'f054ff68-004c-ac4a-8a95-e8b6414caa98'); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->4510); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'4 December 2013 8:37:28 am'); yourself)); add: (#id->#'3dbca45d-ef24-5e49-975e-38f04a9a7729'); add: (#iconCode->'nil'); add: (#next->#'8ed52473-9493-2142-94be-054478bc571b'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)