steps
step53385c7bcff8c8428efde43b039db34b
	<step>

	^ ((Dictionary new) add: (#definition->#'7c3c31a6-c625-d741-9241-e745aec8f9e9'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->4490); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 November 2013 5:07:13 pm'); yourself)); add: (#id->#'53385c7b-cff8-c842-8efd-e43b039db34b'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)