steps
step31eeb1cd153aa246b7d86a6b7f6a95b8
	<step>

	^ ((Dictionary new) add: (#definition->#iconAndLabel); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->8410); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'15 November 2014 4:29:41 pm'); yourself)); add: (#id->#'31eeb1cd-153a-a246-b7d8-6a6b7f6a95b8'); add: (#iconCode->'nil'); add: (#next->#'2af25f9b-ebc0-104e-b6f8-795b2094d0ee'); add: (#viewDefinition->#treePlain); add: (#label->nil); yourself)