steps
step42ef8b6b8cf0da4ab0750fb0146d805c
	<step>

	^ ((Dictionary new) add: (#definition->#'f9974083-86d5-d54f-9ee0-ba85d5b22720'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->2790); add: (#headerText->'Size'); yourself)); add: (#id->#'42ef8b6b-8cf0-da4a-b075-0fb0146d805c'); add: (#iconCode->'nil'); add: (#next->#'1cd2a5a3-05f3-9046-8fd2-06f0a076f80b'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)