steps
step641df55bdc10f74486f32f5eb3f970ab
	<step>

	^ ((Dictionary new) add: (#definition->#iconAndLabel); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->2310); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#headerText->'Comment'); yourself)); add: (#id->#'641df55b-dc10-f744-86f3-2f5eb3f970ab'); add: (#iconCode->'nil'); add: (#next->#'c185247b-7a50-f045-a2a1-b24c4e26d2b4'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)