steps
step7f7cb928c2c5c8408c91995fa40b1fd5
	<step>

	^ ((Dictionary new) add: (#definition->#category); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->4390); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 November 2013 4:22:46 pm'); yourself)); add: (#id->#'7f7cb928-c2c5-c840-8c91-995fa40b1fd5'); add: (#iconCode->'nil'); add: (#next->#'f54c9a3b-47b7-6a42-a9a4-1843fbd23ecd'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)