steps
step56d4e61dee76514bbc24e352a53b0d46
	<step>

	^ ((Dictionary new) add: (#definition->#'66cd48ee-25f8-f845-b648-77d9a1ca2dfe'); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->2490); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'56d4e61d-ee76-514b-bc24-e352a53b0d46'); add: (#iconCode->'nil'); add: (#next->#'358482e0-2cf1-e948-a657-0a354613e3ad'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)