steps
step217e17d656aaff44a6d32e3bf316d470
	<step>

	^ ((Dictionary new) add: (#definition->#'c7f13eaf-02b3-7046-8b08-c7d1a5a911dd'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#copyOfStep->#'bec0a4ef-c091-a844-88ef-be4ea489648e'); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'217e17d6-56aa-ff44-a6d3-2e3bf316d470'); add: (#iconCode->'nil'); add: (#next->#'b9b1a3c9-cfc9-ea4b-a67b-6a2ce4d34918'); add: (#viewDefinition->#treeView); add: (#label->'Outline'); yourself)