steps
stepe91a39227238d847ab9c4bbd53eece98
	<step>

	^ ((Dictionary new) add: (#definition->#'0b9b9237-a5c1-a54d-854e-19b74df33a48'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'2 May 2014 1:33:49 pm'); yourself)); add: (#id->#'e91a3922-7238-d847-ab9c-4bbd53eece98'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)