steps
step83cf71976cf5554eb5352b2ebf2fb60e
	<step>

	^ ((Dictionary new) add: (#definition->#'729f566c-cae2-d342-b313-485aece0c9f6'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->5820); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'24 February 2014 10:42:49 am'); yourself)); add: (#id->#'83cf7197-6cf5-554e-b535-2b2ebf2fb60e'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#textView); add: (#label->'Byte codes'); yourself)