steps
stepd1e78e71956eb045a15ec15acbbeab0f
	<step>

	^ ((Dictionary new) add: (#definition->#'73283011-8d4b-b64a-badf-a73de5cf00cd'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->5150); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#debuggerStack); yourself)); add: (#id->#'d1e78e71-956e-b045-a15e-c15acbbeab0f'); add: (#iconCode->'UiSilkIcons bugIcon'); add: (#next->#'d1fc3ac8-c0bb-cf47-955a-7e0b24221803'); add: (#viewDefinition->#listView); add: (#label->'Debugger'); yourself)