steps
step056ec0b195a2c641a2444e534358b3be
	<step>

	^ ((Dictionary new) add: (#definition->#methodReferenceToPackageName); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->1410); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'056ec0b1-95a2-c641-a244-4e534358b3be'); add: (#iconCode->'nil'); add: (#next->#'cc847404-aa05-ab40-86cf-2fa34232d0d8'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)