steps
stepdebuggerStack
	<step>

	^ ((Dictionary new) add: (#definition->#'d89728bf-0d8f-1143-9a93-e4a1aad379f4'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->570); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#defaultProperties); yourself)); add: (#id->#debuggerStack); add: (#iconCode->'nil'); add: (#next->#'2fdb319c-765a-1a43-863e-792e14de2c1e'); add: (#viewDefinition->#treeView); add: (#label->'Suspended context'); yourself)