steps
step1258312ca457db40aa96499fda6b7623
	<step>

	^ ((Dictionary new) add: (#definition->#iconAndLabel); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->4410); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#'d9634b11-bde6-1a40-a0b4-7be880afc37a'); yourself)); add: (#id->#'1258312c-a457-db40-aa96-499fda6b7623'); add: (#iconCode->'nil'); add: (#next->#'e68d82d7-0f82-5e4f-990d-0b292c42da7f'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)