steps
step651607ab44293e44b61f86c177f0d112
	<step>

	^ ((Dictionary new) add: (#definition->#'60fafc92-17ae-4b40-af17-c13b35d42e25'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->6630); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'23 July 2014 1:24:01 pm'); yourself)); add: (#id->#'651607ab-4429-3e44-b61f-86c177f0d112'); add: (#iconCode->'nil'); add: (#next->#'0caac112-a8fd-c443-bf49-f884e1be7743'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)