steps
step4483ab73df68ab43b4106de476dc855a
	<step>

	^ ((Dictionary new) add: (#definition->#'1bb9207e-4ee2-404a-8f53-21cee72442ae'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->2210); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'4483ab73-df68-ab43-b410-6de476dc855a'); add: (#iconCode->'nil'); add: (#next->#'85478cdc-dec7-5648-b9af-bbf1c6a6d389'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)