steps
stepcb3aaeaa1407b74d8f5e8838680974b5
	<step>

	^ ((Dictionary new) add: (#definition->#'c3d14c30-79e4-7e49-976d-60b6548c297e'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->6090); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'20 May 2014 11:59:48 am'); yourself)); add: (#id->#'cb3aaeaa-1407-b74d-8f5e-8838680974b5'); add: (#iconCode->'nil'); add: (#next->#'acccd738-5017-5e44-ba68-cc46761670dc'); add: (#viewDefinition->#listView); add: (#label->'Bookmarks'); yourself)