steps
step8bef757c004d634e9db4167dccfb28d7
	<step>

	^ ((Dictionary new) add: (#definition->#'70408b61-4313-c047-9375-8bceac479cca'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->280); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'8bef757c-004d-634e-9db4-167dccfb28d7'); add: (#iconCode->'UiSilkIcons bulletFeedIcon'); add: (#next->#'fca5ba47-1c0b-0b4d-8c61-7eca1715c0c5'); add: (#viewDefinition->#treeView); add: (#label->'Changed/Update Aspects'); yourself)