steps
step5e941cab2cc706469ed0d8493d5d3d0e
	<step>

	^ ((Dictionary new) add: (#definition->#'145841e8-e96d-2243-acbf-2de9c5697829'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->#'000000'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->4470); add: (#copyOfStep->#'d9634b11-bde6-1a40-a0b4-7be880afc37a'); yourself)); add: (#id->#'5e941cab-2cc7-0646-9ed0-d8493d5d3d0e'); add: (#iconCode->'nil'); add: (#next->#'2b264d15-bb33-124e-8b3f-227ef7073118'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)