steps
stepe6e2433adfdd7d4c942aae804d9b9e29
	<step>

	^ ((Dictionary new) add: (#definition->#'6f13ef5f-b902-0443-a009-20bc9eb86762'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->2950); add: (#headerText->'Date'); yourself)); add: (#id->#'e6e2433a-dfdd-7d4c-942a-ae804d9b9e29'); add: (#iconCode->'nil'); add: (#next->#'bd2cba9d-0fb4-2e47-9e83-7e3ddec6640f'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)