steps
step4b813e3f30bb714c965802f84e1ecc5b
	<step>

	^ ((Dictionary new) add: (#definition->#'3e52466c-3192-4f4c-8bee-44755adf71a2'); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->3790); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 September 2013 7:00:56 pm'); yourself)); add: (#id->#'4b813e3f-30bb-714c-9658-02f84e1ecc5b'); add: (#iconCode->'nil'); add: (#next->#'d2ab7b32-7b9e-ba48-808c-ab0e89480da4'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)