steps
step3a47c56d3e11344a8b45cc59f6ba7fb5
	<step>

	^ ((Dictionary new) add: (#definition->#'7625f31d-1d00-8f41-ae4e-d329332e8545'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->5410); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'14 February 2014 10:08:57 am'); add: (#headerText->#cH); yourself)); add: (#id->#'3a47c56d-3e11-344a-8b45-cc59f6ba7fb5'); add: (#iconCode->'nil'); add: (#next->#'02e8ebf6-9dc2-a142-8866-0da7a72f9253'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)