steps
step78d3db6d6a90614d88f9eed2f96f9d05
	<step>

	^ ((Dictionary new) add: (#definition->#'6ffb5883-25e9-4643-a943-7dd170e4169a'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->2530); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'78d3db6d-6a90-614d-88f9-eed2f96f9d05'); add: (#iconCode->'nil'); add: (#next->#'ac1f8319-046c-e04d-b22a-43df31b7abef'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)