steps
step2c2a1c1a775d6244a1e834f737246a95
	<step>

	^ ((Dictionary new) add: (#definition->#'563021ef-44a7-e24e-beb7-6201088a6f24'); add: (#class->ViQueryGroupSortStep); add: (#properties->((Dictionary new) add: (#priority->3530); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 September 2013 7:52:55 pm'); yourself)); add: (#id->#'2c2a1c1a-775d-6244-a1e8-34f737246a95'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)