steps
step91982915045f1f44ab9b723d7bbdf298
	<step>

	^ ((Dictionary new) add: (#definition->#'b9a69dcc-6839-3a4a-a9c3-adae96c6c0e4'); add: (#class->ViQueryGroupSortStep); add: (#properties->((Dictionary new) add: (#priority->1590); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'91982915-045f-1f44-ab9b-723d7bbdf298'); add: (#iconCode->'nil'); add: (#next->#'519d344e-f031-2a43-8e42-34a9f07b61f9'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)