steps
step1f71149b9a667343a8bc932007c75e1f
	<step>

	^ ((Dictionary new) add: (#definition->#'7bdeb06f-bb88-d042-8057-b1f6dccae67b'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->4110); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'23 September 2013 4:51:14 pm'); yourself)); add: (#id->#'1f71149b-9a66-7343-a8bc-932007c75e1f'); add: (#iconCode->'nil'); add: (#next->#'bcf11958-a60a-6546-a0c1-c08cb69f40df'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)