steps
step35a0fb8d428f1b4e9c15e5fe341d5e61
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsAsStrings); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->2980); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'35a0fb8d-428f-1b4e-9c15-e5fe341d5e61'); add: (#iconCode->'nil'); add: (#next->#'b2c2bd30-4cbc-ac47-a5a0-4f683a40bf26'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)