steps
step5636df933a8fea449406e602b99e3101
	<step>

	^ ((Dictionary new) add: (#definition->#'9242cbac-4797-8d4c-9f3f-8d8dc15a9b9e'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->6390); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'12 November 2013 4:58:54 pm'); add: (#copyOfStep->#'fb5f9d48-49cf-774c-921f-e9598b74d2c7'); yourself)); add: (#id->#'5636df93-3a8f-ea44-9406-e602b99e3101'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)