steps
step24f23db6299dcc46bb92693cb90073d6
	<step>

	^ ((Dictionary new) add: (#definition->#'f96e87d9-b692-1b47-a3c7-e03bebbb78f1'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->2630); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'24f23db6-299d-cc46-bb92-693cb90073d6'); add: (#iconCode->'nil'); add: (#next->#'3eddb241-9533-1349-8650-c86422ca0395'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)