steps
stepe91a4f525c394c4cb5c51311bacd5025
	<step>

	^ ((Dictionary new) add: (#definition->#'ce43fc0e-5e43-8649-b12f-662c9ac7d2a7'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'15 June 2015 10:20:57 am'); add: (#copyOf->#'1969ce03-4b3d-cd44-a47f-8a50c1ec3a4b'); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->#'8ebc1c71-5396-204d-98e9-e545b22d0823'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'e91a4f52-5c39-4c4c-b5c5-1311bacd5025'); add: (#isReference->false); yourself)