steps
step7b87d63ff0ab524eb406502817498dbb
	<step>

	^ ((Dictionary new) add: (#definition->#'aa928fd1-48f4-084c-878b-5dd4ad186dbf'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->6340); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'23 May 2014 11:10:45 am'); yourself)); add: (#id->#'7b87d63f-f0ab-524e-b406-502817498dbb'); add: (#iconCode->'nil'); add: (#next->#'ae6288a6-a692-bf42-84df-1174cbab45a4'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)