steps
stepf45b857ee698274cb3d6467851b2d5dc
	<step>

	^ ((Dictionary new) add: (#definition->#'49ccd054-1123-b244-8a4b-6541e357ab53'); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->4440); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 November 2013 4:59:20 pm'); yourself)); add: (#id->#'f45b857e-e698-274c-b3d6-467851b2d5dc'); add: (#iconCode->'nil'); add: (#next->#'5d53db96-8bb9-fb43-921c-fbcba4297063'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)