steps
stepcb96415c4b856247877c589b975e69c8
	<step>

	^ ((Dictionary new) add: (#definition->#'d8985e4a-16e9-8643-9143-06e11ad06235'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->4160); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'14 October 2013 5:10:11 pm'); yourself)); add: (#id->#'cb96415c-4b85-6247-877c-589b975e69c8'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)