steps
stepe6902a58ee3c7a4993758c1501d23175
	<step>

	^ ((Dictionary new) add: (#definition->#iconAndLabel); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->3570); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'15 September 2013 5:35:42 pm'); yourself)); add: (#id->#'e6902a58-ee3c-7a49-9375-8c1501d23175'); add: (#iconCode->'nil'); add: (#next->#'458cbad9-3001-ab46-8458-4bb4c3232229'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)