steps
step3a028d6521d5c7409ce22d16d0b47a42
	<step>

	^ ((Dictionary new) add: (#definition->#'2240fd95-5e9a-f745-97eb-38ddbce8c00e'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->6660); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'23 July 2014 3:01:21 pm'); yourself)); add: (#id->#'3a028d65-21d5-c740-9ce2-2d16d0b47a42'); add: (#iconCode->'nil'); add: (#next->#'b3b87871-7516-5049-b092-72ad966f3216'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)