steps
stepab4af50f105f424d95d136bfd2f47ad3
	<step>

	^ ((Dictionary new) add: (#definition->#'49ccd054-1123-b244-8a4b-6541e357ab53'); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->5020); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'11 February 2014 10:18:31 am'); yourself)); add: (#id->#'ab4af50f-105f-424d-95d1-36bfd2f47ad3'); add: (#iconCode->'nil'); add: (#next->#'c2ce4b2e-2257-424b-af73-a84bb479e75c'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)