steps
step427e325e4f83274faa3db1b3a19ef7e6
	<step>

	^ ((Dictionary new) add: (#definition->#'ce6afbe5-bac6-8d43-8242-117271d13401'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->4060); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 September 2013 5:36:31 pm'); yourself)); add: (#id->#'427e325e-4f83-274f-aa3d-b1b3a19ef7e6'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)