steps
step672be6c0ae0fe9479bfceb4abea195b3
	<step>

	^ ((Dictionary new) add: (#definition->#'b3774c3b-c2b4-c343-a067-b265cf1cb7c8'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'1 June 2015 1:41:53 pm'); yourself)); add: (#isProperty->true); add: (#next->#'2dc88784-e2ef-f54a-a4ea-cf58d48dad44'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'672be6c0-ae0f-e947-9bfc-eb4abea195b3'); add: (#isReference->false); yourself)