steps
stepd1fc3ac8c0bbcf47955a7e0b24221803
	<step>

	^ ((Dictionary new) add: (#definition->#'954dc6a5-194d-a143-9928-d69d3079d47a'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->5500); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#'1bb6538b-c256-b34b-958e-5996dea59092'); yourself)); add: (#id->#'d1fc3ac8-c0bb-cf47-955a-7e0b24221803'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)