steps
stepf28761367eb8e94b864d61f883d28db9
	<step>

	^ ((Dictionary new) add: (#definition->#'4a4ff927-816f-5949-98d5-e55b44483adc'); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->4100); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'23 September 2013 5:09:20 pm'); yourself)); add: (#id->#'f2876136-7eb8-e94b-864d-61f883d28db9'); add: (#iconCode->'nil'); add: (#next->#'1f71149b-9a66-7343-a8bc-932007c75e1f'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)