steps
stepff9ce8ad7d0d4744afbaf53a7a933bd9
	<step>

	^ ((Dictionary new) add: (#definition->#'52e3e131-1ce2-6941-86f6-ba307bf8e791'); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->5770); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'20 February 2014 6:28:37 pm'); yourself)); add: (#id->#'ff9ce8ad-7d0d-4744-afba-f53a7a933bd9'); add: (#iconCode->'nil'); add: (#next->#'11f0e878-14f5-b147-a1c6-e95064e1a62a'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)