steps
stepe5f64c36bb633b4eb5961aac061b81a3
	<step>

	^ ((Dictionary new) add: (#definition->#'0de61e46-38d5-0c40-9a76-c49f1d124a42'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'12 May 2015 5:22:22 pm'); yourself)); add: (#isProperty->false); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'e5f64c36-bb63-3b4e-b596-1aac061b81a3'); add: (#isReference->true); yourself)