steps
step22b325c1285b62428b45bf948f7079a2
	<step>

	^ ((Dictionary new) add: (#definition->#'c6a08f05-9e2f-4542-bdfc-23dbd53617cc'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->2020); add: (#headerText->'Origin'); yourself)); add: (#id->#'22b325c1-285b-6242-8b45-bf948f7079a2'); add: (#iconCode->'nil'); add: (#next->#'d977be3c-9e8a-6740-bff7-63c0bd8811c0'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)