steps
stepdebuggerBindings
	<step>

	^ ((Dictionary new) add: (#definition->#'4f4a5855-cc44-7948-bb20-0381aae59f41'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->430); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#debuggerBindings); add: (#iconCode->'UiFugueIcons blockIcon'); add: (#next->#'89162c9a-8847-4744-abdb-1031a61c2898'); add: (#viewDefinition->#treeView); add: (#label->'Bindings'); yourself)