steps
stepc17a5204307f044bb7845a13673d0684
	<step>

	^ ((Dictionary new) add: (#definition->#'b6d3bfa5-95fc-2d4e-afdb-b0ff8f7ac905'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->3580); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'15 September 2013 5:43:59 pm'); yourself)); add: (#id->#'c17a5204-307f-044b-b784-5a13673d0684'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)