steps
step7b14d20029788b408e544c9a03cb23f7
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsBySelector); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->1400); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'7b14d200-2978-8b40-8e54-4c9a03cb23f7'); add: (#iconCode->'nil'); add: (#next->#'056ec0b1-95a2-c641-a244-4e534358b3be'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)