steps
step3d9d6bb7e6bc5444b1a396219e51fe10
	<step>

	^ ((Dictionary new) add: (#definition->#'ecc82096-e22c-1446-9001-ba0f0f6d0be2'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->4900); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'6 September 2013 8:38:52 pm'); add: (#copyOfStep->#'69e497c2-4f93-4d49-84b1-94178c53e847'); yourself)); add: (#id->#'3d9d6bb7-e6bc-5444-b1a3-96219e51fe10'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)