steps
stepce6fede41334d84b81765e5a33fd162f
	<step>

	^ ((Dictionary new) add: (#definition->#'38b1fcda-ea44-fc4b-acfc-118dc0d54db5'); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->2180); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'ce6fede4-1334-d84b-8176-5e5a33fd162f'); add: (#iconCode->'nil'); add: (#next->#'0547837e-8ef9-cd4b-827d-5574ea1e1c91'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)