steps
stepsnippets
	<step>

	^ ((Dictionary new) add: (#definition->#'46e862b1-69aa-e348-ac02-6f21384543b3'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->Object); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'8 June 2015 5:17:29 pm'); add: (#view->ViTreeViewExtended); add: (#outputKind->ViQueryStepDefinition); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->#'5e29ea34-ab1f-4c40-9122-36f7572fc535'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#snippets); add: (#isReference->false); add: (#viewDefinition->nil); yourself)