steps
stepca04a42d26a99947afa01aa1b04bfca1
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsAsStrings); add: (#class->ViQueryGroupSortStep); add: (#properties->((Dictionary new) add: (#priority->2120); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'ca04a42d-26a9-9947-afa0-1aa1b04bfca1'); add: (#iconCode->'nil'); add: (#next->#'f88f0794-d8d8-6c4d-8b7a-445cc52f66df'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)