steps
step736c249139ee9f4c9abc4d4c87ef1a03
	<step>

	^ ((Dictionary new) add: (#definition->#origin); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->4940); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#'d9634b11-bde6-1a40-a0b4-7be880afc37a'); yourself)); add: (#id->#'736c2491-39ee-9f4c-9abc-4d4c87ef1a03'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)