steps
stepd0704ef90a640d4496817487f8ee4e7b
	<step>

	^ ((Dictionary new) add: (#definition->#histogram); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->4590); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'3 January 2014 11:53:42 am'); yourself)); add: (#id->#'d0704ef9-0a64-0d44-9681-7487f8ee4e7b'); add: (#iconCode->'nil'); add: (#next->#'29a5b770-b982-f548-b9d2-9842b501cff9'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)