steps
stepe62241f332bff545a0b1a632d1e53911
	<step>

	^ ((Dictionary new) add: (#definition->#identity); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->370); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'e62241f3-32bf-f545-a0b1-a632d1e53911'); add: (#iconCode->'nil'); add: (#next->#'da240e4d-2791-be42-a47a-879ff7f15f76'); add: (#viewDefinition->#treeView); add: (#label->'Pretty print class comments'); yourself)