steps
stepe62a3f594f571c4ab8f12ea49415d52e
	<step>

	^ ((Dictionary new) add: (#definition->#'86ecc589-bfac-754a-92b4-69704fa9b84b'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->3400); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 September 2013 7:12:18 pm'); yourself)); add: (#id->#'e62a3f59-4f57-1c4a-b8f1-2ea49415d52e'); add: (#iconCode->'nil'); add: (#next->#'72bf6830-31d8-1b42-9ddc-991381a326f0'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)