steps
step600d833722a7304b8565430e818154ce
	<step>

	^ ((Dictionary new) add: (#definition->#'06752cb1-e5f3-b847-8946-50a90ce30938'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->5640); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 February 2014 3:56:01 pm'); add: (#copyOfStep->#'0bf4254a-c615-9549-8fa0-434b920f8c2a'); yourself)); add: (#id->#'600d8337-22a7-304b-8565-430e818154ce'); add: (#iconCode->'nil'); add: (#next->#'0d396a44-b27e-f545-a69d-d25485dfe138'); add: (#viewDefinition->#multiPane); add: (#label->'Classes by Category'); yourself)