steps
step6847631141ac34459df5321d8834e6f7
	<step>

	^ ((Dictionary new) add: (#definition->#'547e6ee1-cc59-9d4d-b9bd-104df881ca75'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->1140); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#headerText->'Object'); yourself)); add: (#id->#'68476311-41ac-3445-9df5-321d8834e6f7'); add: (#iconCode->'nil'); add: (#next->#'5a2edad8-c307-144a-a4b6-dfdddd2c429d'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)