steps
stepbec0a4efc091a84488efbe4ea489648e
	<step>

	^ ((Dictionary new) add: (#definition->#allMethodsForClass); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->100); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#'bec0a4ef-c091-a844-88ef-be4ea489648e'); yourself)); add: (#id->#'bec0a4ef-c091-a844-88ef-be4ea489648e'); add: (#iconCode->'nil'); add: (#next->#'dd7cc162-78d3-5946-8ad0-7e30f7b46f6d'); add: (#viewDefinition->#treeView); add: (#label->'Methods'); yourself)