steps
step8e40f69c66578340838bdd4fb3a4e0b8
	<step>

	^ ((Dictionary new) add: (#definition->#'9aa298c2-a22e-2e43-83cd-8859357e0c7a'); add: (#class->ViQueryGroupSortStep); add: (#properties->((Dictionary new) add: (#priority->1900); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'8e40f69c-6657-8340-838b-dd4fb3a4e0b8'); add: (#iconCode->'nil'); add: (#next->#'265f5360-f208-fe42-b68a-e42b58b5ff93'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)