steps
step89c40fb8551c9e469651f11978e9ff30
	<step>

	^ ((Dictionary new) add: (#definition->#'90e36e33-cecf-6c4a-b7a9-0c4f6192bed2'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->2340); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#headerText->'Object'); yourself)); add: (#id->#'89c40fb8-551c-9e46-9651-f11978e9ff30'); add: (#iconCode->'nil'); add: (#next->#'4c0b175c-ebc3-fb4e-9b1c-31b8b5b5660d'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)