steps
step8d3e35af10d4a3469157f3ad76331d4d
	<step>

	^ ((Dictionary new) add: (#definition->#'ad4d80ac-c0c0-3e47-a673-d51547ce89b8'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->2520); add: (#headerText->'Origin'); yourself)); add: (#id->#'8d3e35af-10d4-a346-9157-f3ad76331d4d'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)