steps
step117962c3a327154ab5319a15adc69887
	<step>

	^ ((Dictionary new) add: (#definition->#'14767347-73da-b249-817d-740c37a6ba4d'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->5380); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 February 2014 1:11:39 pm'); add: (#headerText->#scM); yourself)); add: (#id->#'117962c3-a327-154a-b531-9a15adc69887'); add: (#iconCode->'nil'); add: (#next->#'1bb9843f-ebf1-3848-82dc-01ee3ed5468d'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)