steps
stepd62c865932925541b3b608b9ff46de99
	<step>

	^ ((Dictionary new) add: (#definition->#'6f38796b-7a6d-494e-926e-a2dc03b50f2e'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->6240); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'6 June 2014 4:24:35 pm'); yourself)); add: (#id->#'d62c8659-3292-5541-b3b6-08b9ff46de99'); add: (#iconCode->'nil'); add: (#next->#'1e371f14-64f0-004c-94ca-e667218e38e4'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)