steps
step322c353db95327439b11f8c0ae4041b1
	<step>

	^ ((Dictionary new) add: (#definition->#origin); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->3080); add: (#headerText->'Origin'); yourself)); add: (#id->#'322c353d-b953-2743-9b11-f8c0ae4041b1'); add: (#iconCode->'nil'); add: (#next->#'7d7f7d20-939a-7c4e-9a80-1915e705d82e'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)