steps
step7665bebe0cf425439977ca902db88134
	<step>

	^ ((Dictionary new) add: (#definition->#'353e01ce-518b-5d49-b095-04ef0d632d71'); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->4090); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'23 September 2013 5:12:29 pm'); yourself)); add: (#id->#'7665bebe-0cf4-2543-9977-ca902db88134'); add: (#iconCode->'nil'); add: (#next->#'f2876136-7eb8-e94b-864d-61f883d28db9'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)