steps
stepe61b1b9cdca80246aff493c3b091547a
	<step>

	^ ((Dictionary new) add: (#definition->#category); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->1560); add: (#headerText->'Protocol'); yourself)); add: (#id->#'e61b1b9c-dca8-0246-aff4-93c3b091547a'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)