steps
step177406757772764181dc431205cff3b8
	<step>

	^ ((Dictionary new) add: (#definition->#iconAndLabel); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->3260); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'9 September 2013 2:59:20 pm'); yourself)); add: (#id->#'17740675-7772-7641-81dc-431205cff3b8'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)