steps
step60f99406f09f354a9ed291ddd9060fc4
	<step>

	^ ((Dictionary new) add: (#definition->#'6f88a5a4-246a-344e-a485-3b15cb6fa9ea'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->4700); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'17 January 2014 2:56:58 pm'); yourself)); add: (#id->#'60f99406-f09f-354a-9ed2-91ddd9060fc4'); add: (#iconCode->'nil'); add: (#next->#'cafd96b4-6e9f-904c-bb72-8015ce0d112f'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)