steps
step3952d601cc18de4e81ebdbdbeb2ba7c2
	<step>

	^ ((Dictionary new) add: (#definition->#'0359b0f1-42e5-ef4c-b993-3022fe9fa515'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->710); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'3952d601-cc18-de4e-81eb-dbdbeb2ba7c2'); add: (#iconCode->'nil'); add: (#next->#'2d21437b-3606-d343-9872-5e357a12de36'); add: (#viewDefinition->#treeView); add: (#label->'File tree'); yourself)