steps
step00d6ab8802b8d34398bf44d2fb8c6ab5
	<step>

	^ ((Dictionary new) add: (#definition->#'7057516c-b98e-ea4a-8d54-c4c3a0f4ab33'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->3690); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 September 2013 3:28:44 pm'); yourself)); add: (#id->#'00d6ab88-02b8-d343-98bf-44d2fb8c6ab5'); add: (#iconCode->'UiFugueIcons folderTreeIcon'); add: (#next->#'5f25d26e-227f-9b45-abc1-644d5e129639'); add: (#viewDefinition->#treeView); add: (#label->'Class Category (Eclipse)'); yourself)