steps
stepa6b7eb35f794e7419102f303b6594f32
	<step>

	^ ((Dictionary new) add: (#definition->#'e22c6d26-271f-0145-b39a-d2f7d44aa913'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->810); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#defaultProperties); yourself)); add: (#id->#'a6b7eb35-f794-e741-9102-f303b6594f32'); add: (#iconCode->'UiSilkIcons userSuitIcon'); add: (#next->#'d82ec0a6-a967-514a-953c-27fcb67ec3d3'); add: (#viewDefinition->#treeView); add: (#label->'Count Authors'); yourself)