steps
step03a844ab437b6c418cf915f9a8aab212
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsAsStrings); add: (#class->ViQueryGroupSortStep); add: (#properties->((Dictionary new) add: (#priority->5470); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'7 November 2013 10:52:48 am'); add: (#copyOfStep->#'d8173faa-7721-b340-afaa-a4d664743096'); yourself)); add: (#id->#'03a844ab-437b-6c41-8cf9-15f9a8aab212'); add: (#iconCode->'nil'); add: (#next->#'e4cedfc1-3419-6a46-a306-65067830a9bf'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)