steps
steptextInput
	<step>

	^ ((Dictionary new) add: (#definition->#'d8985e4a-16e9-8643-9143-06e11ad06235'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->6460); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'23 June 2014 3:12:29 pm'); yourself)); add: (#id->#textInput); add: (#iconCode->'UiFugueIcons uiTextFieldIcon'); add: (#next->nil); add: (#viewDefinition->#textInput); add: (#label->'Text Input'); yourself)