steps
step96d77081b7de93458536a0d326322f6e
	<step>

	^ ((Dictionary new) add: (#definition->nil); add: (#class->ViQueryReferenceStep); add: (#properties->((Dictionary new) add: (#priority->540); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'15 September 2013 5:49:24 pm'); yourself)); add: (#next->nil); add: (#label->'References (recursive)'); add: (#iconCode->'UiFugueIcons arrowStepIcon'); add: (#reference->#'b510b1f4-2f4c-514a-bd82-a354adbf042f'); add: (#id->#'96d77081-b7de-9345-8536-a0d326322f6e'); add: (#viewDefinition->#treeView); yourself)