steps
step0c69c004a3f9134e8ba6eafca2418592
	<step>

	^ ((Dictionary new) add: (#definition->#'1db1df87-dcb9-2542-b17b-bc902869ba5d'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->4430); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#defaultProperties); yourself)); add: (#id->#'0c69c004-a3f9-134e-8ba6-eafca2418592'); add: (#iconCode->'UiDiagonaIcons icon0132Normal'); add: (#next->#'f45b857e-e698-274c-b3d6-467851b2d5dc'); add: (#viewDefinition->#treeView); add: (#label->'Singletons and defaults'); yourself)