steps
steped57b1e04b74094a926b2776acef9b31
	<step>

	^ ((Dictionary new) add: (#definition->#'46d59249-1c70-d042-8d2c-c784959fd192'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->5370); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 February 2014 1:10:45 pm'); add: (#headerText->#scH); yourself)); add: (#id->#'ed57b1e0-4b74-094a-926b-2776acef9b31'); add: (#iconCode->'nil'); add: (#next->#'117962c3-a327-154a-b531-9a15adc69887'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)