steps
step69e497c24f934d4984b194178c53e847
	<step>

	^ ((Dictionary new) add: (#definition->#'ecc82096-e22c-1446-9001-ba0f0f6d0be2'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->1020); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'6 September 2013 8:38:52 pm'); yourself)); add: (#id->#'69e497c2-4f93-4d49-84b1-94178c53e847'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)