steps
stepb0043854ca340844a516d5c81e51c885
	<step>

	^ ((Dictionary new) add: (#definition->#'15beca97-e0c0-1e44-81d7-45840aeb820b'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->940); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'b0043854-ca34-0844-a516-d5c81e51c885'); add: (#iconCode->'nil'); add: (#next->#'5c3b9aae-476e-cc4f-96a1-da5e5ab421ad'); add: (#viewDefinition->#treeView); add: (#label->'Variables for whileTrue senders'); yourself)