steps
step46075c8756092c4186d5a35e4089e966
	<step>

	^ ((Dictionary new) add: (#definition->#'9413f6fc-c294-b744-9b9c-dbb35ec66f2d'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->1230); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'46075c87-5609-2c41-86d5-a35e4089e966'); add: (#iconCode->'nil'); add: (#next->#'39e0739a-b359-364a-9c0f-a5b758f8f9c8'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)