steps
stepa8f95d967f396744aca595cde8b9e75e
	<step>

	^ ((Dictionary new) add: (#definition->#origin); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#copyOfStep->#'d9634b11-bde6-1a40-a0b4-7be880afc37a'); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'a8f95d96-7f39-6744-aca5-95cde8b9e75e'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)