steps
step1ab8a66adb32f44587b20c2967596906
	<step>

	^ ((Dictionary new) add: (#definition->#'aea63ea8-7330-d94d-9826-f54d88aca22f'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->6570); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'23 July 2014 11:18:20 am'); yourself)); add: (#id->#'1ab8a66a-db32-f445-87b2-0c2967596906'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)