steps
step44a90e06f6651a44923a22a2103ad8ba
	<step>

	^ ((Dictionary new) add: (#definition->#'563021ef-44a7-e24e-beb7-6201088a6f24'); add: (#class->ViQueryGroupSortStep); add: (#properties->((Dictionary new) add: (#priority->3330); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 September 2013 6:49:57 pm'); add: (#copyOfStep->#'44a90e06-f665-1a44-923a-22a2103ad8ba'); yourself)); add: (#id->#'44a90e06-f665-1a44-923a-22a2103ad8ba'); add: (#iconCode->'nil'); add: (#next->#'6dcf4d7c-0337-da43-85f9-526e23934ee9'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)