steps
step6984c6e097664d45852038f66da3cd32
	<step>

	^ ((Dictionary new) add: (#definition->#'8d8c0677-fb62-2547-b0ca-9397bf9ffce5'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->1770); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'6984c6e0-9766-4d45-8520-38f66da3cd32'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)