steps
step79c77c1fcaea9342ab06db5aad7909f0
	<step>

	^ ((Dictionary new) add: (#definition->#'09aee677-4dd4-a647-8067-b5f15a60f5ff'); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->1310); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'79c77c1f-caea-9342-ab06-db5aad7909f0'); add: (#iconCode->'nil'); add: (#next->#'e5522090-7365-c442-8d15-94253ec1d77e'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)