steps
stepd70d563fbdd718429175cf758450e227
	<step>

	^ ((Dictionary new) add: (#definition->#'8287f41b-826f-0247-b83e-45b6688f9d76'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->330); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'d70d563f-bdd7-1842-9175-cf758450e227'); add: (#iconCode->'UiSilkIcons folderIcon'); add: (#next->#'6094f78a-9d34-d844-8e98-bc414b414eb2'); add: (#viewDefinition->#treeView); add: (#label->'Files & Folders'); yourself)