steps
stepb3a5a8de9e73f64da9603946a4e8fbe5
	<step>

	^ ((Dictionary new) add: (#definition->#'0fee1e3f-c9f8-9042-b646-88feee2a13c8'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->#AAAAAA); add: (#creationAuthor->'mt'); add: (#priority->5040); add: (#creationTimeStamp->'11 February 2014 10:20:51 am'); yourself)); add: (#id->#'b3a5a8de-9e73-f64d-a960-3946a4e8fbe5'); add: (#iconCode->'nil'); add: (#next->#'e44e7438-eba5-7344-8590-a778889ab428'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)