steps
stepa515840fa24cb44083446f05ddcb59fb
	<step>

	^ ((Dictionary new) add: (#definition->#'e92838ff-d429-e247-82cc-de08a1a7afff'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'20 May 2015 2:44:10 pm'); yourself)); add: (#isProperty->false); add: (#next->#'805f3b27-a219-f941-ada8-c489c9fd753d'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'a515840f-a24c-b440-8344-6f05ddcb59fb'); add: (#isReference->false); add: (#viewDefinition->nil); yourself)