steps
stepacccd73850175e44ba68cc46761670dc
	<step>

	^ ((Dictionary new) add: (#definition->#'33ed3fa1-213a-bf45-8092-90ada0211906'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->6100); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'20 May 2014 12:01:18 pm'); yourself)); add: (#id->#'acccd738-5017-5e44-ba68-cc46761670dc'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)