steps
stepccdeb4ee852e184980822d3e37a2cf44
	<step>

	^ ((Dictionary new) add: (#definition->#'31152db4-2b7f-fe48-864d-bfc1f9f4ee9c'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->2930); add: (#headerText->'Timestamp'); yourself)); add: (#id->#'ccdeb4ee-852e-1849-8082-2d3e37a2cf44'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)