steps
stepe68d82d70f825e4f990d0b292c42da7f
	<step>

	^ ((Dictionary new) add: (#definition->#origin); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->4420); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 November 2013 4:20:43 pm'); yourself)); add: (#id->#'e68d82d7-0f82-5e4f-990d-0b292c42da7f'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)