steps
step23d4adf141b29845aeb22b496e4ea663
	<step>

	^ ((Dictionary new) add: (#definition->#'bf222edf-ff5f-7149-8f7e-d65994f90ce9'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->3620); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#'d9634b11-bde6-1a40-a0b4-7be880afc37a'); yourself)); add: (#id->#'23d4adf1-41b2-9845-aeb2-2b496e4ea663'); add: (#iconCode->'nil'); add: (#next->#'8579d16a-7ced-f746-8933-90568d7c97e0'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)