steps
stepcodeDefinitions
	<step>

	^ ((Dictionary new) add: (#definition->#'eaacc8b2-4e11-bb4c-ab2b-7aa0583b7467'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->400); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'3 September 2013 1:46 pm'); add: (#copyOfStep->#codeDefinitions); yourself)); add: (#id->#codeDefinitions); add: (#iconCode->'nil'); add: (#next->#'65524c28-e06a-0e4b-85de-f973d5fa91df'); add: (#viewDefinition->#treeViewExtended); add: (#label->nil); yourself)