steps
step57759e79162b7647b6c7af705463339b
	<step>

	^ ((Dictionary new) add: (#definition->#'6878b8b4-4e3f-354b-86df-a7a1607b09fc'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->1170); add: (#headerText->'S'); yourself)); add: (#id->#'57759e79-162b-7647-b6c7-af705463339b'); add: (#iconCode->'nil'); add: (#next->#'5401af50-ff0b-9941-b850-35ffa4179d50'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)