steps
stepc56e2e0c6b9a7b43a503dfea27e23d82
	<step>

	^ ((Dictionary new) add: (#definition->#'7fd3bade-f48e-c24d-8962-354e9676a6d2'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->2940); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#headerText->'Name'); yourself)); add: (#id->#'c56e2e0c-6b9a-7b43-a503-dfea27e23d82'); add: (#iconCode->'nil'); add: (#next->#'e6e2433a-dfdd-7d4c-942a-ae804d9b9e29'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)