steps
stepe9e1bde11735284cbe1f6b99473e1678
	<step>

	^ ((Dictionary new) add: (#definition->#category); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->2110); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'e9e1bde1-1735-284c-be1f-6b99473e1678'); add: (#iconCode->'nil'); add: (#next->#'ca04a42d-26a9-9947-afa0-1aa1b04bfca1'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)