steps
step0bcec8d5cada9048b7bface560a17f4f
	<step>

	^ ((Dictionary new) add: (#definition->#subclasses); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->2080); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'0bcec8d5-cada-9048-b7bf-ace560a17f4f'); add: (#iconCode->'nil'); add: (#next->#'76221c32-5f94-c545-a4a4-cf57138ffe39'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)