steps
step6b45f38f77e7ee4aac7196c1987498fb
	<step>

	^ ((Dictionary new) add: (#definition->#'034fe71c-762e-3547-8e4b-d55060ebeba3'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->6130); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 May 2014 2:58:16 pm'); yourself)); add: (#id->#'6b45f38f-77e7-ee4a-ac71-96c1987498fb'); add: (#iconCode->'nil'); add: (#next->#'894088c2-9d24-5b40-9246-2e1a298fe761'); add: (#viewDefinition->#treeView); add: (#label->'Empty Objects'); yourself)