steps
step1816b6d5ac0875439b14edd58be27deb
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsAsStrings); add: (#class->ViQueryGroupSortStep); add: (#properties->((Dictionary new) add: (#priority->2430); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'1816b6d5-ac08-7543-9b14-edd58be27deb'); add: (#iconCode->'nil'); add: (#next->#'e0d4454d-0188-6242-916d-1c1f2b47e445'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)