steps
stepartifacts
	<step>

	^ ((Dictionary new) add: (#definition->#'e06097d2-1a38-4845-ae0e-d68113bd2be5'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#view->ViArtifactListView2); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'20 October 2014 7:29:40 am'); yourself)); add: (#id->#artifacts); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treePlain); add: (#label->'Artifacts'); yourself)