steps
step96d9ab1f38366b4c9f56ee9989b7d3a8
	<step>

	^ ((Dictionary new) add: (#definition->#'514e33c1-49ef-db4a-ab27-1b67d793b46b'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->5810); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'11 February 2014 1:01:49 pm'); add: (#copyOfStep->#identity); yourself)); add: (#id->#'96d9ab1f-3836-6b4c-9f56-ee9989b7d3a8'); add: (#iconCode->'nil'); add: (#next->#'83cf7197-6cf5-554e-b535-2b2ebf2fb60e'); add: (#viewDefinition->#textView); add: (#label->nil); yourself)