steps
step069180ba532da840b13313495d451f74
	<step>

	^ ((Dictionary new) add: (#definition->#'12af691a-ac0b-cd49-88c7-73fcb3a92686'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->6410); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'5 June 2014 5:05:04 pm'); yourself)); add: (#id->#'069180ba-532d-a840-b133-13495d451f74'); add: (#iconCode->'nil'); add: (#next->#'7d49f967-e5fd-2d45-a452-864c859fa223'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)