steps
step64c67351149a5b419de2aa23b19628a8
	<step>

	^ ((Dictionary new) add: (#definition->#'fd572dfd-7602-ae44-b123-a3d198f338b0'); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->3640); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 September 2013 9:56:21 am'); yourself)); add: (#id->#'64c67351-149a-5b41-9de2-aa23b19628a8'); add: (#iconCode->'nil'); add: (#next->#'45fb3a38-39dc-2144-a747-a51f5e49f729'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)