steps
stepupdateDefinitions
	<step>

	^ ((Dictionary new) add: (#definition->#'eaacc8b2-4e11-bb4c-ab2b-7aa0583b7467'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->410); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'6 September 2013 8:27:11 pm'); yourself)); add: (#id->#updateDefinitions); add: (#iconCode->'nil'); add: (#next->#'ed778e6a-6ace-e540-84c3-af7329c1f656'); add: (#viewDefinition->#treeViewExtended); add: (#label->nil); yourself)