steps
step1f346fc9d1d0494c8f22fa56031636cb
	<step>

	^ ((Dictionary new) add: (#definition->#'25ba5d71-aab6-224f-b0c7-1fe9151c9ecc'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->630); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#defaultProperties); yourself)); add: (#id->#'1f346fc9-d1d0-494c-8f22-fa56031636cb'); add: (#iconCode->'nil'); add: (#next->#'46817f32-e66b-9342-a3ad-abe14e9713c9'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)