steps
step35e3497e2aff7d4aa4e96ab0b798b3ed
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsByName); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->2830); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'35e3497e-2aff-7d4a-a4e9-6ab0b798b3ed'); add: (#iconCode->'nil'); add: (#next->#'181275cd-bd0c-3642-9b0d-9373d885260e'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)