steps
step97ad3fc76ae68145a2794414ebdd6804
	<step>

	^ ((Dictionary new) add: (#definition->#toplevelClasses); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->2050); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'97ad3fc7-6ae6-8145-a279-4414ebdd6804'); add: (#iconCode->'nil'); add: (#next->#'19536a17-53f2-a544-90d1-73c5acc3cb61'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)