steps
step5f25d26e227f9b45abc1644d5e129639
	<step>

	^ ((Dictionary new) add: (#definition->#'0c53b73c-4e16-1542-b40c-cd76a3b1dda5'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->3700); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 September 2013 3:34:54 pm'); yourself)); add: (#id->#'5f25d26e-227f-9b45-abc1-644d5e129639'); add: (#iconCode->'nil'); add: (#next->#'5810152a-258e-1044-82c6-a1d1c4ad946a'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)