steps
step2efaf9924ab5ff4f8321b9aecefce974
	<step>

	^ ((Dictionary new) add: (#definition->#'42b080f1-f789-de46-8d53-de288f085a5a'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->30); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#defaultProperties); yourself)); add: (#id->#'2efaf992-4ab5-ff4f-8321-b9aecefce974'); add: (#iconCode->'nil'); add: (#next->#'931fac93-b85b-1c42-bcc2-435f7486a3e6'); add: (#viewDefinition->#treeViewExtended); add: (#label->'Last exceptions'); yourself)