steps
stepd346ff340c694d46ac758aa766aef148
	<step>

	^ ((Dictionary new) add: (#definition->#'f5ed8b90-0396-e14a-b7c7-a384000dcbea'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#labelColor->'#999999'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->800); add: (#copyOfStep->#defaultProperties); yourself)); add: (#id->#'d346ff34-0c69-4d46-ac75-8aa766aef148'); add: (#iconCode->'nil'); add: (#next->#'8173a10a-ef99-b643-819d-530c4a9f806f'); add: (#viewDefinition->#treeView); add: (#label->'Chase pointers'); yourself)