steps
step7d7f7d20939a7c4e9a801915e705d82e
	<step>

	^ ((Dictionary new) add: (#definition->#'8171a213-b8ca-1248-b5d5-e386fc8a12e5'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->3090); add: (#headerText->'LOC'); yourself)); add: (#id->#'7d7f7d20-939a-7c4e-9a80-1915e705d82e'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)