steps
stepprintStringNew
	<step>

	^ ((Dictionary new) add: (#definition->#'83fdd12e-c8ff-d04c-aca7-8a67eac8a477'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'30 December 2014 5:04:25 pm'); yourself)); add: (#isProperty->true); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#printStringNew); add: (#viewDefinition->#treePlain); yourself)