steps
step9d1d6fe1e07c9f4a97aa452c1fbcc9af
	<step>

	^ ((Dictionary new) add: (#definition->#'a5322375-d829-bb40-9181-f4ce0b5ec1fd'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->2590); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#headerText->'Object'); yourself)); add: (#id->#'9d1d6fe1-e07c-9f4a-97aa-452c1fbcc9af'); add: (#iconCode->'nil'); add: (#next->#'8290f350-f011-2348-a527-7cfb1d2a5a45'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)