steps
stepcf18cd020e0b344ca7ee82358865b598
	<step>

	^ ((Dictionary new) add: (#definition->#'efde47c0-b44a-7b49-9f37-ea3243404447'); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->3320); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 September 2013 6:49:23 pm'); add: (#copyOfStep->#'cf18cd02-0e0b-344c-a7ee-82358865b598'); yourself)); add: (#id->#'cf18cd02-0e0b-344c-a7ee-82358865b598'); add: (#iconCode->'nil'); add: (#next->#'44a90e06-f665-1a44-923a-22a2103ad8ba'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)