steps
step71efc7d9c3cb724696526b74bc022b8e
	<step>

	^ ((Dictionary new) add: (#definition->#'53b0702c-c7b9-b74c-94b3-d4f943c6e9bc'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->6380); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#'93b6233e-a34e-f54d-9c6a-b7eeef30e075'); yourself)); add: (#id->#'71efc7d9-c3cb-7246-9652-6b74bc022b8e'); add: (#iconCode->'nil'); add: (#next->#'5636df93-3a8f-ea44-9406-e602b99e3101'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)