steps
step172f485a7e690d4aa5ad7233f83da2dc
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsBySelector); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->1780); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'172f485a-7e69-0d4a-a5ad-7233f83da2dc'); add: (#iconCode->'nil'); add: (#next->#'0c8adf16-5e6c-8046-b097-6a6dfeaa52ea'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)