steps
step0598baea8006ef4ea2f26d5412d6ab3c
	<step>

	^ ((Dictionary new) add: (#definition->#selectByContext); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->2160); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'0598baea-8006-ef4e-a2f2-6d5412d6ab3c'); add: (#iconCode->'nil'); add: (#next->#'962950ed-4ad4-244b-9e1b-512547f2422f'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)