steps
step1573b08cd3a1fb43a0304ccb7ad458ac
	<step>

	^ ((Dictionary new) add: (#definition->#'49caf340-056b-ec4c-a1fe-877183ba0bc7'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->560); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#'11617cd4-f3da-b347-b264-37a8dd9e6a46'); yourself)); add: (#id->#'1573b08c-d3a1-fb43-a030-4ccb7ad458ac'); add: (#iconCode->'nil'); add: (#next->#'7665bebe-0cf4-2543-9977-ca902db88134'); add: (#viewDefinition->#treeView); add: (#label->'Projects'); yourself)