steps
step4078cbfe867e564c85b0ac2edd21217d
	<step>

	^ ((Dictionary new) add: (#definition->#'ed9f3ef7-7d17-c541-b7cf-2821cca31d6b'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'007F00'); add: (#creationTimeStamp->'13 September 2013 6:56:36 pm'); add: (#creationAuthor->'mt'); add: (#priority->3350); add: (#copyOfStep->#'4078cbfe-867e-564c-85b0-ac2edd21217d'); yourself)); add: (#id->#'4078cbfe-867e-564c-85b0-ac2edd21217d'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)