steps
step322373256bef9048a0d35e1f4a3e64ed
	<step>

	^ ((Dictionary new) add: (#definition->#'9a123eed-f732-304a-8061-5921223ef529'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->5530); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 February 2014 10:21:58 am'); yourself)); add: (#id->#'32237325-6bef-9048-a0d3-5e1f4a3e64ed'); add: (#iconCode->'nil'); add: (#next->#'aa3ec915-c019-e941-8b9b-f9baa09fd69a'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)