steps
step0d821eecf78fd44e80df96d6b534a947
	<step>

	^ ((Dictionary new) add: (#definition->#'d0608999-e6c6-b648-b748-5cdb7b3c81b3'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->2460); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'0d821eec-f78f-d44e-80df-96d6b534a947'); add: (#iconCode->'nil'); add: (#next->#'e0d4454d-0188-6242-916d-1c1f2b47e445'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)