steps
stepfca5ba471c0b0b4d8c617eca1715c0c5
	<step>

	^ ((Dictionary new) add: (#definition->#'b08835ac-24fe-3b43-87cb-ceb4b81fc6fb'); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->1980); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'fca5ba47-1c0b-0b4d-8c61-7eca1715c0c5'); add: (#iconCode->'nil'); add: (#next->#'8b5ec783-b069-bd44-a805-058c53c7f164'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)