steps
step9d1f7dc5d93e274bb732b08a5181ea6f
	<step>

	^ ((Dictionary new) add: (#definition->#'93525b3f-5fde-bb4c-ad94-1c2c3a53fd53'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->2410); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'3 September 2013 3:29:42 pm'); yourself)); add: (#id->#'9d1f7dc5-d93e-274b-b732-b08a5181ea6f'); add: (#iconCode->'nil'); add: (#next->#'c4cd5013-fa6d-7a44-966e-79cfcaa59612'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)