steps
step894088c29d245b4092462e1a298fe761
	<step>

	^ ((Dictionary new) add: (#definition->#histogram); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->4360); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 November 2013 3:30:24 pm'); yourself)); add: (#id->#'894088c2-9d24-5b40-9246-2e1a298fe761'); add: (#iconCode->'UiSilkIcons chartBarIcon'); add: (#next->#'d740eb73-4267-9240-86ce-b2cb2018f68a'); add: (#viewDefinition->#treeView); add: (#label->'Sorted Bars'); yourself)