steps
stepa36810b7a281b34d9d22e1f1a585db30
	<step>

	^ ((Dictionary new) add: (#definition->#'6a55f686-f73f-d94c-b810-e6a946eb771a'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->4130); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'23 September 2013 5:12:03 pm'); yourself)); add: (#id->#'a36810b7-a281-b34d-9d22-e1f1a585db30'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)