steps
stepa8d9e9fc0bb3384b9baee3c1edb07163
	<step>

	^ ((Dictionary new) add: (#definition->#'a51d601c-c1f2-d540-8878-0769cf929b4d'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->5550); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 February 2014 11:23:26 am'); yourself)); add: (#id->#'a8d9e9fc-0bb3-384b-9bae-e3c1edb07163'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)