steps
step02594c645f169449af33fb7d5bcdd662
	<step>

	^ ((Dictionary new) add: (#definition->#'4bd59430-a20c-da41-8120-fdbb4aeeefc3'); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->1130); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'02594c64-5f16-9449-af33-fb7d5bcdd662'); add: (#iconCode->'nil'); add: (#next->#'68476311-41ac-3445-9df5-321d8834e6f7'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)