steps
step254519a4d387e14598c49d0959d54bb0
	<step>

	^ ((Dictionary new) add: (#definition->#'af7194c4-7ad5-134b-a040-368387dd4009'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->1030); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'6 September 2013 9:08:35 pm'); add: (#copyOfStep->#'254519a4-d387-e145-98c4-9d0959d54bb0'); yourself)); add: (#id->#'254519a4-d387-e145-98c4-9d0959d54bb0'); add: (#iconCode->'nil'); add: (#next->#'fb419e86-ae99-8746-8320-8ef4c8c7e6d2'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)