steps
step5672f69dd1351d409f5ba8d58b762aa5
	<step>

	^ ((Dictionary new) add: (#definition->#'72afa9e5-7d79-104b-97b0-accfde7204b7'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->510); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'5672f69d-d135-1d40-9f5b-a8d58b762aa5'); add: (#iconCode->'nil'); add: (#next->#'476a828e-2f7b-4b4a-9c8a-b515f83ac457'); add: (#viewDefinition->#tileView); add: (#label->'Pictures (nicer)'); yourself)