steps
stepfb20347b7a6fbe43bd7888492dc2d4b1
	<step>

	^ ((Dictionary new) add: (#definition->#'8068b6a4-5651-ed4e-bf4b-38809290491d'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->3720); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 September 2013 4:35:12 pm'); yourself)); add: (#id->#'fb20347b-7a6f-be43-bd78-88492dc2d4b1'); add: (#iconCode->'nil'); add: (#next->#'0fdcdea8-5071-914b-ab0c-5d6335ce985f'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)