steps
step164491a2978d5d4e893103fff9ded75e
	<step>

	^ ((Dictionary new) add: (#definition->#'7bf109e4-f6d2-7c4d-a084-0e72ff4d8753'); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->2200); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'164491a2-978d-5d4e-8931-03fff9ded75e'); add: (#iconCode->'nil'); add: (#next->#'4483ab73-df68-ab43-b410-6de476dc855a'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)