steps
stepafd7936f34666b4484a72d8fc3dc21a4
	<step>

	^ ((Dictionary new) add: (#definition->#'05876be4-b12e-2046-8fe7-256847cabd85'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#headerText->'Methods'); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'afd7936f-3466-6b44-84a7-2d8fc3dc21a4'); add: (#iconCode->'nil'); add: (#next->#'36f18c66-dd99-1f43-b7a8-edc44c309ebc'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)