steps
step2c058a47d6e2a34fb699cb3781ed55cb
	<step>

	^ ((Dictionary new) add: (#definition->#'be7eabb7-04da-5848-b24a-35bba9fe2f6e'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->3760); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#defaultProperties); yourself)); add: (#id->#'2c058a47-d6e2-a34f-b699-cb3781ed55cb'); add: (#iconCode->'nil'); add: (#next->#'c7e12f64-1638-ba43-92a5-5110b39063f2'); add: (#viewDefinition->#treeView); add: (#label->'Outline'); yourself)