steps
step47ebfeaff6ff624a8fc6078f452527db
	<step>

	^ ((Dictionary new) add: (#definition->#'fd572dfd-7602-ae44-b123-a3d198f338b0'); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->3270); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'9 September 2013 3:27:49 pm'); yourself)); add: (#id->#'47ebfeaf-f6ff-624a-8fc6-078f452527db'); add: (#iconCode->'nil'); add: (#next->#'17740675-7772-7641-81dc-431205cff3b8'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)