steps
step328d2fd9190c6f40accdafc2029f12c4
	<step>

	^ ((Dictionary new) add: (#definition->#'0b7a9508-db02-4244-ac2b-4ea7ff772056'); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->4000); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 September 2013 3:17:34 pm'); yourself)); add: (#id->#'328d2fd9-190c-6f40-accd-afc2029f12c4'); add: (#iconCode->'nil'); add: (#next->#'0022b353-daa6-014c-a245-38faec14e32e'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)