steps
stepa5b8674146bd5b47ab8da79879a3b859
	<step>

	^ ((Dictionary new) add: (#definition->#'89be9797-2710-5844-ab5e-b2bdd7f82581'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->2910); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#headerText->'Name'); yourself)); add: (#id->#'a5b86741-46bd-5b47-ab8d-a79879a3b859'); add: (#iconCode->'nil'); add: (#next->#'c2d0a6c2-91d4-2643-a28f-24b6ddd117c5'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)