steps
step8ca5adad98684e4ca40e2b9deba00f31
	<step>

	^ ((Dictionary new) add: (#definition->#'563021ef-44a7-e24e-beb7-6201088a6f24'); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->3560); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 September 2013 8:08:35 pm'); yourself)); add: (#id->#'8ca5adad-9868-4e4c-a40e-2b9deba00f31'); add: (#iconCode->'nil'); add: (#next->#'c65a9646-727f-864b-9955-deeac8d8dcf4'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)