steps
stepcd0c30a916077341a2fe614b91be39ac
	<step>

	^ ((Dictionary new) add: (#definition->#'06639145-042c-c047-b4ce-1c80d1cb3a1d'); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->6440); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'23 June 2014 9:21:07 am'); yourself)); add: (#id->#'cd0c30a9-1607-7341-a2fe-614b91be39ac'); add: (#iconCode->'nil'); add: (#next->#'38378fb0-83d9-5243-a502-4e4e62e18131'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)