steps
step09ffbad63a278b489dad264b9c41c6f9
	<step>

	^ ((Dictionary new) add: (#definition->#'d90a894f-095c-5c43-ac7b-5c0f959c349c'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->6470); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 July 2014 2:12:59 pm'); yourself)); add: (#id->#'09ffbad6-3a27-8b48-9dad-264b9c41c6f9'); add: (#iconCode->'nil'); add: (#next->#'045e9d2c-b29a-4641-b942-d4b769535d4a'); add: (#viewDefinition->#treeView); add: (#label->'World submorphs'); yourself)