steps
stepca622048bcebfd4db080661d9e6b7f04
	<step>

	^ ((Dictionary new) add: (#definition->#'376843ac-1b55-5d4d-a85c-383a3f1acd6b'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->5250); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 February 2014 2:54:36 pm'); yourself)); add: (#id->#'ca622048-bceb-fd4d-b080-661d9e6b7f04'); add: (#iconCode->'nil'); add: (#next->#'94740283-5bf2-514e-8eef-b18ce867137a'); add: (#viewDefinition->#listView); add: (#label->'Test classes'); yourself)