steps
stepobjectExplorer
	<step>

	^ ((Dictionary new) add: (#definition->#identity); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->5); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'11 February 2014 1:01:49 pm'); add: (#copyOfStep->#identity); yourself)); add: (#id->#objectExplorer); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#explorer); add: (#label->'Object Explorer'); yourself)