steps
step55d465d1f7d0c04fa61b099f2ae6b6b9
	<step>

	^ ((Dictionary new) add: (#definition->#'58831cd0-33de-e94f-b638-18be45b71615'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#priority->4540); add: (#copyOfStep->#'4483ab73-df68-ab43-b410-6de476dc855a'); add: (#headerText->'Name'); add: (#resizeMode->#rigid); yourself)); add: (#id->#'55d465d1-f7d0-c04f-a61b-099f2ae6b6b9'); add: (#iconCode->'nil'); add: (#next->#'bb553ae0-c81d-4641-964f-7f27055d9c15'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)