steps
steped82703794ca9a45b2233148d0dc9fc9
	<step>

	^ ((Dictionary new) add: (#definition->#'458aec04-1603-c144-ba90-125a9a27d789'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->6510); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'13 July 2014 2:15:45 pm'); yourself)); add: (#id->#'ed827037-94ca-9a45-b223-3148d0dc9fc9'); add: (#iconCode->'nil'); add: (#next->#'88b2345b-3bda-5e41-a90f-b81c36b39fd8'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)