steps
step8541e0243a147d4a9ac55c521a7c4f27
	<step>

	^ ((Dictionary new) add: (#definition->#'c7f13eaf-02b3-7046-8b08-c7d1a5a911dd'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->5140); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#'217e17d6-56aa-ff44-a6d3-2e3bf316d470'); yourself)); add: (#id->#'8541e024-3a14-7d4a-9ac5-5c521a7c4f27'); add: (#iconCode->'nil'); add: (#next->#'f128659b-7f02-364d-afc1-143f418bf135'); add: (#viewDefinition->#treeView); add: (#label->'Outline (w/ LOC categories)'); yourself)