steps
step37989d230602ed44ad37440cccc8d6d9
	<step>

	^ ((Dictionary new) add: (#definition->#'6731f25c-5705-6843-8e6f-0c4263ca2073'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->6010); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'11 February 2014 1:01:49 pm'); add: (#copyOfStep->#identity); yourself)); add: (#id->#'37989d23-0602-ed44-ad37-440cccc8d6d9'); add: (#iconCode->'nil'); add: (#next->#'9a36a312-8950-9d4e-9c29-7386596f007f'); add: (#viewDefinition->#treeView); add: (#label->'Submorphs'); yourself)