steps
step62d361c42c396e47989e42b4f10c257c
	<step>

	^ ((Dictionary new) add: (#definition->#'c7208da2-7800-1f42-b1d6-e140c304dda7'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->5300); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'14 February 2014 10:04:38 am'); add: (#headerText->#DPc); yourself)); add: (#id->#'62d361c4-2c39-6e47-989e-42b4f10c257c'); add: (#iconCode->'nil'); add: (#next->#'b080bd39-a8a3-1744-b982-fb270b04627f'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)