steps
step6a85aea66f4659418895484cadece99b
	<step>

	^ ((Dictionary new) add: (#definition->#selectByContext); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'6a85aea6-6f46-5941-8895-484cadece99b'); add: (#iconCode->'nil'); add: (#next->#'f45253e3-1e61-2344-8ebb-69fad9e592af'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)