steps
step03d5937adad89045beb6aaa920fd056c
	<step>

	^ ((Dictionary new) add: (#definition->#'514e33c1-49ef-db4a-ab27-1b67d793b46b'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->4920); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#'728402d7-f870-e743-8d2a-abf2353efba1'); yourself)); add: (#id->#'03d5937a-dad8-9045-beb6-aaa920fd056c'); add: (#iconCode->'nil'); add: (#next->#'57addd32-9f03-8e44-9c71-46497f3e7209'); add: (#viewDefinition->#treeView); add: (#label->'Method'); yourself)