steps
step11ba89fbaa6d264a92c1cba5506abae1
	<step>

	^ ((Dictionary new) add: (#definition->#'cb356ae2-d027-6a47-b973-e5696e88f1bc'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'18 December 2014 2:57:53 pm'); yourself)); add: (#isProperty->true); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'11ba89fb-aa6d-264a-92c1-cba5506abae1'); add: (#viewDefinition->#treePlain); yourself)