steps
step65524c28e06a0e4b85def973d5fa91df
	<step>

	^ ((Dictionary new) add: (#definition->#'b91eac56-ad6f-3e42-940d-d558ecbe5eeb'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->990); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'15 September 2013 4:36:44 pm'); add: (#copyOfStep->#'65524c28-e06a-0e4b-85de-f973d5fa91df'); yourself)); add: (#id->#'65524c28-e06a-0e4b-85de-f973d5fa91df'); add: (#iconCode->'UiSilkIcons scriptCodeIcon'); add: (#next->#'8ed52473-9493-2142-94be-054478bc571b'); add: (#viewDefinition->#treeViewExtended); add: (#label->'Code Definitions'); yourself)