steps
stepd70ca6fcbf5eee4aae3989d3d351c3bb
	<step>

	^ ((Dictionary new) add: (#definition->#'9ff9a38b-1638-4e47-80a7-8390c89b325b'); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->1750); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'d70ca6fc-bf5e-ee4a-ae39-89d3d351c3bb'); add: (#iconCode->'nil'); add: (#next->#'572ceaba-6d90-a54d-aa5c-1091a08ad960'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)