steps
step6f505e41acfd5d4fada277cdc48e1601
	<step>

	^ ((Dictionary new) add: (#definition->#iconAndLabel); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->1480); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#headerText->'Sender'); yourself)); add: (#id->#'6f505e41-acfd-5d4f-ada2-77cdc48e1601'); add: (#iconCode->'nil'); add: (#next->#'6db1e613-5156-9940-b0a6-eb4acb825df1'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)