steps
step9a36a31289509d4e9c297386596f007f
	<step>

	^ ((Dictionary new) add: (#definition->#'c70a89eb-72fb-1846-be69-841c75c0a435'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->6020); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'2 March 2014 10:06:15 am'); yourself)); add: (#id->#'9a36a312-8950-9d4e-9c29-7386596f007f'); add: (#iconCode->'nil'); add: (#next->#'e578a963-cfd4-5641-b942-6e1eef180ad2'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)