steps
step6d7f9bea0e5cc94ca4cb7c20ea715fa8
	<step>

	^ ((Dictionary new) add: (#definition->#'720a8d90-f7c1-334e-a4ea-5094ba285a8d'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->4650); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'10 January 2014 12:51:11 pm'); yourself)); add: (#id->#'6d7f9bea-0e5c-c94c-a4cb-7c20ea715fa8'); add: (#iconCode->'nil'); add: (#next->#'bc5c5199-b11b-5a4c-8363-dcfb005b4abf'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)