steps
step0ea571f72db0b843a9ee8203b56d13c9
	<step>

	^ ((Dictionary new) add: (#definition->#'9c7d2184-d97f-0a4f-a361-192c038a7b1c'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->880); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'0ea571f7-2db0-b843-a9ee-8203b56d13c9'); add: (#iconCode->'UiFugueIcons scriptAttributeMIcon'); add: (#next->#'a5b86741-46bd-5b47-ab8d-a79879a3b859'); add: (#viewDefinition->#treeView); add: (#label->'Metacello Projects'); yourself)