steps
stepb2d07dee10329043b2c7876a7ef811bb
	<step>

	^ ((Dictionary new) add: (#definition->#'77a2ad58-1e74-ba40-b2b6-d596c594480b'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->1500); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'b2d07dee-1032-9043-b2c7-876a7ef811bb'); add: (#iconCode->'nil'); add: (#next->#'6f505e41-acfd-5d4f-ada2-77cdc48e1601'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)