steps
step6c0a1727d1af3a4aa6b879445faf91a2
	<step>

	^ ((Dictionary new) add: (#definition->#'eb0e6538-06eb-e34e-8e20-8914317b1981'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->3020); add: (#headerText->'Token'); yourself)); add: (#id->#'6c0a1727-d1af-3a4a-a6b8-79445faf91a2'); add: (#iconCode->'nil'); add: (#next->#'6049746d-7182-cc42-972d-f77ab0baefca'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)