steps
stepcd28236371fbf94a9a4c49ce99c79f7b
	<step>

	^ ((Dictionary new) add: (#definition->#'7f7384b3-4b62-aa46-b5d5-b91053a66277'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'cd282363-71fb-f94a-9a4c-49ce99c79f7b'); add: (#iconCode->'nil'); add: (#next->#'afd7936f-3466-6b44-84a7-2d8fc3dc21a4'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)