steps
step0f263fa973930a45ade8fdacace2318a
	<step>

	^ ((Dictionary new) add: (#definition->#'6658de62-dc22-7f42-b43f-47b99ddfadee'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->4310); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#'d9634b11-bde6-1a40-a0b4-7be880afc37a'); yourself)); add: (#id->#'0f263fa9-7393-0a45-ade8-fdacace2318a'); add: (#iconCode->'nil'); add: (#next->#'d50e64dd-2c00-694f-9ed1-a81ee1b01b81'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)