steps
stepae6288a6a692bf4284df1174cbab45a4
	<step>

	^ ((Dictionary new) add: (#definition->#'9d4a27b4-8a76-bc4d-9738-0a575bc69f07'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->6350); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'21 May 2014 6:12:20 pm'); yourself)); add: (#id->#'ae6288a6-a692-bf42-84df-1174cbab45a4'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)