steps
stepf0de7c8470172d42860de743620ce3b4
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsBySelector); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->6530); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#'dd7cc162-78d3-5946-8ad0-7e30f7b46f6d'); yourself)); add: (#id->#'f0de7c84-7017-2d42-860d-e743620ce3b4'); add: (#iconCode->'nil'); add: (#next->#'36a4ecd2-893b-604c-9199-84cbfbffa8d4'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)