steps
stepe957bc9e51f13b4eac097f23d6c54160
	<step>

	^ ((Dictionary new) add: (#definition->#identity); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->6450); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'11 February 2014 1:01:49 pm'); add: (#copyOfStep->#identity); yourself)); add: (#id->#'e957bc9e-51f1-3b4e-ac09-7f23d6c54160'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#commandsBar); add: (#label->'Commands'); yourself)