steps
stepb90e4eaaf8ab8b47aca3f78a5dadde3e
	<step>

	^ ((Dictionary new) add: (#definition->#removeDuplicates); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->4150); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'4 October 2013 6:33:02 pm'); yourself)); add: (#id->#'b90e4eaa-f8ab-8b47-aca3-f78a5dadde3e'); add: (#iconCode->'nil'); add: (#next->#'7b14d200-2978-8b40-8e54-4c9a03cb23f7'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)