steps
stepa67a43efd74abf46b160bf00ef047753
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsAsStrings); add: (#class->ViQueryGroupSortStep); add: (#properties->((Dictionary new) add: (#priority->6310); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'21 May 2014 6:11:40 pm'); yourself)); add: (#id->#'a67a43ef-d74a-bf46-b160-bf00ef047753'); add: (#iconCode->'nil'); add: (#next->#'6eab0da0-5a97-d94d-84a6-5f930edbbd06'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)