steps
stepc656fd1e4df72247b673381f86e04eef
	<step>

	^ ((Dictionary new) add: (#definition->#'8cd44e71-e224-234c-84af-614a4b0ac44f'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->2360); add: (#headerText->'Tally'); yourself)); add: (#id->#'c656fd1e-4df7-2247-b673-381f86e04eef'); add: (#iconCode->'nil'); add: (#next->#'89d7f52e-8271-3f47-b695-8c06854f6a85'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)