steps
step2902b302607d7340b97a4a497764e9d3
	<step>

	^ ((Dictionary new) add: (#definition->#iconAndLabel); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->1810); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#headerText->'Methods'); yourself)); add: (#id->#'2902b302-607d-7340-b97a-4a497764e9d3'); add: (#iconCode->'nil'); add: (#next->#'82908026-d4e4-d047-83ee-741e175314a3'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)