steps
stepbc5c5199b11b5a4c8363dcfb005b4abf
	<step>

	^ ((Dictionary new) add: (#definition->#'a3a0aaa7-1711-094f-8621-bac1067b8ab0'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->440); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'bc5c5199-b11b-5a4c-8363-dcfb005b4abf'); add: (#iconCode->'UiFugueIcons arrowStepIcon'); add: (#next->#'0cd634b5-d35d-3a4c-8c1f-9515a57e3adb'); add: (#viewDefinition->#treeView); add: (#label->'Senders (recursive)'); yourself)