steps
step4b70743966b1c64b805a80c63759305e
	<step>

	^ ((Dictionary new) add: (#definition->#'3d0c7269-aed8-9e4a-9b3d-fa7ec52d2dc1'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#999999'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->2880); add: (#headerText->'Property'); yourself)); add: (#id->#'4b707439-66b1-c64b-805a-80c63759305e'); add: (#iconCode->'nil'); add: (#next->#'31f74b61-d090-a443-99cc-182ef8e9b039'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)