steps
stepd87b686730987841b98b559b668d9869
	<step>

	^ ((Dictionary new) add: (#definition->#'84ee52f9-c014-804b-b364-628e00c875d7'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->700); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'d87b6867-3098-7841-b98b-559b668d9869'); add: (#iconCode->'nil'); add: (#next->#'92301087-4a3b-9841-bf34-cfaaef53c085'); add: (#viewDefinition->#treeView); add: (#label->'Methods (class-side)'); yourself)