steps
step1a584c05b8fcdc438564d48f2c2b954b
	<step>

	^ ((Dictionary new) add: (#definition->#'664dac2d-ff00-6c42-a83d-3a52f5a83749'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->740); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'1a584c05-b8fc-dc43-8564-d48f2c2b954b'); add: (#iconCode->'UiFugueIcons keyboardExclamationIcon'); add: (#next->#'5b3d233e-c93c-0b42-b8ba-fafb41d70a9e'); add: (#viewDefinition->#treeView); add: (#label->'Inconsistent grab-/hasKeyboard'); yourself)