steps
step04435caf88a5ae49b931413ea2a3e59f
	<step>

	^ ((Dictionary new) add: (#definition->#'0500ed1b-7128-2d43-b307-89fd1223197d'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->910); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'04435caf-88a5-ae49-b931-413ea2a3e59f'); add: (#iconCode->'nil'); add: (#next->#'b2b4ae78-98c6-7844-91b0-87f17deed68c'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)