steps
stepd1ab46b3df50534cb593d1e6683fe045
	<step>

	^ ((Dictionary new) add: (#definition->#iconAndLabel); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->1540); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#headerText->'Implementor'); yourself)); add: (#id->#'d1ab46b3-df50-534c-b593-d1e6683fe045'); add: (#iconCode->'nil'); add: (#next->#'be086e52-473b-3d4b-a833-6d796588f9e6'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)