steps
step9cab60cb31ee7f4b8cac34c9bed5c6ab
	<step>

	^ ((Dictionary new) add: (#definition->#origin); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationAuthor->'mt'); add: (#priority->3150); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#headerText->'Origin'); yourself)); add: (#id->#'9cab60cb-31ee-7f4b-8cac-34c9bed5c6ab'); add: (#iconCode->'nil'); add: (#next->nil); add: (#label->nil); yourself)