steps
step923010874a3b9841bf34cfaaef53c085
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsBySelector); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->2710); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'92301087-4a3b-9841-bf34-cfaaef53c085'); add: (#iconCode->'nil'); add: (#next->#'9caa8ce4-2b82-9b4f-8466-269ee432cdd8'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)