steps
step5cb7a38dcab6d44eb38f779f66faf736
	<step>

	^ ((Dictionary new) add: (#definition->#'058d3529-d310-e847-b148-dadf47ff31b9'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->5910); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'19 February 2014 4:06:47 pm'); yourself)); add: (#id->#'5cb7a38d-cab6-d44e-b38f-779f66faf736'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)