steps
step6c7c176619c3924c954e2cc22258ca1c
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsAsStrings); add: (#class->ViQueryGroupSortStep); add: (#properties->((Dictionary new) add: (#priority->5740); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'20 February 2014 2:05:12 pm'); yourself)); add: (#id->#'6c7c1766-19c3-924c-954e-2cc22258ca1c'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)