steps
step85478cdcdec75648b9afbbf1c6a6d389
	<step>

	^ ((Dictionary new) add: (#definition->#'f9974083-86d5-d54f-9ee0-ba85d5b22720'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#hAlignment->#right); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#priority->2220); yourself)); add: (#id->#'85478cdc-dec7-5648-b9af-bbf1c6a6d389'); add: (#iconCode->'nil'); add: (#next->#'fa4cb8bf-f5a3-134c-8ce1-40866732e786'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)