steps
step5c3b9aae476ecc4f96a1da5e5ab421ad
	<step>

	^ ((Dictionary new) add: (#definition->#iconAndLabel); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->3140); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#headerText->'Object'); yourself)); add: (#id->#'5c3b9aae-476e-cc4f-96a1-da5e5ab421ad'); add: (#iconCode->'nil'); add: (#next->#'9cab60cb-31ee-7f4b-8cac-34c9bed5c6ab'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)