steps
stepidentity
	<step>

	^ ((Dictionary new) add: (#definition->#'44bdd3d3-ea3e-5446-8a1a-5edacc6d70f1'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'20 October 2014 6:54:14 am'); yourself)); add: (#id->#identity); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treePlain); add: (#label->'Identity'); yourself)