steps
step6db1e61351569940b0a6eb4acb825df1
	<step>

	^ ((Dictionary new) add: (#definition->#origin); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->1490); add: (#headerText->'Class'); yourself)); add: (#id->#'6db1e613-5156-9940-b0a6-eb4acb825df1'); add: (#iconCode->'nil'); add: (#next->#'b2d07dee-1032-9043-b2c7-876a7ef811bb'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)