steps
stepb8dcfbd64325b94bbf953a44025557dc
	<step>

	^ ((Dictionary new) add: (#definition->#'b47ce5fd-48ca-be4e-a9ec-085c8c0d5546'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->6600); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'11 February 2014 1:01:49 pm'); add: (#copyOfStep->#identity); yourself)); add: (#id->#'b8dcfbd6-4325-b94b-bf95-3a44025557dc'); add: (#iconCode->'nil'); add: (#next->#'874bd769-4b84-dd45-9644-c5e3a23f29de'); add: (#viewDefinition->#treeViewExtended); add: (#label->'Query Properties'); yourself)