steps
stepsnippets
	<step>

	^ ((Dictionary new) add: (#definition->#'9b701f19-cef1-ad4e-9ed2-5c2e5016305d'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->5000); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#defaultProperties); yourself)); add: (#id->#snippets); add: (#iconCode->'nil'); add: (#next->#'cd0c30a9-1607-7341-a2fe-614b91be39ac'); add: (#viewDefinition->#treeViewExtended); add: (#label->'Executable code snippets'); yourself)