steps
step4ee8e2d89bc67645b541f743df30fe9d
	<step>

	^ ((Dictionary new) add: (#definition->#'0bc0ce7e-2194-504a-b60b-9cd9c19cef01'); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->1570); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'4ee8e2d8-9bc6-7645-b541-f743df30fe9d'); add: (#iconCode->'nil'); add: (#next->#'ba683fae-91bb-ed4c-985f-8c12b3504e50'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)