*VivideDynamicAnalysis-definitions
def148542c19238cc428d1c00892f409d9e
	<definition>

	^ ((Dictionary new) add: (#inputKind->SdMethodCallNode); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'148542c1-9238-cc42-8d1c-00892f409d9e'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:calls | calls gather: [:call | SdCallgraphManager default receiverObjectsForCall: call  ]]'); add: (#mapType->#all); add: (#block->[:calls | calls gather: [:call | SdCallgraphManager default receiverObjectsForCall: call  ]]); yourself)