*VivideDynamicAnalysis-definitions
def10df31eae0c0c04883266c6614a40123
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'10df31ea-e0c0-c048-8326-6c6614a40123'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | #text -> obj parent clientReference]'); add: (#mapType->#each); add: (#block->[:obj | #text -> obj parent clientReference]); yourself)