*VivideDynamicAnalysis-definitions
def1224a3b8329b90428506321ad7915ea8
	<definition>

	^ ((Dictionary new) add: (#inputKind->MethodReference); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'1224a3b8-329b-9042-8506-321ad7915ea8'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:refs | (refs gather: [:ref | SdCallgraphManager default callsForReference: ref])]'); add: (#mapType->#all); add: (#block->[:refs | (refs gather: [:ref | SdCallgraphManager default callsForReference: ref])]); yourself)