*VivideDynamicAnalysis-definitions
def1f58de4b15a5804fa4cbee0f8cf1cf8b
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'1f58de4b-15a5-804f-a4cb-ee0f8cf1cf8b'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | #text -> obj maxDepth]'); add: (#mapType->#each); add: (#block->[:obj | #text -> obj maxDepth]); yourself)