*VivideDynamicAnalysis-definitions
def297764d1a252a541bdc7efba8cc4316b
	<definition>

	^ ((Dictionary new) add: (#inputKind->MethodReference); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'297764d1-a252-a541-bdc7-efba8cc4316b'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:refs | refs gather: [:ref | SdCallgraphManager default argumentObjectsForReference: ref]]'); add: (#mapType->#all); add: (#block->[:refs | refs gather: [:ref | SdCallgraphManager default argumentObjectsForReference: ref]]); yourself)