*VivideDynamicAnalysis-definitions
def38fd82406a18ea4c90e532012d5c5ae3
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'38fd8240-6a18-ea4c-90e5-32012d5c5ae3'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:call | call callgraph traceEvent asString escapeHtmlText]'); add: (#mapType->#each); add: (#block->[:call | call callgraph traceEvent asString escapeHtmlText]); yourself)