*VivideDynamicAnalysis-definitions
def39d7835d1c477746a6448dffbc80134e
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'39d7835d-1c47-7746-a644-8dffbc80134e'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:call | #text -> call numCalls]'); add: (#mapType->#each); add: (#block->[:call | #text -> call numCalls]); yourself)