*VivideDynamicAnalysis-definitions
def3e82b71545359f439e1366b6588f5940
	<definition>

	^ ((Dictionary new) add: (#inputKind->MethodReference); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'3e82b715-4535-9f43-9e13-66b6588f5940'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:refs | refs gather: [:ref | (SdCallgraphManager default returnObjectsForReference: ref ) asSet asOrderedCollection]]'); add: (#mapType->#all); add: (#block->[:refs | refs gather: [:ref | (SdCallgraphManager default returnObjectsForReference: ref ) asSet asOrderedCollection]]); yourself)