*VivideDynamicAnalysis-definitions
def4a8e1bed412974429122688f702fdbf0
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'8 January 2014 10:55:07 am'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'4a8e1bed-4129-7442-9122-688f702fdbf0'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | #text -> (ViLabelService doObject: obj key)]'); add: (#mapType->#each); add: (#block->[:obj | #text -> (ViLabelService doObject: obj key)]); yourself)