*VivideDynamicAnalysis-definitions
def405f34fe1a1daa4a9d553171db3dcf39
	<definition>

	^ ((Dictionary new) add: (#inputKind->SdCallgraphNode); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'405f34fe-1a1d-aa4a-9d55-3171db3dcf39'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | {#text -> obj id}]'); add: (#mapType->#each); add: (#block->[:obj | {#text -> obj id}]); yourself)