*VivideDynamicAnalysis-definitions
def4e7debd71c4ea84dbe1ca6f9fdd5fb40
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'8 January 2014 10:55:25 am'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'4e7debd7-1c4e-a84d-be1c-a6f9fdd5fb40'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | #text -> obj value asArray]'); add: (#mapType->#each); add: (#block->[:obj | #text -> obj value asArray]); yourself)