*VivideDynamicAnalysis-definitions
def96a2918acec21a428691dd90d562d115
	<definition>

	^ ((Dictionary new) add: (#inputKind->SdCallgraphDiff); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'96a2918a-cec2-1a42-8691-dd90d562d115'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | {
	#text -> (ViLabelService doObject: obj).
	#icon -> (ViIconService doObject: obj).
	#color -> (obj isChildDifferent
		ifTrue: [Color yellow paler alpha: 0.5] ifFalse: [])}]'); add: (#mapType->#each); add: (#block->[:obj | {
	#text -> (ViLabelService doObject: obj).
	#icon -> (ViIconService doObject: obj).
	#color -> (obj isChildDifferent
		ifTrue: [Color yellow paler alpha: 0.5] ifFalse: [])}]); yourself)