*VivideDynamicAnalysis-definitions
def98a7b2d771e87242921bb9fde9f77b6f
	<definition>

	^ ((Dictionary new) add: (#inputKind->SdCallgraphNode); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'98a7b2d7-71e8-7242-921b-b9fde9f77b6f'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | #text -> (obj valueOfProperty: #duration ifAbsent: [''''])]'); add: (#mapType->#each); add: (#block->[:obj | #text -> (obj valueOfProperty: #duration ifAbsent: [''])]); yourself)