*VivideDynamicAnalysis-definitions
defce53bd10c48f1d4ca918e91396c77f97
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'ce53bd10-c48f-1d4c-a918-e91396c77f97'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | {#text -> obj labelForFirstNode}]'); add: (#mapType->#each); add: (#block->[:obj | {#text -> obj labelForFirstNode}]); yourself)