*VivideDynamicAnalysis-definitions
defc24c1ca3f63550439d8cf8feed9056b9
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'c24c1ca3-f635-5043-9d8c-f8feed9056b9'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:obj | {#text -> obj labelForSecondNode}]'); add: (#mapType->#each); add: (#block->[:obj | {#text -> obj labelForSecondNode}]); yourself)