*VivideDynamicAnalysis-definitions
defd4f3a6aff8b733489f2f19e08905871c
	<definition>

	^ ((Dictionary new) add: (#inputKind->STestReference); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'d4f3a6af-f8b7-3348-9f2f-19e08905871c'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:refs | refs collect: [:ref | SdCallgraphManager default callTreeForTest: ref] ]'); add: (#mapType->#all); add: (#block->[:refs | refs collect: [:ref | SdCallgraphManager default callTreeForTest: ref] ]); yourself)