*VivideDynamicAnalysis-definitions
defde764d9025d09345ab50ef917b5ac1cc
	<definition>

	^ ((Dictionary new) add: (#inputKind->SdMethodCallNode); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'de764d90-25d0-9345-ab50-ef917b5ac1cc'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:calls | calls gather: [:call | SdCallgraphManager default argumentObjectsForCall: call]]'); add: (#mapType->#all); add: (#block->[:calls | calls gather: [:call | SdCallgraphManager default argumentObjectsForCall: call]]); yourself)