*VivideDynamicAnalysis-definitions
deff7eff87587ab8e48b137bb9b484b04f1
	<definition>

	^ ((Dictionary new) add: (#inputKind->MethodReference); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'f7eff875-87ab-8e48-b137-bb9b484b04f1'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:refs | refs gather: [:ref | SdCallgraphManager default returnObjectsForReference: ref  ]]'); add: (#mapType->#all); add: (#block->[:refs | refs gather: [:ref | SdCallgraphManager default returnObjectsForReference: ref  ]]); yourself)