*VivideDynamicAnalysis-definitions
deffa450c77f6e45a49afdb612538c388a7
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'8 January 2014 11:07:48 am'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'fa450c77-f6e4-5a49-afdb-612538c388a7'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:node | #text -> node clientSelector]'); add: (#mapType->#each); add: (#block->[:node | #text -> node clientSelector]); yourself)