*VivideDynamicAnalysis-definitions
deff85c4d148e070e4fa31c1153f0720368
	<definition>

	^ ((Dictionary new) add: (#inputKind->Object); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'f85c4d14-8e07-0e4f-a31c-1153f0720368'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:cls | #text -> (SCoverageCollector coverageForClass: cls)]'); add: (#mapType->#each); add: (#block->[:cls | #text -> (SCoverageCollector coverageForClass: cls)]); yourself)