*VivideDynamicAnalysis-definitions
deffc15ee6773874548b9e03b219416990b
	<definition>

	^ ((Dictionary new) add: (#inputKind->MethodReference); add: (#class->ViQueryMapDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#updateClearDefinition->nil); add: (#outputKind->Object); add: (#id->#'fc15ee67-7387-4548-b9e0-3b219416990b'); add: (#updateSetDefinition->nil); add: (#sourceCode->'[:refs | refs gather: [:ref | SdCallgraphManager default receiverObjectsForReference: ref  ]]'); add: (#mapType->#all); add: (#block->[:refs | refs gather: [:ref | SdCallgraphManager default receiverObjectsForReference: ref  ]]); yourself)