*VivideDynamicAnalysis-steps
stepbd01ae062df7d848b97932d766d44e65
	<step>

	^ ((Dictionary new) add: (#definition->#'405f34fe-1a1d-aa4a-9d55-3171db3dcf39'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->7860); add: (#headerText->'#'); yourself)); add: (#id->#'bd01ae06-2df7-d848-b979-32d766d44e65'); add: (#iconCode->'nil'); add: (#next->#'a0456e3e-6716-cb45-ab2a-70d7a0c33e6a'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)