*VivideDynamicAnalysis-steps
step4f97146875490e409e8e939fe2581c33
	<step>

	^ ((Dictionary new) add: (#definition->#'baae0367-2eb9-2745-b6af-c747b95925ac'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->8350); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'21 July 2014 10:27:48 am'); yourself)); add: (#id->#'4f971468-7549-0e40-9e8e-939fe2581c33'); add: (#iconCode->'nil'); add: (#next->#'2125acff-72cf-6c43-b959-a1561e3c805a'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)