*VivideDynamicAnalysis-steps
step864acbf4dbad504cb15b449b4519bf31
	<step>

	^ ((Dictionary new) add: (#definition->#origin); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->7900); add: (#headerText->'Class'); yourself)); add: (#id->#'864acbf4-dbad-504c-b15b-449b4519bf31'); add: (#iconCode->'nil'); add: (#next->#'8e6c9b17-5d5a-e64c-9e44-2cd5aa77ba4a'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)