*VivideDynamicAnalysis-steps
stepaf5f47bdb592ad43bffe327af112388e
	<step>

	^ ((Dictionary new) add: (#definition->#'6339f56a-501a-5644-a53c-031d49712bc7'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->8240); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#'728402d7-f870-e743-8d2a-abf2353efba1'); yourself)); add: (#id->#'af5f47bd-b592-ad43-bffe-327af112388e'); add: (#iconCode->'nil'); add: (#next->#'51224d1a-0426-644c-b4af-a9e025e59bf3'); add: (#viewDefinition->#treeView); add: (#label->'Type Communication'); yourself)