*VivideDynamicAnalysis-steps
step3d673274a6c8204891ffeeecde10f451
	<step>

	^ ((Dictionary new) add: (#definition->#'fc15ee67-7387-4548-b9e0-3b219416990b'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->7450); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'3d673274-a6c8-2048-91ff-eeecde10f451'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->'Receivers'); yourself)