*VivideDynamicAnalysis-steps
stepe5c1a408eb801042917459c08d12db96
	<step>

	^ ((Dictionary new) add: (#definition->#'baae0367-2eb9-2745-b6af-c747b95925ac'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->8360); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'21 July 2014 10:30:40 am'); yourself)); add: (#id->#'e5c1a408-eb80-1042-9174-59c08d12db96'); add: (#iconCode->'nil'); add: (#next->#'6b6e988a-f04d-2246-bdf7-ca70c6df8a15'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)