*VivideDynamicAnalysis-steps
step4d608297fe867d4495ecf7203996a62c
	<step>

	^ ((Dictionary new) add: (#definition->#'7f7384b3-4b62-aa46-b5d5-b91053a66277'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->7760); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'4d608297-fe86-7d44-95ec-f7203996a62c'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)