*VivideDynamicAnalysis-steps
step50aeeb8c4ea30148b37cea34278a5cb8
	<step>

	^ ((Dictionary new) add: (#definition->#allMethodsForClass); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->7400); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'50aeeb8c-4ea3-0148-b37c-ea34278a5cb8'); add: (#iconCode->'UiFugueIcons smileyMrGreenIcon'); add: (#next->#'f8248cff-917d-c940-93a4-e129c0107e13'); add: (#viewDefinition->#treeView); add: (#label->'Methods w/ coverage'); yourself)