*VivideDynamicAnalysis-steps
step173aa9da62f8144fb5491c3d017f1481
	<step>

	^ ((Dictionary new) add: (#definition->#'5c7c7115-e42a-e449-9ccc-46e721d91319'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->8250); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#'728402d7-f870-e743-8d2a-abf2353efba1'); yourself)); add: (#id->#'173aa9da-62f8-144f-b549-1c3d017f1481'); add: (#iconCode->'nil'); add: (#next->#'ef191754-8252-4a4b-939d-e0064dc27d22'); add: (#viewDefinition->#treeViewExtended); add: (#label->'Sequence Diagram'); yourself)