*VivideDynamicAnalysis-steps
stepd2721c9bc24ea240a0077a0c4fbbad3f
	<step>

	^ ((Dictionary new) add: (#definition->#iconAndLabel); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->7960); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#headerText->'Selector'); yourself)); add: (#id->#'d2721c9b-c24e-a240-a007-7a0c4fbbad3f'); add: (#iconCode->'nil'); add: (#next->#'fe9b70c7-cf2e-c946-aafa-d74236abbefb'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)