*VivideDynamicAnalysis-steps
stepca901bb9c440f64ca3b3b6416725baba
	<step>

	^ ((Dictionary new) add: (#definition->#'f85c4d14-8e07-0e4f-a31c-1153f0720368'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->7630); add: (#headerText->'Coverage'); yourself)); add: (#id->#'ca901bb9-c440-f64c-a3b3-b6416725baba'); add: (#iconCode->'nil'); add: (#next->#'2054bc16-50c2-9146-bd4f-2cc011273f60'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)