*VivideDynamicAnalysis-steps
step27a700ac3fadbd4ba98a75bb41650157
	<step>

	^ ((Dictionary new) add: (#definition->#'a8e1f6d2-59e5-0b4e-8254-e152fcc315d7'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->8370); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'21 July 2014 10:35:46 am'); yourself)); add: (#id->#'27a700ac-3fad-bd4b-a98a-75bb41650157'); add: (#iconCode->'nil'); add: (#next->#'1ba70416-e60b-ca43-937b-4217215404c4'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)