*VivideDynamicAnalysis-steps
step7f914c3cd3b3b8428d35f3bb800204ed
	<step>

	^ ((Dictionary new) add: (#definition->#toplevelClasses); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->7610); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'7f914c3c-d3b3-b842-8d35-f3bb800204ed'); add: (#iconCode->'nil'); add: (#next->#'22cb9f30-9855-c148-b055-cde908fcda3d'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)