*VivideDynamicAnalysis-steps
stepd22c898d094a5e429d8bfb916647494f
	<step>

	^ ((Dictionary new) add: (#definition->#origin); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->7750); add: (#headerText->'Origin'); yourself)); add: (#id->#'d22c898d-094a-5e42-9d8b-fb916647494f'); add: (#iconCode->'nil'); add: (#next->#'4d608297-fe86-7d44-95ec-f7203996a62c'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)