*VivideDynamicAnalysis-steps
step753cce2cbe1613479986c38ca1c5d905
	<step>

	^ ((Dictionary new) add: (#definition->#origin); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->8150); add: (#headerText->'Origin'); yourself)); add: (#id->#'753cce2c-be16-1347-9986-c38ca1c5d905'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)