*VivideDynamicAnalysis-steps
step00cbd5e8654bf24084acc27108962707
	<step>

	^ ((Dictionary new) add: (#definition->#'d1a31df6-69aa-9f42-9638-bf514aade0ae'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->8220); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'00cbd5e8-654b-f240-84ac-c27108962707'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)