*VivideDynamicAnalysis-steps
stepfeccd28ea4874e47836fe4b67bf342cf
	<step>

	^ ((Dictionary new) add: (#definition->#identity); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->7460); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'feccd28e-a487-4e47-836f-e4b67bf342cf'); add: (#iconCode->'UiFugueIcons clockSelectIcon'); add: (#next->#'8167c595-7b9c-2549-b8aa-4003e9019012'); add: (#viewDefinition->#treeView); add: (#label->'Call tree (w/ duration)'); yourself)