*VivideDynamicAnalysis-steps
stepe0e4995716a0424b848a16ae536548a0
	<step>

	^ ((Dictionary new) add: (#definition->#'148542c1-9238-cc42-8d1c-00892f409d9e'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->7530); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'e0e49957-16a0-424b-848a-16ae536548a0'); add: (#iconCode->'nil'); add: (#next->#'771b4c83-b8e5-fa4f-bd83-8e8072d2955a'); add: (#viewDefinition->#treeView); add: (#label->'Receiver (before/after)'); yourself)