*VivideDynamicAnalysis-steps
step760feed227e18d4f9d3700451a892436
	<step>

	^ ((Dictionary new) add: (#definition->#mergeAssociations); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->7710); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'760feed2-27e1-8d4f-9d37-00451a892436'); add: (#iconCode->'nil'); add: (#next->#'fe635e72-064a-5342-a768-a9c6b245a451'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)