*VivideDynamicAnalysis-steps
stepc00f966f902cd645ae6ba1a2e094ff70
	<step>

	^ ((Dictionary new) add: (#definition->#'d1a31df6-69aa-9f42-9638-bf514aade0ae'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->7880); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'c00f966f-902c-d645-ae6b-a1a2e094ff70'); add: (#iconCode->'nil'); add: (#next->#'8167c595-7b9c-2549-b8aa-4003e9019012'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)