*VivideDynamicAnalysis-steps
stepfe635e72064a5342a768a9c6b245a451
	<step>

	^ ((Dictionary new) add: (#definition->#copyToContext); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->7720); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'fe635e72-064a-5342-a768-a9c6b245a451'); add: (#iconCode->'nil'); add: (#next->#'8b093ab9-490b-8343-8fd3-f55d0c4a63f4'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)