*VivideDynamicAnalysis-steps
step21dd5fb9540d23429fb7ba050f698df1
	<step>

	^ ((Dictionary new) add: (#definition->#'8d8c0677-fb62-2547-b0ca-9397bf9ffce5'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->8090); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#headerText->'Diff'); yourself)); add: (#id->#'21dd5fb9-540d-2342-9fb7-ba050f698df1'); add: (#iconCode->'nil'); add: (#next->#'59d5b87f-176f-ef4f-aad8-cb319a56ee07'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)