*VivideDynamicAnalysis-steps
step3043378b6e193f4e94d00134085346db
	<step>

	^ ((Dictionary new) add: (#definition->#'f7b15067-88bf-874d-b93b-e673b24857e3'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->7550); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'3043378b-6e19-3f4e-94d0-0134085346db'); add: (#iconCode->'nil'); add: (#next->#'409908b4-507d-2d4c-b97c-5465ba460dcd'); add: (#viewDefinition->#treeView); add: (#label->'Unbox call nodes'); yourself)