*VivideDynamicAnalysis-steps
step8167c5957b9c2549b8aa4003e9019012
	<step>

	^ ((Dictionary new) add: (#definition->#iconAndLabel); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->7830); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#headerText->'Selector'); yourself)); add: (#id->#'8167c595-7b9c-2549-b8aa-4003e9019012'); add: (#iconCode->'nil'); add: (#next->#'a0826be8-f8f5-8b4d-85a5-2bdfcfc38956'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)