*VivideDynamicAnalysis-steps
step4e3fcd50492be6408ec850ffffe9bcf4
	<step>

	^ ((Dictionary new) add: (#definition->#'1f58de4b-15a5-804f-a4cb-ee0f8cf1cf8b'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->8200); add: (#headerText->'Max Depth'); yourself)); add: (#id->#'4e3fcd50-492b-e640-8ec8-50ffffe9bcf4'); add: (#iconCode->'nil'); add: (#next->#'ea22362f-b8c1-1541-a96c-6a4aa2a5c97b'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)