*VivideDynamicAnalysis-steps
stepc1ab82f9fdc67d448631bd0d8510fe63
	<step>

	^ ((Dictionary new) add: (#definition->#'39d7835d-1c47-7746-a644-8dffbc80134e'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->8190); add: (#headerText->'Size'); yourself)); add: (#id->#'c1ab82f9-fdc6-7d44-8631-bd0d8510fe63'); add: (#iconCode->'nil'); add: (#next->#'4e3fcd50-492b-e640-8ec8-50ffffe9bcf4'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)