*VivideDynamicAnalysis-steps
step51224d1a0426644cb4afa9e025e59bf3
	<step>

	^ ((Dictionary new) add: (#definition->#'471d5044-e973-e643-b662-418ca69c6b9e'); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->8330); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'8 January 2014 1:55:28 pm'); yourself)); add: (#id->#'51224d1a-0426-644c-b4af-a9e025e59bf3'); add: (#iconCode->'nil'); add: (#next->#'54956528-87ed-cd44-a7d2-d194d5a20d4f'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)