*VivideDynamicAnalysis-steps
stepf94b27800648a24db75b67c4e2f9dbfb
	<step>

	^ ((Dictionary new) add: (#definition->#mergeAssociations); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->7770); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'f94b2780-0648-a24d-b75b-67c4e2f9dbfb'); add: (#iconCode->'nil'); add: (#next->#'c94facc4-f0e5-8141-8504-1d3585062947'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)