*VivideDynamicAnalysis-steps
step3dc18042e4dfda4bbf581a1eb2e97877
	<step>

	^ ((Dictionary new) add: (#definition->#'c24c1ca3-f635-5043-9d8c-f8feed9056b9'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->8110); add: (#headerText->'Second'); yourself)); add: (#id->#'3dc18042-e4df-da4b-bf58-1a1eb2e97877'); add: (#iconCode->'nil'); add: (#next->#'0bd5b5dd-b3bc-1848-93eb-d81739e9f06e'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)