*VivideDynamicAnalysis-steps
step409908b4507d2d4cb97c5465ba460dcd
	<step>

	^ ((Dictionary new) add: (#definition->#iconAndLabel); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->8140); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#headerText->'Object'); yourself)); add: (#id->#'409908b4-507d-2d4c-b97c-5465ba460dcd'); add: (#iconCode->'nil'); add: (#next->#'753cce2c-be16-1347-9986-c38ca1c5d905'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)