*VivideDynamicAnalysis-steps
stepa0826be8f8f58b4d85a52bdfcfc38956
	<step>

	^ ((Dictionary new) add: (#definition->#origin); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->7840); add: (#headerText->'Class'); yourself)); add: (#id->#'a0826be8-f8f5-8b4d-85a5-2bdfcfc38956'); add: (#iconCode->'nil'); add: (#next->#'94dc1891-5848-6e4b-8dd6-f6b3e946fa59'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)