*VivideDynamicAnalysis-steps
step568042c1e8d3cb49869ab9acbcc03bf9
	<step>

	^ ((Dictionary new) add: (#definition->#'d1a31df6-69aa-9f42-9638-bf514aade0ae'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->8130); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'568042c1-e8d3-cb49-869a-b9acbcc03bf9'); add: (#iconCode->'nil'); add: (#next->#'21dd5fb9-540d-2342-9fb7-ba050f698df1'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)