*VivideDynamicAnalysis-steps
step2f0eb228a7ae074eb8662c27c5a1c2b3
	<step>

	^ ((Dictionary new) add: (#definition->#'405f34fe-1a1d-aa4a-9d55-3171db3dcf39'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->7920); add: (#headerText->'#'); yourself)); add: (#id->#'2f0eb228-a7ae-074e-b866-2c27c5a1c2b3'); add: (#iconCode->'nil'); add: (#next->#'a78e03de-0c79-4247-8b8d-c868a10730dc'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)