*VivideDynamicAnalysis-steps
step0bd5b5ddb3bc184893ebd81739e9f06e
	<step>

	^ ((Dictionary new) add: (#definition->#origin); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->8120); add: (#headerText->'Class'); yourself)); add: (#id->#'0bd5b5dd-b3bc-1848-93eb-d81739e9f06e'); add: (#iconCode->'nil'); add: (#next->#'568042c1-e8d3-cb49-869a-b9acbcc03bf9'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)