*VivideDynamicAnalysis-steps
stepa0456e3e6716cb45ab2a70d7a0c33e6a
	<step>

	^ ((Dictionary new) add: (#definition->#'98a7b2d7-71e8-7242-921b-b9fde9f77b6f'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->7870); add: (#headerText->'Duration'); yourself)); add: (#id->#'a0456e3e-6716-cb45-ab2a-70d7a0c33e6a'); add: (#iconCode->'nil'); add: (#next->#'c00f966f-902c-d645-ae6b-a1a2e094ff70'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)