*VivideDynamicAnalysis-steps
step1a926c90e809964da73e4d0f7c6155b6
	<step>

	^ ((Dictionary new) add: (#definition->#'f7eff875-87ab-8e48-b137-bb9b484b04f1'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->7430); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'1a926c90-e809-964d-a73e-4d0f7c6155b6'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->'Results'); yourself)