*VivideDynamicAnalysis-steps
step8b093ab9490b83438fd3f55d0c4a63f4
	<step>

	^ ((Dictionary new) add: (#definition->#'fa585967-f2b4-bf43-9b5e-cc34c15d0e26'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->7730); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'8b093ab9-490b-8343-8fd3-f55d0c4a63f4'); add: (#iconCode->'nil'); add: (#next->#'076a67bf-05dc-8348-8570-ec54874c4481'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)