*VivideDynamicAnalysis-steps
step6b6e988af04d2246bdf7ca70c6df8a15
	<step>

	^ ((Dictionary new) add: (#definition->#'2175d7de-5680-e54d-b0bd-47839e6c806e'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->7420); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'6b6e988a-f04d-2246-bdf7-ca70c6df8a15'); add: (#iconCode->'nil'); add: (#next->#'f94b2780-0648-a24d-b75b-67c4e2f9dbfb'); add: (#viewDefinition->#treeView); add: (#label->'Method Arguments (no duplicates)'); yourself)