*VivideDynamicAnalysis-steps
step2125acff72cf6c43b959a1561e3c805a
	<step>

	^ ((Dictionary new) add: (#definition->#'1224a3b8-329b-9042-8506-321ad7915ea8'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->7560); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'2125acff-72cf-6c43-b959-a1561e3c805a'); add: (#iconCode->'nil'); add: (#next->#'34877119-e7a1-ad41-8369-d0e1c10011de'); add: (#viewDefinition->#treeView); add: (#label->'Calls'); yourself)