*VivideDynamicAnalysis-steps
stepdec99f7940677d4a908a6f813cb2e1e3
	<step>

	^ ((Dictionary new) add: (#definition->#'fa450c77-f6e4-5a49-afdb-612538c388a7'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->#'000000'); add: (#hAlignment->#center); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#priority->8300); add: (#copyOfStep->#'d9634b11-bde6-1a40-a0b4-7be880afc37a'); add: (#headerText->'UiScrollBar <> UiScrollBarSliderButton'); yourself)); add: (#id->#'dec99f79-4067-7d4a-908a-6f813cb2e1e3'); add: (#iconCode->'nil'); add: (#next->#'c00578bd-667a-6c40-bbf4-4ebabc08c106'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)