*VivideDynamicAnalysis-steps
step2054bc1650c29146bd4f2cc011273f60
	<step>

	^ ((Dictionary new) add: (#definition->#subclasses); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->7640); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'2054bc16-50c2-9146-bd4f-2cc011273f60'); add: (#iconCode->'nil'); add: (#next->#'de3c0cb4-93ec-aa46-8e1b-46ee9143938d'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)