*VivideDynamicAnalysis-steps
step2f85bd8f89022549b1ed814604baf42d
	<step>

	^ ((Dictionary new) add: (#definition->#iconAndLabel); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->7690); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#headerText->'Methods'); yourself)); add: (#id->#'2f85bd8f-8902-2549-b1ed-814604baf42d'); add: (#iconCode->'nil'); add: (#next->#'aeec707b-7cd8-0f48-9378-a87c0771e915'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)