*VivideDynamicAnalysis-steps
step540db69afba0ed48b17f47fdbf37abc5
	<step>

	^ ((Dictionary new) add: (#definition->#iconAndLabel); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->8170); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#headerText->'Object'); yourself)); add: (#id->#'540db69a-fba0-ed48-b17f-47fdbf37abc5'); add: (#iconCode->'nil'); add: (#next->#'6a40861e-709a-9749-a977-b4dc093bd03e'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)