*VivideDynamicAnalysis-steps
step101c09a22d48c540823ebd71ad8fcb8b
	<step>

	^ ((Dictionary new) add: (#definition->#'de764d90-25d0-9345-ab50-ef917b5ac1cc'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->7520); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'101c09a2-2d48-c540-823e-bd71ad8fcb8b'); add: (#iconCode->'nil'); add: (#next->#'dae9ff60-5974-f647-9325-2bfdd7ca6acf'); add: (#viewDefinition->#treeView); add: (#label->'Arguments (before/after)'); yourself)