*VivideDynamicAnalysis-steps
step076a67bf05dc83488570ec54874c4481
	<step>

	^ ((Dictionary new) add: (#definition->#iconAndLabel); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->7740); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#headerText->'Object'); yourself)); add: (#id->#'076a67bf-05dc-8348-8570-ec54874c4481'); add: (#iconCode->'nil'); add: (#next->#'d22c898d-094a-5e42-9d8b-fb916647494f'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)