*VivideDynamicAnalysis-steps
stepbd58e1b757dcce4eb027cf3140c36229
	<step>

	^ ((Dictionary new) add: (#definition->#'4a8e1bed-4129-7442-9122-688f702fdbf0'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->8270); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#defaultProperties); yourself)); add: (#id->#'bd58e1b7-57dc-ce4e-b027-cf3140c36229'); add: (#iconCode->'nil'); add: (#next->#'40b75576-ee1a-c24b-baa1-9d80570ca673'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)