*VivideDynamicAnalysis-steps
stepc94facc4f0e5814185041d3585062947
	<step>

	^ ((Dictionary new) add: (#definition->#copyToContext); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->7780); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'c94facc4-f0e5-8141-8504-1d3585062947'); add: (#iconCode->'nil'); add: (#next->#'28918202-1fd1-8c48-b5b6-c362bb139d75'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)