*VivideDynamicAnalysis-steps
stepf8248cff917dc94093a4e129c0107e13
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsBySelector); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->7660); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'f8248cff-917d-c940-93a4-e129c0107e13'); add: (#iconCode->'nil'); add: (#next->#'24f42b54-cc70-6c4d-b8d5-fb0151e2556b'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)