*VivideDynamicAnalysis-steps
step89a90aa2ea6a09459947281d976c0cfe
	<step>

	^ ((Dictionary new) add: (#definition->#origin); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->7950); add: (#headerText->'Origin'); yourself)); add: (#id->#'89a90aa2-ea6a-0945-9947-281d976c0cfe'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)