*VivideDynamicAnalysis-steps
stepde3c0cb493ecaa468e1b46ee9143938d
	<step>

	^ ((Dictionary new) add: (#definition->#selectByContext); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->7650); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'de3c0cb4-93ec-aa46-8e1b-46ee9143938d'); add: (#iconCode->'nil'); add: (#next->#'22cb9f30-9855-c148-b055-cde908fcda3d'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)