*VivideDynamicAnalysis-steps
step0890e42e595dbf4b8df74754d0b9bb8b
	<step>

	^ ((Dictionary new) add: (#definition->#'297764d1-a252-a541-bdc7-efba8cc4316b'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->7410); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'0890e42e-595d-bf4b-8df7-4754d0b9bb8b'); add: (#iconCode->'nil'); add: (#next->#'760feed2-27e1-8d4f-9d37-00451a892436'); add: (#viewDefinition->#treeView); add: (#label->'Method Arguments'); yourself)