*VivideDynamicAnalysis-steps
stepea22362fb8c11541a96c6a4aa2a5c97b
	<step>

	^ ((Dictionary new) add: (#definition->#'10df31ea-e0c0-c048-8326-6c6614a40123'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->8210); add: (#headerText->'Parent'); yourself)); add: (#id->#'ea22362f-b8c1-1541-a96c-6a4aa2a5c97b'); add: (#iconCode->'nil'); add: (#next->#'00cbd5e8-654b-f240-84ac-c27108962707'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)