*VivideDynamicAnalysis-steps
step75531e0e07232a40a8040a3afd0e8022
	<step>

	^ ((Dictionary new) add: (#definition->#iconAndLabel); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->7890); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#headerText->'Selector'); yourself)); add: (#id->#'75531e0e-0723-2a40-a804-0a3afd0e8022'); add: (#iconCode->'nil'); add: (#next->#'864acbf4-dbad-504c-b15b-449b4519bf31'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)