*VivideDynamicAnalysis-steps
step5d303f1e740eab43b722999fad485b78
	<step>

	^ ((Dictionary new) add: (#definition->nil); add: (#class->ViQueryReferenceStep); add: (#properties->((Dictionary new) add: (#priority->8260); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'8 January 2014 10:42:08 am'); yourself)); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#reference->#'894088c2-9d24-5b40-9246-2e1a298fe761'); add: (#id->#'5d303f1e-740e-ab43-b722-999fad485b78'); add: (#viewDefinition->#treeView); yourself)