*VivideDynamicAnalysis-steps
step5dce5e7ff912784cb66165bc08172e33
	<step>

	^ ((Dictionary new) add: (#definition->#origin); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->8080); add: (#headerText->'Origin'); yourself)); add: (#id->#'5dce5e7f-f912-784c-b661-65bc08172e33'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)