*VivideDynamicAnalysis-steps
step24f42b54cc706c4db8d5fb0151e2556b
	<step>

	^ ((Dictionary new) add: (#definition->#'07203f12-f1b6-9746-9884-0b9e8f1a4f6b'); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->7670); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'24f42b54-cc70-6c4d-b8d5-fb0151e2556b'); add: (#iconCode->'nil'); add: (#next->#'d6cc1eb9-52a8-4f4b-a00f-471559c1eabf'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)