*VivideDynamicAnalysis-steps
step58da325f1e89d343be51269a21907435
	<step>

	^ ((Dictionary new) add: (#definition->#'405f34fe-1a1d-aa4a-9d55-3171db3dcf39'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->7980); add: (#headerText->'#'); yourself)); add: (#id->#'58da325f-1e89-d343-be51-269a21907435'); add: (#iconCode->'nil'); add: (#next->#'f566cdeb-005b-7548-9b7a-fcf4c295b638'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)