*VivideDynamicAnalysis-steps
step51fdb8f834929a45afaa5028c86f9397
	<step>

	^ ((Dictionary new) add: (#definition->#'3e82b715-4535-9f43-9e13-66b6588f5940'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->7440); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'51fdb8f8-3492-9a45-afaa-5028c86f9397'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->'Results (no duplicates)'); yourself)