*VivideDynamicAnalysis-steps
step721fdf05d8ca6e46bc6c1aecc986357b
	<step>

	^ ((Dictionary new) add: (#definition->#category); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->7590); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'721fdf05-d8ca-6e46-bc6c-1aecc986357b'); add: (#iconCode->'nil'); add: (#next->#'eba5c8db-4efe-ba48-ba4f-2832757fb3b7'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)