*VivideDynamicAnalysis-steps
stepeba5c8db4efeba48ba4f2832757fb3b7
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsAsStrings); add: (#class->ViQueryGroupSortStep); add: (#properties->((Dictionary new) add: (#priority->7600); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'eba5c8db-4efe-ba48-ba4f-2832757fb3b7'); add: (#iconCode->'nil'); add: (#next->#'7f914c3c-d3b3-b842-8d35-f3bb800204ed'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)