*VivideDynamicAnalysis-steps
step42245e2f1770c94eba6900b9639175ea
	<step>

	^ ((Dictionary new) add: (#definition->#'0fedea78-7d66-bb4e-a5b8-bd879bbe632e'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->7490); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'42245e2f-1770-c94e-ba69-00b9639175ea'); add: (#iconCode->'UiFugueIcons tickSmallIcon'); add: (#next->#'2dbb58bf-d8e3-5042-9cea-67d04d421a76'); add: (#viewDefinition->#treeView); add: (#label->'Unbox test reference'); yourself)