*VivideDynamicAnalysis-steps
stepf8b5fb28df0fbd43ada0ff10766c6525
	<step>

	^ ((Dictionary new) add: (#definition->#'aad01ad6-66cc-6a46-a75b-494db5e535a2'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->7540); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'f8b5fb28-df0f-bd43-ada0-ff10766c6525'); add: (#iconCode->'UiFugueIcons nodeDesignIcon'); add: (#next->#'21dd5fb9-540d-2342-9fb7-ba050f698df1'); add: (#viewDefinition->#treeView); add: (#label->'Call tree diff'); yourself)