*VivideDynamicAnalysis-steps
step43d875f3d68f1f4a84ee33a07e273173
	<step>

	^ ((Dictionary new) add: (#definition->#'006246aa-ae7d-744a-9b29-fc1e299697e9'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->8230); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#'728402d7-f870-e743-8d2a-abf2353efba1'); yourself)); add: (#id->#'43d875f3-d68f-1f4a-84ee-33a07e273173'); add: (#iconCode->'nil'); add: (#next->#'5d303f1e-740e-ab43-b722-999fad485b78'); add: (#viewDefinition->#treeView); add: (#label->'Involved Types'); yourself)