*VivideDynamicAnalysis-steps
step289182021fd18c48b5b6c362bb139d75
	<step>

	^ ((Dictionary new) add: (#definition->#'fa585967-f2b4-bf43-9b5e-cc34c15d0e26'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->7790); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'28918202-1fd1-8c48-b5b6-c362bb139d75'); add: (#iconCode->'nil'); add: (#next->#'760c51c1-0741-7849-b214-5752b6a50e6c'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)