*VivideDynamicAnalysis-steps
stepef19175482524a4b939de0064dc27d22
	<step>

	^ ((Dictionary new) add: (#definition->#'b799fc21-f5b2-ed4a-b6fc-286da12d5cfe'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->8290); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#defaultProperties); yourself)); add: (#id->#'ef191754-8252-4a4b-939d-e0064dc27d22'); add: (#iconCode->'nil'); add: (#next->#'dec99f79-4067-7d4a-908a-6f813cb2e1e3'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)