*VivideDynamicAnalysis-steps
stepcab8a6029fe84d4d8d896832b7160afc
	<step>

	^ ((Dictionary new) add: (#definition->#origin); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->8060); add: (#headerText->'Argument'); yourself)); add: (#id->#'cab8a602-9fe8-4d4d-8d89-6832b7160afc'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)