*VivideDynamicAnalysis-steps
step67805379bff50843a86fdcff0bae7e89
	<step>

	^ ((Dictionary new) add: (#definition->#'e5a158fc-4fce-744c-9e71-88ab69885332'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->8040); add: (#headerText->'Second'); yourself)); add: (#id->#'67805379-bff5-0843-a86f-dcff0bae7e89'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)