*VivideDynamicAnalysis-steps
stepc9b6b489576ff54682e6f0c47e2b68e5
	<step>

	^ ((Dictionary new) add: (#definition->#iconAndLabel); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->7940); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#headerText->'Object'); yourself)); add: (#id->#'c9b6b489-576f-f546-82e6-f0c47e2b68e5'); add: (#iconCode->'nil'); add: (#next->#'89a90aa2-ea6a-0945-9947-281d976c0cfe'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)