*VivideDynamicAnalysis-steps
step59d5b87f176fef4faad8cb319a56ee07
	<step>

	^ ((Dictionary new) add: (#definition->#'ce53bd10-c48f-1d4c-a918-e91396c77f97'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->8100); add: (#headerText->'First'); yourself)); add: (#id->#'59d5b87f-176f-ef4f-aad8-cb319a56ee07'); add: (#iconCode->'nil'); add: (#next->#'3dc18042-e4df-da4b-bf58-1a1eb2e97877'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)