*VivideDynamicAnalysis-steps
step5fb5aa19edf2264d979c4a7832b053a8
	<step>

	^ ((Dictionary new) add: (#definition->#'59e41aec-0017-3e4e-9859-ac773a00bd98'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->8030); add: (#headerText->'First'); yourself)); add: (#id->#'5fb5aa19-edf2-264d-979c-4a7832b053a8'); add: (#iconCode->'nil'); add: (#next->#'67805379-bff5-0843-a86f-dcff0bae7e89'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)