*VivideDynamicAnalysis-steps
stepa78e03de0c7942478b8dc868a10730dc
	<step>

	^ ((Dictionary new) add: (#definition->#'d1a31df6-69aa-9f42-9638-bf514aade0ae'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->7930); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'a78e03de-0c79-4247-8b8d-c868a10730dc'); add: (#iconCode->'nil'); add: (#next->#'75531e0e-0723-2a40-a804-0a3afd0e8022'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)