*VivideDynamicAnalysis-steps
step1fe280d2538c874db3c00bf139a1e563
	<step>

	^ ((Dictionary new) add: (#definition->#'d5507f59-b8a8-df48-a51e-e7b096a9c283'); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->7510); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'1fe280d2-538c-874d-b3c0-0bf139a1e563'); add: (#iconCode->'nil'); add: (#next->#'c9b6b489-576f-f546-82e6-f0c47e2b68e5'); add: (#viewDefinition->#treeView); add: (#label->'Return object'); yourself)