*VivideDynamicAnalysis-steps
stepfe9b70c7cf2ec946aafad74236abbefb
	<step>

	^ ((Dictionary new) add: (#definition->#origin); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->7970); add: (#headerText->'Class'); yourself)); add: (#id->#'fe9b70c7-cf2e-c946-aafa-d74236abbefb'); add: (#iconCode->'nil'); add: (#next->#'58da325f-1e89-d343-be51-269a21907435'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)