*VivideDynamicAnalysis-steps
step40b75576ee1ac24bbaa19d80570ca673
	<step>

	^ ((Dictionary new) add: (#definition->#'4e7debd7-1c4e-a84d-be1c-a6f9fdd5fb40'); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->8280); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#copyOfStep->#'d9634b11-bde6-1a40-a0b4-7be880afc37a'); yourself)); add: (#id->#'40b75576-ee1a-c24b-baa1-9d80570ca673'); add: (#iconCode->'nil'); add: (#next->nil); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)