*VivideDynamicAnalysis-steps
stepdae9ff605974f64793252bfdd7ca6acf
	<step>

	^ ((Dictionary new) add: (#definition->#iconAndLabel); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->8050); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#headerText->'Object'); yourself)); add: (#id->#'dae9ff60-5974-f647-9325-2bfdd7ca6acf'); add: (#iconCode->'nil'); add: (#next->#'cab8a602-9fe8-4d4d-8d89-6832b7160afc'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)