*VivideDynamicAnalysis-steps
step760c51c107417849b2145752b6a50e6c
	<step>

	^ ((Dictionary new) add: (#definition->#iconAndLabel); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->7800); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#headerText->'Object'); yourself)); add: (#id->#'760c51c1-0741-7849-b214-5752b6a50e6c'); add: (#iconCode->'nil'); add: (#next->#'16ea7910-df6d-5a47-a6b8-51a0830d8be9'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)