*VivideDynamicAnalysis-steps
step771b4c83b8e5fa4fbd838e8072d2955a
	<step>

	^ ((Dictionary new) add: (#definition->#iconAndLabel); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->8070); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#headerText->'Object'); yourself)); add: (#id->#'771b4c83-b8e5-fa4f-bd83-8e8072d2955a'); add: (#iconCode->'nil'); add: (#next->#'5dce5e7f-f912-784c-b661-65bc08172e33'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)