*VivideDynamicAnalysis-steps
step44e5aa237528a14c9d0c8cb0326b4c78
	<step>

	^ ((Dictionary new) add: (#definition->#compareObjectsByName); add: (#class->ViQuerySortStep); add: (#properties->((Dictionary new) add: (#priority->7580); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'44e5aa23-7528-a14c-9d0c-8cb0326b4c78'); add: (#iconCode->'nil'); add: (#next->#'721fdf05-d8ca-6e46-bc6c-1aecc986357b'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)