*VivideDynamicAnalysis-steps
step5495652887edcd44a7d2d194d5a20d4f
	<step>

	^ ((Dictionary new) add: (#definition->#'d0c0c27f-b5e8-6044-a8fd-b4dd96ca9d5a'); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->8320); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'8 January 2014 1:48:17 pm'); yourself)); add: (#id->#'54956528-87ed-cd44-a7d2-d194d5a20d4f'); add: (#iconCode->'nil'); add: (#next->#'bd58e1b7-57dc-ce4e-b027-cf3140c36229'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)