*VivideDynamicAnalysis-steps
step2dbb58bfd8e350429cea67d04d421a76
	<step>

	^ ((Dictionary new) add: (#definition->#iconAndLabel); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#priority->8000); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#headerText->'Object'); yourself)); add: (#id->#'2dbb58bf-d8e3-5042-9cea-67d04d421a76'); add: (#iconCode->'nil'); add: (#next->#'a39e0f73-0309-9a41-a620-4f20812c45da'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)