*VivideDynamicAnalysis-steps
stepb2b95c668cd6bd4081bce870efd9fd00
	<step>

	^ ((Dictionary new) add: (#definition->#copyToContext); add: (#class->ViQueryTransformStep); add: (#properties->((Dictionary new) add: (#priority->7570); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'b2b95c66-8cd6-bd40-81bc-e870efd9fd00'); add: (#iconCode->'nil'); add: (#next->#'44e5aa23-7528-a14c-9d0c-8cb0326b4c78'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)