*VivideDynamicAnalysis-steps
step6a40861e709a9749a977b4dc093bd03e
	<step>

	^ ((Dictionary new) add: (#definition->#origin); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->8180); add: (#headerText->'Origin'); yourself)); add: (#id->#'6a40861e-709a-9749-a977-b4dc093bd03e'); add: (#iconCode->'nil'); add: (#next->#'c1ab82f9-fdc6-7d44-8631-bd0d8510fe63'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)