*VivideDynamicAnalysis-steps
step34877119e7a1ad418369d0e1c10011de
	<step>

	^ ((Dictionary new) add: (#definition->#'38fd8240-6a18-ea4c-90e5-32012d5c5ae3'); add: (#class->ViQueryGroupStep); add: (#properties->((Dictionary new) add: (#priority->8160); add: (#creationAuthor->'mt'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); yourself)); add: (#id->#'34877119-e7a1-ad41-8369-d0e1c10011de'); add: (#iconCode->'nil'); add: (#next->#'540db69a-fba0-ed48-b17f-47fdbf37abc5'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)