*VivideDynamicAnalysis-steps
step16ea7910df6d5a47a6b851a0830d8be9
	<step>

	^ ((Dictionary new) add: (#definition->#origin); add: (#class->ViQueryPropertyStep); add: (#properties->((Dictionary new) add: (#labelColor->'#AAAAAA'); add: (#creationTimeStamp->'28 August 2013 2:37:39 pm'); add: (#creationAuthor->'mt'); add: (#priority->7810); add: (#headerText->'Origin'); yourself)); add: (#id->#'16ea7910-df6d-5a47-a6b8-51a0830d8be9'); add: (#iconCode->'nil'); add: (#next->#'4732568c-aec4-4d43-a0fd-3ad53b6f9b85'); add: (#viewDefinition->#treeView); add: (#label->nil); yourself)